Changes made in installation file to make the download
ColoredCow/portal pull request #1007
Opened 2021-09-18 13:21 UTC by gautam071

Targets #1006 

### Description
This PR contains the changes made in the installation file to make the installation process easier 

### Checklist:

- [ ] I have performed a self-review of my code.

2021-09-20 17:01 UTC, GauravGusain98 reviewed
Looks good. @kuldeep3 Could you also review it once.

2021-09-21 12:58 UTC, GauravGusain98 requested changes
Looks good, just some minor changes required. Please make these changes.

2021-09-21 12:58 UTC, GauravGusain98 commented on docs/installation.md
> +10. Then it shows a login page. To get login credentials go to your database or got to this link `http://localhost/phpmyadmin/index.php`. Search for users table you can find the login credentials.
This would be better. As the password is encrypted, therefore you should provide the password also.
```suggestion
10. Login to the portal using the newly created user in the database. Go to `http://localhost/phpmyadmin/index.php` and search for the `users` table and you can find the user email in it. The default password to log in is `12345678`.
```

2021-09-21 13:46 UTC, gautam071 commented on docs/installation.md
> +10. Then it shows a login page. To get login credentials go to your database or got to this link `http://localhost/phpmyadmin/index.php`. Search for users table you can find the login credentials.
Okay lat me change to it

2021-09-21 16:07 UTC, GauravGusain98 requested changes
Can you please correct the indentation of the 7th point i.e the migration command.
![image](https://user-images.githubusercontent.com/54376313/134206639-a7b48abb-849b-4d01-be13-c7ed30a1b8bf.png)

2021-09-22 09:29 UTC, GauravGusain98 commented
@gautam071 Please resolve the merge conflict

2021-09-22 09:50 UTC, gautam071 commented
> @gautam071 Please resolve the merge conflict

Resolved!

2021-09-22 09:55 UTC, GauravGusain98 requested changes
Please check the comments.

2021-09-22 09:55 UTC, GauravGusain98 commented on docs/installation.md
> +10. Login to the portal using the newly created user in the database. Go to `http://localhost/phpmyadmin/index.php` and search for the `users` table and you can find the user email in it. The default
I think you added this point in the wrong place. Because the creation of a virtual host for MAMP should not be inside this point.

2021-09-22 09:59 UTC, gautam071 commented on docs/installation.md
> +10. Login to the portal using the newly created user in the database. Go to `http://localhost/phpmyadmin/index.php` and search for the `users` table and you can find the user email in it. The default
Done

2021-09-22 18:27 UTC, GauravGusain98 approved these changes
Looks good

2021-09-22 18:32 UTC, merged