Additions in Installation Guidelines
ColoredCow/portal pull request #1030
Opened 2021-09-24 18:22 UTC by vipulgoyal006

Targets #{1016}

I have added 3 new guidelines which are essential for the installation of the portal project
These additions help to counter a list of specific errors which one might encounter while installing the project

### Checklist:

- [ ~] I have performed a self-review of my own code.

2021-09-25 04:13 UTC, GauravGusain98 requested changes
Please check the comments and make the required changes

2021-09-25 04:13 UTC, GauravGusain98 commented on docs/installation.md
> +
Don't add extra line spaces and indentations.
```suggestion
        ```apacheconf
             <Directory>
             #...
                 Order allow,deny
                 Allow from all
             </Directory>
        ```
    Change To-
        ```apacheconf
             <Directory>
             #...
                  Require all granted
             </Directory>
        ```    
```

2021-09-25 04:13 UTC, GauravGusain98 commented on docs/installation.md
> +           - Restart MAMP. Next, open this url in your browser: http://portal.test
Correct indentation of these points as well. Currently, there is one level of extra indentation.

2021-09-25 04:13 UTC, GauravGusain98 commented on docs/installation.md
> +           - And the go to vhost file in the terminal
```suggestion
           - Go to vhost file in the terminal 
```

2021-09-25 14:42 UTC, rathorevaibhav reviewed
Some minor edits needed @vipulgoyal006 Else looking good!

2021-09-25 14:42 UTC, rathorevaibhav commented on docs/installation.md
> +   Note- Make sure that the 'php.ini' file in XAMPP/WAMP has this code uncommented/written
```suggestion
   **Note:** Make sure that the 'php.ini' file in XAMPP/WAMP has this code uncommented/written
```

2021-09-25 14:42 UTC, rathorevaibhav commented on docs/installation.md
> +        Note- Use the default values for MySQL database in .env file
Please keep the same level of indentation:
```suggestion
    **Note:** Use the default values for MySQL database in `.env` file
```

2021-09-25 14:42 UTC, rathorevaibhav commented on docs/installation.md
> +          - Go to vhost file in the terminal
```suggestion
          - Open the `vhost` file in the terminal 
```

2021-09-25 14:42 UTC, rathorevaibhav commented on docs/installation.md
> +          - In case you face a 403 Forbidden error in Apache, try this instead-
```suggestion
          - In case you see a 403 Forbidden error in Apache, try this instead:
```

2021-09-25 14:42 UTC, rathorevaibhav commented on docs/installation.md
> +                Allow from all
```suggestion
                # some code above
                Order allow,deny
                Allow from all
```

2021-09-25 14:42 UTC, rathorevaibhav commented on docs/installation.md
> +            Change To-
```suggestion
            Change to:
```

2021-09-25 14:42 UTC, rathorevaibhav commented on docs/installation.md
> +                 Require all granted
```suggestion
            #...
                 Require all granted
```
```suggestion
                 # some code above
                 Require all granted
```

2021-09-28 15:49 UTC, P4NK4J reviewed
Left some comments, please check.

2021-09-28 15:49 UTC, P4NK4J commented on docs/installation.md
> +
Can we remove extra spacing from here ?

2021-09-28 15:49 UTC, P4NK4J commented on docs/installation.md
> +           ```
Why do we need to change the rule from `allow from all` to `require all granted`, is there any specific reason? since they both are equivalent. If this is required to change due to the apache version difference, let me know your thoughts on mentioning that specifically. (Probably for apache 2.4 they have this rule changed).

2021-09-29 04:00 UTC, vipulgoyal006 commented on docs/installation.md
> +           ```
The access control configuration changed in 2.4, and old configurations aren't compatible without some changes. 

If your old config was Allow from all (no IP addresses blocked from accessing the service), then Require all granted is the new functional equivilent.

Without this, it throws a 404 Forbidden error. Thus the change is required.

2021-09-29 04:01 UTC, vipulgoyal006 commented on docs/installation.md
> +
Done!

2021-09-29 04:20 UTC, P4NK4J commented on docs/installation.md
> +           ```
Yeah, I agree the change is required, should we explicitly mention that `in case you are using apache v2.4+, you might want to change the rule from allowing from all to require all granted, otherwise the server would throw 403 forbidden error`?

2021-09-29 04:22 UTC, P4NK4J commented
@GauravGusain98 @rathorevaibhav , Since you guys had requested a change on this PR, it would require approval from your end as well. Please take a look and let's get it merged if everything looks fine.

2021-09-29 04:23 UTC, vipulgoyal006 commented on docs/installation.md
> +           ```
Yes, I agree we can go with this message. I will update the text to specifially mention Apache 2.4+ for better clarity.

2021-09-29 06:13 UTC, vipulgoyal006 commented on docs/installation.md
> +           ```
Made the changes as asked!

2021-09-29 07:04 UTC, P4NK4J approved these changes
Looks good to me, will also require approval from @GauravGusain98 and @rathorevaibhav .

2021-09-29 07:51 UTC, GauravGusain98 approved these changes
Looks fine

2021-09-29 07:51 UTC, merged