Bugfix nonvalidation for previous start_date in update form
ColoredCow/portal pull request #1032
Opened 2021-09-25 03:10 UTC by srivastava-jyoti

Targets #{1019}

Checklist:

- [ ]  The date validation should not be when there is already an existing date.

- [ ]  The validation should only work if the job opportunity didn't have a date before.

2021-09-25 05:22 UTC, srivastava-jyoti commented
@ColoredCow/team-portal-reviewers in this task I have used novalidate attribute in the form to disable javascript validation which was previously working for the previous start_date. So, there is no warning coming for start_date and the form is updating now without throwing any error. And it is still throwing errors for required parts.

For the 2nd part of this task, since the previous dates are already disabled. Do I need to enable form validation for this part??

2021-09-25 14:34 UTC, rathorevaibhav commented on resources/views/hr/job/edit.blade.php
> +    <form action="{{ $formAction }}" method="POST" id="update-form" novalidate>
As per my understanding from [this link](https://www.w3schools.com/tags/att_form_novalidate.asp), this attribute disables validation for the whole form. Can you double-check for other required fields like title & description if you remove the entries in these fields and try submitting the form, then the form should throw validation error.

2021-09-25 14:55 UTC, srivastava-jyoti commented on resources/views/hr/job/edit.blade.php
> +    <form action="{{ $formAction }}" method="POST" id="update-form" novalidate>
@rathorevaibhav the required fields are still throwing errors when I try to submit the form.
![Screenshot (112)](https://user-images.githubusercontent.com/79009032/134775799-73ab291a-97e2-4bf6-8ad0-7e55539a4dc3.png)

2021-09-25 15:00 UTC, rathorevaibhav commented on resources/views/hr/job/edit.blade.php
> +    <form action="{{ $formAction }}" method="POST" id="update-form" novalidate>
@srivastava-jyoti no the frontend validation should work for them like before. The form shouldn't submit at all.

The screenshot you shared is because of backend validation that runs after you've submitted.

2021-09-25 15:00 UTC, rathorevaibhav commented on resources/views/hr/job/edit.blade.php
> +    <form action="{{ $formAction }}" method="POST" id="update-form" novalidate>
It seems the novalidate attribute is disabling the frontend validation for the form.

2021-09-25 15:19 UTC, srivastava-jyoti commented on resources/views/hr/job/edit.blade.php
> +    <form action="{{ $formAction }}" method="POST" id="update-form" novalidate>
Yeah, novalidate attribute is disabling frontend-validation. I will correct this.

2021-09-28 15:43 UTC, P4NK4J approved these changes
looks good.

2021-09-28 15:44 UTC, P4NK4J commented
@rathorevaibhav I see this PR has review requested from your end as well, please take a look and if everything looks fine, please proceed with merging it.

2021-09-28 16:18 UTC, GauravGusain98 requested changes
Please check the comments

2021-09-28 16:18 UTC, GauravGusain98 commented on resources/views/hr/job/edit.blade.php
> +                        <input type="date" class="form-control" id="jobs_start_date" name="start_date" min="{{ old('start_date', $job->start_date) }}" value="{{ old('start_date', $job->start_date) }}
Why you changed the name of id. `jobs_start_date` is not making sense as it is in a plural form which is incorrect as per the case.

2021-09-28 16:18 UTC, GauravGusain98 commented on resources/views/hr/job/edit.blade.php
> +                        <input type="date" class="form-control" id="jobs_start_date" name="start_date" min="{{ old('start_date', $job->start_date) }}" value="{{ old('start_date', $job->start_date) }}
If id is not being used anywhere then you can remove it.

2021-09-29 03:13 UTC, srivastava-jyoti commented on resources/views/hr/job/edit.blade.php
> +                        <input type="date" class="form-control" id="jobs_start_date" name="start_date" min="{{ old('start_date', $job->start_date) }}" value="{{ old('start_date', $job->start_date) }}
I am deleting this pr and will work on #1020

2021-09-29 03:13 UTC, closed without merging