updated-installation-guidelines
ColoredCow/portal pull request #1034
Opened 2021-09-25 05:44 UTC by carrisunrio

Targets #{1028}

### Description
Changes made to the installation guidelines as required to increase the readability and effective usage of the guidelines

### Checklist:

- [ ✔] I have performed a self-review of my own code.

2021-09-25 14:28 UTC, rathorevaibhav requested changes
@carrisunrio some minor edits and questions.

Also, the file `package-lock.json` is not relevant for this task. Can you remove it from the PR?

2021-09-25 14:28 UTC, rathorevaibhav commented on docs/installation.md
> +   git clone git clone https://github.com/coloredcow/portal
```suggestion
   git clone https://github.com/coloredcow/portal
```

2021-09-25 14:28 UTC, rathorevaibhav commented on docs/installation.md
> +Before you start following the guidelines, make sure to go through the [prerequisites](./docs/prerequisites.md) to get started.
```suggestion
Before you start following the guidelines, make sure to go through the [prerequisites guide](./docs/prerequisites.md) to install the required tools and packages on your machine.
```

2021-09-25 14:28 UTC, rathorevaibhav commented on docs/installation.md
> +    - For MAMP(Mac OS): `/Application/MAMP/htdocs/`
```suggestion
1. Navigate to the right diretory where your project will be locally saved
    - For WAMP: 
        ```sh
        cd C:\wamp64\www\
        ```
    - For XAMPP: 
        ```sh
        cd C:/xampp/htdocs/
        ```
    - For MAMP(Mac OS): 
        ```sh
        cd /Application/MAMP/htdocs/
        ```
```

2021-09-25 14:28 UTC, rathorevaibhav commented on docs/installation.md
> +    - For MAMP(Mac OS): `/Application/MAMP/htdocs/`
Also, what's the difference between backslash `\` and forward slash `/` here in the directory names? Do they work differently?

2021-09-25 14:28 UTC, rathorevaibhav commented on docs/installation.md
> +4. Copy and paste `.env.example` file as `.env` file there itself
```suggestion
4. Make a copy of the `.env.example` file in the same directory and save it as `.env`:
```

2021-09-25 14:28 UTC, rathorevaibhav commented on docs/installation.md
> +5. Run the following command to add a key:
```suggestion
5. Run the following command to add the Laravel application key:
```

2021-09-25 14:28 UTC, rathorevaibhav commented on docs/installation.md
> +     Make sure you have a database created in your local server. For more info check this [link](https://www.youtube.com/watch?v=k9yJR_ZJbvI&ab_channel=1BestCsharpblog)(skip to 0:21) for creating an
```
2. Database configurations
    - Create a database in your local server. Check out [this link](URL) and skip to 0:21.
    - Configure your Laravel app with the right DB settings. Check out [this link](URL). Relevant parts are 2:00-2:42 and 4:20-5:40.
```

2021-09-25 14:28 UTC, rathorevaibhav commented on docs/installation.md
> +    DB_DATABASE=homestead
```suggestion
    DB_DATABASE=portal
```

2021-09-25 14:28 UTC, rathorevaibhav commented on docs/installation.md
> +    3. For MAMP(Mac OS):
```suggestion
    3. For MAMP(macOS):
```

2021-09-26 03:48 UTC, carrisunrio commented on docs/installation.md
> +    - For MAMP(Mac OS): `/Application/MAMP/htdocs/`
For MAMP, it is different, rest of the two OSes use a similar kind of slash i.e; backslash \

2021-09-29 08:23 UTC, rathorevaibhav commented
@carrisunrio there are some merge conflicts in here. Can you resolve them so that the team can do the final review?

2021-09-29 08:27 UTC, rathorevaibhav approved these changes

2021-09-29 08:29 UTC, merged