Updated the page the prerequisites and for Mac OS
ColoredCow/portal pull request #1036
Opened 2021-09-25 14:02 UTC by gautam071

Targets #981 

### Description
Pre-Requisites for the macOS and the updated the learning and pre-requisites 

### Checklist:

- [ ] I have performed a self-review of my own code.

2021-09-25 14:18 UTC, rathorevaibhav requested changes

2021-09-25 14:18 UTC, rathorevaibhav commented on docs/prerequisites.md
> -### 8. Automated Testing :computer:
why removed this?

2021-09-25 14:18 UTC, rathorevaibhav commented on docs/prerequisites.md
> +    Linux and MacOS comes pre installed
```suggestion
Git should come pre-installed in Linux and macOS. For Windows, use [this link](https://git-scm.com/download/win).
```

2021-09-25 14:18 UTC, rathorevaibhav commented on docs/prerequisites.md
> +    # git version 2.33.0.windows.2
```suggestion
```sh
git --version
# git version 2.33.0.windows.2
```

2021-09-25 14:18 UTC, rathorevaibhav commented on docs/prerequisites.md
> +### 2. PHP,MYSQL,APACHE :running:
```suggestion
### 2. PHP, MySQL, Apache :running:
```

2021-09-25 14:18 UTC, rathorevaibhav commented on docs/prerequisites.md
> +Portal uses PHP v7.3 or v7.4 is needed. You can install it with the following ways:
```suggestion
Portal uses PHP v7.4. You can install it using one of the following ways:
```

2021-09-25 14:18 UTC, rathorevaibhav commented on docs/prerequisites.md
> +3. MAMP (Windows and MacOS)
```suggestion
3. MAMP (macOS)
```

2021-09-25 14:18 UTC, rathorevaibhav commented on docs/prerequisites.md
> +      #Zend Engine v3.4.0, Copyright (c) Zend Technologies
```suggestion
```sh
php -v
# output should be something like
# PHP 7.4.21 (cli) (built: Aug  5 2021 15:34:00) ( NTS )
```

2021-09-25 14:18 UTC, rathorevaibhav commented on docs/prerequisites.md
> +For (Windows, Ubuntu, MacOS)
```suggestion
For (Windows, Ubuntu, macOS)
```

2021-09-25 14:37 UTC, rathorevaibhav requested changes

2021-09-25 14:37 UTC, rathorevaibhav commented on docs/prerequisites.md
> +### 6.Automated Testing :computer:
remove

2021-09-28 15:42 UTC, P4NK4J reviewed
Left some comments, else looks good.

2021-09-28 15:42 UTC, P4NK4J commented on docs/prerequisites.md
> +# git version 2.33.0.windows.2
Can we add a line `output should be something like this` ?

2021-09-28 15:42 UTC, P4NK4J commented on docs/prerequisites.md
> -### 8. Automated Testing :computer:
@gautam071 I see this comment is unresolved, please check

2021-09-28 15:53 UTC, gautam071 commented on docs/prerequisites.md
> +# git version 2.33.0.windows.2
Okay

2021-09-29 08:15 UTC, rathorevaibhav approved these changes

2021-09-29 08:15 UTC, merged