Corrected validation for start & end date
ColoredCow/portal pull request #1046
Opened 2021-09-29 09:08 UTC by srivastava-jyoti

Targets #{1020}

 Checklist:

- [ ] Removed Unused class
- [ ] Added min and max values to start & end dates

2021-09-30 04:10 UTC, GauravGusain98 requested changes
@srivastava-jyoti Please check the comments and make the required changes.

2021-09-30 04:10 UTC, GauravGusain98 commented on resources/views/hr/job/edit.blade.php
> +                        <input type="date" class="form-control" min ="{{ old('start_date', $job->start_date) }}" value="{{ old('end_date', $job->end_date) }}">
I don't think these changes cover all the requirements of the issue. For example the below case is not covered here:
- [ ] A user can select a start date and end date in the past given the below checks pass.
    - [ ] If start date is selected first, the user should not be able to select end date before start date.
    - [ ] If end date is selected first, the user should not be able to select start date after end date.

2021-09-30 04:10 UTC, GauravGusain98 commented on resources/views/hr/job/edit.blade.php
> +                        <input type="date" class="form-control" min ="{{ old('start_date', $job->start_date) }}" value="{{ old('end_date', $job->end_date) }}">
I think Javascript will be required to handle this case.

2021-09-30 08:14 UTC, srivastava-jyoti commented on resources/views/hr/job/edit.blade.php
> +                        <input type="date" class="form-control" min ="{{ old('start_date', $job->start_date) }}" value="{{ old('end_date', $job->end_date) }}">
Okay, understood I have to make this dynamic. Suppose if the user selects end date first, then start_date should not show dates after that. Same thing goes to start date. But, I have a small query what should be the minimum value of end date then??

2021-10-01 15:23 UTC, rathorevaibhav commented on resources/views/hr/job/edit.blade.php
> +                        <input type="date" class="form-control" min ="{{ old('start_date', $job->start_date) }}" value="{{ old('end_date', $job->end_date) }}">
@srivastava-jyoti answering your questions:
1. There's no limit on the start date and end date when both are blank and any one of them is selected first. It can be a past date, today, or in the future. The validation should only be applied to the other field after one of these fields has been selected.
2. Add dynamic validations in both create and edit

2021-10-01 15:32 UTC, srivastava-jyoti commented on resources/views/hr/job/edit.blade.php
> +                        <input type="date" class="form-control" min ="{{ old('start_date', $job->start_date) }}" value="{{ old('end_date', $job->end_date) }}">
@rathorevaibhav Okay, understood.

2021-10-05 04:10 UTC, GauravGusain98 requested changes
Looks good. Just some minor fixes required.

2021-10-05 04:10 UTC, GauravGusain98 commented on resources/js/app.js
> +});
```suggestion

$("#job_start_date").on("change", function() {
 	let startDate = $("#job_start_date").val();
	$("#job_end_date").attr("min", startDate);
});

$("#job_end_date").on("change", function() {
	let endDate = $("#job_end_date").val();
	$("#job_start_date").attr("max", endDate);
});
```

2021-10-05 07:12 UTC, GauravGusain98 approved these changes
Looks good

2021-10-05 07:12 UTC, merged