added conversion_rate column in invoice table and created field for s…
ColoredCow/portal pull request #1050
Opened 2021-10-01 07:15 UTC by bharatsingh100

…ame in edit invoice view

Targets #814

### Description
Added the conversion rate field in the edit invoice page for international payments and added the column for the same in invoice table 

### Checklist:

- [ ] I have performed a self-review of my own code.

2021-10-01 14:06 UTC, GauravGusain98 requested changes
Left some feedbacks. Please correct them. And whenever you are requesting for review remember to add `ready for review` label to the PR.

2021-10-01 14:06 UTC, GauravGusain98 commented on Modules/User/Resources/views/layouts/master.blade.php
> +<script src="{{ asset('/js/user.js') }}" defer></script>
Is there any specific reason you have used `asset` here? We use `mix` for importing the js and CSS. Please try to use `mix` here.

2021-10-01 15:19 UTC, rathorevaibhav commented on database/migrations/2021_09_29_190515_add_conversion_rate_column_in_invoices_table.php
> +<?php
@bharatsingh100 you can create a migration inside a module using:
```php
php artisan module:make-migration nameOfMigration moduleName
```

2021-10-01 17:14 UTC, bharatsingh100 commented on Modules/Invoice/Resources/views/subviews/edit/invoice-details.blade.php
> +                <div class="form-group" v-if="this.client.type != 'indian'">
ok i will make the changes

2021-10-01 17:15 UTC, bharatsingh100 commented on database/migrations/2021_09_29_190515_add_conversion_rate_column_in_invoices_table.php
> +<?php
sure. thanks

2021-10-01 17:15 UTC, bharatsingh100 commented on database/migrations/2021_09_29_190515_add_conversion_rate_column_in_invoices_table.php
> +            $table->text('conversion_rate')->nullable()->after('conversion_rate_diff');
ok will change this too

2021-10-01 17:17 UTC, bharatsingh100 commented on Modules/User/Resources/views/layouts/master.blade.php
> +<script src="{{ asset('/js/user.js') }}" defer></script>
i was not able to load user management page on my local setup, so anmol told me to change this to asset , then it worked.

2021-10-01 17:19 UTC, bharatsingh100 commented on Modules/User/Resources/views/layouts/master.blade.php
> +<script src="{{ asset('/js/user.js') }}" defer></script>
i will change it to mix again

2021-10-01 17:36 UTC, bharatsingh100 commented on database/migrations/2021_09_29_190515_add_conversion_rate_column_in_invoices_table.php
> +            $table->text('conversion_rate')->nullable()->after('conversion_rate_diff');
conversion_rate_diff is of type "text" too, should i change it too

2021-10-02 05:15 UTC, bharatsingh100 commented on Modules/Invoice/Resources/views/subviews/edit/invoice-details.blade.php
> +                <div class="form-group" v-if="this.client.type != 'indian'">
there are other places where it is hard coded too, should i change those too

2021-10-02 12:49 UTC, GauravGusain98 approved these changes
Looks good on code.

2021-10-02 12:49 UTC, merged