Project and Client seeder implemented
ColoredCow/portal pull request #1051
Opened 2021-10-01 07:42 UTC by vipulgoyal006

Targets #{932}

### Description
Implemented Seeders for Clients table and Projects table for easy use.

### Checklist:

- [~] I have performed a self-review of my own code.

2021-10-01 12:25 UTC, GauravGusain98 requested changes
Please check the comments

2021-10-01 12:25 UTC, GauravGusain98 commented on database/Seeders/ClientsTableSeeder.php
> +                'id' => 1,
If we have already an id with value 1 then this will not work.

2021-10-01 12:25 UTC, GauravGusain98 commented on database/Seeders/ClientsTableSeeder.php
> +                'status' => 'Not Active',
Please confirm if the value for the status column is `Not Active` or `not-active`.

2021-10-01 12:25 UTC, GauravGusain98 commented on database/Seeders/ClientsTableSeeder.php
> +                'id' => 2,
You should not add id column as it is added by default

2021-10-01 12:25 UTC, GauravGusain98 commented on database/Seeders/ClientsTableSeeder.php
> +class ClientsTableSeeder extends Seeder
You should create this seeder in the Client Module. Also, we have a factory for clients, So you can use the factory to seed the clients in the database. 

To know how factories and seeders work you can use laravel documentation. Also, the factory and project concept is implemented in the project seeder in the Project Module. You can take reference from there as well.

2021-10-01 12:25 UTC, GauravGusain98 commented on database/Seeders/ProjectsTableSeeder.php
> +class ProjectsTableSeeder extends Seeder
There is already a seeder and factory created for projects. I don't think it is required.

2021-10-04 07:51 UTC, vipulgoyal006 commented on database/Seeders/ClientsTableSeeder.php
> +                'status' => 'Not Active',
The options were Active and Inactive. I have set 'Inactive' as deafult now.

2021-10-04 07:52 UTC, vipulgoyal006 commented on database/Seeders/ClientsTableSeeder.php
> +                'id' => 1,
As suggested, I have removed id from the Clientfactory.

2021-10-04 07:52 UTC, vipulgoyal006 commented on database/Seeders/ClientsTableSeeder.php
> +                'id' => 2,
Done!

2021-10-04 07:52 UTC, vipulgoyal006 commented on database/Seeders/ProjectsTableSeeder.php
> +class ProjectsTableSeeder extends Seeder
Implemented only ClientsSeeder now

2021-10-04 07:53 UTC, vipulgoyal006 commented on database/Seeders/ClientsTableSeeder.php
> +class ClientsTableSeeder extends Seeder
Used a factory to implement this seeder

2021-10-05 04:04 UTC, GauravGusain98 requested changes
Looks good. Just some minor fixes.

2021-10-05 04:04 UTC, GauravGusain98 commented on Modules/Client/Database/Factories/ClientFactory.php
> +            'status' => 'Inactive',
```suggestion
            'status' => 'inactive',
```

2021-10-05 04:04 UTC, GauravGusain98 commented on Modules/Client/Database/Factories/ClientFactory.php
> +            'has_departments' => rand(0, 1),
You can let them be 0.

2021-10-05 04:04 UTC, GauravGusain98 commented on Modules/Client/Database/Factories/ClientFactory.php
> +            'pincode' => null,
These fields are nullable so you can just remove them. You can keep the address field though.

2021-10-05 05:04 UTC, vipulgoyal006 commented on Modules/Client/Database/Factories/ClientFactory.php
> +            'pincode' => null,
Implemented the suggestion!

2021-10-05 05:04 UTC, vipulgoyal006 commented on Modules/Client/Database/Factories/ClientFactory.php
> +            'has_departments' => rand(0, 1),
Done

2021-10-05 05:04 UTC, vipulgoyal006 commented on Modules/Client/Database/Factories/ClientFactory.php
> +            'status' => 'Inactive',
Done

2021-10-05 07:23 UTC, GauravGusain98 requested changes
Please check the comments

2021-10-05 07:23 UTC, GauravGusain98 commented on Modules/Client/Database/Factories/ClientFactory.php
> +            'has_departments' => '0',
These 2 columns are of int type
```suggestion
            'is_channel_partner' => 0,
            'has_departments' => 0,
```

2021-10-05 11:53 UTC, GauravGusain98 approved these changes
looks good now.

2021-10-05 11:53 UTC, merged