Feature/invoices permissions module
ColoredCow/portal pull request #1152
Opened 2021-10-29 11:34 UTC by srivastava-jyoti

Targets #1111

2021-11-05 09:16 UTC, GauravGusain98 requested changes
Please check the comments.

2021-11-05 09:16 UTC, GauravGusain98 commented on resources/views/layouts/navbar.blade.php
> +                @can('finance_reports.view')
Is there any reason you removed `invoice.view` permission check and added this permission.

2021-11-07 05:32 UTC, srivastava-jyoti commented on resources/views/layouts/navbar.blade.php
> +                @can('finance_reports.view')
It was done by mistake.

2021-11-09 15:34 UTC, GauravGusain98 approved these changes
Looks good on code.

2021-11-09 15:35 UTC, merged