Added whatsapp optin field
ColoredCow/portal pull request #1156
Opened 2021-11-01 05:41 UTC by srivastava-jyoti

Targets #1113

2021-11-09 10:56 UTC, GauravGusain98 requested changes
Please check the comments.

2021-11-09 10:56 UTC, GauravGusain98 commented on database/migrations/2021_10_30_084041_update_hr_applicants_table.php
> +            $table->time('wa_optin_at')->after('phone')->nullable();
This should be timestamp instead of time. It is also given in the issue description.

2021-11-09 10:56 UTC, GauravGusain98 commented on Modules/HR/Entities/Applicant.php
> +            'wa_optin_at' => isset($attr['wa_optin_at']) ? $attr['wa_optin_at'] : null,
you need to add the current date as well along with the time in this column.

2021-11-11 10:55 UTC, GauravGusain98 commented
@rathorevaibhav Can we provide the date and time field for the WhatsApp option as shown below? And can the date be other than the current data?
![image](https://user-images.githubusercontent.com/54376313/141286203-4599e46a-6686-4195-8ba1-f4af222847ee.png)

2021-11-11 11:12 UTC, rathorevaibhav commented
@GauravGusain98 
1. The task was to capture the timestamp of opt-in, no? I didn't get your question
2. Yes, it can be some other date as well (we may require it specially when doing bulk upload)

2021-11-11 12:36 UTC, GauravGusain98 commented
> @GauravGusain98
> 
> 1. The task was to capture the timestamp of opt-in, no? I didn't get your question
> 2. Yes, it can be some other date as well (we may require it specially when doing bulk upload)

1. Initially there was only a time field, So I thought we only need a time field in UI. 
2. Got it

2021-11-11 12:37 UTC, GauravGusain98 approved these changes
Looks good on code.

2021-11-11 12:38 UTC, merged