403 on projects.view on permission fail on projects
ColoredCow/portal pull request #1158
Opened 2021-11-01 12:39 UTC by balendurawat

Targets #1117

### Description

### Checklist:

- [ ] I have performed a self-review of my own code.

2021-11-02 06:25 UTC, GauravGusain98 commented
Please fix the failed checks.

2021-11-05 09:26 UTC, GauravGusain98 requested changes
Please check the comments.

2021-11-05 09:26 UTC, GauravGusain98 commented on Modules/Project/Http/Controllers/ProjectController.php
> +        }
This way is not recommended to solve this problem. Please try other ways like middlewares or policies.

2022-05-24 07:17 UTC, deepankar-sajwan commented
Pull request is closed as code is already merged through diferent code request

2022-05-24 07:17 UTC, closed without merging