Guideline for variable naming convention is done
ColoredCow/portal pull request #1160
Opened 2021-11-02 08:14 UTC by Ayush8923

Targets #1003

### Description

### Checklist:

- [ ] I have performed a self-review of my own code.

2021-11-02 09:13 UTC, GauravGusain98 requested changes
Please check the comments below:
- There is no formatting in the document. Everything is written in plain text. 
- The file should be inside the docs folder
- The link to this file should be added in the [development.md](https://github.com/ColoredCow/portal/blob/master/docs/development.md) file as `Variable Naming Convention in Employee Portal` under the section `Coding Guidelines and Conventions`.
- We don't need to add all the examples of how to access an element using id name, class, name etc. Only the variable names in the proper cases will work. And also there is no need to define what Camecase, Titlecase is.

2021-11-03 08:42 UTC, Ayush8923 reviewed
If you have changed according to the comment, please review it.

2021-11-05 09:23 UTC, GauravGusain98 requested changes
Minor suggestions. Please check.

2021-11-05 09:23 UTC, GauravGusain98 commented on docs/variable-naming-convention.md
> +idName - camelCase
```suggestion
class name - snake-case
id name - camelCase
```

2021-11-05 09:23 UTC, GauravGusain98 commented on docs/variable-naming-convention.md
> +idName - camelCase
```suggestion
class name - snake-case
id name - camelCase
```

2021-11-05 13:39 UTC, Ayush8923 commented
Some changes are done, please review it.

2021-11-09 15:52 UTC, GauravGusain98 requested changes
Please check the comment

2021-11-09 15:52 UTC, GauravGusain98 commented on docs/variable-naming-convention.md
> +id name - camelCase
It's not looking correctly in Display mode
![image](https://user-images.githubusercontent.com/54376313/140957622-ee186cb9-6f35-4cd1-9ddb-cf8adce54efc.png)


Please make the changes as provided below
```suggestion
### JavaScript:
- Class name - snake-case
- Id name - camelCase

### PHP:
- Variable name - camelCase
- Function name - camelCase
- Class name - TitleCase

### Blade:
- Variable name - camelCase
- Class name - snake-case
- Id name - camelCase
```

2021-11-11 04:11 UTC, GauravGusain98 approved these changes
Looks fine

2021-11-11 04:11 UTC, merged