non-req-fields
ColoredCow/portal pull request #1161
Opened 2021-11-02 14:24 UTC by suntwalriya

Targets #1159 

### Description

### Checklist:

- [ ] I have performed a self-review of my own code.

2021-11-03 07:04 UTC, GauravGusain98 reviewed
Looks good. But we also decided to update the Table structure as well. Without that this code will not work as expected.

2021-11-03 07:10 UTC, suntwalriya commented
@GauravGusain98 I did that in my local, and it is working fine on my local.

2021-11-03 08:40 UTC, GauravGusain98 commented
> @GauravGusain98 I did that in my local, and it is working fine on my local.

But we also need to change the structure of the production database. For that, we need the migration file changes. Please add that file in this PR.

2021-11-05 09:01 UTC, GauravGusain98 requested changes
Please check the comments.

2021-11-05 09:01 UTC, GauravGusain98 commented on Modules/Project/Database/Migrations/2021_09_09_082632_update_tables_for_effort_tracking.php
> +            $table->float('monthly_estimated_hours')->nullable()->after('total_estimated_hours');
We don't update an existing migration. If we want to change the table structure then we need to create a new migration for those changes. 

This is because the old migrations have already been executed and will not be executed again. So, if we update anything in the old migration then no changes will be reflected.

2021-11-05 14:18 UTC, suntwalriya commented on Modules/Project/Database/Migrations/2021_09_09_082632_update_tables_for_effort_tracking.php
> +            $table->float('monthly_estimated_hours')->nullable()->after('total_estimated_hours');
Done!

2021-11-09 10:59 UTC, GauravGusain98 requested changes
Please check the comments

2021-11-09 10:59 UTC, GauravGusain98 commented on Modules/Project/Database/Migrations/2021_11_05_105704_make_monthly_estimated_hours_nullable_on_projects_table.php
> +        Schema::dropIfExists('monthly_estimated_hours_nullable_on_projects');
You should not drop this column on rollback. Instead, change the column to not nullable.

2021-11-09 10:59 UTC, GauravGusain98 commented on Modules/Project/Database/Migrations/2021_11_05_105704_make_monthly_estimated_hours_nullable_on_projects_table.php
> +        Schema::create('monthly_estimated_hours_nullable_on_projects', function (Blueprint $table) {
```suggestion
        Schema::table('monthly_estimated_hours_nullable_on_projects', function (Blueprint $table) {
```

2021-11-11 12:39 UTC, GauravGusain98 commented
As per the discussion in the meeting, Please update the code changes. Updating the label to `reviewed`.

2021-11-11 12:46 UTC, suntwalriya commented
I made the discussed changes. Please check.

2021-11-12 12:53 UTC, GauravGusain98 approved these changes
Looks fine

2021-11-12 12:54 UTC, merged