Infrastructure Permissions
ColoredCow/portal pull request #1165
Opened 2021-11-08 09:22 UTC by srivastava-jyoti

Targets #1162

2021-11-09 15:42 UTC, GauravGusain98 requested changes
Please check the comments

2021-11-09 15:42 UTC, GauravGusain98 commented on Modules/Infrastructure/Resources/views/index.blade.php
> +        @include('errors.403')
This permission should not be handled inside the blade. You should check the permission on the backend.

We don't want the user to reach the blade file if he doesn't have permission.

2021-11-09 15:42 UTC, GauravGusain98 commented on Modules/Infrastructure/Resources/views/instances.blade.php
> +        @include('errors.403')
Same here

2021-11-09 15:42 UTC, GauravGusain98 commented on Modules/Infrastructure/Resources/views/index.blade.php
> +        @include('errors.403')
For this, we usually use `Policies` in Laravel. You can check it in the documentation.

2021-11-20 11:41 UTC, GauravGusain98 requested changes
minor feedbacks

2021-11-20 11:47 UTC, srivastava-jyoti commented on app/Providers/AuthServiceProvider.php
> -        'App\Models\Client' => 'App\Policies\ClientPolicy',
It was done by mistake.

2021-11-23 13:09 UTC, GauravGusain98 commented on Modules/Infrastructure/Resources/views/menu_header.blade.php
> +     </ul>
This tag is not aligned properly.

2021-11-23 13:11 UTC, GauravGusain98 requested changes
Minor feedbacks, else looks good.

2021-11-23 13:11 UTC, GauravGusain98 commented on Modules/Infrastructure/Resources/views/menu_header.blade.php
> +     </ul>
This tag is not aligned properly.

2021-11-23 13:11 UTC, GauravGusain98 commented on Modules/Infrastructure/Http/Controllers/InfrastructureController.php
> +
remove this extra line

2021-11-24 06:22 UTC, srivastava-jyoti commented on Modules/Infrastructure/Http/Controllers/InfrastructureController.php
> +
PHP cs check is not getting passed on removing the extra line.

2021-11-24 11:32 UTC, GauravGusain98 approved these changes
looks fine

2021-11-24 11:33 UTC, merged