converted total amounts to words
ColoredCow/portal pull request #1176
Opened 2021-11-17 17:26 UTC by suntwalriya

Targets #1164 
Displayed the amount in words at bottom of all amount fields in red, so that it is easily readable.

### Description

### Checklist:

- [ ] I have performed a self-review of my own code.

2021-11-20 10:48 UTC, GauravGusain98 requested changes
Some suggestions, please check

2021-11-20 10:48 UTC, GauravGusain98 commented on Modules/Invoice/Resources/views/subviews/create/invoice-details.blade.php
> +    var res = "";
The variable names are not proper. Update them so that anyone reading it could easily understand it. Also remove the comments as they will be not required once you update the variable name.

2021-11-20 10:48 UTC, GauravGusain98 commented on Modules/Invoice/Resources/views/subviews/create/invoice-details.blade.php
> +    var res = "";
There are other places where the variable names are not proper. Please correct them as well.

2021-11-20 10:48 UTC, GauravGusain98 commented on Modules/Invoice/Resources/views/subviews/create/invoice-details.blade.php
> +
Please check the formatting once in all places. There should be no extra lines.

2021-11-20 16:17 UTC, suntwalriya commented on Modules/Invoice/Resources/views/subviews/create/invoice-details.blade.php
> +
Done.

2021-11-20 16:17 UTC, suntwalriya commented on Modules/Invoice/Resources/views/subviews/create/invoice-details.blade.php
> +    var res = "";
Done.

2021-11-24 11:39 UTC, GauravGusain98 requested changes
Please check the comments.

2021-11-24 11:39 UTC, GauravGusain98 commented on resources/js/app.js
> +        (result == "" ? "" : " ") + convert_number(thousand) + " THOUSAND";
move this to one line

2021-11-24 11:39 UTC, GauravGusain98 commented on resources/js/app.js
> +	var curr = getcurrency();
This is more meaningful
```suggestion
	var currency = getcurrency();
```

2021-11-24 11:39 UTC, GauravGusain98 commented on resources/js/app.js
> +		var f_text = "";
What does this `f_text` variable do? You can give it a meaningful name.

2021-11-24 11:39 UTC, GauravGusain98 commented on resources/js/app.js
> +		var f_text = "";
Also correct it in other places

2021-11-24 11:39 UTC, GauravGusain98 commented on resources/js/app.js
> +function frac(f) {
what is `f`? Please give it a meaningful name.

2021-11-24 11:39 UTC, GauravGusain98 commented on Modules/Invoice/Resources/views/subviews/create/invoice-details.blade.php
> +        amt: function (){
```suggestion
        amt: function () {
```

2021-11-29 11:40 UTC, GauravGusain98 requested changes
Please check the comments

2021-11-29 11:40 UTC, GauravGusain98 commented on resources/js/app.js
> +   * Finance - Invoices module JS code
Every Module has its own app.js where we write all the js code related to that module. 
Please move all the js code related to the invoice module to the app.js inside the Invoice module

2021-11-29 11:40 UTC, GauravGusain98 commented on resources/js/app.js
> +   * Finance - Invoices module JS code
- Also, define the helper function at the end of the file, after the `document.ready()` function.
- The `document.ready()` function should be at the beginning. 
- In one js file, we usually use only one `document.ready ()` function, and all the code is written inside it. The

2021-11-29 11:40 UTC, GauravGusain98 commented on resources/js/app.js
> +   * Finance - Invoices module JS code
Once you have moved the code. You need to import that js file also in your blade file.

2021-11-29 11:40 UTC, GauravGusain98 commented on Modules/Invoice/Resources/views/subviews/create/invoice-details.blade.php
> +<script src="{{ mix('js/app.js') }}"></script>
- Try not to include js file in a resource blade file.
- In every Module, we have a master.blade file. Which is imported in every blade file that we create. 
- In master.blade file we usually included the js and scss file. Refer to master.blade file of Appointment slot module to see how to include js and scss file in the Module.

2021-11-29 15:57 UTC, suntwalriya commented on resources/js/app.js
> +   * Finance - Invoices module JS code
but the app.js inside the invoice module is an empty file, should i still add it there?

2021-11-29 16:43 UTC, GauravGusain98 commented on resources/js/app.js
> +   * Finance - Invoices module JS code
Yes

2021-11-29 16:47 UTC, suntwalriya commented on resources/js/app.js
> +   * Finance - Invoices module JS code
done

2021-11-29 16:49 UTC, suntwalriya commented on Modules/Invoice/Resources/views/subviews/create/invoice-details.blade.php
> +<script src="{{ mix('js/app.js') }}"></script>
done

2021-12-02 11:49 UTC, GauravGusain98 commented on Modules/Invoice/Resources/views/layouts/master.blade.php
> +<script src="{{ mix('js/app.js') }}"></script>
I think it should be invoice.js. Please check the naming in other modules.

2021-12-02 11:51 UTC, GauravGusain98 requested changes
Please check the comments. Also, the code is not working. Please test it once you are making the PR.

2021-12-03 07:38 UTC, suntwalriya commented on Modules/Invoice/Resources/views/layouts/master.blade.php
> +<script src="{{ mix('js/app.js') }}"></script>
It was working in my local. Do I need to test it on uat as well? If yes, can you please tell me how should I do that?

2021-12-04 08:17 UTC, suntwalriya commented
The working needs to be still checked, I am making a commit in order to save my work here.

2021-12-10 09:38 UTC, GauravGusain98 approved these changes
Looks good.

2021-12-10 09:38 UTC, merged