Feature/icons correction
ColoredCow/portal pull request #1190
Opened 2021-11-23 00:02 UTC by srivastava-jyoti

2021-11-24 11:31 UTC, GauravGusain98 commented on resources/views/hr/application/index.blade.php
> +<div class="menu_wrapper">
The indentation is not correct. Please fix it.

2021-11-24 11:31 UTC, GauravGusain98 requested changes
Minor changes. Please have a look

2021-11-24 11:31 UTC, GauravGusain98 commented on resources/views/hr/application/index.blade.php
> +<div class="menu_wrapper">
The indentation is not correct. Please fix it.

2021-11-29 11:42 UTC, GauravGusain98 commented
@srivastava-jyoti Please fix the merge conflicts and also write the description in the PR.

2021-11-30 09:29 UTC, srivastava-jyoti commented
> @srivastava-jyoti Please fix the merge conflicts and also write the description in the PR.

@GauravGusain98 there was no issue created for this. It is a fix for the icons on the application page.

2021-11-30 10:51 UTC, GauravGusain98 approved these changes
Looks fine

2021-11-30 10:51 UTC, merged