1194-Phase-1-Project-details-page is done
ColoredCow/portal pull request #1213
Opened 2021-12-03 09:58 UTC by Ayush8923

Targets #1194

### Description

### Checklist:

- [ ] I have performed a self-review of my own code.

2021-12-06 04:47 UTC, P4NK4J requested changes
@Ayush8923 Let's use the `show` blade for the project details. The route can be changed to `project.show`  `(/{project}/show)` and make changes to controller function accordingly.

2021-12-07 04:53 UTC, P4NK4J requested changes
@Ayush8923  Left some comments, please check. Also, some of the CI checks have not been passed, please make sure they are passed first and then assign for review.

2021-12-07 04:53 UTC, P4NK4J commented on Modules/Project/Resources/views/project-detail.blade.php
> +    <br> <h4 clss="c-pointer" class="d-inline-block" v-on:click="counter += 1">{{ $project->name }}</h4>
@Ayush8923 Let's remove this blade if not required.

2021-12-07 04:53 UTC, P4NK4J commented on Modules/Project/Resources/views/show.blade.php
> +            <form action="{{ route('project.store') }}" method="POST" id="form_project">
@Ayush8923 As of now, we don't need the project details inside a form, we will be having edit blade separately for the same. The form can be removed and replaced by a heading only.

2021-12-07 16:43 UTC, Ayush8923 commented
Currently in my local system the page looks as in the screenshot.
![Screenshot (190)](https://user-images.githubusercontent.com/80516839/145069453-3d4749ce-c87d-4ee1-82e8-544b79611d54.png)

2021-12-08 06:56 UTC, P4NK4J reviewed
@Ayush8923  Left a comment, please check

2021-12-08 06:56 UTC, P4NK4J commented on Modules/Project/Resources/views/project-detail.blade.php
> +    <br> <h4 clss="c-pointer" class="d-inline-block" v-on:click="counter += 1">{{ $project->name }}</h4>
@Ayush8923 Please resolve the comments before assigning them for review. We can remove this blade if not required.

2021-12-09 08:50 UTC, GauravGusain98 requested changes
Please check the comments.

2021-12-09 08:50 UTC, GauravGusain98 commented on Modules/Project/Resources/views/show.blade.php
> +        <h4 clss="c-pointer" class="d-inline-block" v-on:click="counter += 1">{{ $project->name }}</h4>
```suggestion
        <h4 class="c-pointer d-inline-block" v-on:click="counter += 1">{{ $project->name }}</h4>
```

2021-12-09 08:50 UTC, GauravGusain98 commented on Modules/Project/Resources/views/show.blade.php
> +        <a  id="view_effort_sheet_badge" target="_self" href= "{{route('project.edit', $project )}}" class="btn btn-primary text-white ml-auto">{{ _('Edit') }}</a>
```suggestion
        <a id="view_effort_sheet_badge" target="_self" href= "{{route('project.edit', $project )}}" class="btn btn-primary text-white ml-auto">{{ _('Edit') }}</a>
```

2021-12-09 08:50 UTC, GauravGusain98 commented on Modules/Project/Resources/views/show.blade.php
> +    <div class="card mt-3" >
Where this tag is getting closed?

2021-12-10 09:11 UTC, GauravGusain98 commented
@Ayush8923 
Looks good. Just a minor fix is left. We also need to redirect the user to the project details page if he clicks on his project from the project card in the dashboard. Please update the URL here as well.
![image](https://user-images.githubusercontent.com/54376313/145548247-440c778a-515b-4fab-9a4d-67979eab6eb7.png)

2021-12-13 08:44 UTC, GauravGusain98 reviewed
Please check the comment

2021-12-13 08:44 UTC, GauravGusain98 commented on resources/js/components/Dashboard/UserDashboardProjects.vue
> +                                <a :href="'/projects/'+project.id+'/show/'">{{ project.name }}</a>
Can't we use route instead of hardcoding the URL? Similar to what we have done in this file `Modules/Project/Resources/views/index.blade.php`

2021-12-13 09:19 UTC, GauravGusain98 approved these changes
looks good

2021-12-13 09:30 UTC, Ayush8923 commented on resources/js/components/Dashboard/UserDashboardProjects.vue
> +                                <a :href="'/projects/'+project.id+'/show/'">{{ project.name }}</a>
We can't use route function in this case. We can only use hard-coding URL in this case.

2021-12-14 07:45 UTC, P4NK4J approved these changes
Looks good.

2021-12-14 07:46 UTC, merged