Send email of Invoices
ColoredCow/portal pull request #1219
Opened 2021-12-13 07:17 UTC by srivastava-jyoti

Targets #865

2021-12-15 07:18 UTC, P4NK4J commented
@srivastava-jyoti The PR contains some merge conflicts, please take a look and assign for review once the conflicts are resolved.

2022-01-04 11:57 UTC, GauravGusain98 requested changes
Please check the comments.

2022-01-04 11:57 UTC, GauravGusain98 commented on app/Http/Controllers/EmailInvoiceController.php
> +    public function handle()
The name of the function is very generic. Can you update it to something more specific?

2022-01-04 11:57 UTC, GauravGusain98 commented on Modules/Invoice/Resources/views/mail/invoices-list.blade.php
> +        <p><a href={{ route('invoice.index') }}> You can see more details here. </a></p>
Correct indentation.

2022-01-04 11:57 UTC, GauravGusain98 commented on Modules/Invoice/Resources/views/mail/invoices-list.blade.php
> +</div>
This div is extra

2022-01-04 11:57 UTC, GauravGusain98 commented on app/Http/Controllers/EmailInvoiceController.php
> +
We usually create a mail file to send a mail. You can take reference form [here](https://laravel.com/docs/8.x/mail#sending-mail)

2022-01-04 11:57 UTC, GauravGusain98 commented on app/Http/Controllers/EmailInvoiceController.php
> +
Please send the mail using the approach given in the link.

2022-01-04 11:57 UTC, GauravGusain98 commented on app/Http/Controllers/EmailInvoiceController.php
> +                $m->from('finance@coloredcow.com');
This should come from the config variable. Please confirm with Vaibhav, I think we store this email in .env also.  So you need to check the config variable that uses the env variable for this mail.

2022-08-09 12:21 UTC, closed without merging