Corrected Permissions Table seeding
ColoredCow/portal pull request #1224
Opened 2021-12-16 06:47 UTC by srivastava-jyoti

Issue: On running ` php artisan db:seed --class=PermissionsTableSeeder` previous values were again seeded in the database.

2021-12-16 09:23 UTC, GauravGusain98 requested changes
Please check the comments

2021-12-16 09:23 UTC, GauravGusain98 commented on database/Seeders/PermissionsTableSeeder.php
> +        \DB::table('permissions')->truncate();
I think let's not solve this issue in this manner. AS if we delete the permissions and again create new ones (the permission will have new ids) then the roles cannot find the permissions to which they are mapped as we have deleted those permissions and now the id to which roles are mapped does not exists.

For this we can use the `createOrUpdate()` function of laravel ORM. 
[Reference documentation](https://laravel.com/docs/8.x/eloquent#upserts)

2021-12-16 09:23 UTC, GauravGusain98 commented on database/Seeders/PermissionsTableSeeder.php
> +        \DB::table('permissions')->truncate();
Also then we have to remove the delete statements from the seeder.

2021-12-16 10:56 UTC, srivastava-jyoti commented on database/Seeders/PermissionsTableSeeder.php
> +        \DB::table('permissions')->truncate();
Okay, I'll correct this.

2021-12-17 07:49 UTC, GauravGusain98 commented on database/Seeders/PermissionsTableSeeder.php
>          \DB::table('permissions')->delete();
This is not required. Please remove this line

2021-12-17 07:50 UTC, GauravGusain98 commented on database/Seeders/PermissionsTableSeeder.php
>          Artisan::call('permission:cache-reset');
Same here. This is also not required.

2021-12-17 13:27 UTC, GauravGusain98 approved these changes
Looks good.

2021-12-17 13:27 UTC, merged