Required database for the CRM
ColoredCow/portal pull request #1236
Opened 2021-12-18 12:24 UTC by gautam071

Targets #1208 

### Description
-  Link and Create the required databases

### Checklist:

- [ ] I have performed a self-review of my own code.

2021-12-24 07:04 UTC, GauravGusain98 requested changes
Please check the comments and test the functionality once after making the changes.

2021-12-24 07:04 UTC, GauravGusain98 commented on app/Services/CRMServices.php
> +        ];
```suggestion
        return [
            'clients' =>  Client::all(),
            'prospectes' => Prospect::all(),
        ];
```

2021-12-24 07:04 UTC, GauravGusain98 commented on database/migrations/2021_12_18_110152_create_clients_crm_details_table.php
> +        });
```suggestion
        Schema::create('client_crm_details', function (Blueprint $table) {
            $table->id();
            $table->unsignedBigInteger('client_id');
            $table->foreign('client_id')->references('id')->on('clients');
            $table->unsignedBigInteger('prospect_id')->nullable();
            $table->foreign('prospect_id')->references('id')->on('prospects');
            $table->unsignedBigInteger('client_address_id')->nullable();
            $table->foreign('client_address_id')->references('id')->on('client_addresses');
            $table->unsignedBigInteger('client_contact_person_id')->nullable();
            $table->foreign('client_contact_person_id')->references('id')->on('client_contact_persons');
            $table->timestamp('last_connected');
            $table->string('last_interaction')->nullable();
            $table->string('next_step')->nullable();
            $table->string('source')->nullable();
            $table->string('status');
            $table->string('notes')->nullable();
            $table->timestamps();
        });
```

2021-12-24 07:04 UTC, GauravGusain98 commented on database/migrations/2021_12_18_110152_create_clients_crm_details_table.php
> +        Schema::dropIfExists('clients_crm_details');
```suggestion
        Schema::dropIfExists('client_crm_details');
```

2021-12-24 07:04 UTC, GauravGusain98 commented on resources/views/crm/index.blade.php
> +                <a class="card-body no-transition" href="https://portal.test/crm/<?php echo $client->name; ?>">
Create route for the url.

2021-12-24 07:04 UTC, GauravGusain98 commented on resources/views/crm/index.blade.php
> +                <a class="card-body no-transition" href="https://portal.test/crm/<?php echo $client->name; ?>">
Also don't use php echo in laravel we have `{{ }}` in laravel

2021-12-24 07:04 UTC, GauravGusain98 commented on resources/views/crm/index.blade.php
> +            	   <br><h2 class="text-center"><?php echo $client->name; ?></h2><br>
Here as well

2021-12-24 07:04 UTC, GauravGusain98 commented on app/Http/Controllers/CRM/CRMController.php
>  class CRMController extends Controller
```suggestion
class CrmController extends Controller
```

2021-12-24 07:04 UTC, GauravGusain98 commented on app/Http/Controllers/CRM/CRMController.php
>  class CRMController extends Controller
Also correct it at other places where it is being used.

2021-12-25 11:04 UTC, GauravGusain98 requested changes
Please check the comments

2021-12-25 11:04 UTC, GauravGusain98 commented on resources/views/crm/index.blade.php
> +                <a class="card-body no-transition">
Do we not need the href here? If not then its ok.

2021-12-27 05:53 UTC, gautam071 commented on resources/views/crm/index.blade.php
> +            	   <br><h2 class="text-center">{{ $prospectes->name; }}</h2><br>
The whole UI part is changed in the Next PR so no use in this

2021-12-27 05:53 UTC, gautam071 commented on resources/views/crm/index.blade.php
> +                <a class="card-body no-transition">
The whole UI part is changed in the Next PR so no use in this

2021-12-28 03:29 UTC, GauravGusain98 approved these changes
Looks fine

2021-12-28 03:29 UTC, merged