reports table is created.
ColoredCow/portal pull request #1239
Opened 2021-12-27 16:53 UTC by Ayush8923

Targets #1234 

### Description

### Checklist:

- [ ] I have performed a self-review of my own code.

2021-12-29 09:36 UTC, GauravGusain98 commented on Modules/SalesAutomation/Database/Migrations/2021_12_27_175619_reports_table.php
> +class ReportsTable extends Migration
The the file name and class name should be create_reports_table

2021-12-29 09:37 UTC, GauravGusain98 requested changes
Please check the comments.

2021-12-29 09:37 UTC, GauravGusain98 commented on Modules/SalesAutomation/Database/Migrations/2021_12_27_175619_reports_table.php
> +            $table->text('description');
This is a nullable field

2022-01-13 18:15 UTC, Ayush8923 commented
I am creating another pull request instead. That's why I am closing this PR.

2022-01-13 18:16 UTC, closed without merging