1234 create a reports table to store report url and other data
ColoredCow/portal pull request #1242
Opened 2022-01-14 17:53 UTC by Ayush8923

Targets #1234 

### Description

### Checklist:

- [ ] I have performed a self-review of my own code.

2022-01-17 12:05 UTC, GauravGusain98 requested changes
Minor feedback, please fix it.

2022-01-17 12:05 UTC, GauravGusain98 commented on Modules/SalesAutomation/Database/Migrations/2021_12_27_175619_create_reports_table.php
> +            $table->string('name')->nullable();
This field is a required field

2022-01-18 18:03 UTC, Ayush8923 commented on Modules/SalesAutomation/Database/Migrations/2021_12_27_175619_create_reports_table.php
> +            $table->string('name')->nullable();
u can tell how can i show the required field.Can you give some ideas.
Because as far as I think we can write the requested field as Nullable (False).

2022-01-23 04:51 UTC, GauravGusain98 requested changes
Please check the comments

2022-01-23 04:51 UTC, GauravGusain98 commented on Modules/SalesAutomation/Database/Migrations/2021_12_27_175619_create_reports_table.php
> +            $table->string('name')->nullable(false)->change();
```suggestion
            $table->string('name');
```

2022-01-23 04:51 UTC, GauravGusain98 commented on Modules/SalesAutomation/Database/Migrations/2021_12_27_175619_create_reports_table.php
> +            $table->string('type')->nullable(false)->change();
```suggestion
            $table->string('url');
            $table->string('type');
```

2022-01-23 04:51 UTC, GauravGusain98 commented on Modules/SalesAutomation/Database/Migrations/2021_12_27_175619_create_reports_table.php
> +            $table->string('name')->nullable(false)->change();
By default the field is `required`

2022-01-23 06:26 UTC, Ayush8923 commented on Modules/SalesAutomation/Database/Migrations/2021_12_27_175619_create_reports_table.php
> +            $table->string('type')->nullable(false)->change();
@GauravGusain98, I want to ask you that whatever the URL and type is, as per the database schema is also a required field, so they have to provide the required field as well.

2022-01-23 10:08 UTC, GauravGusain98 commented on Modules/SalesAutomation/Database/Migrations/2021_12_27_175619_create_reports_table.php
> +            $table->string('type')->nullable(false)->change();
If you remove the nullable(), then the field will be consider as required by default

2022-01-29 05:28 UTC, GauravGusain98 requested changes
Please check the comments

2022-01-29 05:28 UTC, GauravGusain98 commented on Modules/SalesAutomation/Database/Migrations/2021_12_27_175619_create_reports_table.php
> +            $table->string('name')->default(false);
First thing, the default value of the string cannot be false. Also In the schema default value is not mentioned anywhere so please don't add default values.

2022-01-29 05:28 UTC, GauravGusain98 commented on Modules/SalesAutomation/Database/Migrations/2021_12_27_175619_create_reports_table.php
> +            $table->string('type')->default(false);
same here

2022-01-30 09:29 UTC, GauravGusain98 approved these changes
looks fine now

2022-01-30 09:29 UTC, merged