Phase 2: Project details page is done.
ColoredCow/portal pull request #1243
Opened 2022-01-21 17:41 UTC by Ayush8923

Targets #1195 

### Description

### Checklist:

- [ ] I have performed a self-review of my own code.

2022-01-22 11:29 UTC, Ayush8923 commented
Project details page on my screen looks like this.
![Screenshot (25)](https://user-images.githubusercontent.com/80516839/150636617-408112c6-99ba-4b70-92ab-ed42f036d902.png)

2022-01-23 04:59 UTC, GauravGusain98 commented
@Ayush8923 
The UI is not looking correct to me. Fix it.

Also, the FTE that we want to show in the UI should be of the project not for each user. You can check if there is any such function available in the project model. If not then you need to create one for calculating the overall FTE of a project i.e (Sum of all team member effort / Total expected effort till that day of the month).

2022-01-23 05:00 UTC, GauravGusain98 requested changes
Please check the comment

2022-01-30 09:47 UTC, GauravGusain98 requested changes
Please check the comments.

2022-01-30 09:47 UTC, GauravGusain98 commented on Modules/Project/Services/ProjectService.php
> +    }
This function should only return the values that are needed to show the project data. It should not do other operations like calculating FTE, for that we should create another function

2022-01-30 09:47 UTC, GauravGusain98 commented on Modules/Project/Services/ProjectService.php
> +    }
Let's do one thing, create `getFteAttribute()` function inside the `project` module so that we can get the FTE by using project objects like `$project->fte`

2022-01-30 09:47 UTC, GauravGusain98 commented on Modules/Project/Services/ProjectService.php
> +    public function getTeamMembersDetails($teamMembers)
Lets move this as well in project model

2022-04-02 11:31 UTC, rathorevaibhav approved these changes

2022-04-02 11:32 UTC, merged