Added the fix for creating the multiple entries with single click
ColoredCow/portal pull request #1373
Opened 2022-05-07 13:52 UTC by gautam071

Targets #1351

### Description

- When a user clicks on the create button on the invoice page multiple times. The record is saved multiple times. Added the fix for this issue in this PR.
### Checklist:

- [x] I have performed a self-review of my own code.

2022-05-10 04:53 UTC, dsajwan2020 commented
Hi @GauravGusain98 can you please do the code review for this PR

2022-05-10 07:58 UTC, GauravGusain98 approved these changes
Looks fine.

2022-05-10 08:02 UTC, GauravGusain98 requested changes
Just a minor change requested.

2022-05-10 08:02 UTC, GauravGusain98 commented on Modules/Client/Resources/views/subviews/create-client-details.blade.php
> +</script>
I see that this functionality is being used at multiple place. can we make a general function for this .You may include that function inside the main app.js file and then you just need to call that function in the button.

2022-05-14 09:40 UTC, GauravGusain98 approved these changes
Looks fine

2022-05-14 09:41 UTC, merged