Invoice details listing page is created
ColoredCow/portal pull request #1389
Opened 2022-05-11 10:12 UTC by Ayush8923

Targets #1324

2022-05-11 11:20 UTC, GauravGusain98 requested changes
Please check the comments.

2022-05-11 11:20 UTC, GauravGusain98 commented on Modules/Invoice/Resources/views/invoice-details-listing.blade.php
> +        <h4 class="mb-1 pb-1">              Invoice Details</h4>
```suggestion
        <h4 class="mb-1 pb-1">Invoice Details</h4>
```

2022-05-11 11:20 UTC, GauravGusain98 commented on Modules/Invoice/Routes/web.php
> +    Route::get('/invoice-details-listing', 'InvoiceController@invoiceDetails')->name('invoice.invoice-details');
```suggestion
    Route::get('/invoice-details-listing', 'InvoiceController@invoiceDetails')->name('invoice.details');
```

2022-05-11 11:20 UTC, GauravGusain98 commented on resources/views/layouts/navbar.blade.php
> +                    <a class="dropdown-item" href="{{ route('invoice.invoice-details') }}"> Invoice details listing</a>
```suggestion
                    <a class="dropdown-item" href="{{ route('invoice.details') }}">Invoice details listing</a>
```

2022-05-11 11:20 UTC, GauravGusain98 commented on Modules/Invoice/Resources/views/invoice-details-listing.blade.php
> +                        <td></td>
Why these columns empty?

2022-05-11 11:20 UTC, GauravGusain98 commented on Modules/Invoice/Resources/views/invoice-details-listing.blade.php
> +                        <td></td>
Please confirm if we need to fill these details or not?

2022-05-15 04:39 UTC, P4NK4J requested changes
Left some comments, please check.

2022-05-15 04:39 UTC, P4NK4J commented on Modules/Invoice/Exports/MonthlyReportExport.php
> +class MonthlyReportExport implements FromCollection, WithHeadings, ShouldAutoSize, WithTitle
Can we rename it to something more specific, let's say `MonthlyGSTTaxReportExport`. Let me know what you think

2022-05-15 04:39 UTC, P4NK4J commented on Modules/Invoice/Exports/MonthlyReportExport.php
> +        return 'Monthly invoice report';
Let's rename it here as well, `Monthly GST Tax Report`

2022-05-15 04:39 UTC, P4NK4J commented on Modules/Invoice/Resources/views/invoice-details-listing.blade.php
> +						<td>{{ $invoice->amount }}</td>
The taxable amount should be invoice amount excluding GST for Indian clients, please refer this issue #1340

2022-05-15 04:39 UTC, P4NK4J commented on Modules/Invoice/Resources/views/invoice-details-listing.blade.php
> +						<td>{{ ($invoice->currency == "INR") ? $sgst[$key] : '' }}</td>
IGST will be implemented when billing state is not Haryana for Indian clients, why USD is checked here ?
Also, CGST and SGST will be added if billing state is Haryana. Please make changes

2022-05-15 04:39 UTC, P4NK4J commented on Modules/Invoice/Routes/web.php
> +    Route::get('/monthly-report-export', 'InvoiceController@monthlyReportExport')->name('invoice.monthly-report-export');
Please provide specific names to the routes and functions here

2022-05-15 04:39 UTC, P4NK4J commented on Modules/Invoice/Services/InvoiceService.php
> +        return app(ClientServiceContract::class)->getAll();
What's the use of this ?

2022-05-15 04:39 UTC, P4NK4J commented on Modules/Invoice/Services/InvoiceService.php
> +    public function monthlyReportExport($filters)
The function name gives a very generic sense of monthly report, can we make it more specific in terms of GST tax report ?

2022-05-15 04:39 UTC, P4NK4J commented on Modules/Invoice/Services/InvoiceService.php
> +        $invoices = $this->formatMonthlyInvoicesForExportAll($invoices);
Please rename this function to something meaningful. Its less readable with the current name

2022-05-15 04:39 UTC, P4NK4J commented on Modules/Invoice/Services/InvoiceService.php
> +        return Excel::download(new MonthlyReportExport($invoices), 'MonthlyReportExport.xlsx');
Please rename the filename as well

2022-05-15 10:53 UTC, P4NK4J approved these changes

2022-05-16 05:07 UTC, GauravGusain98 approved these changes
Looks fine

2022-05-16 05:07 UTC, merged