Bugfix/1299/finance/invoice download with invoice number
ColoredCow/portal pull request #1422
Opened 2022-05-18 13:59 UTC by abhishekkhanduri

#{1299}

### Description
Invoice File download with invoice number in new tab.

2022-05-18 15:02 UTC, P4NK4J requested changes
Left some comments, please take a look

2022-05-18 15:02 UTC, P4NK4J commented on Modules/Invoice/Resources/views/edit.blade.php
> +$filename=basename($invoice_file_path);
How about `$filename=basename($invoice->file_path);` ?

2022-05-18 15:02 UTC, P4NK4J commented on package-lock.json
> -    "name": "portal",
Why we are removing this file ?

2022-05-19 12:08 UTC, P4NK4J commented
@abhishekkhanduri There are some comments left to resolve in your PR, please check and then assign for review. Also, post a response corresponding to the comments.

2022-05-19 12:13 UTC, abhishekkhanduri commented on Modules/Invoice/Resources/views/edit.blade.php
> +$filename=basename($invoice_file_path);
Yes this would be perfect.

2022-05-20 09:59 UTC, abhishekkhanduri commented on package-lock.json
> -    "name": "portal",
I have not made any changes in this file on my own.

2022-05-20 10:20 UTC, abhishekkhanduri commented on .husky/pre-commit
> -
This file will be created automatically when we runs npm install command.

2022-05-20 10:21 UTC, abhishekkhanduri commented on package-lock.json
> -    "name": "portal",
This file will be created automatically when we run install composer.

2022-05-20 11:36 UTC, P4NK4J approved these changes

2022-05-20 11:36 UTC, merged