enable save button
ColoredCow/portal pull request #1512
Opened 2022-06-04 12:48 UTC by JCArya

Targets #{1506}
Enable the save button if an error occurred while project details editing

2022-06-04 13:37 UTC, GauravGusain98 requested changes
Check the comments and make the changes as requested.

2022-06-04 13:37 UTC, GauravGusain98 commented on Modules/Project/Resources/views/edit.blade.php
>                      await axios.post('{{ route('project.update', $project) }}', formData)
This will make the enable button always enable, but we want to make it disable until we get response from backend and if any error comes then we want to make the button enable again.

2022-06-04 13:37 UTC, GauravGusain98 commented on Modules/Project/Resources/views/edit.blade.php
>                      await axios.post('{{ route('project.update', $project) }}', formData)
Also only keep the changes of this file and don't include the changes related to `composer.lock`, `package-lock.json`, `package.json`, `routes/web.php`

2022-06-06 13:02 UTC, JCArya commented
closeing this PR and some changes

2022-06-06 13:04 UTC, JCArya commented
closing this PR since it has a lot of unwanted changes.

2022-06-06 13:04 UTC, closed without merging