Added functionality to generate invoice
ColoredCow/portal pull request #1527
Opened 2022-06-07 18:32 UTC by GauravGusain98

### Description

### Checklist:

- [ ] I have performed a self-review of my own code.

2022-06-13 09:56 UTC, P4NK4J commented
@GauravGusain98 What we are trying to achieve in this PR, what were the requirements to create this PR, can you share it ?

2022-06-13 13:33 UTC, P4NK4J requested changes
Left some questions and comments, also one question, how will snappy work on other systems? Are we getting it checked into the package.json, or does it require separate installation?

2022-06-13 13:33 UTC, P4NK4J commented on Modules/Client/Entities/Client.php
> +        return $this->contactPersons()->where('type', 'billing-contact')->first();
Why do we need to use `first()` here?

2022-06-13 13:33 UTC, P4NK4J commented on Modules/Client/Entities/Client.php
> +        return round($this->getBillableAmountForTerm($month, $year, $projects) * ($this->country->initials == 'IN' ? config('invoice.tax-details.igst') : 0), 2);
Why `igst`, if a client is from the same state as the billing state, which GST would be used here ?

2022-06-13 13:33 UTC, P4NK4J commented on Modules/Client/Entities/Client.php
> +        return 0.00;
What's the use of this function ? Can't we make it a config variable if its returning a constant value ?

2022-06-13 13:33 UTC, P4NK4J commented on Modules/Client/Resources/views/subviews/edit-client-details.blade.php
> +                <div class=" col-md-5 mr-0 form-group">
```suggestion
                <div class="col-md-5 mr-0 form-group">
```

2022-06-13 13:33 UTC, P4NK4J commented on Modules/Invoice/Config/config.php
> +    ],
Can we put them in the .ENV file, since it seems to be confidential information, also the portal code is open source?

2022-06-13 13:33 UTC, P4NK4J commented on Modules/Invoice/Resources/views/create.blade.php
> +        <form method="POST" action="{{ route('invoice.store') }}" id="invoice_form" enctype="multipart/form-data">
Let's use camelCase for IDs here, there are certain areas which need to be refactored, but we can do them eventually

2022-06-13 13:33 UTC, P4NK4J commented on Modules/Invoice/Resources/views/render/international-hourly-billing-template.blade.php
> +                <td>{{round($project->getBillableHourForTerm($monthNumber, $year) * $client->billingDetails->service_rates, 2)}}</td>
Can this function be renamed to `getBillableHoursForTerm`, not a requested change, just a suggestion ?

2022-06-13 13:33 UTC, P4NK4J commented on Modules/Invoice/Services/InvoiceService.php
> +        $invoice_number = $client_type . sprintf('%03s', $client->client_id) . '-' . $project->client_project_id . '-' . sprintf('%06s', $invoice_sequence) . date('m', strtotime($sent_date)) . date('
can we put camelCase in variable name here as well ?

2022-06-13 13:33 UTC, P4NK4J commented on Modules/Invoice/Services/InvoiceService.php
> +        $billing_for = $data['billing_for'] ?? null;
camelCase variable name

2022-06-13 13:33 UTC, P4NK4J commented on Modules/Project/Entities/Project.php
> +    public function getBillableHourForTerm(int $monthNumber, int $year)
```suggestion
    public function getBillableHoursForTerm(int $monthNumber, int $year)
```

2022-06-13 14:14 UTC, GauravGusain98 commented on Modules/Invoice/Config/config.php
> +    ],
Cool

2022-06-13 14:23 UTC, kuldeep3 requested changes

2022-06-13 14:23 UTC, kuldeep3 commented on Modules/Client/Database/Migrations/2022_06_12_095905_add_primary_project_id_column_to_clients_table.php
> +            $table->unsignedBigInteger('primary_project_id')->nullable()->after('client_id');
What exactly are we storing in the `primary_project_id`. Is it the project_id corresponding to the client? If yes, can we remove `primary` from it..or it is for the case that there can be multiple project_ids for a client and out of all those, we are selecting and saving one? 💭

2022-06-13 14:23 UTC, kuldeep3 commented on Modules/Client/Http/Requests/ClientFormsRequest.php
> +            'primary_project_id' => 'nullable|string',
Does it need to be a string or integer? 🤔

2022-06-13 14:23 UTC, kuldeep3 commented on Modules/Invoice/Resources/views/render/international-hourly-billing-template.blade.php
> +                <td>{{round($project->getBillableHourForTerm($monthNumber, $year) * $client->billingDetails->service_rates, 2)}}</td>
Can we pass this whole as a variable from where the template is being loaded?

2022-06-13 16:54 UTC, GauravGusain98 commented on Modules/Client/Entities/Client.php
> +        return $this->contactPersons()->where('type', 'billing-contact')->first();
Aa, without first() the query will return a collection. So to get the first element from the collection we use first() as every client has only one billing connect person. If collection is empty it will return null.

2022-06-13 17:20 UTC, GauravGusain98 commented on Modules/Invoice/Resources/views/render/international-hourly-billing-template.blade.php
> +                <td>{{round($project->getBillableHourForTerm($monthNumber, $year) * $client->billingDetails->service_rates, 2)}}</td>
I think this is fine as we are just doing a simple calculation

2022-06-13 17:20 UTC, GauravGusain98 commented on Modules/Client/Http/Requests/ClientFormsRequest.php
> +            'primary_project_id' => 'nullable|string',
Corrected

2022-06-13 17:21 UTC, GauravGusain98 commented on Modules/Client/Database/Migrations/2022_06_12_095905_add_primary_project_id_column_to_clients_table.php
> +            $table->unsignedBigInteger('primary_project_id')->nullable()->after('client_id');
It is integer

2022-06-14 14:14 UTC, P4NK4J reviewed
Looks good, just one minor comment.

2022-06-14 14:14 UTC, P4NK4J commented on Modules/Invoice/Services/InvoiceService.php
> +            'currencyService' => $this->currencyService(),
Seems like this function is returning invoice data, instead of generating invoice. If that is the case, can we have a better name for this ?

2022-06-14 14:23 UTC, P4NK4J approved these changes
Looks good.

2022-06-14 17:53 UTC, kuldeep3 approved these changes

2022-06-14 17:56 UTC, merged