Invoice having payment overdue is marked as disputed.
ColoredCow/portal pull request #1544
Opened 2022-06-11 06:59 UTC by Ayush8923

Targets #1534

2022-06-11 07:31 UTC, GauravGusain98 requested changes
Please check the comment

2022-06-11 07:31 UTC, GauravGusain98 commented on Modules/Invoice/Resources/views/index.blade.php
> +                            @endif
Instead of using 2 condition for this, we can just modify the `shouldHighlighted()` function as it is handling the invoice status color

2022-06-12 09:36 UTC, GauravGusain98 approved these changes
Looks good

2022-06-12 09:37 UTC, GauravGusain98 commented
@Ayush8923 Please resolve the merge conflicts.

2022-06-12 10:23 UTC, Ayush8923 commented
> @Ayush8923 Please resolve the merge conflicts.

@GauravGusain98 Done!

2022-06-12 18:32 UTC, GauravGusain98 approved these changes
Looks good

2022-06-12 18:32 UTC, merged