WIP: Email Functionality
ColoredCow/portal pull request #1593
Opened 2022-06-20 16:10 UTC by gautam071

Targets #{ISSUE_ID}

### Description

### Checklist:

- [ ] I have performed a self-review of my own code.

2022-06-22 06:56 UTC, rathorevaibhav requested changes
@gautam071 several feedbacks and questions. Also I think a thorough self-review would have helped a multiple places. Please check.

2022-06-22 06:56 UTC, rathorevaibhav commented on Modules/Project/Contract/ProjectServiceContract.php
> +interface ProjectServiceContract
why is this file needed? what purpose is it solving?

2022-06-22 06:56 UTC, rathorevaibhav commented on Modules/Project/Console/ZeroEffortInProject.php
> +            Mail::send(new ZeroEffortInProjectMail($projectManager));
let's use queue please to send the emails.

2022-06-22 06:56 UTC, rathorevaibhav commented on Modules/Project/Resources/views/mail/zero-effort-team-member-list.blade.php
> +            <th scope="col">ProjectName</th>
```suggestion
            <th scope="col">Project Name</th>
```

2022-06-22 06:56 UTC, rathorevaibhav commented on Modules/Project/Resources/views/mail/zero-effort-team-member-list.blade.php
> +            @foreach ($projectManager['projects'] as $projects)
```suggestion
            @foreach ($projectManager['projects'] as $project)
```

2022-06-22 06:56 UTC, rathorevaibhav commented on Modules/Project/Services/ProjectService.php
> +        $user = User::get();
what's the difference between `User::get()` and `User::all()`?

2022-06-22 06:56 UTC, rathorevaibhav commented on Modules/Project/Services/ProjectService.php
> +        foreach ($user as $user) {
```suggestion
        foreach ($users as $user) {
```

2022-06-22 06:56 UTC, rathorevaibhav commented on Modules/Project/Services/ProjectService.php
> +    public function getZeroEffortTeamMemberInProject()
this returns a summed-up data for all projects and all team members. I think the name doesn't resemble same. Let's rename.

2022-06-22 06:56 UTC, rathorevaibhav commented on Modules/Project/Services/ProjectService.php
> +                        foreach ($project->teamMembers as $projectTeamMember) {
what's the use of this inner loop? You are already looping through `$project->teamMembers`

2022-06-22 06:56 UTC, rathorevaibhav commented on Modules/Project/Services/ProjectService.php
> +            $projects = $user->projects;
instead of all user projects, can we only get the projects where user is `project manager`?

2022-06-22 06:56 UTC, rathorevaibhav commented on Modules/Project/Console/ZeroEffortInProject.php
> +        $service = app(ProjectServiceContract::class);
what does this line do?

2022-06-22 06:56 UTC, rathorevaibhav commented on Modules/Project/Services/ProjectService.php
> +                    'projectManagerName' => $projectManagerName,
```suggestion
                    'name' => $projectManagerName,
```

2022-06-22 06:56 UTC, rathorevaibhav commented on Modules/Project/Services/ProjectService.php
> +                    'projectManagerEmail' =>$projectManagerEmail,
```suggestion
                    'email' =>$projectManagerEmail,
```

2022-06-22 07:08 UTC, gautam071 commented
@rathorevaibhav Let me do a thorough review before assigning you for review again.

2022-06-22 18:07 UTC, gautam071 commented on Modules/Project/Contract/ProjectServiceContract.php
> +interface ProjectServiceContract
The Laravel Contracts package provides a special way to extend Laravel core components explicitly and provides a stable API for developers to access the framework’s behaviour. [To know more ](https://www.addwebsolution.com/blog/understand-basic-laravel-contracts)

2022-06-23 02:52 UTC, gautam071 commented on Modules/Project/Console/ZeroEffortInProject.php
> +        $service = app(ProjectServiceContract::class);
This gets all the function from project service

2022-06-23 04:36 UTC, gautam071 commented on Modules/Project/Console/ZeroEffortInProject.php
> +            Mail::send(new ZeroEffortInProjectMail($projectManager));
I think we can't use both queue and command to send the email. We are using a command to trigger an email every Monday 9.00am

2022-06-23 08:26 UTC, rathorevaibhav commented on Modules/Project/Console/ZeroEffortInProject.php
> +            Mail::send(new ZeroEffortInProjectMail($projectManager));
I think we can. I don't think queue and command are mutually exclusive.

2022-06-23 08:35 UTC, rathorevaibhav requested changes
Several optimizations required, @gautam071 please check

2022-06-23 08:35 UTC, rathorevaibhav commented on Modules/Project/Emails/ZeroEffortInProjectMail.php
> +        ->subject('Some of your team members have zero effort in project!')
```suggestion
        ->subject('ColoredCow Portal - Some of your team members have zero effort in your projects!')
```

2022-06-23 08:35 UTC, rathorevaibhav commented on Modules/Project/Services/ProjectService.php
> +            $userProjectManager = ProjectTeamMember::where('team_member_id', $user->id)->where('designation', 'project_manager')->pluck('project_id');
is the variable naming right? I think it will give you an array of project ids not project manager.

2022-06-23 08:35 UTC, rathorevaibhav commented on Modules/Project/Services/ProjectService.php
> +            $userProjectManager = ProjectTeamMember::where('team_member_id', $user->id)->where('designation', 'project_manager')->pluck('project_id');
Also, if there is an empty array of projects, we should continue to next user immediately without any further processing.

2022-06-23 08:35 UTC, rathorevaibhav commented on Modules/Project/Services/ProjectService.php
> +                foreach ($project->teamMembers as $teamMember) {
`$project->teamMembers` must be pre-loaded

2022-06-23 08:35 UTC, rathorevaibhav commented on Modules/Project/Services/ProjectService.php
> +                        $projectManagerEmail = $user->email;
We don't need to look into other remaining project team members if we found one project team member with zero expected effort. We can exit the loop.

2022-06-23 08:35 UTC, rathorevaibhav commented on Modules/Project/Services/ProjectService.php
> +                        $projectManagerEmail = $user->email;
project manager name and email should not be inside inner most loop as they would remain same for every team member and project that's being iterated.

2022-06-23 13:29 UTC, rathorevaibhav requested changes
I see some implementation is not done correctly. Please check.

2022-06-23 13:29 UTC, rathorevaibhav commented on Modules/Project/Services/ProjectService.php
> +                        continue;
this will continue in the next `projectTeamMembers` loop. You need to continue to next project, not to next team member.

2022-06-23 13:29 UTC, rathorevaibhav commented on Modules/Project/Services/ProjectService.php
> +                $projectTeamMembers = $project->teamMembers;
This is not pre-loading. Please check this:
https://laravel.com/docs/9.x/eloquent-relationships#eager-loading

2022-06-23 13:29 UTC, rathorevaibhav commented on Modules/Project/Services/ProjectService.php
> +            $userAsProjectManagerInProjectsId = ProjectTeamMember::where('team_member_id', $user->id)->where('designation', 'project_manager')->pluck('project_id');
```suggestion
            $userProjects = ProjectTeamMember::where('team_member_id', $user->id)->where('designation', 'project_manager')->pluck('project_id');
```

2022-06-23 14:30 UTC, rathorevaibhav requested changes

2022-06-23 14:30 UTC, rathorevaibhav commented on Modules/Project/Services/ProjectService.php
> +                $projectTeamMembers = Project::with(['teamMembers'])->get();
You don't need a separate query to fetch the project which is already fetched above. Not needed separately. You can do:
```
$projects = Project::with(['teamMembers'])->whereIn('id', $userProjects)->get();
```

and then access inside the loop with `$project->teamMembers`

2022-06-23 15:24 UTC, merged