hiring-guidelines-and-recources phase2 done
ColoredCow/portal pull request #1603
Opened 2022-06-22 12:07 UTC by JCArya

Targets #{1568}
Phase 2: Hiring guidelines and resources done

2022-06-22 14:13 UTC, P4NK4J requested changes
Left some comments, please take a look

2022-06-22 14:13 UTC, P4NK4J commented on resources/views/layouts/navbar.blade.php
> +                <a class="dropdown-item " href="{{ route('resources.index') }}">Guidelines And Resources</a>
Let's keep it disabled for a while, we can enable it once the page is ready to use

2022-06-22 14:13 UTC, P4NK4J commented on Modules/HR/Resources/views/guidelines-resources/show.blade.php
> +        <a href="#" class="btn btn-success btn-block btn-lg">Add Resources</a>
Let's add a comment here `//ToDo: Functionality yet to be created`

2022-06-22 14:13 UTC, P4NK4J commented on Modules/HR/Http/Controllers/ResourcesController.php
> +        $jobs = Job::select('title')->get();
Why we are using `$jobs = Job::select('title')->get();`, what would happen if we use `all()` ?

2022-06-22 15:49 UTC, JCArya commented on resources/views/layouts/navbar.blade.php
> +                <a class="dropdown-item " href="{{ route('resources.index') }}">Guidelines And Resources</a>
okk

2022-06-23 05:08 UTC, P4NK4J approved these changes

2022-06-23 05:09 UTC, merged