installation guide fixes
ColoredCow/portal pull request #1607
Opened 2022-06-23 11:31 UTC by LAKSHYA0501

Targets https://github.com/ColoredCow/portal/issues/1606

### Description
I have added a new line in readme file for windows user to use gitbash or power shell instead of cmd.

### Checklist:

- [x] I have performed a self-review of my own code.

2022-06-23 13:31 UTC, rathorevaibhav requested changes

2022-06-23 13:31 UTC, rathorevaibhav commented on docs/installation.md
> +### If you are a windows user use GitBash or PowerShell instead of command prompt.
```suggestion
**Note:** If you are a Windows user, use GitBash or PowerShell instead of the command prompt.
```

2022-06-24 05:03 UTC, P4NK4J approved these changes
Looks good, also add assignee on the PR as well, whenever assigning for review

2022-06-29 04:38 UTC, rathorevaibhav approved these changes

2022-06-29 05:48 UTC, P4NK4J commented
We can merge the PR 1607 without worrying about the failing check. It's happening because Lakshya created the PR from a forked repository and Github does not pass secrets (in our case CYPRESS_DASHBOARD_KEY) when workflow are triggered from a forked repository.

See note here: https://docs.github.com/en/actions/security-guides/encrypted-secrets#using-encrypted-secrets-in-a-workflow

2022-06-29 05:48 UTC, merged