Fixed create seeders for Job opportunities in dev environment
ColoredCow/portal pull request #1681
Opened 2022-07-02 06:13 UTC by Bahugunajii

Targets #1638

2022-07-04 07:29 UTC, kuldeep3 commented
@Bahugunajii Could you please fix the issue with CI checks that are not passing and then assign it for review?

2022-07-04 18:27 UTC, Bahugunajii commented
> @Bahugunajii Could you please fix the issue with CI checks that are not passing and then assign it for review?

Fixed all CI checks!

2022-07-04 18:37 UTC, P4NK4J commented
@Bahugunajii The seeders are throwing error while running the command
<img width="717" alt="image" src="https://user-images.githubusercontent.com/35001775/177204723-6b5037e1-e055-4203-bdad-ac2f68909588.png">

2022-07-04 18:42 UTC, P4NK4J requested changes
requesting changes, as seeders are throwing an error while running the module:seed command

2022-07-05 06:11 UTC, GauravGusain98 requested changes
please check the comments

2022-07-05 06:11 UTC, GauravGusain98 commented on Modules/HR/Database/Factories/HrJobFactory.php
> +            'id' => $index,
Remove this

2022-07-05 06:11 UTC, GauravGusain98 commented on Modules/HR/Database/Factories/HrJobFactory.php
> +            'link' => 'https=>//coloredcow.com/career/laravel-developer/',
Make it null

2022-07-05 06:11 UTC, GauravGusain98 commented on Modules/HR/Database/Factories/HrJobFactory.php
> +            'start_date' => $faker->date,
Use todays date or make it null.

2022-07-05 06:11 UTC, GauravGusain98 commented on Modules/HR/Database/Factories/HrJobFactory.php
> +            'end_date' => $faker->date,
Make it null

2022-07-05 06:11 UTC, GauravGusain98 commented on Modules/HR/Database/Factories/HrJobFactory.php
> +            'status' => $faker->text,
status available - archived, published, draft

But in this case use published

2022-07-05 06:11 UTC, GauravGusain98 commented on Modules/HR/Database/Factories/HrJobFactory.php
> +            'deleted_at' => $faker->date,
Make it null

2022-07-05 06:11 UTC, GauravGusain98 commented on Modules/HR/Database/Factories/HrJobFactory.php
> +            'posted_by' => $faker->randomDigit,
If it is nullable then make it null, else give the id of any user that exists in the database.

2022-07-05 06:11 UTC, GauravGusain98 commented on Modules/HR/Database/Factories/HrJobFactory.php
> +            'instagram_post' => $faker->text,
Make it null

2022-07-05 06:11 UTC, GauravGusain98 commented on Modules/HR/Database/Seeders/HRDatabaseSeeder.php
> +        $this->call(HRJobSeederTableSeeder::class);
Move it after `SettingsTableSeeder` seeder line

2022-07-05 07:28 UTC, Bahugunajii commented on Modules/HR/Database/Factories/HrJobFactory.php
> +            'start_date' => $faker->date,
Done!

2022-07-05 07:28 UTC, Bahugunajii commented on Modules/HR/Database/Factories/HrJobFactory.php
> +            'end_date' => $faker->date,
Done!

2022-07-05 07:28 UTC, Bahugunajii commented on Modules/HR/Database/Factories/HrJobFactory.php
> +            'status' => $faker->text,
Done!

2022-07-05 07:28 UTC, Bahugunajii commented on Modules/HR/Database/Factories/HrJobFactory.php
> +            'deleted_at' => $faker->date,
done!

2022-07-05 07:28 UTC, Bahugunajii commented on Modules/HR/Database/Factories/HrJobFactory.php
> +            'posted_by' => $faker->randomDigit,
Done!

2022-07-05 07:29 UTC, Bahugunajii commented on Modules/HR/Database/Factories/HrJobFactory.php
> +            'instagram_post' => $faker->text,
Done!

2022-07-05 07:29 UTC, Bahugunajii commented on Modules/HR/Database/Seeders/HRDatabaseSeeder.php
> +        $this->call(HRJobSeederTableSeeder::class);
Done!

2022-07-05 08:37 UTC, GauravGusain98 requested changes
Minor suggestion. Please check

2022-07-05 08:37 UTC, GauravGusain98 commented on Modules/HR/Database/Factories/HrJobsFactory.php
> +            'type' => config('hr.opportunities.job.type'),
Please use the job type here

2022-07-05 08:52 UTC, Bahugunajii commented on Modules/HR/Database/Factories/HrJobsFactory.php
> +            'status' => array_rand(config('hr.opportunities-status')),
> For now make all the job status as `published`

Changes made!

2022-07-05 08:52 UTC, Bahugunajii commented on Modules/HR/Database/Factories/HrJobsFactory.php
> +            'type' => config('hr.opportunities.job.type'),
Changes made!

2022-07-05 10:47 UTC, GauravGusain98 approved these changes
Looks good

2022-07-05 10:49 UTC, P4NK4J approved these changes
looks good

2022-07-05 10:49 UTC, merged