Feature/shedule listing
ColoredCow/portal pull request #1691
Opened 2022-07-02 12:02 UTC by gautam071

Targets #

### Description

### Checklist:

- [ ] I have performed a self-review of my own code.

2022-07-04 17:58 UTC, GauravGusain98 requested changes
Minor changes requested. Please check

2022-07-04 17:58 UTC, GauravGusain98 commented on resources/views/settings/index.blade.php
> +        @if (auth()->user()->hasAnyPermission(['super-admin']))
I think this should be role instead of permission as we don't have super-admin as permission

2022-07-05 11:58 UTC, rathorevaibhav requested changes

2022-07-05 11:58 UTC, rathorevaibhav commented on app/Http/Controllers/Settings/CronController.php
> +        app()->make(\Illuminate\Contracts\Console\Kernel::class);
what does this line do?

2022-07-05 11:58 UTC, rathorevaibhav commented on app/Http/Controllers/Settings/CronController.php
> +        $events = collect($schedule->events())->map(function ($event) {
can you add a 1-2 liner comment on what exactly is happening here?

2022-07-05 11:58 UTC, rathorevaibhav commented on app/Http/Controllers/Settings/CronController.php
> +            $date = Carbon::now();
what's the use of this variable?

2022-07-05 11:58 UTC, rathorevaibhav commented on app/Http/Controllers/Settings/CronController.php
> +    public function run($command)
can we typehint the parameter?

2022-07-05 11:58 UTC, rathorevaibhav commented on resources/views/settings/index.blade.php
> +        @if (auth()->user()->hasAnyRole(['super-admin']))
Let's use the `@role` directive here

2022-07-05 11:58 UTC, rathorevaibhav commented on routes/web.php
> +        Route::get('/cron', 'CronController@index')->name('settings.cron');
What happens if a non super-admin user directly types the URL on browser? Will he/she go to that page?

2022-07-05 11:58 UTC, rathorevaibhav commented on routes/web.php
> +        Route::get('/cron', 'CronController@index')->name('settings.cron');
I believe you need to add Laravel Policy at controller level

2022-07-13 05:25 UTC, rathorevaibhav requested changes

2022-07-13 05:25 UTC, rathorevaibhav commented on app/Http/Controllers/Settings/CronController.php
> +        app()->make(\Illuminate\Contracts\Console\Kernel::class);
any update on my question @gautam071 ? I don't see there is a variable assigned here so wanted to understand what's happening here.

2022-07-13 05:25 UTC, rathorevaibhav commented on app/Http/Controllers/Settings/CronController.php
> +        $events = collect($schedule->events())->map(function ($event) {
@gautam071 you missed my comment 👆

2022-07-13 05:25 UTC, rathorevaibhav commented on routes/web.php
> +        Route::get('/cron/{command}', 'CronController@run')->name('settings.cron.run');
What happens if a non super-admin user directly types the URL on browser? Will he/she go to that page?

2022-07-13 05:25 UTC, rathorevaibhav commented on resources/views/settings/index.blade.php
> +        @role('super-admin')
there should be permissions based checks not role based.

2022-07-13 05:25 UTC, rathorevaibhav commented on app/Http/Controllers/Settings/CronController.php
> +                'next_run_at' => $cron->getNextRunDate()->format('d, M, Y, g:i A'), // Converts the cron expression to a human readable date.
can we also add a row in the UI to show `last_run_at`, if that is something that is supported in-built. That would be handy also? Sorry I'm adding this requirement at the end!

2022-07-13 05:25 UTC, rathorevaibhav commented on app/Http/Controllers/Settings/CronController.php
> +        return redirect()->route('settings.cron')->with('success', 'Command executed successfully');
will the page keep loading until the artisan command is finished? If yes, do we disable the button so that user does not click it again?

2022-07-13 05:31 UTC, rathorevaibhav commented on app/Http/Controllers/Settings/CronController.php
> +        $this->authorize('index', 'super-admin');
This should be a permission-based check and not a role-based check.

2022-07-13 05:49 UTC, gautam071 commented on app/Http/Controllers/Settings/CronController.php
> +            $date = Carbon::now();
The Cron variable is used to convert the corn expression to a readable format

2022-07-13 05:50 UTC, gautam071 commented on app/Http/Controllers/Settings/CronController.php
> +        $events = collect($schedule->events())->map(function ($event) {
I have added a comment in the code on what exactly happens

2022-07-13 05:51 UTC, gautam071 commented on app/Http/Controllers/Settings/CronController.php
> +        $events = collect($schedule->events())->map(function ($event) {
You can look [here](https://github.com/ColoredCow/portal/blob/ea01fa5a42f9d462a03b294ba0421bc21516d531/app/Http/Controllers/Settings/CronController.php#L18)

2022-07-13 06:23 UTC, gautam071 commented on app/Http/Controllers/Settings/CronController.php
> +        app()->make(\Illuminate\Contracts\Console\Kernel::class);
@rathorevaibhav This gets all the data from the kernel file.
I just added it globally because we don't have to use this every time.
like this 
`app()->make(\Illuminate\Contracts\Console\Kernel::class)->make(\Illuminate\Console\Scheduling\Schedule::class);`

2022-07-13 06:24 UTC, gautam071 commented on routes/web.php
> +        Route::get('/cron/{command}', 'CronController@run')->name('settings.cron.run');
It will show an error of 403 forbidden

2022-07-13 06:44 UTC, gautam071 commented on resources/views/settings/index.blade.php
> +        @role('super-admin')
@rathorevaibhav As Gaurav suggested I went with roles. Changing back to permissions

2022-07-13 06:55 UTC, gautam071 commented on app/Http/Controllers/Settings/CronController.php
> +                'next_run_at' => $cron->getNextRunDate()->format('d, M, Y, g:i A'), // Converts the cron expression to a human readable date.
Okay! 👍

2022-07-23 09:40 UTC, gautam071 commented on app/Http/Controllers/Settings/CronController.php
> +        $events = collect($schedule->events())->map(function ($event) {
I am collecting the events from the kernel file schedule function mapping through each function and getting the required details

2023-04-07 12:02 UTC, closed without merging