WIP Need follow up tagged applications to be automatically reminded
ColoredCow/portal pull request #1729
Opened 2022-07-05 18:45 UTC by Bahugunajii

#1592 

### Description

### Checklist:

- [ ] I have performed a self-review of my own code.

2022-07-11 19:55 UTC, GauravGusain98 requested changes
Minor suggestion. Please check

2022-07-11 19:55 UTC, GauravGusain98 commented on Modules/HR/Database/Seeders/SettingsTableSeeder.php
> +            'setting_key' => 'Follow_up_email_for_scheduling_interview_subject',
key should be in lowercase
```suggestion
            'setting_key' => 'follow_up_email_for_scheduling_interview_subject',
```

2022-07-11 19:55 UTC, GauravGusain98 commented on Modules/HR/Database/Seeders/SettingsTableSeeder.php
> +            'setting_key' => 'Follow_up_email_for_scheduling_interview_body',
```suggestion
            'setting_key' => 'follow_up_email_for_scheduling_interview_body',
```

2022-07-11 19:55 UTC, GauravGusain98 commented on Modules/HR/Database/Seeders/SettingsTableSeeder.php
> +            'setting_key' => 'Follow_up_email_for_scheduling_interview_body',
Also, we should not use hardcoded values. As I can see this key being used at many place so can we take the value of this key from the config file inside the HR Module. 

For reference you can see the invoice templates config which is stored in config file of Invoice module.

2022-07-11 19:55 UTC, GauravGusain98 commented on Modules/HR/Listeners/FollowUpListener.php
> +        $body = Setting::where('module', 'hr')->where('setting_key', 'Follow_up_email_for_scheduling_interview_body')->first();
same here

2022-07-11 19:55 UTC, GauravGusain98 commented on Modules/HR/Listeners/FollowUpListener.php
> +                ]);
```suggestion
        FollowUp::create([
            'hr_application_round_id' => $application->latestApplicationRound->id,
            'comments' => 'sent follow up email',
            'conducted_by' => User::select('id')->first()->id
        ]);
```

2022-07-11 19:55 UTC, GauravGusain98 commented on resources/views/settings/hr/follow-up.blade.php
> +							<label for="setting_key[Follow_up_email_for_scheduling_interview_body]">Mail body:</label>
Take value from config

2022-07-12 09:35 UTC, Bahugunajii commented on resources/views/settings/hr/follow-up.blade.php
> +							<label for="setting_key[Follow_up_email_for_scheduling_interview_body]">Mail body:</label>
Done!

2022-07-12 09:35 UTC, Bahugunajii commented on Modules/HR/Database/Seeders/SettingsTableSeeder.php
> +            'setting_key' => 'Follow_up_email_for_scheduling_interview_body',
Done!

2022-07-12 09:35 UTC, Bahugunajii commented on Modules/HR/Database/Seeders/SettingsTableSeeder.php
> +            'setting_key' => 'Follow_up_email_for_scheduling_interview_subject',
Done!

2022-07-12 11:12 UTC, GauravGusain98 requested changes
Minor changes requested. Please check.

2022-07-12 11:12 UTC, GauravGusain98 commented on Modules/HR/Database/Seeders/SettingsTableSeeder.php
> +            'setting_key' => 'follow_up_email_for_scheduling_interview_subject',
We can also take it from config

2022-07-12 11:12 UTC, GauravGusain98 commented on Modules/HR/Database/Seeders/SettingsTableSeeder.php
> +            'setting_key' => 'follow_up_email_for_scheduling_interview_body',
same here

2022-07-12 11:35 UTC, GauravGusain98 approved these changes
Looks good

2022-07-12 11:35 UTC, merged