Correctly aligned the UI of the dashboard
ColoredCow/portal pull request #1730
Opened 2022-07-05 19:23 UTC by amisha296

Targets #{ISSUE_ID}

### Description

### Checklist:

- [ ] I have performed a self-review of my own code.

2022-07-06 06:37 UTC, P4NK4J requested changes
Left a comment, and currently, the height of the `my projects` card is smaller as compared to all the others, can we make all the cards with equal heights?
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/35001775/177484938-0567018f-3b9f-46e5-a263-19748317af39.png">

2022-07-06 06:37 UTC, P4NK4J commented on resources/js/components/Dashboard/UserDashboardInvoice.vue
> +    <div class="card-body pt-3" style=" width:25em; height: 18em;overflow: auto;">
Let's use bootstrap classes here, instead of style tags. For example you can use `w-600`, 600 is just a random number here, variables can be picked from `_variables.scss` file

2022-07-06 06:39 UTC, amisha296 commented on resources/js/components/Dashboard/UserDashboardInvoice.vue
> +    <div class="card-body pt-3" style=" width:25em; height: 18em;overflow: auto;">
Okay

2022-07-06 08:56 UTC, amisha296 commented on resources/js/components/Dashboard/UserDashboardInvoice.vue
> +    <div class="card-body pt-3" style=" width:25em; height: 18em;overflow: auto;">
I have made the suggested changes, you can check them.

2022-07-08 05:27 UTC, kuldeep3 commented
@amisha296 Please resolve the merge conflicts and then assign it for review. Moreover, if you could provide a before and after screenshot of the changes (as the changes are related to UI), it would be great.

2022-07-08 06:02 UTC, P4NK4J commented
@amisha296 Please fix the CI checks, and share the screenshot of how the dashboard UI is looking after the fixes.

2022-07-08 06:04 UTC, amisha296 commented
> @amisha296 Please resolve the merge conflicts and then assign it for review. Moreover, if you could provide a before and after screenshot of the changes (as the changes are related to UI), it would be great.

After:
![Screenshot (100)](https://user-images.githubusercontent.com/90472056/177927105-2a32e0d3-4d73-4625-9fea-9ee70269373f.png)  

Before:
![Screenshot (99)](https://user-images.githubusercontent.com/90472056/177927234-aee0a64e-ae59-48ab-a857-538d914663a5.png)

2022-07-08 06:12 UTC, P4NK4J commented
@amisha296 can we reduce the gap between the cards a bit (when we traverse horizontally). Also, fix the CI checks once you complete the spacing part

2022-07-08 06:16 UTC, amisha296 commented
> @amisha296 can we reduce the gap between the cards a bit (when we traverse horizontally). Also, fix the CI checks once you complete the spacing part

For sure!

2022-07-08 06:19 UTC, GauravGusain98 commented on resources/js/components/Dashboard/UserDashboardInfrastructure.vue
> +         <div class="card-body pt-3 h-325 w-md-389 w-389  overflow-y-scroll">
Nice 👏, we usually don't use style tag inside blade. So whenever you see style tag at any place please try to fix that as well.

2022-07-08 06:22 UTC, GauravGusain98 requested changes
Please check the comment

2022-07-08 06:22 UTC, GauravGusain98 commented on resources/js/components/Dashboard/UserDashboardInvoice.vue
>  </template>
I think you have used tab indentation while in Laravel we use space indentation. You can change this from the setting of your vs code editor. Let me know if you need any help here.

2022-07-08 06:22 UTC, GauravGusain98 commented on resources/sass/_variables.scss
> +$line-heights: ( "half": 0.5, "none": 1, "tight": 1.25, "normal": 1.5, "loose": 2, "10": 10px, "14": 14px, "16": 16px, "20": 20px, "22": 22px, "25": 25px, "30": 30px, "44": 44px, "45": 45px, "60": 60
I think you have used some formatting tool, due to which all these line got wrapped in one line. Can you please revert these changes and from the vs editor setting disable the auto formatting on save setting.

2022-07-08 06:23 UTC, GauravGusain98 commented
@amisha296 Please fix the feedbacks and also your CI checks are failing, fix them as well

2022-07-08 06:25 UTC, amisha296 commented on resources/sass/_variables.scss
> +$line-heights: ( "half": 0.5, "none": 1, "tight": 1.25, "normal": 1.5, "loose": 2, "10": 10px, "14": 14px, "16": 16px, "20": 20px, "22": 22px, "25": 25px, "30": 30px, "44": 44px, "45": 45px, "60": 60
okay okay

2022-07-08 06:26 UTC, amisha296 commented on resources/js/components/Dashboard/UserDashboardInvoice.vue
>  </template>
okay, let me try first.

2022-07-08 06:26 UTC, amisha296 commented on resources/js/components/Dashboard/UserDashboardInfrastructure.vue
> +         <div class="card-body pt-3 h-325 w-md-389 w-389  overflow-y-scroll">
I'll keep that in mind!

2022-07-08 06:27 UTC, amisha296 commented
> > @amisha296 can we reduce the gap between the cards a bit (when we traverse horizontally). Also, fix the CI checks once you complete the spacing part
> 
> For sure!
![Screenshot (102)](https://user-images.githubusercontent.com/90472056/177930243-01ff7f16-9ad8-4324-bb2b-80ff15930cc0.png)

Is it fine now?

2022-07-08 06:31 UTC, P4NK4J commented
> > > @amisha296 can we reduce the gap between the cards a bit (when we traverse horizontally). Also, fix the CI checks once you complete the spacing part
> > 
> > 
> > For sure!
> > ![Screenshot (102)](https://user-images.githubusercontent.com/90472056/177930243-01ff7f16-9ad8-4324-bb2b-80ff15930cc0.png)
> 
> Is it fine now?

Looks good 👏

2022-07-08 09:55 UTC, GauravGusain98 approved these changes
Looks good

2022-07-08 10:23 UTC, merged