over_flow_fix
ColoredCow/portal pull request #1781
Opened 2022-07-08 11:48 UTC by Tushar403

Targets #1716 

### Description
fixed overflow in the popup screen 

### Checklist:
 [ ] I have performed a self-review of my own code.

2022-07-08 12:21 UTC, GauravGusain98 requested changes
Please check the comment

2022-07-08 12:21 UTC, GauravGusain98 commented on resources/views/knowledgecafe/library/books/show_nudge_modal.blade.php
> +                                                    class="reader_image"
Why you are repeating the code so this many times. For a user the image should appear only one time. According your current implementation, the logic will print the image of a user 8 times as in every loop iteration 8 div will be printed.

2022-07-08 13:02 UTC, Tushar403 commented on resources/views/knowledgecafe/library/books/show_nudge_modal.blade.php
> +                                                    class="reader_image"
corrected my mistakes please check and review it, and let me if any changes are needed.

2022-07-11 06:33 UTC, kuldeep3 reviewed
As this PR contains UI changes, could you provide a screenshot of how it was before and how it is looking after these changes? @Tushar403

2022-07-14 06:40 UTC, Tushar403 commented
> As this PR contains UI changes, could you provide a screenshot of how it was before and how it is looking after these changes? @Tushar403
![Screenshot (20)](https://user-images.githubusercontent.com/108524329/178917481-10f41c1c-ff2f-43cf-aa33-46a6bc3f470a.png)
(before changes)
![Screenshot (21)](https://user-images.githubusercontent.com/108524329/178917650-8abb9728-3c55-4699-90f7-edb68ecc7cb0.png)
(after changes)

2022-07-14 06:45 UTC, kuldeep3 approved these changes

2022-07-14 07:09 UTC, Tushar403 commented
@kuldeep3  so I am done with my task. Is it ready to merge?

2022-07-14 07:51 UTC, P4NK4J commented
@GauravGusain98 You need to submit your review here as well. Please take a look.

2022-07-14 07:54 UTC, merged