add domain button
ColoredCow/portal pull request #1792
Opened 2022-07-11 06:13 UTC by rohit123-rawat

Targets #1632 

### Description
1-create a hr_job_domain table 
2-add button 
3-create a popup by clicking the button 
4-save the form in the database
### Checklist:

- [ ] I have performed a self-review of my own code.

2022-07-12 07:28 UTC, P4NK4J requested changes
@rohit123-rawat On clicking the save button on the modal, the page is redirected to a blank page. Please take a look and fix it
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/35001775/178433544-7cac2ca5-0824-4410-8f14-15edd8180973.png">

2022-07-13 13:41 UTC, P4NK4J commented
@rohit123-rawat The slug needs to be present in the value of the opportunity, while the Title should be displayed in the Options label. Also, the values you removed from config, need to be added to this domains table through seeders.
Please create seeders for adding the default Job domains in the `hr_job_domains` table.
<img width="1435" alt="image" src="https://user-images.githubusercontent.com/35001775/178747460-22090edc-e788-4c44-822b-ea4c91ae8308.png">

2022-07-15 12:42 UTC, P4NK4J commented
@rohit123-rawat Good job! In the edit blade, the job domain is not shown in the dropdown. I created this test job, and mapped it with a custom domain, it's saved in the database, but I am not able to see the created domain under edit blade. It is showing `Engineering` there. Please check
<img width="1432" alt="image" src="https://user-images.githubusercontent.com/35001775/179224978-dc7f5022-b12a-4030-8736-3f53162c25bf.png">

2022-07-15 18:44 UTC, GauravGusain98 requested changes
Please check the comment

2022-07-15 18:44 UTC, GauravGusain98 commented on Modules/HR/Http/Controllers/Recruitment/JobController.php
> +        return redirect('/hr/recruitment/opportunities/create');
Please use the route name instead of harcoding the URL. Or you can also use this
```
return redirect()->back()

```

2022-07-15 18:44 UTC, GauravGusain98 commented on resources/views/hr/job/create.blade.php
> +                            @endforeach
You also need to do the same thing in the edit job opportunity blade as well. There I think we are using the config values, so when we are seeding any new job domain in the database, that domain is not shown in the dropdown list on edit job opportunity blade.

Pankaj Kandpal is also saying the same.

2022-07-16 13:35 UTC, P4NK4J commented
@rohit123-rawat I created a test opportunity and added a CC test for that as the job domain, it's going to edit blade and the domain is selected as Engineering. Also, while I am editing, its giving me domain name required error. I think there is some issue with the mapping. Please check. In the database, the domain corresponding to the test job is CC test, but not reflected on edit blade.
<img width="1438" alt="image" src="https://user-images.githubusercontent.com/35001775/179357186-c2b41dae-54b9-4a8d-9e66-1f9c2275c3a8.png">

2022-07-20 09:04 UTC, GauravGusain98 requested changes
Please check the comments?

2022-07-20 09:04 UTC, GauravGusain98 commented on Modules/HR/Http/Controllers/Recruitment/JobController.php
> -            ->appends(Request::except('page'));
Why you have removed this?

2022-07-20 09:04 UTC, GauravGusain98 commented on resources/views/hr/job/edit.blade.php
> +                            <option  value="{{ $jobtitle->slug }}" {{ old('domain',$jobtitle->slug) == $job->domain ? 'selected' : '' }} >{{ Str::title(str_replace('-', ' ', $jobtitle->domain)) }}</o
```suggestion
                                <option  value="{{ $jobtitle->slug }}" {{ old('domain',$jobtitle->slug) == $job->domain ? 'selected' : '' }} >{{ Str::title(str_replace('-', ' ', $jobtitle->domain)) }}</option>
```

2022-07-20 09:04 UTC, GauravGusain98 commented on Modules/HR/Http/Controllers/Recruitment/JobController.php
> -use Request;
Is this not being used anywhere in this file?

2022-07-20 10:04 UTC, GauravGusain98 approved these changes
Looks fine

2022-07-20 10:29 UTC, P4NK4J commented on Modules/HR/Http/Controllers/Recruitment/JobController.php
> +        $hr_job_domains = new EntitiesHrJobDomain();
```suggestion
        $hrJobDomains = new EntitiesHrJobDomain();
```

2022-07-20 12:32 UTC, merged