Feature/1788/Add_coming_soon_template_to_leads
ColoredCow/portal pull request #1797
Opened 2022-07-11 07:16 UTC by Sachinbisht27

Targets #1788

### Description
I changed lead page theme to ColoredCow main theme and added a coming soon template to it.

### Checklist:
- [x] I have performed a self-review of my own code.

2022-07-11 07:20 UTC, P4NK4J requested changes
@Sachinbisht27 I don't think you need to create header and everything again. That's already created. You just need to see how you can include them here, probably it would be including any master/app blade file that will bring the changes here. Please correct this and then assign for review.

2022-07-12 03:35 UTC, Sachinbisht27 commented
@P4NK4J I don't get you. Does i have to make changes in master/app blade file? And What are those major changes if they are not creating headers. Please explain.

2022-07-12 07:57 UTC, P4NK4J commented
@Sachinbisht27 If you take a latest pull from master branch, run `npm run dev` and then access the `Task` module from navigation, it will give you some reference, how you can make the leads page similar to it. Let me know if that makes sense

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/35001775/178439517-d9b731de-bd20-40e4-a09e-2fe679b4c00b.png">

2022-07-12 13:57 UTC, P4NK4J requested changes
@Sachinbisht27 Left some comments, also could you share the screenshot of how it is looking on the UI.

2022-07-12 13:57 UTC, P4NK4J commented on Modules/AppointmentSlots/Resources/views/layouts/master.blade.php
> +@extends('')
why this is changed ?

2022-07-13 12:54 UTC, P4NK4J requested changes
Left a comment, please check

2022-07-13 17:21 UTC, Sachinbisht27 commented
@P4NK4J At first I used HTML code of main coloredcow portal to get the theme for the lead page, then you said me that we don't have to add headers and all again and again then I learned about @extends & @yield used in laravel to get content from other pages and used @extends('layouts.app') in master.blade.php file.
This is my first time on laravel and i did some mistakes.
Now I understand that why we use @extends (which is a laravel tamplate which defines its own sections using @yield) and @yield (used to define section in layout and used to get content from one page to another page).
Attaching new screenshot of master.blade.php file. 
![Screenshot (9)](https://user-images.githubusercontent.com/96137915/178789014-81d8fbd8-827c-4b7c-a525-47f97bd70adc.png)

Does I have to make more changes?

2022-07-14 05:24 UTC, P4NK4J commented
@Sachinbisht27 No worries, we always learn from our mistakes. Glad you researched a lot about these helpers. If you feel like everything is fine from your end, please push the code and assign it for review. The portal team reviewers would take a look and take action accordingly.

2022-07-14 06:20 UTC, Sachinbisht27 commented on Modules/AppointmentSlots/Resources/views/layouts/master.blade.php
> +@extends('')
I don't remember when I did these changes in AppointmentSlots.
I don't know sir, I think by mistake.

2022-07-14 06:23 UTC, Sachinbisht27 commented on Modules/AppointmentSlots/Resources/views/layouts/master.blade.php
> +@extends('')
I am correcting it and adding new PR

2022-07-14 07:26 UTC, P4NK4J reviewed
A minor comment, else looks good

2022-07-15 06:14 UTC, Sachinbisht27 commented
> @Sachinbisht27 If you take a latest pull from master branch, run `npm run dev` and then access the `Task` module from navigation, it will give you some reference, how you can make the leads page similar to it. Let me know if that makes sense
> 
> <img alt="image" width="1440" src="https://user-images.githubusercontent.com/35001775/178439517-d9b731de-bd20-40e4-a09e-2fe679b4c00b.png">

@P4NK4J  
I searched everywhere and tried so much to align ComingSoon!! text in the middle of the page. But it always aligned in the center of the row not in the center of the page.
Till this morning I haven't did this method which you suggested to do pull req. and all..
Now I saw the [ div class="task-content" ] i did't saw this bootstrap class anywhere.
But now by taking your reference task is done. 

I have a question.
please suggest me any reference where i can learn about <div class="task-content">.

2022-07-15 06:15 UTC, Sachinbisht27 commented
please suggest me any reference where i can learn about div class="task-content"

2022-07-15 06:24 UTC, P4NK4J commented
@Sachinbisht27 `text-center` is a class in Bootstrap used to align the text in the center of the section. In CSS you would right it to
```
div {
text-align: center;
}
```
I told you to replace the `style="margin-top:6cm` with bootstrap class `mt`, if you write it like `mt-2`, it means, that `margin-top: 2*spacer (spacer will be defined in your variables.scss)`.

Let me know if that answers your question.

2022-07-15 07:13 UTC, Sachinbisht27 commented
> @Sachinbisht27 `text-center` is a class in Bootstrap used to align the text in the center of the section. In CSS you would right it to
> 
> ```
> div {
> text-align: center;
> }
> ```
> 
> I told you to replace the `style="margin-top:6cm` with bootstrap class `mt`, if you write it like `mt-2`, it means, that `margin-top: 2*spacer (spacer will be defined in your variables.scss)`.
> 
> Let me know if that answers your question.

@P4NK4J I tried to replace style with mt already but it allows me to increase by mt-25 only after that the div length ends and the text goes up as it is.

Attaching some SS:

1) When i used mt-25
![Screenshot (13)](https://user-images.githubusercontent.com/96137915/179171471-40d3dbd8-a3d3-4614-ae57-0a1f20dfb403.png)


2) When i used mt-26
![Screenshot (14)](https://user-images.githubusercontent.com/96137915/179171541-1eefc016-2540-4d0f-b92d-48b0568bc134.png)

2022-07-15 08:01 UTC, P4NK4J commented
@Sachinbisht27 mt-26, just see inspect in the browser how much margin is being applied. Why on a different screen is not correct, and how you can use bootstrap media queries to resolve the same. You can refer to Tasks page coming soon template as well.

2022-07-15 08:29 UTC, Sachinbisht27 commented
@P4NK4J i have added new PR as i take reference from task module from nav.

2022-07-15 08:36 UTC, merged