add-a-count-of-total-verified-applications
ColoredCow/portal pull request #1810
Opened 2022-07-12 09:33 UTC by LavishRawat

Targets #1789 

### Description
On the HR recruitment reports page, add a count of total verified applications 

### Checklist:
- [ ] I have performed a self-review of my own code.

2022-07-12 12:52 UTC, P4NK4J commented on resources/views/hr/recruitment/reports.blade.php
> +         <span class="total-chart">Total Verified Applications-|*COUNT*|</span>
|*COUNT*| is a method to clarify that is a dynamic section, where the total applications count will come from database. Please correct this.

2022-07-16 13:45 UTC, P4NK4J requested changes
@LavishRawat After these changes, the UI of applications report count is distorted. Also, when you select the date from datepicker inputs and click on view, its throwing an error
<img width="1427" alt="image" src="https://user-images.githubusercontent.com/35001775/179357507-6ff29b84-79b2-4df9-a0cf-b9f948cb6b15.png">
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/35001775/179357518-c8290b88-3e0e-4c67-9634-ee771cb1488f.png">

The correct UI of date counter graph should be as per shared in the screenshot.
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/35001775/179357532-854fe87b-bbb8-48ce-8cd2-efe40a9a7e01.png">

2022-07-18 07:47 UTC, kuldeep3 requested changes

2022-07-18 07:47 UTC, kuldeep3 commented on Modules/HR/Http/Controllers/Recruitment/ReportsController.php
> +        ->get();
Can we create query that fetches only those applications where is_verified is set to 1 🤔 ? That will reduce the below for-loop

2022-07-18 07:47 UTC, kuldeep3 commented on Modules/HR/Http/Controllers/Recruitment/ReportsController.php
> +        foreach ($record1 as $row) {
Same as previous feedback. Moreover, we can create a function for it and then call that function here to avoid duplicacy.

2022-07-18 07:47 UTC, kuldeep3 commented on resources/views/hr/recruitment/reports.blade.php
> +        <span class="chart-heading mr-5">Analytics</span><span class="total-chart">Total Verified Applications:<?php echo $countIsVerified ?></span>
Indentation

2022-07-18 08:16 UTC, P4NK4J reviewed
@LavishRawat I have added a minor comment on the issue as well. Right now, we are querying all the applications, we need to check applications created after July 6th. I missed mentioning it in the initial requirements, if that can be done now, that would be great. Because the verification functionality was on that date only, applications before that, won't be verified, and querying them would be an unnecessary performance burden.
Let me know your thoughts.

2022-07-18 09:00 UTC, LavishRawat commented
okay , I will try to do that.

2022-07-21 10:18 UTC, kuldeep3 commented on Modules/HR/Http/Controllers/Recruitment/ReportsController.php
> +        $from = date('2022-07-06');
Can we pass this date from config instead of hardcoding here?

2022-07-21 10:18 UTC, kuldeep3 commented on Modules/HR/Http/Controllers/Recruitment/ReportsController.php
> +        $verifiedApplicationCount = $this->verifiedApplications();
If we are only getting count of verified applications here, let's rename the function to getVerifiedApplicationsCount()

2022-07-22 05:26 UTC, kuldeep3 approved these changes

2022-07-22 05:50 UTC, P4NK4J approved these changes
Looks good.

2022-07-22 05:50 UTC, merged