Fix/1571/count of applications
ColoredCow/portal pull request #1812
Opened 2022-07-12 12:07 UTC by aquibmoin786

#1571

### Description

### Checklist:

- [ ] I have performed a self-review of my own code.

2022-07-13 10:02 UTC, P4NK4J commented
@aquibmoin786 Please see the screenshot below, its throwing an error. Seems like total-count-icon blade is not available on GitHub. Please check.
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/35001775/178707659-4bd74251-3e6c-44ed-86fd-a5c9a418df0d.png">

2022-07-13 10:02 UTC, P4NK4J requested changes
Left a comment, please check.

2022-07-13 10:34 UTC, GauravGusain98 requested changes
Please check the comments

2022-07-13 10:34 UTC, GauravGusain98 commented on Modules/HR/Http/Controllers/Recruitment/ApplicationController.php
> +        $attr['rounds'] = $hrRounds;
I think this is duplicate. Please remove this.

2022-07-13 10:34 UTC, GauravGusain98 commented on resources/views/hr/application/total-count-modal.blade.php
> +  <div class="modal fade" id="myModal" role="dialog">
Don't use the variable, id or class names as `myModal`. We should use the names that give clarity on what this element or variable is doing. 

So please update the name to a more meaningful name.

2022-07-13 10:34 UTC, GauravGusain98 commented on resources/views/hr/menu.blade.php
> +    <li class="nav-item" data-toggle="modal" data-target="#myModal">
Update the name here as well

2022-07-13 10:34 UTC, GauravGusain98 commented on resources/views/hr/menu.blade.php
> +        <a class="nav-item nav-link"><i class="fa" style="font-size:24px">&#xf07a;</i>&nbsp;Total Count</a>
We don't use style attribute inside the blade. Please use the class name that is provide for increasing the font size

2022-07-14 06:12 UTC, aquibmoin786 commented
I'm facing some problem in this branch. So I close this branch.

2022-07-14 06:12 UTC, closed without merging