Replace books count JS alert with modal form
ColoredCow/portal pull request #1827
Opened 2022-07-13 09:57 UTC by PreetiKotiyal28

Targets #1765 }

### Description
Replace books count JS alert with modal form

### Checklist:

- [ ] I have performed a self-review of my own code.

2022-07-13 10:11 UTC, P4NK4J requested changes
@PreetiKotiyal28 I tested it out, and overall looks good. It seems like the number of copies available is not preserved in the modal. While its should be populated in the modal as well. Also, the UI of modal seems a bit off, can we have the input field and the label (Number of copies available) in different rows
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/35001775/178709438-565a70b8-5699-4c1e-af1a-ed4221766f14.png">

2022-07-13 10:11 UTC, GauravGusain98 requested changes
Please check comments

2022-07-13 10:11 UTC, GauravGusain98 commented on resources/js/app.js
> +        	},
```suggestion
			updateIndex: function(index){
         		 this.currentIndex = index;
        	         },
```

2022-07-13 10:11 UTC, GauravGusain98 commented on resources/views/knowledgecafe/library/books/index.blade.php
> +                <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
Correct the `id` and `arial-labelledby` name here as well

2022-07-13 10:11 UTC, GauravGusain98 commented on resources/views/knowledgecafe/library/books/index.blade.php
> +            <div v-for="(book, index) in books" :id="'copiesOfBooks'+index" class="card book_card  mr-1 mb-3 p-2 mr-lg-4">
What it is doing?

2022-07-21 07:36 UTC, P4NK4J approved these changes
Looks good.

2022-07-21 07:37 UTC, P4NK4J commented
@PreetiKotiyal28 It has some merge conflicts with the index.blade.php please fix them

2022-07-21 08:06 UTC, GauravGusain98 requested changes
Minor suggestion, else looks Good. Will approve when merge conflicts are resolved

2022-07-21 08:06 UTC, GauravGusain98 commented on resources/views/knowledgecafe/library/books/index.blade.php
> +                <div class="modal fade" :id="'updateModalValue'+index" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
```suggestion
                <div class="modal fade" :id="'copiesOfBooksCountModal'+index" tabindex="-1" role="dialog" aria-labelledby="copiesOfBooksCount" aria-hidden="true">
```

2022-07-21 08:06 UTC, GauravGusain98 commented on resources/views/knowledgecafe/library/books/index.blade.php
> +                                    <li @click="updateIndex(index)" data-toggle="modal" :data-target="'#updateModalValue'+index" class="dropdown-item">Copies Available</li>
```suggestion
                                    <li @click="updateIndex(index)" data-toggle="modal" :data-target="'#copiesOfBooksCountModal'+index" class="dropdown-item">Copies Available</li>
```

2022-07-21 08:06 UTC, GauravGusain98 commented on resources/views/knowledgecafe/library/books/index.blade.php
> +                                    <li @click="updateIndex(index)" data-toggle="modal" :data-target="'#updateModalValue'+index" class="dropdown-item">Copies Available</li>
I think this name will give more clarity to what this function is doing

2022-07-21 09:54 UTC, GauravGusain98 commented
The fixes has been made in another PR. https://github.com/ColoredCow/portal/pull/1936

Closing this

2022-07-21 09:54 UTC, closed without merging