Modified the send confirmation mail functionality
ColoredCow/portal pull request #1834
Opened 2022-07-13 15:35 UTC by Kirannegi02

Targets #1805

### Description

### Checklist:

- [ ] I have performed a self-review of my own code.

2022-07-13 16:51 UTC, GauravGusain98 requested changes
Please check the comments

2022-07-13 16:51 UTC, GauravGusain98 commented on Modules/Invoice/Resources/views/subviews/edit/invoice-details.blade.php
> +        <div v-if="show_on_select">Mail not sent</div>
Why we need this?

2022-07-13 17:33 UTC, Kirannegi02 commented on Modules/Invoice/Resources/views/subviews/edit/invoice-details.blade.php
> +        <div v-if="show_on_select">Mail not sent</div>
As it was required that there should be message displayed as Mail not sent when checkbox is disabled below the Send Confirmation Mail. So, I have written it over here and put a condition (v-if="show_on_select") which will show" mail not sent" only when the checkbox is disabled.

2022-07-13 17:40 UTC, Kirannegi02 commented on Modules/Invoice/Resources/views/subviews/edit/invoice-details.blade.php
>                      <input type="checkbox" id="showEmail" class="ml-auto" @change="showEmail($event)" name="send_mail">
If I am removing it, then the code is not working properly. The "mail not sent" text is being displayed in both cases whether the checkbox is enabled or disabled.

2022-07-13 17:52 UTC, Kirannegi02 commented on Modules/Invoice/Resources/views/subviews/edit/invoice-details.blade.php
> +
It is being used for "mail not sent" text.

2022-07-15 07:14 UTC, GauravGusain98 approved these changes
Looks fine

2022-07-18 10:13 UTC, merged