Fix/1571/count of application new
ColoredCow/portal pull request #1841
Opened 2022-07-14 06:08 UTC by aquibmoin786

#1571

### Description

- We are added new popup icon in requirement field. This popup icon works to calculate round wise applicant.

### Checklist:

- [ ] I have performed a self-review of my own code.

2022-07-14 06:38 UTC, P4NK4J requested changes
@aquibmoin786 Shared some testing feedback with you, on Google chat. Please check and let me know if you have any questions.

2022-07-19 13:51 UTC, GauravGusain98 requested changes
Please check the comment

2022-07-19 13:51 UTC, GauravGusain98 commented on resources/sass/_utilities.scss
> +.c-pointer,.nav-item{
Why we are giving this styel to `.nav-item` we can use `c-pointer` class directly to apply these styles

2022-07-19 13:51 UTC, GauravGusain98 commented on resources/views/hr/menu.blade.php
> +    <li class="nav-item" data-toggle="modal" data-target="#countIcon">
```suggestion
    <li class="nav-item c-pointer" data-toggle="modal" data-target="#countIcon">
```

2022-07-19 14:15 UTC, aquibmoin786 commented on resources/views/hr/menu.blade.php
> +    <li class="nav-item" data-toggle="modal" data-target="#countIcon">
I will fixing it

2022-07-20 05:33 UTC, GauravGusain98 requested changes
Please check the comment

2022-07-20 05:33 UTC, GauravGusain98 commented on resources/views/hr/application/total-application-count-modal.blade.php
> +      @foreach ($rounds as $key=>$round)
```suggestion
          @foreach ($rounds as $key=>$round)
```

2022-07-20 05:33 UTC, GauravGusain98 commented on resources/sass/_utilities.scss
> +.c-pointer{
```suggestion
.c-pointer {
```

2022-07-20 05:33 UTC, GauravGusain98 commented on resources/views/hr/application/total-application-count-modal.blade.php
> +        {{-- @dd($rounds) --}}
remove this dev code

2022-07-20 05:33 UTC, GauravGusain98 commented on Modules/HR/Http/Controllers/Recruitment/ApplicationController.php
> -
Please add a new line here

2022-07-21 05:31 UTC, GauravGusain98 approved these changes
Looks fine

2022-07-21 05:34 UTC, P4NK4J approved these changes
Looks good.

2022-07-21 05:34 UTC, merged