1818 channel for job applications
ColoredCow/portal pull request #1857
Opened 2022-07-14 13:58 UTC by LAKSHYA0501

Targets #1818 

- [ ] I have performed a self-review of my own code.

2022-07-14 14:20 UTC, P4NK4J requested changes
Left some comments, please check.

2022-07-14 14:20 UTC, P4NK4J commented on Modules/HR/Database/Migrations/2022_07_13_104929_create_hr_channel_table.php
> +            $table->timestamps();
Let's add `softDeletes` to this table as well

2022-07-14 14:20 UTC, P4NK4J commented on Modules/HR/Database/Seeders/HrChannelSeederTableSeeder.php
> +class HrChannelSeederTableSeeder extends Seeder
Let's rename it to `HrChannelsTableSeeder`

2022-07-14 14:20 UTC, P4NK4J commented on Modules/HR/Database/Migrations/2022_07_13_104929_create_hr_channel_table.php
> +        Schema::create('hr_channel', function (Blueprint $table) {
let's rename this to `hr_channels`

2022-07-14 19:16 UTC, GauravGusain98 requested changes
Please check the comments

2022-07-14 19:16 UTC, GauravGusain98 commented on Modules/HR/Database/Seeders/HrChannelsTableSeeder.php
> +    }
Lets use updateOrCreate function of Laravel. It will automatically check if the records is created or not. Also you don't need to pass the value of `created_on` and `updated_on`. Laravel will automatically handle it by itself.

2022-07-14 19:16 UTC, GauravGusain98 commented on Modules/HR/Database/Migrations/2022_07_14_144257_add_soft_delete_column_to_hr_channels.php
> +            $table->softDeletes();
Lets add this to the above migration only.

2022-07-15 08:26 UTC, P4NK4J commented on Modules/HR/Database/Seeders/HrChannelsTableSeeder.php
> +    }
@GauravGusain98 Not sure it would be suitable to use `updateOrCreate`, since its an eloquent method and we don't; have model created here. While we are using DB, would it be fine if we keep it insert() here ?

2022-07-15 08:29 UTC, GauravGusain98 commented on Modules/HR/Database/Seeders/HrChannelsTableSeeder.php
> +    }
Ok, But I think we can still use updateOrCreate without a modal. @LAKSHYA0501 can you confirm if updateOrCreate is working in this case

2022-07-15 08:34 UTC, LAKSHYA0501 commented on Modules/HR/Database/Seeders/HrChannelsTableSeeder.php
> +    }
As far as I did it is not working and it is given in documentation that `updateOrCreate` is used for updating or creating a model. Still if you know any other method kindly let me know that.

2022-07-15 10:29 UTC, P4NK4J commented on Modules/HR/Database/Seeders/HrChannelsTableSeeder.php
> +    }
@pokhiii We had an offline discussion, and we will be using the HrChannels model in future as well. So @LAKSHYA0501 is now proceeding with creating a model and using `updateOrCreate` for the same.

2022-07-15 13:38 UTC, GauravGusain98 requested changes
Please check the comment

2022-07-15 13:38 UTC, GauravGusain98 commented on Modules/HR/Database/Migrations/2022_07_15_115016_hr_channels_table.php
> +class HrChannelsTable extends Migration
```suggestion
class CreateHrChannelsTable extends Migration
```

2022-07-15 13:38 UTC, GauravGusain98 commented on Modules/HR/Database/Migrations/2022_07_15_115016_hr_channels_table.php
> +class HrChannelsTable extends Migration
Also change the file name accordingly

2022-07-15 13:38 UTC, GauravGusain98 commented on Modules/HR/Database/Seeders/HrChannelsTableSeeder.php
> +        $hrChannel = HrChannel::updateOrCreate(['name'=>'Website']);
```suggestion
        $hrChannels = ['LinkedIn', 'Indeed', 'Website'];
        foreach ($hrChannels as $channelName) {
            HrChannel::updateOrCreate(['name' => $channelName);
        }
```

2022-07-15 13:38 UTC, GauravGusain98 commented on Modules/HR/Entities/HrChannel.php
> +    protected $fillable = ['id', 'name'];
```suggestion
    protected $guarded = [];
```

2022-07-15 13:38 UTC, GauravGusain98 commented on Modules/HR/Database/Migrations/2022_07_15_115016_hr_channels_table.php
> +        Schema::create('hr_channels_table', function (Blueprint $table) {
```suggestion
        Schema::create('hr_channels', function (Blueprint $table) {
```

We don't use table as suffix in table name.

2022-07-15 13:38 UTC, GauravGusain98 commented on Modules/HR/Database/Migrations/2022_07_15_115016_hr_channels_table.php
> +            'hr_channels_table',
```suggestion
            'hr_channels',
```

2022-07-15 13:38 UTC, GauravGusain98 commented on Modules/HR/Database/Migrations/2022_07_15_115016_hr_channels_table.php
> +            }
This is not needed as we are removing the table. So it will be removed by dafault. Also you should test it once in your local as this will throw error

2022-07-15 13:38 UTC, GauravGusain98 commented on Modules/HR/Database/Migrations/2022_07_15_115134_update_hr_applications_with_hr_channels_table.php
> +            $table->foreign('hr_channels_id')->references('id')->on('hr_channels_table');
```suggestion
            $table->foreign('hr_channels_id')->references('id')->on('hr_channels');
```

2022-07-15 13:38 UTC, GauravGusain98 commented on Modules/HR/Database/Migrations/2022_07_15_115134_update_hr_applications_with_hr_channels_table.php
> +            $table->foreign('hr_channels_id')->references('id')->on('hr_channels_table');
```suggestion
            $table->foreign('hr_channel_id')->references('id')->on('hr_channels_table');
```

2022-07-15 13:38 UTC, GauravGusain98 commented on Modules/HR/Database/Migrations/2022_07_15_115134_update_hr_applications_with_hr_channels_table.php
> +            $table->unsignedBigInteger('hr_channels_id')->nullable();
```suggestion
            $table->unsignedBigInteger('hr_channel_id')->nullable();
```

2022-07-15 13:38 UTC, GauravGusain98 commented on Modules/HR/Database/Migrations/2022_07_15_115134_update_hr_applications_with_hr_channels_table.php
> +            $table->dropColumn(['hr_channel_id']);
This is correct but just mentioning as you have written `hr_channels_id` in up function as column name. Make sure to check if the column names are correct or not while writing the code. Also you should test rollback functionality as well once you are done with the changes

2022-07-16 10:17 UTC, GauravGusain98 approved these changes
Looks fine

2022-07-16 11:12 UTC, P4NK4J approved these changes
Looks good.

2022-07-16 14:02 UTC, merged