add the label and fix the font
ColoredCow/portal pull request #1864
Opened 2022-07-15 06:27 UTC by gulshan81

Targets #1829

### Description
add `No Contract` label and fix the font

### Checklist:

- [ ] I have performed a self-review of my own code.

2022-07-15 06:29 UTC, P4NK4J requested changes
@gulshan81 Please fix the CI checks and then assign for review

2022-07-15 07:06 UTC, P4NK4J approved these changes
Looks good.

2022-07-15 07:06 UTC, P4NK4J commented on Modules/Project/Resources/views/index.blade.php
> +                    <th class="sticky-top"> Tags </th>
```suggestion
                    <th class="sticky-top">Tags</th>
```

2022-07-15 07:06 UTC, P4NK4J commented
@gulshan81 Minor suggestion, else looks good.

2022-07-15 07:21 UTC, GauravGusain98 requested changes
Please check the comment

2022-07-15 07:21 UTC, GauravGusain98 commented on Modules/Project/Resources/views/index.blade.php
> +                                        <span>No Contract</span>
As per the issue requirement we have to make it as a label/badge. You can take reference form this document to see how to make a text as badge

https://getbootstrap.com/docs/4.0/components/badge/#contextual-variations

2022-07-17 14:24 UTC, GauravGusain98 requested changes
Please check the comment

2022-07-17 14:24 UTC, GauravGusain98 commented on resources/sass/app.scss
> +
I think there is one extra bracket. Please check, due to this the integration testing is also getting failed

2022-07-17 14:24 UTC, GauravGusain98 commented on resources/sass/app.scss
> +	border:#E4E4E4;
Why you have removed the space?

2022-07-17 14:24 UTC, GauravGusain98 commented on Modules/Project/Resources/views/index.blade.php
> +                                         border-radius: 0.15rem " >No Contract</span>
Don't use style tag inside the blade file

2022-07-18 05:43 UTC, GauravGusain98 requested changes
Left some comment. Please check.

2022-07-18 05:43 UTC, GauravGusain98 commented on resources/sass/app.scss
> +
Why you have added these class when you are not using them anywhere in your code.

2022-07-18 05:43 UTC, GauravGusain98 commented on Modules/Project/Resources/views/index.blade.php
> +                                         border-radius: 0.15rem " >No Contract</span>
Lets remove the style tag and use the bootstrap classes. All these styles are provided by bootstrap

2022-07-18 14:51 UTC, GauravGusain98 approved these changes
Looks fine

2022-07-18 15:31 UTC, merged