Disable the Save and Remove button available in the Project team memb…
ColoredCow/portal pull request #1876
Opened 2022-07-15 13:23 UTC by Sachinbisht27

…er tab for Halted project

Targets #1869

### Description
Disable the Save and Remove button available in the Project team member tab for Halted project.

### Checklist:

- [x] I have performed a self-review of my own code.

2022-07-15 16:11 UTC, GauravGusain98 submitted a review, later dismissed
Please check the comments.

2022-07-15 16:11 UTC, GauravGusain98 commented on Modules/Project/Resources/views/subviews/edit-project-team-members.blade.php
> +                        <button v-on:click="removeProjectTeamMember(index)" type="button" class="btn btn-danger btn-sm mt-1 ml-2 text-white fz-14" disabled="disabled">Remove</button>
We only need to add this for halted and inactive projects

2022-07-15 16:11 UTC, GauravGusain98 commented on Modules/Project/Resources/views/subviews/edit-project-team-members.blade.php
> +                <button type="button" class="btn btn-primary save-btn" v-on:click="updateProjectForm('update_project_team_member_form')" disabled="disabled">Save</button>
We only need to add this for halted and inactive projects

2022-07-15 16:13 UTC, GauravGusain98 requested changes
Please check the comment and make the changes

2022-07-25 06:37 UTC, P4NK4J reviewed
Minor suggestions, else looks good.

2022-07-25 06:37 UTC, P4NK4J commented on Modules/Project/Resources/views/subviews/edit-project-team-members.blade.php
> +                        @endforeach
Please fix the indentations.

2022-07-25 06:40 UTC, Sachinbisht27 commented on Modules/Project/Resources/views/subviews/edit-project-team-members.blade.php
> +                        @endforeach
Oky sir.

2022-07-26 09:37 UTC, Sachinbisht27 commented
Done sir, due to xampp crash i did installation process again.

2022-07-26 10:54 UTC, GauravGusain98 requested changes
Please check the comments

2022-07-26 10:54 UTC, GauravGusain98 commented on Modules/Project/Resources/views/subviews/edit-project-team-members.blade.php
> +            @endif
Instead of using if condition on whole button you can just use if condition for disabled attribute

2022-07-26 10:54 UTC, GauravGusain98 commented on Modules/Project/Resources/views/subviews/edit-project-team-members.blade.php
> +                        @endif
Instead of using if condition on whole button element. You can just use it for the disabled attribute

2022-07-26 10:54 UTC, GauravGusain98 commented on Modules/Project/Resources/views/subviews/edit-project-team-members.blade.php
> +                        <input type="number" :name="`project_team_member[${index}][daily_expected_effort]`" :value="projectTeamMember.pivot.daily_expected_effort" class="form-control daily-effort">
Why remove v-model? Is it causing any issue?

2022-07-26 10:54 UTC, GauravGusain98 commented on Modules/Project/Resources/views/subviews/edit-project-team-members.blade.php
> +                        @endif
We should avoid code duplicacy.

2022-07-26 10:56 UTC, Sachinbisht27 commented on Modules/Project/Resources/views/subviews/edit-project-team-members.blade.php
> +                        <input type="number" :name="`project_team_member[${index}][daily_expected_effort]`" :value="projectTeamMember.pivot.daily_expected_effort" class="form-control daily-effort">
No sir, i think by mistake.

2022-08-01 09:28 UTC, Sachinbisht27 commented
@GauravGusain98 @P4NK4J please review

2022-08-03 10:29 UTC, Sachinbisht27 commented
@GauravGusain98 please review this...

2022-08-04 09:55 UTC, P4NK4J approved these changes
Looks good.

2022-08-04 10:07 UTC, GauravGusain98 requested changes
Please check the comment

2022-08-04 10:07 UTC, GauravGusain98 commented on Modules/Project/Resources/views/subviews/edit-project-team-members.blade.php
> +                <button type="button" class="btn btn-primary save-btn" v-on:click="updateProjectForm('update_project_team_member_form')" {{ $project->status == 'active' ? '' : 'disabled' }} >Save</bu
Why you have replaced `updateProjectTeamMemberForm` with  `update_project_team_member_form`?

2022-08-04 10:38 UTC, Sachinbisht27 commented on Modules/Project/Resources/views/subviews/edit-project-team-members.blade.php
> +                <button type="button" class="btn btn-primary save-btn" v-on:click="updateProjectForm('update_project_team_member_form')" {{ $project->status == 'active' ? '' : 'disabled' }} >Save</bu
Sir may be, when v-modal mistake was happen that time it was also happened.
I think every time when i am taking new pull these changes are coming in my branch.
I am reverting these changes.

2022-08-08 06:56 UTC, GauravGusain98 approved these changes
looks fine

2022-08-08 06:57 UTC, merged