Feature/Profit and Loss Report
ColoredCow/portal pull request #1889
Opened 2022-07-16 17:43 UTC by pankaj-ag

Targets #{ISSUE_ID}

### Description

### Checklist:

- [ ] I have performed a self-review of my own code.

2022-07-17 07:37 UTC, P4NK4J requested changes
@pankaj-ag The following error is occurring upon opening the P&L tab. In RevenueReportService, on line number 47, we are incrementing the total amount with the invoice amount, while the structure of the invoice amount is a hashed number. I think we need to tweak the codebase here a bit. Please take a look.
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/35001775/179388733-dce3d366-6b5d-42c3-9d75-715edc1a300f.png">

2022-07-18 07:53 UTC, pankaj-ag commented
@P4NK4J I think you pulled the data from production and use it on your local. That's why you can not see the invoice amount.

Can you open any invoice on your system and let me know if you are able to see the amount of that? 

We encrypt the invoice amount in the DB also so that nobody can see that even if he has database access.

2022-07-18 08:22 UTC, pankaj-ag commented
@P4NK4J I have also added a new command  ```php artisan invoice:fix-invoice-amount``` to fix the invoice amount issue on local. Can you run this command and then check.

2022-07-18 08:25 UTC, P4NK4J commented
@pankaj-ag I was testing on UAT SQL dump and the error was being encountered. After running the command, it's working fine. 
Just curious, if we deploy it on the UAT or production, will the encryption be automatically handled? Also, do we need to run this command there post-deployment?

2022-07-18 08:40 UTC, pankaj-ag commented
So we encrypt the data when you create the invoice in the system. So all the invoices you create in your local will work fine (without running this command) but if you pull the data from another system (like UAT or Production) then you have to run that command because the invoices were not created from your system originally. 

If deploy this on UAT and production it should work automatically because all the invoices are created there. You don't need to run that command on UAT or production. 
I have also added a check so that this command does not work on production. 

Let me know if you want to discuss encryption, I will be happy to discuss that.

2022-07-18 09:24 UTC, P4NK4J commented
> So we encrypt the data when we create the invoice in the system. So all the invoices you create in your local will work fine (without running this command) but if you pull the data from another system (like UAT or Production) then you have to run that command because the invoices were not created from your system originally.
> 
> If deploy this on UAT and production it should work automatically because all the invoices are created there. You don't need to run that command on UAT or production. I have also added a check so that this command does not work on production.
> 
> Let me know if you want to discuss encryption, I will be happy to discuss that.
> 
> @P4NK4J

@pankaj-ag That makes sense, thanks for elaborating. I will try to figure out the encryption in the codebase, and how its implemented, and maybe reach out offline if there are any questions.

2022-07-18 09:27 UTC, pankaj-ag commented
Okay, so what is the next step?  Can I merge it or assign somebody for review . 

@P4NK4J

2022-07-18 09:45 UTC, P4NK4J requested changes
Great job 👏 Left some questions and suggestions, please take a look.

2022-07-18 09:45 UTC, P4NK4J commented on Modules/Invoice/Console/FixInvoiceAmountsCommand.php
> +        }
Can we check this with `production` env, because on UAT, env file has `uat` as environment, also, `local` may be different on someone's system. Like it can be changed to `dev` by any user. While with production, we will have a fixed env variable. Let me know your thoughts ?

2022-07-18 09:45 UTC, P4NK4J commented on Modules/Invoice/Entities/Invoice.php
> +        return $query;
That's a great approach 👏 Creating scopes for status will help with future enhancements as well. Thanks for adding this.

2022-07-18 09:45 UTC, P4NK4J commented on Modules/Report/Config/config.php
> +
Just a question, these particulars are fixed as of now, if we need to add more items in particulars, add them from UI and database would be good, or should we keep adding them in config ?

2022-07-18 09:45 UTC, P4NK4J commented on Modules/Report/Resources/views/finance/profit-and-loss.blade.php
> +                <a href="" class="btn disabled btn-info text-white"> Export To Excel </a>
I am assuming this functionality is yet to be added, if that is the case, can we add comment and ToDo here ?

2022-07-18 09:45 UTC, P4NK4J commented on Modules/Report/Resources/views/finance/profit-and-loss.blade.php
> +                            <option disabled {{ request()->input('transaction') == 'texes' ? 'selected=selected' : '' }}
```suggestion
                            <option disabled {{ request()->input('transaction') == 'taxes' ? 'selected=selected' : '' }}
```

2022-07-18 09:45 UTC, P4NK4J commented on Modules/Report/Resources/views/finance/profit-and-loss.blade.php
> +                            <option disabled {{ request()->input('transaction') == 'texes' ? 'selected=selected' : '' }}
```suggestion
                            <option disabled {{ request()->input('transaction') == 'taxes' ? 'selected=selected' : '' }}
```

2022-07-18 09:45 UTC, P4NK4J commented on Modules/Report/Services/Finance/RevenueReportService.php
> +    }
This seems to be a repetitive function, can we put it into helpers, if its possible ?

2022-07-18 09:45 UTC, P4NK4J commented on Modules/Report/Services/Finance/RevenueReportService.php
> +    }
I am assuming these values are added for scaffolding, and functionality is yet to be created, let me know if that's correct. If yes, can we mark a comment here `what needs to be done in future?`

2022-07-18 09:45 UTC, P4NK4J commented on resources/views/layouts/navbar.blade.php
> +                <a class="dropdown-item " href="{{ route('reports.finance.profit-and-loss') }}"> P&L Report</a>
```suggestion
                <a class="dropdown-item " href="{{ route('reports.finance.profit-and-loss') }}">P&L Report</a>
```

2022-07-18 10:12 UTC, P4NK4J commented
> Okay, so what is the next step? Can I merge it or assign somebody for review .
> 
> @P4NK4J

@pankaj-ag So the process is, if a member of portal team reviewer approves the PR, we can merge it. If anyone has requested changes, without their approval it won't be merged. I was testing it out before code review, hence had a couple of questions. Now then everything is looking good, I had a couple of questions and comments on the code level. Once those are resolved, I will approve it and we can merge it. Let me know if that helps, I would be happy to share details further.

2022-07-18 11:09 UTC, pankaj-ag commented on Modules/Invoice/Console/FixInvoiceAmountsCommand.php
> +        }
Yes so that was deliberate and this is a high risk. In case somebody put prod instead of production this will corrupt all the invoices. Also 'local' and 'staging' are laravel conventions. 

Let me know if that makes sense.

2022-07-18 11:12 UTC, pankaj-ag commented on Modules/Report/Config/config.php
> +
Yes these are fixed. We can not add these form the UI because for every particular we have the to define a function also to fetch the data. 

I mean salary can come from different places and food bill can come from a different place so both needs to be different functions. 

So the process will be 
1. You will define a particular here. 
2. Wrote a logic to fetch the data from the system
3. It will print that in the excel sheet.

2022-07-18 11:13 UTC, pankaj-ag commented on Modules/Report/Resources/views/finance/profit-and-loss.blade.php
> +                <a href="" class="btn disabled btn-info text-white"> Export To Excel </a>
I have disabled my this button. I will add a Todo tag also. Thanks

2022-07-18 11:15 UTC, pankaj-ag commented on Modules/Report/Services/Finance/RevenueReportService.php
> +    }
@P4NK4J we will change this function as we will define the expense functionality. But I agree with you if you are confused then other members as well so I will clean this and add a comment.

2022-07-18 11:15 UTC, pankaj-ag commented on Modules/Report/Services/Finance/RevenueReportService.php
> +    }
Ohh okay I thought function name is descriptive but I will put comments also.

2022-07-18 12:17 UTC, pankaj-ag commented on Modules/Report/Services/Finance/RevenueReportService.php
> +    }
I have added a comment at the top.

2022-07-18 12:32 UTC, P4NK4J approved these changes
Looks good 👍

2022-07-18 12:53 UTC, merged