Added 6sec timer to alert
ColoredCow/portal pull request #1893
Opened 2022-07-17 18:14 UTC by junaid1010

Targets #1868 

### Description
Added 6sec timer to the alert message.

### Checklist:
- [ ] I have performed a self-review of my own code.

2022-07-18 05:10 UTC, P4NK4J requested changes
@junaid1010 Please check if we can move the js code to app.js file, instead of writing in the blade file.

2022-07-18 05:10 UTC, P4NK4J commented on Modules/Client/Resources/views/index.blade.php
> +            });
Let's write the JS code in app.js file instead of having `script` tag here

2022-07-18 05:10 UTC, P4NK4J commented on Modules/Invoice/Resources/views/index.blade.php
> +                </script>
Can we move this JS code to app.js ?

2022-07-18 05:16 UTC, junaid1010 commented on Modules/Invoice/Resources/views/index.blade.php
> +                </script>
Okay sir I'll try to do these changes.

2022-07-19 05:40 UTC, P4NK4J requested changes
@junaid1010 I can still see the script tags written in almost all the blade files, please move the JS code to app.js.

2022-07-19 06:23 UTC, P4NK4J requested changes
left some feedback, please check

2022-07-19 06:23 UTC, P4NK4J commented on Modules/Prospect/Resources/views/index.blade.php
> +            </script>
Can it be moved to app.js ?

2022-07-19 06:23 UTC, P4NK4J commented on Modules/Project/Resources/views/index.blade.php
> +            </script>
Can it be moved to app.js ?

2022-07-19 06:34 UTC, P4NK4J approved these changes
looks good.

2022-07-19 06:34 UTC, merged

2022-07-19 06:35 UTC, junaid1010 commented
sir, does it mean I have to add this js code to every app.js file?