Bugfix limited team members
ColoredCow/portal pull request #1904
Opened 2022-07-19 07:09 UTC by akriti12negi

#1808 

the team member column should display only limited team members in a single row 

 I have performed a self-review of my own code.

2022-07-19 07:15 UTC, P4NK4J requested changes
left some comments, please check.

2022-07-19 07:18 UTC, akriti12negi commented on Modules/Project/Resources/views/index.blade.php
> +                                <td style="width:21%;">
![2022-07-19](https://user-images.githubusercontent.com/85788400/179690070-96120852-54a3-49bb-996f-c844f23e518f.png)

2022-07-19 07:32 UTC, P4NK4J commented on Modules/Project/Resources/views/index.blade.php
> +                                <td style="width:21%;">
@akriti12negi UI looks good. can we have a small space between the member icons in the next row? Also, let's put the style into app.scss rather

2022-07-19 07:39 UTC, akriti12negi commented on Modules/Project/Resources/views/index.blade.php
> +                                <td style="width:21%;">
okay I'll do the recommended changes @P4NK4J

2022-07-20 08:40 UTC, P4NK4J approved these changes
Looks good.

2022-07-20 08:40 UTC, merged