Feature/send invoice reminder multiple times
ColoredCow/portal pull request #1909
Opened 2022-07-19 10:49 UTC by amisha296

Targets #1783 

### Description
I have added the feature of sending multiple reminders and storing those reminders in an invoice_mails table.

### Checklist:
I have done the self-review.

2022-07-19 11:41 UTC, GauravGusain98 requested changes
Please check the comments.

2022-07-19 11:41 UTC, GauravGusain98 commented on Modules/Invoice/Database/Migrations/2022_07_12_060306_drop_reminder_mail_count_from_invoices_table.php
> +            // $table->dropColumn("reminder_mail_count");
I think we need this line

2022-07-19 11:41 UTC, GauravGusain98 commented on Modules/Invoice/Services/InvoiceService.php
> +        // dd($invoice);
remove this

2022-07-19 11:41 UTC, GauravGusain98 commented on Modules/Invoice/Entities/Invoice.php
> +        return $this->invoiceMail()->orderByDesc('sent_on')->first();
```suggestion
        return $this->invoiceMail()->where('type', config('invoice.mail-type.invoice-reminder.slug'))->orderByDesc('sent_on')->first();
```

2022-07-19 11:41 UTC, GauravGusain98 commented on Modules/Invoice/Entities/Invoice.php
> +        return $this->invoiceMail()->orderByDesc('sent_on')->first();
We only want reminder type emails

2022-07-19 11:41 UTC, GauravGusain98 commented on Modules/Invoice/Resources/views/index.blade.php
> +                                        <div class="btn btn-sm btn-primary send-reminder" data-invoice-data="{{ json_encode($invoiceData) }}" data-toggle="modal" data_toogle="tooltip" data-placement=
data-toggle is used 2 times here. Please find a solution to fix this as we need to toggle modal and tooltip from same button

2022-07-19 12:42 UTC, amisha296 commented on Modules/Invoice/Services/InvoiceService.php
> +        // dd($invoice);
okay

2022-07-19 12:42 UTC, amisha296 commented on Modules/Invoice/Database/Migrations/2022_07_12_060306_drop_reminder_mail_count_from_invoices_table.php
> +            // $table->dropColumn("reminder_mail_count");
okay

2022-07-26 06:48 UTC, GauravGusain98 requested changes
Please check the comments

2022-07-26 06:48 UTC, GauravGusain98 commented on Modules/Invoice/Resources/views/edit.blade.php
> + $filename=basename($invoice->file_path);
```suggestion
    $filename=basename($invoice->file_path);
```

2022-07-26 06:48 UTC, GauravGusain98 commented on Modules/Invoice/Resources/views/edit.blade.php
> +                <a class="btn btn-sm btn-info text-white mr-4 font-weight-bold" data-toggle="modal" data-target="#previewMails" href="#">Preview mails</a>
Please use this when you are not using href
**https://www.tutorialspoint.com/How-to-make-an-anchor-tag-refer-to-nothing#:~:text=To%20make%20an%20anchor%20tag%20refer%20to%20nothing%2C%20use%20%E2%80%9Cjavascript,back%20into%20the%20current%20document.**

2022-07-26 06:48 UTC, GauravGusain98 commented on Modules/Invoice/Resources/views/modals/email-details.blade.php
> +                            {{ method_field('PATCH') }}
```suggestion
                            @csrf
```

2022-07-26 06:48 UTC, GauravGusain98 commented on Modules/Invoice/Resources/views/modals/email-details.blade.php
> +                        <form action="" method="POST">
remove this  form

2022-07-26 06:48 UTC, GauravGusain98 commented on Modules/Invoice/Resources/views/modals/email-details.blade.php
> +                        </form>
remove this

2022-07-26 06:48 UTC, GauravGusain98 commented on Modules/Invoice/Resources/views/subviews/edit/invoice-details.blade.php
> +                @if($invoice->getInvoiceConfirmationMail() === null)
```suggestion
                @if(empty($invoice->getInvoiceConfirmationMail()))
```

2022-07-26 06:48 UTC, GauravGusain98 commented on Modules/Invoice/Services/InvoiceService.php
> +            'type' => config('invoice.mail-type.payment-confirmation.label')
Please add sent_on time as well. Set it to current time

2022-07-26 06:48 UTC, GauravGusain98 commented on Modules/Invoice/Services/InvoiceService.php
> +            'type' => config('invoice.mail-type.invoice.label')
Same here

2022-07-26 06:48 UTC, GauravGusain98 commented on Modules/Invoice/Services/InvoiceService.php
> +            'subject' => $email['subject'],
Same here

2022-07-26 06:48 UTC, GauravGusain98 commented on Modules/Invoice/Services/InvoiceService.php
> +            'file_path' => ''
Please fix this as we have removed this just for testing

2022-07-26 09:10 UTC, GauravGusain98 commented
Found some issues while testing
1. When sending reminder, getting this error
<img width="1361" alt="image" src="https://user-images.githubusercontent.com/54376313/180969129-39510052-b297-4926-b37b-6325975367e5.png">

2. After sending the invoice the reminder count shows 1 instead of 0
<img width="467" alt="image" src="https://user-images.githubusercontent.com/54376313/180969344-b99d3750-8306-4cc9-9990-9771249aede3.png">

3. In the preview mails, Don't know why there is a save button as we don't need to update anything.
<img width="787" alt="image" src="https://user-images.githubusercontent.com/54376313/180969575-6be77bc4-d65a-42f7-9aad-92ceea67d990.png">

2022-07-26 10:04 UTC, amisha296 commented
@GauravGusain98  I have resolved the issues, kindly check the PR.

2022-07-26 10:50 UTC, GauravGusain98 commented
@amisha296 The first 2 issues are not yet fixed. Still getting the errors. Found one more issue related to alignment of the sent on time. It should be right aligned instead of starting in between

<img width="799" alt="image" src="https://user-images.githubusercontent.com/54376313/180988992-2e62794f-d41c-4a1f-8e10-d838c49d2c54.png">

2022-07-31 06:24 UTC, GauravGusain98 commented
Looks fine will approve and merge it after testing

2023-04-07 12:05 UTC, closed without merging