created Secondary Billing contact, Tertiary billing contact roles in edit client information page for storing clients Emails
ColoredCow/portal pull request #1914
Opened 2022-07-19 13:14 UTC by abhishekkhanduri

…g cC

Targets #{ISSUE_ID}

### Description
Created Secondary Billing Contact Role for storing cc Emails
Created Tertiary Billing Contact Role for storing bcc Emails

### Checklist:

- [ ] I have performed a self-review of my own code.

2022-07-19 13:47 UTC, mohitgusain reviewed
Please check the comments

2022-07-19 13:47 UTC, mohitgusain commented on Modules/Client/Config/config.php
> +        'Primary-billing-contact' => 'billing-contact',
```suggestion
        'primary-billing-contact' => 'billing-contact',
```

2022-07-19 13:47 UTC, mohitgusain commented on Modules/Client/Config/config.php
> +        'General-Point-of-contact' => 'general-contact',
can you also format this and the below line as mentioned above?

2022-07-19 13:47 UTC, mohitgusain commented on Modules/Client/Entities/Client.php
> +        return $this->contactPersons()->where('type', config('client.client-roles.Primary-billing-contact'))->first();
Change all the query after changing the config values

2022-07-19 13:47 UTC, mohitgusain commented on Modules/Invoice/Resources/views/modals/payment-received.blade.php
> +    {$bccEmails .= ",$bccEmail->email";}
Check once the formatting

2022-07-19 13:47 UTC, mohitgusain commented on Modules/Invoice/Resources/views/modals/payment-received.blade.php
> +    foreach($invoice->client->secondary_contact as $ccEmail)
Check once this code is working or not

2022-07-19 18:36 UTC, abhishekkhanduri commented on Modules/Invoice/Resources/views/modals/payment-received.blade.php
> +    foreach($invoice->client->secondary_contact as $ccEmail)
I have checked, the code is working fine

2022-07-20 13:46 UTC, GauravGusain98 requested changes
minor suggestions. Please have a look

2022-07-20 13:46 UTC, GauravGusain98 commented on Modules/Invoice/Resources/views/modals/payment-received.blade.php
> +}
can we send these 2 variables from service. We should not perform logics inside blade file.

2022-07-20 13:46 UTC, GauravGusain98 commented on Modules/Invoice/Resources/views/index.blade.php
> +                            }
Lets create a getAttribute inside Module to access the bcc and cc emails

2022-07-21 17:54 UTC, GauravGusain98 requested changes
Left some comments, please check

2022-07-21 17:54 UTC, GauravGusain98 commented on Modules/Invoice/Entities/Invoice.php
> +    }
We don't want this attribute, AS we can directly use like this `$invoice->client->bcc_emails`

2022-07-21 17:54 UTC, GauravGusain98 commented on Modules/Client/Entities/Client.php
> +                $bccEmails .= ",$bccEmail->email";
Not sure how this is working correct, as you have passed variable inside a string.
```suggestion
                $bccEmails .= $tertiaryContact->email . ",";
```

2022-07-21 17:54 UTC, GauravGusain98 commented on Modules/Invoice/Resources/views/modals/payment-received.blade.php
> +                        <input type="text" name="cc" id="cc" class="form-control" value="{{$invoice->cc_emails == null ? config('invoice.mail.send-invoice.email') : config('invoice.mail.send-invoice.
```suggestion
                        <input type="text" name="cc" id="cc" class="form-control" value="{{ config('invoice.mail.send-invoice.email') . ($invoice->cc_emails == null ?: ','. $invoice->cc_emails) }}">
```

2022-07-22 21:00 UTC, GauravGusain98 approved these changes
Looks fine

2022-07-22 21:00 UTC, merged