add edit and delete functionality for HR resource
ColoredCow/portal pull request #1923
Opened 2022-07-20 10:35 UTC by JCArya

Targets #1814
Description
add edit and delete functionality for hr resource

2022-07-22 10:25 UTC, P4NK4J reviewed
Left some minor comments, please check

2022-07-22 10:25 UTC, P4NK4J commented on Modules/HR/Resources/views/guidelines-resources/edit-modal.blade.php
> +                        <label for="name" class="form-label">Resource_Link</label>
```suggestion
                        <label for="name" class="form-label">Resource Link</label>
```

2022-07-22 10:25 UTC, P4NK4J commented on Modules/HR/Resources/views/guidelines-resources/show.blade.php
> +            <div class="mb-4">Not in any resources</div>
```suggestion
            <div class="mb-4">No resources found</div>
```

2022-07-22 10:51 UTC, GauravGusain98 requested changes
Minor suggestions. Else looks good on code.

2022-07-22 10:51 UTC, GauravGusain98 commented on Modules/HR/Resources/views/guidelines-resources/show.blade.php
> +                    <th>Sno</th>
```suggestion
                    <th>S. no.</th>
```

2022-07-22 10:51 UTC, GauravGusain98 commented on Modules/HR/Resources/views/guidelines-resources/edit-modal.blade.php
> +                            @endforeach
```suggestion
                            @foreach ($categories as $category)
                                <option value="{{ $category->id }}">{{ $category->name }}</option>
                            @endforeach
```

2022-07-22 10:51 UTC, GauravGusain98 commented on Modules/HR/Http/Controllers/ResourcesController.php
> +
```suggestion
    public function show(Job $job)
    {

```
This will directly give you the object Job whose Id you have passed. You just need to check if in route the variable name should also be job i.e same as the variable name you have used in Controller

2022-07-22 11:13 UTC, P4NK4J reviewed
Looks good.

2022-07-22 11:13 UTC, P4NK4J approved these changes

2022-07-22 13:05 UTC, GauravGusain98 reviewed
please ceck the comment

2022-07-22 13:05 UTC, GauravGusain98 commented on Modules/HR/Http/Controllers/ResourcesController.php
>      {
Why have you removed the Job object

2022-07-22 14:19 UTC, JCArya commented on Modules/HR/Http/Controllers/ResourcesController.php
>      {
If I add a class there, then our resources are not being loaded, and the error is coming.

2022-07-25 06:35 UTC, GauravGusain98 approved these changes
Looks fine

2022-07-25 06:35 UTC, merged