1920-fixing-allignment-of-effortsheet-and-status-button
ColoredCow/portal pull request #1926
Opened 2022-07-20 12:48 UTC by chetanbhatt10

Targets #{1920}

### Description
the issue in crm->project section that efforts are unalligned for the team members. is solved

### Checklist:

- [ ] I have performed a self-review of my own code.

2022-07-20 13:02 UTC, GauravGusain98 requested changes
Please check the comments.

2022-07-20 13:26 UTC, chetanbhatt10 commented on Modules/Project/Resources/views/show.blade.php
> +                            <label for="name" class="mt- -2 font-weight-bold">Status:</label>
@GauravGusain98 that was a mistake sir, I removed it

2022-07-21 16:56 UTC, GauravGusain98 approved these changes
Looks fine

2022-07-21 16:56 UTC, GauravGusain98 approved these changes
Looks fine

2022-07-21 16:57 UTC, merged