Added a bulk applications upload feature
ColoredCow/portal pull request #1934
Opened 2022-07-21 07:18 UTC by Bahugunajii

Targets #{ISSUE_ID}

### Description

### Checklist:

- [ ] I have performed a self-review of my own code.

2022-08-08 18:03 UTC, P4NK4J requested changes
A couple of testing feedbacks
1. Update sample excel file for correct data format
2. MoveFilesToWordPress.php, we don’t need to call that when we are using bulk import
3. The following error appears when an application is directly moved from Resume Screening to Telephonic interview. It seems that it looks out for marks corresponding to round 1 as well.
<img width="1435" alt="image" src="https://user-images.githubusercontent.com/35001775/183483549-b3cfb9aa-5756-4966-8a61-bfadbbc28dff.png">

2022-08-11 07:20 UTC, P4NK4J requested changes
Minor suggestions, else looks good.

2022-08-11 07:20 UTC, P4NK4J commented on Modules/HR/Http/Controllers/EvaluationController.php
> +        }
Let's not use round ID here, it may vary for different databases. Instead, can we check it with Round Name? Because Round Names can be updated from the database if are inconsistent, but ID will create issues with the other rows as well ?

2022-08-11 07:20 UTC, P4NK4J commented on Modules/HR/Resources/views/application/render-application-row.blade.php
> +                            ($attampt = optional($application->latestApplicationRound->followUps)->count()))
Let's rename this to $attempt

2022-08-11 07:52 UTC, GauravGusain98 requested changes
Minor suggestions, else looks fine.

2022-08-11 07:52 UTC, GauravGusain98 commented on Modules/HR/Config/config.php
> +        'cutoffScore-telephonic-interview' => 5,
Let's follow one convention only
```suggestion
        'cut-off-score-resume-screening' => 6,
        'cut-off-score-telephonic-interview' => 5,
```

Please fix this at other places as well

2022-08-11 07:52 UTC, GauravGusain98 commented on resources/views/hr/application/evaluation-form.blade.php
> +    @if ($applicationRound->hr_round_id == 14)
Lets not harcode the id of a round as it may change in future. Maybe you can use the round name instead

2022-08-11 15:30 UTC, P4NK4J approved these changes
Looks good.

2022-08-11 16:13 UTC, GauravGusain98 approved these changes
looks good

2022-08-11 16:54 UTC, merged