Feature/render the data of invoice mails table in UI
ColoredCow/portal pull request #1975
Opened 2022-07-22 17:57 UTC by amisha296

Targets #1959 
<https://github.com/ColoredCow/portal/issues/1960>
<https://github.com/ColoredCow/portal/issues/1961>
<https://github.com/ColoredCow/portal/issues/1962>

### Description
I have made a modal named preview mails where I stored all the data of the invoice_mails table

### Checklist:
 I have performed a self-review of my own code.

2022-07-24 09:17 UTC, amisha296 commented
@GauravGusain98 I have made the suggested changes, here is how my UI looking now:

![Screenshot (108)](https://user-images.githubusercontent.com/90472056/180640517-7839660b-1b1d-4649-a024-84ae585ad6c2.png)

![Screenshot (109)](https://user-images.githubusercontent.com/90472056/180640522-b74507db-da30-4145-be4a-4b4008c637a8.png)

2022-07-25 06:44 UTC, P4NK4J requested changes
@amisha296 I see there are some merge conflicts in your PR. Please fix them and assign for review

2022-07-25 08:28 UTC, amisha296 commented
@P4NK4J I have resolved the merge conflict can you check it now?

2022-07-25 12:31 UTC, P4NK4J requested changes
Left some comments, please check

2022-07-25 12:31 UTC, P4NK4J commented on Modules/Invoice/Entities/Invoice.php
> +    public function invoiceOfInvoiceTypeMail()
Why don't we need `getTotalAmountAttribute()` now ? I see they both are different functions. Also, can we rename the function to `getInvoiceTypeMail()` ?

2022-07-25 12:31 UTC, P4NK4J commented on Modules/Invoice/Entities/Invoice.php
> +    public function confirmationMail()
Can we rename it to `getInvoiceConfirmationMail()` ?

2022-07-25 12:31 UTC, P4NK4J commented on Modules/Invoice/Entities/Invoice.php
> +    public function latestReminder()
can we rename it to `getInvoiceLatestReminderMail()` ?

2022-07-25 12:31 UTC, P4NK4J commented on Modules/Invoice/Resources/views/modals/email-details.blade.php
> +                        <form action="" method="POST">
Why we don't need action on this form. ?

2022-07-25 12:31 UTC, P4NK4J commented on Modules/Invoice/Resources/views/modals/email-details.blade.php
> +                                            <span style="font-weight: bold">Sent on:</span>
Let's avoid using style tags here, instead let's use bootstrap classes or app.scss

2022-07-25 12:31 UTC, P4NK4J commented on Modules/Invoice/Resources/views/modals/email-details.blade.php
> +                                                    <textarea type="text" placeholder="{{ $email ['body'] }}" rows="10" class=" form-control" disabled></textarea>
```suggestion
                                                    <textarea type="text" placeholder="{{ $email['body'] }}" rows="10" class=" form-control" disabled></textarea>
```
Please change at other places as well

2022-07-25 12:31 UTC, P4NK4J commented on Modules/Invoice/Resources/views/subviews/edit/invoice-details.blade.php
> +                @if($invoice->confirmationMail() === null)
how about `@if($invoice->confirmationMail()` ?

2022-07-25 12:31 UTC, P4NK4J commented on Modules/Invoice/Services/InvoiceService.php
> +        // $pdf->generateFromHtml($html, storage_path('app' . $filePath), [], true);
Why you have commented out this code ?

2022-07-25 16:30 UTC, amisha296 commented on Modules/Invoice/Entities/Invoice.php
> +    public function invoiceOfInvoiceTypeMail()
I think this happened by mistake, I'll. make the changes.

2022-07-25 16:30 UTC, amisha296 commented on Modules/Invoice/Entities/Invoice.php
> +    public function confirmationMail()
for sure

2022-07-25 16:30 UTC, amisha296 commented on Modules/Invoice/Entities/Invoice.php
> +    public function latestReminder()
okay

2022-07-25 16:32 UTC, amisha296 commented on Modules/Invoice/Resources/views/modals/email-details.blade.php
> +                        <form action="" method="POST">
I think because it not going anywhere, this is only showing the data no action is being performed after rendering the data.

2022-07-25 16:32 UTC, amisha296 commented on Modules/Invoice/Resources/views/modals/email-details.blade.php
> +                                            <span style="font-weight: bold">Sent on:</span>
okay\

2022-07-25 16:33 UTC, amisha296 commented on Modules/Invoice/Resources/views/modals/email-details.blade.php
> +                                                    <textarea type="text" placeholder="{{ $email ['body'] }}" rows="10" class=" form-control" disabled></textarea>
okay okay

2022-07-25 16:34 UTC, amisha296 commented on Modules/Invoice/Services/InvoiceService.php
> +        // $pdf->generateFromHtml($html, storage_path('app' . $filePath), [], true);
This code was throwing an error while running my code so I commented that out and forgot to uncomment...

2022-07-25 16:34 UTC, amisha296 commented on Modules/Invoice/Resources/views/subviews/edit/invoice-details.blade.php
> +                @if($invoice->confirmationMail() === null)
yess

2022-07-25 16:47 UTC, P4NK4J approved these changes
Looks good.

2022-07-26 06:38 UTC, GauravGusain98 commented
Merging in the base branch. Will review together

2022-07-26 06:38 UTC, merged