Project Level Invoice Generation
ColoredCow/portal pull request #1984
Opened 2022-07-23 18:06 UTC by GauravGusain98

Targets #1635 

### Description

- Functionality to Show client level and project level ready to send Invoices
- Functionality to create project level billing invoice

### Checklist:

- [ ] I have performed a self-review of my own code.

2022-07-23 18:09 UTC, GauravGusain98 commented on Modules/Invoice/Resources/views/index.blade.php
> +                                    {{-- <i class="pt-1 ml-1 fa fa-external-link-square" data-toggle="modal" data-target="#InvoiceDetailsForClient{{ $client->id }}"></i> --}}
Commented as this feature is only built for client level projects

2022-07-23 19:27 UTC, rathorevaibhav requested changes

2022-07-23 19:27 UTC, rathorevaibhav commented on Modules/Client/Entities/Client.php
> +    public function getClientMonthStartDateAttribute($monthsToSubtract)
```suggestion
    public function getMonthStartDateAttribute($monthsToSubtract)
```

2022-07-23 19:27 UTC, rathorevaibhav commented on Modules/Client/Entities/Client.php
> +        $monthsToSubtract = $monthsToSubtract ?? 0;
why default value is zero here and `1` at other places?

Also, let's remove this line and set default value at function param level.

2022-07-23 19:27 UTC, rathorevaibhav commented on Modules/Client/Entities/Client.php
> +            if (today(config('constants.timezone.indian'))->subMonthsNoOverflow($monthsToSubtract + 1)->addDays($billingDate - today(config('constants.timezone.indian'))->day) > today(config('constan
I don't think we need to hardcode `constants.timezone.indian` anywhere if we set the APP_TIMEZONE in the env file to IST.

We would need a single timezone in the application and I think we can keep it IST. I believe we also need to ensure what is the timezone for our DB server. It should be IST as well.

What do you think?

2022-07-23 19:27 UTC, rathorevaibhav commented on Modules/Client/Entities/Client.php
> +            if (today(config('constants.timezone.indian'))->subMonthsNoOverflow($monthsToSubtract + 1)->addDays($billingDate - today(config('constants.timezone.indian'))->day) > today(config('constan
I just checked our servers. We have APP_TIMEZONE set to `Asia/Calcutta`.

Maybe it'll be better if you make these three changes in your PR:
1. Set the default value of app timezone in the .env.example file to asia/kolkata
2. Set the backup value in `app.php` for timezone to asia/kolkata instead of UTC
3. As a part of deployment step, mention to change OS server and DB server timezone to same as app timezone

2022-07-23 19:31 UTC, GauravGusain98 commented on Modules/Client/Entities/Client.php
> +            return ! $date->isWeekend();
done

2022-07-23 19:35 UTC, GauravGusain98 commented on Modules/Invoice/Routes/web.php
> -    Route::post('/generate-invoice-client', 'InvoiceController@generateInvoiceForClient')->name('invoice.generate-invoice-for-client');
It is not being used anywhere

2022-07-23 19:35 UTC, GauravGusain98 commented on Modules/Project/Entities/Project.php
> +            return $query->whereMonth('sent_on', now(config('constants.timezone.indian')))->whereYear('sent_on', now(config('constants.timezone.indian')));
They are store in IST

2022-07-23 19:50 UTC, GauravGusain98 commented on Modules/Client/Entities/Client.php
> +        $monthsToSubtract = $monthsToSubtract ?? 0;
Its because for the client we usually take the dates for the current Month but at other places the functions are mostly related to invoice, so the default value was set to 1.

2022-07-23 19:54 UTC, GauravGusain98 commented on Modules/Client/Entities/Client.php
> +        $monthsToSubtract = $monthsToSubtract ?? 0;
The reason for not setting the value in the parameter at most places was that when we use this accessor like `$client->month_start_date` then the value that is set to $monthToSubtract is NULL instead of 0. And many places where the default value is 1 there the result comes incorrect. 

Apart from this at some places where there are 2 parameter, we are getting error from Larastan, and as a suggestion it is removing the value from the parameter.

2022-07-24 19:17 UTC, rathorevaibhav approved these changes

2022-07-24 19:21 UTC, merged