1991-removing-error-displayed-in-NDA-template
ColoredCow/portal pull request #2010
Opened 2022-07-26 10:09 UTC by chetanbhatt10

Targets #{1991}

### Description
While opening NDA template we fixed error 

### Checklist:

- [ ] I have performed a self-review of my own code.

2022-07-26 11:11 UTC, GauravGusain98 reviewed
Please check the comment

2022-07-26 11:11 UTC, GauravGusain98 commented on resources/views/settings/agreement/nda/index.blade.php
> +            @endif
What is this logic doing? Can you explain?

2022-07-26 11:19 UTC, chetanbhatt10 commented on resources/views/settings/agreement/nda/index.blade.php
> +            @endif
This is Removing  error message  and helps to access body and subject from array whenever needed

2022-07-26 11:20 UTC, chetanbhatt10 commented on resources/views/settings/agreement/nda/index.blade.php
> +            @endif
To check if there is any empty subject and body in any section if it is empty then don't do anything

2022-07-26 17:26 UTC, GauravGusain98 requested changes
Please check the comment.

2022-07-26 17:26 UTC, GauravGusain98 commented on resources/views/settings/agreement/nda/index.blade.php
> +                                    <input type="text" name="round_mail_subject" class="form-control" value="{{ $mailSubject }}">
You can use it like this as well. 
```suggestion
                                    <input type="text" name="round_mail_subject" class="form-control" value="{{ $round->{$mailTemplate}['subject'] ?? '' }}">
```

Just try it once.

2022-07-26 17:26 UTC, GauravGusain98 commented on resources/views/settings/agreement/nda/index.blade.php
> +                                        <textarea name="round_mail_body" rows="10" class="richeditor form-control" placeholder="Body">{{ $mailBody }}</textarea>
```suggestion
                                        <textarea name="round_mail_body" rows="10" class="richeditor form-control" placeholder="Body">{{ $round->{$mailTemplate}['body'] ?? '' }}</textarea>
```

2022-07-27 05:38 UTC, P4NK4J approved these changes
Looks good.

2022-07-27 06:07 UTC, GauravGusain98 reviewed
Looks fine

2022-07-27 06:07 UTC, GauravGusain98 approved these changes

2022-07-27 06:07 UTC, merged