Backend validation for evaluation segments
ColoredCow/portal pull request #2022
Opened 2022-07-27 05:53 UTC by NirmalNegi07

#1924

### Description
 Frontend validation is not that much fast and secure so I have applied backend validation in Segment modal along with ajax form submission.
AJAX is a technique for creating fast and dynamic web pages.
AJAX allows web pages to be updated asynchronously by exchanging small amounts of data with the server behind the scenes. This means that it is possible to update parts of a web page, without reloading the whole page.

### Checklist:
- [x] I have performed a self-review of my own code.

2022-07-27 06:06 UTC, kuldeep3 commented
@NirmalNegi07 There are conflicting files in this PR. Please fix this and then assign it for review.

2022-07-27 10:56 UTC, GauravGusain98 requested changes
Please check the comment

2022-07-27 10:56 UTC, GauravGusain98 commented on Modules/HR/Http/Requests/ManageEvaluationRequest.php
> +            'rounds' => 'required',
Can you also add a datatype check here, as you did with `name`

2022-07-27 10:56 UTC, GauravGusain98 commented on Modules/HR/Resources/views/evaluation/index.blade.php
> +        </div><br><br> --}}
If this is not needed then please remove this

2022-07-27 10:56 UTC, GauravGusain98 commented on resources/js/app.js
> +				}
Instead of showing and hiding the error div you should set the text of the div based on the errors message that you get from `response.responseJSON.errors.`

This way we can show different messages in future when we add more fields, without updating the logic. 

**Action items**
Just create an empty div and show the errors messages received in the error in that div using jS

2022-07-31 06:42 UTC, GauravGusain98 requested changes
PLease check the comments and remove the package.lock.json file from you code changes. Only the files related to your tasks should be committed to GitHub

2022-07-31 06:42 UTC, GauravGusain98 commented on Modules/HR/Http/Requests/ManageEvaluationRequest.php
> +            'rounds' => 'required|string    ',
```suggestion
            'rounds' => 'required|string',
```

2022-07-31 06:42 UTC, GauravGusain98 commented on resources/js/app.js
> +					console.log(error);
remove console log

2022-07-31 06:42 UTC, GauravGusain98 commented on resources/js/app.js
> +		console.log($("#segmentError"));
remove console log

2022-08-02 09:37 UTC, GauravGusain98 approved these changes
Looks fine

2022-08-02 09:37 UTC, merged