Add backend validation while adding a invoice
ColoredCow/portal pull request #2031
Opened 2022-07-27 08:24 UTC by Ayushigupta2

Target #{1939}

### Description
 I have added backend validation on all the data coming in the  add new invoice form.
 Applied old function on all the data in the form 

### Checklist:

- [ ] I have performed a self-review of my own code.

2022-07-27 10:24 UTC, GauravGusain98 requested changes
Please fix merge conflicts and check the comment

2022-07-27 10:24 UTC, GauravGusain98 commented on Modules/Invoice/Http/Controllers/InvoiceController.php
> +     * @param \Modules\Invoice\Http\Requests\StorePostRequest $request
```suggestion
     * @param StorePostRequest $request
```

2022-07-27 10:24 UTC, GauravGusain98 commented on Modules/Invoice/Resources/views/subviews/create/invoice-details.blade.php
> +                    <textarea name="comments" id="comments" rows="5" class="form-control">{{old('comments') }}</textarea>
```suggestion
                    <textarea name="comments" id="comments" rows="5" class="form-control">{{ old('comments') }}</textarea>
```

2022-07-27 10:24 UTC, GauravGusain98 commented on Modules/Invoice/Resources/views/subviews/create/invoice-details.blade.php
> +                        <option value="sent" {{ old('status')=="sent" ? "selected" : ''}}>Sent</option>
```suggestion
                        <option value="sent" {{ old('status')=="sent" ? "selected" : '' }}>Sent</option>
```

2022-07-27 10:24 UTC, GauravGusain98 commented on Modules/Invoice/Resources/views/subviews/create/invoice-details.blade.php
> +                        <option value="paid" {{ old('status')=="paid" ? "selected" : ''}}>Paid</option>
```suggestion
                        <option value="paid" {{ old('status')=="paid" ? "selected" : '' }}>Paid</option>
```

2022-07-27 10:24 UTC, GauravGusain98 commented on Modules/Invoice/Http/Requests/StorePostRequest.php
> +        ];
```suggestion
        $rules = [
            'client_id' =>'required|integer',
            'billing_level' => 'required|string',
            'status' => 'required|string',
            'currency' => 'required|string',
            'comments' => nullable|string",
            'amount' => 'required|numeric',
            'gst' =>'required|numeric',
            'term' => 'required',
            'sent_on' => 'required|date',
            'due_on' => 'required|date',
            'invoice_file' =>'required|mimes:pdf',
        ];
```

2022-07-27 10:24 UTC, GauravGusain98 commented on Modules/Invoice/Resources/views/subviews/create/invoice-details.blade.php
> +                        value="{{ old('sent_on', now()->format('Y-m-d'))}}">
```suggestion
                        value="{{ old('sent_on', now()->format('Y-m-d')) }}">
```

2022-07-27 11:33 UTC, Ayushigupta2 commented on Modules/Invoice/Http/Requests/StorePostRequest.php
> +        ];
Done with suggested changes

2022-07-31 06:36 UTC, GauravGusain98 requested changes
Please make the required changes and fix merge conflicts

2022-07-31 06:36 UTC, GauravGusain98 commented on Modules/Invoice/Http/Requests/StorePostRequest.php
> +        ];
The changes requested earlier to this file is not done.

2022-08-02 09:59 UTC, Ayushigupta2 commented on Modules/Invoice/Http/Requests/StorePostRequest.php
> +        ];
done with these changes now
i am getting problem in resolving conflicts i have take pull from master and accept both changes and then commited there only and changes total 190 files so i reset commit to old commit.

2022-08-08 06:17 UTC, GauravGusain98 commented on Modules/Invoice/Http/Controllers/InvoiceController.php
> +    public function store(StorePostRequest $request)
Why we are using `StorePostRequest`? What does it do?

2023-04-07 12:05 UTC, closed without merging