Fix/1935
ColoredCow/portal pull request #2042
Opened 2022-07-28 05:40 UTC by parasnegi2002

Targets #1935

### Description
- fixed tag in project

### Checklist:

- [ ] I have performed a self-review of my own code.

2022-08-02 07:34 UTC, GauravGusain98 requested changes
Please check the comment

2022-08-02 07:34 UTC, GauravGusain98 commented on Modules/Project/Resources/views/index.blade.php
> +									@endforeach
Also use the bootstrap classes instead of style tag. We avoid writing CSS code in blade write.

2022-08-02 07:34 UTC, GauravGusain98 commented on Modules/Project/Resources/views/show.blade.php
> +							@endforeach
remove this as we don't want to show label in this file.

2022-08-02 07:34 UTC, GauravGusain98 commented on Modules/Project/Services/ProjectService.php
> +        });
We don't want to tag and untag whenever the we are opening the page

2022-08-08 07:30 UTC, P4NK4J reviewed
Left a comment please check.

2022-08-08 07:30 UTC, P4NK4J commented on Modules/Project/Services/ProjectService.php
> +
If only effortsheet URL is not present, that doesn't mean, project is not available in the system ? I think there is something missing here. Can you share some details, why we are doing this ?

2022-08-09 07:23 UTC, GauravGusain98 requested changes
Please check the comments.

2022-08-09 07:23 UTC, GauravGusain98 commented on Modules/Project/Resources/views/index.blade.php
> +									@endforeach
ok, cool, just fix the formatting then

2022-08-09 07:23 UTC, GauravGusain98 commented on Modules/Project/Resources/views/show.blade.php
> +                        @endif
Revert this change, we need the Not available status

2022-08-09 07:23 UTC, GauravGusain98 commented on Modules/Project/Services/ProjectService.php
> +
@parasnegi2002 Don't tag or untag tags inside this file. For that I'll assign you next action item. Please remove the code at all the places where you are tagging or untagging tags to a project.

2022-08-09 07:23 UTC, GauravGusain98 commented on Modules/Project/Services/ProjectService.php
> +        }
Same here

2022-08-09 07:23 UTC, GauravGusain98 commented on Modules/Project/Services/ProjectService.php
> +            $project->untag('no-contract');
Same here

2023-04-07 12:05 UTC, closed without merging