Cypress automated test cases
ColoredCow/portal pull request #2074
Opened 2022-07-30 16:23 UTC by deepankar-sajwan

Test cases for login to portal based on user role

2022-07-31 06:02 UTC, rathorevaibhav requested changes

2022-07-31 06:02 UTC, rathorevaibhav commented on cypress/integration/login/login.spec.js
> +    cy.contains('Dashboard')
let's remove this. We will eventually remove the dashboard text from the landing page for a person with no roles.

2022-07-31 06:02 UTC, rathorevaibhav commented on cypress/integration/login/login.spec.js
> +it("logs in the admin user", () => {
please fix indentation

2022-07-31 06:02 UTC, rathorevaibhav commented on cypress/integration/login/login.spec.js
> +  cy.get('ul.navbar-nav').contains('CRM'); // employee should see CRM
the comment requires an update here. please update at other places also
```suggestion
  cy.get('ul.navbar-nav').contains('CRM'); // admin should see CRM
```

2022-07-31 06:02 UTC, rathorevaibhav commented on cypress/integration/login/login.spec.js
> +  cy.get('ul.navbar-nav').contains('KnowledgeCafe'); // employee should see KnowledgeCafe
please add check for other areas like Finance, HR for admins and super-admins

2022-07-31 06:02 UTC, rathorevaibhav commented on cypress/integration/login/login.spec.js
> +  cy.get('ul.navbar-nav').contains('KnowledgeCafe'); // employee should see KnowledgeCafe
Superadmins should see the user management dropdown also. Please add that check.

2022-07-31 06:02 UTC, rathorevaibhav commented on cypress/integration/login/login.spec.js
> +it("logs in the superadmin user", () => {
fix indentation

2022-07-31 06:02 UTC, rathorevaibhav commented on cypress.json.example
> +  "baseUrl": "https://portal.test",
I think changing this back to the original `baseUrl` will help the CI running
```suggestion
  "baseUrl": "http://127.0.0.1:8000",
```

2022-07-31 06:07 UTC, deepankar-sajwan commented on cypress/integration/login/login.spec.js
> +    cy.contains('Dashboard')
Done

2022-07-31 06:10 UTC, deepankar-sajwan commented on cypress/integration/login/login.spec.js
> +it("logs in the admin user", () => {
Done!

2022-07-31 06:11 UTC, deepankar-sajwan commented on cypress/integration/login/login.spec.js
> +  cy.get('ul.navbar-nav').contains('CRM'); // employee should see CRM
done

2022-07-31 06:18 UTC, deepankar-sajwan commented on cypress/integration/login/login.spec.js
> +it("logs in the superadmin user", () => {
Done

2022-07-31 11:15 UTC, deepankar-sajwan commented on cypress/integration/login/login.spec.js
> +  cy.get('ul.navbar-nav').contains('KnowledgeCafe'); // employee should see KnowledgeCafe
done

2022-07-31 11:21 UTC, deepankar-sajwan commented on cypress/integration/login/login.spec.js
> +  cy.get('ul.navbar-nav').contains('KnowledgeCafe'); // employee should see KnowledgeCafe
done

2022-08-01 05:22 UTC, rathorevaibhav approved these changes

2022-08-01 05:22 UTC, merged