feature/1922/hours_column_contain_expected_no._of_days
ColoredCow/portal pull request #2099
Opened 2022-08-02 08:44 UTC by saurabhpatel123456

Targets #1922 

### Description
Hours column contains day column
### Checklist:

- [ ] I have performed a self-review of my own code.

2022-08-02 09:18 UTC, P4NK4J reviewed
Left a comment, please check.

2022-08-02 09:18 UTC, P4NK4J commented on Modules/EffortTracking/Resources/views/show.blade.php
> +                                    (1 Days)
Why we have hardcoded this data ?

2022-08-02 09:35 UTC, saurabhpatel123456 commented on Modules/EffortTracking/Resources/views/show.blade.php
> +                                    (1 Days)
for insertion of day column into hours column, and also for changes in fte page as well as final page by providing  user input.

2022-08-07 17:18 UTC, GauravGusain98 requested changes
PLease check the comments.

2022-08-07 17:18 UTC, GauravGusain98 commented on Modules/EffortTracking/Resources/views/show.blade.php
> +                            {{-- @dd($project) --}}
Remove this commented line

2022-08-07 17:18 UTC, GauravGusain98 commented on Modules/EffortTracking/Services/EffortTrackingService.php
> +        $daysTillToday = count($project->getWorkingDaysList($project->client->month_start_date, $currentDate));
How come these 2 functions `getWorkingDaysList`, `getworkingDays` doing the same thing? Do we have duplicate functions?

2022-08-08 05:51 UTC, saurabhpatel123456 commented on Modules/EffortTracking/Resources/views/show.blade.php
> +                            {{-- @dd($project) --}}
ok, done.

2022-08-08 05:51 UTC, saurabhpatel123456 commented on Modules/EffortTracking/Services/EffortTrackingService.php
> +        $daysTillToday = count($project->getWorkingDaysList($project->client->month_start_date, $currentDate));
no, both function performs different things. the getworkingdayslist used to call daystilltoday function.

2022-08-08 06:45 UTC, GauravGusain98 requested changes
PLease check the comment

2022-08-08 06:45 UTC, GauravGusain98 commented on Modules/EffortTracking/Resources/views/show.blade.php
> +                            {{-- @dd($project) --}}
You have not committed this I guess. It is still showing in the chnages

2022-08-09 07:26 UTC, GauravGusain98 requested changes
Minor feedbacks. Else looks good. Will approve once the changes are fixed

2022-08-09 07:26 UTC, GauravGusain98 commented on Modules/EffortTracking/Services/EffortTrackingService.php
> +                     'sheet_index_for_billable_effort' => $sheetIndexForTotalBillableEffort,
Fix the formatting

2022-08-09 08:09 UTC, GauravGusain98 approved these changes
Looks fine

2022-08-09 08:09 UTC, merged