Count of resources needed in job opportunities
ColoredCow/portal pull request #2100
Opened 2022-08-02 09:19 UTC by LavishRawat

Targets #1964 

### Description
Count of resources needed in job opportunities

### Checklist:
- [ ] I have performed a self-review of my own code.

2022-08-02 11:22 UTC, P4NK4J commented
@LavishRawat As shared on Google chat, we need to make some edits to avoid the breakdown of Job Observer functionality. Let me know if you would be having any questions.

2022-08-02 11:22 UTC, P4NK4J requested changes
Requesting changes as per the comments

2022-08-07 17:04 UTC, P4NK4J requested changes
@LavishRawat The error remains the same, upon editing the count of resources required. Please take a look. Also, in the edit functionality, the counter is not coming prefilled in the form, if there exists a value.

2022-08-09 16:55 UTC, P4NK4J requested changes
@LavishRawat Based on our conversation offline, please add null checks in the job observer, where ID and status are fetched.

2022-08-10 10:26 UTC, P4NK4J requested changes
overall looks good, left some comments.

2022-08-10 10:26 UTC, P4NK4J commented on Modules/HR/Http/Controllers/Recruitment/ApplicationController.php
> +            $attr[camel_case($string) . 'ApplicationsCount'] = $query->count();
Why do we need this change ?

2022-08-10 10:26 UTC, P4NK4J commented on Modules/HR/Routes/web.php
> +            Route::post('opportunities/{opportunity}/updateResources', 'RecruitmentOpportunityController@updateResources')->name('recruitment.opportunities.updateResources');
Let's rename this route to something meaninful, say `update-resources-count`

2022-08-10 10:26 UTC, P4NK4J commented on Modules/HR/Http/Controllers/Recruitment/RecruitmentOpportunityController.php
> +    public function updateResources(HttpRequest $request, Job $opportunity)
Let's rename this function to `resourcesRequiredCount`

2022-08-10 12:07 UTC, LavishRawat commented on Modules/HR/Http/Controllers/Recruitment/ApplicationController.php
> +            $attr[camel_case($string) . 'ApplicationsCount'] = $query->count();
These changes doesn't affect anything so reverting back to previous code .

2022-08-11 06:07 UTC, P4NK4J approved these changes
Left a suggestion, else looks good.

2022-08-11 06:07 UTC, P4NK4J commented on Modules/HR/Observers/Recruitment/JobObserver.php
> +        $corcel->post_status = (config('hr.opportunities-status-wp-mapping')[$job_status]);
How about ?
```suggestion
        $corcel->post_status = $job_status ? (config('hr.opportunities-status-wp-mapping')[$job_status]) : 'draft';
```

2022-08-11 06:07 UTC, P4NK4J commented on Modules/HR/Observers/Recruitment/JobObserver.php
> +        }
Seems like it can be resolved using simple ternary operator suggested below, can we remove this ?

2022-08-11 07:02 UTC, merged