timeline and last refreshed add in project
ColoredCow/portal pull request #2119
Opened 2022-08-03 11:40 UTC by tarunnjoshi

#2039

### Description
The timeline and last refresh at  available in the project details 

### Checklist:

- [ X] I have performed a self-review of my own code.

2022-08-04 10:11 UTC, GauravGusain98 requested changes
Please check the comment

2022-08-04 10:11 UTC, GauravGusain98 commented on Modules/EffortTracking/Resources/views/show.blade.php
> +                               <strong>Timeline:</strong> {{ config('project.meta_keys.project.key') . __(''). (Carbon\Carbon::parse($project->client->month_start_date )->format('dS M'))}}
What is this `config('project.meta_keys.project.key') . __('')` doing?

2022-08-04 10:11 UTC, GauravGusain98 commented on Modules/EffortTracking/Resources/views/show.blade.php
> +                                {{ config('project.meta_keys.project.key') . __(' - ') . (Carbon\Carbon::parse($project->client->month_end_date)->format('dS M'))}}
Same here

2022-08-04 10:54 UTC, tarunnjoshi commented on Modules/EffortTracking/Resources/views/show.blade.php
> +                               <strong>Timeline:</strong> {{ config('project.meta_keys.project.key') . __(''). (Carbon\Carbon::parse($project->client->month_start_date )->format('dS M'))}}
This code was used previously that's why i used it but without this code it will work properly.

2022-08-08 07:10 UTC, srivastava-jyoti commented on Modules/EffortTracking/Resources/views/show.blade.php
> +                            <strong>Last refreshed at:</strong>{{(Carbon\Carbon::parse($project->last_updated_at)->setTimezone('Asia/Kolkata')->format(' Y-M-d , D h:i:s A'))}}
```suggestion
                            <strong>Last refreshed at:</strong>{{ (Carbon\Carbon::parse($project -> last_updated_at) -> setTimezone('Asia/Kolkata') -> format(' Y-M-d , D h:i:s A')) }}
```

2022-08-08 07:11 UTC, srivastava-jyoti commented on Modules/EffortTracking/Resources/views/show.blade.php
> +                            <strong>Timeline:</strong>{{(Carbon\Carbon::parse($project->client->month_start_date )->format('dS M'))}}
Same spacing fixes here also

2022-08-08 07:12 UTC, srivastava-jyoti commented on Modules/Project/Resources/views/show.blade.php
> +                            <strong>Timeline:</strong> {{(Carbon\Carbon::parse($project->client->month_start_date)->format('dS M'))}}
Please correct formatting at all places

2022-08-08 07:15 UTC, srivastava-jyoti commented on Modules/Project/Resources/views/show.blade.php
> +                            -{{(Carbon\Carbon::parse($project->client->month_end_date)->format('dS M'))}}
Can you give one example of this format `format('dS M')` in the comment itself?

2022-08-08 07:42 UTC, tarunnjoshi commented on Modules/Project/Resources/views/show.blade.php
> +                            -{{(Carbon\Carbon::parse($project->client->month_end_date)->format('dS M'))}}
ds show the date and M show the month of that project.
"09th Jul" like this

2022-08-08 08:07 UTC, GauravGusain98 requested changes
Please check the comments.

2022-08-08 08:07 UTC, GauravGusain98 commented on Modules/Project/Resources/views/show.blade.php
> +                            <strong>Timeline:</strong>{{ (Carbon\Carbon::parse($project -> client -> month_start_date) -> format('dS M')) }}
```suggestion
                            <strong>Timeline:</strong>{{ (Carbon\Carbon::parse($project->client->month_start_date)->format('dS M')) }}                       
```

2022-08-08 08:07 UTC, GauravGusain98 commented on Modules/Project/Resources/views/show.blade.php
> +                            -{{ (Carbon\Carbon::parse($project -> client -> month_end_date) -> format('dS M')) }}
Same here

2022-08-08 08:07 UTC, GauravGusain98 commented on Modules/EffortTracking/Resources/views/show.blade.php
> +                            -{{ (Carbon\Carbon::parse($project -> client -> month_end_date) -> format('dS M')) }}
Don't use space when using arrow 
```suggestion
                            -{{ (Carbon\Carbon::parse($project->client->month_end_date)->format('dS M')) }}              
```

2022-08-09 07:18 UTC, GauravGusain98 approved these changes
Looks fine

2022-08-09 07:18 UTC, merged