Job role engagement
ColoredCow/portal pull request #2123
Opened 2022-08-04 08:26 UTC by belwalshubham

Targets #2005 

### Description
On clicking Job-Role-Engagement- card, a horizontal bar graph should appear, indicating each job role and the number of applications we have received.

- [x] I have performed a self-review of my own code.

2022-08-07 17:01 UTC, P4NK4J reviewed
@belwalshubham Based on our offline discussion, can we make thee scale difference to 100, and apply date range filters on this PR ?

2022-08-09 16:49 UTC, P4NK4J requested changes
@belwalshubham Overall the graph looks good. The date range filters seem not to be working fine. Please check
<img width="1439" alt="image" src="https://user-images.githubusercontent.com/35001775/183710484-33c4e1b8-4691-415b-a534-c841305d850a.png">

2022-08-10 12:19 UTC, P4NK4J requested changes
Left some comments, else looks good.

2022-08-10 12:19 UTC, P4NK4J commented on Modules/HR/Http/Controllers/Recruitment/ReportsController.php
> +    public function bargraph(Request $request)
Let's rename this function to something meaningful, say `jobWiseApplicationsGraph` ?

2022-08-10 12:19 UTC, P4NK4J commented on Modules/HR/Http/Controllers/Recruitment/ReportsController.php
> +        $jobs = [];
Do we need this ? I guess the next line where you are fetching all the jobs would be sufficient

2022-08-10 12:19 UTC, P4NK4J commented on Modules/HR/Routes/web.php
> +            Route::get('bargraph', 'ReportsController@bargraph')->name('recruitment.graph');
Rename here as well `name("Put actual route name, based on what its doing")

2022-08-10 12:19 UTC, P4NK4J commented on resources/js/app.js
> +function bargraph() {
can we rename this function as well ?

2022-08-10 12:19 UTC, P4NK4J commented on resources/views/hr/recruitment/reportcard.blade.php
> +
let's remove these spaces

2022-08-10 12:23 UTC, belwalshubham commented on Modules/HR/Http/Controllers/Recruitment/ReportsController.php
> +        $jobs = [];
I use filter for fetching the application from start date to end date ....... not jobs

2022-08-10 12:28 UTC, belwalshubham commented on Modules/HR/Http/Controllers/Recruitment/ReportsController.php
> +        $jobs = [];
I use filter for applications start date to end date not for jobs

2022-08-11 08:59 UTC, P4NK4J requested changes
Left some comments, please check

2022-08-11 08:59 UTC, P4NK4J commented on Modules/HR/Http/Controllers/Recruitment/ReportsController.php
> +        return view('hr.recruitment.horizontalBarGraph')->with([
@belwalshubham This `horizontalBarGraph` can be for many modules, let's name it specific `jobWiseApplicationsGraph` instead

2022-08-11 08:59 UTC, P4NK4J commented on Modules/HR/Routes/web.php
> +            Route::get('applications/barChart', 'ReportsController@jobWiseApplicationsGraph')->name('applications.job-Wise-Applications-Graph');
```suggestion
            Route::get('applications/jobWiseApplicatonReport', 'ReportsController@jobWiseApplicationsGraph')->name('applications.job-Wise-Applications-Graph');
```

2022-08-11 09:20 UTC, P4NK4J approved these changes
Looks good.

2022-08-11 09:21 UTC, merged