The filter for selecting start date and End date for displaying FTE should be dynamic
ColoredCow/portal pull request #2140
Opened 2022-08-05 17:54 UTC by Himanshunegi0332

#1871 
### Description
Currently the filter selecting start date and End date for displaying the FTE is static, as the start date is set as 1st day of current month, and end date is set as last day of current month. Therefore only FTE of current month is displayed. Hence there is no method to check FTE of past month. 
Made it dynamic.

### Checklist:
- [X] I have performed a self-review of my own code.

2022-08-08 08:45 UTC, P4NK4J requested changes
Left some comments, overall looks good.

2022-08-08 08:45 UTC, P4NK4J commented on Modules/EffortTracking/Resources/views/show.blade.php
> +    </a>
d-flex would make the whole container full width and will lead it to be clickable, we need only space up to All projects to be clickable. The UI will show `All projects` on a small space, while the remaining space will be clickable and take users to `All projects` page. Please test it once in UI

2022-08-08 08:45 UTC, P4NK4J commented on Modules/EffortTracking/Resources/views/show.blade.php
> +                    </select>
Can we fetch it from Config ? rather than hardcoding here ? Or maybe look out for some better way to pass an array of months in the controller itself.

2022-08-08 08:45 UTC, P4NK4J commented on Modules/EffortTracking/Services/EffortTrackingService.php
> +        $currentDate = now(config('constants.timezone.indian'));
Can we fetch these variables in different function ? Let's say create a function `getFilterParameters` and return all these from there. This currently looks like a lot of things for `show()`

2022-08-10 05:11 UTC, P4NK4J requested changes
Left some comments, overall looks good.

2022-08-10 05:11 UTC, P4NK4J commented on Modules/EffortTracking/Services/EffortTrackingService.php
> +        $startDate = $project->client->getMonthStartDateAttribute($totalMonths);
Why can't we use the get attribute like `$project->client->month_start_date` here and other places?

2022-08-10 05:11 UTC, P4NK4J commented on Modules/EffortTracking/Services/EffortTrackingService.php
> +
If its returning totalMonths can we rename this function to some specific? something like `getTotalMonthsFilterParameter` ?

2022-08-10 05:37 UTC, Himanshunegi0332 commented on Modules/EffortTracking/Services/EffortTrackingService.php
> +        $startDate = $project->client->getMonthStartDateAttribute($totalMonths);
we are using $project->client->getMonthStartDateAttribute($totalMonths) because this function is made on project.php and by giving $totalMonths to this attributes helps us in getting the previous months start date and FTE also whereas by using $project->client->month_start_date  we are getting only current months start date.

2022-08-10 05:39 UTC, Himanshunegi0332 commented on Modules/EffortTracking/Services/EffortTrackingService.php
> +
ok sir.

2022-08-10 06:20 UTC, P4NK4J approved these changes
Looks good.

2022-08-10 06:20 UTC, merged