Manage segments round wise
ColoredCow/portal pull request #2144
Opened 2022-08-06 12:25 UTC by jaskaransingh304

Targets #2097 

### Description

I have classified segments on the basis of rounds.

Whenever user selects a particular round, segments related  to it get displayed.

### Checklist:

- [ ] I have performed a self-review of my own code.

2022-08-07 16:41 UTC, P4NK4J requested changes
@Jaskaran Singh Good attempt. Let's restore back the edit functionality. Currently, the edit form is not working as it was working earlier. 
Also, let's remove the borders above and below each accordion header
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/35001775/183301535-7f3fc1f1-d393-4e2e-8ed1-a27bbe1b8e81.png">

2022-08-09 11:16 UTC, P4NK4J requested changes
@jaskaransingh304 Functionality looks good. Left some comments on the PR

2022-08-09 11:16 UTC, P4NK4J commented on Modules/HR/Http/Controllers/EvaluationController.php
> +    public function createSegment(Request $request)
Why we are changing the request type here ?

2022-08-09 11:16 UTC, P4NK4J commented on Modules/HR/Resources/views/evaluation/index.blade.php
>          <div class="d-flex justify-content-between">
This is a success message, when a segment is created, this message pops up. Please don't remove this

2022-08-09 11:16 UTC, P4NK4J commented on Modules/HR/Resources/views/evaluation/index.blade.php
> +
Let's remove unwanted spaces

2022-08-09 11:16 UTC, P4NK4J commented on Modules/HR/Resources/views/evaluation/index.blade.php
> +                        <div class="col-md-2">
Indentation is badly off, please fix this

2022-08-09 11:16 UTC, P4NK4J commented on Modules/HR/Resources/views/evaluation/index.blade.php
> +                    <h5></h5>
Please fix the indentation here as well

2022-08-10 09:44 UTC, jaskaransingh304 commented on Modules/HR/Resources/views/evaluation/index.blade.php
>          <div class="d-flex justify-content-between">
Sure.

2022-08-10 09:44 UTC, jaskaransingh304 commented on Modules/HR/Http/Controllers/EvaluationController.php
> +    public function createSegment(Request $request)
Fixed it.

2022-08-10 09:44 UTC, jaskaransingh304 commented on Modules/HR/Resources/views/evaluation/index.blade.php
> +
Ok.

2022-08-10 09:45 UTC, jaskaransingh304 commented on Modules/HR/Resources/views/evaluation/index.blade.php
> +                        <div class="col-md-2">
Done.

2022-08-10 09:45 UTC, jaskaransingh304 commented on Modules/HR/Resources/views/evaluation/index.blade.php
> +                    <h5></h5>
Done.

2022-08-10 10:45 UTC, P4NK4J reviewed
Minor comments, else looks good.

2022-08-10 10:45 UTC, P4NK4J commented on Modules/HR/Resources/views/evaluation/index.blade.php
> +                    @if($round->id == $segment->round_id )
What would happen if there are no segments corresponding to rounds ?

2022-08-10 10:45 UTC, P4NK4J commented on Modules/HR/Resources/views/evaluation/index.blade.php
> +                            @if($round->id == $segment->round_id )
What if there are not segments available ?

2022-08-10 11:49 UTC, jaskaransingh304 commented on Modules/HR/Resources/views/evaluation/index.blade.php
> +                    @if($round->id == $segment->round_id )
Then round name won't get displayed. Because if there is corresponding segment , then only it gets displayed.

2022-08-10 11:52 UTC, jaskaransingh304 commented on Modules/HR/Resources/views/evaluation/index.blade.php
> +                            @if($round->id == $segment->round_id )
If there is no segment available sir. Then also round name won't get displayed . As the round and segment are associated through id. So if there is no match. It won't get displayed.

2022-08-10 12:04 UTC, P4NK4J requested changes
Left a comment, please check

2022-08-10 12:04 UTC, P4NK4J commented on Modules/HR/Resources/views/evaluation/index.blade.php
> +                    @if($round->id == $segment->round_id )
Let's fetch segments corresponding to the round through an eloquent relationship. This way we won't have to iterate all the segments present in the system

2022-08-10 12:09 UTC, jaskaransingh304 commented on Modules/HR/Resources/views/evaluation/index.blade.php
> +                    @if($round->id == $segment->round_id )
OK , I will try.

2023-04-07 12:05 UTC, closed without merging