2088
ColoredCow/portal pull request #2147
Opened 2022-08-06 17:08 UTC by Jkishan544

Targets #{ISSUE_ID}

### Description

### Checklist:

- [ ] I have performed a self-review of my own code.

2022-08-07 16:47 UTC, P4NK4J requested changes
Left some comments, please check

2022-08-07 16:47 UTC, P4NK4J commented on resources/views/hr/menu.blade.php
> +            <a class="nav-item nav-link"style="color:blue;"><i class="fa fa-bitbucket" aria-hidden="true"></i>&nbsp;Total Count</a>
Let's remove the inline style from here and use bootstrap classes.

2022-08-16 06:22 UTC, Jkishan544 commented on resources/views/hr/menu.blade.php
> +            <a class="nav-item nav-link"style="color:blue;"><i class="fa fa-bitbucket" aria-hidden="true"></i>&nbsp;Total Count</a>
please review

2022-08-16 07:20 UTC, P4NK4J approved these changes
Looks good.

2022-08-16 07:20 UTC, merged