follow ups reminder count
ColoredCow/portal pull request #2152
Opened 2022-08-07 17:22 UTC by NirmalNegi07

#2124

### Description
Follow-Ups reminder count.

### Checklist:
- [x] I have performed a self-review of my own code.

2022-08-08 15:31 UTC, P4NK4J requested changes
@NirmalNegi07 based on our conversation earlier, please make the changes and assign for review once done.

2022-08-09 10:03 UTC, P4NK4J requested changes
Left some comments, please check

2022-08-09 10:03 UTC, P4NK4J commented on Modules/HR/Console/Recruitment/SendFollowUpThresholdMail.php
> +            }
How about ?
```suggestion
            $followUpCount = $application->latestApplicationRound ? $application->latestApplicationRound->followUps->count() : 0;
            if ($followUpCount == config('hr.follow-up-attempts-threshold')) {
                return $application;
            }
```

2022-08-09 10:03 UTC, P4NK4J commented on Modules/HR/Emails/SendThreshholdFollowUp.php
> +        return $this->from(config('hr.default.email'), config('hr.default.name'))
Why two email addresses in sender's address ?

2022-08-09 10:03 UTC, P4NK4J commented on Modules/HR/Resources/views/application/followups.blade.php
> +    </p>
Why 2 `p` tags are opening up and only 1 is closed ? Please see the indentation as well

2022-08-09 10:03 UTC, P4NK4J commented on app/Console/Kernel.php
> +        $schedule->command('hr:send-follow-ups-mail')->daily();
Can we have a fixed time like in the morning 8:00 am ?

2022-08-09 10:25 UTC, NirmalNegi07 commented on app/Console/Kernel.php
> +        $schedule->command('hr:send-follow-ups-mail')->daily();
yes sir i will do it.

2022-08-09 10:25 UTC, NirmalNegi07 commented on Modules/HR/Resources/views/application/followups.blade.php
> +    </p>
I will fix it.

2022-08-09 10:27 UTC, NirmalNegi07 commented on Modules/HR/Console/Recruitment/SendFollowUpThresholdMail.php
> +            }
Looks nice

2022-08-09 11:01 UTC, NirmalNegi07 commented on Modules/HR/Emails/SendThreshholdFollowUp.php
> +        return $this->from(config('hr.default.email'), config('hr.default.name'))
Sir, one is email address and another one is name.

2022-08-09 16:56 UTC, P4NK4J approved these changes
Looks good.

2022-08-09 16:56 UTC, P4NK4J commented on Modules/HR/Config/config.php
> +        'secondary' => env('HR_FOLLOWUP_EMAIL_SECONDARY', 'pk@coloredcow.in'),
```suggestion
        'secondary' => env('HR_FOLLOWUP_EMAIL_SECONDARY', 'pk@coloredcow.com'),
```

2022-08-09 16:57 UTC, P4NK4J commented
@NirmalNegi07 Glad you updated the env example file along with your changes. Good job with the overall work 👏

2022-08-09 16:58 UTC, P4NK4J commented
@NirmalNegi07 Glad you updated the env example file along with your changes. Good job with the overall work 👏

2022-08-09 16:58 UTC, merged