user profile in employee page
ColoredCow/portal pull request #2153
Opened 2022-08-08 06:29 UTC by akriti12negi

#2113 

### Description
User profile in employee page

### Checklist
 I have performed a self-review of my own code.

2022-08-08 08:25 UTC, GauravGusain98 requested changes
Please check the comments

2022-08-08 08:25 UTC, GauravGusain98 commented on routes/web.php
> +        Route::get('employee-reports', 'Employees\ReportsController@index')->name('employees.reports');
What these 2 routes are being used for?

2022-08-08 08:25 UTC, GauravGusain98 commented on routes/web.php
> +        Route::get('employee-reports', 'Employees\ReportsController@index')->name('employees.reports');
If these are not being used then please remove.

2022-08-08 08:29 UTC, srivastava-jyoti commented on resources/views/hr/employees/menu.blade.php
> +        <a class="nav-item nav-link {{ Request::is('hr/employee-basic-details*') ? 'active' : '' }}" href="{{ route('employees.basic.details')}}"><i class="fa fa-details"></i>&nbsp;Basic Details</a>
```suggestion
        <a class="nav-item nav-link {{ Request::is('hr/employee-basic-details*') ? 'active' : ' ' }}" href="{{ route('employees.basic.details') }}"><i class="fa fa-details"></i>&nbsp;Basic Details</a>
```

2022-08-08 08:30 UTC, srivastava-jyoti commented on resources/views/hr/employees/basic-details.blade.php
> +                @includeWhen($user->profile, 'user::profile.subviews.show-user-profile-info')
What is the use of `@includeWhen`?

2022-08-11 16:23 UTC, GauravGusain98 requested changes
@akriti12negi I am getting this error. Its looking like you are not passing the employee id to the route and it is required there. Please fix this
<img width="1385" alt="image" src="https://user-images.githubusercontent.com/54376313/184181923-d9c2e2c0-5ed6-4851-ab00-79ace2b2929d.png">

2022-08-12 07:31 UTC, GauravGusain98 approved these changes
Looks fine

2022-08-12 07:31 UTC, merged