Automated email to key account manager
ColoredCow/portal pull request #2166
Opened 2022-08-10 08:22 UTC by Sachinbisht27

Targets #{ISSUE_ID}
2011

### Description
Added Mail functionality in Project Module.

There are some projects surpassed end date but still marked as active. Sending mail to those project's Key Account manager.

### Checklist:
- [ ] I have performed a self-review of my own code.

2022-08-19 07:42 UTC, gautam071 requested changes
Left some comments

2022-08-19 07:42 UTC, gautam071 commented on Modules/Project/Resources/views/mail/ended-project.blade.php
> +	    @endforeach
Why empty foreach?

2022-08-19 07:42 UTC, gautam071 commented on Modules/Project/Resources/views/mail/ended-project.blade.php
> +			<th scope="col">Project Name</th>
Indentation

2022-08-19 07:42 UTC, gautam071 commented on Modules/Project/Resources/views/mail/ended-project.blade.php
> +	    @endforeach
Indentation

2022-08-19 07:42 UTC, gautam071 commented on Modules/Project/Resources/views/mail/ended-project.blade.php
> +    <p>To view all your projects, you can use this link  <a href="http://portal.test/projects">My Projects</a>.</p>
Don't hard code the url

2022-08-19 11:17 UTC, Sachinbisht27 commented on Modules/Project/Resources/views/mail/ended-project.blade.php
> +	    @endforeach
I'll remove it.

2022-08-19 11:17 UTC, Sachinbisht27 commented on Modules/Project/Resources/views/mail/ended-project.blade.php
> +			<th scope="col">Project Name</th>
ok

2022-08-19 11:18 UTC, Sachinbisht27 commented on Modules/Project/Resources/views/mail/ended-project.blade.php
> +	    @endforeach
ok

2022-08-19 11:18 UTC, Sachinbisht27 commented on Modules/Project/Resources/views/mail/ended-project.blade.php
> +    <p>To view all your projects, you can use this link  <a href="http://portal.test/projects">My Projects</a>.</p>
ok

2022-08-19 11:29 UTC, Sachinbisht27 commented
@gautam071 Required Changes Done please review.

2022-08-24 06:32 UTC, gautam071 approved these changes
Looks good!

Can you just check wheater the blade file is formated?

2022-08-30 06:02 UTC, merged