Organization setting has been stored in the database
ColoredCow/portal pull request #2168
Opened 2022-08-10 18:31 UTC by VivekU03

#2122 

### Description
Created a new setting with the name organization and created a table in database and and stored organization setting details in the database.

- [ ] I have performed a self-review of my own code.

2022-08-18 06:20 UTC, gautam071 requested changes
Few comments

2022-08-18 06:20 UTC, gautam071 commented on app/Http/Controllers/Settings/SettingController.php
> +
Can you add the backend validation

2022-08-18 06:20 UTC, gautam071 commented on resources/views/settings/organization/organization.blade.php
> +@stop
`@stop` is not recommended to use. 
Can we change it to the @endsection

If you want to know more https://stackoverflow.com/questions/21199412/laravel-blade-endsection-vs-stop

2022-08-18 06:20 UTC, gautam071 commented on resources/views/settings/index.blade.php
> +        @endcanany
You started the `@can` and using `@endcanany`?
What was the reason?

2022-08-18 06:20 UTC, gautam071 commented on resources/views/settings/organization/organization.blade.php
> +            <input type="text" class="form-control" name="name" placeholder="Organization"
```suggestion
            <input type="text" class="form-control" name="name" placeholder="Organization Name"
```

2022-08-18 06:20 UTC, gautam071 commented on resources/views/settings/organization/organization.blade.php
> +            <label for="name" class="field-required">Name</label>
```suggestion
            <label for="name" class="field-required">Organization Name</label>
```

2022-08-19 08:15 UTC, gautam071 requested changes
Left some comments

2022-08-19 08:15 UTC, gautam071 commented on app/Http/Controllers/Settings/SettingController.php
> +
Can we use a service file to store the data

2022-08-19 08:15 UTC, gautam071 commented on app/Http/Requests/OrganizationRequest.php
> +        ];
Can you check the format of the rules

2022-08-19 08:15 UTC, gautam071 commented on app/Models/Organization.php
> +    protected $table = 'organizations';
```suggestion

    protected $table = 'organizations';
```

2022-08-19 08:15 UTC, gautam071 commented on resources/views/settings/index.blade.php
> +
empty space

2022-08-19 08:15 UTC, gautam071 commented on resources/views/settings/organization/organization.blade.php
> +            @csrf
Indentation

2022-08-19 08:15 UTC, gautam071 commented on resources/views/settings/organization/organization.blade.php
> +                @error('name') <small class="text-danger">{{ $message }}</small>@enderror
format

2022-08-19 08:15 UTC, gautam071 commented on resources/views/settings/organization/organization.blade.php
> +            @error('address') <small class="text-danger">{{ $message }}</small>@enderror
format

2022-08-19 08:15 UTC, gautam071 commented on resources/views/settings/organization/organization.blade.php
> +            @error('annual_sales') <small class="text-danger">{{ $message }}</small>@enderror
Check the format in the blade file

2022-08-19 08:15 UTC, gautam071 commented on resources/views/settings/organization/organization.blade.php
> +@endsection
line at end of file

2022-08-19 08:34 UTC, VivekU03 commented on app/Http/Controllers/Settings/SettingController.php
> +
Task required me to store the data in the database. Please confirm where to store the data.

2022-08-30 05:16 UTC, gautam071 requested changes
Looks good just a question

2022-08-30 05:16 UTC, gautam071 commented on app/Http/Controllers/Settings/SettingController.php
> +    }
What's the use of this?

2022-09-01 14:57 UTC, VivekU03 commented on app/Http/Controllers/Settings/SettingController.php
> +    }
To view this page.
![Screenshot](https://user-images.githubusercontent.com/108857598/187945563-726aa494-8be1-4ea4-9a62-4913167a0e29.png)

.

2022-09-03 15:18 UTC, VivekU03 commented on app/Http/Controllers/Settings/SettingController.php
> +    }
Sir please check it.

2022-09-07 14:38 UTC, gautam071 requested changes

2022-09-07 14:38 UTC, gautam071 commented on app/Http/Controllers/Settings/SettingController.php
> +    }
The index()?

2023-04-07 12:05 UTC, closed without merging