Added email validation for CC and BCC field available in the email body
ColoredCow/portal pull request #2179
Opened 2022-08-11 18:14 UTC by Sachinbisht27

Targets #2174 

### Description
Added email validation for CC and BCC field available in the invoice reminder email body.

### Checklist:

- [ ] I have performed a self-review of my own code.

2022-08-11 18:59 UTC, gautam071 reviewed
One suggestion

2022-08-11 18:59 UTC, gautam071 commented on Modules/Invoice/Resources/views/modals/invoice-reminder.blade.php
> +                            <input type="email" name="bcc" id="bcc" class="form-control" value="{{ config('invoice.mail.send-invoice.email') }}">
Already via CC, the mail is sent to the same email we don't need this,
we can remove this line 
```suggestion
                            <input type="email" name="bcc" id="bcc" class="form-control" value="">
```

2022-08-12 01:37 UTC, Sachinbisht27 commented on Modules/Invoice/Resources/views/modals/invoice-reminder.blade.php
> +                            <input type="email" name="bcc" id="bcc" class="form-control" value="{{ config('invoice.mail.send-invoice.email') }}">
Yes, sure getting the point.

2022-08-12 05:37 UTC, gautam071 approved these changes
Looks good

2022-08-19 07:48 UTC, gautam071 requested changes
looks good!

2022-08-19 07:48 UTC, gautam071 approved these changes

2022-08-19 07:49 UTC, merged