Fix/1990/confirmation on taking over evaluation
ColoredCow/portal pull request #2181
Opened 2022-08-12 06:18 UTC by aquibmoin786

#1990

- Application Handover request

2022-08-13 11:50 UTC, gautam071 commented
@aquibmoin786 Fix the Checks

2022-08-15 05:39 UTC, P4NK4J requested changes
@aquibmoin786 If an application is already assigned to a person clicking on evaluate button, the popup should not appear, it should only as for handover if the application is assigned to other person than the logged in user. 
Also, in the email, there are a couple of things to be changed, 
1. Hey Scheduled person is to be replaced by the person name to whom the application is assigned
2. Provide application details, in the email, The |*APPLICATION TYPE*| application of |*APPLICANT NAME*| applied for |*JOB ROLE*| is requested for evaluation by |*PERSON SENDING THE REQUEST*|. Please click the link to handover the application.
|APPLICATION TYPE| can be job or internship, data will be available in applications table
3. Also, correct the spelling mistakes in the email template

2022-08-15 08:45 UTC, gautam071 requested changes

2022-08-15 08:45 UTC, gautam071 commented on Modules/HR/Http/Controllers/Recruitment/ApplicationController.php
> +            return redirect()->back()->with('status', "You are not assign to this application So you cann't take this action");
```suggestion
            return redirect()->back()->with('status', "You are not assign to this application So you can't take this action");
```

2022-08-15 08:45 UTC, gautam071 commented on Modules/HR/Resources/views/application/application-handover-request.blade.php
> +{{-- $jobType = $this->getApplicationType(); --}}
Remove the unwanted code

2022-08-15 13:11 UTC, P4NK4J requested changes
Left some comments, please check.

2022-08-15 13:11 UTC, P4NK4J commented on .husky/_/husky.sh
> +    fi
Why we need these changes in this PR ?

2022-08-15 13:11 UTC, P4NK4J commented on Modules/HR/Http/Controllers/Recruitment/ApplicationController.php
> +    public function request(Application $application)
What's the role of this function ? Can we rename it to something meaningful from readability perspective ? Maybe `applicationHandoverRequest` ? Let me know your thoughts

2022-08-15 13:11 UTC, P4NK4J commented on Modules/HR/Http/Controllers/Recruitment/ApplicationController.php
> +        return redirect()->back()->with('status', 'You email has successfully been sent');
```suggestion
        return redirect()->back()->with('status', 'Your request has successfully been sent');
```

2022-08-15 13:11 UTC, P4NK4J commented on Modules/HR/Http/Controllers/Recruitment/ApplicationController.php
> +        $status = 'Successful Assign to ' . $user->name;
```suggestion
        $status = 'Successful Assigned to ' . $user->name;
```

2022-08-15 13:11 UTC, P4NK4J commented on Modules/HR/Resources/views/application/application-handover-request.blade.php
> +<p>Hey {{$assignee->name}}, <br> <br>The {{$application->job->type}} application of {{$application->applicant->name}} applied for {{$application->job->title}} is requested for evaluation by {{auth()-
Why do we need $application->name here ? Do we have any such attribute in the database ?

2022-08-15 13:11 UTC, P4NK4J commented on Modules/HR/Resources/views/application/application-handover-request.blade.php
> +<p>Thanks,<br>HR,<br>Coloredcow</p>
Please correct HTML formatting for this template.

2022-08-15 13:11 UTC, P4NK4J commented on Modules/HR/Resources/views/application/render-application-row.blade.php
> +				@endif
Formatting seems off, please check

2022-08-15 13:11 UTC, P4NK4J commented on Modules/HR/Routes/web.php
> +            Route::get('application/{application}/assign-to/{user}', 'JobApplicationController@acceptHandoverRequest')->name('application.handover.confirmation');
What we are passing in {user} here ?

2022-08-15 13:11 UTC, P4NK4J commented on Modules/HR/Routes/web.php
> +        Route::get('evaluation/segment/{segmentID}/parameters', 'EvaluationController@segmentParameters')->name('hr.evaluation.segment-parameters');
Why we need to change this ?

2022-08-15 13:11 UTC, P4NK4J commented on Modules/HR/Resources/views/application/render-application-row.blade.php
> -		<img src="{{$assignee->avatar}}" alt="{{$assignee->name}}" class="w-25 h-25 rounded-circle"
how you are getting $assignee, after removing these lines ?

2022-08-15 13:11 UTC, P4NK4J commented on routes/web.php
> +    // Route::get('my-projects/{employee}', 'hr\Employees\EmployeeController@showProjects')->name('projects.my-projects');
Why you have commented out this line ?

2022-08-15 13:49 UTC, aquibmoin786 commented on .husky/_/husky.sh
> +    fi
It's auto generated.

2022-08-15 13:49 UTC, aquibmoin786 commented on Modules/HR/Http/Controllers/Recruitment/ApplicationController.php
> +    public function request(Application $application)
Changes

2022-08-15 13:50 UTC, aquibmoin786 commented on Modules/HR/Http/Controllers/Recruitment/ApplicationController.php
> +        return redirect()->back()->with('status', 'You email has successfully been sent');
Changes

2022-08-15 13:50 UTC, aquibmoin786 commented on Modules/HR/Http/Controllers/Recruitment/ApplicationController.php
> +        $status = 'Successful Assign to ' . $user->name;
Changes

2022-08-15 13:51 UTC, aquibmoin786 commented on Modules/HR/Resources/views/application/application-handover-request.blade.php
> +<p>Hey {{$assignee->name}}, <br> <br>The {{$application->job->type}} application of {{$application->applicant->name}} applied for {{$application->job->title}} is requested for evaluation by {{auth()-
By mistake added. I have remove that.

2022-08-15 16:32 UTC, aquibmoin786 commented on Modules/HR/Resources/views/application/render-application-row.blade.php
> -		<img src="{{$assignee->avatar}}" alt="{{$assignee->name}}" class="w-25 h-25 rounded-circle"
I have declare $assignee globally and for use this line `<p class="text-secondary">This application is already assigned to {{$assignee->name}}, to evaluate this, a confirmation would be needed from their end. Please click the request button to request the handover.</p>` and below line  ```
<img src="{{$assignee->avatar}}" alt="{{$assignee->name}}" class="w-25 h-25 rounded-circle"
			data-toggle="tooltip" data-placement="top" title="{{$assignee->name}}">
```

2022-08-15 16:34 UTC, aquibmoin786 commented on Modules/HR/Routes/web.php
> +        Route::get('evaluation/segment/{segmentID}/parameters', 'EvaluationController@segmentParameters')->name('hr.evaluation.segment-parameters');
I have changes it

2022-08-15 16:35 UTC, aquibmoin786 commented on Modules/HR/Routes/web.php
> +            Route::get('application/{application}/assign-to/{user}', 'JobApplicationController@acceptHandoverRequest')->name('application.handover.confirmation');
I use for getting user id and user name

2022-08-15 16:35 UTC, aquibmoin786 commented on routes/web.php
> +    // Route::get('my-projects/{employee}', 'hr\Employees\EmployeeController@showProjects')->name('projects.my-projects');
I have changes it.

2022-08-15 17:30 UTC, P4NK4J requested changes
Left some comments, please check

2022-08-15 17:30 UTC, P4NK4J commented on .husky/_/husky.sh
> +    fi
Can we remove it from this PR ?

2022-08-15 17:30 UTC, P4NK4J commented on Modules/HR/Resources/views/application/application-handover-request.blade.php
> +<p>
Let's keep it as it was in the render blade and use the $assignee variable here ?

2022-08-15 17:30 UTC, P4NK4J commented on Modules/HR/Resources/views/application/render-application-row.blade.php
> +
Remove this space

2022-08-15 17:30 UTC, P4NK4J commented on routes/web.php
> +    // Route::get('my-projects/{employee}', 'hr\Employees\EmployeeController@showProjects')->name('projects.my-projects');
Its still showing commented here, am I missing something ?

2022-08-16 05:33 UTC, P4NK4J requested changes
Minor comment, else looks good

2022-08-16 05:33 UTC, P4NK4J commented on Modules/HR/Http/Controllers/Recruitment/ApplicationController.php
> +use App\Mail\ApplicationHandover;
Let's put it inside HR module Email folder

2022-08-16 05:33 UTC, P4NK4J commented on app/Mail/ApplicationHandover.php
> +namespace App\Mail;
Let's put this inside HR email folder

2022-08-16 08:30 UTC, P4NK4J reviewed
@aquibmoin786 Let's keep the routes file changes as they were in the master branch. Please make these changes.  in HR routes and main web.php

2022-08-16 09:57 UTC, P4NK4J approved these changes
Looks good.

2022-08-24 11:36 UTC, gautam071 reviewed
Left some comments

2022-08-24 11:36 UTC, gautam071 commented on Modules/HR/Resources/views/application/render-application-row.blade.php
> +		$application->latestApplicationRound->hr_round_id != 14)
Don't hard code the id

2022-08-24 11:36 UTC, gautam071 commented on Modules/HR/Resources/views/application/render-application-row.blade.php
> +</tr>
Leave a line at the end

2022-08-24 11:36 UTC, gautam071 commented on resources/views/mail/hr/application-handover-request-email.blade.php
> +</p>
leave a line at the end

2022-08-24 11:58 UTC, gautam071 approved these changes
Looks good

2022-08-24 12:16 UTC, P4NK4J approved these changes
Looks good.

2022-08-25 05:22 UTC, merged