HR reporting - rejected applications
ColoredCow/portal pull request #2188
Opened 2022-08-12 10:54 UTC by rohit123-rawat

Targets #2075 

### Description
Create Round-wise-rejections and Rejection reasons Graph

### Checklist:

- [ ] I have performed a self-review of my own code.

2022-08-15 07:28 UTC, srivastava-jyoti commented on Modules/HR/Http/Controllers/Recruitment/ReportsController.php
> +        $data = HRRejectionReason::select(\DB::raw('reason_title as label'), \DB::Raw('COUNT(id) as count'))
```suggestion
        $data = HRRejectionReason::select(\DB::raw('reason_title as label'), \DB::raw('COUNT(id) as count'))
```

2022-08-15 11:23 UTC, srivastava-jyoti commented on resources/js/app.js
> +							if (data == "0") {
What is the datatype of `data`?

2022-08-15 11:24 UTC, srivastava-jyoti commented on resources/js/app.js
> +							if (data == "0") {
Why have u passed `(data == "0")` as string?

2022-08-15 11:26 UTC, srivastava-jyoti commented on resources/views/hr/recruitment/rejected-applications.blade.php
> +        <form class="form-inline text-right" action="{{route('recruitment.rejected-applications')}}" method="get" align="Right">
```suggestion
        <form class="form-inline text-right" action="{{ route('recruitment.rejected-applications') }}" method="get" align="Right">
```

2022-08-15 11:26 UTC, srivastava-jyoti commented on resources/views/hr/recruitment/rejected-applications.blade.php
> +        <form class="form-inline text-right" action="{{route('recruitment.rejected-applications')}}" method="get" align="Right">
```suggestion
        <form class="form-inline text-right" action="{{ route('recruitment.rejected-applications') }}" method="get" align="Right">
```

2022-08-20 10:41 UTC, P4NK4J requested changes
Left some comments, please check

2022-08-20 10:41 UTC, P4NK4J commented on Modules/HR/Http/Controllers/Recruitment/ReportsController.php
> +    public function showResult(Request $request)
The function name seems very generic, let's rename it to `showRejectedApplicationsGraph` instead

2022-08-20 10:41 UTC, P4NK4J commented on Modules/HR/Http/Controllers/Recruitment/ReportsController.php
> +        ];
Let's close these two different queries into different functions instead of writing both of them here

2022-08-20 10:41 UTC, P4NK4J commented on resources/js/app.js
> +function graphChart(){
If these are specific function, let's write function name as specific ones, which graph chart these are. Else, since we have multiple graphs having same JS code, maybe we can differentiate the data variables and use same function throughout

2022-08-20 10:41 UTC, P4NK4J commented on resources/js/app.js
> +function graphBarChart(){
Same goes for this graph function as well

2022-08-20 10:41 UTC, P4NK4J commented on resources/views/hr/recruitment/rejected-applications.blade.php
> +      <a class="nav-link {{ request('tabId') == 'tab2' ?  'active' : ' ' }}" id="tab2" data-toggle="tab" href="#rejection-reasons" role="tab" aria-controls="rejection-reasons" aria-selected="false">R
Let's rename tab1 and tab2 to their specific names, say rejectedReasons or roundWiseRejection Tab

2022-08-20 21:22 UTC, P4NK4J requested changes
Left some comments.

2022-08-20 21:22 UTC, P4NK4J commented on Modules/HR/Http/Controllers/Recruitment/ReportsController.php
> +        return $this->roundWiseRejectionsData($request, $chartBarData);
Let's do it in this way, there should be a common function, sending details for rejectedApplications, where chart data for different  graphs would be fetched from different functions, one function can be rejectedReasons and other can be roundWiseRejections. Let me know if that makes sense.

2022-08-20 21:22 UTC, P4NK4J commented on resources/views/hr/recruitment/rejected-applications.blade.php
> +      <a class="nav-link {{ request('tabId') == 'tab1' || !request()->has('tabId')  ?  'active' : ' ' }}" id="tab1" data-toggle="tab" href="#round-wise-rejections" role="tab" aria-controls="round-wis
If you will rename the id to specific like `rejectedReasonsTab` and `roundWiseReasons` tab, then you don't need to specify `tab1` or `tab2` in the request and conditionals. Please try making these changes

2022-08-25 04:42 UTC, P4NK4J approved these changes
Looks good.

2022-08-25 04:42 UTC, merged