functionality for zero effort projects
ColoredCow/portal pull request #2189
Opened 2022-08-12 14:01 UTC by Abhishek25081999

Targets #2095

### Description
Weekly alert to Key Account Managers about zero expected team effort.

### Checklist:

- [ ] I have performed a self-review of my own code.

2022-08-15 06:15 UTC, gautam071 requested changes

2022-08-15 06:15 UTC, gautam071 commented on Modules/Project/Emails/ZeroEffortInProjectMail.php
> +
Remove empty space

2022-08-15 06:15 UTC, gautam071 commented on Modules/Project/Resources/views/mail/zero-effort-team-member-list.blade.php
> +	 @endforeach
Why empty for each loop?

2022-08-15 06:15 UTC, gautam071 commented on Modules/Project/Resources/views/mail/zero-effort-team-member-list.blade.php
> +
Remove empty space

2022-08-15 06:15 UTC, gautam071 commented on Modules/Project/Console/ZeroEffortInProject.php
> +        $service = app(ProjectService::class);
What is the reason for changing from `ProjectServiceContract` to `ProjectService`?

2022-08-21 08:45 UTC, Abhishek25081999 commented on Modules/Project/Emails/ZeroEffortInProjectMail.php
> +
ok

2022-08-21 08:45 UTC, Abhishek25081999 commented on Modules/Project/Resources/views/mail/zero-effort-team-member-list.blade.php
> +	 @endforeach
ok i'll remove it.

2022-08-21 08:45 UTC, Abhishek25081999 commented on Modules/Project/Resources/views/mail/zero-effort-team-member-list.blade.php
> +
ok

2022-08-24 06:43 UTC, gautam071 commented
Looks like earlier suggested feedbacks was not fixed please check that

2022-08-31 17:50 UTC, gautam071 requested changes
@Abhishek25081999 
Left some comments and there are some unresolved comments as well

2022-09-03 06:17 UTC, Abhishek25081999 commented on Modules/Project/Emails/ZeroEffortInProjectMail.php
> +    public function __construct($projectDetail)
@gautam071 Done!

2022-09-07 14:41 UTC, gautam071 requested changes

2022-09-07 14:41 UTC, gautam071 commented on Modules/Project/Console/ZeroEffortInProject.php
> +            Mail::queue(new ZeroEffortInProjectMail($projectDetail));
Variable name changes why?

2022-09-07 14:41 UTC, gautam071 commented on Modules/Project/Emails/ZeroEffortInProjectMail.php
> +    public function __construct(array $projectDetail)
here as well?
what's the reason

2022-09-07 14:41 UTC, gautam071 commented on Modules/Project/Services/ProjectService.php
> +    public function getMailDetailsForKeyAccountManager()
The email is going out for multiple managers some 
```suggestion
    public function getMailDetailsForKeyAccountManagers()
```

2022-09-07 14:41 UTC, gautam071 commented on Modules/Project/Services/ProjectService.php
> +    public function getMailDetailsForKeyAccountManager()
Also change it every where

2022-09-08 17:15 UTC, Abhishek25081999 commented on Modules/Project/Console/ZeroEffortInProject.php
> +            Mail::queue(new ZeroEffortInProjectMail($projectDetail));
variable name changed after foreach loop.

2022-09-11 13:57 UTC, gautam071 approved these changes
looks good

2022-09-11 13:57 UTC, merged