2135 university reporting via automation
ColoredCow/portal pull request #2194
Opened 2022-08-13 10:08 UTC by LAKSHYA0501

Targets #2135  

### Description
1. Formatted Routes for different university report pages.
2. Did changes in the university listing page.
3. 

### Checklist:

- [ ] I have performed a self-review of my own code.

2022-08-13 11:47 UTC, gautam071 commented
@LAKSHYA0501 I am not able to see the chart the page is empty can you check it once?

2022-08-13 12:25 UTC, pokhiii commented on Modules/HR/Http/Controllers/Universities/ReportController.php
> +        $datas = DB::table('hr_applications')
_Data_ is a plural word. The singular is _datum_.
```suggestion
        $data = DB::table('hr_applications')
```

2022-08-13 12:26 UTC, pokhiii commented on Modules/HR/Http/Controllers/Universities/ReportController.php
> +    ->get();
indentation is off

2022-08-13 12:27 UTC, pokhiii commented on Modules/HR/Http/Controllers/Universities/ReportController.php
> +    public function show(University $report)
Why are calling a university object a report?
```suggestion
    public function show(University $university)
```

2022-08-13 12:31 UTC, pokhiii commented on Modules/HR/Http/Controllers/Universities/ReportController.php
> +        }
You can use [`pluck`](https://laravel.com/docs/8.x/collections#method-pluck) method of collection. This is avoid the need you to write a `foreach` loop here

2022-08-13 12:31 UTC, pokhiii commented on Modules/HR/Http/Controllers/Universities/ReportController.php
> +    ];
check indentation

2022-08-13 12:33 UTC, pokhiii commented on Modules/HR/Resources/views/universities/menu.blade.php
> +        <a class="nav-item nav-link {{ Request::is('hr/universities/reports*') ? 'active' : '' }}" href="{{route('universities.reports',$report = $university->id)}}"><i class="fa fa-pie-chart"></i>&n
```suggestion
        <a class="nav-item nav-link {{ Request::is('hr/universities/reports*') ? 'active' : '' }}" href="{{route('universities.reports', $university)}}"><i class="fa fa-pie-chart"></i>&nbsp;Reports</a>
```

2022-08-13 12:34 UTC, pokhiii commented on Modules/HR/Resources/views/universities/reports.blade.php
> +</div>
What's the use of this empty form?

2022-08-13 12:34 UTC, pokhiii commented on Modules/HR/Routes/web.php
> +                'index'=>'universitiesreports..index',
```suggestion
                'index'=>'universitiesreports.index',
```

2022-08-13 12:37 UTC, pokhiii commented on Modules/HR/Routes/web.php
> +        Route::resource('universities/reports', 'Universities\ReportController')
It seems like reports is a nested inside the university. In that case, can we follow Laravel's way to define routes for nested resources? https://laravel.com/docs/9.x/controllers#restful-nested-resources

2022-08-13 12:39 UTC, pokhiii commented on Modules/HR/Routes/web.php
> +                'show' =>'universities.reports',
```suggestion
                'show' =>'universities.reports.show',
```

2022-08-15 07:37 UTC, gautam071 requested changes

2022-08-15 07:37 UTC, gautam071 commented on Modules/HR/Resources/views/universities/index.blade.php
> +    </ul>
Repeated twice? 

Can we use the `Request::is` check and show the code?

2022-08-15 07:37 UTC, gautam071 commented on Modules/HR/Resources/views/universities/edit.blade.php
> +    </ul>
Same here

2022-08-15 07:37 UTC, gautam071 commented on Modules/HR/Resources/views/universities/edit.blade.php
> +
Remove the unwanted line

2022-08-15 07:37 UTC, gautam071 commented on Modules/HR/Resources/views/universities/reports.blade.php
> +<h1>Applications Per Jobs Roles</h1>
Change the mane according to the chart?

2022-08-15 07:37 UTC, gautam071 commented on Modules/HR/Routes/web.php
> +
Remove the unwanted space

2022-08-15 09:05 UTC, P4NK4J requested changes
Left some comments, please check

2022-08-15 09:05 UTC, P4NK4J commented on Modules/HR/Http/Controllers/Universities/ReportController.php
> +    }
Let's not put this code in show function, we will use show() for a different purpose. The function name for this can be `jobWiseApplicationsData` or something similar.

2022-08-15 09:05 UTC, P4NK4J commented on Modules/HR/Http/Controllers/Universities/ReportController.php
> +        $applicationsCount->all();
What we are trying to do here ?

2022-08-15 09:05 UTC, P4NK4J commented on Modules/HR/Http/Controllers/Universities/ReportController.php
> +        $jobTitle->all();
What we are trying to do here?

2022-08-15 09:05 UTC, P4NK4J commented on Modules/HR/Http/Controllers/Universities/ReportController.php
> +            'university' => $university,
Why we need $university in the view file ?

2022-08-15 10:46 UTC, LAKSHYA0501 commented on Modules/HR/Http/Controllers/Universities/ReportController.php
> +            'university' => $university,
![image](https://user-images.githubusercontent.com/53862863/184622042-69d45eb4-1877-4a7e-af6f-4ace03636cc1.png)
Removing this is creating error in reports.blade.php

2022-08-15 10:48 UTC, LAKSHYA0501 commented on Modules/HR/Http/Controllers/Universities/ReportController.php
> +            'university' => $university,
![image](https://user-images.githubusercontent.com/53862863/184622459-172bc4b7-2ed3-42e5-bbfc-d02d0e409fd2.png)

2022-08-15 10:51 UTC, LAKSHYA0501 commented on Modules/HR/Http/Controllers/Universities/ReportController.php
> +        $jobTitle->all();
use pluck to fetch the title and applications in 2 different arrays from $data which i used instead of foreach loop.

2022-08-15 10:59 UTC, LAKSHYA0501 commented on Modules/HR/Resources/views/universities/reports.blade.php
> +<h1>Applications Per Jobs Roles</h1>
Can you suggest any name for it?

2022-08-15 11:01 UTC, gautam071 commented on Modules/HR/Resources/views/universities/reports.blade.php
> +<h1>Applications Per Jobs Roles</h1>
Name the chart according to what it does.

Does your chart does this `Applications Per Jobs Roles`

2022-08-15 11:17 UTC, gautam071 commented on Modules/HR/Resources/views/universities/reports.blade.php
> +<h1>Applications Per Jobs Roles</h1>
Also, show the university name in the chart

2022-08-15 11:17 UTC, gautam071 commented on Modules/HR/Resources/views/universities/reports.blade.php
> +<h1>Applications Per Jobs Roles</h1>
Also, show the university name in the chart

2022-08-15 11:41 UTC, P4NK4J commented on Modules/HR/Http/Controllers/Universities/ReportController.php
> +            'university' => $university,
My question here is why we need $university variable, what data is obtained into that? Is it necessarily required or the graphData would be sufficient to serve the purpose? I didn't ask what will happen if I remove the variable. Please check the question carefully.

2022-08-15 11:51 UTC, LAKSHYA0501 commented on Modules/HR/Http/Controllers/Universities/ReportController.php
> +            'university' => $university,
$university is used in routes and also to get the data of each university in query for chart data $university is using to get id of each university

2022-08-15 11:55 UTC, P4NK4J commented on Modules/HR/Http/Controllers/Universities/ReportController.php
> +    }
@LAKSHYA0501 What about this ?

2022-08-15 11:57 UTC, P4NK4J commented on Modules/HR/Http/Controllers/Universities/ReportController.php
> +            'university' => $university,
Passing $university in route would be for getting $university object in the controller to fetch chart data, I am asking why you are returning the variable from controller, once you have the chartdata ?

2022-08-15 12:46 UTC, LAKSHYA0501 commented on Modules/HR/Http/Controllers/Universities/ReportController.php
> +            'university' => $university,
So the chart data only consists of job title and no of aaplications to add name of each university i am using $university

2022-08-15 12:46 UTC, LAKSHYA0501 commented on Modules/HR/Http/Controllers/Universities/ReportController.php
> +            'university' => $university,
applications*

2022-08-15 12:53 UTC, LAKSHYA0501 commented on Modules/HR/Http/Controllers/Universities/ReportController.php
> +            'university' => $university,
![Screenshot (71)](https://user-images.githubusercontent.com/53862863/184638450-a502413f-ecfd-4dd0-8afd-c4cb46975a11.png)

2022-08-15 13:12 UTC, P4NK4J commented on Modules/HR/Http/Controllers/Universities/ReportController.php
> +            'university' => $university,
👍

2022-08-15 16:56 UTC, LAKSHYA0501 commented on Modules/HR/Routes/web.php
> +
CI checks are failing so can't remove spaces

2022-08-15 17:13 UTC, gautam071 requested changes

2022-08-15 17:13 UTC, gautam071 commented on resources/js/app.js
> +}
There is already a chart does this same job can we use that chart 

https://github.com/ColoredCow/portal/blob/ea2e2a4ad8c6608e36b9e39135efbd83443c64cc/resources/js/app.js#L1421

2022-08-16 07:25 UTC, LAKSHYA0501 commented on resources/js/app.js
> +}
done these changes

2022-08-16 07:26 UTC, LAKSHYA0501 commented on Modules/HR/Http/Controllers/Universities/ReportController.php
> +    }
yup it is done.

2022-08-16 07:26 UTC, LAKSHYA0501 commented on Modules/HR/Resources/views/universities/edit.blade.php
> +    </ul>
done

2022-08-16 07:26 UTC, LAKSHYA0501 commented on Modules/HR/Resources/views/universities/index.blade.php
> +    </ul>
done

2022-08-16 10:05 UTC, P4NK4J approved these changes
Looks good. @gautam071 Please take a look once,

2022-08-16 10:34 UTC, gautam071 requested changes
Overall looks good!

Can you remove the changes from `app.js`

2022-08-17 05:21 UTC, LAKSHYA0501 commented
> Overall looks good!
> 
> Can you remove the changes from `app.js`

about what changes can you let me know

2022-08-17 06:03 UTC, LAKSHYA0501 commented
@gautam071 there are only space changes and no code changes and i think we can got with them rather than that a line was to be added that i did.

2022-08-17 09:15 UTC, gautam071 requested changes
Please revert the unwanted changes

2022-08-17 09:15 UTC, gautam071 commented on resources/js/app.js
> +	Vue.filter("str_limit", function (value, size) {
Why these indentation changes?

2022-08-17 09:15 UTC, gautam071 commented on resources/js/app.js
> +	setTimeout(function () {
same here

2022-08-17 09:44 UTC, LAKSHYA0501 commented on resources/js/app.js
> +	Vue.filter("str_limit", function (value, size) {
it is got fixed with the formatter, i confirmed with @GauravGusain98 and he also said the same.

2022-08-18 06:27 UTC, LAKSHYA0501 commented on resources/js/app.js
> +	setTimeout(function () {
it is got fixed with the formatter, i confirmed with @GauravGusain98 and he also said the same

2022-08-18 12:32 UTC, gautam071 approved these changes

2022-08-18 12:38 UTC, merged