not completed
ColoredCow/portal pull request #2203
Opened 2022-08-14 13:04 UTC by NirmalNegi07

Targets #{ISSUE_ID}

### Description

- [ ] I have performed a self-review of my own code.

2022-08-15 06:14 UTC, srivastava-jyoti commented on Modules/HR/Database/Seeders/SettingsTableSeeder.php
> +            'setting_value' => '<div>Hello |*APPLICANT NAME*|,</div><div> </div><div>We are very pleased to inform you that you have been selected for Team Interaction Round at ColoredCow. For the pr
`<div> </div>` why empty div has been inserted mid-between?

2022-08-15 06:17 UTC, srivastava-jyoti commented on Modules/HR/Http/Requests/TeamInteractionRequest.php
> +            'starttime' => 'required|date_format:H:i',
Please write it `starttime` as `start_time`.  And  correct it all other places too.

2022-08-15 06:23 UTC, srivastava-jyoti commented on Modules/HR/Resources/views/application/render-application-row.blade.php
> +            @php
I can't see any modification made by you in this file. Can u please remove this file from the pr

2022-08-15 06:24 UTC, srivastava-jyoti commented on resources/js/app.js
> +					if(this.nextRoundName=="Move to Team Interaction Round") {
```suggestion
					if(this.nextRoundName == "Move to Team Interaction Round") {
```

2022-08-15 06:26 UTC, srivastava-jyoti commented on resources/js/app.js
> +			tinymce.get("confirmMailToApplicantBody").setContent(response.body, { format: "html" });
What is the use of `tinymice`?

2022-08-15 06:27 UTC, srivastava-jyoti commented on resources/views/hr/round-review-confirm-modal.blade.php
> +                    <h6 class="text-secondary d-inline" id="applicantName">{{ $applicationRound->application->applicant->name }}</h6>&mdash;
```suggestion
                    <h6 class="text-secondary d-inline" id="applicantName">{{ $applicationRound->application->applicant->name }}</h6> &mdash;
```

2022-08-15 06:31 UTC, srivastava-jyoti commented on resources/views/settings/hr/team-interaction.blade.php
> +							<textarea name="setting_key[hr_team_interaction_round_body]" rows="10" class="richeditor form-control" placeholder="Body">{{ isset($settings['hr_team_interaction_round_body']->setting_value) ?
What is the datatype of `$settings['hr_team_interaction_round_body']->setting_value`?

2022-08-15 10:10 UTC, NirmalNegi07 commented on resources/views/settings/hr/team-interaction.blade.php
> +							<textarea name="setting_key[hr_team_interaction_round_body]" rows="10" class="richeditor form-control" placeholder="Body">{{ isset($settings['hr_team_interaction_round_body']->setting_value) ?
Datatype is string

2022-08-15 10:11 UTC, NirmalNegi07 commented on resources/js/app.js
> +			tinymce.get("confirmMailToApplicantBody").setContent(response.body, { format: "html" });
tinymce is a email editor and we need to set the email content into this editor

2022-08-15 10:11 UTC, NirmalNegi07 commented on Modules/HR/Database/Seeders/SettingsTableSeeder.php
> +            'setting_value' => '<div>Hello |*APPLICANT NAME*|,</div><div> </div><div>We are very pleased to inform you that you have been selected for Team Interaction Round at ColoredCow. For the pr
Ohk i will remove that

2022-08-15 11:42 UTC, srivastava-jyoti approved these changes
looks good

2022-08-15 11:54 UTC, P4NK4J requested changes
@NirmalNegi07 The pending calendar information should not appear for team interaction round. Please fix the same
<img width="792" alt="image" src="https://user-images.githubusercontent.com/35001775/184630673-7336207e-b538-41a4-936f-8e4b0159e931.png">

2022-08-16 05:14 UTC, P4NK4J requested changes
@NirmalNegi07 Let's remove the following things in the Team Interaction Round. 
Also, let's change the subject to `Congratulations for making it to the Team Interaction Round`.
I found console.logs left in between, please remove them.

<img width="733" alt="image" src="https://user-images.githubusercontent.com/35001775/184802724-e2fbd0af-88c5-41e0-b0bd-b377959f57a3.png">

2022-08-16 07:07 UTC, P4NK4J requested changes
Left some comments, please check

2022-08-16 07:07 UTC, P4NK4J commented on Modules/HR/Resources/views/application/render-application-row.blade.php
> +		$application->latestApplicationRound->hr_round_id != 14 && $application->latestApplicationRound->round->name != "Team Interaction Round")
Let's replace `14` with Telephonic Interview here, I know its not related to your PR, but let's change it

2022-08-16 07:07 UTC, P4NK4J commented on app/Http/Controllers/Settings/SettingController.php
> +
Let's put it in the HR module inside the ApplicationController file. Keeping in settings seem a bit irrelevant here, let me know what you think

2022-08-16 07:07 UTC, P4NK4J commented on resources/js/app.js
> +					}
What we are doing here ? Can we do something to avoid the hardcoded condition, since the text can be different in future ?

2022-08-16 07:07 UTC, P4NK4J commented on app/Http/Controllers/Settings/SettingController.php
> +    public function teaminteraction(TeamInteractionRequest $request)
Let's rename this function to `generateTeamInteractionEmail` ?

2022-08-16 07:07 UTC, P4NK4J commented on resources/views/hr/application/edit.blade.php
> +                                                        @if ($application->latestApplicationRound->hr_round_id != 14  && $applicationRound->round->name != "Team Interaction Round")
Let's replace `14` with `Telephonic Interview` here as well

2022-08-16 07:07 UTC, P4NK4J commented on resources/views/hr/application/edit.blade.php
> +																@endif
Why the indentation is off here ?

2022-08-16 07:07 UTC, P4NK4J commented on resources/views/hr/round-review-confirm-modal.blade.php
> +                    <strong>Success!!!</strong>Email generated successfully please find it below in the editor.
```suggestion
                    <strong>Success!</strong>Email generated successfully please find it below in the editor.
```

2022-08-16 07:31 UTC, NirmalNegi07 commented on resources/js/app.js
> +					}
@P4NK4J sir this we are using to show the fields which are mentioned in the issue , when an application moves to Team Interaction round

2022-08-16 07:32 UTC, NirmalNegi07 commented on Modules/HR/Resources/views/application/render-application-row.blade.php
> +		$application->latestApplicationRound->hr_round_id != 14 && $application->latestApplicationRound->round->name != "Team Interaction Round")
ohk sir

2022-08-17 06:04 UTC, P4NK4J approved these changes
Looks good.

2022-08-17 06:06 UTC, merged