2198 update date filters
ColoredCow/portal pull request #2210
Opened 2022-08-15 13:20 UTC by LAKSHYA0501

Targets #2198

### Description
1. Updated date filters.

### Checklist:
- [ ] I have performed a self-review of my own code.

2022-08-15 13:28 UTC, P4NK4J approved these changes
Looks good.
@gautam071 can you also take a look at this once.

2022-08-15 16:29 UTC, gautam071 requested changes

2022-08-15 16:29 UTC, gautam071 commented on resources/js/app.js
> +}
@LAKSHYA0501 There is already a function for this can we use that? 

https://github.com/ColoredCow/portal/blob/6325f5beb0c30d31c5e2964f76932b972c26eea6/resources/js/app.js#L1340

also leave a empty line at the end

2022-08-16 07:28 UTC, LAKSHYA0501 commented on resources/js/app.js
> +}
made the following changes.

2022-08-16 07:31 UTC, gautam071 commented
@LAKSHYA0501 Please fix the merge conflicts

2022-08-16 08:26 UTC, gautam071 requested changes
Looks good couple of feedbacks!

2022-08-16 08:26 UTC, gautam071 commented on resources/js/app.js
> +		datePickerChart();
Remove this function from else becasue it is repeated on the both if and else condition
```suggestion
```

2022-08-16 08:26 UTC, gautam071 commented on resources/js/app.js
> +});
add a line in the EOF

2022-08-16 08:51 UTC, LAKSHYA0501 commented on resources/js/app.js
> +		datePickerChart();
Removing the datePickerChart() function will not give alert for the second chart.

2022-08-16 08:58 UTC, gautam071 commented on resources/js/app.js
> +		datePickerChart();
Can you be a bit clear
I am unable to understand you

2022-08-16 08:58 UTC, gautam071 commented on resources/js/app.js
> +		datePickerChart();
Can you be a bit clear
I am unable to understand you

2022-08-16 09:09 UTC, LAKSHYA0501 commented
> Looks good couple of feedbacks!

made final changes

2022-08-16 14:44 UTC, gautam071 commented
@LAKSHYA0501 Please make the requested changes and then assign for review

2022-08-17 05:25 UTC, LAKSHYA0501 commented
@gautam071 about what changes you are talking about can you make it a bit clear?

2022-08-17 05:27 UTC, gautam071 commented
> @gautam071 about what changes you are talking about can you make it a bit clear?

About this comment https://github.com/ColoredCow/portal/pull/2210#discussion_r946512786

Man! Just look above

2022-08-17 06:30 UTC, LAKSHYA0501 commented
@gautam071 ya after that only i just removed the else function and used 2 different if() for different charts.

2022-08-17 06:45 UTC, gautam071 approved these changes
Looks good

2022-08-17 09:46 UTC, merged