making the delete button
ColoredCow/portal pull request #2218
Opened 2022-08-16 10:56 UTC by gulshan81

Targets #2190

### Description
making the delete button

### Checklist:
- [ ] I have performed a self-review of my own code.

2022-08-16 14:42 UTC, gautam071 requested changes
Left some comments

2022-08-16 14:42 UTC, gautam071 commented on Modules/Prospect/Database/Migrations/2020_04_30_174905_create_prospect_checklist_statuses_table.php
> +            $table->foreign('prospect_id')->references('id')->on('prospects')->onDelete('cascade');
Can we create a new migration for this?

2022-08-16 14:42 UTC, gautam071 commented on Modules/Prospect/Database/Migrations/2020_04_30_182928_create_prospect_nda_meta_table.php
> +            $table->foreign('nda_meta_id')->references('id')->on('nda_meta')->onDelete('cascade');
Can we create a new migration for this?

2022-08-16 14:42 UTC, gautam071 commented on Modules/Prospect/Database/Migrations/2020_05_02_113031_create_prospect_requirements_table.php
> +            $table->foreign('prospect_id')->references('id')->on('prospects')->onDelete('cascade');
Can we create a new migration for this?

2022-08-16 14:42 UTC, gautam071 commented on Modules/Prospect/Database/Migrations/2020_05_04_150517_create_prospect_calendar_meeting_table.php
>          });
Can we create a new migration for this?

2022-08-16 14:42 UTC, gautam071 commented on Modules/Prospect/Resources/views/index.blade.php
> +                            {{-- <a class="btn btn-danger" href="{{ route('prospect.destroy', $prospect->id)}}">Delete</a> --}}
Remove the unwanted code

2022-08-16 15:38 UTC, gulshan81 commented on Modules/Prospect/Resources/views/index.blade.php
> +                            {{-- <a class="btn btn-danger" href="{{ route('prospect.destroy', $prospect->id)}}">Delete</a> --}}
I removed the unwanted code.

2022-08-17 09:28 UTC, gautam071 commented
@gulshan81 Sorry for changing the requirement at the last minute 
Can we implement the soft delete

2022-08-18 17:10 UTC, merged