Remove
ColoredCow/portal pull request #2225
Opened 2022-08-16 16:32 UTC by Himanshunegi0332

Targets #2213

### Description
 Add a remove functionality to that projects in the client.

### Checklist:
- [X] I have performed a self-review of my own code.

2022-08-17 06:47 UTC, gautam071 requested changes
Looks good one minor change

2022-08-17 06:47 UTC, gautam071 commented on Modules/Client/Resources/views/subviews/edit-client-projects.blade.php
> +                    <div class="w-30p ml-2">
```suggestion
                    <div class="w-30p w-md-40p ml-2">
```

2022-08-17 06:57 UTC, Himanshunegi0332 commented on Modules/Client/Resources/views/subviews/edit-client-projects.blade.php
> +                    <div class="w-30p ml-2">
done sir

2022-08-17 09:12 UTC, gautam071 commented
@Himanshunegi0332 Make the name and description more related to the PR

2022-08-17 09:37 UTC, gautam071 commented
@Himanshunegi0332 Sorry for changing the requirement at the last minute
Can we implement the soft delete

2022-08-17 15:45 UTC, gautam071 commented on Modules/Client/Resources/views/subviews/edit-client-projects.blade.php
> +            </div>
Can we move the modal to a new blade file and include the blade file here

2022-08-17 15:47 UTC, gautam071 commented on Modules/Project/Http/Controllers/ProjectController.php
> +                'reason_for_deletion' => $request['comment']
Can you add backend validation not accepting any special characters

2022-08-19 06:26 UTC, gautam071 approved these changes
Looks good! Left some suggestions

2022-08-19 06:26 UTC, gautam071 commented on Modules/Client/Resources/views/subviews/edit-client-projects.blade.php
> +    </div>
Leave a line at end of file

2022-08-19 06:26 UTC, gautam071 commented on Modules/Client/Resources/views/subviews/create-client-projects-modal.blade.php
> +</div>
Leave a line at end of file

2022-08-19 07:09 UTC, merged