Added a modal for storing reason for deletion
ColoredCow/portal pull request #2228
Opened 2022-08-17 08:26 UTC by Kirannegi02

Targets #1347 

### Description
- Added a modal for storing reason for deletion of Invoice.

### Checklist:

- [ ] I have performed a self-review of my own code.

2022-08-17 09:11 UTC, gautam071 requested changes

2022-08-17 09:11 UTC, gautam071 commented on Modules/Invoice/Resources/views/subviews/edit/invoice-details.blade.php
> +            dd("kiran");
Can you remove this

2022-08-17 10:16 UTC, Kirannegi02 commented on Modules/Invoice/Resources/views/subviews/edit/invoice-details.blade.php
> +            dd("kiran");
yes

2022-08-17 10:17 UTC, Kirannegi02 commented on Modules/Invoice/Resources/views/subviews/edit/invoice-details.blade.php
> +                    </div>
ya sure.

2022-08-17 16:07 UTC, gautam071 requested changes

2022-08-17 16:07 UTC, gautam071 commented on app/Models/InvoiceAudit.php
> +}
You cannot modify the package files or tables because if the future if the package is deprecated or changed we will lose all the details. 

So can we use soft deleted and add a column

2022-08-17 16:07 UTC, gautam071 commented on database/migrations/2022_08_16_215934_update_invoice_number_to_audits_table.php
> +}
Same here

2022-08-19 08:03 UTC, gautam071 requested changes
Left some comments

2022-08-19 08:03 UTC, gautam071 commented on Modules/Invoice/Resources/views/subviews/edit/invoice-details.blade.php
> +        <span class="btn btn-danger" @click="deleteInvoice()" >Delete</span>
indentation

2022-08-19 08:03 UTC, gautam071 commented on database/migrations/2022_08_16_215934_update_invoice_number_to_audits_table.php
> +}
Remove the migrations if not needed

2022-08-19 08:03 UTC, gautam071 commented on database/migrations/2022_08_19_124517_remove_reason_for_deletion_from_audits_table.php
> +}
Remove the migrations if not needed

2022-08-24 06:36 UTC, gautam071 commented
@Kirannegi02 I remember seeing multiple files of changes 
Can you check if the PR has all the files

2022-08-24 06:47 UTC, Kirannegi02 commented
Initially, I have added other files for the modal, but now this code is only for soft delete

2022-08-26 06:46 UTC, Kirannegi02 commented
@gautam071 I have removed [ protected $table = 'invoices'; ] and it is also working fine without this.

2022-08-31 17:51 UTC, gautam071 approved these changes

2022-08-31 17:52 UTC, merged