Creating the delete button
ColoredCow/portal pull request #2229
Opened 2022-08-17 10:48 UTC by gulshan81

Targets #2218

### Description
created the delete button and it's functionality in prospect with the help of soft delete. 

### Checklist:
- [ ] I have performed a self-review of my own code.

2022-08-17 11:13 UTC, gulshan81 commented
Please delete the previous pr named (making the delete button #2218 ) because I created a new pr for that issue. And prefer this pr for that issue.

2022-08-17 16:14 UTC, gautam071 requested changes
few questions?

2022-08-17 16:14 UTC, gautam071 commented on Modules/Prospect/Entities/Prospect.php
> +    protected $primarykey = 'prospect_id';
What was the reason for adding this $primarykey?

2022-08-17 16:14 UTC, gautam071 commented on Modules/Prospect/Http/Controllers/ProspectController.php
> +    }
What is the purpose of adding restore?

2022-08-18 04:19 UTC, gulshan81 commented on Modules/Prospect/Entities/Prospect.php
> +    protected $primarykey = 'prospect_id';
because  this primary key is worked as a parent row

2022-08-18 04:22 UTC, gulshan81 commented on Modules/Prospect/Http/Controllers/ProspectController.php
> +    }
Because
 1. destroy() method will soft delete a specific post from the list.
2. restore() method will restore specific posts from the list
3. restore all() method will restore all soft deleted posts.

2022-08-18 07:03 UTC, gulshan81 commented on Modules/Prospect/Entities/Prospect.php
> +    protected $primarykey = 'prospect_id';
the reason is that I supposed that when the delete function executes in the prospects table then it searches the prospect id in the module file where we describe the soft delete. But it works properly without it so I understand that the soft delete already has that property.

2022-08-18 07:10 UTC, gulshan81 commented on Modules/Prospect/Http/Controllers/ProspectController.php
> +    }
sorry, I did not understand you at first but the purpose of this restore function is to restore the prospects in the database but there is no need for this so I removing the functionality from my code.

2022-08-18 17:10 UTC, gautam071 approved these changes
Looks good!

2022-08-18 17:10 UTC, merged