added search by category functionality
ColoredCow/portal pull request #2231
Opened 2022-08-17 11:42 UTC by parasnegi2002

Targets #{2185}

### Description
added the functionality "sort by category "

2022-08-17 16:34 UTC, gautam071 requested changes
Few suggestions

2022-08-17 16:34 UTC, gautam071 commented on resources/views/knowledgecafe/library/books/index.blade.php
> +				<option value="Select Category"></option>
Remove this if its not needed

2022-08-17 16:34 UTC, gautam071 commented on resources/views/knowledgecafe/library/books/index.blade.php
> +        <span>sort by category</span>
```suggestion
        <span>Sort book by category</span>
```

2022-08-17 16:34 UTC, gautam071 commented on app/Http/Controllers/KnowledgeCafe/Library/BookController.php
> +        $searchString = $request->search ?? false;
What was the reason for changing the search string variable contnent

2022-08-18 07:01 UTC, parasnegi2002 commented on app/Http/Controllers/KnowledgeCafe/Library/BookController.php
> +        $searchString = $request->search ?? false;
both are same . Its a shortform of this $searchString

2022-08-18 17:24 UTC, gautam071 approved these changes
loooks good

2022-08-18 17:24 UTC, merged