[#1752] HR module seeders
ColoredCow/portal pull request #2236
Opened 2022-08-18 06:55 UTC by belwalshubham

Targets #1752 

### Description
fixing all the seeders in the HR module and create seeder for all the remaining table of Hr Module.

### Checklist:
- [x] I have performed a self-review of my own code.

2022-08-22 12:18 UTC, P4NK4J requested changes
Left some questions for you, please check

2022-08-22 12:18 UTC, P4NK4J commented on Modules/HR/Database/Factories/HrFollowUpFactory.php
> +            'conducted_by' => null,
Let's not keep conducted_by null, maybe let's put random user_ids here

2022-08-22 12:18 UTC, P4NK4J commented on Modules/HR/Database/Factories/HrResourcesCategoriesFactory.php
> +            'id'=> null,
Why ID is null here ? we are using it as a foreign key in resources module

2022-08-22 12:18 UTC, P4NK4J commented on Modules/HR/Database/Factories/HrResourcesCategoriesFactory.php
> +             'slug'=> 1,
Slug should be a hyphen separated value for the name, let's say name=> "Interview Guidelines", so slug should be "interview-guidelines"

2022-08-22 12:18 UTC, P4NK4J commented on Modules/HR/Database/Factories/HrResourcesFactory.php
> +             'job_id'=> 1,
```suggestion
            'job_id'=> 1,
```

2022-08-22 12:18 UTC, P4NK4J commented on Modules/HR/Database/Factories/HrUniversitiesFactory.php
> +            'rating'=> 1,
can this be random number ? all the universities can't be of 1 rating. Its a cosmetic change, but let's do it by faker

2022-08-22 12:18 UTC, P4NK4J commented on Modules/HR/Database/Seeders/ApplicationEvaluationTableSeeder.php
> +        // $this->call("OthersTableSeeder");
Why this is commented?

2022-08-22 12:18 UTC, P4NK4J commented on Modules/HR/Database/Seeders/HrApplicationEvaluationSegmentTableSeeder.php
> +        $segmentNames = $this->getSegmentNames();
Let's add a check, if app environment is not production, then only these seeders should run

2022-08-22 12:18 UTC, P4NK4J commented on Modules/HR/Database/Seeders/HrApplicationSegmentTableSeeder.php
> +        Model::unguard();
Why we are only unguarding this seeder Model ? We didn't do it for others ?

2022-08-22 12:19 UTC, P4NK4J commented on config/constants.php
> +                'class' => 'badge badge-success',
This is how it is appearing on an already existing database
<img width="1148" alt="image" src="https://user-images.githubusercontent.com/35001775/185919591-8b593b91-868c-43c7-bab0-8ba28b20a76f.png">

2022-08-22 12:21 UTC, P4NK4J commented on Modules/HR/Http/Controllers/Recruitment/ApplicationRoundController.php
> +        $template = json_decode($applicationRound->round->{$templateType}, true);
This is how it's appearing on the system, where data is present
<img width="1434" alt="image" src="https://user-images.githubusercontent.com/35001775/185919770-cb25e933-50cf-4f60-a951-121cc1b4fd13.png">

2022-08-22 12:26 UTC, P4NK4J commented on config/constants.php
> +                'class' => 'badge badge-success',
The tags are getting duplicated, I think this must be due to seeders running again for already created tags
<img width="1427" alt="image" src="https://user-images.githubusercontent.com/35001775/185920598-cdd94917-e96b-4145-85b2-3d577f25905a.png">

2022-08-22 12:27 UTC, P4NK4J commented on Modules/HR/Http/Controllers/Recruitment/ApplicationRoundController.php
> +        $template = json_decode($applicationRound->round->{$templateType}, true);
Its breaking the rendering of email template on data existing database
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/35001775/185920790-a4cb521c-6f46-4e0b-baef-b1dbcb8fc78f.png">

2022-08-22 12:27 UTC, P4NK4J commented on resources/views/settings/hr/index.blade.php
> +				$round->{$mailTemplate} = json_decode($round->{$mailTemplate}, true);
This is conflicting with the email templates rendering

2022-08-22 16:05 UTC, belwalshubham commented on Modules/HR/Config/config.php
> +            'class' => 'badge badge-success',
It won't impact other . badge-success will change the color of label new to green

2022-08-22 16:05 UTC, belwalshubham commented on Modules/HR/Database/Factories/HrApplicationMetaFactory.php
> +            'key'=> 2,
done with the changes..

2022-08-22 16:05 UTC, belwalshubham commented on Modules/HR/Database/Factories/HrApplicationRoundFactory.php
> +             'hr_round_id' => Round::first()->id,
done

2022-08-22 16:05 UTC, belwalshubham commented on Modules/HR/Database/Factories/HrApplicationRoundFactory.php
> +            'is_latest' => true,
donw with chnages . is_latest should be false here

2022-08-22 16:05 UTC, belwalshubham commented on Modules/HR/Database/Factories/HrApplicationRoundReviewFactory.php
> +            'review_value'=> 2,
done with changes

2022-08-22 16:06 UTC, belwalshubham commented on Modules/HR/Entities/Evaluation/Segment.php
> +    // }
done with changes

2022-08-22 16:06 UTC, belwalshubham commented on Modules/HR/Resources/views/application/render-application-row.blade.php
> +		$application->latestApplicationRound->round->name != "Telephonic Interview" && $application->latestApplicationRound->round->name != "Team Interaction Round" && $application->latestApplicationRound-
this is due to merge conflict happening with nirmal negi's code .

2022-08-22 16:06 UTC, belwalshubham commented on resources/views/settings/hr/index.blade.php
> +				$round->{$mailTemplate} = json_decode($round->{$mailTemplate}, true);
it wont impact the existing workflow. this is working fine  and trhe email rendering will also working fine

2022-08-22 21:53 UTC, GauravGusain98 requested changes
Left some comments please check

2022-08-22 21:53 UTC, GauravGusain98 commented on Modules/HR/Database/Factories/HrApplicationEvaluationFactory.php
> +            'option_id'=> 1,
What will happen if we don't have evaluation or option present in database. In that case it will throw error. You can fetch the evaluation and option from database and then use the id of them here. If evaluation and option are not present then you can created one and use its id here.

2022-08-22 21:53 UTC, GauravGusain98 commented on Modules/HR/Database/Factories/HrApplicationRoundFactory.php
> +            'is_latest' => false,
I think this should be true. As for a application there should be on latest round.

2022-08-22 21:53 UTC, GauravGusain98 commented on Modules/HR/Database/Factories/HrApplicationSegmentFactory.php
> +        $hrEvalationSegmentId = Segment::first();
What will happen if no segment in present, maybe you can create one in that case.

2022-08-22 21:53 UTC, GauravGusain98 commented on Modules/HR/Database/Factories/HrUniversityAliasesFactory.php
> +
```suggestion
```

2022-08-22 21:53 UTC, GauravGusain98 commented on Modules/HR/Database/Seeders/ApplicationEvaluationTableSeeder.php
> +        // $this->call("OthersTableSeeder");
remove this

2022-08-22 21:53 UTC, GauravGusain98 commented on Modules/HR/Database/Seeders/HRDatabaseSeeder.php
> +        $this->call(HrApplicationSegmentTableSeeder::class);
Among these seeders, lets only keep that seeder which is dependent on most of the tables related to application, that way all the entries in other tables will automatically be created as we are creating the entries using factories when we are using the ids in the foreign key field

2022-08-22 21:53 UTC, GauravGusain98 commented on Modules/HR/Database/Seeders/HrApplicationMetaTableSeeder.php
> +            // $this->call("OthersTableSeeder");
```suggestion
```

2022-08-22 21:53 UTC, GauravGusain98 commented on Modules/HR/Database/Seeders/HrApplicationRejectionReasonTableSeeder.php
> +            // $this->call("OthersTableSeeder");
```suggestion
```

2022-08-22 21:53 UTC, GauravGusain98 commented on Modules/HR/Database/Seeders/HrApplicationRoundReviewTableSeeder.php
> +            // $this->call("OthersTableSeeder");
```suggestion
```

2022-08-22 21:53 UTC, GauravGusain98 commented on Modules/HR/Entities/ApplicationEvaluationSegment.php
> +    public static function newFactory()
Leave a line space before and after a function
```suggestion

    public static function newFactory()
```

2022-08-22 21:53 UTC, GauravGusain98 commented on Modules/HR/Entities/ApplicationMeta.php
> +    public static function newFactory()
Same here

2022-08-22 21:53 UTC, GauravGusain98 commented on Modules/HR/Entities/ApplicationRoundReview.php
> +    public static function newFactory()
same here

2022-08-22 21:53 UTC, GauravGusain98 commented on Modules/HR/Entities/Evaluation/ApplicationEvaluation.php
> +    public static function newFactory()
here as well

2022-08-22 21:53 UTC, GauravGusain98 commented on Modules/HR/Entities/Evaluation/Segment.php
> -
dont remove this

2022-08-23 03:47 UTC, P4NK4J commented on Modules/HR/Database/Factories/HrApplicationRoundFactory.php
> +            'is_latest' => false,
In this case, each application can have multiple rounds. Only one `round` can be the latest in which an application resides. With seeders, I think if there will only be an entry round in the hr_application_round table corresponding to one application, I am fine by keeping it to `true`.

2022-08-31 17:54 UTC, gautam071 commented
@belwalshubham Please fix the CI checks when ever possible

2022-09-06 05:10 UTC, P4NK4J approved these changes
Looks good. @GauravGusain98 Please take a look as well

2022-09-06 07:41 UTC, GauravGusain98 requested changes
Please check the comments

2022-09-06 07:41 UTC, GauravGusain98 commented on Modules/HR/Database/Factories/HrApplicationEvaluationFactory.php
> +        ];
Please don't use the harcoded id. This logic may break if these ids are not present in the DB

2022-09-06 07:41 UTC, GauravGusain98 commented on Modules/HR/Database/Factories/HrApplicationMetaFactory.php
> +        ];
same here

2022-09-06 07:41 UTC, GauravGusain98 commented on Modules/HR/Database/Factories/HrApplicationEvaluationFactory.php
> +        ];
You can fetch a random application from DB and use its id instead. Same for other tables. 

```
Application::inRandomOrder()->first();
```

2022-09-06 07:41 UTC, GauravGusain98 commented on Modules/HR/Database/Factories/HrApplicationRejectionFactory.php
> +        ];
same here

2022-09-06 07:41 UTC, GauravGusain98 commented on Modules/HR/Database/Factories/HrApplicationRoundReviewFactory.php
> +            '7',
same here

2022-09-06 07:41 UTC, GauravGusain98 commented on Modules/HR/Database/Factories/HrApplicationSegmentFactory.php
> +            '9',
same here

2022-09-06 07:41 UTC, GauravGusain98 commented on Modules/HR/Database/Factories/HrApplicationsFactory.php
> +            'resume' => 'https://coloredcow.com/wp-content/uploads/2022/08/sample.pdf',
lets put this URL in a config and take the value from there.

2022-09-06 07:41 UTC, GauravGusain98 commented on Modules/HR/Database/Factories/HrApplicationsFactory.php
> +            '2',
Same here, fetch the values from DB

2022-09-06 07:41 UTC, GauravGusain98 commented on Modules/HR/Database/Factories/HrFollowUpFactory.php
> +
remove this extra line

2022-09-06 07:41 UTC, GauravGusain98 commented on Modules/HR/Database/Factories/HrFollowUpFactory.php
> +
here as well

2022-09-06 07:41 UTC, GauravGusain98 commented on Modules/HR/Database/Factories/HrFollowUpFactory.php
> +            '9',
Same as above feedbacks

2022-09-06 07:41 UTC, GauravGusain98 commented on Modules/HR/Database/Factories/HrResourcesCategoriesFactory.php
> +
remove extra lines

2022-09-06 07:41 UTC, GauravGusain98 commented on Modules/HR/Database/Factories/HrResourcesFactory.php
> +        ];
```suggestion
        return [
            'resource_link'=> $this->faker->url,
            'hr_resource_category_id'=> 2,
            'job_id'=> 1,
        ];
```

2022-09-06 07:41 UTC, GauravGusain98 commented on Modules/HR/Database/Factories/HrUniversitiesFactory.php
> +        ];
Can't we use random function in PHP for this

2022-09-06 07:41 UTC, GauravGusain98 commented on Modules/HR/Database/Seeders/ApplicationEvaluationTableSeeder.php
> +                ->count(20)
Lets use less count in the seeders. Maybe 10 is fine otherwise we will have a lot of fake data

2022-09-06 07:41 UTC, GauravGusain98 commented on Modules/HR/Database/Seeders/HRJobsSeederTableSeeder.php
> +                ->count(20)
```suggestion
                ->count(10)
```

2022-09-06 07:41 UTC, GauravGusain98 commented on Modules/HR/Database/Seeders/HrApplicantsTableSeeder.php
> +                ->count(20)
```suggestion
                ->count(10)
```

2022-09-06 07:41 UTC, GauravGusain98 commented on Modules/HR/Database/Seeders/HrApplicationRoundTableSeeder.php
> +
remove extra blank lines

2022-09-06 07:41 UTC, GauravGusain98 commented on Modules/HR/Database/Seeders/HrApplicationRoundTableSeeder.php
> +                        'hr_round_id' => 1,
Lets not harcode ids. We can use 
```
Round::first()->id;
```

2022-09-06 07:41 UTC, GauravGusain98 commented on Modules/HR/Database/Seeders/HrApplicationSegmentTableSeeder.php
> +                ->count(20)
```suggestion
                ->count(10)
```

2022-09-06 07:41 UTC, GauravGusain98 commented on Modules/HR/Database/Seeders/HrApplicationsTableSeeder.php
> +              ->count(60)
```suggestion
              ->count(10)
```

2022-09-06 07:41 UTC, GauravGusain98 commented on Modules/HR/Database/Seeders/HrFollowUpTableSeeder.php
> +                ->count(20)
```suggestion
                ->count(10)
```

2022-09-06 07:41 UTC, GauravGusain98 commented on Modules/HR/Database/Seeders/ResumeScreeningEvaluationSeeder.php
> +
remove extra lines

2022-09-06 07:41 UTC, GauravGusain98 commented on Modules/HR/Database/Seeders/ResumeScreeningEvaluationSeeder.php
> +
Please remove all blank lines from this file

2022-09-07 11:51 UTC, belwalshubham commented on Modules/HR/Database/Factories/HrApplicationEvaluationFactory.php
> +        ];
done with changes

2022-09-07 11:51 UTC, belwalshubham commented on Modules/HR/Database/Factories/HrApplicationRejectionFactory.php
> +        ];
done wih the changes

2022-09-07 11:51 UTC, belwalshubham commented on Modules/HR/Database/Factories/HrFollowUpFactory.php
> +
done

2022-09-07 11:51 UTC, belwalshubham commented on Modules/HR/Database/Factories/HrApplicationSegmentFactory.php
> +            '9',
done

2022-09-07 11:51 UTC, belwalshubham commented on Modules/HR/Database/Factories/HrFollowUpFactory.php
> +
done

2022-09-07 11:51 UTC, belwalshubham commented on Modules/HR/Database/Factories/HrFollowUpFactory.php
> +            '9',
done

2022-09-07 11:52 UTC, belwalshubham commented on Modules/HR/Database/Seeders/ApplicationEvaluationTableSeeder.php
> +                ->count(20)
done

2022-09-07 11:52 UTC, belwalshubham commented on Modules/HR/Database/Factories/HrApplicationsFactory.php
> +            '2',
done

2022-09-07 11:52 UTC, belwalshubham commented on Modules/HR/Database/Seeders/HrApplicationRoundTableSeeder.php
> +
done

2022-09-07 11:52 UTC, belwalshubham commented on Modules/HR/Database/Factories/HrApplicationsFactory.php
> +            'resume' => 'https://coloredcow.com/wp-content/uploads/2022/08/sample.pdf',
done

2022-09-07 11:52 UTC, belwalshubham commented on Modules/HR/Database/Seeders/HrApplicationRoundTableSeeder.php
> +                        'hr_round_id' => 1,
done

2022-09-07 11:52 UTC, belwalshubham commented on Modules/HR/Database/Seeders/HrApplicationSegmentTableSeeder.php
> +                ->count(20)
done

2022-09-07 11:52 UTC, belwalshubham commented on Modules/HR/Database/Seeders/HrApplicationsTableSeeder.php
> +              ->count(60)
done

2022-09-07 11:52 UTC, belwalshubham commented on Modules/HR/Database/Seeders/HrDomainTableSeeder.php
> +            ], [
done

2022-09-07 11:52 UTC, belwalshubham commented on Modules/HR/Database/Seeders/HrFollowUpTableSeeder.php
> +                ->count(20)
done

2022-09-07 11:53 UTC, belwalshubham commented on Modules/HR/Database/Seeders/ResumeScreeningEvaluationSeeder.php
> +
done

2022-09-09 14:10 UTC, GauravGusain98 requested changes
Please check the comments

2022-09-09 14:10 UTC, GauravGusain98 commented on Modules/HR/Entities/ApplicationRound.php
> -
Why removed this? Is this not being used?

2022-09-09 14:10 UTC, GauravGusain98 commented on Modules/HR/Entities/Evaluation/Segment.php
> +// use Modules\HR\Database\Factories\HrApplicationEvaluationSegmentFactory;
remove this if not being used

2022-09-09 15:15 UTC, belwalshubham commented on Modules/HR/Entities/ApplicationRound.php
> -
yess, I removed this because here I call application round factory but there is no need to use application round factory which also I removed , wih only seeder all the functionalities working fine so, there is no need of add applicationRound.php here.

2022-09-12 05:24 UTC, GauravGusain98 approved these changes

2022-09-12 05:46 UTC, merged