Added module - Project Contracts
ColoredCow/portal pull request #2262
Opened 2022-08-22 11:52 UTC by Kirannegi02

Targets #2252 

### Description
- Added a new module - Project Contract

### Checklist:

- [ ] I have performed a self-review of my own code.

2022-09-11 14:09 UTC, gautam071 requested changes
Left some comments

2022-09-11 14:09 UTC, gautam071 commented on Modules/ProjectContract/Entities/ProjectContractMeta.php
> +    protected $guarded = [];
I think fillable array is missing

2022-09-11 14:09 UTC, gautam071 commented on Modules/ProjectContract/Http/Controllers/ProjectContractController.php
> +
Can we use services file?

2022-09-11 14:09 UTC, gautam071 commented on Modules/ProjectContract/Resources/views/create.blade.php
> +    <div class="">
why empty class

2022-09-11 14:09 UTC, gautam071 commented on Modules/ProjectContract/Resources/views/index.blade.php
> +                <button class="btn btn-info ml-2 text-white">Search</button>
Is this a search button?

2022-09-11 14:09 UTC, gautam071 commented on Modules/ProjectContract/Resources/views/index.blade.php
> +        </div>
Repeated code?

2022-09-11 14:09 UTC, gautam071 commented on Modules/ProjectContract/Resources/views/index.blade.php
> +                @empty
What is this for?

2022-09-11 14:09 UTC, gautam071 commented on database/migrations/2018_03_30_132837_create_projects_table.php
> +        ');
Revert back

2022-09-11 14:09 UTC, gautam071 commented on resources/views/layouts/navbar.blade.php
> +                @endcan
Have you created seeders as well?

2022-09-11 14:09 UTC, gautam071 commented on resources/views/status.blade.php
> +			@endforeach
Formatting?

2022-09-11 14:09 UTC, gautam071 commented
Please resolve the conflicts as well

2022-09-14 15:21 UTC, Kirannegi02 commented on Modules/ProjectContract/Resources/views/index.blade.php
> +                <button class="btn btn-info ml-2 text-white">Search</button>
Yes, it is a search button.

2022-09-14 15:27 UTC, Kirannegi02 commented on Modules/ProjectContract/Resources/views/index.blade.php
> +                @empty
For adding clients in the Index page.

2022-09-14 15:31 UTC, Kirannegi02 commented on resources/views/layouts/navbar.blade.php
> +                @endcan
No, I haven't created.

2023-04-07 12:05 UTC, closed without merging