total expected efforts for fixed budget
ColoredCow/portal pull request #2266
Opened 2022-08-24 06:28 UTC by Abhinegi2

Targets #2239

### Description
 1- if project has Fixed Budget selected, we need to use that project Total Estimated Hours and project Duration.
 2-For Fixed Budget project type Total monthly expected efforts for project = Total Estimated Hours/Duration.
 3-After that we need to calculate Daily Expected Hours and Weekly Expected Hours for that project.
 4-For Monthly billling , No calculation,as it is.Total will be the sum of Individual expected hours.

- [ ] I have performed a self-review of my own code.

2022-08-24 06:33 UTC, gautam071 commented
@Abhinegi2 Please fix the CI checks

2022-08-25 05:16 UTC, gautam071 commented
@Abhinegi2 I am able to see @Himanshunegi0332 commits in your PR as well
Can you check that once?

2022-08-31 05:18 UTC, Abhinegi2 commented
> @Abhinegi2 I am able to see @Himanshunegi0332 commits in your PR as well Can you check that once?

i checked, this is happened because i forget about changing  my git config email and username .

2022-09-05 16:53 UTC, gautam071 requested changes

2022-09-05 16:53 UTC, gautam071 commented on Modules/Project/Resources/views/subviews/edit-project-team-members.blade.php
>                      </div>
Looks like some code are repeating can we make the repeated code command like `Daily` `Weekly` etc.

2023-04-07 12:05 UTC, closed without merging