2238/features view the wish listed books
ColoredCow/portal pull request #2270
Opened 2022-08-24 12:53 UTC by gulshan81

Targets #2238
### Description
 Now we see the wishlisted books 

### Checklist:
- [ ] I have performed a self-review of my own code.

2022-08-25 05:29 UTC, gautam071 requested changes

2022-08-25 05:29 UTC, gautam071 commented on app/Http/Controllers/KnowledgeCafe/Library/BookController.php
> +        if (request()->has('show')) {
Can we rename the `Show` to something related to the issue or fix

2022-08-25 05:29 UTC, gautam071 commented on resources/views/knowledgecafe/library/menu.blade.php
> +     $request['books'] = 'books';
Can we rename the `Books` to something related to the issue or fix

2022-08-25 05:29 UTC, gautam071 commented on resources/views/knowledgecafe/library/menu.blade.php
> +         $request['show'] = 'booksInWishlist';
same here

2022-08-25 05:59 UTC, gulshan81 commented on app/Http/Controllers/KnowledgeCafe/Library/BookController.php
> +        if (request()->has('show')) {
can you please suggest me something?

2022-08-25 06:25 UTC, P4NK4J reviewed
left a comment

2022-08-25 06:25 UTC, P4NK4J commented on resources/views/knowledgecafe/library/menu.blade.php
> +        <a class="nav-item nav-link {{ (request()->input('wishlist','active') === 'booksInWishlist') ? 'active' : '' }}"  href="{{ route('books.index', $request)  }}"><i class="fa fa-book"></i>&nbsp;
@gulshan81 Do you think a navigation item on UI would have `-` separated titles ?

2022-08-25 08:51 UTC, gulshan81 commented on resources/views/knowledgecafe/library/menu.blade.php
> +        <a class="nav-item nav-link {{ (request()->input('wishlist','active') === 'booksInWishlist') ? 'active' : '' }}"  href="{{ route('books.index', $request)  }}"><i class="fa fa-book"></i>&nbsp;
good afternoon @P4NK4J sorry for this late reply. I think you are right the navigation item on UI would not have the - separated titles. thank you.

2022-08-30 06:05 UTC, gautam071 approved these changes
Looks good!

2022-08-30 06:05 UTC, merged