changes added
ColoredCow/portal pull request #2280
Opened 2022-08-25 09:46 UTC by shivam333rawat

Targets #2254

### Description
Make the description field mandatory on recurring sales Expenses

### Checklist:

- [ ] I have performed a self-review of my own code.

2022-08-25 10:12 UTC, gautam071 approved these changes
Looks good one suggestion

2022-08-25 10:12 UTC, gautam071 commented on Modules/Expense/Resources/views/recurring/edit.blade.php
> +                                    <label for="description" class="field-required">Description</label>
```suggestion
                                    <label for="description" required="required">Description</label>
```

2022-08-25 10:58 UTC, P4NK4J reviewed
Left a question for you

2022-08-25 10:58 UTC, P4NK4J commented on Modules/Expense/Resources/views/recurring/edit.blade.php
> +                                    <label for="description" required = "required">Description</label>
```suggestion
                                    <label for="description" required>Description</label>
```

How about this ?

2022-08-25 14:10 UTC, P4NK4J approved these changes
Looks good.

2022-08-25 14:11 UTC, P4NK4J commented
@shivam333rawat I think you need to add `*` as well, as per the issue @gautam071 You can confirm this, but having a look at the issue description, it seems like a red * would be required.

2022-08-25 16:59 UTC, gautam071 commented
@P4NK4J You are right.

2022-08-25 17:00 UTC, gautam071 requested changes

2022-08-25 17:00 UTC, gautam071 commented on Modules/Expense/Resources/views/recurring/edit.blade.php
> +                                    <label for="description" class="field-required">Description</label>
<img width="81" alt="Screenshot 2022-08-25 at 10 29 41 PM" src="https://user-images.githubusercontent.com/73119570/186725770-a2972f52-7c38-4789-bd6d-dd1bf8588bd5.png">

Add the red astrix similar to the image

2022-08-26 09:37 UTC, gautam071 approved these changes

2022-08-26 09:37 UTC, merged