Changed alignment of search button
ColoredCow/portal pull request #2293
Opened 2022-08-26 08:37 UTC by Sarvesh-Ghildiyal

Targets #{2282}

### Description
Alligned search button with search placeholder.
### Checklist:

- [ ] I have performed a self-review of my own code.

2022-08-26 14:47 UTC, Ayush8923 requested changes
Please check the comments.

2022-08-27 05:37 UTC, gautam071 requested changes
remove this unwanted space

2022-08-27 05:37 UTC, gautam071 commented on resources/views/knowledgecafe/library/books/index.blade.php
> +        <div class="col-lg-4 col-md-5 col-sm-6 col-xs-12 mr-2 mb-2 p-2  d-flex justify-content-center align-items-center">
```suggestion
        <div class="col-lg-4 col-md-5 col-sm-6 col-xs-12 mr-2 mb-2 p-2 d-flex justify-content-center align-items-center">
```

2022-08-27 06:37 UTC, Sarvesh-Ghildiyal commented on resources/views/knowledgecafe/library/books/index.blade.php
> +        <div class="col-lg-4 col-md-5 col-sm-6 col-xs-12 mr-2 mb-2 p-2  d-flex justify-content-center align-items-center">
Okay! i have made the changes, but can you please explain how exactly does it affect the code?

2022-08-28 08:07 UTC, Sarvesh-Ghildiyal reviewed
Done

2022-08-28 08:56 UTC, closed without merging