added plus icon and changed  the background color
ColoredCow/portal pull request #2296
Opened 2022-08-26 09:35 UTC by Arjun8532

Targets #2288 

### Description
added  plus icon and changed the background color of Add client

### Checklist:

- [ ] I have performed a self-review of my own code.

2022-08-26 10:10 UTC, Ayush8923 commented
Please resolve merge conflict.

2022-08-26 10:10 UTC, Ayush8923 commented on Modules/Client/Resources/views/index.blade.php
> +            <a href= "{{ route('client.create') }}" class="btn btn-success float-right"><i class="fa fa-plus"></i> Add client</a>
Why did you add the float-right class here? While it was not needed.

2022-08-26 15:32 UTC, Ayush8923 requested changes
@Arjun8532 As far as I see the same code is written twice. Does it need to be written twice?

2022-08-26 15:33 UTC, Ayush8923 requested changes

2022-08-26 15:33 UTC, Ayush8923 commented on Modules/Client/Resources/views/index.blade.php
> +            <a href= "{{ route('client.create') }}" class="btn btn-success text-white"><i class="fa fa-plus"></i> Add new client</a>
As far as I see the same code is written twice. Does it need to be written twice?

2022-08-28 12:53 UTC, Ayush8923 requested changes
Please check the comment.

2022-08-28 12:53 UTC, Ayush8923 commented on Modules/Client/Resources/views/index.blade.php
> +                <a href= "{{ route('client.create') }}" class="btn btn-primary text-white">Add client</a>
Please change the name of the button here also. And also add plus icon. As done in line no. 8.

2022-08-28 15:07 UTC, Arjun8532 commented on Modules/Client/Resources/views/index.blade.php
> +                <a href= "{{ route('client.create') }}" class="btn btn-primary text-white">Add client</a>
Xamp was not functioning properly so  I  am reinstalling my portal as soon as I will be able to reset the portal
 I will make the suitable changes

2022-08-31 17:56 UTC, gautam071 commented
@Arjun8532 There are some conflicts please resolve them. 

If you don't know how. Please go through this link https://github.com/ColoredCow/portal/blob/master/docs/contributing.md#merge-conflict-

2022-09-03 08:15 UTC, Ayush8923 commented
The issue is already fixed.

2022-09-03 08:15 UTC, closed without merging