added a barchart in employee detail page
ColoredCow/portal pull request #2299
Opened 2022-08-27 07:59 UTC by JCArya

Targets #2065

 Description
 we added a bar chart to the employee detail page and this bar chart shows the effort of every team member.

2022-08-31 18:02 UTC, gautam071 requested changes

2022-08-31 18:02 UTC, gautam071 commented on Modules/HR/Http/Controllers/EffortReportController.php
> +        $color = ['#ff0080', '#00bfff', '#ffff00'];
what's the use of this?

2022-08-31 18:02 UTC, gautam071 commented on composer.json
> -        "friendsofphp/php-cs-fixer": "^3.0",
Why did you remove this?

2022-08-31 18:02 UTC, gautam071 commented on public/lib/fullcalendar/examples/php/get-events.php
> -
Why these changes?

2022-08-31 18:02 UTC, gautam071 commented on public/lib/fullcalendar/examples/php/utils.php
> -
Why these changes?

2022-09-05 10:56 UTC, JCArya commented on Modules/HR/Http/Controllers/EffortReportController.php
> +        $color = ['#ff0080', '#00bfff', '#ffff00'];
Using this gives the last seven days

2022-09-05 10:59 UTC, JCArya commented on composer.json
> -        "friendsofphp/php-cs-fixer": "^3.0",
because it is no longer in use

2022-09-05 11:05 UTC, JCArya commented on public/lib/fullcalendar/examples/php/get-events.php
> -
Because these files had CI checks fail

2022-09-05 11:05 UTC, JCArya commented on public/lib/fullcalendar/examples/php/utils.php
> -
Because these files had CI checks fail

2022-09-05 11:05 UTC, JCArya commented on Modules/HR/Resources/views/effort-report/bar-graph.blade.php
> +</script>
okay

2022-09-05 11:07 UTC, JCArya commented on Modules/HR/Resources/views/effort-report/bar-graph.blade.php
> +      }
But why not use CSS?

2022-09-19 06:57 UTC, gautam071 commented
@JCArya 

I am getting this error while clicking on the effort report icon

<img width="1440" alt="Screenshot 2022-09-19 at 12 25 45 PM" src="https://user-images.githubusercontent.com/73119570/190964083-1497207d-a81a-419c-baf6-35c0048db7b6.png">

2022-09-23 08:16 UTC, GauravGusain98 requested changes
Left some comments please check

2022-09-23 08:16 UTC, GauravGusain98 commented on Modules/HR/Http/Controllers/EffortReportController.php
> +    }
```suggestion
        return view('hr.effort.bar-graph', ['employee' => $employee, 'projectTeamMembers' => $projectTeamMembers],  'chartData' => json_encode($chartData));
    }
```

2022-09-23 08:16 UTC, GauravGusain98 commented on composer.json
> -        "friendsofphp/php-cs-fixer": "^3.0",
If this is not related to your code then revert this change.

2022-09-23 09:52 UTC, JCArya commented on Modules/HR/Http/Controllers/EffortReportController.php
> +    }
this way does not get any effort I tried.

2022-09-24 05:22 UTC, JCArya commented on Modules/HR/Http/Controllers/EffortReportController.php
> +                    ->where('project_team_member_id', $projectTeamMember->team_member_id)->sum('actual_effort');
this way does not get any effort I tried.

2023-04-07 12:05 UTC, closed without merging