Task 2155 INTERVIEW DURATION
ColoredCow/portal pull request #2305
Opened 2022-08-29 06:32 UTC by shardulgusain

#2155 

### Description
1.Modified HR/Recruitment/Job/edit page
2.Split scheduled date to date and time from timestamp.
3.Created a migration ,added a "meeting duration" field in "hr_application_round" table that is holding a timestamp for the interview duration.
4.For rounds only where we need calendar events, provided a Finish Interview button left to the pencil icon, clicking on which, an ajax call is going in the backend and saving the interview time in the column created in first step. Interview time is the difference between, scheduled_date timestamp and the time when Finish Interview button is calculated.
5.Fetching the same to the frontend in place of "finish interview button"

### Checklist:

- [ ] I have performed a self-review of my own code.

2022-08-30 09:30 UTC, P4NK4J requested changes
Left some comments, please check

2022-08-30 09:30 UTC, P4NK4J commented on Modules/HR/Http/Controllers/Recruitment/ApplicationController.php
> +    }
Let's write this function in ApplicationService, and rename it to `markInterviewFinished`

2022-08-30 09:30 UTC, P4NK4J commented on Modules/HR/Http/Controllers/Recruitment/ApplicationController.php
> +        $meet_Duration = Carbon::parse($meetDuration);
don't change variable naming convention, it should be in camelcase, also why two different meet durations are there ? this variable should be named on the basis of specific thing it is doing

2022-08-30 09:30 UTC, P4NK4J commented on Modules/HR/Routes/web.php
> +            Route::get('/finishinterview', 'JobApplicationController@finish')->name('finishinterview');
rename the function here as well

2022-08-30 09:30 UTC, P4NK4J commented on resources/views/hr/application/edit.blade.php
> +                                                        @if($applicationRound->meeting_duration!= NULL)
```suggestion
                                                        @if($applicationRound->meeting_duration) 
```

how about this ?

2022-08-30 09:30 UTC, P4NK4J commented on resources/views/hr/application/edit.blade.php
> +                                                        @if($applicationRound->meeting_duration!= NULL)
why so many nested if conditions ? let's merge them

2022-08-30 09:30 UTC, P4NK4J commented on resources/views/hr/application/edit.blade.php
> +                                                        <input type="Text" style="display: none;" readonly="readonly" name="meeting_time"
```suggestion
                                                        <input type="Text" style="display: none;" readonly="readonly" name="meetingTime"
```

Change at all the places

2022-08-30 09:30 UTC, P4NK4J commented on resources/views/hr/application/edit.blade.php
> +                                                                $time=($time_diff->days * 24) + $time_diff->h;
Please correct variable names, date1 and date2 doesn't make sense. Also, the variable name should be in camelcase

2022-08-31 03:35 UTC, shardulgusain commented on Modules/HR/Http/Controllers/Recruitment/ApplicationController.php
> +    }
okay

2022-08-31 03:35 UTC, shardulgusain commented on Modules/HR/Http/Controllers/Recruitment/ApplicationController.php
> +        $meet_Duration = Carbon::parse($meetDuration);
got it

2022-08-31 03:35 UTC, shardulgusain commented on Modules/HR/Routes/web.php
> +            Route::get('/finishinterview', 'JobApplicationController@finish')->name('finishinterview');
okay

2022-08-31 03:35 UTC, shardulgusain commented on resources/views/hr/application/edit.blade.php
> +                                                        @if($applicationRound->meeting_duration!= NULL)
yeah..thanks

2022-08-31 03:36 UTC, shardulgusain commented on resources/views/hr/application/edit.blade.php
> +                                                        @if($applicationRound->meeting_duration!= NULL)
okay

2022-09-26 06:24 UTC, merged