add applications-round wise filer
ColoredCow/portal pull request #2311
Opened 2022-08-29 13:45 UTC by rohit123-rawat

Targets #2273 

### Description
add applications-round wise filter

### Checklist:

- [ ] I have performed a self-review of my own code.

2022-08-29 14:19 UTC, P4NK4J requested changes
Left some comments, please check

2022-08-29 14:19 UTC, P4NK4J commented on Modules/HR/Entities/Application.php
> +                    $query->filterBydetails($value);
I see we already have a scope defined for roundName in line 135-137, can we use that ?

2022-08-29 14:19 UTC, P4NK4J commented on Modules/HR/Entities/Application.php
> +    }
Let's use the scopeFilterbyRoundName in above lines

2022-08-29 14:19 UTC, P4NK4J commented on Modules/HR/Http/Controllers/Recruitment/ApplicationController.php
> +            'details' => request()->get('details')
We already have round defined, can we use the same ?

2022-08-29 14:19 UTC, P4NK4J commented on Modules/HR/Http/Controllers/Recruitment/ApplicationController.php
> +        $attr['details'] = round::orderBy('name')->get();
Can we use roundName here instead of `details`?

2022-08-29 14:19 UTC, P4NK4J commented on resources/views/hr/application/index.blade.php
> +                            $class = in_array($detail->id, request()->get('details') ?? []) ? 'visible' : 'invisible';
Can we use rounds instead of details keyword ?

2022-08-30 06:50 UTC, rohit123-rawat commented on Modules/HR/Entities/Application.php
> +                    $query->filterBydetails($value);
no, that one is used for different function

2022-08-30 06:51 UTC, rohit123-rawat commented on Modules/HR/Entities/Application.php
> +    }
that one is used for different function

2022-08-30 06:53 UTC, rohit123-rawat commented on Modules/HR/Http/Controllers/Recruitment/ApplicationController.php
> +            'details' => request()->get('details')
round use for other functions.
so I can change details to round filters.

2022-08-30 06:54 UTC, rohit123-rawat commented on Modules/HR/Http/Controllers/Recruitment/ApplicationController.php
> +        $attr['details'] = round::orderBy('name')->get();
I'm using round Filters.

2022-08-30 06:56 UTC, rohit123-rawat commented on resources/views/hr/application/index.blade.php
> +                            $class = in_array($detail->id, request()->get('details') ?? []) ? 'visible' : 'invisible';
I'll change details into round filters.

2022-08-30 06:56 UTC, rohit123-rawat commented on Modules/HR/Http/Controllers/Recruitment/ApplicationController.php
> +        $attr['details'] = round::orderBy('name')->get();
I'll change details into round filters.

2022-08-30 06:57 UTC, rohit123-rawat commented on Modules/HR/Http/Controllers/Recruitment/ApplicationController.php
> +        $attr['details'] = round::orderBy('name')->get();
ok I'll change it

2022-08-30 06:58 UTC, rohit123-rawat commented on resources/views/hr/application/index.blade.php
> +                            $class = in_array($detail->id, request()->get('details') ?? []) ? 'visible' : 'invisible';
ok, I'll change it.

2022-08-30 10:44 UTC, P4NK4J approved these changes
Looks good.

2022-08-30 10:44 UTC, merged