changed background color of <add new project> button and added plus icon before it
ColoredCow/portal pull request #2316
Opened 2022-08-30 11:34 UTC by Sarvesh-Ghildiyal

Targets #{ISSUE_ID}
2314

### Description
I changed background color of <add new project> button and added plus icon before it

### Checklist:

- [ ] I have performed a self-review of my own code.

2022-08-30 18:14 UTC, Ayush8923 commented
@Sarvesh-Ghildiyal Please enter the issue link in your PR. And also resolve the merge conflict.

2022-08-31 18:09 UTC, gautam071 commented
@Sarvesh-Ghildiyal Can you resolve the merge conflicts?

2022-09-01 08:51 UTC, Ayush8923 requested changes
Please check the comments.

2022-09-01 08:51 UTC, Ayush8923 commented on Modules/Project/Resources/views/index.blade.php
> +                <a href= "{{ route('project.create') }}" class="btn btn-success text-white"><i class="fa fa-plus" style="font-size:14px"></i> {{ __('Add new project') }}</a>
Please use bootstrap class instead of normal CSS.

2022-09-05 10:14 UTC, Ayush8923 requested changes
Please check the comments.

2022-09-05 10:14 UTC, Ayush8923 commented on resources/views/knowledgecafe/library/books/index.blade.php
> +                <a href="{{ route('books.create') }}" class="btn btn-success float-right"><i class="fa fa-plus fs-1 mr-12"></i> Add New Book</a>
Why have you made changes to this file? While there was no need to make changes to this file.

2022-09-05 10:14 UTC, Ayush8923 commented on Modules/Project/Resources/views/index.blade.php
> +                <a href= "{{ route('project.create') }}" class="btn btn-success text-white"><i class="fa fa-plus fs-5"></i> {{ __('Add new project') }}</a>
Why did you add the `fs-5` class?

2022-09-09 04:57 UTC, gautam071 approved these changes
Looks good!

@Ayush8923 Can you take a look at this PR once?

2022-09-09 15:13 UTC, Ayush8923 approved these changes
LGTM.

2022-09-09 15:14 UTC, merged