Feature/2097 manage evaluations round wise segments
ColoredCow/portal pull request #2320
Opened 2022-08-30 18:43 UTC by LAKSHYA0501

Targets #2097 
### Description
1. Made changes in the UI from tables to accordions.
2. Added Round wise evaluations in accrodions and a drop down of respective segments.
3. fixed delete button.

### Checklist:
- [ ] I have performed a self-review of my own code.

2022-09-01 13:45 UTC, P4NK4J requested changes
Left some comments, please check

2022-09-01 13:45 UTC, P4NK4J commented on Modules/HR/Http/Controllers/EvaluationController.php
> +            $segmentedRounds[$value->id] = $attr;
what is $segmentedRounds ? It doesn't make sense to me, can the variable be like roundWithSegments if that's what you meant ?

2022-09-01 13:45 UTC, P4NK4J commented on Modules/HR/Resources/views/evaluation/index.blade.php
> +
remove this space

2022-09-01 13:45 UTC, P4NK4J commented on Modules/HR/Resources/views/evaluation/index.blade.php
> +                    <div class="card" style="background-color:#E7E6E0">
Let's use bootstrap class for this, maybe something like `bg-color-variable` defined in variables.scss

2022-09-01 13:45 UTC, P4NK4J commented on Modules/HR/Resources/views/evaluation/index.blade.php
> +                    echo "show";}?>" aria-labelledby="headingOne">
Let's use ternary operators here `$count == 0 ? 'show' : ' '`

2022-09-01 13:45 UTC, P4NK4J commented on Modules/HR/Resources/views/evaluation/index.blade.php
> +                            </tr>
Can you explain what's inside $round, $attr and $segment ? I don't think three nested for loops is a good practice

2022-09-01 18:05 UTC, LAKSHYA0501 commented on Modules/HR/Resources/views/evaluation/index.blade.php
> +                    echo "show";}?>" aria-labelledby="headingOne">
ok done for this?

2022-09-01 18:05 UTC, LAKSHYA0501 commented on Modules/HR/Resources/views/evaluation/index.blade.php
> +
done

2022-09-01 18:06 UTC, LAKSHYA0501 commented on Modules/HR/Http/Controllers/EvaluationController.php
> +            $segmentedRounds[$value->id] = $attr;
so i was not sure with name that's why i used this one, no worries i changed it.

2022-09-02 06:02 UTC, LAKSHYA0501 commented on Modules/HR/Resources/views/evaluation/index.blade.php
> +                    <div class="card" style="background-color:#E7E6E0">
done

2022-09-02 06:07 UTC, LAKSHYA0501 commented on Modules/HR/Resources/views/evaluation/index.blade.php
> +                            </tr>
In $round we have id and name of all rounds
in $attr we have round_id wise data of all segments in arrays
in  $segment we have different parameters or data of segments 

So should i change them?

2022-09-02 12:24 UTC, P4NK4J approved these changes
Looks good.

2022-09-02 12:24 UTC, merged