Change the text color
ColoredCow/portal pull request #2325
Opened 2022-08-31 11:15 UTC by Shivanshu2003

Targets #2324

### Description
Changed the background color of delete button

### Checklist:

- [ ] I have performed a self-review of my own code.

2022-08-31 18:10 UTC, gautam071 requested changes

2022-08-31 18:10 UTC, gautam071 commented on resources/views/knowledgecafe/library/categories/index.blade.php
> +                <div  class="btn btn-danger" @click="deleteCategory(index)">
```suggestion
                <div class="btn btn-danger" @click="deleteCategory(index)">
```

2022-09-01 14:19 UTC, Ayush8923 requested changes
Please check the comment.

2022-09-01 14:19 UTC, Ayush8923 commented on resources/views/knowledgecafe/library/categories/index.blade.php
> +                <div  class="btn btn-danger" @click="deleteCategory(index)">
Why removed the `c-pointer` and `ml-3` class?

2022-09-03 07:33 UTC, Ayush8923 requested changes
Please check the comment.

2022-09-03 07:33 UTC, Ayush8923 commented on resources/views/knowledgecafe/library/categories/index.blade.php
> +                <div  class="btn btn-danger" class="text-danger c-pointer ml-3" @click="deleteCategory(index)">
Why removed the `c-pointer` and `ml-3` class?

2022-09-03 14:18 UTC, Ayush8923 requested changes
Please check the comment.

2022-09-03 14:18 UTC, Ayush8923 commented on resources/views/knowledgecafe/library/categories/index.blade.php
> +                <div  class="btn btn-danger text-white c-pointer ml-3"  @click="deleteCategory(index)">
@Shivanshu2003 Remove the extra 2 spaces used before class and after class.

2022-09-09 17:34 UTC, Ayush8923 approved these changes
Looks good.

2022-09-09 17:35 UTC, Ayush8923 commented
@gautam071 Can you take a look at this PR once?

2022-09-17 07:24 UTC, Ayush8923 approved these changes

2022-09-17 07:25 UTC, Ayush8923 approved these changes

2022-09-17 07:31 UTC, gautam071 approved these changes

2022-09-17 07:31 UTC, merged