Added table in Project Dashboard and made route for efforts
ColoredCow/portal pull request #2326
Opened 2022-08-31 12:59 UTC by Sachinbisht27

Targets #2182 

### Description
Added table for my projects in dashboard and also added user efforts in table.

### Checklist:

- [ ] I have performed a self-review of my own code.

2022-08-31 18:09 UTC, gautam071 requested changes
Left some comments!

2022-08-31 18:09 UTC, gautam071 commented on Modules/User/Entities/User.php
> +    }
Can we try to incorporate with the active projects() function 
looks like there are lot of similarites

2022-08-31 18:09 UTC, gautam071 commented on resources/js/components/Dashboard/UserDashboardProjects.vue
> +		<div class="card ">
Indentation of the file

2022-09-01 09:58 UTC, Sachinbisht27 commented on Modules/User/Entities/User.php
> +    }
Ok understand.

2022-09-01 09:59 UTC, Sachinbisht27 commented on resources/js/components/Dashboard/UserDashboardProjects.vue
> +		<div class="card ">
ok done

2022-09-02 06:13 UTC, gautam071 requested changes

2022-09-02 06:13 UTC, gautam071 commented on resources/js/components/Dashboard/UserDashboardProjects.vue
> +								</table>
Check the indentation

2022-09-02 06:20 UTC, gautam071 approved these changes
Looks good!

2023-04-07 12:33 UTC, pankaj-ag approved these changes

2023-04-07 12:37 UTC, closed without merging