Ajax scrolling implimented in place of pagination
ColoredCow/portal pull request #2328
Opened 2022-09-01 06:35 UTC by tarunnjoshi

Targets #2207

### Description
Ajax scrolling implemented in CRM->project

### Checklist:
- [ ] I have performed a self-review of my own code.

2022-09-05 16:55 UTC, gautam071 requested changes

2022-09-05 16:55 UTC, gautam071 commented on Modules/Project/Resources/views/client-project.blade.php
> +                    <td class="w-33p"><div class="pl-2 pl-xl-3"><a href="{{ route('project.show', $project) }}">{{ $project->name }}</a></div></td>
formating

2022-09-05 16:55 UTC, gautam071 commented on Modules/Project/Resources/views/client-project.blade.php
> +                    <td class="w-33p"><div class="pl-2 pl-xl-3">{{ $project->name }}</div></td>
formating

2022-09-05 16:55 UTC, gautam071 commented on Modules/Project/Resources/views/client-project.blade.php
> +                        <a href={{ route('employees.show', $teamMember->user->employee) }}><img src="{{ $teamMember->user->avatar }}" class="w-35 h-30 rounded-circle mb-1 mr-0.5 {{ $teamMember->curre
Formating can you check use the blade formatter

2022-09-06 05:44 UTC, tarunnjoshi commented
Formatted

2023-04-07 12:38 UTC, closed without merging