triggereing mail to keyAccountManager
ColoredCow/portal pull request #2330
Opened 2022-09-01 07:59 UTC by Abhishek25081999

Targets #{2321}

### Description
Triggering mail to Key Account Manager for fixed budget projects.

### Checklist:
- [ ] I have performed a self-review of my own code.

2022-09-01 08:11 UTC, P4NK4J requested changes
Looks good, left some comments on your PR

2022-09-01 08:11 UTC, P4NK4J commented on Modules/Project/Resources/views/mail/fixed-budget-project.blade.php
> +	<p>Hi, {{ $projectData[0]['name'] }}</p>
Why we are using hardcoded index here ?

2022-09-01 08:11 UTC, P4NK4J commented on Modules/Project/Resources/views/mail/fixed-budget-project.blade.php
> +					<p>{{$projectData[0]['end date']->todatestring()}}</p>
why hardcoded index here as well ?

2022-09-01 08:11 UTC, P4NK4J commented on app/Console/Kernel.php
> +        $schedule->command('project:Fixed-budget-project');
Let's keep the command name in small case

2022-09-01 08:22 UTC, Abhishek25081999 commented on Modules/Project/Resources/views/mail/fixed-budget-project.blade.php
> +	<p>Hi, {{ $projectData[0]['name'] }}</p>
I did this because I don't know if there is any other way.

2022-09-01 08:22 UTC, Abhishek25081999 commented on app/Console/Kernel.php
> +        $schedule->command('project:Fixed-budget-project');
okay!

2022-09-01 08:22 UTC, Abhishek25081999 commented on Modules/Project/Resources/views/mail/fixed-budget-project.blade.php
> +					<p>{{$projectData[0]['end date']->todatestring()}}</p>
same as above

2022-09-01 12:33 UTC, Abhishek25081999 commented on Modules/Project/Resources/views/mail/fixed-budget-project.blade.php
> +	<p>Hi, {{ $projectData[0]['name'] }}</p>
sir I'm getting data in string and we are getting the name of user which is key account manager.

2022-09-02 05:46 UTC, P4NK4J approved these changes
Looks good

2022-09-02 05:49 UTC, gautam071 requested changes
One question

2022-09-02 05:49 UTC, gautam071 commented on Modules/Project/Resources/views/mail/fixed-budget-project.blade.php
> +<div>
@Abhishek25081999 can you check the formatting once in the blade file

2022-09-03 17:51 UTC, Abhishek25081999 commented on Modules/Project/Resources/views/mail/fixed-budget-project.blade.php
> +<div>
@gautam071 Done!.

2022-09-05 16:48 UTC, gautam071 approved these changes
Looks good to me!

2022-09-11 13:56 UTC, merged