disabling new member functionality
ColoredCow/portal pull request #2331
Opened 2022-09-01 08:31 UTC by Vimalnegi03

Targets #1624

### Description
I have successfully disabled the add new member functionality for  inactive or halted members.. 

### Checklist:

- [ ] I have performed a self-review of my own code.

2022-09-01 13:54 UTC, Ayush8923 requested changes
Please check the comments.

2022-09-01 13:54 UTC, Ayush8923 commented on Modules/Project/Resources/views/subviews/edit-project-team-members.blade.php
> +
Remove extra space.

2022-09-01 13:54 UTC, Ayush8923 commented on Modules/Project/Resources/views/subviews/edit-project-team-members.blade.php
> +
Same here. Remove extra line.

2022-09-02 12:34 UTC, Vimalnegi03 commented on Modules/Project/Resources/views/subviews/edit-project-team-members.blade.php
> +
okay sir

2022-09-03 09:36 UTC, Ayush8923 requested changes
Please check the comments.

2022-09-03 09:36 UTC, Ayush8923 commented on Modules/Project/Resources/views/subviews/edit-project-team-members.blade.php
> +                    <span v-on:click="addNewProjectTeamMember()" style="text-decoration: underline;" class="text-underline btn" >Add new team member</span>
Please use bootstrap class instead of inline CSS.

2022-09-17 07:29 UTC, Ayush8923 approved these changes
LGTM👍

2022-09-17 07:29 UTC, merged