add FTE alert and show columns
ColoredCow/portal pull request #2334
Opened 2022-09-01 12:32 UTC by rohit123-rawat

Targets #2250 

### Description
1. add feature FTE-Alert that is triggered when FTE is greater than 1.

### Checklist:

- [ ] I have performed a self-review of my own code.

2022-09-09 04:50 UTC, gautam071 commented
The CI checks are failing?

2022-09-10 08:39 UTC, P4NK4J requested changes
Overall looks good, left some minor comments.

2022-09-10 08:39 UTC, P4NK4J commented on Modules/HR/Emails/SendHiringMail.php
> +        ->to('hr@coloredcow.com')
Let's pick this from ENV

2022-09-10 08:39 UTC, P4NK4J commented on Modules/HR/Emails/SendHiringMail.php
> +        return $this->from(config('hr.default.email'), config('hr.default.name'))
Let's not send it from hr.default, instead, let's send it from `MAIL_FROM_ADDRESS` from ENV, or maybe check if its being used somewhere in the config. This would be a system email

2022-09-10 08:39 UTC, P4NK4J commented on Modules/HR/Entities/JobRequisition.php
> +    protected $fillable = ['domain_id', 'job_id'];
Do you think we need fillable here ?

2022-09-10 08:39 UTC, P4NK4J commented on Modules/HR/Http/Controllers/EmployeeController.php
> +        Mail::send(new SendHiringMail($jobHiring));
what's the use of `$jobHiring` here ?

2022-09-10 08:39 UTC, P4NK4J commented on Modules/HR/Http/Controllers/EmployeeController.php
> +        $DomainName = HrJobDomain::all();
```suggestion
        $domainName = HrJobDomain::all();
```

2022-09-10 08:39 UTC, P4NK4J commented on Modules/HR/Http/Controllers/EmployeeController.php
> +        $jobHiring = null;
Let's use store function of RequisitionController, instead of using modelInstance

2022-09-10 08:39 UTC, P4NK4J commented on Modules/HR/Routes/web.php
> +        Route::get('/rquisition-complete', 'RequisitionController@showCompletedRequisition')->name('employees.complete');
```suggestion
        Route::get('/requisition-complete', 'RequisitionController@showCompletedRequisition')->name('employees.complete');
```

2022-09-10 08:39 UTC, P4NK4J commented on resources/js/app.js
> +
```suggestion
```

2022-09-10 08:39 UTC, P4NK4J commented on resources/views/emails/send-hiring.blade.php
> +   <a href="http://portal.test/hr/requisition">click here</a>
Let's not hardcode the URL here, use it from ENV, APP_URL

2022-09-10 08:39 UTC, P4NK4J commented on resources/views/hr/employees/fte-handler.blade.php
> +                                        <option value="{{ $DomainName->id }}">{{ $DomainName->domain }}</option>
Correct the variable name, please use camelCase. Make changes at all the places, wherever you find the inconsistency

2022-09-10 08:39 UTC, P4NK4J commented on resources/views/hr/employees/fte-handler.blade.php
> +                            <button type="submit" class="btn btn-primary" data-action="SendHiringMail">Submit</button>
```suggestion
                            <button type="submit" class="btn btn-primary" data-action="sendHiringMail">Submit</button>
```

2022-09-10 08:39 UTC, P4NK4J commented on resources/views/hr/employees/index.blade.php
> +
Remove extra spaces from everywhere

2022-09-10 12:03 UTC, P4NK4J requested changes
Left some comments, please check

2022-09-10 12:03 UTC, P4NK4J commented on Modules/HR/Config/config.php
> +    ],
We won't need requisition URL as a separate variable, use APP_URL/your_route

2022-09-10 12:03 UTC, P4NK4J commented on Modules/HR/Emails/SendHiringMail.php
> +        ->view('emails.send-hiring');
Sender address is missing, its throwing error on the form submission

2022-09-12 05:12 UTC, P4NK4J approved these changes
Overall looks good, just one thing, after form submission the overlay of modal is appearing. Please correct and it should be good to go

2022-09-13 07:14 UTC, merged