added filter in  knowledgecafe module
ColoredCow/portal pull request #2347
Opened 2022-09-03 06:06 UTC by akriti12negi

#2186 

### Description
Added filter the books that i have read in KnowledgeCafe module

### Checklist:
I have performed a self-review of my own code.

2022-09-05 05:51 UTC, gautam071 requested changes

2022-09-05 05:51 UTC, gautam071 commented on app/Models/KnowledgeCafe/Library/Book.php
> +                        ->orWhere('isbn', 'LIKE', "%$searchString%");
What's the reason of changing the variable name?

2022-09-05 06:19 UTC, akriti12negi commented on app/Models/KnowledgeCafe/Library/Book.php
> +                        ->orWhere('isbn', 'LIKE', "%$searchString%");
fixed it

2022-09-07 14:42 UTC, gautam071 requested changes
Looks good a question

2022-09-07 14:42 UTC, gautam071 commented on app/Models/KnowledgeCafe/Library/Book.php
> +                        ->orWhere('isbn', 'LIKE', "%$filterString%");
Variable name changes why?

2022-09-08 07:23 UTC, akriti12negi commented on app/Models/KnowledgeCafe/Library/Book.php
> +                        ->orWhere('isbn', 'LIKE', "%$filterString%");
changed earlier, this is the original variable name

2022-09-16 18:11 UTC, closed without merging