Added Borrowed Books Tab
ColoredCow/portal pull request #2353
Opened 2022-09-03 14:15 UTC by Sachinbisht27

Targets #2337 

### Description
Added borrowed books tab in knowledge cafe.

### Checklist:

- [ ] I have performed a self-review of my own code.

2022-09-05 05:47 UTC, gautam071 requested changes

2022-09-05 05:47 UTC, gautam071 commented on resources/views/knowledgecafe/library/menu.blade.php
> +        <a class="nav-item nav-link {{ (request()->input('borrowedBook','active') === 'markedAsBorrowed') ? 'active' : '' }}"  href="{{ route('books.index', $params)  }}"><i class="fa fa-book"></i>&n
Did you replace the wishlist to borrowed?

2022-09-05 06:19 UTC, Sachinbisht27 commented on resources/views/knowledgecafe/library/menu.blade.php
> +        <a class="nav-item nav-link {{ (request()->input('borrowedBook','active') === 'markedAsBorrowed') ? 'active' : '' }}"  href="{{ route('books.index', $params)  }}"><i class="fa fa-book"></i>&n
I replaced wishlist with borrowed but, before that i added wishlist tab code above. (line 27)

2022-09-05 06:19 UTC, Sachinbisht27 commented on resources/views/knowledgecafe/library/menu.blade.php
> +        <a class="nav-item nav-link  {{ (request()->input('wishlist','active') === 'booksInWishlist') ? 'active' : '' }}"  href="{{ route('books.index', $params)  }}"><i class="fa fa-book"></i>&nbsp;
here

2022-09-05 06:21 UTC, Sachinbisht27 commented on resources/views/knowledgecafe/library/menu.blade.php
> +        <a class="nav-item nav-link {{ (request()->input('borrowedBook','active') === 'markedAsBorrowed') ? 'active' : '' }}"  href="{{ route('books.index', $params)  }}"><i class="fa fa-book"></i>&n
i tested both wishlist and borrowed working good

2022-09-24 06:37 UTC, gautam071 approved these changes
Looks good

2022-09-24 06:37 UTC, merged