On filtering months in FTE page table is available
ColoredCow/portal pull request #2367
Opened 2022-09-05 11:02 UTC by Sachinbisht27

Targets #2365 

### Description
On filtering months in FTE page for Projects table is available for all months.

### Checklist:

- [ ] I have performed a self-review of my own code.

2022-09-05 11:25 UTC, gautam071 commented
@Sachinbisht27 Displaying the table is part of the requirement 
but the table needs to calculate all the details according to the filtered month

2022-09-05 11:26 UTC, gautam071 commented
Please make the changes accordingly

2022-09-07 14:48 UTC, gautam071 requested changes
Left some comments

2022-09-07 14:48 UTC, gautam071 commented on Modules/EffortTracking/Resources/views/show.blade.php
> -    @if($totalMonths === 0)
why did you remove this code?

2022-09-07 14:48 UTC, gautam071 commented on Modules/EffortTracking/Resources/views/show.blade.php
> +                                <td>{{ $teamMember->getFteAttribute($startDate, $endDate) }}</td>
Looks like the function is called in multiple places can we assign a variable for the function and call it

2022-09-07 15:58 UTC, Sachinbisht27 commented on Modules/EffortTracking/Resources/views/show.blade.php
> -    @if($totalMonths === 0)
if  i am putting @if($totalMonths === 0) there the table is only working for current month and if i am putting @if($totalMonths === 0 || $totalMonths != 0) then the table working for both current and previous months also.
But, i thought that if we are putting total month ($totalMonths === 0 || $totalMonths != 0) what is the need of this $totalMonths now.
that's why i removed it...
Should i have to add the condition for ==0 and != 0?

2022-09-07 16:06 UTC, Sachinbisht27 commented on Modules/EffortTracking/Resources/views/show.blade.php
> +                                <td>{{ $teamMember->getFteAttribute($startDate, $endDate) }}</td>
*send

2022-09-07 17:58 UTC, Sachinbisht27 commented on Modules/EffortTracking/Resources/views/show.blade.php
> +                                <td>{{ $teamMember->getFteAttribute($startDate, $endDate) }}</td>
@gautam071 after doing suggested changes i am not getting the data as expected.

2022-09-08 08:31 UTC, Sachinbisht27 commented
@gautam071 on adding variables over attribute functions in show.blade not getting correct values in table.

2022-09-09 04:54 UTC, gautam071 requested changes

2022-09-09 04:54 UTC, gautam071 commented on Modules/EffortTracking/Resources/views/show.blade.php
> -    @if($totalMonths === 0)
@Sachinbisht27 
`@if($totalMonths === 0 || $totalMonths != 0)`

it means `$totalMonths` if it is zero and not zero it should run right. 
Then what is the use of the check?

2022-09-09 06:06 UTC, Sachinbisht27 commented on Modules/EffortTracking/Resources/views/show.blade.php
> -    @if($totalMonths === 0)
yes, we have to run the table for both $totalMonths zero and not zero.  i thought that if we are putting ($totalMonths === 0 || $totalMonths != 0) what is the need of this. that's why i previously removed it.

2022-09-09 14:42 UTC, gautam071 approved these changes
Looks good to me

2022-09-09 14:42 UTC, merged