changed 'no contract' button using bootstrap class
ColoredCow/portal pull request #2369
Opened 2022-09-05 11:13 UTC by Vishakha7906

Targets #{2354}

### Description
no contract button changes using bootstarp class

### Checklist:

- [ ] I have performed a self-review of my own code.

2022-09-05 11:25 UTC, Ayush8923 requested changes
Please check the comments.

2022-09-05 11:25 UTC, Ayush8923 commented on Modules/Project/Resources/views/index.blade.php
> +                                    <div class="text-center"> <span class="badge badge-pill badge-secondary">No Contract</span> </div>                                    @endif
Why have you used extra `div` here?
We don't need extra `div` here.

2022-09-06 16:39 UTC, Ayush8923 requested changes
Please check the comments.

2022-09-06 16:39 UTC, Ayush8923 commented on Modules/Project/Resources/views/index.blade.php
> +                                <td>  <div class="text-center">
@Vishakha7906 Why did you use extra div here? Whereas we don't need this extra div. And as far as I see this extra div is not closed.

2022-09-06 16:39 UTC, Ayush8923 commented on package-lock.json
>      "packages": {
Please remove this `package.json` file from your PR. We don't need this file.

2022-09-07 08:58 UTC, Vishakha7906 commented on Modules/Project/Resources/views/index.blade.php
> +                                <td>  <div class="text-center">
@Ayush8923 I have done the required changes can you please review it again.

2022-09-09 04:56 UTC, gautam071 commented
@Vishakha7906 Please fix the conflicts

2022-09-11 17:29 UTC, Vishakha7906 commented
@gautam071 I am facing some issues with my laptop so that's why it is taking time.
I hope I will complete it by tomorrow.

2022-09-15 11:15 UTC, closed without merging