Validation applied on the backend for recurring expense
ColoredCow/portal pull request #2377
Opened 2022-09-06 13:08 UTC by dhruvshrinet1

Targets #{ISSUE_ID}

### Description

### Checklist:

- [ ] I have performed a self-review of my own code.

2022-09-07 11:16 UTC, P4NK4J requested changes
Left some comments, please take a look.

2022-09-07 11:16 UTC, P4NK4J commented on Modules/Expense/Resources/views/recurring/create.blade.php
> +@endif
I think this would display all the errors on the top of the blade file, instead of this, you can place them below the input fields as well. Let me know what you think ?
On a sidenote - the indentation is a bit off, please correct the same

2022-09-07 11:16 UTC, P4NK4J commented on Modules/Expense/Resources/views/recurring/create.blade.php
> +                                      required="required"   value="{{ now()->format('Y-m-d') }}">
Why extra space here ?

2022-09-07 11:16 UTC, P4NK4J commented on Modules/Expense/Resources/views/recurring/create.blade.php
> +                                        <option value="yearly" >Yearly</option>
Why extra space here ?

2022-09-07 11:16 UTC, P4NK4J commented on Modules/Expense/Resources/views/recurring/create.blade.php
> +                                       required="required"  />
how about this ?
```suggestion
                                       required />
```

2022-09-08 07:58 UTC, dhruvshrinet1 commented on Modules/Expense/Resources/views/recurring/create.blade.php
> +@endif
I have made the changes as suggested please have a look

2022-09-10 10:43 UTC, P4NK4J reviewed
Minor suggestions else looks good. Just one question, what's the use of migrations cc_employees in this PR ?

2022-09-10 10:43 UTC, P4NK4J commented on Modules/Expense/Resources/views/recurring/create.blade.php
> +                                <div class="alert alert-danger">{{ $message }}</div>
```suggestion
                                    <div class="alert alert-danger">{{ $message }}</div>
```

2022-09-10 10:43 UTC, P4NK4J commented on Modules/Expense/Resources/views/recurring/create.blade.php
> +                                    <div class="alert alert-danger">{{ $message }}</div>
```suggestion
                                         <div class="alert alert-danger">{{ $message }}</div>
```

2022-09-10 10:43 UTC, P4NK4J commented on Modules/Expense/Resources/views/recurring/create.blade.php
> +                                   @enderror
```suggestion
                                    @error('name')
                                        <div class="alert alert-danger">{{ $message }}</div>
                                    @enderror
```

2022-09-10 10:56 UTC, dhruvshrinet1 commented
> Minor suggestions else looks good. Just one question, what's the use of migrations cc_employees in this PR ?

I lost my database so had to import it again cc_employees  was the name of database dump , updating as per the suggestions

2022-09-12 07:27 UTC, P4NK4J approved these changes
Looks good

2022-09-12 07:44 UTC, merged

2022-09-12 08:18 UTC, pankaj-ag commented on Modules/Expense/Http/Controllers/RecurringExpenseController.php
>          // ToDo:: we need to add validations here.
Remove this comment now.
> // ToDo:: we need to add validations here.