Bug Fixed for approve round and able to send mail with pdf attached
ColoredCow/portal pull request #2392
Opened 2022-09-08 07:36 UTC by LavishRawat

Targets #2363

### Description
Bug Fixed for approve round and able to send mail with pdf attached

### Checklist:
- [ ] I have performed a self-review of my own code.

2022-09-17 08:53 UTC, P4NK4J requested changes
Left some comments, please check

2022-09-17 08:53 UTC, P4NK4J commented on Modules/HR/Http/Controllers/Recruitment/ApplicantController.php
> +
Let' put these logics into service and use controller only to call the function. Also, let's rename the function to `storeApprovedApplicantDetails`

2022-09-17 08:53 UTC, P4NK4J commented on Modules/HR/Database/Migrations/2022_09_12_140344_create_hr_applicant_meta_table.php
> +        });
Can we include adding foreign key into the previous function only ?

2022-09-17 08:53 UTC, P4NK4J commented on Modules/HR/Entities/ApplicantMeta.php
> +    protected $fillable = ['key', 'value', 'hr_applicant_id'];
Why we need fillables here ? cant we keep guarded array empty? since all the fields would be fillable with that ?

2022-09-17 08:53 UTC, P4NK4J commented on Modules/HR/Http/Requests/ApplicantMetaRequest.php
> +            'scanned_copy_pan_card' => 'required|mimes:jpg,jpeg,png',
scanned copy can be pdf as well ? can you update the validations for a file, everywhere?

2022-09-17 08:53 UTC, P4NK4J commented on Modules/Salary/Config/config.php
> +        'basic_salary' => env('BASIC_SALARY', '30000')
why this is needed ?

2022-09-17 08:53 UTC, P4NK4J commented on app/Helpers/FileHelper.php
> +        $pdf = Pdf::loadView('hr.application.joining-letter', compact('applicant', 'job', 'offer_letter_body'));
let's rename it to draft offer letter ?

2022-09-17 08:53 UTC, P4NK4J commented on resources/js/app.js
> +function initRicheditor() {
why we have used this function here ?

2022-09-17 08:53 UTC, P4NK4J commented on resources/views/hr/application/applicant-details.blade.php
> +<form action="{{route('hr.applicant.store-details')}}" enctype="multipart/form-data" method="POST">
Let's rename this route to `store-approved-applicants-details`

2022-09-17 08:53 UTC, P4NK4J commented on resources/views/hr/application/applicant-details.blade.php
> +
Let's rename this blade to `approved-applicants-details.balde.php`

2022-09-17 08:53 UTC, P4NK4J commented on resources/views/hr/application/applicant-details.blade.php
> +                                <label for="customFile0" class="custom-file-label overflow-hidden w-300">Add File</label>
```suggestion
                                <label for="customFile" class="custom-file-label overflow-hidden w-300">Add File</label>
```

2022-09-17 08:53 UTC, P4NK4J commented on resources/views/hr/application/applicant-details.blade.php
> +                                <label for="customFile0" class="custom-file-label overflow-hidden w-300">Add File</label>
```suggestion
                                <label for="customFile" class="custom-file-label overflow-hidden w-300">Add File</label>
```

2022-09-17 08:53 UTC, P4NK4J commented on resources/views/hr/application/applicant-details.blade.php
> +                                <label for="customFile0" class="custom-file-label overflow-hidden w-300 mt-2">Add File</label>
```suggestion
                                <label for="customFile" class="custom-file-label overflow-hidden w-300 mt-2">Add File</label>
```

2022-09-17 08:53 UTC, P4NK4J commented on resources/views/hr/application/applicant-details.blade.php
> +                                <label for="customFile0" class="custom-file-label overflow-hidden w-300 mt-1">Add File</label>
```suggestion
                                <label for="customFile" class="custom-file-label overflow-hidden w-300 mt-1">Add File</label>
```

2022-09-17 08:53 UTC, P4NK4J commented on resources/views/hr/application/approve-applicant-modal.blade.php
> +                    <h5 class="modal-title" id="approved_application">Approve</h5>
```suggestion
                    <h5 class="modal-title" id="approvedApplication">Approve</h5>
```

2022-09-17 08:53 UTC, P4NK4J commented on resources/views/hr/application/approve-applicant-modal.blade.php
> +                        <label for="body" class="field-required" id="bigbang">Body</label>
```suggestion
                        <label for="body" class="field-required" >Body</label>
```

2022-09-17 08:53 UTC, P4NK4J commented on resources/views/hr/application/edit.blade.php
> +                                                                @click="takeAction()" id="take_action">Take action</button>
```suggestion
                                                                @click="takeAction()" id="takeAction">Take action</button>
```

2022-09-17 08:53 UTC, P4NK4J commented on resources/views/hr/application/joining-letter.blade.php
> +    <head>
Let's rename this to `draft-joining-letter.blade.php`

2022-09-17 08:53 UTC, P4NK4J commented on resources/views/hr/application/joining-letter.blade.php
> +            <img src="C:\xampp\htdocs\portal\public\images\coloredcow.png">
Let's use relative URL and store cc logo into public folder

2022-09-17 08:53 UTC, P4NK4J commented on resources/views/hr/application/joining-letter.blade.php
> +ColoredCow Consulting Pvt. Ltd | +91 9818571035 | <span href="mailto">contact@colored.cow</span> |
```suggestion
ColoredCow Consulting Pvt. Ltd | +91 9818571035 | <span href="mailto">contact@coloredcow.com</span> | 
```

2022-09-29 05:09 UTC, P4NK4J requested changes
Left some comments, please check.

2022-09-29 05:09 UTC, P4NK4J commented on Modules/HR/Http/Controllers/Recruitment/ApplicantController.php
> +        $hr_applicant_id = $request->get('hr_applicant_id');
Let's use camelCasing in variables everywhere

2022-09-29 05:09 UTC, P4NK4J commented on Modules/HR/Http/Controllers/Recruitment/ApplicantController.php
> +    public function formSubmit($id, $email)
What this function is doing ?

2022-09-29 05:09 UTC, P4NK4J commented on Modules/HR/Http/Controllers/Recruitment/ApplicantController.php
> +    public function showFormDetails($id)
can we rename formDetails to specific function, say `showOnboardingFormDetails` ?

2022-09-29 05:09 UTC, P4NK4J commented on Modules/HR/Http/Controllers/Recruitment/ApplicationController.php
> +        }
what's the use of this logic ?

2022-09-29 05:09 UTC, P4NK4J commented on Modules/HR/Resources/views/application/render-application-row.blade.php
> +            @endif
Why are we are using the config tags instead of the database ?

2022-09-29 05:09 UTC, P4NK4J commented on Modules/HR/Routes/web.php
> +Route::get('/showDetails/{id}', 'Recruitment\ApplicantController@showFormDetails')->name('hr.applicant.show-applicant-form-details');
Can these route names be specific ? form-submitted seems to be very generic, applicant form can be the one where they are applying for recruitment. Can it be applicant-onboarding form ?

`/store` seems very generic, can we add specific keywords to the route as well

2022-09-29 05:09 UTC, P4NK4J commented on Modules/HR/Services/ApplicationService.php
> +                $file = $request->file($key);
ApplicationService, store function is specific to storing application details, can this logic go into Applicant Service, inside a specific function say `storeApplicantOnboardingDetails` ?

2022-09-29 05:09 UTC, P4NK4J commented on resources/views/hr/application/approved-applicants-details.blade.php
> +                                @enderror
Indentation seems a bit off for these blocks, can you check it once ?

2022-09-29 05:09 UTC, P4NK4J commented on resources/views/hr/application/retainership-template.blade.php
> +Mr/Mrs. {{$applicant->name}}
Let's remove retainership blade as of now, we will build this laterwards

2022-09-29 05:09 UTC, P4NK4J commented on resources/views/hr/application/draft-joining-letter.blade.php
> +                <pre>To							Date:{{\Carbon\Carbon::now()->format('d-m-y')}}</pre>
Is Carbon working fine here ?

2022-09-29 05:09 UTC, P4NK4J commented on resources/views/hr/application/draft-joining-letter.blade.php
> +                                          Name: Mr. Mohit Sharma
You can simply add empty container here, rather than adding spaces ?

2022-09-29 05:17 UTC, LavishRawat commented on Modules/HR/Database/Migrations/2022_09_26_134702_alter_column_for_application_meta_value.php
> +     */
so previous type of value column was varchar and it take upto 191 words only and the encrypted value had 201 words so when the encrypted value was stored in the column , the last 10 digits were not adding due to which we cannot decrypt the value.

2022-09-29 05:21 UTC, LavishRawat commented on Modules/HR/Http/Controllers/Recruitment/ApplicantController.php
> +    public function formSubmit($id, $email)
@P4NK4J it is viewing the details-submitted.blade.php which comes after the applicant had filled the personal details from where the applicant can preview the details filled or go back to update the details.

2022-09-29 05:23 UTC, LavishRawat commented on Modules/HR/Http/Controllers/Recruitment/ApplicationController.php
> +        }
@P4NK4J here we are checking if any hr_applicant_id in Application matches the hr_applicant_id in ApplicantMeta because if it matches it means that the applicant had filled the form.

2022-09-29 05:29 UTC, LavishRawat commented on resources/views/hr/application/draft-joining-letter.blade.php
> +                <pre>To							Date:{{\Carbon\Carbon::now()->format('d-m-y')}}</pre>
@P4NK4J yes it is working fine.

2022-09-29 05:30 UTC, LavishRawat commented on resources/views/hr/application/retainership-template.blade.php
> +Mr/Mrs. {{$applicant->name}}
@P4NK4J okay

2022-09-29 05:34 UTC, LavishRawat commented on resources/views/hr/application/approved-applicants-details.blade.php
> +                                @enderror
@P4NK4J okay

2022-09-29 05:38 UTC, LavishRawat commented on Modules/HR/Http/Controllers/Recruitment/ApplicantController.php
> +    public function showFormDetails($id)
@P4NK4J Done

2022-09-29 05:42 UTC, LavishRawat commented on Modules/HR/Services/ApplicationService.php
> +                $file = $request->file($key);
@P4NK4J okay

2022-09-29 07:26 UTC, LavishRawat commented on Modules/HR/Http/Controllers/Recruitment/ApplicantController.php
> +        $hr_applicant_id = $request->get('hr_applicant_id');
@P4NK4J Done

2022-09-29 07:41 UTC, LavishRawat commented on resources/views/hr/application/draft-joining-letter.blade.php
> +                                          Name: Mr. Mohit Sharma
@P4NK4J Done

2022-09-29 08:07 UTC, LavishRawat commented on Modules/HR/Resources/views/application/render-application-row.blade.php
> +            @endif
@P4NK4J here we are directly comparing the  hr_applicant_id from the ApplicantMeta table with the  hr_applicant_id from application table and if both matches we are then showing the badge and the badge label,title,class are stored in config.

2022-10-05 05:30 UTC, P4NK4J reviewed
Looks good.

2022-10-05 05:31 UTC, P4NK4J approved these changes

2022-10-05 05:31 UTC, merged