Featutr/2301/revenue module scaffolding
ColoredCow/portal pull request #2410
Opened 2022-09-12 08:57 UTC by Abhishek25081999

Targets #{2301}

### Description
Made new module Revenue

### Checklist:
- [ ] I have performed a self-review of my own code.

2022-09-12 12:50 UTC, pankaj-ag requested changes

2022-09-12 12:50 UTC, pankaj-ag commented on Modules/Revenue/Entities/Revenue.php
> +class Revenue extends Model
Let's called this table as **revenue_proceeds**

2022-09-12 12:50 UTC, pankaj-ag commented on Modules/Revenue/Database/Migrations/2022_09_09_171756_create_revenue_table.php
> +        Schema::create('Revenue', function (Blueprint $table) {
```suggestion
        Schema::create('revenue_proceeds', function (Blueprint $table) {
```

2022-09-12 12:50 UTC, pankaj-ag commented on Modules/Revenue/Entities/Revenue.php
> +class Revenue extends Model
```suggestion
class RevenueProceed extends Model
```

2022-09-12 12:50 UTC, pankaj-ag commented on Modules/Revenue/Http/Controllers/RevenueController.php
> +        $revenue->save();
Let's move this to a dedicated service class. Check other controllers and modules.

2022-09-12 12:50 UTC, pankaj-ag commented on Modules/Revenue/Http/Controllers/RevenueController.php
> +        return redirect()->route('revenue.index')->with('status', "$revenue->name updated successfully!!");
Same let's move this to services.

2022-09-12 12:50 UTC, pankaj-ag commented on Modules/Revenue/Http/Controllers/RevenueController.php
> +        return redirect()->route('revenue.index')->with('status', "$revenue->name deleted successfully!!");
Same here please.

2022-09-12 12:50 UTC, pankaj-ag commented on Modules/Revenue/Http/Requests/RevenueRequest.php
> +            'recieved_at' => 'nullable|integer',
Nice 👍

2022-09-12 12:50 UTC, pankaj-ag commented on Modules/Revenue/Resources/views/create.blade.php
> +<div class="modal fade bd-example-modal-lg" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
```suggestion
<div class="modal fade bd-example-modal-lg" id="editRevenueProcced" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
```

Let's change the name to editRevenueProcced or createRevenueProcced

2022-09-12 12:50 UTC, pankaj-ag commented on Modules/Revenue/Resources/views/edit.blade.php
> + <div class="modal fade text-left"  tabindex="-1" role="dialog" id="modalEdit" aria-hidden="true">
This file will be moved to Modules/Revenue/Resources/views/revenue-proceeds/edit.blade.php

Same will happen fro create view also.

2022-09-12 12:50 UTC, pankaj-ag commented on Modules/Revenue/Resources/views/layouts/master.blade.php
>  </html>
Let's remove these extra lines. Check other layout files.

2022-09-12 12:50 UTC, pankaj-ag commented on Modules/Revenue/Resources/views/layouts/master.blade.php
> +<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
Why do we need this file. Bootstrap is already there in app.js file I guess.

2022-09-12 12:50 UTC, pankaj-ag commented on Modules/Revenue/Routes/web.php
> +    Route::get('/', 'RevenueController@index')->name('revenue.index');
```suggestion
    Route::get('/', 'RevenueProceedController@index')->name('revenue.procceds.index');
```

2022-09-12 12:50 UTC, pankaj-ag commented on resources/views/layouts/navbar.blade.php
> +                    <a class="dropdown-item" href="{{ route('revenue.index') }}">Revenue</a>
I have moved these files in the report section. Please undo this change. 
We already have a Revenue ite, on like no 71 so let's enable that.

2022-09-12 12:50 UTC, pankaj-ag commented on webpack.mix.js
> +  .js("Modules/Revenue/Resources/assets/js/app.js", "public/js/revenue.js")
Good.

2022-09-12 13:11 UTC, Abhishek25081999 commented on Modules/Revenue/Entities/Revenue.php
> +class Revenue extends Model
okay!

2022-09-12 13:11 UTC, Abhishek25081999 commented on Modules/Revenue/Database/Migrations/2022_09_09_171756_create_revenue_table.php
> +        Schema::create('Revenue', function (Blueprint $table) {
okay

2022-09-14 04:19 UTC, pankaj-ag requested changes

2022-09-14 04:19 UTC, pankaj-ag commented on Modules/Revenue/Database/Migrations/2022_09_09_171756_create_revenue_table.php
> +        Schema::create('Revenue_proceeds', function (Blueprint $table) {
```suggestion
        Schema::create('revenue_proceeds', function (Blueprint $table) {
```

We never use the capital letters in the table name

2022-09-14 04:19 UTC, pankaj-ag commented on Modules/Revenue/Http/Requests/RevenueProceedRequest.php
> +            'recieved_at' => 'nullable|integer',
received_at should be a date right or integer?

2022-09-14 04:19 UTC, pankaj-ag commented on Modules/Revenue/Resources/views/create.blade.php
> +<div class="modal fade bd-example-modal-lg" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
Please use a valid name instead of exampleModal or exampleModalLabel

2022-09-14 04:19 UTC, pankaj-ag commented on Modules/Revenue/Routes/web.php
>  Route::prefix('revenue')->group(function () {
```suggestion
Route::prefix('revenue-proceeds')->group(function () {
```

2022-09-14 04:57 UTC, pankaj-ag commented on Modules/Revenue/Resources/views/edit.blade.php
> + <div class="modal fade text-left"  tabindex="-1" role="dialog" id="modalEdit" aria-hidden="true">
@Abhishek25081999 we need to fix this also

2022-09-14 07:10 UTC, pankaj-ag requested changes

2022-09-14 07:10 UTC, pankaj-ag commented on Modules/Revenue/Http/Controllers/RevenueProceedController.php
> +        return view('revenue::index')->with('revenues', $revenueData);
```suggestion
        return view('revenue::index')->with('revenueProcceds', $revenueData);
```

2022-09-14 07:10 UTC, pankaj-ag commented on Modules/Revenue/Resources/assets/js/app.js
> +	const revenue = $(revenueEdited).data("json");
```suggestion
	const revenueProceed = $(revenueEdited).data("json");
```

2022-09-14 07:10 UTC, pankaj-ag commented on Modules/Revenue/Resources/views/index.blade.php
> +            @foreach ($revenues as $revenue)
```suggestion
            @foreach ($revenueProceeds as $revenueProceed)
```

2022-09-14 08:05 UTC, pankaj-ag commented
- [ ] - Fix the notes issue
- [ ] - Fix form formatting
- [ ] - Added currency and Category as dropdown

2022-09-14 13:56 UTC, pankaj-ag approved these changes
Looks good to me.

2022-09-14 13:56 UTC, pankaj-ag commented on Modules/Revenue/Resources/assets/js/app.js
> +	console.log(revenueProceed.category);
Remove console logs

2022-09-14 14:02 UTC, merged