Feature/2155/interview duration
ColoredCow/portal pull request #2414
Opened 2022-09-12 12:09 UTC by LAKSHYA0501

Targets #2155 

### Description
1. Made changes in the finish interview button.
2. Ajax call error solved.
3. Fixing and Updation in UI.
4. Add local time in .env file and make changes in the time functionality.

### Checklist:
- [ ] I have performed a self-review of my own code.

2022-09-13 05:32 UTC, P4NK4J requested changes
Left some comments, please check

2022-09-13 05:32 UTC, P4NK4J commented on Modules/HR/Entities/ApplicationRound.php
> +                $time = $attr['scheduled_time'];
can we rename these variables to scheduledDate and scheduledTime

2022-09-13 05:32 UTC, P4NK4J commented on Modules/HR/Entities/ApplicationRound.php
> +        $TimeDiff = $ScheduleEnd->diffAsCarbonInterval($ScheduleDate);
Please put camelCase as a naming convention here

2022-09-13 05:32 UTC, P4NK4J commented on Modules/HR/Http/Controllers/Recruitment/ApplicationController.php
> -            $application->latestApplicationRound->scheduled_date = today()->toDateString();
Why you have removed this line ?

2022-09-13 05:32 UTC, P4NK4J commented on Modules/HR/Routes/web.php
> -            Route::get('/onHoldEmail', 'JobApplicationController@generateOnHoldEmail');
why you have removed this route ? please create your routes instead of removing other routes

2022-09-13 05:32 UTC, P4NK4J commented on Modules/HR/Services/ApplicationService.php
> +        $MeetDuration = Carbon::parse($MeetDate);
correct the variable naming convention, camelCase required here

2022-09-13 05:32 UTC, P4NK4J commented on resources/js/app.js
> +	var dID = $(".finish_interview").val();
what is dID ? can we have a better name ?

2022-09-13 05:32 UTC, P4NK4J commented on resources/js/app.js
> +		type: "GET",
why making GET request here ?

2022-09-13 05:32 UTC, P4NK4J commented on Modules/HR/Entities/ApplicationRound.php
> +        $MeetDuration = Carbon::createFromFormat('Y-m-d H:i:s', $this->actual_end_time);
Is actual end time being saved in the database? I didn't find any line of code written to save that, can you share any link or reference where it is ?

2022-09-13 05:35 UTC, LAKSHYA0501 commented on Modules/HR/Routes/web.php
> -            Route::get('/onHoldEmail', 'JobApplicationController@generateOnHoldEmail');
Sorry that got removed by mistake.

2022-09-13 05:35 UTC, LAKSHYA0501 commented on Modules/HR/Http/Controllers/Recruitment/ApplicationController.php
> -            $application->latestApplicationRound->scheduled_date = today()->toDateString();
this was prior done , not my changes.

2022-09-13 05:36 UTC, LAKSHYA0501 commented on Modules/HR/Services/ApplicationService.php
> +        $MeetDuration = Carbon::parse($MeetDate);
These were prior done by Shardul thats why i didn't changed them, still if needed ill do

2022-09-13 05:37 UTC, LAKSHYA0501 commented on resources/js/app.js
> +	var dID = $(".finish_interview").val();
These were prior done by Shardul thats why i didn't changed them.

2022-09-13 05:38 UTC, LAKSHYA0501 commented on resources/js/app.js
> +		type: "GET",
It was implemented by shardul, it was there when i took the pull.

2022-09-13 05:39 UTC, LAKSHYA0501 commented on Modules/HR/Entities/ApplicationRound.php
> +        $MeetDuration = Carbon::createFromFormat('Y-m-d H:i:s', $this->actual_end_time);
yes, after clicking on the finish interview button the time it is clicked gets  stored in db in column actual_end_time.

2022-09-13 05:42 UTC, LAKSHYA0501 commented on Modules/HR/Entities/ApplicationRound.php
> +                $time = $attr['scheduled_time'];
ok

2022-09-13 05:55 UTC, LAKSHYA0501 commented on Modules/HR/Entities/ApplicationRound.php
> +        $MeetDuration = Carbon::createFromFormat('Y-m-d H:i:s', $this->actual_end_time);
![image](https://user-images.githubusercontent.com/53862863/189820526-2f8c1150-136f-4ce9-b1fd-7fa9a29a6190.png)

2022-09-13 05:56 UTC, LAKSHYA0501 commented on Modules/HR/Routes/web.php
> -            Route::get('/onHoldEmail', 'JobApplicationController@generateOnHoldEmail');
i have added it back.

2022-09-13 05:59 UTC, LAKSHYA0501 commented on Modules/HR/Http/Controllers/Recruitment/ApplicationController.php
> -            $application->latestApplicationRound->scheduled_date = today()->toDateString();
ok , added it back

2022-09-13 06:16 UTC, LAKSHYA0501 commented on Modules/HR/Entities/ApplicationRound.php
> +        $TimeDiff = $ScheduleEnd->diffAsCarbonInterval($ScheduleDate);
done

2022-09-13 06:24 UTC, LAKSHYA0501 commented on resources/js/app.js
> +	var dID = $(".finish_interview").val();
in dID we are getting the actual_end_time , can you suggest any name?

2022-09-13 06:38 UTC, LAKSHYA0501 commented on resources/js/app.js
> +		type: "GET",
We have used  GET request as so that we can get in response in the json format status and time what we have passed  from the  ApplicationController

2022-09-13 06:57 UTC, LAKSHYA0501 commented on Modules/HR/Services/ApplicationService.php
> +        $MeetDuration = Carbon::parse($MeetDate);
done

2022-09-13 07:47 UTC, P4NK4J commented on resources/js/app.js
> +	var dID = $(".finish_interview").val();
make it actualEndTime then

2022-09-13 07:47 UTC, P4NK4J commented on resources/js/app.js
> +		type: "GET",
But why not POST request ?

2022-09-13 07:53 UTC, LAKSHYA0501 commented on resources/js/app.js
> +		type: "GET",
beacuse the POST method is not supported by the route

2022-09-13 07:53 UTC, LAKSHYA0501 commented on resources/js/app.js
> +	var dID = $(".finish_interview").val();
ok

2022-09-24 08:42 UTC, P4NK4J requested changes
Left some comments, please check

2022-09-24 08:42 UTC, P4NK4J commented on resources/views/hr/application/edit.blade.php
> +                                                @endif
Let's combine them in one conditional ?

2022-09-24 08:42 UTC, P4NK4J commented on resources/views/hr/application/edit.blade.php
> +                                                            <div class="form-group col-md-4">
can this be replaced with the separate blade file you have created, this seems to be repeatitive

2022-09-24 08:42 UTC, P4NK4J commented on resources/views/hr/application/edit.blade.php
> +                                                @endif
Here as well, let's combine the conditions

2022-09-24 08:42 UTC, P4NK4J commented on resources/views/hr/application/edit.blade.php
> +                                                                    <input type="Time" readonly="readonly"
can this code be replaced from the blade file created ?

2022-09-24 08:55 UTC, LAKSHYA0501 commented on resources/views/hr/application/edit.blade.php
> +                                                @endif
ok

2022-09-24 11:22 UTC, LAKSHYA0501 commented on resources/views/hr/application/edit.blade.php
> +                                                                @include('hr.application.meeting')
done

2022-09-24 11:22 UTC, LAKSHYA0501 commented on resources/views/hr/application/edit.blade.php
> +                                                            <div class="form-group col-md-4">
ok done

2022-09-24 11:22 UTC, LAKSHYA0501 commented on resources/views/hr/application/edit.blade.php
> +                                                                    <input type="Time" readonly="readonly"
done

2022-09-26 06:23 UTC, P4NK4J approved these changes
Looks good.

2022-09-26 06:24 UTC, merged