team members are updated according to their user name
ColoredCow/portal pull request #2435
Opened 2022-09-14 06:48 UTC by tarunnjoshi

Targets #2429

### Description
Team Members are updated according to their user names.

### Checklist:
- [ ] I have performed a self-review of my code.

2022-09-15 05:14 UTC, gautam071 commented
@GauravGusain98 Can you review this PR once

2022-09-17 11:29 UTC, GauravGusain98 requested changes
Please check the comment

2022-09-17 11:29 UTC, GauravGusain98 commented on Modules/EffortTracking/Services/EffortTrackingService.php
> +                $projectMembersCount++;
According to current logic the teamember will already have the value and this for loop will do an increment over that value. The initial value should be 0 of `projectMembersCount` at line 189. Then we will get the exact count.

2022-09-22 14:10 UTC, tarunnjoshi commented on Modules/EffortTracking/Services/EffortTrackingService.php
> +                $projectMembersCount++;
Done with the changes.

2022-10-07 12:24 UTC, merged