Feature/show the book data of an individual user
ColoredCow/portal pull request #2455
Opened 2022-09-15 07:39 UTC by amisha296

#2454 

I have made a page to show all the details of users, the books they read, wishlisted and borrowed.

I have performed a self-review of my own code.

2022-09-15 08:53 UTC, amisha296 commented
![Screenshot (111)](https://user-images.githubusercontent.com/90472056/190360437-e7358021-b70a-4185-b463-848138f17223.png)

2022-09-15 09:05 UTC, amisha296 commented
![Screenshot (112)](https://user-images.githubusercontent.com/90472056/190363190-47894a50-f88f-49a8-9453-f8dc54dd16a4.png)

2022-09-16 19:03 UTC, amisha296 commented on resources/views/knowledgecafe/library/books/index.blade.php
> +=======
okay

2022-09-26 09:36 UTC, gautam071 requested changes
left some comments

2022-09-26 09:36 UTC, gautam071 commented on resources/views/knowledgecafe/library/books/user-books-details.blade.php
> +    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorig
Use css from assets

2022-09-26 09:36 UTC, gautam071 commented on resources/views/knowledgecafe/library/books/user-books-details.blade.php
> +  <body style="background-color: rgba(177, 170, 129, 0.15); font-family: Muli, sans-serif;">
style to css

2022-09-26 09:36 UTC, gautam071 commented on resources/views/knowledgecafe/library/books/user-books-details.blade.php
> +    <!-- Bootstrap CSS -->
The head section already comes from  `@extends('layouts.app') @section('content')` from here

2022-09-26 09:37 UTC, gautam071 commented
@amisha296 please check the conflicts, also there are some changes with the `composer.lock` file please check that

2022-09-26 10:23 UTC, amisha296 commented
> @amisha296 please check the conflicts, also there are some changes with the `composer.lock` file please check that

Resolved the merge conflict, I am not getting any idea of composer.lock, I didn't make the changes in there!

2022-09-29 08:26 UTC, gautam071 requested changes

2022-09-29 08:26 UTC, gautam071 commented on app/Http/Controllers/UserBookController.php
> +        $books = (new BookServices)->getReaderDetails($user);
What does this do?

2022-09-29 08:26 UTC, gautam071 commented on resources/views/knowledgecafe/library/books/index.blade.php
> +                    <div  class="pl-0 pt-2 pb-3">
Indentations
```suggestion
                    <p class="mb-0 mt-1">Borrowed by</p>
                    <div class="pl-0 pt-2 pb-3">
```

2022-09-29 08:26 UTC, gautam071 commented on resources/views/knowledgecafe/library/books/index.blade.php
> -
Add line back

2022-09-29 08:26 UTC, gautam071 commented on resources/views/knowledgecafe/library/books/user-books-details.blade.php
> +                  <div class=" fs-1 my-3 mx-4 px-2"> User Details</div>
Make the heading according as discussed!

2022-09-29 08:26 UTC, gautam071 commented on resources/views/knowledgecafe/library/books/user-books-details.blade.php
> +                              <h4 class="card-header" style="color: #1B65D5">Wishlisted Books({{$books['wishlistBookCount']}})</h4>
Use CSS!

2022-09-29 08:26 UTC, gautam071 commented on resources/views/knowledgecafe/library/books/user-books-details.blade.php
> +                              <h4 class="card-header" style="color: #0A6B51">Read Books({{$books['readBookCount']}})</h4>
Use CSS

2022-09-29 08:26 UTC, gautam071 commented on resources/views/knowledgecafe/library/books/user-books-details.blade.php
> +                              <h4 class="card-header"  style="color: #E32315">Borrowed Books({{$books['borrowedBookCount']}})</h4>
Use CSS

2022-10-03 08:25 UTC, amisha296 commented on app/Http/Controllers/UserBookController.php
> +        $books = (new BookServices)->getReaderDetails($user);
It calls the getReaderDetails function from the service file.

2022-10-03 08:52 UTC, amisha296 commented on resources/views/knowledgecafe/library/books/user-books-details.blade.php
> +                              <h4 class="card-header"  style="color: #E32315">Borrowed Books({{$books['borrowedBookCount']}})</h4>
Did you mean classes?

2022-10-04 17:51 UTC, gautam071 commented
@amisha296 Can you check the requested changes

2022-10-05 07:20 UTC, amisha296 commented
> @amisha296 Can you check the requested changes

@gautam071 where to make the changes?

2022-10-05 07:40 UTC, amisha296 commented
> @amisha296 Can you check the requested changes

@gautam071 What changes?

2023-05-08 11:30 UTC, closed without merging