add role by a new button in role section
ColoredCow/portal pull request #2459
Opened 2022-09-15 08:27 UTC by saurabhpatel123456

Targets #2423 
add role by a new button in role section.

### Description
 you have to add new role button in role section. whenever anybody hit that button then it should be open a form and that form requires all input column of database roles and after filling that data of form it will save in roles column as well as in database table.

### Checklist:

- [ ] I have performed a self-review of my own code.

2022-09-28 06:41 UTC, gautam071 requested changes

2022-09-28 06:41 UTC, gautam071 commented on Modules/User/Http/Controllers/UserController.php
> +        return redirect()->back();
use service and request files

2022-09-28 06:41 UTC, gautam071 commented on Modules/User/Resources/assets/js/components/RoleListing.vue
>  		}
why this is needed?

2022-09-28 06:41 UTC, gautam071 commented on Modules/User/Resources/assets/js/components/RoleListing.vue
> +			// rolelocal: this.roles,
remove the comment code

2022-09-28 06:41 UTC, gautam071 commented on Modules/User/Resources/assets/js/components/RoleListing.vue
> +						<button v-if="role.id != '1'" v-on:click="removeRole(index)" class="btn btn-danger" id="disablebtn">Delete</button>
use by `guard_name`

2022-09-28 06:41 UTC, gautam071 commented on Modules/User/Resources/assets/js/components/RoleListing.vue
> +					<th>Correction</th>
What is this?

2022-09-28 06:41 UTC, gautam071 commented on Modules/User/Resources/views/roles/index.blade.php
> +        <strong>Updated!</strong> Submitted successfully.
```suggestion
        <strong>Updated!</strong> the Role successfully.
```

2022-09-28 06:41 UTC, gautam071 commented on Modules/User/Resources/views/roles/index.blade.php
> +	ADD NEW ROLE
```suggestion
	Add New Role 
```

2022-09-28 06:41 UTC, gautam071 commented on Modules/User/Resources/views/roles/index.blade.php
> +	<h4>Roles management </h4>
check the formatting in the bklade file

2022-09-28 06:41 UTC, gautam071 commented on Modules/User/Resources/views/roles/index.blade.php
> +					<h5 class="modal-title" id="rolesModalLabel">ADD NEW ROLE</h5>
Same here

2022-09-28 06:41 UTC, gautam071 commented on Modules/User/Routes/web.php
> +    Route::get('/showForm', 'UserController@showForm')->name('user.show-form');
why a route for modal?

2022-09-28 06:41 UTC, gautam071 commented on database/Seeders/RolesTableSeeder.php
> +            ],
```suggestion
            ]
```

2022-09-28 06:41 UTC, gautam071 commented on resources/js/app.js
> +		});
What is the purpose of JQuery

2022-09-28 07:42 UTC, saurabhpatel123456 commented on Modules/User/Resources/assets/js/components/RoleListing.vue
>  		}
for deleting the roles.

2022-09-28 07:42 UTC, saurabhpatel123456 commented on Modules/User/Resources/assets/js/components/RoleListing.vue
> +			// rolelocal: this.roles,
ok

2022-09-28 07:51 UTC, saurabhpatel123456 commented on resources/js/app.js
> +		});
it is used for checking  the similar data in database and then give a message to the user.

2022-09-28 07:58 UTC, saurabhpatel123456 commented on Modules/User/Resources/assets/js/components/RoleListing.vue
> +						<button v-if="role.id != '1'" v-on:click="removeRole(index)" class="btn btn-danger" id="disablebtn">Delete</button>
ok

2022-09-28 08:10 UTC, saurabhpatel123456 commented on Modules/User/Resources/assets/js/components/RoleListing.vue
> +					<th>Correction</th>
i renamed.

2022-09-28 08:14 UTC, saurabhpatel123456 commented on Modules/User/Routes/web.php
> +    Route::get('/showForm', 'UserController@showForm')->name('user.show-form');
sorry i forgot to remove this route, i made for the form.

2022-09-29 12:06 UTC, saurabhpatel123456 commented on Modules/User/Resources/assets/js/components/RoleListing.vue
> +					<th>Correction</th>
that is the title of delete button but now i have changed the name.

2023-05-08 11:32 UTC, closed without merging