Start capturing the average usd rates for a month.
ColoredCow/portal pull request #2474
Opened 2022-09-16 12:14 UTC by Himanshunegi0332

Targets #2380 

### Description
Start capturing the average usd rates for a month in database for future refernce.

### Checklist:
- [X] I have performed a self-review of my own code.

2022-09-17 17:02 UTC, pankaj-ag requested changes

2022-09-17 17:02 UTC, pankaj-ag commented on Modules/Invoice/Services/InvoiceService.php
> +        ]);
```suggestion
       
```
@Himanshunegi0332 I think there is some confusion. 

We can't add this code here.
We need to do that via cron or some API calls.

For now, let's create a table only and we can fill it from the backend.

2022-09-18 06:34 UTC, Himanshunegi0332 commented on Modules/Invoice/Entities/CurrencyAvgRates.php
> +class CurrencyAvgRates extends Model
Ok sir

2022-09-18 06:35 UTC, Himanshunegi0332 commented on Modules/Invoice/Entities/CurrencyAvgRates.php
> +    protected $fillable = ['currency', 'captured_for', 'avg_rate', 'created_at', 'updated_at'];
Ok sor

2022-09-18 06:51 UTC, Himanshunegi0332 commented on Modules/Invoice/Services/InvoiceService.php
> +        ]);
Ok for now I have created the table and model.

2022-09-19 06:54 UTC, pankaj-ag approved these changes

2022-09-19 06:55 UTC, merged