Functionality added to trigger mail to KeyAccountManager if fixed budget project isn't having an end date.
ColoredCow/portal pull request #2482
Opened 2022-09-19 06:19 UTC by Anshgupta456

Targets #{2315}

### Description
If any fixed budget project does not have any end date, then a mail will send to Key Account Manager of the Project.

### Checklist:

- [x] I have performed a self-review of my own code.

2022-09-19 07:10 UTC, Ayush8923 commented
@Anshgupta456 Please fix CI checks then assign reviewers for review.

2022-09-19 07:11 UTC, Ayush8923 reviewed
@Anshgupta456 Please fix CI checks then assign reviewers for review.

2022-09-23 09:36 UTC, Ayush8923 requested changes
Please check the comment.

2022-09-23 09:36 UTC, Ayush8923 commented on Modules/Project/Emails/SendMailForNotHavingProjectEndDate.php
> +        ->from('anshikagupta45612@gmail.com')
You have to get an email from the env file here.

2022-09-23 09:36 UTC, Ayush8923 commented on Modules/Project/Emails/SendMailForNotHavingProjectEndDate.php
> +        ->view('project::mail.not-having-end-date')
```suggestion
        ->view('project::mail.not-having-project-end-date')
```

2022-09-23 09:36 UTC, Ayush8923 commented on Modules/Project/Resources/views/mail/not-having-end-date.blade.php
> +	<style>
Why are you using inline CSS here? We don't need to write inline CSS here

2022-09-23 09:36 UTC, Ayush8923 commented on Modules/Project/Console/MailToAccountManagerForNotHavingEndDate.php
> +    protected $name = 'project:send-daily-mail-for-not-having-project-end-date';
```suggestion
    protected $name = 'project:send-mail-for-not-having-project-end-date';
```

2022-09-23 09:36 UTC, Ayush8923 commented on Modules/Project/Console/MailToAccountManagerForNotHavingEndDate.php
> +    protected $description = 'Sends a mail to key account manager that fixed budget project is not having an end date';
```suggestion
    protected $description = 'Send mail to key account manager that fixed budget project is not having project end date';
```

2022-09-23 09:36 UTC, Ayush8923 commented on app/Console/Kernel.php
> +        MailToAccountManagerForNotHavingEndDate::class,
```suggestion
        MailToKeyAccountManagerForNotHavingProjectEndDate::class,
```

2022-09-23 09:36 UTC, Ayush8923 commented on app/Console/Kernel.php
> +use Modules\Project\Console\MailToAccountManagerForNotHavingEndDate;
```suggestion
use Modules\Project\Console\MailToKeyAccountManagerForNotHavingProjectEndDate;
```

2022-09-23 09:36 UTC, Ayush8923 commented on Modules/Project/Console/MailToAccountManagerForNotHavingEndDate.php
> +class MailToAccountManagerForNotHavingEndDate extends Command
```suggestion
class MailToKeyAccountManagerForNotHavingProjectEndDate extends Command
```

2022-09-23 09:40 UTC, Anshgupta456 commented on Modules/Project/Emails/SendMailForNotHavingProjectEndDate.php
> +        ->from('anshikagupta45612@gmail.com')
Sir, I have added the same email ID in .env file

2022-09-23 09:52 UTC, Ayush8923 commented on Modules/Project/Emails/SendMailForNotHavingProjectEndDate.php
> +        ->from('anshikagupta45612@gmail.com')
No. Please check other email files to see how email is used there.

2022-09-23 09:52 UTC, Anshgupta456 commented on Modules/Project/Resources/views/mail/not-having-end-date.blade.php
> +	<style>
Please suggest me, what can I do for it?

2022-09-23 14:29 UTC, Ayush8923 commented on Modules/Project/Resources/views/mail/not-having-end-date.blade.php
> +	<style>
Please use bootstrap classes.
Refrence link:- https://getbootstrap.com/docs/5.0/utilities/text/#line-height

2022-09-25 15:33 UTC, Ayush8923 commented
@Anshgupta456 please update mail template, I am sharing mail template.

```
Hi, KeyAccountManager

There are some fixed-budget projects which are not having any project end-date where you are assigned as a key account manager, please update these projects:

  	Project Name

1.	MegaFitMeals  (Link)
2.	PMG (Link)

Thanks,
Portal Team
ColoredCow

```

2022-09-26 11:11 UTC, Ayush8923 requested changes
Please check the comments

2022-09-26 11:11 UTC, Ayush8923 commented on Modules/Project/Console/MailToKeyAccountManagerForNotHavingEndDate.php
> +class MailToKeyAccountManagerForNotHavingEndDate extends Command
```suggestion
class MailToKeyAccountManagerForNotHavingProjectEndDate extends Command
```

2022-09-26 11:11 UTC, Ayush8923 commented on app/Console/Kernel.php
> +use Modules\Project\Console\MailToKeyAccountManagerForNotHavingEndDate;
```suggestion
use Modules\Project\Console\MailToKeyAccountManagerForNotHavingProjectEndDate;
```

2022-09-26 11:11 UTC, Ayush8923 commented on app/Console/Kernel.php
> +        MailToKeyAccountManagerForNotHavingEndDate::class,
```suggestion
        MailToKeyAccountManagerForNotHavingProjectEndDate::class,
```

2022-09-27 15:17 UTC, Ayush8923 requested changes
@Anshgupta456 Please check the comment

2022-09-27 15:17 UTC, Ayush8923 commented on Modules/Project/Console/MailToKeyAccountManagerForNotHavingEndDate.php
> +            if ($project->end_date == null) {
```suggestion
            if ($project->end_date === null) {
```

2022-09-27 15:17 UTC, Ayush8923 commented on Modules/Project/Emails/SendMailForNotHavingProjectEndDate.php
> +        ->subject('ColoredCow Portal - Fixed Budget Project is not having an end date')
```suggestion
        ->subject('Fixed Budget Project is not having project end date')
```

2022-09-27 15:21 UTC, P4NK4J requested changes
@Ayush8923 @Anshgupta456 Left some comments here, please check.

2022-09-27 15:21 UTC, P4NK4J commented on Modules/Project/Console/MailToKeyAccountManagerForNotHavingEndDate.php
> +            if ($project->end_date == null) {
Instead of fetching all projects and looping for end date, can we fetch projects only where end date is null ?

2022-09-27 15:21 UTC, P4NK4J commented on Modules/Project/Emails/SendMailForNotHavingProjectEndDate.php
> +        ->from(config('constants.hr.default.email'), config('constants.hr.default.name'))
Why HR default email is used here ? Its related to project module, can we use system email here ?

2022-09-28 05:58 UTC, Anshgupta456 commented on Modules/Project/Emails/SendMailForNotHavingProjectEndDate.php
> +        ->from(config('constants.hr.default.email'), config('constants.hr.default.name'))
@P4NK4J With hr.default.email we are using portal@coloredcow.in ID, should we change it to another specific ID?

2022-09-28 05:59 UTC, Anshgupta456 commented on Modules/Project/Emails/SendMailForNotHavingProjectEndDate.php
> +        ->from(config('constants.hr.default.email'), config('constants.hr.default.name'))
@P4NK4J And may you please specify something about system email?

2022-09-28 06:06 UTC, P4NK4J commented on Modules/Project/Emails/SendMailForNotHavingProjectEndDate.php
> +        ->from(config('constants.hr.default.email'), config('constants.hr.default.name'))
@Anshgupta456 HR_DEFAULT_EMAIL in ENV file is `careers@coloredcow.com`. The `portal@coloredcow.com` you have seen is the fallback email address if ENV variable is empty. Let's use `MAIL_FROM_ADDRESS` variable this corresponds to `contact@coloredcow.com` in the production. Let me know if you have any questions.

2022-09-28 10:42 UTC, Anshgupta456 commented on Modules/Project/Emails/SendMailForNotHavingProjectEndDate.php
> +        ->from(config('constants.hr.default.email'), config('constants.hr.default.name'))
@P4NK4J okay, let me try this first and then I will ask if I have any questions.

2023-04-07 12:26 UTC, closed without merging