2443 sort universities by most application received
ColoredCow/portal pull request #2483
Opened 2022-09-19 06:19 UTC by brajesh-lab

Targets #{2443}

### Description
Order of university by most application received

### Checklist:
- [ ] I have performed a self-review of my own code.

2022-09-19 07:29 UTC, P4NK4J requested changes
Left some comments, please check

2022-09-19 07:29 UTC, P4NK4J commented on resources/views/hr/application/edit.blade.php
> +                                    @endif
Why we need these changes ?

2022-09-19 07:29 UTC, P4NK4J commented on Modules/HR/Resources/views/universities/index.blade.php
>                  <td>
Indentation is off, please change at other places as well.

2022-09-19 07:29 UTC, P4NK4J commented on Modules/HR/Resources/views/universities/index.blade.php
> +
Why making it into a loop, can't we make a relationship to fetch universities corresponding to applications ? We do have a mapping of university with hr_applicant and application mapping with application

2022-09-19 07:29 UTC, P4NK4J commented on Modules/HR/Http/Controllers/Universities/UniversityController.php
> +        ->get();
Can we fetch universities directly based on whereHas mapping here ?

2022-09-20 13:13 UTC, brajesh-lab commented on Modules/HR/Http/Controllers/Universities/UniversityController.php
> +        ->get();
when i have studied  about whereHas mapping ,I  have seen that the performance of  laravel eloquent is slower than Query Builder

2022-09-21 05:52 UTC, brajesh-lab commented on resources/views/hr/application/edit.blade.php
> +                                    @endif
There is no need to change  in this file . It's  attached  from privious  issue

2022-09-21 05:54 UTC, brajesh-lab commented on Modules/HR/Resources/views/universities/index.blade.php
> +
I have  solved

2022-09-21 06:26 UTC, P4NK4J requested changes
Responded to the comments

2022-09-21 06:26 UTC, P4NK4J commented on resources/views/hr/application/edit.blade.php
> +                                    @endif
Let's remove these changes, it would stop showing the followup button then

2022-09-21 10:42 UTC, P4NK4J approved these changes
Looks good.

2022-09-21 10:42 UTC, merged