all the fields visible on user profile
ColoredCow/portal pull request #2503
Opened 2022-09-20 10:15 UTC by ditya0504

Targets #2478 

### Description
 All the fields are visible on the user profile and all fields are available in the edit profile.

### Checklist:

- [ ] I have performed a self-review of my own code.

2022-09-21 05:27 UTC, P4NK4J requested changes
Left some comments, for enhancements, please check

2022-09-21 05:27 UTC, P4NK4J commented on Modules/User/Resources/views/profile/subviews/show-user-profile-info.blade.php
> +<!-- <div class="form-group">
why these code lines are commented out ?

2022-09-21 05:27 UTC, P4NK4J commented on Modules/User/Resources/views/profile/show-basic-details.blade.php
> +                </div>
Let's put spouse name here, and rename the database column as well. Also, Spouse name should appear if marital status `married`

2022-09-21 06:56 UTC, ditya0504 commented on Modules/User/Resources/views/profile/subviews/show-user-profile-info.blade.php
> +<!-- <div class="form-group">
designations field was showing multiple times so commented extra code.

2022-09-21 12:35 UTC, P4NK4J requested changes
Minor comment, else looks good.

2022-09-21 12:35 UTC, P4NK4J commented on Modules/User/Resources/views/profile/show-basic-details.blade.php
> +                </div>
Let's make the marital status as checkbox having options married, unmarried, or divorced. If user selects, married, then Spouse name should appear, else it should not appear on the UI

2022-09-26 11:09 UTC, P4NK4J requested changes
Its giving an error while accessing the profile, can we put a null check here ?
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/35001775/192261858-885f6823-65bd-47d5-8b01-b8e6f06e6bbe.png">

2022-10-12 07:53 UTC, P4NK4J requested changes
Fix indentation in blade file at all places, as per suggested. Also take a latest pull from master

2022-10-12 07:53 UTC, P4NK4J commented on Modules/User/Resources/views/profile/subviews/show-user-profile-info.blade.php
> +</div> -->
why commented this code ?

2022-10-12 07:53 UTC, P4NK4J commented on Modules/User/Resources/views/profile/show-basic-details.blade.php
> +                              <option {{$domain['id'] == $user->employee->domain_id ? "selected" : ""}} value="{{ $domain['id'] }}">{{$domain['domain']}}</option>
```suggestion
                                  <option {{$domain['id'] == $user->employee->domain_id ? "selected" : ""}} value="{{ $domain['id'] }}">{{$domain['domain']}}</option>
```

2022-10-12 08:15 UTC, ditya0504 commented on Modules/User/Resources/views/profile/subviews/show-user-profile-info.blade.php
> +</div> -->
designations field was showing multiple times so commented extra code.

2022-10-12 08:43 UTC, P4NK4J requested changes
left some comments

2022-10-12 08:43 UTC, P4NK4J commented on Modules/User/Resources/views/profile/show-basic-details.blade.php
> +                      @endif
Can we simply put condition on the form field to populate in HTML? rather than doing d-none  ? also the conditions seems very repetitive, it can simply go inside @else, nothing further action should be required, infact else condition is also not required, just put if(married or something), then show HTML

2022-10-12 08:43 UTC, P4NK4J commented on Modules/User/Resources/views/profile/show-basic-details.blade.php
> +                  <span>{{ $user->employee->domain_id == $domain['id'] ? $domain['domain'] : "" }}</span>
Indentation

2022-10-12 11:56 UTC, P4NK4J approved these changes
Looks good.

2022-10-12 11:56 UTC, merged