Feature/2049 flagging applications
ColoredCow/portal pull request #2515
Opened 2022-09-21 17:21 UTC by LAKSHYA0501

Targets #2049 

### Description
1. created the flag which will open a modal to get resume response data.
2. made a new column in hr_applications table which turns 0=> 1 on submission of data
3. created a new view with tables of the resumes with resume-flag value and is_desired_resume =1 

### Checklist:

- [x] I have performed a self-review of my own code.

2022-09-24 08:44 UTC, P4NK4J requested changes
The desired resume page should have title saying `Desired Resume for JOB_ROLE`. Also, the success message right now, is very faded and not catching attention on the UI, can we make it like project edit message ?
<img width="1216" alt="image" src="https://user-images.githubusercontent.com/35001775/192089099-a9ddbd9f-a748-45ef-95af-acd879649990.png">

2022-09-24 10:10 UTC, LAKSHYA0501 commented
@P4NK4J done with the changes

2022-09-24 10:20 UTC, LAKSHYA0501 commented
Changed the table title with job roles:
![image](https://user-images.githubusercontent.com/53862863/192092725-3ee80a77-3557-4335-964f-89d8b732bc27.png)

Toast message added:
![image](https://user-images.githubusercontent.com/53862863/192092739-d511e797-2402-4967-bf8b-648833ae9061.png)

2022-09-26 06:21 UTC, P4NK4J requested changes
Left some comments, else looks good.

2022-09-26 06:21 UTC, P4NK4J commented on Modules/HR/Http/Controllers/Recruitment/ApplicationController.php
> +        $resumeData = DB::table('hr_applications')->select(['hr_applications.resume'])->where('hr_applications.hr_job_id', '=', $job->id)->where('is_desired_resume', '=', 1)->get();
can we rename it to desiredResume ?

2022-09-26 06:21 UTC, P4NK4J commented on Modules/HR/Http/Controllers/Recruitment/JobController.php
> +            ->where('hr_application_meta.key', '=', 'resume-flag')
can we rename the meta key to `reasons_for_desired_resume` ?

2022-09-26 06:21 UTC, P4NK4J commented on resources/views/hr/application/edit.blade.php
> +                                                                            target="_blank">sample desired resume
```suggestion
                                                                            target="_blank">Sample Desired Resume
```

2022-09-26 06:21 UTC, P4NK4J commented on resources/views/hr/application/edit.blade.php
> +
Let's put this in a separate modal file and include it here

2022-09-26 06:37 UTC, LAKSHYA0501 commented on Modules/HR/Http/Controllers/Recruitment/ApplicationController.php
> +        $resumeData = DB::table('hr_applications')->select(['hr_applications.resume'])->where('hr_applications.hr_job_id', '=', $job->id)->where('is_desired_resume', '=', 1)->get();
Done

2022-09-26 06:38 UTC, LAKSHYA0501 commented on Modules/HR/Http/Controllers/Recruitment/JobController.php
> +            ->where('hr_application_meta.key', '=', 'resume-flag')
doen

2022-09-26 07:30 UTC, LAKSHYA0501 commented on resources/views/hr/application/edit.blade.php
> +                                                                            target="_blank">sample desired resume
done

2022-09-26 07:31 UTC, LAKSHYA0501 commented on resources/views/hr/application/edit.blade.php
> +
done

2022-09-26 09:20 UTC, P4NK4J requested changes
Left some comments, please check

2022-09-26 09:20 UTC, P4NK4J commented on resources/views/hr/application/resume-table.blade.php
> +            @endforeach
What is datas, can you pass applicationData from controller and each single item can be named as $data here ?

2022-09-26 09:20 UTC, P4NK4J commented on resources/views/hr/application/desired-resume.blade.php
> +                    <div class="fomodal-body">
What is fomodal-body ? can this classname be more specific ?

2022-09-26 09:21 UTC, LAKSHYA0501 commented on resources/views/hr/application/resume-table.blade.php
> +            @endforeach
ok

2022-09-26 10:07 UTC, P4NK4J approved these changes
Looks good.

2022-09-26 10:07 UTC, merged