Calc fte noamc
ColoredCow/portal pull request #2522
Opened 2022-09-22 10:11 UTC by dhruvshrinet1

Targets #{2521}
Issue: https://github.com/ColoredCow/portal/issues/2521

Calculating the fte of user/employee for only those projects which have not AMC

- [ ] I have performed a self-review of my own code.

2022-09-22 10:49 UTC, pankaj-ag requested changes

2022-09-22 10:49 UTC, pankaj-ag commented on Modules/User/Entities/User.php
> +        foreach ($this->projectTeamMembers as $projectTeamMembers) {
```suggestion
        foreach ($this->projectTeamMembers()->with('project')->get() as $projectTeamMembers) {
```

2022-09-22 11:11 UTC, gautam071 reviewed
Looks good one suggestion

2022-09-22 11:11 UTC, gautam071 commented on Modules/User/Entities/User.php
> -
Add the space back

2022-09-24 07:53 UTC, pankaj-ag requested changes

2022-09-24 07:53 UTC, pankaj-ag commented on Modules/User/Entities/User.php
> +        foreach ($this->projectTeamMembers()->with('project')->get() as $projectTeamMembers) {
```suggestion
        foreach ($this->projectTeamMembers()->with('project')->get() as $projectTeamMember) {
```

2022-09-24 07:53 UTC, pankaj-ag commented on Modules/User/Entities/User.php
> +    public function getamcProjectsFteAttribute()
```suggestion
    public function getAmcProjectsFteAttribute()
```

2022-09-24 07:53 UTC, pankaj-ag commented on Modules/User/Entities/User.php
> +    }
Since we are running a loop twice I think let's create a single function that gave a fet of both types of projects in one go. 

with name getFtesAttribute which will return [ 'main' => 10, 'amc' => 2 ] kind of thing.

2022-09-24 07:53 UTC, pankaj-ag commented on resources/views/hr/employees/show.blade.php
> +            <div class="font-weight-bold fz-24 pl-5 mt-5 mb-3 d-flex justify-content-inline">{{__('Current FTE: ')}}<div class=" ml-1 {{ $employee->user ? ($employee->user->MainProjectsFte > 1 ? 'tex
Let's move this function in a single if block with the employer check. We don't need to repeat the full code again.

2022-09-24 19:46 UTC, dhruvshrinet1 commented on Modules/User/Entities/User.php
> +    }
Updated as per the feedback

2022-09-26 02:32 UTC, pankaj-ag approved these changes

2022-09-26 02:33 UTC, merged