make new module project contract
ColoredCow/portal pull request #2524
Opened 2022-09-22 12:22 UTC by tarunnjoshi

Targets #2252

### Description
Make new module Project Contract

### Checklist:

- [ ] I have performed a self-review of my own code.

2022-09-26 07:08 UTC, gautam071 requested changes
left some feedbacks

2022-09-26 07:08 UTC, gautam071 commented on Modules/ProjectContract/Services/ProjectContractService.php
> +        $ProjectContractMeta->save();
Use services!

2022-09-26 07:08 UTC, gautam071 commented on Modules/ProjectContract/Services/ProjectContractService.php
> +        return $ProjectContractMeta;
here as well

2022-09-26 07:21 UTC, tarunnjoshi commented on Modules/ProjectContract/Services/ProjectContractService.php
> +        return $ProjectContractMeta;
It is already correct .

2022-09-26 16:54 UTC, gautam071 requested changes
Left some comments

2022-09-26 16:54 UTC, gautam071 commented on Modules/ProjectContract/Resources/views/add-new-client.blade.php
> +    <span class=""><h1>Add New Contract</h1></span>
why span and h1 both?

2022-09-26 16:54 UTC, gautam071 commented on Modules/ProjectContract/Resources/views/add-new-client.blade.php
> +</div><br>
```suggestion
</div>
<br>
```

2022-09-26 16:54 UTC, gautam071 commented on Modules/ProjectContract/Resources/views/add-new-client.blade.php
> +                            <span data-toggle="tooltip" data-placement="right" title="Address, Summary, Authority Phone Number, Authority Email, Authority Designation." class="ml-2">
```suggestion
                            <span data-toggle="tooltip" data-placement="right" title="You can details like Address, Summary, Authority Phone Number, Authority Email, Authority Designation." class="ml-2">
```

2022-09-26 16:54 UTC, gautam071 commented on Modules/ProjectContract/Resources/views/edit-project-contract.blade.php
> +</div><br>
same

2022-09-26 16:54 UTC, gautam071 commented on Modules/ProjectContract/Resources/views/index.blade.php
> +</div><br>
```suggestion
</div>
<br>
```

2022-09-26 16:54 UTC, gautam071 commented on Modules/ProjectContract/Resources/views/index.blade.php
> +                    <a href="{{route('projectcontract.delete', $project->id)}}" class="pl-1 btn btn-link" ><i class="text-danger fa fa-trash fa-lg"></i></a>
Format

2022-09-27 05:12 UTC, tarunnjoshi commented on Modules/ProjectContract/Resources/views/index.blade.php
> +                    <a href="{{route('projectcontract.delete', $project->id)}}" class="pl-1 btn btn-link" ><i class="text-danger fa fa-trash fa-lg"></i></a>
Done with the changes.

2022-09-27 05:33 UTC, gautam071 reviewed
Looks good minor changes

2022-09-27 05:33 UTC, gautam071 commented on Modules/ProjectContract/Resources/views/add-new-client.blade.php
> +                            <span data-toggle="tooltip" data-placement="right" title="You can details like Address, Summary, Authority Phone Number, Authority Email, Authority Designation." class="ml
```suggestion
                            <span data-toggle="tooltip" data-placement="right" title="You can add details like Address, Summary, Authority Phone Number, Authority Email, Authority Designation." class="ml-2">
```

2022-09-27 05:33 UTC, gautam071 commented on Modules/ProjectContract/Resources/views/add-new-client.blade.php
> +                            <span data-toggle="tooltip" data-placement="right" title="You can details like Address, Summary, Authority Phone Number, Authority Email, Authority Designation." class="ml
same in edit as well

2022-09-27 05:33 UTC, gautam071 commented on Modules/ProjectContract/Services/ProjectContractService.php
> +        return ProjectContractMeta::with('client')->orderBy('updated_at', 'desc')->get();
```suggestion
        return ProjectContractMeta::with('client')->orderBy('created_at', 'desc')->get();
```

2022-09-27 05:41 UTC, tarunnjoshi commented on Modules/ProjectContract/Services/ProjectContractService.php
> +        return ProjectContractMeta::with('client')->orderBy('updated_at', 'desc')->get();
Done with the changes

2022-09-27 10:46 UTC, gautam071 approved these changes
Looks good!

2022-09-27 10:46 UTC, merged