CurrencyAvgRate table data to calculate p&l amount
ColoredCow/portal pull request #2527
Opened 2022-09-23 06:28 UTC by Himanshunegi0332

Targets #2487 

### Description
Created a CurrencyAvgRate table data to calculate p&l amount If there is no entry for that month then we can use the current rates by default.

### Checklist:
- [X] I have performed a self-review of my own code.

2022-09-23 07:25 UTC, pankaj-ag requested changes

2022-09-23 07:25 UTC, pankaj-ag commented on Modules/Report/Services/Finance/RevenueReportService.php
> +        }
We don't need this loop or something. 

We just need a value where 
captured_for month is the same as invoice->sent->date month, 
currency  = invoice->currency

2022-09-24 06:09 UTC, Himanshunegi0332 commented on Modules/Report/Services/Finance/RevenueReportService.php
> +        }
> We don't need this loop or something.
> 
> We just need a value where captured_for month is the same as invoice->sent->date month, currency = invoice->currency

Can you explain it little bit.

2022-09-24 08:44 UTC, pankaj-ag requested changes

2022-09-24 08:44 UTC, pankaj-ag commented on Modules/Report/Services/Finance/RevenueReportService.php
> -        return $this->getAmountsForRevenueProceeds(Str::snake($particular['name']), $startDate, $endDate);
@Himanshunegi0332 why w reverted those changes ?

2022-09-24 08:44 UTC, pankaj-ag commented on Modules/Report/Services/Finance/RevenueReportService.php
>      }
Why we removed this code? Please add it back.

2022-09-24 08:44 UTC, pankaj-ag commented on Modules/Report/Services/Finance/RevenueReportService.php
> +            foreach ($exchangeRates as $exchangeRate) {
Let's not run this loop again and again for each invoice. 
Let's take this loop outside of the top for loop and store the values in a variable like currency_chages [
'01-22' => 74,
'02-22' => 0,
 
]

and then use that variable.

2022-09-24 10:52 UTC, pankaj-ag requested changes

2022-09-24 10:52 UTC, pankaj-ag commented on Modules/Report/Services/Finance/RevenueReportService.php
> +                $exchangeDollor = $exchangeRate['avg_rate'];
I think this should be like this right ?

```suggestion
            if (isset($currency_chages[$dateKey])) {
                $exchangeDollor = $currency_chages[$dateKey];
```

2022-09-24 10:52 UTC, pankaj-ag commented on Modules/Report/Services/Finance/RevenueReportService.php
> +                $exchangeDollor = $exchangeRate['avg_rate'];
Please test by checking if the invoice amount is calculating based on the other the currency value. 

Like if a April invoice amount is 100
and April avg rate is 70 

Then the invoice value will be 7000

2022-09-24 10:52 UTC, pankaj-ag commented on Modules/Report/Services/Finance/RevenueReportService.php
> +        }
Very good now let's move this to new function with name like getAvgCurrencyRates()

2022-09-24 11:13 UTC, Himanshunegi0332 commented on Modules/Report/Services/Finance/RevenueReportService.php
> +                $exchangeDollor = $exchangeRate['avg_rate'];
$exchangeDollor = $currency_chages[$dateKey];     by doing this we will get only the month and year not the avg_rate

2022-09-25 15:11 UTC, Himanshunegi0332 commented on Modules/Report/Services/Finance/RevenueReportService.php
> +        }
ok done.

2022-09-26 02:46 UTC, pankaj-ag requested changes

2022-09-26 02:46 UTC, pankaj-ag commented on Modules/Report/Services/Finance/RevenueReportService.php
> +        $invoices = $this->invoiceService->getInvoicesBetweenDates($startDate, $endDate, 'non-indian');
```suggestion
        $invoices = $this->invoiceService->getInvoicesBetweenDates($startDate, $endDate, 'indian');
```

2022-09-26 02:46 UTC, pankaj-ag commented on Modules/Report/Services/Finance/RevenueReportService.php
> +                $exchangeDollor = $this->getAvgCurrencyRates();
@Himanshunegi0332 please try to understand the code first and then write :).

2022-09-26 02:46 UTC, pankaj-ag commented on Modules/Report/Services/Finance/RevenueReportService.php
> +    public function getAvgCurrencyRates()
OKay now let's send the startDate and endDate in this function and get the currency average between those dates only.

2022-09-26 02:46 UTC, pankaj-ag commented on Modules/Report/Services/Finance/RevenueReportService.php
> +        $exchangeRates = CurrencyAvgRate::select('captured_for')->groupBy('captured_for')->get()->toArray();
```suggestion
        $exchangeRates = $this->getAvgCurrencyRates($startDate, $endDate);
```

2022-09-26 02:46 UTC, pankaj-ag commented on Modules/Report/Services/Finance/RevenueReportService.php
> +        }
```suggestion
       
```

2022-09-26 02:46 UTC, pankaj-ag commented on Modules/Report/Services/Finance/RevenueReportService.php
> +            if ($exchangeMonth == $dateKey) {
```suggestion
            if (isset($exchangeRates[$dateKey])) { 
```

2022-09-26 02:46 UTC, pankaj-ag commented on Modules/Report/Services/Finance/RevenueReportService.php
> +                $exchangeDollor = $this->getAvgCurrencyRates();
```suggestion
                $exchangeDollor = $exchangeRates[$dateKey];
```

2022-09-26 02:48 UTC, pankaj-ag commented on Modules/Report/Services/Finance/RevenueReportService.php
> +                $exchangeDollor = $exchangeRate['avg_rate'];
So please why this is not working. 

Also check the exchangeRates array format. It should be
[
"month-Year" => "AvgRates"
]

2022-09-26 02:49 UTC, pankaj-ag commented on Modules/Report/Services/Finance/RevenueReportService.php
> +        $invoices = $this->invoiceService->getInvoicesBetweenDates($startDate, $endDate, 'non-indian');
Sorry it was my bad.

2022-09-26 10:31 UTC, Himanshunegi0332 commented on Modules/Report/Services/Finance/RevenueReportService.php
> +        $exchangeRates = CurrencyAvgRate::select('captured_for')->groupBy('captured_for')->get()->toArray();
ok sir

2022-10-01 09:53 UTC, pankaj-ag approved these changes

2022-10-01 09:56 UTC, pankaj-ag approved these changes

2022-10-01 09:56 UTC, merged