made UI
ColoredCow/portal pull request #2528
Opened 2022-09-23 11:55 UTC by Abhishek25081999

Targets #2505

### Description

### Checklist:
- [ ] I have performed a self-review of my own code.

2022-09-24 16:20 UTC, pankaj-ag requested changes

2022-09-24 16:20 UTC, pankaj-ag commented on Modules/Expense/Resources/views/create.blade.php
> +                                @foreach (config('constants.office_locations') as $office => $locaions)
```suggestion
                                @foreach (config('constants.office_locations') as $office => $location)
```

2022-09-24 16:20 UTC, pankaj-ag commented on Modules/Expense/Services/ExpenseService.php
> +            $expense = Expense::create($data);
Why we are creating expense again and again?

2022-09-24 17:29 UTC, pankaj-ag requested changes
We also need to create the update functionality

2022-09-24 17:29 UTC, pankaj-ag commented on Modules/Expense/Database/Migrations/2022_08_26_122610_create_Expense_table.php
> -            $table->bigIncrements('id');
As per the new database standards, Ids should be big int. Why we are making this change ?

Or this a new thing in laravel ?

2022-09-24 17:29 UTC, pankaj-ag commented on Modules/Expense/Database/Migrations/2022_09_23_184506_create_expense_files_table.php
> +            $table->integer('expense_id')->unsigned();
```suggestion
            $table->bigUnsignedInteger('expense_id');
```

2022-09-24 17:29 UTC, pankaj-ag commented on Modules/Expense/Resources/views/create.blade.php
> +                                @foreach (config('constants.office_locations') as $office => $locations)
```suggestion
                                @foreach (config('constants.office_locations') as $office => $location)
```

2022-09-24 17:35 UTC, Abhishek25081999 commented on Modules/Expense/Database/Migrations/2022_08_26_122610_create_Expense_table.php
> -            $table->bigIncrements('id');
I've changed it because without this change it was showing the error.
and I took reference from users and wishlist book's migration tables.

2022-09-26 05:16 UTC, Abhishek25081999 commented on Modules/Expense/Services/ExpenseService.php
> +            $expense = Expense::create($data);
Sorry made mistakenly. I've resolved it.

2022-09-26 05:16 UTC, Abhishek25081999 commented on Modules/Expense/Database/Migrations/2022_09_23_184506_create_expense_files_table.php
> +            $table->integer('expense_id')->unsigned();
Done!

2022-09-26 05:16 UTC, Abhishek25081999 commented on Modules/Expense/Resources/views/create.blade.php
> +                                @foreach (config('constants.office_locations') as $office => $locations)
Done!

2022-09-28 05:18 UTC, pankaj-ag commented
Can we show the file names here?

<img width="1135" alt="image" src="https://user-images.githubusercontent.com/10670690/192693549-07c7af69-34e6-4770-9c6b-06d712610606.png">

Getting errors while editing the file and removing a document.
<img width="1317" alt="image" src="https://user-images.githubusercontent.com/10670690/192693602-65d814c5-cba1-4cd0-b954-5fcbe5d35c9e.png">

2022-09-28 05:23 UTC, pankaj-ag requested changes
Shared feedback already please check.

2022-09-28 05:23 UTC, pankaj-ag commented on Modules/Expense/Resources/views/edit.blade.php
> +            <form action="{{ route('expense.update',$expense[0]['id']) }}" method="POST" enctype="multipart/form-data">
Did not get this? why we need to use $expense[0]['id'] instead of $expense->id?

2022-09-28 05:23 UTC, pankaj-ag commented on Modules/Expense/Services/ExpenseService.php
> +            ExpenseFile::find($key)->update($data);
$data ?

2022-09-28 09:25 UTC, Abhishek25081999 commented on Modules/Expense/Services/ExpenseService.php
> +            ExpenseFile::find($key)->update($data);
Can I use $request instead of data?

2022-10-13 11:14 UTC, pankaj-ag approved these changes

2022-10-13 11:14 UTC, merged