added plus icon in add university button
ColoredCow/portal pull request #2531
Opened 2022-09-24 06:16 UTC by Sarvesh-Ghildiyal

Targets #{ISSUE_ID}
#2335

### Description
added plus icon in ADD UNIVERSITY BUTTON

### Checklist:
- [ ] I have performed a self-review of my own code.

2022-09-24 06:24 UTC, Ayush8923 requested changes
Please check the comment.

2022-09-24 06:24 UTC, Ayush8923 commented on Modules/HR/Resources/views/universities/index.blade.php
> +        <div class="col-md-2">
Why did you change this line? While there was no need to change this line.

2022-09-24 06:24 UTC, Ayush8923 commented on Modules/HR/Resources/views/universities/index.blade.php
> +            <a href="{{ route('universities.create') }}" class="btn btn-success btn-block btn-lg"><i class="fa fa-plus fa-light icon-0.2x"><span style="font-size:medium;"> Add University</span></i></
Why add this class `fa-light icon-0.2x`? and please use bootstrap class.

2022-09-24 06:54 UTC, Ayush8923 requested changes

2022-09-24 06:54 UTC, Ayush8923 commented on Modules/HR/Resources/views/universities/index.blade.php
> +            <a href="{{ route('universities.create') }}" class="btn btn-success btn-block btn-lg"><i class="fa fa-plus fa-light icon-0.2x"><span style="font-size:medium;"> Add University</span></i></
```suggestion
            <a href="{{ route('universities.create') }}" class="btn btn-success btn-block btn-lg"><i class="fa fa-plus fa-light icon-0.2x"><span style="font-size:medium;"> Add New University</span></i></a>
```

2022-09-26 07:58 UTC, Ayush8923 requested changes
Please check the comment.

2022-09-26 07:58 UTC, Ayush8923 commented on Modules/HR/Resources/views/universities/index.blade.php
> +            <a href="{{ route('universities.create') }}" class="btn btn-success btn-block btn-lg"><i class="fa fa-plus"></i><span style="font-size:medium;"> Add New University</span></a>
```suggestion
            <a href="{{ route('universities.create') }}" class="btn btn-success btn-block btn-lg"><i class="fa fa-plus mr-1"></i>Add New University</a>
```

2022-09-30 02:54 UTC, Sarvesh-Ghildiyal commented on Modules/HR/Resources/views/universities/index.blade.php
> +            <a href="{{ route('universities.create') }}" class="btn btn-success btn-block btn-lg"><i class="fa fa-plus"></i><span style="font-size:medium;"> Add New University</span></a>
i used <span class="font-size:medium"> that is to keep "add new university" text in check so that it comes in single line of the button else it is shown in multi line:

"""""Add New""""""
"""University""""""

like this in the button.

2022-10-02 07:02 UTC, Ayush8923 requested changes
Please check the comments.

2022-10-02 07:02 UTC, Ayush8923 commented on Modules/HR/Resources/views/universities/index.blade.php
> +        <div class="col-md-3 font-size:medium;">
```suggestion
        <div class="col-md-3">
```

2022-10-02 07:07 UTC, Sarvesh-Ghildiyal commented on Modules/HR/Resources/views/universities/index.blade.php
> +        <div class="col-md-3 font-size:medium;">
I need to use font-size medium class if not here, not using span then where can I use it?????

2022-10-02 07:08 UTC, Sarvesh-Ghildiyal commented on Modules/HR/Resources/views/universities/index.blade.php
> +        <div class="col-md-3 font-size:medium;">
Without it webpage wouldn't be like we need!

2022-10-02 13:51 UTC, Ayush8923 requested changes

2022-10-02 13:51 UTC, Ayush8923 commented on Modules/HR/Resources/views/universities/index.blade.php
> +        <div class="col-md-3 font-size:medium;">
I did not understand your point. what do you want to say?

2022-10-07 15:42 UTC, Ayush8923 approved these changes
Looks good.

2022-10-08 07:37 UTC, merged