show drop down for all round application in to approve tab
ColoredCow/portal pull request #2540
Opened 2022-09-26 07:55 UTC by brajesh-lab

Targets #{2509}

### Description
show drop down for all round application in to approve tab
### Checklist:

- [ ] I have performed a self-review of my own code.

2022-09-27 04:22 UTC, P4NK4J requested changes
Left some comments, please check

2022-09-27 04:22 UTC, P4NK4J commented on resources/views/hr/application/edit.blade.php
> +                        <div  id="nav-tabContent">
What does these additional classes do ?, I didn't see a bootstrap class with name nav-tabContent ?

2022-09-27 04:22 UTC, P4NK4J commented on resources/views/hr/application/edit.blade.php
> +                                                            data-action="update">Update feedback702</button>
what's feedback 702 ?

2022-09-27 04:22 UTC, P4NK4J commented on resources/views/hr/application/edit.blade.php
> +                                                    if (in_array($applicationRound->application->status, [config('constants.hr.status.sent-for-approval.label'), config('constants.hr.status.approved.l
what's the purpose of adding in progress label here ?

2022-09-27 04:22 UTC, P4NK4J commented on resources/views/hr/application/edit.blade.php
> -                                                        @if ($applicationRound->showActions)
why this condition is removed ?

2022-09-27 06:03 UTC, brajesh-lab commented on resources/views/hr/application/edit.blade.php
> +                                                    if (in_array($applicationRound->application->status, [config('constants.hr.status.sent-for-approval.label'), config('constants.hr.status.approved.l
To show footer for if application status is in progress label

2022-09-28 05:55 UTC, brajesh-lab commented on resources/views/hr/application/edit.blade.php
> +                        <div  id="nav-tabContent">
these classes hide the div  when clicking on any part of the these div tag

2022-09-28 05:57 UTC, brajesh-lab commented on resources/views/hr/application/edit.blade.php
> +                                                            data-action="update">Update feedback702</button>
sorry i will correct that it is made by mistake

2022-09-28 05:58 UTC, brajesh-lab commented on resources/views/hr/application/edit.blade.php
> -                                                        @if ($applicationRound->showActions)
to show drop down for all round of applications

2022-10-11 07:53 UTC, P4NK4J requested changes
@brajesh-lab If an application is evaluated in previous round, the take action bar should not appear there. Please fix that, and else looks good.
<img width="829" alt="image" src="https://user-images.githubusercontent.com/35001775/195030931-f11843f9-f9e2-4a36-9954-0f9be04c258e.png">

2023-04-07 12:26 UTC, closed without merging