total amount
ColoredCow/portal pull request #2543
Opened 2022-09-26 11:07 UTC by parasnegi2002

Targets #2295 
### Description
added Total amount calculation for the Indian Client Invoice 
### Checklist:
- [ ] I have performed a self-review of my own code.

2022-10-01 08:19 UTC, Ayush8923 commented
@parasnegi2002 Please add the correct issue target id of your PR. You have added the id of another PR.

2022-10-01 08:19 UTC, Ayush8923 reviewed
@parasnegi2002 Please add the correct issue target id of your PR. You have added the id of another PR.

2022-10-02 06:58 UTC, Ayush8923 requested changes
Please check the comment.

2022-10-02 06:58 UTC, Ayush8923 commented on Modules/Invoice/Resources/views/subviews/edit/invoice-details.blade.php
> +                        </span>
Can we write it like this?
```suggestion
                        <span>
                            {{ $invoice->display_amount . " + " . $invoice->gst ." ₹". " = " }} <span id="totalAmount">{{$invoice->total_amount }} ₹</span>
                        </span>
```

2022-10-13 11:11 UTC, Shivam-Samant approved these changes
Looks good

2022-10-16 07:40 UTC, Ayush8923 requested changes

2022-10-16 07:40 UTC, Ayush8923 commented on Modules/Invoice/Resources/views/subviews/edit/invoice-details.blade.php
> +            console.log($("#totalAmount").text().trim(), (totalPaidAmount.split(/\=/)[1]).trim(), $("#totalAmount").text().trim() == (totalPaidAmount.split(/\=/)[1]).trim())
Removed debugging code `console.log`.

2022-10-28 15:17 UTC, Ayush8923 approved these changes

2023-05-08 11:44 UTC, closed without merging