Fixed wishlisted books functionality
ColoredCow/portal pull request #2547
Opened 2022-09-27 13:35 UTC by Kirannegi02

Targets #2534 

### Description
- Fixed the wish listed books functionality.

### Checklist:

- [ ] I have performed a self-review of my own code.

2022-09-27 15:23 UTC, P4NK4J requested changes
@Kirannegi02 Left some comments, please check

2022-09-27 15:23 UTC, P4NK4J commented on app/Http/Controllers/KnowledgeCafe/Library/BookController.php
> +        } elseif (request()->has('category_name')) {
Two questions, 
1. Can we use switch cases instead of these multiple else if ?
2. Why snake case is used in request variable here while in above line its camelCase ? can we have consistent parameters casing ?

2022-09-28 13:10 UTC, Kirannegi02 commented on app/Http/Controllers/KnowledgeCafe/Library/BookController.php
> +        } elseif (request()->has('category_name')) {
Yes, I will correct it

2022-10-11 09:29 UTC, P4NK4J approved these changes
Looks good.

2022-10-11 17:53 UTC, Ayush8923 approved these changes

2022-10-11 17:54 UTC, merged