Feature-2532-first-commit
ColoredCow/portal pull request #2550
Opened 2022-09-28 07:17 UTC by 11karangm

Targets #2523

### Description

Created a view to display volunteers that applied today on a chart as bargraph.

### Checklist:

- [ ] I have performed a self-review of my own code.

2022-09-29 08:24 UTC, P4NK4J requested changes
left some comments, please check

2022-09-29 08:24 UTC, P4NK4J commented on Modules/HR/Http/Controllers/Recruitment/JobController.php
> +    }
What's the use of this function ?

2022-09-29 08:24 UTC, P4NK4J commented on Modules/HR/Http/Controllers/Recruitment/JobController.php
> +    public function findApplicant()
Which applicant we are trying to find here ?

2022-09-29 08:24 UTC, P4NK4J commented on Modules/HR/Http/Controllers/Recruitment/JobController.php
> +        //dd($jobs);
Let's remove the code if not needed

2022-09-29 08:24 UTC, P4NK4J commented on app/Http/Controllers/HR/Volunteers/ReportsController.php
> +    }
I see this function was used in the JobController as well ? What's the use and why its repeated ?

2022-09-29 08:24 UTC, P4NK4J commented on app/Models/user.php
> +}
Why we need this model file here in app folder ?

2022-09-29 08:24 UTC, P4NK4J commented on database/migrations/2022_09_25_131747_add_foreign_key_to_hr_applicants.php
> +            $table->integer('job_id')->unsigned()->nullable();
Why we need to have job_id in applicants table ? job ID should be mapped to application, and applications are mapped to the applicant. I don't understand the use case of this?

2022-09-29 08:24 UTC, P4NK4J commented on resources/views/hr/volunteers/reports.blade.php
> +    <h1 class="text-center">Reports Vol</h1>
What's Reports vol ?

2022-09-29 08:24 UTC, P4NK4J commented on routes/web.php
> +            //Route::get('reportscount', 'ReportsController@Show')->name('volunteers.dailyapplicationscount');
Can we remove this commented code ?

2022-09-29 08:38 UTC, 11karangm commented on database/migrations/2022_09_25_131747_add_foreign_key_to_hr_applicants.php
> +            $table->integer('job_id')->unsigned()->nullable();
I will delete this file. Made this file when I was a bit confused with the logic. I had deleted that column from my local database.

2022-09-29 08:38 UTC, 11karangm commented on resources/views/hr/volunteers/reports.blade.php
> +    <h1 class="text-center">Reports Vol</h1>
It was the heading of the page , will make it a clearer heading.

2022-09-29 08:39 UTC, 11karangm commented on routes/web.php
> +            //Route::get('reportscount', 'ReportsController@Show')->name('volunteers.dailyapplicationscount');
Will delete

2022-09-29 08:43 UTC, 11karangm commented on app/Models/user.php
> +}
Sorry created that file by accident when I was working on another laravel project to learn about some eloquent functions.
I will delete that file.

2022-09-29 09:03 UTC, 11karangm commented on Modules/HR/Http/Controllers/Recruitment/JobController.php
> +        //dd($jobs);
I will remove the "dd()" need the job id for performing query.

2022-09-29 09:06 UTC, 11karangm commented on Modules/HR/Http/Controllers/Recruitment/JobController.php
> +    public function findApplicant()
We are trying to find Applications applied by an applicant for volunteer type job.
Or 
In other words we are trying to find the number of Applicants who have applied to become a volunteer and diplay it on the chart.

2022-09-29 09:10 UTC, 11karangm commented on Modules/HR/Http/Controllers/Recruitment/JobController.php
> +    }
That function was there in the ReportsController in HR module. It gives the count of verified applications.
My chart model was based of the one present in HR module.  It was present in that module. But my guide told to remove it from the volunteers module. I removed the view but forgot to remove the code logic . I will remove it now.

2022-09-29 12:45 UTC, P4NK4J requested changes
Left some comments.

2022-09-29 12:45 UTC, P4NK4J commented on Modules/HR/Http/Controllers/Recruitment/JobController.php
> +    public function findApplicant()
Why this is written in JobController ? Shouldn't this be a part of applicantController? Also the function name should be `findVolunteerApplicant` or something similar

2022-09-29 12:45 UTC, P4NK4J commented on Modules/HR/Http/Controllers/Recruitment/JobController.php
> +        $data['chartData'] = json_encode($data);
This logic should go in applicant service, where you need to send the request data and call service function.

2022-09-29 12:45 UTC, P4NK4J commented on resources/views/hr/volunteers/reportresult.blade.php
> +@extends('layouts.app')
Can we rename this to `daily-volunteer-application-report.blade.php` if its serving the same purpose ?

2022-09-29 12:45 UTC, P4NK4J commented on routes/web.php
> +Route::get('reportserCard', [JobController::class, 'findApplicant'])->name('volunteers.applicationcount');
This route doesn't make sense, `reportserCard` ? Also, why this route is outside auth bracket ?

2022-09-30 07:12 UTC, 11karangm commented on Modules/HR/Http/Controllers/Recruitment/JobController.php
> +        $data['chartData'] = json_encode($data);
I don't understand exactly what you mean.
That is the logic of findVolunteerApplicant().
I am going to put that function in Application Controller according to you instructions. A simmilar logic is there in a simmilar function showReportCard(), and this function is in ReportsController.

2023-04-07 12:26 UTC, closed without merging