Bugfix/fixing the velocity
ColoredCow/portal pull request #2559
Opened 2022-09-29 10:55 UTC by amisha296

Targets #2256 

### Description

### Checklist:

- [ ] I have performed a self-review of my own code.

2022-10-04 17:45 UTC, gautam071 commented on Modules/Project/Resources/views/index.blade.php
> +
INDENTATION

2022-10-04 17:45 UTC, gautam071 commented on Modules/Project/Resources/views/index.blade.php
> +                        @forelse($data['clients'] as $client)
Why are you using the $data['clients'] instead of $clients

2022-10-05 07:42 UTC, amisha296 commented on Modules/Project/Resources/views/index.blade.php
> +                        @forelse($data['clients'] as $client)
I have made the changes in the service file now the data is coming under data.

2022-10-05 08:05 UTC, amisha296 commented on Modules/Project/Resources/views/index.blade.php
> +
done!

2022-10-06 05:45 UTC, gautam071 requested changes

2022-10-06 05:45 UTC, gautam071 commented on Modules/Project/Resources/views/index.blade.php
> +                        @forelse($data['clients'] as $client)
my question is why?

2022-10-06 05:49 UTC, amisha296 commented on Modules/Project/Resources/views/index.blade.php
> +                        @forelse($data['clients'] as $client)
Because data is coming from data no, I have stored the data inside the data

2023-05-08 11:47 UTC, closed without merging