Feature 2566 edit delete button
ColoredCow/portal pull request #2569
Opened 2022-10-04 05:51 UTC by 11karangm

Targets #2566

### Description
Problems already existing in code:
1) All resume flaged 1 doesn't appear on the table only the currently flaged resume appears on the table.
2) The resume doesn't dissapear from the table when I unflag it.

**What I implemented: **
1)Created an actions column in the table and added edit and delete button.
2) **Edit button functionality: ** - Pops up a modal for editing the reason for desiring a resume.
                                                    - The text from the modal is used to update column "value" in table "hr_application_meta"
3) **Delete Button** - Changes the value of column "is_desired_resume" in "hr_applications" table from 1 to 0.              

### Checklist:

- [ ] I have performed a self-review of my own code.

2022-10-04 05:55 UTC, P4NK4J requested changes
@11karangm Let's add null checks where data is not present, its throwing errors when there is no information available.

<img width="1340" alt="image" src="https://user-images.githubusercontent.com/35001775/193744753-56e0306e-30a3-4248-91f6-da998bf4ea29.png">

The reason available should be prefilled in the modal
<img width="1412" alt="image" src="https://user-images.githubusercontent.com/35001775/193744828-be4411e0-f14c-4165-ae94-f205047fef5c.png">

Upon submitting the form, the following error is thrown
<img width="1437" alt="image" src="https://user-images.githubusercontent.com/35001775/193744877-b49b59df-48f7-4d15-8381-272abfad0564.png">

Upon deletion, the following error is appearing

<img width="1440" alt="image" src="https://user-images.githubusercontent.com/35001775/193744926-e8fd77d4-7d86-4f24-9c80-ebde1b3cd5e7.png">

2022-10-04 14:14 UTC, P4NK4J requested changes
Left some comments, please check

2022-10-04 14:14 UTC, P4NK4J commented on Modules/HR/Http/Controllers/Recruitment/JobController.php
> +        // dd($id, $hr_job_id);
Let's remove the commented code here

2022-10-04 14:14 UTC, P4NK4J commented on Modules/HR/Http/Controllers/Recruitment/JobController.php
> +    public function unflagResponse($id, $hr_job_id)
let's give this function a relative name say `unflagDesiredResume`, thoughts ?

2022-10-04 14:14 UTC, P4NK4J commented on Modules/HR/Http/Controllers/Recruitment/JobController.php
> +    public function editResponse(HttpRequest $request, $id, $hr_job_id)
```suggestion
    public function editDesiredResumeReasons(HttpRequest $request, $id, $hr_job_id)
```
How about this ?

2022-10-04 14:14 UTC, P4NK4J commented on Modules/HR/Http/Controllers/Recruitment/JobController.php
> +    public function editResponse(HttpRequest $request, $id, $hr_job_id)
```suggestion
    public function editResponse(HttpRequest $request, $id, $hrJobId)
```

2022-10-04 14:14 UTC, P4NK4J commented on Modules/HR/Http/Controllers/Recruitment/JobController.php
> +            'title' => $applicationdata[0]->title
```suggestion
            'title' => $applicationData[0]->title
```

2022-10-04 14:14 UTC, P4NK4J commented on resources/views/hr/application/resume-table.blade.php
> +                    </td> --}}
Let's remove this code if not needed

2022-10-05 05:28 UTC, 11karangm commented on Modules/HR/Http/Controllers/Recruitment/JobController.php
> +    public function unflagResponse($id, $hr_job_id)
sure

2022-10-05 05:29 UTC, 11karangm commented on Modules/HR/Http/Controllers/Recruitment/JobController.php
> +    public function editResponse(HttpRequest $request, $id, $hr_job_id)
sure
Personaly I think it's too long though.

2022-10-05 05:30 UTC, 11karangm commented on Modules/HR/Http/Controllers/Recruitment/JobController.php
> +            'title' => $applicationdata[0]->title
There is another variable in that function called 'applicationData' that's why I used 'applicationdata'.

2022-10-05 05:31 UTC, 11karangm commented on resources/views/hr/application/resume-table.blade.php
> +                    </td> --}}
sure

2022-10-05 05:33 UTC, P4NK4J commented on Modules/HR/Http/Controllers/Recruitment/JobController.php
> +    public function editResponse(HttpRequest $request, $id, $hr_job_id)
Yeah, for a better readability of code, we don't see the length of function name, the function name should tell why it's being used. So better if we keep specific names.

2022-10-05 05:33 UTC, P4NK4J commented on Modules/HR/Http/Controllers/Recruitment/JobController.php
> +            'title' => $applicationdata[0]->title
Maybe rename the variable ? how both the variables have same name and functioning differently ? can we make it consistent, maybe by using the same variable, passing data in that through controller. If not, let's rename this variable. then

2022-10-05 05:34 UTC, 11karangm commented on Modules/HR/Http/Controllers/Recruitment/JobController.php
> +    public function editResponse(HttpRequest $request, $id, $hr_job_id)
ok understood

2022-10-05 05:54 UTC, P4NK4J approved these changes
Looks good.

2022-10-05 05:54 UTC, merged