email template
ColoredCow/portal pull request #2601
Opened 2022-10-13 05:17 UTC by kanuj365

Targets #2539

### Description
Resume Screening , Introductory call , Basic technical round. 

### Checklist:
- [ ] I have performed a self-review of my own code.

2022-10-15 14:04 UTC, Shivam-Samant commented on Modules/HR/Database/Seeders/SettingsTableSeeder.php
> +            'setting_value' => '<div>Hello,<br /><br /></div><div>ColoredCow congratulates you on taking the first step to explore the opportunities of building great things!<br /><br /></div><div><p
Why are you change in this file?

2022-10-15 14:08 UTC, Shivam-Samant commented on Modules/HR/Database/Seeders/HRRoundsTableSeeder.php
> +            'confirmed_mail_template' => '{"body": "<p class=\\"p1\\">Hi |*applicant_name*|,</p><p class=\\"p1\\">Thanks for talking to us on |*interview_time*|.<br /><br />It\'s nice talking to you.
Why are you changing the Telephonic Interview round template?

2022-10-15 14:10 UTC, Shivam-Samant commented on Modules/HR/Database/Seeders/HRRoundsTableSeeder.php
>          ]);
You need to make the changes in the rejected template as well

2022-10-15 15:31 UTC, kanuj365 commented on Modules/HR/Database/Seeders/HRRoundsTableSeeder.php
>          ]);
the task's requirement.

2022-11-10 12:15 UTC, P4NK4J requested changes
@kanuj365 You only needed to update the content of the email template, instead of updating the HTML coding, adding JSON decode etc. This will work on your local machine but throw an error on production. Please change only the content in the templates. Also, there are different files changed here, the only file which is supposed to be updated is `HRRoundsTableSeeder.php`, please make the changes and assign for review.

2022-11-11 11:50 UTC, P4NK4J approved these changes
Looks good.

2022-11-11 11:50 UTC, merged