update feedback and schedule
ColoredCow/portal pull request #2606
Opened 2022-10-14 04:13 UTC by kanuj365

Targets #2602

### Description
update feedback and schedule

### Checklist:
- [ ] I have performed a self-review of my own code.

2022-10-15 11:48 UTC, P4NK4J requested changes

2022-10-15 11:48 UTC, P4NK4J commented on Modules/HR/Http/Controllers/Recruitment/ApplicationRoundController.php
> +        return redirect()->back()->with('status', 'Application updated successfully!');
This will return to the edit page, for all the actions, we only need when updatefeedback and updateSchedule buttons are clicked. Please change the logic

2022-11-12 08:03 UTC, pokhiii commented
> for some reason app.js code not going back as before, I tried many time but it was not changed

@kanuj365 Just checking about this:

1. Do you want to make `resources/js/app.js` exactly like it is in the `master` branch?
2. What have you tried so far?

2022-11-14 05:08 UTC, P4NK4J requested changes
@kanuj365 All the actions are redirecting user to edit application page, even if we reject the application. We only want update Schedule button and update Feedback button to be redirected to this page, rest of them can go to the applications listing page.

2022-11-15 08:46 UTC, P4NK4J requested changes
Left a comment, please check

2022-11-15 08:46 UTC, P4NK4J commented on Modules/HR/Http/Controllers/Recruitment/ApplicationRoundController.php
> +        $var = $request->validated();
I see `$request->validated()` is being used on line number 24 as well. Can we define it in a single variable and then use at both the places ? Also, let's rename this to something meaningful, like `$validatedData` or so ?

2022-11-15 09:46 UTC, merged