feature-2603-working-staff-directory
ColoredCow/portal pull request #2609
Opened 2022-10-14 11:53 UTC by 11karangm

Targets #2603
Did everything in the task description except fetching constants from config.php to modal.

### Checklist:

- [ ] I have performed a self-review of my own code.

2022-10-15 11:46 UTC, P4NK4J requested changes
Left some minor comments, overall looks really good.

2022-10-15 11:46 UTC, P4NK4J commented on resources/views/settings/permissions/users.blade.php
> -		@include('settings.permissions.update-user-roles-modal')
Why this is removed ?

2022-10-15 11:46 UTC, P4NK4J commented on resources/views/settings/permissions/update-user-roles-modal.blade.php
> -</div>
Why we are removing this modal ?

2022-10-15 11:46 UTC, P4NK4J commented on resources/js/app.js
> +				console.log("working");
remove logs here

2022-10-15 11:46 UTC, P4NK4J commented on package.json
> +        "axios": "^0.21.4",
Why this needs to be updated ?

2022-10-15 11:46 UTC, P4NK4J commented on Modules/User/Resources/assets/js/components/UserListing.vue
> +
Let's strip this empty space

2022-10-15 11:46 UTC, P4NK4J commented on Modules/User/Resources/assets/js/components/UpdateUserStaffTypeModal.vue
> +
Remove extra spaces

2022-10-15 11:46 UTC, P4NK4J commented on Modules/User/Resources/assets/js/components/UpdateUserStaffTypeModal.vue
> +
Remove space here as well

2022-10-15 11:46 UTC, P4NK4J commented on Modules/User/Resources/assets/js/components/UpdateUserStaffTypeModal.vue
> +					console.log("success");
Remove the console log

2022-10-15 11:46 UTC, P4NK4J commented on Modules/User/Resources/assets/js/components/UpdateUserStaffTypeModal.vue
> +	</template>
Indentation for the main <div> is needed

2022-10-15 12:20 UTC, 11karangm commented on resources/views/settings/permissions/users.blade.php
> -		@include('settings.permissions.update-user-roles-modal')
That is reduntant code , the actual modal being used is UpdateUserRoleModal.vue I wasted alot of time trying to figure out how update-user-roles-modal worked. So after I made everything work I checked if it is still worked without that. I don't know if it's used for any other functionality, I forgot to add back, should I add it back to the code.

2022-10-15 12:21 UTC, 11karangm commented on resources/views/settings/permissions/update-user-roles-modal.blade.php
> -</div>
same as above please check and confirm if we need it.

2022-10-15 12:23 UTC, 11karangm commented on resources/js/app.js
> +				console.log("working");
I will remove that. but that function is also redundant I think. I didn't remove it because I don't know the project that well.
That function and many other related functions in app.js was giving me such a headache. I was being misdirected a lot because of them.

2022-10-15 12:24 UTC, 11karangm commented on package.json
> +        "axios": "^0.21.4",
I installed axios from my command line, because I thought without installing the code wouldn't work , so it got added again I will remove it.

2022-10-15 12:24 UTC, 11karangm commented on Modules/User/Resources/assets/js/components/UserListing.vue
> +
ok

2022-10-15 12:28 UTC, 11karangm commented on Modules/User/Resources/assets/js/components/UpdateUserStaffTypeModal.vue
> +	</template>
can you explain a little more elaborately? main?

2022-10-17 05:54 UTC, P4NK4J commented on Modules/User/Resources/assets/js/components/UpdateUserStaffTypeModal.vue
> +	</template>
Indentation should be like this, while above I see the div and template tags are on the same line
```
<template>
    <div>
    </div>
</template>
```

2022-10-17 05:57 UTC, P4NK4J reviewed
Responded to the comments, please check

2022-10-17 05:57 UTC, P4NK4J commented on resources/views/settings/permissions/users.blade.php
> -		@include('settings.permissions.update-user-roles-modal')
If that's redundant, probably removing it should be good. If there is any issue with production, we will figure it out later.

2022-10-17 05:58 UTC, P4NK4J commented on resources/js/app.js
> +				console.log("working");
Let it be there for a while removing the console log. I didn't get a chance to give it a thought, maybe we will refactor is later.

2022-10-17 06:57 UTC, P4NK4J approved these changes
Looks good 👏

2022-10-17 06:57 UTC, merged