made user management page responsive
ColoredCow/portal pull request #2611
Opened 2022-10-16 05:05 UTC by Vimalnegi03

Targets #{2481}

### Description
MADE USER MANAGEMENT PAGE RESPONSIVE

### Checklist:

- [ ] I have performed a self-review of my own code.

2022-11-03 18:17 UTC, Ayush8923 commented on Modules/User/Resources/views/index.blade.php
> +	</div>
Can we write like this? We don't need to extra `div`.
```suggestion
	<h4 class="ml-3">User Management</h4>
```

2022-11-03 18:19 UTC, Ayush8923 requested changes
@Vimalnegi03 Please fix the indentation.

2022-11-03 18:19 UTC, Ayush8923 commented
@Vimalnegi03 Please resolve the merge conflicts also.

2022-11-05 16:31 UTC, Ayush8923 commented on Modules/User/Resources/assets/js/components/UserListing.vue
> +
Remove extra line.

2022-11-05 16:32 UTC, Ayush8923 requested changes
@Vimalnegi03 Please remove extra line and update the all place.

2022-11-05 16:32 UTC, Ayush8923 commented on Modules/User/Resources/assets/js/components/UserListing.vue
> +
Same here. Remove these extra line

2022-11-05 16:32 UTC, Ayush8923 commented on Modules/User/Resources/assets/js/components/UserListing.vue
> +
Same here.

2022-11-06 15:23 UTC, Ayush8923 requested changes

2022-11-06 15:23 UTC, Ayush8923 commented on Modules/User/Resources/assets/js/components/UserListing.vue
> +			<div class="col-12 col sm-12 col md-12">
```suggestion
			<div class="col-12">
```

2022-11-07 12:25 UTC, Ayush8923 requested changes
@Vimalnegi03 Left some questions. Please check.

2022-11-07 12:25 UTC, Ayush8923 commented on Modules/User/Resources/assets/js/components/UserListing.vue
> -								<i class="fa fa-cog fa-lg" aria-hidden="true"></i>
Why did you remove it?

2022-11-07 12:25 UTC, Ayush8923 commented on Modules/User/Resources/assets/js/components/UserListing.vue
> -								<i class="fa fa-trash fa-lg" aria-hidden="true"></i>
Same here.

2022-11-07 14:08 UTC, Vimalnegi03 commented on Modules/User/Resources/assets/js/components/UserListing.vue
> -								<i class="fa fa-trash fa-lg" aria-hidden="true"></i>
Actually these two buttons are not removed @Ayush8923 sir the first button was given some classes so that it becomes responsive ...same goes with second button 2 to adjust margin and padding some classes was added to it and when i recieved that task the name of that button was already changed to remove user..

2022-11-07 14:24 UTC, Vimalnegi03 commented on Modules/User/Resources/assets/js/components/UserListing.vue
> -								<i class="fa fa-cog fa-lg" aria-hidden="true"></i>
Sir these lines of codes was removed by someone who might have worked on this page before me..  I just recieved a merge conflict that i resolved ...may be because of that merge conflict it looks like that I have made this change...

2023-04-07 12:28 UTC, closed without merging