UI issue in Home screen
ColoredCow/portal pull request #2618
Opened 2022-10-18 05:10 UTC by ShivanshGairola

Targets #2536

### Description
the highlight is not the same size as the other two buttons.

### Checklist:
- [ ] I have performed a self-review of my own code.

2022-10-18 06:08 UTC, gautam071 submitted a review, later dismissed
what is the purpose of removing the development.md file

Can you add it back?

2022-10-18 06:08 UTC, gautam071 commented on resources/js/components/Dashboard/UserDashboardLibrary.vue
> +            padding-top: 20px;"
Can we use bootstrap class?

2022-10-19 05:12 UTC, ShivanshGairola commented on resources/js/components/Dashboard/UserDashboardLibrary.vue
> +            padding-top: 20px;"
done , I use py-3 for both top and bottom padding .

2022-12-20 06:14 UTC, GauravGusain98 commented on resources/js/components/Dashboard/UserDashboardLibrary.vue
> +            class="nav-link c-pointer py-3"
Why you removed this `@click="setActiveTile('recommend')"`

It was calling the function `setActiveTile` when the element is clicked. Do we not need that functionality?

2022-12-21 04:33 UTC, ShivanshGairola commented on resources/js/components/Dashboard/UserDashboardLibrary.vue
> +            class="nav-link c-pointer py-3"
Changes have been reverted

2022-12-21 05:43 UTC, GauravGusain98 approved these changes
LGTM

2022-12-21 05:47 UTC, GauravGusain98 requested changes
The `recommend` button doesnot seem to have fix
<img width="440" alt="image" src="https://user-images.githubusercontent.com/54376313/208831005-aa749352-c424-4f48-9dc9-fe7e9bcfa0ad.png">

2022-12-21 06:33 UTC, GauravGusain98 approved these changes
LGTM

2022-12-21 06:33 UTC, GauravGusain98 commented
> The `recommend` button doesnot seem to have fix <img alt="image" width="440" src="https://user-images.githubusercontent.com/54376313/208831005-aa749352-c424-4f48-9dc9-fe7e9bcfa0ad.png">

This is fixed by running `npm run dev`

2022-12-26 05:42 UTC, merged