ADD VALIDATION IN RECURRING EXPENSE
ColoredCow/portal pull request #2635
Opened 2022-11-04 08:00 UTC by ShivanshGairola

Targets #2361 

### Description
1.Added a new request file
2.Add backend validation
### Checklist:
- [ ] I have performed a self-review of my own code.

2022-11-25 04:49 UTC, gautam071 approved these changes
looks good

2022-12-19 08:23 UTC, GauravGusain98 requested changes
Please check the comment

2022-12-19 08:23 UTC, GauravGusain98 commented on Modules/Expense/Http/Requests/recurringExpenseRequest.php
> +        ];
```suggestion
        return [
            'name.required' => 'name is required',
            'amount.required'=>'amount is required',
            'currency.required'=>'currency is required',
            'frequency.required'=>'frequency is required',
        ];
```

2022-12-19 08:23 UTC, GauravGusain98 commented on Modules/Expense/Http/Requests/recurringExpenseRequest.php
> +class recurringExpenseRequest extends FormRequest
The name of the Class is in incorrect syntax. 
It should be in the Title case `RecurringExpenseRequest`. Also, the file name should also in title case. You can take reference from other request files

2022-12-20 05:41 UTC, GauravGusain98 approved these changes
LGTM

2022-12-26 05:41 UTC, merged