Feature/send email to user
ColoredCow/portal pull request #2636
Opened 2022-11-09 09:00 UTC by kanuj365

Targets #2563

### Description
- Create a query who read books by the users but some books was not commented by them.

### Checklist:
- [x] I have performed a self-review of my own code.

2022-11-15 09:09 UTC, gautam071 commented on app/Console/Commands/Testcron.php
> +                });
why Hello world?

2022-11-15 09:09 UTC, gautam071 commented on app/Console/Commands/Testcron.php
> +                $data = ['name' => $key, 'key1' => $value];
use service file

2022-11-15 09:09 UTC, gautam071 commented on app/Console/Kernel.php
> +use App\Console\Commands\Testcron;
change name

2022-11-15 09:09 UTC, gautam071 commented on app/Console/Kernel.php
> +        Testcron::class,
here as well

2022-11-15 09:10 UTC, gautam071 commented on resources/views/emails/mailsend.blade.php
> +				</td>
Change the variable name

2022-11-15 09:11 UTC, gautam071 commented
There are some file changes on the package.json? 
what's the reason

2022-11-16 06:03 UTC, gautam071 requested changes
Left some comments

2022-11-16 06:03 UTC, gautam071 commented on app/Services/BookServices.php
> +        $user_name = USER::wherenull('deleted_at')->orwhere('id', $user_id)->pluck('name')->toArray();
can we get the user name from the user id

2022-11-16 06:03 UTC, gautam071 commented on app/Services/BookServices.php
> +        $Id = [];
change the variable name

2022-11-16 06:03 UTC, gautam071 commented on resources/views/emails/mailsend.blade.php
> +	<p>It will take you about few minutes to complete our survey, but it’ll be invaluable to us for improving our services.</p>
```suggestion
	<p>It will take you about a few minutes to complete our survey, but it’ll be valuable to us for improving our books feature.</p>
```

2022-11-16 06:03 UTC, gautam071 commented on resources/views/emails/mailsend.blade.php
> +</div>
leave a line at the end

2022-11-16 06:34 UTC, kanuj365 commented on app/Services/BookServices.php
> +        $user_name = USER::wherenull('deleted_at')->orwhere('id', $user_id)->pluck('name')->toArray();
it can only user table. otherwise in library can't

2022-11-21 06:06 UTC, gautam071 requested changes

2022-11-21 06:06 UTC, gautam071 commented on app/Services/BookServices.php
> +                });
move the mail function to the command file

2023-05-08 12:15 UTC, closed without merging