Added the search bar and sorted on the basis maximum project first
ColoredCow/portal pull request #2637
Opened 2022-11-09 10:16 UTC by ditya0504

Targets #2627 

### Description
I'm using the searching function for employee name and sorted on the basis of maximum projects first.
### Checklist:

- [ ] I have performed a self-review of my own code.

2022-11-09 13:23 UTC, GauravGusain98 requested changes
Please check the comments

2022-11-09 13:23 UTC, GauravGusain98 commented on Modules/HR/Http/Controllers/EmployeeController.php
> +            ->leftJoin('project_team_members', 'employees.user_id', '=', 'project_team_members.team_member_id')
Here, I think we have to exclude the projects in which the user is not a part now but was earlier. For this you have to add a check where ended_on is NOT NULL. Then count the number of projects.

2022-11-09 13:23 UTC, GauravGusain98 commented on resources/views/hr/employees/index.blade.php
> +                        {{$employee-> Count}}
```suggestion
                        {{$employee->project_count}}
```

2022-11-09 13:23 UTC, GauravGusain98 commented on Modules/HR/Http/Controllers/EmployeeController.php
> +            ->selectRaw('employees.*, team_member_id, count(team_member_id) as Count')
Lets use more meaningful name
```suggestion
            ->selectRaw('employees.*, team_member_id, count(team_member_id) as project_count')
```

2022-11-10 05:13 UTC, ditya0504 commented on Modules/HR/Http/Controllers/EmployeeController.php
> +            ->leftJoin('project_team_members', 'employees.user_id', '=', 'project_team_members.team_member_id')
@GauravGusain98 Sorry but this was not mentioned in the issue, so i was not sure about this.

2022-11-10 05:13 UTC, ditya0504 commented on resources/views/hr/employees/index.blade.php
> +                        {{$employee-> Count}}
ok will change this

2022-11-10 10:19 UTC, GauravGusain98 commented on Modules/HR/Http/Controllers/EmployeeController.php
> +            ->leftJoin('project_team_members', 'employees.user_id', '=', 'project_team_members.team_member_id')
Actually it was in the code here
<img width="424" alt="image" src="https://user-images.githubusercontent.com/54376313/201065138-6ebaa339-5a67-4337-94d7-932f3c332a85.png">

2022-11-10 10:20 UTC, GauravGusain98 commented on resources/views/hr/employees/index.blade.php
> +                        {{$employee-> project_count}}
```suggestion
                        {{$employee->project_count}}
```

2022-11-10 10:20 UTC, GauravGusain98 commented on resources/views/hr/employees/index.blade.php
> +        <form id="employeeFilterForm" class ="d-md-flex justify-content-between ml-md-3">
```suggestion
        <form id="employeeFilterForm" class="d-md-flex justify-content-between ml-md-3">
```

2022-11-10 10:21 UTC, GauravGusain98 commented on Modules/HR/Http/Controllers/EmployeeController.php
> +            ->leftJoin('project_team_members', 'employees.user_id', '=', 'project_team_members.team_member_id')
please implement the changes

2022-11-10 11:41 UTC, GauravGusain98 requested changes
minor change requested, else looks good

2022-11-10 11:41 UTC, GauravGusain98 commented on Modules/HR/Http/Controllers/EmployeeController.php
> +            ->where('project_team_members.ended_on', '!=', 'NULL')
If the ended_on column is filled then it means that the team member is not a part of project
```suggestion
            ->where('project_team_members.ended_on', '=', 'NULL')
```

2022-11-10 13:45 UTC, GauravGusain98 approved these changes
minor change. Fixing it. Else looks good

2022-11-10 13:45 UTC, GauravGusain98 commented on Modules/HR/Http/Controllers/EmployeeController.php
> +            ->WhereNull('project_team_members.ended_on')
```suggestion
            ->whereNull('project_team_members.ended_on')
```

2022-11-10 13:47 UTC, merged