Added a search bar on the HR designations page
ColoredCow/portal pull request #2643
Opened 2022-11-16 06:11 UTC by rajatsajwan

Targets #2642

### Description
added a search bar for HR designation page

### Checklist:
- [ ] I have performed a self-review of my own code.

2022-11-18 05:15 UTC, P4NK4J requested changes
Left some comments, please check

2022-11-18 05:15 UTC, P4NK4J commented on Modules/HR/Routes/web.php
> +        Route::get('/search', 'HrJobDesignationController@index')->name('hr-job-designation.searchDesignation');
We don't need to create a separate route for this, it can be used as a GET parameter in index function of the resource controller

2022-11-18 05:15 UTC, P4NK4J commented on Modules/HR/Http/Controllers/HrJobDesignationController.php
> -        return view('hr.designations.index', $this->service->index(request()->all()));
Why this is changed to $request ?

2022-11-18 05:15 UTC, P4NK4J commented on Modules/HR/Services/HrJobDesignationService.php
> +        $searchDesignation = $request->input('search');
what would happen if `$request->input` doesn't have a search param value ?

2022-11-18 05:15 UTC, P4NK4J commented on Modules/HR/Services/HrJobDesignationService.php
> +        $design = HrJobDesignation::where('designation', $searchDesignation)->get();
There may be chances, that users may not enter the correct designation, let's change this to match a string set rather than calculating exact match, try use LIKE

2022-11-18 05:15 UTC, P4NK4J commented on Modules/HR/Services/HrJobDesignationService.php
> +        $design = HrJobDesignation::where('designation', $searchDesignation)->get();
Let's change the variable name, it doesn't make sense

2022-11-18 05:15 UTC, P4NK4J commented on resources/views/hr/designations/index.blade.php
> +            <form class="d-flex" method="GET" action="{{route('hr-job-designation.searchDesignation')}}">
You can use designation index as a action route here

2022-11-18 05:39 UTC, rajatsajwan commented on Modules/HR/Http/Controllers/HrJobDesignationController.php
> -        return view('hr.designations.index', $this->service->index(request()->all()));
``

2022-11-18 05:40 UTC, rajatsajwan commented on Modules/HR/Http/Controllers/HrJobDesignationController.php
> -        return view('hr.designations.index', $this->service->index(request()->all()));
@P4NK4J   we are using request in service so if we dont use a request it is giving us error

2022-11-18 05:49 UTC, rajatsajwan commented on Modules/HR/Services/HrJobDesignationService.php
> +        $searchDesignation = $request->input('search');
it will show all the values

2022-11-21 06:39 UTC, P4NK4J approved these changes

2022-11-21 06:39 UTC, merged