fix velocity bug in project
ColoredCow/portal pull request #2648
Opened 2022-11-21 10:12 UTC by rajatsajwan

Targets #2556 

### Description
fix the velocity bug in projects

### Checklist:

- [ ] I have performed a self-review of my own code.

2022-11-21 10:19 UTC, GauravGusain98 requested changes
Please check the comment

2022-11-21 10:19 UTC, GauravGusain98 commented on Modules/EffortTracking/Resources/views/show.blade.php
> +                    <span>{{ $project->velocity }}</span>
`$project->velocity` will only show the velocity for the current month. But we want to show the velocity for a particular month based on the dropdown here. 
<img width="1287" alt="image" src="https://user-images.githubusercontent.com/54376313/203025427-152b60ea-272c-45f5-842d-0f424e7d9d0d.png">

So you need to fix the calculation in the getVelocityForMonthAttribute() function that you will find inside the Project entity/Model

2022-11-21 10:19 UTC, GauravGusain98 commented on Modules/EffortTracking/Resources/views/show.blade.php
> +                    <span>{{ $project->velocity }}</span>
For current month the value of `$project->velocity` and `$project->getVelocityForMonthAttribute` should be same

2022-11-22 05:25 UTC, rajatsajwan commented on Modules/EffortTracking/Resources/views/show.blade.php
> +                    <span>{{ $project->velocity }}</span>
for particular month I don't have data , I shown only for november month .
![Screenshot (22)](https://user-images.githubusercontent.com/117888235/203229220-b9a98850-a97d-40b9-896a-f463b9340c87.png)

2022-11-22 06:48 UTC, rajatsajwan commented on Modules/EffortTracking/Resources/views/show.blade.php
> +                    <span>{{ $project->velocity }}</span>
sir what is formula to get velocity for month?????

2022-11-22 07:45 UTC, rajatsajwan commented on Modules/EffortTracking/Resources/views/show.blade.php
> +                    <span>{{ $project->velocity }}</span>
@GauravGusain98  sir what is formula to get for month????

2022-11-23 06:24 UTC, rajatsajwan commented
![Screenshot_20221123_115302](https://user-images.githubusercontent.com/117888235/203483999-ea68c54d-2244-46f6-b252-cf594a3dd9a3.png)

2022-11-23 06:26 UTC, rajatsajwan commented
formula of velocity = hour booked/expected hours

2022-11-24 05:31 UTC, GauravGusain98 requested changes
Please check the comment

2022-11-24 05:31 UTC, GauravGusain98 commented on Modules/EffortTracking/Resources/views/show.blade.php
> +                    <span>{{ $project->getVelocityForMonthAttribute($monthToSubtract=1, $startDate , $endDate ) }}</span>
Why you are assigning `$monthToSubtract=1` while calling a function?

2022-11-24 05:31 UTC, GauravGusain98 commented on Modules/EffortTracking/Resources/views/show.blade.php
> +                    <span>{{ $project->getVelocityForMonthAttribute($monthToSubtract=1, $startDate , $endDate ) }}</span>
This is not a correct syntax, This will always pass 1 as the first argument I guess, so whatever the value of `$monthToSubtract` will be it will become 1 while calling this function

2022-11-24 05:31 UTC, GauravGusain98 commented on Modules/Project/Entities/Project.php
> +    public function getVelocityForMonthAttribute($monthToSubtract = 1, $startDate = null, $endDate = null)
Why you have used `1` as default value for $monthToSubtract in the function definition?

2022-11-24 05:39 UTC, rajatsajwan commented on Modules/Project/Entities/Project.php
> +    public function getVelocityForMonthAttribute($monthToSubtract = 1, $startDate = null, $endDate = null)
it is putting error
![Screenshot_20221124_110547](https://user-images.githubusercontent.com/117888235/203702859-09ca564f-1401-4121-a74b-4f354a026a97.png)

2022-11-24 05:40 UTC, rajatsajwan commented on Modules/Project/Entities/Project.php
> +    public function getVelocityForMonthAttribute($monthToSubtract = 1, $startDate = null, $endDate = null)
and sir i put value null then it is working

2022-11-24 05:51 UTC, rajatsajwan commented on Modules/Project/Entities/Project.php
> +    public function getVelocityForMonthAttribute($monthToSubtract = 1, $startDate = null, $endDate = null)
@GauravGusain98  sir please check this

2022-11-24 05:56 UTC, rajatsajwan commented
![Screenshot_20221124_112606](https://user-images.githubusercontent.com/117888235/203705233-d22d019e-6af5-4702-813f-88fd8358adcc.png)

2022-11-24 05:56 UTC, rajatsajwan commented
![Screenshot_20221124_112625](https://user-images.githubusercontent.com/117888235/203705291-2611e0d7-1a23-43f7-9911-8ab12d2f258d.png)

2022-11-24 06:38 UTC, GauravGusain98 commented
The velocites are not matching 
<img width="851" alt="Screenshot 2022-11-24 at 12 04 28 PM" src="https://user-images.githubusercontent.com/54376313/203711488-924261cd-d428-469a-9f26-0811734636d5.png">

2022-11-24 06:40 UTC, rajatsajwan commented
velocity is of 18 days 
![Screenshot_20221124_112625](https://user-images.githubusercontent.com/117888235/203711854-27e02b8c-d396-4412-a2e6-2b0e26ba8c3b.png)

2022-11-24 07:02 UTC, rajatsajwan commented
@GauravGusain98 sir please review

2022-11-24 07:03 UTC, rajatsajwan commented
![Screenshot_20221124_123319](https://user-images.githubusercontent.com/117888235/203715910-0e8a9d1a-3505-426d-8068-5ef9557d063f.png)
![Screenshot_20221124_123258](https://user-images.githubusercontent.com/117888235/203715942-2e57a37d-19b1-489b-ba8a-9526045dc243.png)

2022-11-24 07:28 UTC, GauravGusain98 requested changes
Please check the comment.

2022-11-24 07:28 UTC, GauravGusain98 commented on Modules/Project/Resources/views/index.blade.php
> +                                            class="{{ $textColor }} font-weight-bold">{{ $project->getVelocityForMonthAttribute($monthToSubtract=null, $startDate = null , $endDate = null ) . ' (' . $
This calculation was correct, you don't need to do changes here. The issue was only on the FTE page velocity. So just fix that function. 

Try figuring out how that function is working and see why the FTE is not coming correct there.

2022-11-24 07:59 UTC, rajatsajwan commented
sir , please  check now

2022-11-24 10:16 UTC, rajatsajwan commented
@GauravGusain98 sir ,please check now

2022-11-24 11:25 UTC, GauravGusain98 requested changes
Please check the comments

2022-11-24 11:25 UTC, GauravGusain98 commented on Modules/Project/Entities/Project.php
> +        return $this->getExpectedHoursInMonthAttribute($startDate, $endDate) ? round($this->getHoursBookedForMonth($monthToSubtract, $startDate, $endDate) / ($this->getCurrentExpectedHoursAttribute()
Why dividing by `$this->getCurrentExpectedHoursAttribute()`? This will give you the expected hours for current month but in case we want to calculate the velocity for previous months then we wanted to get the expected hours for month instead of the current month. 

For eg. Suppose, here is the velocity trend for a project 

Sep
    velocity - 0.94          
    Expected hours - 176
Oct
    velocity - 0.6
    Expected hours - 176
Nov
    velocity - 0.6          
    Expected hours - 150
    
So if we want to calculate the velocity for September then we will use `getExpectedHoursInMonthAttribute($startDate, $endDate)` function. 

But if we want to use current month velocity only then we will use `getCurrentExpectedHoursAttribute()` function. 

In the FTE page we wanted to see the velocity for different month so we can't use the current months related functions. Therefore we have to use the generic functions using which we can find the velocity or expected hours for a particular month.

2022-11-25 08:59 UTC, rajatsajwan commented
![Screenshot_20221125_142822](https://user-images.githubusercontent.com/117888235/203941260-1ffdc275-86ce-4d79-bb11-9af669cff643.png)

2022-11-25 09:00 UTC, rajatsajwan commented
![Screenshot_20221125_142942](https://user-images.githubusercontent.com/117888235/203941469-3393fb5b-9446-4975-af03-2b264a54d759.png)

2022-11-25 09:00 UTC, rajatsajwan commented
@GauravGusain98 sir , ye logic sahi h?

2022-11-25 09:09 UTC, rajatsajwan commented
![Screenshot_20221125_143743](https://user-images.githubusercontent.com/117888235/203943076-ed335681-44fa-4fa0-9a2b-24f2a839ab0c.png)
![Screenshot_20221125_143701](https://user-images.githubusercontent.com/117888235/203943100-1190e437-9366-481f-a816-5a32cd80d125.png)
![Screenshot_20221125_143717](https://user-images.githubusercontent.com/117888235/203943115-caec05cf-d015-4171-b023-9c0eaeb7830b.png)

2022-11-25 09:38 UTC, rajatsajwan commented
![Screenshot_20221125_150750](https://user-images.githubusercontent.com/117888235/203948671-8027b05d-7cf4-473c-b803-63906fbb2e96.png)
![Screenshot_20221125_150726](https://user-images.githubusercontent.com/117888235/203948685-f1185019-98ea-4593-a1bc-c65f49599e92.png)

2022-11-25 09:39 UTC, rajatsajwan commented
@GauravGusain98 sir , is this logic is correct

2022-11-25 09:39 UTC, rajatsajwan commented
@GauravGusain98 sir , is this logic is correct??

2022-11-25 09:50 UTC, rajatsajwan commented
@GauravGusain98 please review and reply

2022-11-29 08:03 UTC, GauravGusain98 requested changes
Please check the comment

2022-11-29 08:03 UTC, GauravGusain98 commented on Modules/Project/Entities/Project.php
> +        if (($currentmonth == $usermonth) && ($currentyear == $useryear)) {
This check is not needed. 

`$this->getExpectedHoursInMonthAttribute($startDate, $endDate)` function should return the correct value if the user month and current month are the same.

2022-11-29 08:03 UTC, GauravGusain98 commented on Modules/Project/Entities/Project.php
> +        if (($currentmonth == $usermonth) && ($currentyear == $useryear)) {
So, the definition of `$this->getExpectedHoursInMonthAttribute($startDate, $endDate)` should be fixed. In your current implementation you are again using `$this->getCurrentExpectedHoursAttribute()` function which will show correct value for current month but for old months we are not sure if the velocity is coming correct. 

So you need to fix the `$this->getExpectedHoursInMonthAttribute($startDate, $endDate)` function

2022-11-30 11:06 UTC, GauravGusain98 requested changes
LGTM. Left a minor suggestion

2022-11-30 11:06 UTC, GauravGusain98 commented on Modules/Project/Entities/Project.php
> +        $daysInMonth = count($this->getWorkingDaysList($startDate, $endDate)) - 1;
You don't need to pass `config('constants.timezone.indian')` as the default the timezone is set in .env and we have set it to IST in the application

```suggestion
        $currentMonth = today()->format('m');
        $currentYear = today()->format('y');
        $projectMonth = $startDate->format('m');
        $projectYear = $startDate->format('y');
        if (($currentMonth == $projectMonth) && ($currentYear == $projectYear)) {
            $endDate = today();
        }
        $daysInMonth = count($this->getWorkingDaysList($startDate, $endDate)) - 1;
```

2022-11-30 11:21 UTC, GauravGusain98 approved these changes
LGTM

2023-01-11 13:45 UTC, merged