adding techstack functionality store in database
ColoredCow/portal pull request #2649
Opened 2022-11-22 14:32 UTC by kanuj365

Targets #2506

### Description
- We need a input box for multiple techstack and that techstack store in database.

### Checklist:

- [x] I have performed a self-review of my own code.

2022-11-23 05:18 UTC, gautam071 requested changes
left some comments

2022-11-23 05:18 UTC, gautam071 commented on Modules/Project/Config/config.php
> +    'stack' => ['C', 'C++', ' C#', 'Java', 'Flask', 'Elixir', 'Angular', 'Mongodb', 'Koa', 'Phoenix', 'ExpressJS', 'Asp .NET', 'Spring Boot', 'Django', 'Ruby on Rails', 'CakePHP', 'Javascript', 'boot
Why hard code the tech stacks? 
Can we manually get it from the user

2022-11-23 05:18 UTC, gautam071 commented on Modules/Project/Http/Requests/ProjectRequest.php
> +                            new TeamMemberRule(),
revet indentation

2022-11-23 05:18 UTC, gautam071 commented on Modules/Project/Resources/views/subviews/create-project-details.blade.php
> +                <input type="text" class="form-control" name="name" id="name" placeholder="Enter project name" required="required" value="{{ old('name') }}">
revet the changes

2022-11-23 05:18 UTC, gautam071 commented on Modules/Project/Resources/views/subviews/create-project-details.blade.php
> +                <input type="url" class="form-control" name="effort_sheet_url" id="effort_sheet_url" placeholder="Enter effort sheet url" value="{{ old('effort_sheet_url') }}">
revet the changes

2022-11-23 05:18 UTC, gautam071 commented on Modules/Project/Resources/views/subviews/create-project-details.blade.php
> +                <input type="url" class="form-control" name="google_chat_webhook_url" id="google_chat_webhook_url" placeholder="Enter Google Chat Webhook URL" value="{{ old('google_chat_webhook_url')
revet the changes

2022-11-23 05:18 UTC, gautam071 commented on Modules/Project/Resources/views/subviews/create-project-details.blade.php
> +                <input type="date" class="form-control" name="start_date" id="startDate" value="{{ old('start_date') }}">
revet the changes

2022-11-23 05:18 UTC, gautam071 commented on Modules/Project/Services/ProjectService.php
> +            ->paginate(config('constants.pagination_size'));
revet the changes

2022-11-23 05:18 UTC, gautam071 commented on Modules/Project/Services/ProjectService.php
> +                ];
revet the changes

2022-11-23 05:18 UTC, gautam071 commented on Modules/Project/Services/ProjectService.php
> +                        'email' => $teamMember->email,
revet the changes

2022-11-24 05:56 UTC, gautam071 commented
@kanuj365 Can you add some screenshots of how the feature looks?

2022-11-24 06:06 UTC, gautam071 commented
@kanuj365 Read the solution properly in the issue 

```
Solution:

1. We can add a new tag with the name: tech: node, tech:laravel, tech: PHP and things like that.
2. We need an ability to add those tags to project.
```

1. You need to create a tech stack button, via there create a tag which user enters. 
2. then the tags can be reused to any other project

This is what my understanding is. 
Just let me know if you have any doubts

2022-11-29 07:05 UTC, kanuj365 commented
![input_techstack](https://user-images.githubusercontent.com/68420715/204461611-477e4536-2367-4e51-a578-acca047e6bf1.png)
![tag_techstack](https://user-images.githubusercontent.com/68420715/204461620-d535e197-c67f-4d48-8d27-cf50b3c8cd11.png)

2022-11-30 05:34 UTC, gautam071 requested changes
left some comment

Also, why are we using 2 different tables for the tech stacks?

2022-11-30 05:34 UTC, gautam071 commented on Modules/Project/Http/Controllers/ProjectController.php
> +        return view('project::create', compact('clients', 'total_tech_stack'));
why did you use the `compact`?

2022-11-30 05:34 UTC, gautam071 commented on Modules/Project/Resources/views/index.blade.php
> +                                        @if ($project->name==$key)
Can we get the tech from the project?

Learn about the relations in laravel

2022-11-30 05:34 UTC, gautam071 commented on Modules/Project/Http/Controllers/ProjectController.php
> +        $total_tech_stack = $clients_tech[1];
Don't hard code

2022-12-02 11:36 UTC, kanuj365 commented
![image](https://user-images.githubusercontent.com/68420715/205284303-3e1ac77c-eeac-4cc7-8857-be271f9c2115.png)

2022-12-05 05:13 UTC, gautam071 requested changes

2022-12-05 05:13 UTC, gautam071 commented on Modules/Project/Resources/views/subviews/create-project-details.blade.php
> +
remove this

2022-12-05 05:13 UTC, gautam071 commented on Modules/Project/Resources/views/subviews/create-project-details.blade.php
> +                </datalist>
indentation

2022-12-05 05:13 UTC, gautam071 commented on Modules/Project/Resources/views/subviews/create-project-details.blade.php
> +                <datalist id="techstacks">
also what is the use of the datalist

2022-12-05 05:13 UTC, gautam071 commented on Modules/Project/Resources/views/index.blade.php
> +                                @if ($project->name == $tech_names['name'])
why this check?

2022-12-05 05:31 UTC, kanuj365 commented on Modules/Project/Resources/views/index.blade.php
> +                                @if ($project->name == $tech_names['name'])
![image](https://user-images.githubusercontent.com/68420715/205556617-22b01b37-83a5-4679-905a-95d80fe95f08.png)
if I'm not using condition then it's showing like this because one client have many projects changes accordingly same that's why i'm apply this conditon.

2022-12-05 05:34 UTC, kanuj365 commented on Modules/Project/Resources/views/subviews/create-project-details.blade.php
> +                <datalist id="techstacks">
actually i'm using datalist because of, that is a popup which shows all technology which have been used, but you right there is not any uses or not selected many tech by the users so i remove that.

2022-12-05 06:27 UTC, kanuj365 commented on Modules/Project/Resources/views/index.blade.php
> +                                @if ($project->name == $tech_names['name'])
but i removed foreach and if condition

2023-05-08 12:17 UTC, closed without merging