add Features to Media Module
ColoredCow/portal pull request #2668
Opened 2022-11-30 11:23 UTC by ShivanshGairola

Targets #2599

### Description
Added Features to Media Module

### Checklist:
- [ ] I have performed a self-review of my own code.

2022-12-20 05:54 UTC, GauravGusain98 requested changes
Please check the comments. The feedbacks mostly include formatting issues. I'll do another round of review once these issues are fixed. Will also need some help in the testing of the workflow on local

2022-12-20 05:54 UTC, GauravGusain98 commented on Modules/Media/Resources/views/media/index.blade.php
>                          </td>
Why you have used `<td>` tag when there is no table. Also remove the class attribute if there is no class we are using

2022-12-20 05:54 UTC, GauravGusain98 commented on Modules/Media/Resources/views/media/index.blade.php
> +                    @if(pathinfo($row->file_url, PATHINFO_EXTENSION) == 'jpg' || pathinfo($row->file_url, PATHINFO_EXTENSION) == 'jpeg' || pathinfo($row->file_url, PATHINFO_EXTENSION) == 'PNG' )
Why only `PNG` is in uppercase, while `jpg` and `jpeg` are lowercase? Can you confirm if the syntax is correct

2022-12-20 05:54 UTC, GauravGusain98 commented on Modules/Media/Http/Controllers/MediaController.php
> +                $postData = [
Please correct the indentation

2022-12-20 08:12 UTC, ShivanshGairola commented on Modules/Media/Resources/views/media/index.blade.php
> +                    @if(pathinfo($row->file_url, PATHINFO_EXTENSION) == 'jpg' || pathinfo($row->file_url, PATHINFO_EXTENSION) == 'jpeg' || pathinfo($row->file_url, PATHINFO_EXTENSION) == 'PNG' )
Sir png image have extension in uppercase only.thats why used in upper case

2022-12-21 05:50 UTC, GauravGusain98 commented on Modules/Media/Http/Controllers/MediaController.php
> +                $postData = [
This is not implemented

2022-12-21 05:57 UTC, ShivanshGairola commented on Modules/Media/Http/Controllers/MediaController.php
> +                $postData = [
After implementing it failing in CI check.It is showing larstan error

2022-12-21 06:10 UTC, GauravGusain98 requested changes
- The text of this button is not updated.
    <img width="342" alt="image" src="https://user-images.githubusercontent.com/54376313/208833518-f54782de-f2ef-4597-8c72-ae1c145e1877.png">
- The modal title and button text is also not updated
    <img width="515" alt="image" src="https://user-images.githubusercontent.com/54376313/208833984-8387eaa4-a38c-41a2-93be-9d9674dc323a.png">
- On Saving the media the image is not getting saved.

2022-12-21 11:30 UTC, GauravGusain98 commented on Modules/Media/Http/Controllers/MediaController.php
> +                $postData = [
ok

2022-12-22 07:34 UTC, GauravGusain98 commented
The image is not getting saved and is not getting displayed on the page. Please test it once in your system.

2023-04-07 12:28 UTC, closed without merging