Origin/feature/employee work history #2652
ColoredCow/portal pull request #2689
Opened 2022-12-08 11:14 UTC by kanuj365

Targets #2655 

### Description

### Checklist:

- [ ] I have performed a self-review of my own code.

2022-12-11 13:22 UTC, kanuj365 commented
![workhistory](https://user-images.githubusercontent.com/68420715/206906095-b654bc03-0583-45a9-b533-aaed90ed93a9.png)
![techstacktab](https://user-images.githubusercontent.com/68420715/206906117-ddb1a3c0-3735-42bb-acba-91cafe7a0a3f.png)
![workhistory link](https://user-images.githubusercontent.com/68420715/206906144-ea89516d-3756-4a57-bdcc-32a7b41c7719.png)

2022-12-12 06:45 UTC, P4NK4J requested changes
@kanuj365 Work history link was supposed to be added inside the basic details page. You have added it on the employee listing, please make that update and assign for review

2022-12-12 06:47 UTC, P4NK4J commented
This is how the data is appearing for me, can you please fix the alignment ?
<img width="1363" alt="image" src="https://user-images.githubusercontent.com/35001775/206979003-e35a5a19-cf77-45ff-943e-15da853b5b60.png">

2022-12-12 06:49 UTC, P4NK4J commented
Also, the client name is appearing inside techstack tab.
the techstack, cell can be formatted as
Language: DATA
Framework: DATA
Database: DATA
Hosting: DATA

Let me know if you have any questions

2022-12-14 04:59 UTC, kanuj365 commented
![image](https://user-images.githubusercontent.com/68420715/207509842-a86b3c2c-a3f4-4750-a8cc-f8301fac3f24.png)

2022-12-14 07:00 UTC, P4NK4J requested changes
@kanuj365 There are unused blocks popping out of the table, please fix them. Also, Work History Title is not aligned with the table, they both should be in same vertical alignment. Please take a look
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/35001775/207527675-048bfa42-1a67-4c40-bb44-69ea3c5751ea.png">

2022-12-15 09:51 UTC, P4NK4J requested changes
Left some comments, please check

2022-12-15 09:51 UTC, P4NK4J commented on resources/views/hr/employees/employee-work-history.blade.php
> +</div>
Indentation is off

2022-12-15 09:51 UTC, P4NK4J commented on Modules/Project/Resources/views/subviews/edit-project-techstack-details.blade.php
> +        <div id="project_techstack_form">
Id should be in camelCase

2022-12-15 09:51 UTC, P4NK4J commented on Modules/Project/Resources/views/edit.blade.php
> +                        role="tab" aria-selected="false">Project TechStack</a>
```suggestion
                        role="tab" aria-selected="false">Project Techstack</a>
```

2022-12-15 09:51 UTC, P4NK4J commented on Modules/HR/Http/Controllers/EmployeeController.php
> +        $employeesDetails = ProjectTeamMember::where('team_member_id', $employee->user_id)->get()->unique('project_id');
What's the use of unique here ?

2022-12-15 10:47 UTC, kanuj365 commented on Modules/Project/Resources/views/subviews/edit-project-techstack-details.blade.php
> +            <input type="hidden" value="project_techstack" name="update_section">
![image](https://user-images.githubusercontent.com/68420715/207838241-e2e2df7e-9251-4945-b8f1-09156b096149.png)
1->here you can see a switch case where "updatesection" and "project techstack" is used inside the input.
2-> if you not use type hidden then input tag is visible on page unnecessarily.

2022-12-15 10:53 UTC, kanuj365 commented on Modules/HR/Http/Controllers/EmployeeController.php
> +        $employeesDetails = ProjectTeamMember::where('team_member_id', $employee->user_id)->get()->unique('project_id');
Here I'm getting duplicate project_id so that's why i'm using here

2022-12-16 12:18 UTC, P4NK4J approved these changes
Minor suggestion else looks good.

2022-12-16 12:18 UTC, P4NK4J commented on resources/views/hr/employees/employee-work-history.blade.php
> +          $value='Not_Available';
```suggestion
          $value='Not Available';
```

2022-12-16 12:24 UTC, P4NK4J commented on resources/views/hr/employees/employee-work-history.blade.php
> +          $value='Not_Available';
```suggestion
          $data = $details->project;
          $projectmeta = $data->meta->pluck('value', 'key');
          $placeholder ='Not_Available';
```

2022-12-16 15:08 UTC, merged