Origin/fix/streamline application evaluation
ColoredCow/portal pull request #2692
Opened 2022-12-10 18:27 UTC by rajatsajwan

Targets #2672

### Description
Reject Option in Resume Screening Evaluation Dialog

### Checklist:

- [ ] I have performed a self-review of my own code.

2022-12-11 14:50 UTC, rajatsajwan commented
![Screenshot (32)](https://user-images.githubusercontent.com/117888235/206910587-26bcfc9e-8212-402c-b835-7c315578d518.png)
![Screenshot (33)](https://user-images.githubusercontent.com/117888235/206910599-9e2cfda7-38b9-4582-8682-d4ebac730681.png)
![Screenshot (34)](https://user-images.githubusercontent.com/117888235/206910640-5c5f7096-06f0-4b19-98b8-14c8648f8505.png)

2022-12-12 04:42 UTC, rajatsajwan commented
![Screenshot (35)](https://user-images.githubusercontent.com/117888235/206962271-99a828d7-dfef-4e1d-9699-e84fc771e6a2.png)
sir , these are the code changes.

2022-12-12 05:15 UTC, P4NK4J requested changes
Left a comment, please check

2022-12-12 05:15 UTC, P4NK4J commented on resources/views/hr/application/evaluation-form.blade.php
> +                        </script>
Rather than having a script block here, is it possible to include the app.js file ? We do have a single js file loading on the browser. If you can figure out a mechanism on how the JS can be included here, that would work.

2022-12-14 06:58 UTC, P4NK4J requested changes
Left some comments, please check

2022-12-14 06:58 UTC, P4NK4J commented on resources/views/hr/application/evaluation-form.blade.php
> +                        </script>
Can this script go into app.js file ?

2022-12-14 06:58 UTC, P4NK4J commented on resources/views/hr/application/evaluation-form.blade.php
> +                        {{-- @if ($option["name"]=="No"){ --}}
Let's remove the commented code form here

2022-12-14 06:58 UTC, P4NK4J commented on resources/views/hr/application/evaluation-form.blade.php
> +                            <button type="button" class="btn btn-outline-danger ml-2 d-none show-evaluation-stage1" id="rejectButton" @click="rejectApplication()">
Why this button has show-evaluation-stage1 as a class name, its completely different from the functioning of this button. Can you make selector from the ID, also keep a specific id here, the original reject button might have the same.

2022-12-14 06:58 UTC, P4NK4J commented on resources/js/app.js
> +	});
I find this code repetitive, can you make it a generic block and use in both the places line 373 and here

2022-12-16 12:29 UTC, P4NK4J requested changes
<img width="832" alt="image" src="https://user-images.githubusercontent.com/35001775/208098272-a80fb8ff-0bf8-4f7b-a054-440c30422a72.png">
<img width="798" alt="image" src="https://user-images.githubusercontent.com/35001775/208098300-e3eefe98-22bb-4b52-9341-bfb52375822b.png">
Two comments, 
1. Once No is selected in parent option, the other questions should no appear
2. Upon selecting Yes, next button is not appearing, only reject option is present. 

Please fix the issues, if Yes is selected on first question, there should be an option to move next, while on selecting No, none other option should populate.

2022-12-16 15:05 UTC, rajatsajwan commented
![Screenshot (36)](https://user-images.githubusercontent.com/117888235/208127067-fa1fc763-a3ec-427a-9440-6cafff939ce8.png)
![Screenshot (37)](https://user-images.githubusercontent.com/117888235/208127082-9a958d7b-7bfa-4f8b-b409-e42c305acc87.png)

2022-12-17 12:17 UTC, rajatsajwan commented
![Screenshot (40)](https://user-images.githubusercontent.com/117888235/208241464-9c3c51dd-de1d-4ce7-8c9c-5d8c53f24c5f.png)
![Screenshot (41)](https://user-images.githubusercontent.com/117888235/208241470-9c74a58c-8962-4ec8-929d-eee291731cb7.png)
Result

2022-12-19 05:50 UTC, P4NK4J requested changes
Left a comment, please check.

2022-12-19 05:50 UTC, P4NK4J commented on resources/js/app.js
> +});
This is hardcoded and may change if we change the label of the question. Please see how the resume feeling questions are fetched and perform that operation dynamically .

2022-12-20 05:59 UTC, rajatsajwan commented on resources/js/app.js
> +});
hello sir, @P4NK4J i can not find resume feeling questions?

2023-01-10 07:37 UTC, P4NK4J reviewed
Let's remove package.json from the PR, and left a question for you

2023-01-10 07:37 UTC, P4NK4J commented on Modules/HR/Http/Controllers/EvaluationController.php
> +            if ($option) {
what's the use of conditional here ? if there is no option, the loop will throw an error. Shouldn't it be applied before the loop ?

2023-01-11 13:44 UTC, P4NK4J approved these changes

2023-01-11 13:45 UTC, merged