Team_member_getting_removed_when_halted
ColoredCow/portal pull request #2699
Opened 2022-12-17 05:53 UTC by ShivanshGairola

Targets #2695 

### Description
fixed team member getting removed when status changed to halted.

### Checklist:
- [ ] I have performed a self-review of my own code.

2022-12-19 05:58 UTC, GauravGusain98 commented on Modules/Project/Entities/Project.php
> +        return $this->hasMany(ProjectTeamMember::class);
This function is being used at many places. Please don't modify it.

2022-12-19 05:58 UTC, GauravGusain98 commented on Modules/Project/Resources/views/show.blade.php
> +                                        @if($project->teamMembers->first() != null)
This is also not required.

2022-12-19 05:58 UTC, GauravGusain98 requested changes
Please check the comments

2022-12-20 06:41 UTC, GauravGusain98 requested changes
Please check the comment

2022-12-20 06:41 UTC, GauravGusain98 commented on Modules/Project/Services/ProjectService.php
> +            $project->client->update(['status' => 'active', 'halted']);
The syntax is incorrect. Did you test it locally? Also this line will update the status of client instead of project.

2022-12-20 06:47 UTC, ShivanshGairola commented on Modules/Project/Services/ProjectService.php
> +            $project->client->update(['status' => 'active', 'halted']);
Tested it locally it is working.

2022-12-20 07:12 UTC, ShivanshGairola commented on Modules/Project/Services/ProjectService.php
> +            $project->client->update(['status' => 'active', 'halted']);
It is working locally.

2022-12-20 07:14 UTC, GauravGusain98 commented on Modules/Project/Services/ProjectService.php
> +            $project->client->update(['status' => 'active', 'halted']);
Not sure how its working but anyhow the implementation is incorrect. You don't have to mark the client as halted.

2022-12-20 07:15 UTC, GauravGusain98 commented on Modules/Project/Services/ProjectService.php
> +            $project->client->update(['status' => 'active', 'halted']);
Client only has 2 status `active` and `inactive`

2022-12-21 06:38 UTC, GauravGusain98 approved these changes
LGTM

2022-12-26 05:41 UTC, merged