Feature/resource pipeline model in a project #2657
ColoredCow/portal pull request #2720
Opened 2022-12-21 12:38 UTC by kanuj365

Targets #{ISSUE_ID}

### Description

### Checklist:

- [ ] I have performed a self-review of my own code.

2022-12-26 05:47 UTC, P4NK4J requested changes
Left some comments, please check

2022-12-26 05:47 UTC, P4NK4J commented on Modules/Project/Database/Factories/ProjectTeamMemberFactory.php
> -            'designation' => array_rand(config('project.designation')),
Why this is removed ? I guess this was to seed the data in designations table for the first time

2022-12-26 05:47 UTC, P4NK4J commented on Modules/Project/Resources/views/index.blade.php
> -                                                title="{{ $teamMember->user->name }} - {{ config('project.designation')[$teamMember->designation] }} <br>    Efforts: {{ $teamMember->current_actual_ef
Why team member designation is removed from here ?

2022-12-26 05:47 UTC, P4NK4J commented on database/migrations/2022_12_24_125621_drop_designation_from_project_team_members.php
> +        $this->getDesignationid();
What's the use of this line, if this is used to migrate existing designation data, can we rename this function to something meaningful ?

2022-12-26 06:17 UTC, kanuj365 commented on Modules/Project/Database/Factories/ProjectTeamMemberFactory.php
> -            'designation' => array_rand(config('project.designation')),
yes when i'm using this it's showing error in run seeders because it was searching that column so that's why i removed that.
that error->
![image](https://user-images.githubusercontent.com/68420715/209509674-c107929c-b025-4116-895d-2fd717b0e529.png)

2022-12-26 07:01 UTC, kanuj365 commented on Modules/Project/Resources/views/index.blade.php
> -                                                title="{{ $teamMember->user->name }} - {{ config('project.designation')[$teamMember->designation] }} <br>    Efforts: {{ $teamMember->current_actual_ef
it's requirement of 3rd phase of task ->
On the project listing page, we would like to remove the designation of a member from the tooltip.

2022-12-26 07:25 UTC, kanuj365 commented on database/migrations/2022_12_24_125621_drop_designation_from_project_team_members.php
> +        $this->getDesignationid();
i called that function because, before remove that column it migrate all designation id

2022-12-26 09:50 UTC, P4NK4J requested changes
Left a comment please check

2022-12-26 09:50 UTC, P4NK4J commented on Modules/Project/Database/Factories/ProjectTeamMemberFactory.php
> -            'designation' => array_rand(config('project.designation')),
You need to find out solution to fix this, rather than removing the line of codes. Please do that

2022-12-26 09:51 UTC, P4NK4J commented
@kanuj365 Also there was requirement to replace the dropdown items and bring them from database in project team members page. You have simply added the items to config and not modified the dropdown. Please read the requirements and make changes accordingly

2022-12-28 06:15 UTC, P4NK4J requested changes
Left some comments, please check.

2022-12-28 06:15 UTC, P4NK4J commented on Modules/HR/Database/Seeders/ResumeScreeningEvaluationSeeder.php
Why this code is commented out ? will this not impact the workflow if someone runs the seeder first time ?

2022-12-28 06:15 UTC, P4NK4J commented on Modules/Project/Database/Factories/ProjectTeamMemberFactory.php
> +            'designation_id' =>  HrJobDesignation::where('designation', array_rand(config('project.designation')))->value('id'),
If there are no designations in the table how this will work ?

2022-12-28 06:15 UTC, P4NK4J commented on Modules/HR/Database/Seeders/HRDatabaseSeeder.php
> +        $this->call(HrDesignationTableSeeder::class);
Designations have domains column in the table, will changing the sequence of the seeders would be impacted on a fresh database here ?

2022-12-28 07:28 UTC, kanuj365 commented on Modules/HR/Database/Seeders/ResumeScreeningEvaluationSeeder.php
when i run module:Seed then in this file created duplicate id. it's impacted module:Seed for that i removed this.

2022-12-28 07:30 UTC, kanuj365 commented on Modules/HR/Database/Seeders/HRDatabaseSeeder.php
> +        $this->call(HrDesignationTableSeeder::class);
No, it was last changes.

2022-12-28 09:22 UTC, kanuj365 commented on Modules/Project/Database/Factories/ProjectTeamMemberFactory.php
> +            'designation_id' =>  HrJobDesignation::where('designation', array_rand(config('project.designation')))->value('id'),
1 - if there is no designation then it will return null,

2022-12-28 09:39 UTC, kanuj365 commented
![image](https://user-images.githubusercontent.com/68420715/209790051-ef9ae408-0b27-4194-8fb1-07e3c1ae1963.png)
![image](https://user-images.githubusercontent.com/68420715/209791550-bd93403f-c2fb-485f-a372-3b3137cda116.png)

2023-04-07 12:28 UTC, closed without merging