Inactive client not getting shown when creating a new project
ColoredCow/portal pull request #2726
Opened 2022-12-23 07:43 UTC by race45

Targets #2700 

### Description

    when we create a new project for inactive client . in select client option it show active client detail . I changed it and show all 
     the inactive clients.
### Checklist:

- [ ] I have performed a self-review of my own code.

2022-12-23 09:15 UTC, GauravGusain98 requested changes
Please check the comment

2022-12-23 09:15 UTC, GauravGusain98 commented on Modules/Project/Services/ProjectService.php
> +                       ->orderBy('name')->get();
1. There are only 2 status for client `inactive` or `active`. If you want both then why you are using where clause? It should work without any of the where clause
2. Its possible that this function is used at other places as well in the code where only active clients are needed. If you make any changes in this function definition then it will affect all other places. 
3. You have now 2 options:
    - Create a new function that will give you only active clients.
    - Modify this function in such a way that can you can pass some parameters to it that will decide if you want active client, inactive clients or all clients.  But the default behavior of this function should be the same as of now so that it does not affect other places.

Option 2 looks good as that way the code will be optimize and we don't have to make 2 functions for status filter. Please implement it as suggested

2022-12-23 12:45 UTC, GauravGusain98 commented on Modules/Project/Services/ProjectService.php
> +    public function getClients($status = 'active')
This is correct now

2022-12-23 12:48 UTC, GauravGusain98 commented on Modules/Project/Services/ProjectService.php
> +        }
Also while fetching clients, I am not sure why you are using the `where` clause. Without a where clause it will automatically fetch all the clients, right?

2022-12-26 05:35 UTC, GauravGusain98 requested changes
Please check the comments

2022-12-26 05:35 UTC, GauravGusain98 commented on Modules/Project/Services/ProjectService.php
> +        }
It's good practice to make our code as optimized as we can. This piece of code can be more optimized by reducing the conditions like this:

If status == `all` then fetch all clients
else fetch clients where status = `$status`

2022-12-26 05:37 UTC, GauravGusain98 commented on Modules/Project/Services/ProjectService.php
> +        }
For your information, the error in the CI checks is telling to add a blank line before return statement. So you need to add a blank line before each return statement. Note the there should not be any spaces in the blank line, else the CI checks will again throw error

2022-12-26 08:22 UTC, GauravGusain98 requested changes
Left a comment please check

2022-12-26 08:22 UTC, GauravGusain98 commented on Modules/Project/Services/ProjectService.php
> +            $client = Client::where('status', 'active')->orWhere('status', 'inactive')->orderBy('name')->get();
This is still not fixed

2022-12-26 08:24 UTC, race45 commented on Modules/Project/Services/ProjectService.php
> +            $client = Client::where('status', 'active')->orWhere('status', 'inactive')->orderBy('name')->get();
I am sorry, I missed it.

2022-12-26 08:28 UTC, GauravGusain98 approved these changes
LGTM

2022-12-26 08:32 UTC, merged