Add a dropdown field Country on the Add Client page for the country,e…
ColoredCow/portal pull request #2738
Opened 2022-12-28 08:13 UTC by race45

Targets issue  #2722 

### Description

Add a dropdown field Country on the Add Client page for the country similar to what we have for Parent Organization.
Create an entry for the new client in the client_addresses table and store the country value in the table.

### Checklist:

- [x] I have performed a self-review of my own code.

2022-12-28 08:33 UTC, GauravGusain98 requested changes
Please check the comments

2022-12-28 08:33 UTC, GauravGusain98 commented on Modules/Client/Http/Controllers/ClientController.php
> +        $countries = Country::all();
This should come from the clientService. Then you don't have to add it separately inside the return() function as you have done now because the data is directly coming from clientService.

2022-12-28 08:33 UTC, GauravGusain98 commented on Modules/Client/Resources/views/subviews/create-client-details.blade.php
> +    <div class="form-row" action="{{url('/')}}/ClientController@store" method="posts">
Why you have added `action` and `method` here? The form was getting saved earlier also. I think it was getting submitted using Javascript and not using PHP. 

I think it should work without adding action also.

2022-12-28 08:33 UTC, GauravGusain98 commented on Modules/Client/Resources/views/subviews/create-client-details.blade.php
> +            <select name="country_id" id="country_id" class="form-coutrol">
Check the naming convention used in portal from [here](https://github.com/ColoredCow/portal/blob/master/docs/variable-naming-convention.md)
```suggestion
            <select name="country_id" id="countryId" class="form-control">
```

2022-12-28 08:36 UTC, GauravGusain98 commented on Modules/Client/Resources/views/subviews/create-client-details.blade.php
> +    <div class="form-row" action="{{url('/')}}/ClientController@store" method="posts">
If its not working without action then you need to find how the form was getting submitted earlier. You can look at submit button below and search whole codebase for the id that is used in submit button. We might have written a JS code somewhere that will use the Id to submit the form

2022-12-28 12:37 UTC, GauravGusain98 commented
It's not working. I've created a new client and added the country to it but in client details, the country was not showing. Also in database `client_addresses` table, no entry corresponding to that client was created.
<img width="1251" alt="image" src="https://user-images.githubusercontent.com/54376313/209813278-eca2e876-0299-4da2-9fdc-39f00f37e9f1.png">

2023-01-13 07:03 UTC, GauravGusain98 commented on Modules/Client/Http/Controllers/ClientController.php
> +                               ->get();
This is not needed as we don't want to change the view file

2023-01-13 07:06 UTC, GauravGusain98 commented on Modules/Client/Services/ClientService.php
> +    public function edit($client, $section, $clientAddress)
Why changes are done to edit function? We just need to do changes for creating a client. Functionality to update country by editing the client details is already present and working correct. So this should not be changed at all.

2023-01-13 07:08 UTC, GauravGusain98 commented on Modules/Client/Services/ClientService.php
> +        $clientAddress->client_id = $data['client_id'];
Are you sure that this client_id is same as the id of the client that is created? We also have a client_id column in client table.

2023-01-13 07:09 UTC, GauravGusain98 commented on database/migrations/2023_01_05_195430_add_country_field_to_clients.php
> +<?php
This file is not needed. Rollback the changes that have been done due to this file in your database and then remove this file

2023-01-13 07:09 UTC, GauravGusain98 commented on database/migrations/2023_01_05_204310_rename_country_in_clients_table.php
> +
This is also not needed. rollback the changes if any were made in database due to this file and then delete this file

2023-01-13 07:09 UTC, GauravGusain98 commented on database/migrations/2023_01_09_121655_drop_column_country_id_from_clients_table.php
> +
File not needed

2023-01-13 07:26 UTC, race45 commented on Modules/Client/Services/ClientService.php
> +        $clientAddress->client_id = $data['client_id'];
In `clients` & `client_addresses` both table have `client_id`. so which client_id I will use

2023-01-13 07:29 UTC, GauravGusain98 commented on Modules/Client/Services/ClientService.php
> +        $clientAddress->client_id = $data['client_id'];
When you are creating a client did you try to print you are getting $store variable?

2023-01-13 07:39 UTC, race45 commented on Modules/Client/Services/ClientService.php
> +        $clientAddress->client_id = $data['client_id'];
yes, i was print $store variable into that only client detail had passed. client_addresses will not pass with $store variable.

2023-01-13 13:49 UTC, GauravGusain98 requested changes
Minor suggestions, please have a look

2023-01-13 13:49 UTC, GauravGusain98 commented on Modules/Client/Resources/views/subviews/create-client-details.blade.php
> +                <span data-toggle="tooltip" data-placement="right" title="If this client came via a channel partner then link that client from here."><i class="fa fa-question-circle"></i>&nbsp;</span
I think we don't need this

2023-01-13 13:49 UTC, GauravGusain98 commented on Modules/Client/Services/ClientService.php
> +        $store = Client::create($data);
Its good practice to use meaningful variable name. 
```suggestion
        $newClient = Client::create($data);
```

2023-01-13 13:49 UTC, GauravGusain98 commented on Modules/Client/Services/ClientService.php
> +        $clientId = $store->id;
No need to create a variable for this. Directly put value on line 163

2023-01-13 13:54 UTC, race45 commented on Modules/Client/Services/ClientService.php
> +        $clientId = $store->id;
ok.

2023-01-16 04:50 UTC, GauravGusain98 approved these changes
LGTM

2023-01-16 05:48 UTC, merged