Feature/lifetime of job application and escalation#2686
ColoredCow/portal pull request #2742
Opened 2022-12-31 09:42 UTC by kanuj365

Targets #2686

### Description
-  Created a scheduler to send email notifications.
-  Fetched the count of total applications with the status new and in progress was received 15 days before the current time.
-  Created a config variable, for the outdated time period.
-   Sent an email on created email template to hr.

### Checklist:

- [ ] I have performed a self-review of my own code.

2022-12-31 10:48 UTC, kanuj365 commented
![image](https://user-images.githubusercontent.com/68420715/210133960-cac5c9df-00d7-4c94-a63c-4b659466078d.png)

2023-01-01 07:43 UTC, P4NK4J requested changes
Left some comments, please check

2023-01-01 07:43 UTC, P4NK4J commented on resources/views/emails/send-application-lifecycle.php
> +<p>We have a total of <span>{{ $no_of_application }}</span> applications that are outdated and no action is being taken on them.</p>
let's use camel casing for variables here

2023-01-01 07:43 UTC, P4NK4J commented on app/Console/Kernel.php
> +        Lifecycle_of_mail::class,
Naming convention is not correct here as well

2023-01-01 07:43 UTC, P4NK4J commented on Modules/HR/Emails/Lifecycle_of_mail.php
> +class Lifecycle_of_mail extends Command
Please see how laravel classes are written, what are the naming conventions, and update accordingly. Also, check the file name casing

2023-01-01 07:43 UTC, P4NK4J commented on Modules/HR/Emails/Lifecycle_of_mail.php
> +        return Mail::send('emails.send-application-lifecycle', ['no_of_application' => $exceed_date_application_no], function ($messge) use ($email) {
Let's use queues to send the email here

2023-01-01 07:43 UTC, P4NK4J commented on Modules/HR/Emails/Lifecycle_of_mail.php
> +        $email = 'hr@coloredcow.com';
Let's fetch this email address from ENV file, you can refer to other places where its sued.

2023-01-01 07:43 UTC, P4NK4J commented on Modules/HR/Emails/Lifecycle_of_mail.php
> +        $exceed_date_application_no = 0;
Correct naming convention in variables

2023-01-01 07:43 UTC, P4NK4J commented on Modules/HR/Emails/Lifecycle_of_mail.php
> +        $exceed_date_application_no = 0;
what's the use of this variable ? Its name is very confusing, can we rename it to something meaningful ?

2023-01-02 12:06 UTC, kanuj365 commented on Modules/HR/Emails/Lifecycle_of_mail.php
> +        $exceed_date_application_no = 0;
that variable take only those value whose date exceeded the time limit of application submission date.

2023-01-02 12:34 UTC, P4NK4J requested changes
Left some comments, please check

2023-01-02 12:34 UTC, P4NK4J commented on Modules/HR/Config/config.php
> +    ],
This is supposed to be fetched from ENV, just refer to other places how we are using the HR email

2023-01-02 12:34 UTC, P4NK4J commented on app/Console/Kernel.php
> +        LifecyCleOfMail::class,
Did you even test it on your local ? The classname is different here ?

2023-01-02 12:34 UTC, P4NK4J commented on app/Mail/NotifyExceededLifeCycleEmail.php
> +class NotifyExpiredLifeCycleEmail extends Mailable implements ShouldQueue
What's the meaning of this classname ? Does it sound relevant to you ? How about `ApplicationLifeCycleNotifcationEmail`

2023-01-03 09:46 UTC, P4NK4J requested changes
Left some comments, please take a look. Also, add the variable in ENV sample file, so that it can be added in production ENV as well

2023-01-03 09:46 UTC, P4NK4J commented on Modules/HR/Emails/LifeCycleOfMail.php
> +        }
Just see if we can combine this logic in the application query itself, the query should fetch all the applications, whose created date and current date difference is greater than 15 days.

2023-01-03 09:46 UTC, P4NK4J commented on app/Console/Kernel.php
> +        LifeCycleOfMail::class,
Let's rename it to `ApplicationLifeCycleEmailTrigger`

2023-01-03 09:46 UTC, P4NK4J commented on app/Console/Kernel.php
> +        $schedule->command('application:lifecycle')->everyday()->at('08:00');
Let's rename this to `hr:application-lifecycle-email`

2023-04-07 12:28 UTC, closed without merging