Fix the alignment of report tiles in the finance report
ColoredCow/portal pull request #2748
Opened 2023-01-03 08:19 UTC by Akshiteshnaithani

Targets #2688 

### Description
I have Fixed the alignment of report tiles in the finance report.
### Checklist:

- [ ] I have performed a self-review of my own code.

2023-01-03 08:31 UTC, GauravGusain98 requested changes
In you code changes, package.lock.json should not exist as it is not related to the issue. So remove that file from the code changes. 

In case you face issue with this, please take help from anyone near you.

2023-01-03 13:46 UTC, GauravGusain98 requested changes
Minor suggestion. Please check

2023-01-03 13:46 UTC, GauravGusain98 commented on Modules/Report/Resources/views/finance/profit-and-loss/index.blade.php
> +    </div>
The indentation looks incorrect here.

2023-01-04 05:53 UTC, Akshiteshnaithani commented on Modules/Report/Resources/views/finance/profit-and-loss/index.blade.php
> +    </div>
I dont get what do you mean by tiles ? for all box and their inside content padding are same .

2023-01-04 05:57 UTC, GauravGusain98 commented on Modules/Report/Resources/views/finance/profit-and-loss/index.blade.php
> +    </div>
These 2 gap looks different in size, No?
<img width="636" alt="image" src="https://user-images.githubusercontent.com/54376313/210493159-f3e21650-5d65-4c9f-a831-e4fb51c4869d.png">

2023-01-04 07:07 UTC, Akshiteshnaithani commented on Modules/Report/Resources/views/finance/profit-and-loss/index.blade.php
> +    </div>
done

2023-01-04 07:11 UTC, GauravGusain98 approved these changes
LGTM

2023-01-04 07:11 UTC, merged