Show project details link to all team members
ColoredCow/portal pull request #2761
Opened 2023-01-09 11:03 UTC by Gauravchamoli1997

Targets #2678

### Description
Previously , the project link was shown for all members either he/she is member of project or not and I have to fixed this , so that the link is shown only on projects where the user is a team member of the project. I create a check for this.

### Checklist:

- [ ] I have performed a self-review of my own code.

2023-01-09 12:03 UTC, GauravGusain98 requested changes
The functionality is not working correct. Try adding more than 1 member in a project and see. The project row is being duplicate for each member of the team. 

Please test it properly.

2023-01-11 05:41 UTC, GauravGusain98 requested changes
Left some comments

2023-01-11 05:41 UTC, GauravGusain98 commented on Modules/Project/Resources/views/index.blade.php
> +                                            @if($client->key_account_manager_id === auth()->user()->id)
This line was correct earlier. Please revert it

2023-01-11 05:41 UTC, GauravGusain98 commented on Modules/Project/Resources/views/index.blade.php
>                                      @can('projects.update')
Check why we use @can function. 
Also remember that not every project member have permission `'projects.update'` but we want to show them the project link.

2023-01-11 05:54 UTC, Gauravchamoli1997 commented
@can  is used to check weather a user have specific permission or not.

2023-01-11 06:10 UTC, Gauravchamoli1997 commented
Currently those who have not permission of (project.update) they can also saw the project link. 
![Screenshot (13)](https://user-images.githubusercontent.com/121275531/211730058-51dc8cd7-acee-49bf-a642-eefea098dea6.png)

2023-01-11 07:15 UTC, GauravGusain98 commented
> Currently those who have not permission of (project.update) they can also saw the project link.

what will happen if we not used can as we want to show URL in both case i.e if user has permission and if he does not have (just in this case there is other condition that he should be part to team)

2023-01-11 11:09 UTC, GauravGusain98 commented on Modules/Project/Resources/views/index.blade.php
> +                                    @if('projects.update')
Why you have added if condition here and what exactly is this condition doing? I am not able to understand. 

Just think like that that if I need to print "hello world", then is the below code implementation looks correct or incorrect

if (true) {
    print("hello world")
} else {
    print("hello world")
}

2023-01-11 11:11 UTC, Gauravchamoli1997 commented on Modules/Project/Resources/views/index.blade.php
> +                                    @if('projects.update')
incorrect

2023-01-12 05:05 UTC, Gauravchamoli1997 commented
> > Currently those who have not permission of (project.update) they can also saw the project link.
> 
> what will happen if we don't use @can() because we want to show URL in both case i.e if user has permission and if he does not have (just in this case there is other condition that he should be part to team)

when we have to show link in both cases then why we need the permission check

2023-01-12 05:11 UTC, Gauravchamoli1997 commented on Modules/Project/Resources/views/index.blade.php
> +                                    @if('projects.update')
> > > Currently those who have not permission of (project.update) they can also saw the project link.
> > 
> > 
> > what will happen if we don't use @can() because we want to show URL in both case i.e if user has permission and if he does not have (just in this case there is other condition that he should be part to team)
> 
> when we have to show link in both cases then why we need the permission check

 as far as I understand we have to show the link in both the case whether the member has permission or not. So for this we have to give link to @can as well as inside else. The condition inside @can will be applied when the member has permission, otherwise the else condition will work in which only the project link will be visible.

2023-01-12 05:33 UTC, GauravGusain98 commented on Modules/Project/Resources/views/index.blade.php
> +                                    @if('projects.update')
So if in both condition you are printing the URL, then why you need those conditions? It should would work without them as well, no?

2023-01-13 08:06 UTC, Gauravchamoli1997 commented
In @can(project.update) I don't have to change anything in this because if a user have permission to update a project then he/she already see the project link.
I have to change only in (else) condition where if a user is member of project then user see the link otherwise user only can see project name.

2023-01-16 03:42 UTC, GauravGusain98 commented on Modules/Project/Resources/views/index.blade.php
> +                                                    @endif
This is correct now

2023-01-16 03:43 UTC, GauravGusain98 commented on Modules/Project/Resources/views/index.blade.php
> +                                                    @endphp
Correct the indentation of @php and @endphp and also other related code

2023-01-16 03:46 UTC, GauravGusain98 requested changes
Looks good now, just fix the indentation

2023-01-16 06:00 UTC, GauravGusain98 approved these changes
LGTM

2023-01-16 06:00 UTC, merged