feedBack_update
ColoredCow/portal pull request #2765
Opened 2023-01-12 06:30 UTC by rajatsajwan

Targets #2682
### Description
Ability to add feedback in Application evaluation box

### Checklist:

- [ ] I have performed a self-review of my own code.

2023-01-13 05:07 UTC, P4NK4J requested changes
Facing the following error while evaluating new applications, seems like for those there is no comment, a fallback should be added. Please check.
<img width="1064" alt="image" src="https://user-images.githubusercontent.com/35001775/212241873-105b6be0-f484-4184-a153-3af417f99126.png">

2023-01-13 05:40 UTC, rajatsajwan commented
![Screenshot_20230113_104702](https://user-images.githubusercontent.com/117888235/212245439-615c183e-0667-441a-aa3b-04ba462ada6a.png)
![Screenshot_20230113_104734](https://user-images.githubusercontent.com/117888235/212245553-a3577a2b-ccc8-42d1-834c-e74d1d8f6271.png)
![Screenshot (53)](https://user-images.githubusercontent.com/117888235/212245575-6a532c39-f822-4a43-8534-27dd9ca965c5.png)

2023-01-16 04:51 UTC, P4NK4J requested changes
Left a comment

2023-01-16 04:51 UTC, P4NK4J commented on resources/views/hr/application/evaluation-form.blade.php
> +
These queries should be moved either to service or controller at least, blade file should not be determining any database logic.

2023-01-16 04:51 UTC, P4NK4J commented on resources/views/hr/application/evaluation-form.blade.php
> +        {{-- @dd($applicationRound); --}}
Didn't expect to push commented lines, please do a self review

2023-01-17 03:59 UTC, P4NK4J approved these changes
Looks good.

2023-01-17 04:00 UTC, merged