Functionality to add resource requirement in a project.
ColoredCow/portal pull request #2772
Opened 2023-01-16 17:04 UTC by race45

Targets #2766 

### Description

In the project details page add a section for Resource Requirement. creating a table adding columns and displaying all the designations on the first column.

### Checklist:

- [x] I have performed a self-review of my own code.

2023-02-01 06:06 UTC, GauravGusain98 requested changes
Please check the comments

2023-02-01 06:06 UTC, GauravGusain98 commented on Modules/Project/Http/Controllers/ProjectController.php
> +        $this->service->store($validated, $request);
Can you check what is the used of `$request->validated()` line. I think you don't need to pass `$request`, if you are passing `$validated`.

2023-02-01 06:06 UTC, GauravGusain98 commented on Modules/Project/Resources/views/subviews/edit-resource-requirement.blade.php
> +                                <td><input type="text" name="to-be-deployed" class="form-control"></td>
If you want, we can remove name from these 2 field and make them disabled as we are not using them in backend. We only need `needed[]` field in the backend as we are storing that value only in DB

2023-02-01 06:06 UTC, GauravGusain98 commented on Modules/Project/Services/ProjectService.php
>      public function updateProjectData($data, $project)
I think you have not created the update functionality as for update I could not see any code changes. 

By update I mean when we are editing an existing project and changing the value of resource requirement and saving it. Does the value gets updated or not?

2023-02-01 06:11 UTC, race45 commented on Modules/Project/Services/ProjectService.php
>      public function updateProjectData($data, $project)
yes, the value gets updated.

2023-02-01 07:56 UTC, race45 commented on Modules/Project/Services/ProjectService.php
>      public function updateProjectData($data, $project)
if ($record === null) {
                    $requirement = new ProjectResourceRequirement();
                    $requirement->project_id = $project_id;
                    $requirement->designation = $designation;
                    $requirement->total_requirement = $needed[$index];
                    $requirement->save();
                } else {
                    $record->total_requirement = $needed[$index];
                    $record->save();
                }

2023-02-01 07:56 UTC, race45 commented on Modules/Project/Services/ProjectService.php
>      public function updateProjectData($data, $project)
else part gets the value updated.

2023-02-01 12:24 UTC, GauravGusain98 requested changes

2023-02-01 12:24 UTC, GauravGusain98 commented on Modules/Project/Resources/views/subviews/edit-resource-requirement.blade.php
> +                                <td><input type="text" name="designation[]" class="form-control" value="{{ $designation }}" readonly></td>
We don't want to store designation name in database. The slug/key should be used. 
<img width="417" alt="image" src="https://user-images.githubusercontent.com/54376313/216041646-8add3ed4-ea2d-4af5-a39b-28ae651b4f81.png">


Using laravel methods to diplay data, you can update the name in such a way that you will get the designation slug as key in the designation array.

2023-02-03 05:29 UTC, GauravGusain98 commented
### Testing feedbacks
1. Getting error when leaving any `needed` field as empty. You need to add a check in both frontend, backend that if any value is empty then the default should be 0
    <img width="1225" alt="image" src="https://user-images.githubusercontent.com/54376313/216519287-35fc535c-a839-45f8-9ada-01c34de84610.png">
    <img width="1388" alt="image" src="https://user-images.githubusercontent.com/54376313/216519153-6623203c-00b6-4921-ab2b-b2a6e86620b8.png">

2. The 2 tabs `Project Financial Details` and `Project Techstack` are not present in your code
    <img width="1302" alt="image" src="https://user-images.githubusercontent.com/54376313/216519477-17abfd0e-f71d-405c-9c2c-0c864a347476.png">

3. The alignment of the titles and the table is not looking correct. The title are too much indented. Also the title should be bold 
    <img width="1151" alt="image" src="https://user-images.githubusercontent.com/54376313/216519841-0cb31997-837b-4436-9fa9-448443506c07.png">

4. Also interchange the position of `Total Team Members Required` and `Requirement Details`
    <img width="360" alt="image" src="https://user-images.githubusercontent.com/54376313/216519928-a7a34600-ef75-41fe-87c1-318f49e3f345.png">

2023-02-08 04:13 UTC, GauravGusain98 commented
### Testing Feedbacks

1. This section UI is totally incorrect. Why 2 sections data is showing
<img width="1319" alt="image" src="https://user-images.githubusercontent.com/54376313/217431409-c949718a-4ddc-4cdc-880d-edad001a2385.png">

2. `Project Techstack` and `Resource Requirement` section are having same content
<img width="1216" alt="image" src="https://user-images.githubusercontent.com/54376313/217431539-1090abb2-de8e-4c66-8593-019b3d8f8d80.png">

3. The UI of team member page is totally distorted due to incorrect size of table
<img width="1440" alt="image" src="https://user-images.githubusercontent.com/54376313/217431790-601f7c55-6ac2-41e5-87fc-399a88528751.png">

2023-02-08 04:27 UTC, GauravGusain98 requested changes
Please check the comment

2023-02-08 04:27 UTC, GauravGusain98 commented on Modules/Project/Resources/views/edit.blade.php
> +        <div class="mt-2" style="width: max-content">
We don't use style attribute in HTML. But why you have given it max-content width? I think due to this the team member page got distorted

2023-02-08 04:27 UTC, GauravGusain98 commented on Modules/Project/Resources/views/edit.blade.php
> +                            window.location = '{{ route('project.index') }}';
Why added this. We don't want to redirect user to project page

2023-02-08 04:27 UTC, GauravGusain98 commented on Modules/Project/Resources/views/subviews/edit-resource-requirement.blade.php
> +    <div id="resource_requirement_form">
if should be in camelCase

2023-02-08 04:27 UTC, GauravGusain98 commented on Modules/Project/Resources/views/subviews/edit-resource-requirement.blade.php
> +                        <table class="table table-bordered text-justify">
Indentation not looking correct. There is too much space. Please correct it everywhere

2023-02-08 04:27 UTC, GauravGusain98 commented on Modules/Client/Resources/views/subviews/create-client-details.blade.php
> +            <label for="select_country">Select Country</label>
Take pull from master branch and push the changes to this branch

2023-02-08 04:27 UTC, GauravGusain98 commented on Modules/Project/Services/ProjectService.php
> +    {
Why created a function for one line of code. You can use this line in controller only

2023-02-08 04:27 UTC, GauravGusain98 commented on Modules/Project/Resources/views/subviews/edit-resource-requirement.blade.php
> +                                @foreach ($posts as $post)
What is this $post variable. Please use a meaningful name

2023-02-08 04:27 UTC, GauravGusain98 commented on Modules/Project/Resources/views/subviews/edit-resource-requirement.blade.php
> +                              @endif
This doesnot look correct. There is too much duplicacy of code. Please optimize it

2023-02-08 06:28 UTC, race45 commented on Modules/Project/Resources/views/subviews/edit-resource-requirement.blade.php
> +                              @endif
one `foreach` for store the form data & and another `foreach` $requirements is showing the stored data.

2023-02-08 07:30 UTC, race45 commented on Modules/Project/Resources/views/edit.blade.php
> +        <div class="mt-2" style="width: max-content">
![image](https://user-images.githubusercontent.com/92683476/217462662-56b0381c-5d3b-4784-a105-2e54f8afaf30.png)
without using style attributes UI look shown in the image. show/hide is working

2023-02-10 02:44 UTC, GauravGusain98 requested changes

2023-02-10 02:44 UTC, GauravGusain98 commented on Modules/Project/Http/Controllers/ProjectController.php
> +        $data = $request->all();
This is not corrected. Why you have removed `$validated = $request->validated();`

This line might have been added for some purpose. Figure out how you can get the expected data without removing this file .

Note: You need to read about form request in laravel for this

2023-02-10 02:44 UTC, GauravGusain98 commented on Modules/Project/Http/Controllers/ProjectController.php
> +          ];
We have this stored in config. Just search that config file and get data from there

2023-02-10 02:44 UTC, GauravGusain98 commented on Modules/Project/Http/Controllers/ProjectController.php
> +            'designationNames' => $designationNames,
It sounds better
```suggestion
            'designations' => $designations,
```

2023-02-10 02:44 UTC, GauravGusain98 commented on Modules/Project/Services/ProjectService.php
> +            ];
Get this from config

2023-02-10 02:44 UTC, GauravGusain98 commented on Modules/Project/Services/ProjectService.php
> +                $record = ProjectResourceRequirement::where([
```suggestion
                $projectResourceRequirement = ProjectResourceRequirement::where([
```

2023-02-10 02:44 UTC, GauravGusain98 commented on Modules/Project/Services/ProjectService.php
> +                }
Why you are using index. Can't we use key to fetch the data form needed array

2023-02-10 02:44 UTC, GauravGusain98 commented on Modules/Project/Resources/views/subviews/edit-resource-requirement.blade.php
> +                      <td><input type="text" name="needed[]" class="form-control" value="{{ ($requirements->count() > 0) ? $requirements[$index]->total_requirement : '' }}"></td>
You also need to pass slug as key for designation and instead of designationName you have to pass designation slug in needed array

```suggestion
                      <td><input type="text" name="needed[{{designationName}}]" class="form-control" value="{{ ($requirements->count() > 0) ? $requirements[$index]->total_requirement : '' }}"></td>
```

2023-02-10 06:03 UTC, race45 commented on Modules/Project/Services/ProjectService.php
> +                }
when leaving any needed field empty. then the default should be 0.

2023-02-10 06:14 UTC, race45 commented on Modules/Project/Http/Controllers/ProjectController.php
> +            'designationNames' => $designationNames,
when I write `designationName` as `designations`. then it will pass through an error duplicity code.

2023-02-10 12:40 UTC, race45 commented on Modules/Project/Resources/views/subviews/edit-resource-requirement.blade.php
> +                      <td><input type="text" name="needed[]" class="form-control" value="{{ ($requirements->count() > 0) ? $requirements[$index]->total_requirement : '' }}"></td>
![image](https://user-images.githubusercontent.com/92683476/218094184-9f091ff3-beef-45e9-b81b-e62634bcf562.png)
when i added `name="needed[{{$designationName}}]"`. i got the error `Undefined index: project_manager `.

2023-02-13 04:25 UTC, GauravGusain98 requested changes
Minor suggestions

2023-02-13 04:25 UTC, GauravGusain98 commented on Modules/Project/Resources/views/subviews/edit-resource-requirement.blade.php
> +                      <td><input type="text" name="designation[]" class="form-control" value="{{ ($requirements->count() > 0) ? $designations[$requirements[$index]->designation] : $designations[$desi
You can simply use designation Name here. No need to add a check

2023-02-13 04:25 UTC, GauravGusain98 commented on Modules/Project/Resources/views/subviews/edit-resource-requirement.blade.php
> +                      <td><input type="text" name="needed[{{$designationName}}]" class="form-control" value="{{ ($requirements->count() > 0) ? $requirements[$index]->total_requirement : '' }}"></td>
You need to fecth the requirements using designation name instead of index because using index we are not sure if the index of designation and requirement for that designation will be same. 

So maybe you will be needed to make function in project model to get requirement based on deignation.

2023-02-13 04:25 UTC, GauravGusain98 commented on Modules/Project/Services/ProjectService.php
> +            $designationMap = array_keys(config('project.designation'));
I think this will give you keys array, why you are taking keys separately when you can easily get them in the for loop

2023-02-13 04:25 UTC, GauravGusain98 commented on Modules/Project/Services/ProjectService.php
> +                $designation = $designationMap[$key] ?? $value;
You could have easily got the designation key if you have not taken keys in a separate array

2023-02-13 04:25 UTC, GauravGusain98 commented on Modules/Project/Services/ProjectService.php
> +                    ['designation', '=', $designation],
```suggestion
                    ['designation', '=', $key],
```

2023-02-14 05:51 UTC, GauravGusain98 requested changes
Minor fix

2023-02-14 05:51 UTC, GauravGusain98 commented on Modules/Project/Services/ProjectService.php
> +            $project_id = $project->id;
Please use correct naming convention
```suggestion
            $projectId = $project->id;
```

2023-02-14 05:51 UTC, GauravGusain98 commented on Modules/Project/Entities/Project.php
> +    public function getRequirementByDesignation($designationName)
```suggestion
    public function getResourceRequirementByDesignation($designationName)
```

2023-02-14 05:51 UTC, GauravGusain98 commented on Modules/Project/Resources/views/subviews/edit-resource-requirement.blade.php
> +                      <td><input type="text" name="needed[{{$designationName}}]" class="form-control" value="{{ ($requirement = $project->getRequirementByDesignation($designationName)) ? $requirement
This condition looks incorrect. 

1
```suggestion
                      <td><input type="text" name="needed[{{$designationName}}]" class="form-control" value="{{ optional($project->getResourceRequirementByDesignation($designationName))->total_requirement ?? 0 }}"></td>
```

2023-02-15 10:56 UTC, GauravGusain98 commented
This looks fine now

2023-02-20 06:12 UTC, GauravGusain98 requested changes

2023-02-20 06:12 UTC, GauravGusain98 commented on Modules/Project/Resources/views/subviews/edit-resource-requirement.blade.php
> +                      <td><input type="text" name="to-be-deployed[{{$designationName}}]" class="form-control" value="{{ max(0, optional($project->getResourceRequirementByDesignation($designationName)
Lets make a function `getToBeDeployedCountForDesignation($designation)` inside Project Model that will give you the to_be_deployed count. The you can use that function anywhere.

2023-02-21 05:57 UTC, GauravGusain98 commented
1. If `needed` is less than `deployed` than show -ve count in `to be deployed`
<img width="1203" alt="image" src="https://user-images.githubusercontent.com/54376313/220259204-ff5478a7-5ccc-40b3-ba31-6a7e31a57d88.png">

2. The value of `to_be_deployed` should be changed in UI as I am inserting the count of members in needed. you can use Vue js for this.

3. The overall sum of `to_be_depolyed` should be shown in front of the heading `Total Team Members Required:`
<img width="451" alt="image" src="https://user-images.githubusercontent.com/54376313/220259716-916e85cc-960a-4eba-830e-4150a682b129.png">

2023-02-22 10:49 UTC, race45 commented
I am able to understand how The value of to_be_deployed should be changed in UI as I am inserting the count of members in needed. you can use Vue js for this. i need help on that.

2023-02-22 10:50 UTC, race45 commented
i am not able to understand.

2023-02-22 12:33 UTC, race45 commented
other's feedback 1 and 3 points are working. I am stuck on the second point. The value of to_be_deployed should be changed in UI as I am inserting the count of members in needed. you can use Vue js for this.

2023-02-23 18:08 UTC, GauravGusain98 requested changes
minor suggestion

2023-02-23 18:08 UTC, GauravGusain98 commented on Modules/Project/Entities/Project.php
> +                    ->count();
You can use the relationship here
```suggestion
        return $this->getTeamMembers()->where('designation', '=', $designation)->count();
```

2023-02-24 07:04 UTC, GauravGusain98 approved these changes
LGTM

2023-02-24 07:04 UTC, merged