ordering client dropdown
ColoredCow/portal pull request #2776
Opened 2023-01-18 12:27 UTC by nishant22029

Targets #2773 

### Description
In this PR  ,I updated the query that is used to fetch client details in a way that is to order the client's result by client name in ascending order.
 The client list is not ordered by name which is causing trouble, if we sort the list by client name in ascending order then it would be easier to find the client for that list.

### Checklist:
- [x] I have performed a self-review of my own code.

2023-01-18 12:38 UTC, GauravGusain98 requested changes
Looks good minor suggestion

2023-01-18 12:38 UTC, GauravGusain98 commented on Modules/Project/Http/Controllers/ProjectController.php
> +use Google\Service\AnalyticsData\OrderBy;
This is not needed. Why it was imported?

2023-01-19 05:01 UTC, GauravGusain98 requested changes
Check the comment

2023-01-19 05:01 UTC, GauravGusain98 commented on Modules/Project/Http/Controllers/ProjectController.php
> +// use Google\Service\AnalyticsData\OrderBy;
Commenting code is not a good practice. Remove this line as it was not there earlier.

2023-01-19 05:19 UTC, nishant22029 commented on Modules/Project/Http/Controllers/ProjectController.php
> +// use Google\Service\AnalyticsData\OrderBy;
ok sir

2023-01-19 05:49 UTC, GauravGusain98 approved these changes
LGTM

2023-01-19 05:49 UTC, merged