bug fixed
ColoredCow/portal pull request #2778
Opened 2023-01-19 08:42 UTC by rahulpanwar16

Targets #2690 

Description:

I have correct the FTE calculation of the user if the project billing date lies in between the month. 
To do so I have created new variable($firstDayOfMonth) whose value is 2022/01/01 and declared that variable in the FTE calculation function so that in variable $daysTillToday  , workingDaysList() can pass the value of  $firstDayOfMonth and be able to return the desired dates of the working days.

For the hours booked there is a CurrentActualEffort() who returns to the projectTeamMemberEffort() where 'added on' ,'>=',month_start_date ->sum('actual effort'). Here, month_start_date represents project billing date and I have replaced it with $firstDayOfMonth so that FTE calculation should not depend on the project billing date. Therefore, it will sum the actual effort from day 1st to the current date from the database table name "project_team_member_effort". 

The changes are required because the calculation of FTE is from the month start date to the month end date. 
This PR resolves the behavior of the FTE when project billing date lies in between of the month  as the FTE value is now constant when you add any random numbers till the current date of that project. 

 Checklist:

- [ ] I have performed a self-review of my own code.

2023-01-19 09:38 UTC, GauravGusain98 requested changes
Great, you are very close. Left some suggestion please check

2023-01-19 09:38 UTC, GauravGusain98 commented on Modules/Project/Entities/ProjectTeamMember.php
> +        $daysTillToday = count($project->getWorkingDaysList($firstDayOfMonth, $currentDate));
We needed this for calculating the Velocity of the project. The velocity is calculated from the billing date. So this should not be changed

2023-01-19 09:38 UTC, GauravGusain98 commented on Modules/Project/Entities/ProjectTeamMember.php
This function is use to get the effort of user for the billing cycle i.e we need to use the billing date here.

2023-01-19 09:38 UTC, GauravGusain98 commented on Modules/Project/Entities/ProjectTeamMember.php
Maybe you can just make this function take a $startDate argument whose initial value will be null. inside the function just check if the $startDate is null then assign it the value `$this->project->client->month_start_date` else the value should be $startDate only.

2023-01-19 09:38 UTC, GauravGusain98 commented on Modules/Project/Entities/ProjectTeamMember.php
> +        $daysTillToday = count($project->getWorkingDaysList($firstDayOfMonth, $currentDate));
Maybe you can just make this function take a $startDate argument whose initial value will be null. inside the function just check if the $startDate is null then assign it the value $this->project->client->month_start_date else the value should be $startDate only.

2023-01-19 09:38 UTC, GauravGusain98 commented on Modules/Project/Entities/ProjectTeamMember.php
>          }
On line 98 just pass $firstDayOfMonth to `$this->getCurrentExpectedEffortAttribute()` and it will give you the booked hours from first day of the month

2023-01-19 09:38 UTC, GauravGusain98 commented on Modules/Project/Entities/ProjectTeamMember.php
> +        $daysTillToday = count($project->getWorkingDaysList($firstDayOfMonth, $currentDate));
Do the same with the function `getExpectedEffortTillTodayAttribute()` at line 70

2023-01-19 11:14 UTC, GauravGusain98 commented on Modules/Project/Entities/ProjectTeamMember.php
> +        $startDate = $startDate ?? $this->project->client->month_start_date;
Nice. You know why we user `??` right?

2023-01-19 11:17 UTC, GauravGusain98 requested changes
minor suggestion

2023-01-19 11:17 UTC, GauravGusain98 commented on Modules/Project/Entities/ProjectTeamMember.php
>          }
On line 99, we want to calculate the hours booked by user from first day of the month. So, also pass the firstDateOfMonth to `$this->current_actual_effort`

2023-01-19 11:52 UTC, rahulpanwar16 commented on Modules/Project/Entities/ProjectTeamMember.php
> +        $startDate = $startDate ?? $this->project->client->month_start_date;
Yes, ?? is a null coalescing operator which means it will check if the value of $startDate is null or not and if null then it will assign a value to the $startDate

2023-01-19 12:34 UTC, GauravGusain98 requested changes

2023-01-19 12:34 UTC, GauravGusain98 commented on Modules/Project/Entities/ProjectTeamMember.php
> +        return round($firstDayOfMonth / ($daysTillToday * config('efforttracking.minimum_expected_hours')), 2);
Why numerator is number of days, it should be actual effort that you will get from the existing function, you just need to pass the start date to it. That's why we added the startDate field to above functions.

2023-01-23 06:20 UTC, GauravGusain98 approved these changes
LGTM

2023-01-23 06:20 UTC, merged