Multiple email templates option upon rejecton
ColoredCow/portal pull request #2779
Opened 2023-01-19 12:00 UTC by rajatsajwan

Targets #2687

### Description
Creating Multiple email templates option upon rejection Template with

### Checklist:

- [ ] I have performed a self-review of my own code.

2023-01-20 06:18 UTC, P4NK4J requested changes
Left some comments.

2023-01-20 06:18 UTC, P4NK4J commented on resources/js/app.js
> +$(".rejectMailOpt").on("click",function(){
If this is a classname, why it is camelcased ?

2023-01-20 06:18 UTC, P4NK4J commented on resources/js/app.js
> +	var originUrl = window.location.origin;
can we define this variable as a global one ?

2023-01-20 06:18 UTC, P4NK4J commented on resources/views/hr/application/rejection-modal.blade.php
> +                                                <input name="subject_general_communication" type="text" class="form-control option-subject" id="general_communicationSubject">
What is the naming convention you are using in id ? Is it camelcase or snakecase ? Please avoid these silly mistakes

2023-01-20 09:31 UTC, rajatsajwan commented on resources/views/hr/application/rejection-modal.blade.php
> +                                                <input name="subject_general_communication" type="text" class="form-control option-subject" id="general_communicationSubject">
i change it into snakecase

2023-01-20 12:16 UTC, P4NK4J commented
> ![Screenshot (63)](https://user-images.githubusercontent.com/117888235/213692420-a84962ad-6232-4c82-8eec-18e77a342a6f.png) sir this is running fine in my system.

If it's working on your local, it doesn't mean it would work on the production server as well. It's working on your system because you started with a. fresh database. Try importing the UAT one and see with existing database what's happening

2023-01-23 11:08 UTC, rajatsajwan commented
![image](https://user-images.githubusercontent.com/117888235/214025109-243c522d-aa49-48fa-a21a-580ce0be58b2.png)

this is result in general communication

2023-01-23 11:09 UTC, rajatsajwan commented
![image](https://user-images.githubusercontent.com/117888235/214025354-5e9cc484-548e-4c5d-9172-92069027dc41.png)

this is  codetrack

2023-01-24 05:38 UTC, rajatsajwan commented
![image](https://user-images.githubusercontent.com/117888235/214219853-b9313668-411b-4894-9fd3-18d3b67b44bf.png)

result of changes.

2023-01-24 05:53 UTC, rajatsajwan commented
![image](https://user-images.githubusercontent.com/117888235/214219853-b9313668-411b-4894-9fd3-18d3b67b44bf.png)

result of changes.

2023-01-24 08:16 UTC, rajatsajwan commented
![image](https://user-images.githubusercontent.com/117888235/214219853-b9313668-411b-4894-9fd3-18d3b67b44bf.png)

result of changes.

2023-01-26 08:16 UTC, rajatsajwan commented
![Screenshot (65)](https://user-images.githubusercontent.com/117888235/214787629-bc54c6ef-f9b5-49a3-a82e-0648a81b73a6.png)

this is result of changes

2023-04-07 12:28 UTC, closed without merging