created a feature resource and guideline
ColoredCow/portal pull request #2780
Opened 2023-01-19 12:34 UTC by kanuj365

#2764
create a feature for resource and guideline that can have different types of categories.

### Description
- Create a resource and guideline view page that have resource and category model.
- In view page have 3 types of data like category, mark as read , user's suggestions.
- Create a resource and guideline view page for users that user can see all types of category.
- On resource and guideline view page have 3 type of table data like category, mark as read and post_suggestion.  
 

### Checklist:

- [ ] I have performed a self-review of my own code.

2023-01-20 05:12 UTC, kanuj365 commented
![image](https://user-images.githubusercontent.com/68420715/213622088-df31dc53-4a37-4090-b933-80d9c836fae6.png)

2023-01-20 06:14 UTC, P4NK4J requested changes
left some comments,

2023-01-20 06:14 UTC, P4NK4J commented on Modules/HR/Http/Controllers/EmployeeController.php
> +    }
Controller should not be responsible for executing database queries, please put the create logic in service. Also, this function name doesn't make sense what its doing, please check

2023-01-20 06:14 UTC, P4NK4J commented on Modules/HR/Http/Controllers/EmployeeController.php
> +    public function resources(Employee $employee)
Can we rename this function to have getAllResources kind of name ?

2023-01-20 06:14 UTC, P4NK4J commented on Modules/HR/Resources/views/guidelines-resources/index.blade.php
> +                    @if (!$userSuggestion->mark_as_read && $userSuggestion->category==$resource->category->name)
check indentation and formatting, don't push unhygienic code

2023-01-20 11:35 UTC, kanuj365 commented on Modules/HR/Resources/views/guidelines-resources/index.blade.php
> +@endsection
In blade file i used php intelligence for HTML elements formatting for every line.

2023-01-20 12:29 UTC, kanuj365 commented on Modules/HR/Resources/views/guidelines-resources/index.blade.php
> +@endsection
I always used PHP Intelsense for HTML element format

2023-01-21 10:26 UTC, P4NK4J requested changes
Resource link not appearing correctly
<img width="701" alt="image" src="https://user-images.githubusercontent.com/35001775/213862544-047c082c-e4e4-4a56-b425-25bbdf4f4ce4.png">

If there is no reader, the message should not say please click on avatar
<img width="1084" alt="Screenshot 2023-01-21 at 3 49 11 PM" src="https://user-images.githubusercontent.com/35001775/213862551-165e2331-12f8-4ce8-8430-bb90f091218a.png">

The size of buttons is very large, can we make the buttons text in a single line ?

Deleting a resource is displaying the message, `category deleted successfully`, it should say `resource deleted successfully`, because we are not deleting the category

Upon saving the suggestion, I am getting empty values on the dashboard. The checkbox should be checked if I have marked it as read, and the suggestion should be stored, in case I edit the suggestion, it should be updated on HR resources page as well. Also, the tab should read `Resources` here. 
Also, there should be functionality to mark as unread. The table header can say `Action`, and the UI can be like a checkbox and mark as read/unread message next to it
<img width="1302" alt="image" src="https://user-images.githubusercontent.com/35001775/213862636-996d51eb-e2d8-4abd-8646-ae206a235594.png">

Let's make suggestions color black, because blue is used for denoting a hyperlink. 
<img width="460" alt="image" src="https://user-images.githubusercontent.com/35001775/213862709-6c98d568-7479-4e87-94ca-ae619e986487.png">

2023-01-23 10:37 UTC, kanuj365 commented
![image](https://user-images.githubusercontent.com/68420715/214019201-0014cd4a-8285-4e80-b97f-51b7a28981df.png)

2023-01-28 07:41 UTC, kanuj365 commented
![image](https://user-images.githubusercontent.com/68420715/215253574-aacd0147-324e-4e01-9291-1d13442e1ba2.png)
![image](https://user-images.githubusercontent.com/68420715/215253607-26ae1c53-4fc5-4221-bd0c-8f72f3933e88.png)

2023-04-07 12:28 UTC, closed without merging