Feature/2781 add link to client
ColoredCow/portal pull request #2789
Opened 2023-01-24 11:09 UTC by rajneeshweb

Targets #2781 

### Description

Add link to client detail page on the client name in project details page

### Checklist:

- [x] I have performed a self-review of my own code.

2023-01-24 11:55 UTC, GauravGusain98 requested changes
Please check the comments

2023-01-24 11:55 UTC, GauravGusain98 commented on package.json
> +        "cross-env": "^7.0.3",
Why this is updated? In your file changes, only the files related to your task should be present. Please remove other files like package.json, package-lock.json, and composer.lock

2023-01-24 11:55 UTC, GauravGusain98 commented on Modules/Project/Resources/views/show.blade.php
> +                        <a href="/client/{{ $project->client->id }}/edit" class="text-capitalize ml-2 fz-lg-22">{{ $project->client->name }}</a>
We don't hardcode the URL instead use route() function to get the URL. Read about route in Laravel

2023-01-28 12:51 UTC, rajneeshweb commented
Closing this branch.

2023-01-28 12:51 UTC, closed without merging