phase 1.2 added applicant module
ColoredCow/portal pull request #2793
Opened 2023-01-26 06:13 UTC by nishant22029

Targets #2743 

### Description
created the page that will be used to display the applicant's list and details. Added button for add new applicant
 so that on clicking the button add new applicant button the modal should pop up a form. Added two tabs applicants and reports.

### Checklist:

- [x] I have performed a self-review of my own code.

2023-01-26 06:58 UTC, GauravGusain98 requested changes
Great work, left some comment please check

2023-01-26 06:58 UTC, GauravGusain98 commented on Modules/CodeTrek/Resources/views/modals/add-applicant-modal.blade.php
> +            <div class="card-footer">
There should not be any padding in this 
<img width="875" alt="image" src="https://user-images.githubusercontent.com/54376313/214774326-01c9f34b-c721-4140-a18e-a932b17db7ae.png">

2023-01-26 06:58 UTC, GauravGusain98 commented on Modules/CodeTrek/Resources/views/modals/add-applicant-modal.blade.php
> +                            <option value="">Select Graduation Year</option>
the Graduation year should be from 1990 to 4 years ahead from the current year. Note, this should be dynamic

2023-01-26 06:58 UTC, GauravGusain98 commented on Modules/CodeTrek/Resources/views/index.blade.php
> +          <a class="nav-link {{ (request()->input('status', 'active') == 'applicants')  ? 'active' : '' }}" href="{{ route('codetrek.index', $request)  }}"><i class="fa fa-list-ul"></i> Applicants</a
By default this tab should be active. Currently nothing is selected when we visit the page
<img width="1255" alt="image" src="https://user-images.githubusercontent.com/54376313/214775315-9dd7ff49-6a5e-41b5-b296-ce9d45c28a06.png">

2023-01-26 06:58 UTC, GauravGusain98 commented on Modules/CodeTrek/Resources/views/modals/add-applicant-modal.blade.php
> +<div id="add_applicant_details_form">
You should also need a form tag that you will use to submit the data

2023-01-26 07:08 UTC, GauravGusain98 commented on Modules/CodeTrek/Resources/views/modals/add-applicant-modal.blade.php
> +            <div class="card-footer">
Also make this bold
<img width="352" alt="image" src="https://user-images.githubusercontent.com/54376313/214776771-bea5059c-202d-4290-a3d2-1f29f0be8720.png">

2023-01-26 07:10 UTC, GauravGusain98 requested changes

2023-01-26 07:10 UTC, GauravGusain98 commented on Modules/CodeTrek/Resources/views/index.blade.php
> +                   </table>
Fix indentation
```suggestion
                   </td>
               </table>
```

2023-01-27 07:16 UTC, nishant22029 commented on Modules/CodeTrek/Resources/views/modals/add-applicant-modal.blade.php
> +            <div class="card-footer">
done this changes

2023-01-27 07:17 UTC, nishant22029 commented on Modules/CodeTrek/Resources/views/modals/add-applicant-modal.blade.php
> +                            <option value="">Select Graduation Year</option>
added gradution years in select tag.

2023-01-27 07:17 UTC, nishant22029 commented on Modules/CodeTrek/Resources/views/index.blade.php
> +          <a class="nav-link {{ (request()->input('status', 'active') == 'applicants')  ? 'active' : '' }}" href="{{ route('codetrek.index', $request)  }}"><i class="fa fa-list-ul"></i> Applicants</a
done sir.

2023-01-27 07:18 UTC, nishant22029 commented on Modules/CodeTrek/Resources/views/modals/add-applicant-modal.blade.php
> +<div id="add_applicant_details_form">
added form tag .

2023-01-27 07:20 UTC, nishant22029 commented on Modules/CodeTrek/Resources/views/index.blade.php
> +                   </table>
done sir.

2023-01-27 07:36 UTC, GauravGusain98 requested changes

2023-01-27 07:36 UTC, GauravGusain98 commented on Modules/CodeTrek/Resources/views/modals/add-applicant-modal.blade.php
> +                                      }
1. Please use blade syntax `@for` instead of Php for.
2. Also, can you read about [diplaying data](https://laravel.com/docs/8.x/blade#displaying-data) in blade files. We don't use the echo function in the blade until it is necessary.
3. Can you give the options in descending order? It will be easier and faster for users.

2023-01-27 07:36 UTC, GauravGusain98 commented on Modules/CodeTrek/Resources/views/modals/add-applicant-modal.blade.php
> +            <div class="modal-header">
Indentation is not correct. All the elements inside form should be 1 tab inside.

2023-01-27 07:36 UTC, GauravGusain98 commented on Modules/CodeTrek/Resources/views/modals/add-applicant-modal.blade.php
> +                        <input type="text" class="form-control" name="name" id="first_name" placeholder="Enter first name"
Just check the [naming convention](https://github.com/ColoredCow/portal/blob/master/docs/variable-naming-convention.md) that we use for different attributes.  

```suggestion
                        <input type="text" class="form-control" name="first_name" id="firstName" placeholder="Enter first name"
```

2023-01-27 07:36 UTC, GauravGusain98 commented on Modules/CodeTrek/Resources/views/modals/add-applicant-modal.blade.php
> +                        <input type="text" class="form-control" name="name" id="first_name" placeholder="Enter first name"
Correct the naming convention every where

2023-01-27 07:36 UTC, GauravGusain98 commented on Modules/CodeTrek/Resources/views/modals/add-applicant-modal.blade.php
> +                            ?>
1. Try to use blade functions instead of PHP functions as it makes it easy to read. Here you can use `@for` instead of PHP for loop
2. Show the options in descending order as it will be easier for user to find year as most of the applicant would be ones who have graduated recently
3. Avoid using echo in blade file. Read how to [display date](https://laravel.com/docs/8.x/blade#displaying-data) in blade.

2023-01-27 07:36 UTC, GauravGusain98 commented on Modules/CodeTrek/Resources/views/modals/add-applicant-modal.blade.php
> +                        <input type="tel" class="form-control" name="phone_no" id="course" placeholder="Enter Phone Number"
Keep it of type text only. Also change the name attribute to `phone`

2023-01-27 07:36 UTC, GauravGusain98 commented on Modules/CodeTrek/Resources/views/modals/add-applicant-modal.blade.php
> +                        <input type="tel" class="form-control" name="phone_no" id="course" placeholder="Enter Phone Number"
Also can you please move the phone input field after email.

2023-01-27 11:13 UTC, nishant22029 commented on Modules/CodeTrek/Resources/views/modals/add-applicant-modal.blade.php
> +                            ?>
done.

2023-01-27 11:13 UTC, nishant22029 commented on Modules/CodeTrek/Resources/views/modals/add-applicant-modal.blade.php
> +                        <input type="text" class="form-control" name="name" id="first_name" placeholder="Enter first name"
done sir

2023-01-27 11:13 UTC, nishant22029 commented on Modules/CodeTrek/Resources/views/modals/add-applicant-modal.blade.php
> +            <div class="modal-header">
done sir

2023-01-27 11:13 UTC, nishant22029 commented on Modules/CodeTrek/Resources/views/modals/add-applicant-modal.blade.php
> +                                      }
done sir.

2023-01-27 11:58 UTC, nishant22029 commented on Modules/CodeTrek/Resources/views/modals/add-applicant-modal.blade.php
> +                                    required="required"  maxlength="10" value="">
ok sir

2023-01-27 16:08 UTC, GauravGusain98 requested changes
please do a self reveiw before assigning for review. There are many feedbacks that are still not implemented.

2023-01-27 16:08 UTC, GauravGusain98 commented on Modules/CodeTrek/Resources/views/index.blade.php
> +                         </td>
Indentation not correct

2023-01-27 16:08 UTC, GauravGusain98 commented on Modules/CodeTrek/Resources/views/modals/add-applicant-modal.blade.php
> +                           </button>
Indentation not correct

2023-01-27 16:08 UTC, GauravGusain98 commented on Modules/CodeTrek/Resources/views/modals/add-applicant-modal.blade.php
> +                                        @endfor
Indentation not yet fixed

2023-01-28 04:48 UTC, nishant22029 commented on Modules/CodeTrek/Resources/views/modals/add-applicant-modal.blade.php
> +                                        @endfor
corrected the identation .

2023-01-28 08:48 UTC, GauravGusain98 approved these changes
LGTM

2023-01-28 08:48 UTC, merged