phase 1.3 module added
ColoredCow/portal pull request #2801
Opened 2023-01-31 11:04 UTC by nishant22029

Targets #2794 

### Description

I have created codetrek_applicants migration and table , a controller with store() that will store applicants
data into table. Also created service file to fetch the applicants data and sent to codetrek page.
### Checklist:

- [x] I have performed a self-review of my own code.

2023-02-01 05:55 UTC, GauravGusain98 commented
### Testing Feedbacks
1. Lets make these field as not required, as they are also not required in database level
    <img width="783" alt="image" src="https://user-images.githubusercontent.com/54376313/215962529-e236ecff-2999-4d87-9fa3-aa8d29b7471b.png">
2. Good job, You've added the success banner, I think it can be made better if you use vue-toastification toggle as we have used in projects edit page. Just figure out how it is being used there and implement it here as well
    <img width="485" alt="image" src="https://user-images.githubusercontent.com/54376313/215962918-b86e02df-17f4-4872-a732-3d6bcee5d848.png">

2023-02-02 05:33 UTC, nishant22029 commented
I am stuck with this task to dispaly success banner using vue-toastification toggle ,please help on this sir.
![image](https://user-images.githubusercontent.com/114382264/216240139-ee160a8f-fca5-4be7-a2e5-0e2ce10fbf1e.png)

2023-02-06 04:19 UTC, GauravGusain98 requested changes
Please check the comments

2023-02-06 04:19 UTC, GauravGusain98 commented on Modules/CodeTrek/Entities/CodeTrekApplicant.php
> +  ];
If you want all the fields to be fillable then you can use this 
`protected $guarded = []`

2023-02-06 04:19 UTC, GauravGusain98 commented on Modules/CodeTrek/Http/Controllers/CodeTrekController.php
> +        $applicant->save();
We usually do these kinds of operations in the service file. Can you create a function inside the CodeTrekService file and do this operation in it instead of here. 

Controllers are just use to call functions and return views.

2023-02-06 04:19 UTC, GauravGusain98 commented on Modules/CodeTrek/Resources/views/index.blade.php
> +                            @endforeach
Instead of adding foreach in each <td>, we can just use it outside <tr>, that way we don't have to duplicate the  foreach loop. Duplicacy is not a good practice in programming.

2023-02-06 04:19 UTC, GauravGusain98 commented on Modules/CodeTrek/Resources/views/index.blade.php
> +            submitForm: async function(formId) {
The form is getting saved even when I have not filled any data in required fields
<img width="512" alt="image" src="https://user-images.githubusercontent.com/54376313/216882585-b7f3992b-e59a-4ca0-90f0-a9f180122640.png">


Check by inspecting the page and see errors in console.

2023-02-06 04:19 UTC, GauravGusain98 commented on Modules/CodeTrek/Resources/views/index.blade.php
> +@section('vue_scripts')
I've a doubt that we already have some code defined to handle ajax form submission. let me check and get back to you on this. Till then please fix other feedbacks

2023-02-06 04:20 UTC, GauravGusain98 commented
The toast is also not getting displayed when submitting the form

2023-02-07 05:16 UTC, nishant22029 commented on Modules/CodeTrek/Resources/views/index.blade.php
> +@section('vue_scripts')
![image](https://user-images.githubusercontent.com/114382264/217154046-36ee885c-3bbf-4f80-9d74-2741e6328f8b.png)
sir i'm trying to display toggle notifation but after submission data storing twice ,need help on this
![image](https://user-images.githubusercontent.com/114382264/217154488-18a1507b-fbc6-4ff7-bb00-9466b75440a0.png)
![image](https://user-images.githubusercontent.com/114382264/217154753-464b57f4-a5eb-4805-9ced-d98de9121adb.png)

2023-02-07 05:20 UTC, nishant22029 commented on Modules/CodeTrek/Resources/views/index.blade.php
> +@section('vue_scripts')
![image](https://user-images.githubusercontent.com/114382264/217155272-87dc61ee-c0a6-412e-8ec5-3b00798d35ba.png)

2023-02-08 04:53 UTC, GauravGusain98 requested changes
Minor feedbacks, else looks good

1. The key name should not be status. Lets rename it to `tab`
    <img width="160" alt="image" src="https://user-images.githubusercontent.com/54376313/217436880-d4ff843f-7f09-478a-a90d-0de0ad8c05ab.png">

2. On submitting the applicant form the toast is not coming.

2023-02-08 04:53 UTC, GauravGusain98 commented on Modules/CodeTrek/Resources/views/index.blade.php
> +                            <td>{{$applicant->status}}</td>
You need to create a status key in config.py file insider Codetrek module and for different status you need to set the label and slug. Then based on status value from database you need to show th label in the UI instead of slug
<img width="211" alt="image" src="https://user-images.githubusercontent.com/54376313/217436127-07b3f707-6314-4297-ba69-a3e5789c24e0.png">

2023-02-08 04:53 UTC, GauravGusain98 commented on Modules/CodeTrek/Services/CodeTrekService.php
> +        $applicant->phone = $data['phone'];
Use null coalescing in fields that are nullable
```suggestion
        $applicant->phone = $data['phone'] ?? null;
```

2023-02-08 06:13 UTC, nishant22029 commented
![image](https://user-images.githubusercontent.com/114382264/217448472-548a2472-c10b-4e4f-8cf8-1b5e36428ea4.png)
toast message is coming on my system

2023-02-08 06:16 UTC, GauravGusain98 reviewed
minor fix

2023-02-08 06:16 UTC, GauravGusain98 commented on Modules/CodeTrek/Config/config.php
> +    ]
```suggestion
    'status' => [
        'active' => [
            'label' => 'Active',
            'slug' => 'active'
         ],
        'inactive' => [
            'label' => 'Inactive',
            'slug' => 'inactive'
         ]
    ]
```

2023-02-08 07:54 UTC, GauravGusain98 approved these changes
LGTM

2023-02-08 07:55 UTC, merged