provide a new functionality on remaining amount
ColoredCow/portal pull request #2804
Opened 2023-02-03 08:52 UTC by kanuj365

Targets #2729

### Description
- In this feature we provide a functionality that Clients can pay partial payments or has paid the invoice in installments.

### Checklist:
- [ ] I have performed a self-review of my own code.

2023-02-03 18:24 UTC, GauravGusain98 commented
### Feedbacks
1. The partially paid option is not available 
<img width="696" alt="image" src="https://user-images.githubusercontent.com/54376313/216677326-3fcaa4ec-d5e8-4a9f-a712-3cf57f9eabb1.png">

2. I have not paid anything but the remaining amount is 0 by default
<img width="1231" alt="image" src="https://user-images.githubusercontent.com/54376313/216677919-08de7d9c-14d3-4822-a060-ce8bff06ce9b.png">

3. Also on adding the amount in the received amount field the remaining amount should change. This can be easily done  using vuejs
<img width="1210" alt="image" src="https://user-images.githubusercontent.com/54376313/216678771-859d14ea-0900-4f77-bb6d-e707431ebb1f.png">

2023-02-06 07:57 UTC, kanuj365 commented
![image](https://user-images.githubusercontent.com/68420715/216915765-a122d6f3-3140-4897-a3cb-e89907f5c482.png)
if user paid in installments then every amount after installments amount can see.

2023-02-06 12:44 UTC, kanuj365 commented
![image](https://user-images.githubusercontent.com/68420715/216974735-31cf7448-7367-4572-a9cd-f5dd6e77c6d5.png)

2023-02-08 04:44 UTC, GauravGusain98 requested changes
### Testing feedbacks
1. Partially paid Status should also be shown here
    <img width="1229" alt="image" src="https://user-images.githubusercontent.com/54376313/217434750-a4225f47-7725-4adc-bae6-a32e2f92a0e6.png">

2. The status should come as `Partially Paid` in orange color
<img width="114" alt="image" src="https://user-images.githubusercontent.com/54376313/217435018-d2d48342-613a-44c5-bae2-b3c4b0eff780.png">


3. The amount related columns should be encrypted
    <img width="276" alt="image" src="https://user-images.githubusercontent.com/54376313/217435281-7b24bcde-73a2-4230-ab78-0ae4328261de.png">

I think I'll update the requirement of this task a bit. So please give me some time to do that. Till then please fix the given feedbacks

2023-02-08 04:44 UTC, GauravGusain98 commented on Modules/Invoice/Config/config.php
> +        'partially' => 'Partially Paid',
```suggestion
        'partially_paid' => 'Partially Paid',
```

2023-02-10 02:12 UTC, GauravGusain98 commented
### Testing Feedbacks
- [ ] I am getting this error. Mostly looks like php issue. 
    <img width="1380" alt="image" src="https://user-images.githubusercontent.com/54376313/217981550-8bb00f3e-c1a8-45cd-856a-9dd308ae3d40.png">

- [ ] The status field is not coming up correct
    <img width="967" alt="image" src="https://user-images.githubusercontent.com/54376313/217982285-fe61a676-b765-4fde-9355-fb26d61ebcfa.png">

- [ ] The partially paid filter is not showing correct data
    <img width="1312" alt="image" src="https://user-images.githubusercontent.com/54376313/217982549-a0ffe1df-459d-4333-9aa3-8f057170cba1.png">

- [ ] If an invoice is partially paid then we should not show overdue status, instead show partially paid status
    <img width="711" alt="image" src="https://user-images.githubusercontent.com/54376313/217982811-933daeeb-c6be-4267-b314-3621eec243bd.png">

2023-02-10 02:29 UTC, GauravGusain98 commented
### Additonal requirements
- [ ] We need to make some changes in the current table [schema](https://docs.google.com/presentation/d/1djNuUlhABvhZieWBax39jshAGEGsComSzvzMKtMQv6w/edit#slide=id.g1c14b30e04f_0_134) use this file to update the `invoice_details` table
- [ ] If any invoice payment details is capture then make an entry for that payment in this table
- [ ] For partially paid invoices. The amount paid till now should be calculated by adding the amount paid information of all the entries for an invoice in this table
- [ ] If there is any previous payment details available then show the details like shown in below image
<img width="540" alt="image" src="https://user-images.githubusercontent.com/54376313/217985074-bc1178ec-d442-4df5-9c04-c50e197af9b1.png">

2023-02-14 06:50 UTC, GauravGusain98 commented
### Testing feedbacks
1. Overdue is still showing
2. Remaining amount is only decreasing. Its not resetting if we change the paid amount to 0
3. Rename the button text to Payment History
4. Make all the field default values as empty
5. Make details in accordion
    <img width="1273" alt="image" src="https://user-images.githubusercontent.com/54376313/218660572-2fe1efda-9d27-41c4-8d4b-8ff0ce731734.png">
6. Store paid payment details also in new table

2023-05-08 12:27 UTC, closed without merging