Changed the time of effort syncing to hourly at 25th minute
ColoredCow/portal pull request #2815
Opened 2023-02-11 06:46 UTC by Priyanka-Kaintura

Change time of effort syncing #2805

### Description
Changed effort syncing time from every four hours to hourly at 25th minute 
To reduce the chance of sending non-updated data to the channel.
### Checklist:

- [x] I have performed a self-review of my own code.

2023-02-11 08:27 UTC, Ayush8923 requested changes
Left some comment. Please check.

2023-02-11 08:27 UTC, Ayush8923 commented on package-lock.json
>                  "merge-source-map": "^1.1.0",
@Priyanka-Kaintura  Please remove this file from this PR. It's not needed.

2023-02-13 06:04 UTC, GauravGusain98 requested changes
You don't have to remove the package-lock.json from the codebase. Please revert the file.

2023-02-13 09:27 UTC, GauravGusain98 commented
> You don't have to remove the package-lock.json from the codebase. Please revert the file.

Only the extra code changes were supposed to be removed

2023-02-14 06:41 UTC, Priyanka-Kaintura commented
<!--
/* Font Definitions */
@font-face
	{font-family:"Cambria Math";
	panose-1:2 4 5 3 5 4 6 3 2 4;}
@font-face
	{font-family:Calibri;
	panose-1:2 15 5 2 2 2 4 3 2 4;}
/* Style Definitions */
p.MsoNormal, li.MsoNormal, div.MsoNormal
	{margin:0cm;
	font-size:11.0pt;
	font-family:"Calibri",sans-serif;}
a:link, span.MsoHyperlink
	{mso-style-priority:99;
	color:blue;
	text-decoration:underline;}
.MsoChpDefault
	{mso-style-type:export-only;}
@page WordSection1
	{size:612.0pt 792.0pt;
	margin:72.0pt 72.0pt 72.0pt 72.0pt;}
div.WordSection1
	{page:WordSection1;}
--> Can I delete the pull request and the branch? And recreate branch and pull request. Since I have made the mistake and now I’m stuck there. I tried to reset the commit but it still shows the commits already done. If possible, please allow me to delete the branch and create another one.Sent from Mail for Windows Thank-You—

2023-02-15 09:51 UTC, GauravGusain98 approved these changes

2023-02-15 09:59 UTC, Ayush8923 approved these changes

2023-02-15 10:00 UTC, merged