User FTE shown on Dashboard
ColoredCow/portal pull request #2828
Opened 2023-02-20 10:57 UTC by Priyanka-Kaintura

Targets #2819

### User FTE shown on the dashboard

### Checklist:

- [x] I have performed a self-review of my own code.

2023-02-23 17:42 UTC, GauravGusain98 requested changes
Please check comment

2023-02-23 17:42 UTC, GauravGusain98 commented on app/Http/Controllers/HomeController.php
> +        $FTE = $efforts / (date('d') * 8.00);
There is already a function defined inside user Model that provides fte for user

2023-02-23 17:42 UTC, GauravGusain98 commented on app/Http/Controllers/HomeController.php
> +        $name = auth()->user()->name;
auth()->user() will give you user object which contains all data i.e id, name, email, etc. related to the user

2023-02-23 17:42 UTC, GauravGusain98 commented on resources/views/home.blade.php
> +            <span>Your FTE: <b style="color : red;">{{$FTE}}</b> </span>
We don't prefer to use style tag in blade file as we use bootstrap classes that are compiled and minified. Please check the variables.scss file to see all the color classes available. You can also check code in other pages to see how we can change the text color

2023-02-23 17:42 UTC, GauravGusain98 commented on app/Http/Controllers/HomeController.php
> +        return view('home')->with(['book' => $unreadBook, 'FTE'=>$FTE]);
You don't have to pass FTE. You can simply use auth()->user() inside blade file

2023-02-23 17:46 UTC, GauravGusain98 commented
There should be proper gap below the text `Your FTE: 0`. Currently, the books card is very close to FTE 
<img width="1009" alt="image" src="https://user-images.githubusercontent.com/54376313/220987781-81642899-2521-4691-991b-61c5060c3625.png">

2023-02-24 09:08 UTC, GauravGusain98 requested changes

2023-02-24 09:08 UTC, GauravGusain98 commented on resources/views/home.blade.php
> +            <span>Your FTE: <b class = 'text-danger'>{{$data}}</b> </span>
```suggestion
            <span>Your FTE: <b class='text-danger'>{{$data}}</b> </span>
```

2023-02-24 09:32 UTC, Priyanka-Kaintura commented on resources/views/home.blade.php
> +        @if (($data = auth()->user()->ftes['main']) < 1)
I actually could not find any function in User model which gives FTE, however I saw this implementation in one of the views named 'fte-handler.blade.php' and so tried using it.

2023-02-24 10:38 UTC, Priyanka-Kaintura commented on resources/views/home.blade.php
> +            <span>Your FTE: <b class = 'text-danger'>{{$data}}</b> </span>
Okay sir, I will do that.

2023-02-25 13:40 UTC, Priyanka-Kaintura commented on resources/views/home.blade.php
> +        @if (($data = auth()->user()->ftes['main']) < 1)
Sir I checked the code as suggested and the method is present in the following directory: 'Modules/User/Entities/User.php' with name 'getFtesAttribute()'which returns and saves ftes as an attribute of the user, which has two key value pair: one is main or current fte while other is amc. so fte['main] gives the user's current fte. So I  think this isn't a wrong way to get user current fte

2023-02-27 05:28 UTC, GauravGusain98 commented on resources/views/home.blade.php
> +        @if (($data = auth()->user()->ftes['main']) < 1)
Ok Let me check.

2023-02-27 14:23 UTC, GauravGusain98 approved these changes
LGTM

2023-02-27 14:24 UTC, GauravGusain98 requested changes
Please check the comment

2023-02-27 14:24 UTC, GauravGusain98 commented on resources/views/home.blade.php
> +        @if (($data = auth()->user()->ftes['main']) < 1)
Why initializing a variable inside if condition?

2023-03-02 06:11 UTC, GauravGusain98 requested changes
Please check comment

2023-03-02 06:11 UTC, GauravGusain98 commented on resources/views/home.blade.php
> +    </div>
```suggestion
    <div>
        <span>Your FTE: <b class="{{ auth()->user()->ftes['main'] < 1 ? 'text-danger' : 'text-success' }}">{{auth()->user()->ftes['main'] }}</b> </span>
    </div>
```

2023-03-02 06:11 UTC, GauravGusain98 commented on resources/views/home.blade.php
> +    </div>
Also add a proper margin bottom so that the FTE should have proper spacing with below section

2023-03-02 10:38 UTC, GauravGusain98 approved these changes
LGTM

2023-03-02 10:39 UTC, merged