Show previous month invoice amount and hours while sending the invoice
ColoredCow/portal pull request #2829
Opened 2023-02-20 12:10 UTC by Gauravchamoli1997

Targets #2676
- Firstly Inside the Invoices/Resource/views/modals folder I  create automatic-invoice-details.blade.php file and Fill the dummy data inside the modal.
- Then  Now on the invoice page for every ready-to-send invoices (project level) I create an arrow button that will open the modal when pressed and also have to include the modal page in the page.
- Now inside the modal I print the name of the project for which we have opened it.
- In the modal, set header as <Project Name> Invoice Details.
- After that I create a table inside the modal body and works as requirement.

- [ ] I have performed a self-review of my own code.

2023-02-24 09:10 UTC, GauravGusain98 commented
Testing Feedbacks
- The table data is interchanged. You're showing previous month data in current month column and vice versa. Please correct it
- The previous invoice amount and hours are not coming correct

2023-02-27 14:33 UTC, GauravGusain98 requested changes
Please check the comment

2023-02-27 16:21 UTC, Gauravchamoli1997 commented on Modules/Client/Entities/Client.php
> +    }
Yes , we can directly take the last invoice and get the sent on date from there. That time I don't know about it so I create a Function to get previousBillingDate of invoice through database.

2023-02-27 16:24 UTC, Gauravchamoli1997 commented on Modules/Invoice/Resources/views/index.blade.php
> +                                                href="#"><big><i class="ml-10 fa fa-external-link-square "></i></big>
@GauravGusain98 

> The alignment of the icon is not correct. Either it should be at right or a space after the amount <img alt="image" width="351" src="https://user-images.githubusercontent.com/54376313/221591565-f3e743fc-b11a-438c-9ad0-dc08e243f6ea.png">

I will Fix it.

2023-02-27 16:55 UTC, Gauravchamoli1997 commented
Is this look fine or I have to change this again
![Screenshot (70)](https://user-images.githubusercontent.com/121275531/221628400-ec120e86-8a28-4c05-a3f8-1338f6c49d79.png)

2023-05-08 12:31 UTC, closed without merging