Containerized portal
ColoredCow/portal pull request #2835
Opened 2023-02-21 12:45 UTC by Mrigesh901

Prerequisites: 
 -Docker and docker-compose
 
Installation guide is yet to be written.
Script to automate the installation is yet to be written.

2023-03-02 07:03 UTC, Satendra-SR requested changes
@Mrigesh901 added a few comments/suggestions. Have a look

2023-03-02 07:03 UTC, Satendra-SR commented on docs/prerequisites.md
> +### 2. You can take one of the following two paths:-
```suggestion
### 2. Installation options
The portal can be installed in two following ways. If you are familiar with Docker, please choose option 1 below, otherwise go with option 2
```

2023-03-02 07:03 UTC, Satendra-SR commented on docs/prerequisites.md
> +# Lets begin with the Docker setup:
```suggestion
#### Lets begin with the Docker setup:
```

2023-03-02 07:03 UTC, Satendra-SR commented on docs/installation.md
> +    - For Docker users:
Let's break the guild into two part
1. Dockerized setup
2. Non-dockerized setup

2023-03-02 07:03 UTC, Satendra-SR commented on docs/installation.md
> +    - For Docker users:
This way, we can differential between the two. This guild should say to choose only one option, not all

2023-03-13 09:45 UTC, Mrigesh901 commented on Dockerfile
> +ARG NODE_VERSION=18
Changed to version 16

2023-03-13 09:46 UTC, Mrigesh901 commented on Dockerfile
> +ENV TZ=UTC
UTC is the default in most Docker containers, changed to to Asia/Kolkata

2023-03-13 10:06 UTC, Mrigesh901 commented on docker-compose.yml
> +        image: 'mysql/mysql-server:8.0'
MYSQL version is not specified in the prerequisites, it is coming packaged with xampp or other stacks.
mysql-server:8.0 is running smoothly in our case.

2023-05-08 12:39 UTC, closed without merging