HR update scheduled
ColoredCow/portal pull request #2845
Opened 2023-02-24 06:13 UTC by Adarsh123Singh

Targets #2817 

### Description
HR update schedule throwing error 500

2023-02-24 06:31 UTC, GauravGusain98 commented on resources/views/hr/application/details.blade.php
> +                                    <label for="scheduled_" class="fz-14 leading-none text-secondary w-100p">
The value of `for` attribute is not correct. Please read about `for` attributes in HTML

2023-02-24 06:31 UTC, GauravGusain98 commented on resources/views/hr/application/details.blade.php
> +                                        <input type="date"
Why you changed this? What is difference between `datetime-local` and `date` type?

2023-02-24 06:31 UTC, GauravGusain98 commented on resources/views/hr/application/details.blade.php
> +                                            value="{{ $applicationRound['0']->scheduled_date->format(config('constants.date_format')) }}">
Do we need date along with time or only date here?

2023-02-24 06:31 UTC, GauravGusain98 commented on resources/views/hr/application/details.blade.php
> +                                </div>
What added this? I guess this issue was related to a bug fix. So is it needed to add a new field?

2023-02-24 07:43 UTC, Adarsh123Singh commented on resources/views/hr/application/details.blade.php
> +                                        <input type="date"
Both, datetime-local & date are diff. because in datetime-local locate a values of scheduled_date and scheduled_time but date locate the value scheduled_date in given programme.

2023-02-24 07:53 UTC, Adarsh123Singh commented on resources/views/hr/application/details.blade.php
> +                                            value="{{ $applicationRound['0']->scheduled_date->format(config('constants.date_format')) }}">
We need only date because here we separate format of date and time in given programme.

2023-02-24 09:16 UTC, Adarsh123Singh commented on resources/views/hr/application/details.blade.php
> +                                </div>
In this task, I added new field. Yes, it is needed to add a new field because Scheduled Time is not given in dd($attr); and it is needed to debug which is given in our task.

2023-02-25 09:29 UTC, GauravGusain98 requested changes
left a comment

2023-03-04 09:44 UTC, GauravGusain98 approved these changes
LGTM

2023-03-04 09:45 UTC, merged