added operations module
ColoredCow/portal pull request #2847
Opened 2023-02-24 18:06 UTC by Harshvardhan80

Targets #2783 

### Description

### Checklist:

- [x] I have performed a self-review of my own code.

2023-02-28 06:25 UTC, GauravGusain98 requested changes
Along with the feedbacks, also Remove package-lock.json file changes.

2023-02-28 06:25 UTC, GauravGusain98 commented on Modules/Operations/Resources/views/layouts/master.blade.php
> +</html>
This is not correct way to create a page. please check logic in other modules

2023-02-28 06:55 UTC, Harshvardhan80 commented on Modules/Operations/Resources/views/layouts/master.blade.php
> +</html>
ok sir

2023-03-02 18:07 UTC, GauravGusain98 requested changes

2023-03-02 18:07 UTC, GauravGusain98 commented on resources/views/index.blade.php
> +@extends('layouts.app')
The blade file corresponding to Operations should be inside operation module

2023-03-02 18:07 UTC, GauravGusain98 commented on resources/views/index.blade.php
> +@extends('layouts.app')
This file is not needed

2023-03-02 18:07 UTC, GauravGusain98 commented on resources/views/layouts/navbar.blade.php
> +                <a class="dropdown-item" href="{{ url('/operations') }}">Office location</a>
We use route for URLs. PLease use route function

2023-03-24 06:37 UTC, closed without merging