Add Functionality to send a mail to HR email on completion 3 days
ColoredCow/portal pull request #2849
Opened 2023-02-27 13:42 UTC by race45

Targets #2846 

### Description

When the functionality is executed every day, it should check if any application form is pending for 3 days it will send an email to HR. it should provide a summary of the total number of job and internship applications received. It should also provide a detailed list of all the applications received

### Checklist:

- [x] I have performed a self-review of my own code.

2023-03-02 05:57 UTC, GauravGusain98 requested changes
Left a few comments, please check

2023-03-02 05:57 UTC, GauravGusain98 commented on resources/views/emails/applicants_before_three_days.blade.php
> +                    <td><a href="http://portal.test/hr/recruitment/applicant/details/show/{{ $applicant->id }}">{{ $applicant->name }}</a></td>
why added this URL. It is your local URL. Please use route function with route name

2023-03-02 05:57 UTC, GauravGusain98 commented on resources/views/emails/applicants_before_three_days.blade.php
> +    Please find below a table summarizing the applicants' details:</p>
Can you share the screenshot of email that you are getting in MailTrap

2023-03-02 05:57 UTC, GauravGusain98 commented on app/Mail/ApplicantsSubmittedBeforeThreeDays.php
> +        $count = $this->screeningApplicants->count();
```suggestion
```

2023-03-02 05:57 UTC, GauravGusain98 commented on app/Mail/ApplicantsSubmittedBeforeThreeDays.php
> +        $subject = "$count applicants submitted their application before 3 days.";
```suggestion
        $subject = "Applications in resume screening round for more than 3 days.";
```

2023-03-02 05:57 UTC, GauravGusain98 commented on app/Console/Kernel.php
> +        $schedule->command('hr:send-mail-to-hr')->dailyAt('10:00');
```suggestion
        $schedule->command('hr:resume-screening-application-review-reminder')->dailyAt('10:00');
```

2023-03-02 05:57 UTC, GauravGusain98 commented on app/Mail/ApplicantsSubmittedBeforeThreeDays.php
> +class ApplicantsSubmittedBeforeThreeDays extends Mailable
```suggestion
class ResumeScreeningPendingApplication extends Mailable
```

2023-03-02 05:57 UTC, GauravGusain98 commented on app/Mail/ApplicantsSubmittedBeforeThreeDays.php
> +class ApplicantsSubmittedBeforeThreeDays extends Mailable
Also update the file name

2023-03-02 05:57 UTC, GauravGusain98 commented on app/Console/Commands/ManageApplications.php
> +    protected $signature = 'hr:send-mail-to-hr';
```suggestion
    protected $signature = 'hr:resume-screening-application-review-reminder';
```

2023-03-02 05:57 UTC, GauravGusain98 commented on app/Console/Commands/ManageApplications.php
> +    protected $description = 'This will check every morning';
```suggestion
    protected $description = 'This command will trigger mail to HR reminding him to review applications that are in resume screening round for more than 3 days';
```

2023-03-02 05:57 UTC, GauravGusain98 commented on app/Console/Commands/ManageApplications.php
> +        // Get the current date/time
Add comments only when the code is not able to make it clear
```suggestion
```

2023-03-02 05:57 UTC, GauravGusain98 commented on app/Console/Commands/ManageApplications.php
> +        // Calculate the date/time 3 days ago
```suggestion
```

2023-03-02 05:57 UTC, GauravGusain98 commented on app/Console/Commands/ManageApplications.php
> +                    ->where('hr_applications.status', config('hr.status.new.label'))
Have we stored label in database?

2023-03-02 05:57 UTC, GauravGusain98 commented on app/Console/Commands/ManageApplications.php
> +            Mail::to(env('MAIL_FROM_ADDRESS'))->send(new ApplicantsSubmittedBeforeThreeDays($screeningApplicants));
Don't fetch variable directly from env. You need to add them to config and fetch the value from config.

2023-03-02 05:57 UTC, GauravGusain98 commented on app/Console/Commands/ManageApplications.php
> +            Mail::to(env('MAIL_FROM_ADDRESS'))->send(new ApplicantsSubmittedBeforeThreeDays($screeningApplicants));
Also the env variable that you are using is incorrect. You have to use `HR_FOLLOWUP_EMAIL_PRIMARY` and for name you can use `HR_DEFAULT_FROM_NAME`

2023-03-02 06:16 UTC, race45 commented on resources/views/emails/applicants_before_three_days.blade.php
> +    Please find below a table summarizing the applicants' details:</p>
![image](https://user-images.githubusercontent.com/92683476/222346521-aefe8804-aea9-4943-9c92-af548e6f53b5.png)

2023-03-03 10:17 UTC, GauravGusain98 commented on resources/views/emails/applicants_before_three_days.blade.php
> +                <br> <strong>Applied on -</strong> {{ \Carbon\Carbon::parse($applicant->created_at)->format('j M Y') }}</li>
I think this will also work. Please test with this once
```suggestion
                <br> <strong>Applied on -</strong> {{ $applicant->created_at->format('j M Y') }}</li>
```

2023-03-03 10:17 UTC, GauravGusain98 commented on resources/views/emails/applicants_before_three_days.blade.php
> +                <br> <strong>Applied on -</strong> {{ \Carbon\Carbon::parse($applicant->created_at)->format('j M Y') }}</li>
Can you share the email screenshot in Github comment

2023-03-03 10:18 UTC, GauravGusain98 commented on resources/views/emails/applicants_before_three_days.blade.php
> +<div>
Update file name to `application_in_resume_screening_reminder`

2023-03-03 10:19 UTC, GauravGusain98 commented on Modules/HR/Config/config.php
> +        'name' => env('HR_DEFAULT_FROM_NAME', 'ColoredCow Portal'),
```suggestion
        'name' => env('HR_DEFAULT_FROM_NAME', 'ColoredCow HR'),
```

2023-03-03 10:19 UTC, GauravGusain98 commented on Modules/HR/Config/config.php
> +        'primary' => env('HR_FOLLOWUP_EMAIL_PRIMARY'),
Keep it as default as well
```suggestion
        'primary' => env('HR_FOLLOWUP_EMAIL_PRIMARY', 'hr@coloredcow.com'),
```

2023-03-03 10:21 UTC, GauravGusain98 commented on resources/views/emails/applicants_before_three_days.blade.php
> +        @foreach ($applicants as $applicant)
I think here you should get application instead of applicant.

2023-03-03 10:22 UTC, GauravGusain98 commented on app/Console/Commands/ManageApplications.php
> +                    ->get();
$applications = Application::with('applicant')->where('status',  config('hr.status.new'))
    ->where('hr_applications.created_at', '<', $threeDaysAgo)
    ->get()

2023-03-03 10:23 UTC, GauravGusain98 commented on app/Console/Commands/ManageApplications.php
> +                    ->get();
Then from application you can easily get applicant detail using relationship

2023-03-03 10:35 UTC, race45 commented on resources/views/emails/applicants_before_three_days.blade.php
> +                <br> <strong>Applied on -</strong> {{ \Carbon\Carbon::parse($applicant->created_at)->format('j M Y') }}</li>
![image](https://user-images.githubusercontent.com/92683476/222698470-3fc87c13-9240-49f9-a15b-69b7ee0dd8ce.png)

2023-03-03 13:35 UTC, race45 commented on resources/views/emails/applicants_before_three_days.blade.php
> +                <br> <strong>Applied on -</strong> {{ \Carbon\Carbon::parse($applicant->created_at)->format('j M Y') }}</li>
<br> <strong>Applied on -</strong> {{ $applicant->created_at->format('j M Y') }}</li>. that code was not working. 
![image](https://user-images.githubusercontent.com/92683476/222733576-086c7695-55f2-418b-9918-837173485946.png)

2023-03-06 05:51 UTC, GauravGusain98 requested changes
Remove Composer.lock file from your code changes

2023-03-06 05:52 UTC, GauravGusain98 requested changes

2023-03-06 05:52 UTC, GauravGusain98 commented on app/Console/Commands/ManageApplications.php
> +        }
Why used this when you are not using it anywhere.

2023-03-13 14:41 UTC, GauravGusain98 requested changes
Can you remove the changes done to composer.lock file. Just copy the code from master branch and paste it in the file and push it.

Also check the comment that are shared

2023-03-13 14:41 UTC, GauravGusain98 commented on app/Console/Commands/ManageApplications.php
> +        $now = now();
Not needed
```suggestion
```

2023-03-13 14:41 UTC, GauravGusain98 commented on app/Console/Commands/ManageApplications.php
> +        $threeDaysAgo = $now->subDays(3);
```suggestion
        $threeDaysAgo = now()->subDays(3);
```

2023-03-15 08:34 UTC, GauravGusain98 requested changes
Please check the comments

2023-03-15 08:34 UTC, GauravGusain98 commented on resources/views/emails/application_in_resume_screening_reminder.blade.php
> +            <li><strong>Name -</strong><a href="route(hr/recruitment/applicant/details/show/{{ $application->applicant->id }} )">{{ $application->applicant->name }}</a>
Instead of passing URL, please use route name

2023-03-15 08:34 UTC, GauravGusain98 commented on app/Console/Commands/ManageApplications.php
> +            Mail::to(config('hr.hr-email.primary'))->send(new ResumeScreeningPendingApplication($applications));
Instead of using send message, you can use queue method

2023-03-15 08:34 UTC, GauravGusain98 commented on app/Console/Kernel.php
> +        $schedule->command('hr:resume-screening-application-review-reminder')->dailyAt('10:00');
I want this command to only run on production environment. You can use something like this
<img width="862" alt="image" src="https://user-images.githubusercontent.com/54376313/225252183-e236aa6d-6f10-4071-90a8-4a10ad9020e3.png">

2023-05-08 12:40 UTC, closed without merging