added operations modules
ColoredCow/portal pull request #2869
Opened 2023-03-11 07:50 UTC by Harshvardhan80

2023-03-13 13:51 UTC, GauravGusain98 commented on Modules/Operations/Resources/views/index.blade.php
> +@extends('operations::layouts.master')
You should move this file inside Module/Operations/Resources/views/office-location and create index file inside that. Then in controller as well you should call that file.

2023-03-13 13:52 UTC, GauravGusain98 commented on Modules/Operations/Routes/web.php
> +    Route::get('/', 'operationsController@index')->name('office_location.index');
the url should be `operation/office-location`

2023-03-13 13:53 UTC, GauravGusain98 commented on resources/views/layouts/navbar.blade.php
> +    @can('operations.view')
Where is this permission created. You need to create this permission and assign this permission to `admin` and `super-admin`

2023-03-13 13:54 UTC, GauravGusain98 commented on resources/views/layouts/navbar.blade.php
> +    @can('operations.view')
Check how we have created other permissions and assign them to different role.

2023-03-24 19:19 UTC, Harshvardhan80 commented on resources/views/layouts/navbar.blade.php
> +    @can('operations.view')
i have done

2023-03-24 19:22 UTC, Harshvardhan80 commented on Modules/Operations/Resources/views/index.blade.php
> +@extends('operations::layouts.master')
i have done

2023-03-26 18:48 UTC, GauravGusain98 requested changes
minor suggestions please check

2023-03-26 18:48 UTC, GauravGusain98 commented on Modules/Operations/Routes/web.php
> +    Route::get('/operations/office_location', 'operationsController@index')->name('office-location.index');
As per your implementation, the URL for this route will become `operations/operations/office_location` but it should be `operations/office_location`

2023-03-26 18:48 UTC, GauravGusain98 commented on composer.lock
We don't need any changes in this file. So please revert the changes done to this file

2023-03-26 18:48 UTC, GauravGusain98 commented on package-lock.json
We don't need any changes in this file. So please revert the changes done to this file

2023-03-26 18:48 UTC, GauravGusain98 commented on Modules/Operations/Database/Seeders/OperationsDatabaseSeeder.php
> +
I think here you need to call the `OperationsPermissionTableSeeder`. Check other modules like Project, HR etc.

2023-05-22 13:29 UTC, closed without merging