Set default value of invoices
ColoredCow/portal pull request #2871
Opened 2023-03-13 12:09 UTC by Hemrajbharti123

Targets #2866 

Description
In this task we do that  Set the default value of

 invoice term start date as 1st of previous month

 invoice term end date as last day of previous month

Checklist:
- [ ] I have performed a self-review of my own code.

2023-03-13 12:29 UTC, Hemrajbharti123 commented
The value of term start date and term end date has been set as demanded above which you can see in the UI.

![Screenshot (3)](https://user-images.githubusercontent.com/121417679/224702172-483d2b38-0371-4a8d-8725-79c646b9f2e3.png)

2023-03-13 12:31 UTC, Hemrajbharti123 commented
If we change the values that were set by default.
![Screenshot (4)](https://user-images.githubusercontent.com/121417679/224702547-8744031a-1404-4c6e-b7f1-334752852f20.png)

2023-03-13 14:03 UTC, GauravGusain98 requested changes
Please check the comment

2023-03-13 14:03 UTC, GauravGusain98 commented on Modules/Invoice/Resources/views/subviews/create/invoice-details.blade.php
> +                           value="{{ \Carbon\Carbon::now()->subMonth()->startOfMonth()->toDateString() }}">
Use `subMonthNoOverflow` function instead of subMonth as subMonth() function subtract 30 days from date, this  sometimes subtract 2 months instead of 1 month incase of February as it has 28 days only.  The subMonthNoOverflow() function takes care of it and only subtract 1 month.

```suggestion
                           value="{{ now()->subMonthNoOverflow()->startOfMonth()->toDateString() }}">
```

2023-03-13 14:03 UTC, GauravGusain98 commented on Modules/Invoice/Resources/views/subviews/create/invoice-details.blade.php
> +                           value="{{ \Carbon\Carbon::now()->subMonth()->endOfMonth()->toDateString() }}">
now() is be default treated as a carbon function 
```suggestion
                           value="{{ now()->subMonthNoOverflow()->endOfMonth()->toDateString() }}">
```

2023-03-14 06:05 UTC, GauravGusain98 approved these changes
LGTM

2023-03-14 06:05 UTC, merged