added applicant evaluation page
ColoredCow/portal pull request #2876
Opened 2023-03-15 07:13 UTC by nishant22029

Targets #{ISSUE_ID}

### Description

Added evaluation page for applicants to evaluate thier levels with thier feedbacks .

### Checklist:

- [x] I have performed a self-review of my own code.

2023-03-23 04:09 UTC, Hemrajbharti123 commented
I have checked all the functionality everything is working fine please do a big check too

2023-03-23 04:10 UTC, Hemrajbharti123 commented
![image](https://user-images.githubusercontent.com/121417679/227100874-a991d7cc-a0b0-41f8-a029-eaf51c409dff.png)

2023-03-23 04:11 UTC, Hemrajbharti123 commented
![image](https://user-images.githubusercontent.com/121417679/227100975-0f5b3d4b-bd56-4857-a808-2d5aeb12dae4.png)


![image](https://user-images.githubusercontent.com/121417679/227101029-08eedd5f-3e9e-4770-85cc-e87eac5011bc.png)

2023-03-23 04:12 UTC, Hemrajbharti123 commented
![image](https://user-images.githubusercontent.com/121417679/227101124-9dfbac88-7876-4f3d-899d-d263a81c6d50.png)

2023-03-27 11:57 UTC, Hemrajbharti123 commented
![image](https://user-images.githubusercontent.com/121417679/227934937-1d1ff397-8966-4c87-a5c7-ca55ef5ce7bb.png)

2023-03-28 07:44 UTC, GauravGusain98 commented on Modules/CodeTrek/Resources/views/evaluate.blade.php
> +                                             <option value="level-3">Move to Level 3</option>
take round name and values from config. If in future we want to change name of a level or add new level then we just need to update the config.

2023-03-28 07:44 UTC, GauravGusain98 commented on Modules/CodeTrek/Resources/views/evaluate.blade.php
> +                                                         if ($roundDetail->round_name == 'level-1') {
Take it from config

2023-03-28 07:45 UTC, GauravGusain98 commented on Modules/CodeTrek/Resources/views/evaluate.blade.php
> +                                             data-target="#confirm-delete">Remove Applicant</button>
We don't need remove applicant flow here

2023-03-28 07:48 UTC, GauravGusain98 commented on Modules/CodeTrek/Resources/views/evaluate.blade.php
> +                     @if ($roundDetail->round_name == 'level-1')
You should not add a check for each round and duplicate the code. Its a bad practice. Try to make it more optimized and dynamic.

2023-03-28 07:49 UTC, GauravGusain98 commented on Modules/CodeTrek/Routes/web.php
> +    Route::post('/update-feedback/{applicant}', 'CodeTrekApplicantRoundDetailController@update')->name('codetrek.update-feedback');
should it be applicant or applicantDetail?

2023-03-28 08:03 UTC, Hemrajbharti123 commented on Modules/CodeTrek/Routes/web.php
> +    Route::post('/update-feedback/{applicant}', 'CodeTrekApplicantRoundDetailController@update')->name('codetrek.update-feedback');
it should be applicantDetail because we are updating or evaluating the applicant details

2023-03-28 08:05 UTC, Hemrajbharti123 commented
ok i will try to do the changes you suggest

2023-03-29 12:58 UTC, Hemrajbharti123 commented on Modules/CodeTrek/Routes/web.php
> +    Route::post('/update-feedback/{applicant}', 'CodeTrekApplicantRoundDetailController@update')->name('codetrek.update-feedback');
sir we are sending applicant id so we are using applicant instead of applicantdetails

2023-03-30 19:58 UTC, GauravGusain98 requested changes
Please check the comment. Don't use repititive code and make it dynamic

2023-03-30 19:58 UTC, GauravGusain98 commented on Modules/CodeTrek/Config/config.php
> +            'label' =>'Move to Level-1',
It should be `Level-1`. You can ass the text `Move to` at the place where you are printing this text

2023-03-30 19:58 UTC, GauravGusain98 commented on Modules/CodeTrek/Routes/web.php
> +    Route::post('/update-feedback/{applicant}', 'CodeTrekApplicantRoundDetailController@update')->name('codetrek.update-feedback');
But why you sending applicant. How you will know which applicant Detail you want to update if the round name of both applicantDetail are same

2023-03-30 19:58 UTC, GauravGusain98 commented on Modules/CodeTrek/Resources/views/evaluate.blade.php
> +                             <div class="ml-auto">Started at:-{{ $roundDetail->start_date }}</div>
I think this should be using a loop, because if I add new round in config then it will not be added here. Therefore, this logic is not dynamic in nature, please make it dynamic

2023-03-30 19:58 UTC, GauravGusain98 commented on Modules/CodeTrek/Resources/views/evaluate.blade.php
> +                                         <br>
make it dynamic

2023-03-30 19:58 UTC, GauravGusain98 commented on Modules/CodeTrek/Resources/views/evaluate.blade.php
> +                                             {{ config('codetrek.rounds.onboard.label') }}</option>
Use loop instead of this.

2023-03-30 19:58 UTC, GauravGusain98 commented on Modules/CodeTrek/Http/Controllers/CodeTrekApplicantRoundDetailController.php
> +    public function update(Request $request, $id)
Read [route modal binding](https://laravel.com/docs/8.x/routing#route-model-binding) concept and implement that here. That way you don't have to find the applicant object using id inside service

2023-03-31 05:10 UTC, Hemrajbharti123 commented
ok i will try to do the changes you suggest

2023-04-04 08:05 UTC, GauravGusain98 requested changes
Please check the comments.

2023-04-04 08:05 UTC, GauravGusain98 commented on database/migrations/2023_03_21_111928_add_started_date_to_codetrek_applicant_round_details.php
> +        });
If you have added a column in up() function then in down() function you should remove that column only instead of removing the whole table. This will throw error as the table will not be found in the migration where the table is created as it will also try to drop the table if down() function is called in that migration.

2023-04-04 08:05 UTC, GauravGusain98 commented on Modules/CodeTrek/Resources/views/index.blade.php
> +                            <th class="col-md-2"> Days in CodeTrek</th>
Can you also show the data in the column `Days in CodeTrek`

2023-04-04 08:05 UTC, GauravGusain98 commented on Modules/CodeTrek/Resources/views/index.blade.php
> +                            <th class="col-md-2"> Days in CodeTrek</th>
```suggestion
                            <th class="col-md-2">Days in CodeTrek</th>
```

2023-04-04 08:05 UTC, GauravGusain98 commented on Modules/CodeTrek/Resources/views/index.blade.php
> +                            <th> Status</th>
```suggestion
                            <th>Status</th>
```

2023-04-04 08:05 UTC, GauravGusain98 commented on Modules/CodeTrek/Resources/views/evaluate.blade.php
> +                             @endforeach
correct the indentation

2023-04-04 08:05 UTC, GauravGusain98 commented on Modules/CodeTrek/Resources/views/evaluate.blade.php
> +                                     <h4>{{ $applicant->first_name }} {{ $applicant->last_name }}</h4>
can you decrease the font size of all the values. maybe use <h5>

2023-04-04 11:36 UTC, Hemrajbharti123 commented on Modules/CodeTrek/Services/CodeTrekService.php
> +    }
round_name is already updated in applicant table

![image](https://user-images.githubusercontent.com/121417679/229779333-4bf2590d-8b9f-48f5-9a25-ed548a48179b.png)

![image](https://user-images.githubusercontent.com/121417679/229779397-6bd6244d-087a-4d50-9a41-543cd6879f79.png)

2023-04-04 12:41 UTC, GauravGusain98 approved these changes
LGTM

2023-04-04 12:41 UTC, merged