Show correct velocity of team members according to their added on data in a project
ColoredCow/portal pull request #2883
Opened 2023-03-16 15:52 UTC by Gauravchamoli1997

Targets #2877
### Description
Previously, the velocity of a team members is calculated from the start date of the project billing cycle . This doesn't depends on whether the team members are added in middle of the month or at the end of the month. Due to this the velocity of new members does not come correct in the first month. But now the velocity of  team members is calculated from the started_on date in the project for first month only  if team member team member is added in the middle of the month.

### Checklist:
- [ ] I have performed a self-review of my own code.

2023-03-16 16:49 UTC, GauravGusain98 requested changes
Please check the comment

2023-03-16 16:49 UTC, GauravGusain98 commented on Modules/Project/Entities/ProjectTeamMember.php
> +        return $this->projectTeamMemberEffort()->where('added_on', '>=', $this->started_on)->where('added_on', '>=', $startDate)->sum('actual_effort');
I think this was correct earlier. We don't need to make any change to this function because if we keep the start date before the team member was added to project, it will not affect the actual effort.

2023-03-16 16:49 UTC, GauravGusain98 commented on Modules/Project/Entities/ProjectTeamMember.php
> +        }
Why you are calculating the days till today 2 times. It can be made more optimized. Just calculate start date first based on different cases and then calculate the days till today

2023-03-16 17:19 UTC, Gauravchamoli1997 commented on Modules/Project/Entities/ProjectTeamMember.php
> +        }
Ok i will work on it.

2023-03-16 17:53 UTC, Gauravchamoli1997 commented
This is my updated code . 
![image](https://user-images.githubusercontent.com/121275531/225709152-ee227dcd-e168-4d3f-b835-6101e1b67b70.png)

2023-03-16 18:18 UTC, GauravGusain98 requested changes
Please check the comment

2023-03-16 18:18 UTC, GauravGusain98 commented on Modules/Project/Entities/ProjectTeamMember.php
> +            $startDate = $this->started_on;
The start date will aways be team member added on date as started_on date will always be greater than null because the initial value of startDate is null. 

Due to this logic the expected efforts are coming very high  
<img width="229" alt="image" src="https://user-images.githubusercontent.com/54376313/225715836-b5929cf0-219a-47d0-9be9-96f65fca5e19.png">

2023-03-16 18:37 UTC, Gauravchamoli1997 commented on Modules/Project/Entities/ProjectTeamMember.php
> +            $startDate = $this->started_on;
@GauravGusain98 I think the expected efforts are coming very high due to this ```$this->started_on > $startDate``` . I think I have to take this ```$this->started_on > $this->project->client->month_start_date``` in the place of ```$this->started_on > $startDate```

2023-03-16 18:45 UTC, GauravGusain98 commented on Modules/Project/Entities/ProjectTeamMember.php
> +            $startDate = $this->started_on;
Ok the try and check if it is working or not

2023-03-17 05:29 UTC, Gauravchamoli1997 commented on Modules/Project/Entities/ProjectTeamMember.php
> +            $startDate = $this->started_on;
@GauravGusain98 It is working correctly in my system.
![image](https://user-images.githubusercontent.com/121275531/225819115-6309eac7-07b3-4b8f-b345-ad90d278c0d2.png)

2023-03-17 06:40 UTC, GauravGusain98 approved these changes
LGTM

2023-03-17 06:40 UTC, merged