Automated notification to update the efforts sheet before billing date.
ColoredCow/portal pull request #2907
Opened 2023-03-27 09:44 UTC by Himanshunegi0332

Targets #2895 
### Description
Currently, we don't have any automated notification system feature which tells to update the efforts sheet of a project to avoid last minutes updates at the end of the billing cycle.
So, created an automated notification system telling all active project members to update the efforts sheet to avoid last minutes updates.

### Checklist:
- [X] I have performed a self-review of my own code.

2023-03-27 13:33 UTC, GauravGusain98 requested changes

2023-03-27 13:33 UTC, GauravGusain98 commented on Modules/Project/Notifications/GoogleChat/NotificationToUpdateEffortForProject.php
> +                $interval = date_diff(today(), $date);
The interval is not correct. It gives 1 in both -ve and +ve case. So please correct that.

2023-03-28 05:07 UTC, GauravGusain98 requested changes
please check the comment

2023-03-28 05:07 UTC, GauravGusain98 commented on Modules/Project/Notifications/GoogleChat/NotificationToUpdateEffortForProject.php
> +            $interval = (strtotime($date) - strtotime(today())) / (60 * 60 * 24);
This approach is not clean. You can use carbon Class to get difference

Just check Carbon::tomorrow() == $date

2023-03-28 05:08 UTC, GauravGusain98 commented on Modules/Project/Notifications/GoogleChat/NotificationToUpdateEffortForProject.php
> +            $interval = (strtotime($date) - strtotime(today())) / (60 * 60 * 24);
Whenever you are dealing with time try to find the function corresponding to your requirement in the Carbon Package

2023-03-28 06:12 UTC, Himanshunegi0332 commented on Modules/Project/Notifications/GoogleChat/NotificationToUpdateEffortForProject.php
> +            $interval = (strtotime($date) - strtotime(today())) / (60 * 60 * 24);
ok sir, sorry for the mistake.

2023-03-28 07:09 UTC, GauravGusain98 approved these changes
LGTM

2023-03-28 07:09 UTC, merged