Add new book button overlapping fixed
ColoredCow/portal pull request #2926
Opened 2023-04-01 12:30 UTC by akshatsemwal146

Targets #{ISSUE_ID}

### Description

### Checklist:

- [ ] I have performed a self-review of my own code.

2023-04-10 11:37 UTC, GauravGusain98 commented
I think this is not looking correct.
1. The font size of `Books(count)` can be reduced so that the button text should come in one line
2. The margin below the `Books(count)` can be reduced 
4. Also the button text font size can be reduced so that the button size does not become too large
5. The margin bottom between search and sort fields can be reduced in mobile screens. Currently they are too far away
6. The space on the right side of books card is greater then left side. So the card can be placed in between for better UI
<img width="453" alt="image" src="https://user-images.githubusercontent.com/54376313/230893900-060bf481-2c45-4a6c-8903-89b227cbdd9f.png">
<img width="795" alt="image" src="https://user-images.githubusercontent.com/54376313/230894356-c138b300-d6c0-4b00-840c-cce2f63a3a0c.png">

2023-04-12 07:57 UTC, Hemrajbharti123 commented
### Local Testing Feedback
The button is still overlapping 

![image](https://user-images.githubusercontent.com/121417679/231390450-96aacf74-572b-4594-aac8-41a5a7191433.png)

2023-04-12 08:02 UTC, Hemrajbharti123 commented
Decrease the size of `short book by category ` 


![image](https://user-images.githubusercontent.com/121417679/231391753-7e6767bf-01cf-448c-9742-1e984a0532b5.png)

2023-04-12 11:04 UTC, Ayush8923 requested changes
Left some comments.

2023-04-12 11:04 UTC, Ayush8923 commented on resources/views/knowledgecafe/library/books/index.blade.php
> +            <a href="{{ route('books.create') }}" class="btn btn-success float-right xs-2"><i class="fa fa-plus mr-1"></i> Add New Book</a>
What are the means of this class `xs-2`? I think this class is not working.
The correct class is this `col-xs-2`
```suggestion
            <a href="{{ route('books.create') }}" class="btn btn-success float-right xs-2"><i class="fa fa-plus mr-1"></i> Add New Book</a>
```

2023-04-15 06:12 UTC, Ayush8923 requested changes
## Testing Feedbacks

**Current Behaviour**
- As far as I can see, the `Books` and the `Search` bar are not aligned, please take refer below screenshot.
<img width="1015" alt="image" src="https://user-images.githubusercontent.com/80516839/232188874-6507e3ea-93c4-4271-8dde-d6c21579dec8.png">
&#8204;

**Expected Behaviour**

<img width="1071" alt="image" src="https://user-images.githubusercontent.com/80516839/232188681-ee630d9d-81ce-4fa1-93ea-644004f480f1.png">

2023-04-18 09:02 UTC, Ayush8923 requested changes
One small comment. else looks good to me.

2023-04-18 09:02 UTC, Ayush8923 commented on resources/views/knowledgecafe/library/books/index.blade.php
> +            <h4>Books({{count($books)}})</h4>
```suggestion
            <h3>Books({{count($books)}})</h3>
```

2023-04-19 05:59 UTC, Ayush8923 approved these changes

2023-04-19 05:59 UTC, merged