feature/2929/add-requisition-button-functionality
ColoredCow/portal pull request #2949
Opened 2023-04-05 12:26 UTC by rahulpanwar16

Targets #2929

### Description

-  Add a requisition button to the project resource page.
- Added a column requested_by in the resource requisition page which contains the user id who have submit a form by clicking add requisition button. 

### Checklist:
- [x] I have performed a self-review of my own code.

2023-04-10 06:15 UTC, GauravGusain98 commented
### Testing Feedbacks
- Requested by column should be before action column. Also it should show the user name instead of id
<img width="1181" alt="image" src="https://user-images.githubusercontent.com/54376313/230838229-1775abc3-9ee2-4bb0-9626-1fb894a7c88f.png">
- On submitting the requisition. The modal simply closes and there is not message or indicator like "Requisition added successfully.". It is currently putting a question in user mind that was his requisition submitted or not.
- The alignment of `+` and `add requisition` is not correct. The `+` icon should be on the left and the text should be on the right side. Also the + icon should be vertically centre aligned 
<img width="215" alt="image" src="https://user-images.githubusercontent.com/54376313/230838785-f8c283c7-2e53-4c1b-97cc-e14b69a77180.png">
- Also make sure that when you are creating requisition from the HR page then also the requested by column should be filled.

2023-04-13 18:45 UTC, GauravGusain98 requested changes
Please check the comments

2023-04-13 18:45 UTC, GauravGusain98 commented on Modules/HR/Http/Controllers/RequisitionController.php
> +            'user' => ['required', 'regex:/^[a-zA-Z]+(\s[a-zA-Z]+)+$/'],
It should be  user_id

2023-04-13 18:45 UTC, GauravGusain98 commented on Modules/HR/Http/Controllers/RequisitionController.php
> +            'requested_by' => $jobrequisition['user'],
We need to store id in this column not name

2023-04-13 18:45 UTC, GauravGusain98 commented on database/migrations/2023_04_05_073848_add_requested_by_to_job_requisition_table.php
> +            $table->string('requested_by')->nullable();
it should be foreign key to users table

2023-04-13 18:45 UTC, GauravGusain98 commented on resources/views/hr/employees/fte-handler.blade.php
> +                            <input type="hidden" name="user" id="user" value="{{ auth()->user()->name }}" pattern="^[a-zA-Z]+(\s[a-zA-Z]+)+$">
simply pass user_id

2023-04-13 18:45 UTC, GauravGusain98 commented on resources/js/app.js
> +				$("#submitSuccessMessage").fadeToggle(4000);
This is not correct way to implement it. Please remove this and use the successMessage approach that is being used everywhere

2023-04-17 06:05 UTC, GauravGusain98 requested changes

2023-04-17 06:05 UTC, GauravGusain98 commented on resources/js/app.js
> +				$("#submitSuccessMessage").fadeToggle(4000);
Why there is a need to add another id instead of using the id $("#successMessage") in your element? It is causing any problem?

2023-04-17 06:05 UTC, GauravGusain98 commented on resources/views/hr/employees/fte-handler.blade.php
> +        <div class="d-none alert alert-success " id="submitSuccessMessage" role="alert">
why you have changed this? Was it not working?

2023-04-17 06:05 UTC, GauravGusain98 commented on resources/views/hr/requisition/index.blade.php
> +                {{ auth()->user()->name }}
It will always show current user in all the requisition. You need to create a relationship function for the requested_by column and then using the relationship you need to fetch the name of the related user

2023-04-18 06:22 UTC, GauravGusain98 requested changes
Please check the comment

2023-04-18 06:22 UTC, GauravGusain98 commented on Modules/HR/Http/Controllers/RequisitionController.php
> +            'user' => 'required|integer',
lets change this to user_id instead of user. Its a bit confusing,

2023-04-18 06:22 UTC, GauravGusain98 commented on Modules/Project/Resources/views/resource-requirement.blade.php
> +                            <button type="submit" class="btn btn-primary" data-action="sendHiringMail">Submit</button>
Why data-action has value `sendHiringMail`? What is it used for?

2023-04-18 06:26 UTC, GauravGusain98 commented
### Testing Feedbacks

- [ ] Fix merge conflicts
- [ ] The submit is taking too much time to process? Please fix it. 
- [ ] No success message is shown when the form is submitted. It creates doubt in user mind whether the requisition was submitted or not.

<img width="887" alt="image" src="https://user-images.githubusercontent.com/54376313/232689292-6f61e836-144d-49c4-abd5-c901966c7f67.png">

2023-04-21 06:20 UTC, GauravGusain98 commented
### Testing Feedbacks
- The success message is not being shown when we submit a second requisition
- Also, can we sue toast message instead of showing alert. its not a good practice to use different approaches for showing alerts. It should be consistent in every page. We use the bootstrap alert earlier but now we always add toast message as an alert.

2023-04-24 05:44 UTC, rahulpanwar16 commented
**Unit Testing**

- Optimized the process time when we submit a requisition. 
- Removed success alert to success toast message on project resource page when we submit a requisition. 
- Success toast message also shown when we submit a second requisition.

![Screenshot (84)](https://user-images.githubusercontent.com/106467597/233908227-20eb958e-d83c-45ee-b2d7-434bfaa00773.png)


Same for fte handler page as well. 
![Screenshot (87)](https://user-images.githubusercontent.com/106467597/233908359-0226defb-1132-4ab8-a8ae-44f12a640244.png)

2023-06-25 15:05 UTC, GauravGusain98 commented on Modules/HR/Jobs/SendHiringMailJob.php
> +        Mail::send(new sendHiringMail($this->jobHiring));
```suggestion
        Mail::queue(new sendHiringMail($this->jobHiring));
```

2023-06-25 15:09 UTC, GauravGusain98 approved these changes
LGTM

2023-06-25 15:09 UTC, merged