feature/2948/add-authorization-for-code-codeTrek-page
ColoredCow/portal pull request #2954
Opened 2023-04-06 08:17 UTC by Hemrajbharti123

Targets #2948 

### Description

So anyone with role employee, admin and super admin should be able to open CodeTrek page. Currently only admin and super admin has CodeTrek option in the menu
If someone is trying to open the page using link then you have implement Laravel policies like we have in invoice module so that if a user does not have permission CodeTrek.view

### Checklist:
- [ ] I have performed a self-review of my own code.

2023-04-06 08:22 UTC, Hemrajbharti123 commented
If an unauthorized user try to open CodeTrek.view directly by using URL this error is shown to him.

![image](https://user-images.githubusercontent.com/121417679/230318082-bff976c5-483e-46c9-9a55-f76fdb2e9e14.png)

2023-04-07 10:04 UTC, GauravGusain98 requested changes
Please check the comment

2023-04-07 10:04 UTC, GauravGusain98 commented on Modules/CodeTrek/Http/Controllers/CodeTrekController.php
> +
Lets use the approach that is used throughout the portal for policies. You can search for invoicePolicy file and see how it is working. Based on it you can implement policies using the Policy file that exists for codetrek

2023-04-10 05:53 UTC, GauravGusain98 approved these changes
LGTM

2023-04-10 05:53 UTC, merged