added a  Round column in Code Trek
ColoredCow/portal pull request #2959
Opened 2023-04-08 06:09 UTC by ShefaliDharwal

Targets #2951 

### Description
Added a round column in the CodeTrek page.

### Checklist:
- [X] I have performed a self-review of my own code.

2023-04-10 08:01 UTC, GauravGusain98 requested changes
Please fix the code

2023-04-10 08:01 UTC, GauravGusain98 commented on Modules/CodeTrek/Resources/views/index.blade.php
> +                            <th>Round</th>
You also need to show value corresponding to each candidate. The code that you have added will just add a column heading but it will not show the values for candidates in that column

2023-04-10 08:03 UTC, ShefaliDharwal commented on Modules/CodeTrek/Resources/views/index.blade.php
> +                            <th>Round</th>
Ok sir

2023-04-25 09:39 UTC, GauravGusain98 requested changes

2023-04-25 09:39 UTC, GauravGusain98 commented on Modules/CodeTrek/Resources/views/index.blade.php
> -            </div>
Why you removed this whole code. It was needed, please correct it.

2023-04-26 09:01 UTC, rahulpanwar16 requested changes
Please check the comments.

2023-04-26 09:01 UTC, rahulpanwar16 commented on Modules/CodeTrek/Resources/views/index.blade.php
> +
Please remove this space

2023-04-26 09:16 UTC, rahulpanwar16 approved these changes

2023-05-22 13:34 UTC, closed without merging