feature/2964/CodeTrek_Applicant_Inactive_Action
ColoredCow/portal pull request #2968
Opened 2023-04-11 07:11 UTC by Hemrajbharti123

Targets #2964 

### Description
There are many interns who get onboarded or leave midway for whatever reason, so no functionality has been built in for those applicants yet the status of all applicants is shown as active.
In the CodeTrek module, we have a button marked inactive Use the same button so that we can inactive the application as well.

### Checklist:
- [ ] I have performed a self-review of my own code.

2023-04-11 07:13 UTC, Hemrajbharti123 commented
Status of applicant 
![image](https://user-images.githubusercontent.com/121417679/231084036-77fa70df-3fd2-46c5-b93d-be1f7500122d.png)

2023-04-13 18:27 UTC, GauravGusain98 requested changes
please check the comments

2023-04-13 18:27 UTC, GauravGusain98 commented on Modules/CodeTrek/Resources/views/evaluate.blade.php
> +                                 <button type="submit" class="btn btn-danger">Marked Inactive</button>
```suggestion
                                 <button type="submit" class="btn btn-danger">Mark Inactive</button>
```

2023-04-13 18:27 UTC, GauravGusain98 commented on Modules/CodeTrek/Http/Controllers/CodeTrekApplicantRoundDetailController.php
> +    public function markInactive(CodeTrekApplicant $applicant)
lets make it updateStatus(). This will update the status to any value that comes in $request

2023-04-13 18:27 UTC, GauravGusain98 commented on Modules/CodeTrek/Resources/views/evaluate.blade.php
> +                                 <button type="submit" class="btn btn-danger">Marked Inactive</button>
Can you also add a button for status completed. For that the hidden input field should have value `completed`

2023-04-13 18:27 UTC, GauravGusain98 commented on Modules/CodeTrek/Resources/views/evaluate.blade.php
> +                                 @csrf
There should be a hidden input field with value `inactive`

2023-04-17 05:51 UTC, GauravGusain98 requested changes
left minor suggestion

2023-04-17 05:51 UTC, GauravGusain98 commented on Modules/CodeTrek/Http/Controllers/CodeTrekApplicantRoundDetailController.php
> +        if ($request->input('action') === 'inactive') {
take the value from config

2023-04-17 05:51 UTC, GauravGusain98 commented on Modules/CodeTrek/Http/Controllers/CodeTrekApplicantRoundDetailController.php
> +            $applicant->status = 'inactive';
here as well

2023-04-17 05:51 UTC, GauravGusain98 commented on Modules/CodeTrek/Http/Controllers/CodeTrekApplicantRoundDetailController.php
> +            $applicant->status = 'completed';
same here

2023-04-17 05:51 UTC, GauravGusain98 commented on Modules/CodeTrek/Routes/web.php
> +    Route::post('/mark-inactive/{applicant}', 'CodeTrekApplicantRoundDetailController@updateStatus')->name('codetrek.updateStatus');
Correct the URL here as well. It should not be `/mark-inactive/{applicant}` it should be `/update-status/{applicant}`

2023-04-18 06:36 UTC, GauravGusain98 requested changes
left a comment please check

2023-04-18 06:36 UTC, GauravGusain98 commented on Modules/CodeTrek/Resources/views/evaluate.blade.php
> +                                 <input type="hidden" name="status" value="">
What is the use of this input field?

2023-04-18 09:38 UTC, Hemrajbharti123 commented on Modules/CodeTrek/Resources/views/evaluate.blade.php
> +                                 <input type="hidden" name="status" value="">
The purpose of the hidden input field status is to submit the status of the form along with the selected action value when the form is submitted.
In this case, the status field is initially set to an empty string using the value attribute

2023-04-18 12:45 UTC, Hemrajbharti123 commented
### Unit Testing 
![Screenshot 2023-04-18 180109](https://user-images.githubusercontent.com/121417679/232781326-f0783dd6-0a25-4765-88d6-ec46c5f54754.png)

![image](https://user-images.githubusercontent.com/121417679/232781135-1886fde1-c357-484a-9186-5e82e5b67478.png)

2023-04-19 07:11 UTC, GauravGusain98 commented on Modules/CodeTrek/Resources/views/evaluate.blade.php
> +                                 <input type="hidden" name="status" value="">
What will happen if I remove this field? As I don't see any logic in the backend that is using this field.

2023-04-19 07:12 UTC, GauravGusain98 approved these changes
LGTM

2023-04-19 07:13 UTC, merged

2023-04-19 07:13 UTC, Hemrajbharti123 commented on Modules/CodeTrek/Resources/views/evaluate.blade.php
> +                                 <input type="hidden" name="status" value="">
I got your point sir i already remove the field you suggest