office location phase 2
ColoredCow/portal pull request #2977
Opened 2023-04-11 18:28 UTC by Harshvardhan80

Targets #2802

### Description
<!---I created a migration as i was told.
<!---I have created a dashboard page on which a link is given, after clicking on it you will go to add new centre form page.

2023-04-12 17:19 UTC, rahulpanwar16 commented on Modules/Operations/Resources/views/office-location/index.blade.php
> +<div class="container">
Please fix the indentation of this file.

2023-04-12 18:03 UTC, rahulpanwar16 commented
**Testing Feedbacks**

- Some space should be there in between ```+``` and  ```add new center``` like below :

![Screenshot (44)](https://user-images.githubusercontent.com/106467597/231536157-f14bdc5d-af14-4687-9402-c153a73c264f.png)

-  Modal should be at center as it more declined to right. 

![Screenshot (45)](https://user-images.githubusercontent.com/106467597/231537223-55725ae6-bc23-4dd9-b4f3-e3956728302c.png)

- Replace center with ```centre``` in model as well as in table. 

![Screenshot (46)](https://user-images.githubusercontent.com/106467597/231544706-5c1a7358-2844-4527-a47b-5979b23f620c.png)

2023-04-12 18:20 UTC, rahulpanwar16 commented
@Harshvardhan80  There are a few suggestions that needs to be done when you are making the PR. 

In ```Assignees``` : Assign it to yourself before assigning to the reviewers.
In ```Label``` : Put ready for review label before assigning it to the reviewers.
In ```Reviewers``` : Assign it to team-portal-reviewers.

2023-04-13 09:11 UTC, rahulpanwar16 requested changes
@Harshvardhan80  Left few comments. Please check.

```Center head``` is empty please bring back the values. 

![Screenshot (53)](https://user-images.githubusercontent.com/106467597/231713189-22883d79-7a33-40bf-962d-7987f5fae01a.png)

2023-04-13 09:11 UTC, rahulpanwar16 commented on Modules/Operations/Config/config.php
> -    'centre_heads' => [
Why you have remove it ? Please add back the ```centre_heads``` values will be fetched from config itself.

2023-04-13 11:00 UTC, rahulpanwar16 requested changes
Left few comments. Please check

2023-04-13 11:46 UTC, rahulpanwar16 commented on Modules/Operations/Resources/views/modals/operation.blade.php
> +        <a><i class="fa fa-plus"></i> &nbsp; @yield('popup')</a>
> * Instead of &nbsp for spacing you can use bootstrap classes for padding or margin inside the `<i>` tag.

I think you missed out this, please work on it.

2023-04-13 11:51 UTC, rahulpanwar16 commented
> @Harshvardhan80 There are a few suggestions that needs to be done when you are making the PR.
> 
> In Label : Put ready for review label before assigning it to the reviewers.


I think you missed it out, please do it.

2023-04-16 18:34 UTC, GauravGusain98 requested changes
Left a comment

2023-04-16 18:34 UTC, GauravGusain98 commented on database/migrations/2023_04_11_233918_create_office_locations_table.php
> +            $table->integer('centre_head')->unsigned();
```suggestion
            $table->integer('centre_head_id')->unsigned();
```

2023-04-17 13:24 UTC, GauravGusain98 commented
### Testing Feedbacks

- Getting this error while adding a new centre. Is it working in your local machine?
<img width="1436" alt="image" src="https://user-images.githubusercontent.com/54376313/232496950-d799bed4-5701-4955-9172-bf87c3adf773.png">
- I don't see any code that will show the list of centers that we have added. Have you tested it?

2023-04-18 09:10 UTC, Harshvardhan80 commented
Sir my data is getting store in database  and sir there is no mention in the task to show on the data view page

2023-04-18 12:40 UTC, Harshvardhan80 commented
![Screenshot 2023-04-18 1758583](https://user-images.githubusercontent.com/112154429/232779201-9f7e7abd-fc19-44af-b1ae-aadadd695c9c.png)
@GauravGusain98 
Sir what to put in actions and wheather to show current people count or not?

2023-04-19 06:03 UTC, GauravGusain98 commented
> ![Screenshot 2023-04-18 1758583](https://user-images.githubusercontent.com/112154429/232779201-9f7e7abd-fc19-44af-b1ae-aadadd695c9c.png) @GauravGusain98 Sir what to put in actions and wheather to show current people count or not?

- In the action field there should be a button to edit it. 
- Also the alignment of row data does not look correct to me in the screenshot you shared. Please fix it.

2023-04-21 06:43 UTC, GauravGusain98 requested changes

2023-04-21 06:43 UTC, GauravGusain98 commented on Modules/Operations/Resources/views/office-location/index.blade.php
> +@endsection
@Harshvardhan80 I don't think we need the @section('heading') 

Please remove it

2023-04-21 06:43 UTC, GauravGusain98 commented on Modules/Operations/Resources/views/modals/operation.blade.php
The name of the file doesnot look correct. If it is for adding a new center then its name should be `add-center-modal.blade.php`

2023-04-21 06:43 UTC, GauravGusain98 commented on Modules/Operations/Entities/OfficeLocation.php
> +    protected $fillable = ['centre_name', 'centre_head_id', 'capacity', 'current_people_count'];
When you want all the fields as fillable then you can use $guarded attrbite
```suggestion
    protected $guarded = [];
```

2023-04-21 06:43 UTC, GauravGusain98 commented on Modules/Operations/Entities/OfficeLocation.php
> +namespace Modules\operations\Entities;
Please use proper naming Convention as it will break in Ununtu and Mac systems
```suggestion
namespace Modules\Operations\Entities;
```

2023-04-24 08:12 UTC, rahulpanwar16 requested changes
Please go through below changes. 
Also, there is no functionality of ```edit and delete``` please work on it too.

2023-04-24 08:12 UTC, rahulpanwar16 commented on database/migrations/2023_04_17_113950_create_office_locations_table.php
> +    }
You need to drop the foreign key first and then the columns.

2023-04-24 08:22 UTC, Harshvardhan80 commented on database/migrations/2023_04_17_113950_create_office_locations_table.php
> +            $table->integer('centre_head_id')->unsigned();
@rahulpanwar16 
Check my comment Gaurav Sir asked to do Centre_head_id

2023-04-24 10:27 UTC, rahulpanwar16 approved these changes

2023-04-24 11:07 UTC, GauravGusain98 approved these changes

2023-05-05 10:01 UTC, merged