2970 add card to settings
ColoredCow/portal pull request #2986
Opened 2023-04-13 12:12 UTC by AJAYSINGHBISHT12

Targets #{2970}
### Description
Added a card in the setting file
### Checklist:

- [ ] I have performed a self-review of my own code.

2023-04-13 18:35 UTC, GauravGusain98 requested changes
Please check the comments

2023-04-13 18:35 UTC, GauravGusain98 commented on routes/web.php
> +        Route::prefix('bankdetails')->group(function () {
These are 2 different words

2023-04-13 18:35 UTC, GauravGusain98 commented on app/Http/Controllers/Settings/bankController.php
> +        return view('Settings.bankdetails');
CI Check if failing. Also the naing convention of blade file is incorrect. Please check how we pass blade file name here.

2023-04-13 18:35 UTC, GauravGusain98 commented on resources/views/settings/index.blade.php
Please correct the file naming convention

2023-04-14 10:28 UTC, Hemrajbharti123 approved these changes
LGTM

2023-05-22 13:36 UTC, GauravGusain98 approved these changes

2023-05-22 13:36 UTC, merged