The 'A Book A Month Page' is now opening properly
ColoredCow/portal pull request #2988
Opened 2023-04-13 14:31 UTC by Priyanka-Kaintura

Targets #2985

### Description
The 'A Book A Month' page is now opening properly.

### Checklist:

- [x] I have performed a self-review of my own code.

2023-04-13 14:59 UTC, Ayush8923 requested changes
Left some comments.

2023-04-13 14:59 UTC, Ayush8923 commented on app/Http/Controllers/KnowledgeCafe/Library/BookController.php
> +        $books = Book::all();
We do not need to show all the books on this page. On this page, we need to show the books corresponding to the user.

2023-04-13 14:59 UTC, Ayush8923 commented on app/Http/Controllers/KnowledgeCafe/Library/BookController.php
>                  return Carbon::parse($item->created_at)->format('Y');
Please check how this query is working. And debug whether we are getting data shown here or not. and accordingly, changes need to be made in the frontend.

2023-04-14 02:42 UTC, Priyanka-Kaintura commented on app/Http/Controllers/KnowledgeCafe/Library/BookController.php
> +        $books = Book::all();
But sir, the books corresponding to the user comes from the '$bookCollection' variable, whereas this 'books' variable is to count the wishlisted and borrowed books.

2023-04-14 06:39 UTC, Ayush8923 requested changes
Left some comment.

2023-04-14 06:39 UTC, Ayush8923 commented on app/Http/Controllers/KnowledgeCafe/Library/BookController.php
> +        $books = Book::all();
Yes yes, you are right. 
But, when I test this PR, getting this error, then get the below error. Please check and test it locally.

<img width="1255" alt="image" src="https://user-images.githubusercontent.com/80516839/231961448-de22771d-f77d-4897-893f-99468835a4f2.png">

2023-04-14 06:40 UTC, Ayush8923 commented on app/Http/Controllers/KnowledgeCafe/Library/BookController.php
> +        $books = Book::all();
Yes yes, you are right. 
But, when I test this PR, getting this error, then get the below error. Please check and test it locally.

<img width="1255" alt="image" src="https://user-images.githubusercontent.com/80516839/231961448-de22771d-f77d-4897-893f-99468835a4f2.png">

2023-04-14 06:58 UTC, Priyanka-Kaintura commented on app/Http/Controllers/KnowledgeCafe/Library/BookController.php
> +        $books = Book::all();
Sir it seem to work fine on my local system. Can you share a screeshot of line 29-46 of 'resource/views/KnowledgeCafe/library/books/book-a-month.blade.php' from where you are testing.

![image](https://user-images.githubusercontent.com/112419110/231967443-5729f6d3-27c8-475c-ad61-5912747ec0a3.png)

2023-04-14 07:43 UTC, Ayush8923 commented on app/Http/Controllers/KnowledgeCafe/Library/BookController.php
> +        $books = Book::all();
Okay, Got it. 
I tested this PR in a different system, it's working fine.

2023-04-14 07:43 UTC, Ayush8923 approved these changes

2023-04-14 07:43 UTC, merged