added a bank details file
ColoredCow/portal pull request #2990
Opened 2023-04-14 14:18 UTC by AJAYSINGHBISHT12

Targets #{2989}

[ 2989]

### Description

added a table in bankdetails

### Checklist:

- [ ] I have performed a self-review of my own code.

2023-04-14 14:34 UTC, GauravGusain98 requested changes

2023-04-14 14:34 UTC, GauravGusain98 commented on app/Models/BankDetails.php
> +    protected $fillable = ['id', 'key', 'label', 'value'];
simply use guarded function when you want all field to be fillable
```suggestion
    protected $guarded = [];
```

2023-04-15 05:33 UTC, Hemrajbharti123 commented on database/migrations/2023_04_14_181019_create_bank_details_table.php
> +        });
@AJAYSINGHBISHT12 For code optimization we don't use this way created_at and updated_at.

2023-04-15 10:19 UTC, Hemrajbharti123 approved these changes
LGTM

2023-06-21 07:08 UTC, AkshitRawat1207 commented
Added Bank Details form and submitted data
![Screenshot 2023-06-21 123429](https://github.com/ColoredCow/portal/assets/93993793/aa775c5b-b622-491c-a898-666c5740b0bf)
![Screenshot 2023-06-21 123453](https://github.com/ColoredCow/portal/assets/93993793/c694a603-6a88-4311-849a-b023777636de)

2023-06-21 08:37 UTC, GauravGusain98 commented
### Testing feedbacks

1. You don't need to show all the data. Most of these fields are not needed to be displayed in UI. In the UI only show the label and value.
<img width="1435" alt="image" src="https://github.com/ColoredCow/portal/assets/54376313/1d453925-9172-4342-865a-82bd6a590641">
2. Put the key as the second field. When a user enters the label then automatically populates the key field value as sluggified version of the Label.  Read about slug from [here](https://laravel.com/docs/8.x/helpers#method-str-slug)
<img width="1070" alt="image" src="https://github.com/ColoredCow/portal/assets/54376313/5a7cc575-63af-4df8-8025-f3d4e9160d98">
3. Also provide the functionality to edit existing fields. Provide and edit icon, clicking on this icon should open a modal in which the label, key, and value should be shown. Here we don't want the functionality to update the key automatically when user enter the label
4. Also add backend validation for unique values in key column

2023-06-26 12:53 UTC, AkshitRawat1207 commented
I have made the requested changes to the code based on your feedback. The script has been updated accordingly. If you have any further questions or need additional assistance, please let me know. I'm here to help!

![Screenshot 2023-06-26 181452](https://github.com/ColoredCow/portal/assets/93993793/795bd8fc-a53b-4320-99c3-9d5312a919a9)
![Screenshot 2023-06-26 181613](https://github.com/ColoredCow/portal/assets/93993793/9e3b3136-f342-40da-875e-0ecbbce52ed3)
![Screenshot 2023-06-26 181604](https://github.com/ColoredCow/portal/assets/93993793/1f14a158-ab89-4d11-a074-41322b4b0bac)
![Screenshot 2023-06-26 181538](https://github.com/ColoredCow/portal/assets/93993793/3b3e085a-28c3-41e0-ac93-31a1b4fd0c7e)

2023-06-26 13:03 UTC, GauravGusain98 requested changes

2023-06-26 13:03 UTC, GauravGusain98 commented on resources/js/app.js
> +		$('#editModal').modal('show');
Can we use more specific id or class names? As this app.js loads on many screens so it is possible that the same class name or id name may be present on those screens. So it's not a good practice to use generic names

2023-06-26 13:03 UTC, GauravGusain98 commented on resources/views/settings/bank-details/index.blade.php
> +                    <form action="{{ route('bank-details.update', ['bankDetail' => '__bankDetailId__']) }}" method="POST" id="editBankDetailForm">
Why you have used `__` underscore in the value? You can simply pass the value.

2023-06-26 13:03 UTC, GauravGusain98 commented on resources/views/settings/bank-details/index.blade.php
> +    </script>
Move this to app.js file

2023-06-26 16:04 UTC, LavishRawat requested changes

2023-06-26 16:04 UTC, LavishRawat commented on resources/views/settings/bank-details/index.blade.php
> +                        <a href="#" class="edit-btn" data-id="{{ $bankDetail->id }}" data-label="{{ $bankDetail->label }}" data-value="{{ $bankDetail->value }}">
Remove `` href="#" `` if not required.

2023-06-26 16:04 UTC, LavishRawat commented on resources/views/settings/bank-details/create.blade.php
> +{{-- <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script> --}}
Remove this line if not required.

2023-06-26 16:05 UTC, LavishRawat commented
@AkshitRawat1207 Please resolve the merge conflicts also.

2023-07-05 06:30 UTC, GauravGusain98 requested changes

2023-07-05 06:30 UTC, GauravGusain98 commented on resources/js/app.js
>  });
Are we using it? If yes, then please use a specific class and id name. The current names are too generic and its possible that someone can use the same name at other places.

So whenever we give name to id or class we try to use the name that is specifically for the functionality such that the chance of other people using it at other places become very low

2023-07-05 06:30 UTC, GauravGusain98 commented on app/Models/BankDetails.php
> +    protected $fillable = ['key', 'label', 'value'];
The `guarded = []` attribute means that all the columns are fillable. You don't need to provide fillable attribute with `guarded`

2023-07-05 06:49 UTC, AkshitRawat1207 commented on resources/js/app.js
>  });
no sir we are no using it forgot to remove this code

2023-07-05 06:54 UTC, GauravGusain98 commented on resources/js/app.js
>  });
Ok remove it then

2023-07-05 07:02 UTC, AkshitRawat1207 commented on app/Models/BankDetails.php
> +    protected $fillable = ['key', 'label', 'value'];
okay sir

2023-07-05 09:20 UTC, GauravGusain98 approved these changes
LGTM

2023-07-05 09:21 UTC, merged