fixed the issue date of invoice
ColoredCow/portal pull request #2996
Opened 2023-04-17 12:49 UTC by AmishaBisht

Targets #2930 

### Description
I have changed the issue date for invoice to the termEndDate that is the ending date of billing. 

### Checklist:
- [ ] I have performed a self-review of my own code.

2023-04-17 13:00 UTC, GauravGusain98 requested changes

2023-04-17 13:00 UTC, GauravGusain98 commented on Modules/Invoice/Resources/views/render/invoice-template.blade.php
> +                                            <p>{{ date('F d, Y', strtotime(now()->subMonthNoOverflow()->endOfMonth()->toDateString())) }}</p>
What it will return is billing date is 1 and today is 17 April. 

The expected output should be 31 march 2023

2023-04-17 18:11 UTC, AmishaBisht commented on Modules/Invoice/Resources/views/render/invoice-template.blade.php
> +                                            <p>{{ date('F d, Y', strtotime(now()->subMonthNoOverflow()->endOfMonth()->toDateString())) }}</p>
yes it is giving 31st March, here its billing date is 1 in database
![Screenshot (159)](https://user-images.githubusercontent.com/90472056/232573401-a42291fa-5267-4c8b-b4e2-ad5d3202da12.png)

2023-04-17 18:16 UTC, GauravGusain98 commented on Modules/Invoice/Resources/views/render/invoice-template.blade.php
> +                                            <p>{{ date('F d, Y', strtotime(now()->subMonthNoOverflow()->endOfMonth()->toDateString())) }}</p>
OK what if the billing date is 15?

2023-04-18 10:32 UTC, AmishaBisht commented on Modules/Invoice/Resources/views/render/invoice-template.blade.php
> +                                            <p>{{ date('F d, Y', strtotime(now()->subMonthNoOverflow()->endOfMonth()->toDateString())) }}</p>
@GauravGusain98 I can directly use the term-end-date in the place of issue date?

2023-04-19 05:56 UTC, GauravGusain98 commented on Modules/Invoice/Resources/views/render/invoice-template.blade.php
> +                                            <p>{{ date('F d, Y', strtotime($invoiceData['term'])) }}</p>
are you sure it si giving correct answers in all different cases? Did you tried testing it with different cases. 

Can you share screenshot of the result for different cases

2023-04-19 16:23 UTC, AmishaBisht commented on Modules/Invoice/Resources/views/render/invoice-template.blade.php
> +                                            <p>{{ date('F d, Y', strtotime($invoiceData['term'])) }}</p>
@GauravGusain98  this function is calculating the $termEndDate but when I am using this it is only returning the month. I need to make another function for date?
![Screenshot (161)](https://user-images.githubusercontent.com/90472056/233138507-61f8dbb9-3473-4a81-a8e8-336a09c9f373.png)

2023-04-20 07:57 UTC, GauravGusain98 commented on Modules/Invoice/Resources/views/render/invoice-template.blade.php
> +                                            <p>{{ date('F d, Y', strtotime($invoiceData['term'])) }}</p>
No you don't need to create another function. Just check how the `$invoiceData['term']` is defined

2023-04-20 08:39 UTC, AmishaBisht commented on Modules/Invoice/Resources/views/render/invoice-template.blade.php
> +                                            <p>{{ date('F d, Y', strtotime($invoiceData['term'])) }}</p>
@GauravGusain98 
![Uploading Screenshot (162).png…]()
there modifications have been made

2023-04-21 10:04 UTC, AmishaBisht commented on Modules/Invoice/Resources/views/render/invoice-template.blade.php
> +                                            <p>{{ date('F d, Y', strtotime($invoiceData['term'])) }}</p>
![Screenshot (163)](https://user-images.githubusercontent.com/90472056/233608995-86f2076f-92cb-4e8f-ace0-4b24742a6c80.png)
I wrote this query to get the term_end_date in the ready to send invoices.

2023-04-21 11:23 UTC, GauravGusain98 commented on Modules/Invoice/Resources/views/render/invoice-template.blade.php
> +                                            <p>{{ date('F d, Y', strtotime($invoiceData['term'])) }}</p>
But how you are getting term_end_date from the database when the invoice entry is not yet created?

2023-04-21 11:24 UTC, GauravGusain98 commented on Modules/Invoice/Resources/views/render/invoice-template.blade.php
> +                                            <p>{{ date('F d, Y', strtotime($invoiceData['term'])) }}</p>
The invoice that you are going to show in ready to send invoices is not yet stored in the database. From the database you can only get the end_date of invoices are sent.

2023-04-23 17:44 UTC, AmishaBisht commented on Modules/Invoice/Resources/views/render/invoice-template.blade.php
> +                                            <p>{{ date('F d, Y', strtotime($invoiceData['term'])) }}</p>
@GauravGusain98 
![Screenshot (167)](https://user-images.githubusercontent.com/90472056/233855885-372e621a-782c-4cc6-97dc-7ad4f1b738ef.png)
the preview URL is hitting this function according to my inderstanding.

2023-04-23 17:46 UTC, AmishaBisht commented on Modules/Invoice/Resources/views/render/invoice-template.blade.php
> +                                            <p>{{ date('F d, Y', strtotime($invoiceData['term'])) }}</p>
@GauravGusain98 
![Screenshot (168)](https://user-images.githubusercontent.com/90472056/233856023-732b1f2c-231c-41a1-97a7-859cc89f8466.png)
the preview URL is hitting this function according to my understanding.

2023-04-24 17:18 UTC, GauravGusain98 commented
@AmishaBisht This is correct. As I've already done these changes and release the PR. So I'm closing this PR. 

But Congrats on understanding the logic that as important

2023-04-24 17:18 UTC, closed without merging