To Clear The Filter From Search Functionality
ColoredCow/portal pull request #2997
Opened 2023-04-17 16:21 UTC by Himanshunegi0332

Targets #2992 
### Description
Currently we don't have any feature that if a user has applied the name filter then how to remove that filter, for this I have created a functionality to remove the filter.

### Checklist:
- [X] I have performed a self-review of my own code.

2023-04-17 16:28 UTC, GauravGusain98 requested changes
Please check the comment

2023-04-17 16:28 UTC, GauravGusain98 commented on Modules/CodeTrek/Resources/views/index.blade.php
> +        <span>Result for 'search text'</span><a href="/codetrek"> To clear the filter click here X </a>
This `'search text'` should be replaced with the text that user has searched. If user has not search anything then the whole sentence should not be seen

2023-04-17 18:15 UTC, GauravGusain98 requested changes

2023-04-17 18:15 UTC, GauravGusain98 commented on Modules/CodeTrek/Resources/views/index.blade.php
> +        <span>Result for '{{ request()->get('name') }}'</span><a href="/codetrek"> To clear the filter click here X </a>
The UI is not looking good. Can we make it like this. Just add a simple clear button
<img width="1213" alt="image" src="https://user-images.githubusercontent.com/54376313/232574346-dabe60d3-5075-4c81-ae80-63470020794d.png">

2023-04-19 06:00 UTC, GauravGusain98 commented
### Testing Feedbacks
- I've searched `Gaurav Gusain` but the field is only showing `Gaurav`

2023-04-19 07:14 UTC, Himanshunegi0332 commented
> ### Testing Feedbacks
> * I've searched `Gaurav Gusain` but the field is only showing `Gaurav`
> 
> <img alt="image" width="632" src="https://user-images.githubusercontent.com/54376313/232980509-b7cd93fb-fcbc-4929-b260-6f6690d5c05f.png">

2023-04-20 08:39 UTC, GauravGusain98 approved these changes
LGTM

2023-04-20 08:39 UTC, merged