feature/3005/New-tabs-for-every-status
ColoredCow/portal pull request #3009
Opened 2023-04-20 11:49 UTC by Hemrajbharti123

Targets #3005 

In the CodeTrek index page, all the applicants are shown, so it is difficult for the users to find which applicant is 'inactive' 'completed' and 'active' For this I make separate tabs for every status.

### Checklist:
- [ ] I have performed a self-review of my own code.

2023-04-21 07:36 UTC, Hemrajbharti123 commented
**Unit Testing**

![image](https://user-images.githubusercontent.com/121417679/233572943-1ac867a2-bbc6-49c2-89e8-657799da130b.png)

![image](https://user-images.githubusercontent.com/121417679/233573082-c9aa4be8-0f9d-455c-8bf6-12ec0a5304c7.png)

2023-04-25 05:36 UTC, GauravGusain98 requested changes
minor suggestion else looks fine

2023-04-25 05:36 UTC, GauravGusain98 commented on resources/views/layouts/navbar.blade.php
> +            <a class="nav-item nav-link" href="{{('/codetrek?status=active') }}">CodeTrek</a>
User route() function here. Also no need to pass status = active as by default `active` is selected

2023-04-25 06:42 UTC, Hemrajbharti123 commented
### Unit Testing

- Tabs are working fine.

![image](https://user-images.githubusercontent.com/121417679/234194849-64692b8c-fcfb-4afa-964a-40f6a1317f2b.png)

2023-04-25 06:44 UTC, GauravGusain98 approved these changes
LGTM

2023-04-25 06:44 UTC, merged