Feature/3017 activate edit and delete icons
ColoredCow/portal pull request #3021
Opened 2023-04-25 05:16 UTC by Harshvardhan80

Targets #3017 

### Description
Activate the edit icon
Activate delete icon

### Checklist:

- [ ] I have performed a self-review of my own code.

2023-04-25 08:16 UTC, rahulpanwar16 requested changes
**Testing Feedback** 

When user clicks on edit button the modal pops in and when user clicks on outside the modal, the modal closes and leave a blank page. Please fix it. 
![Screenshot (95)](https://user-images.githubusercontent.com/106467597/234215794-3a4d53c0-dcf0-4d68-a3ec-92ff702dbdbc.png)

2023-04-25 08:16 UTC, rahulpanwar16 commented on database/migrations/2023_04_17_113950_create_office_locations_table.php
> +        Schema::table('office_locations', function (Blueprint $table) {
```suggestion
        Schema::dropIfExists('office_locations');
 {
```

2023-04-25 08:21 UTC, rahulpanwar16 commented
@Harshvardhan80  Can you put ```assignees``` to yourself.

2023-04-26 07:06 UTC, rahulpanwar16 commented on Modules/Operations/Resources/views/office-location/edit.blade.php
> +        <form action="{{ route('office-location.update', $centre->id) }}" method="POST">
Please bring back the modal as it was earlier and move js code to app.js

2023-04-26 07:13 UTC, Harshvardhan80 commented on Modules/Operations/Resources/views/office-location/edit.blade.php
> +        <form action="{{ route('office-location.update', $centre->id) }}" method="POST">
Javascript used or not
![Screenshot_2023-04-26-12-40-38-40_40deb401b9ffe8e1df2f1cc5ba480b12](https://user-images.githubusercontent.com/112154429/234498112-f0e86fc6-9c2a-4663-9ea8-0efccee889b1.jpg)

2023-04-26 07:55 UTC, GauravGusain98 requested changes
Please check the comments

2023-04-26 07:55 UTC, GauravGusain98 commented on database/migrations/2023_04_08_181613_create_office_locations_table.php
> +
Why this change is still present in this PR? 

Did you make the new branch over the old branch. While starting a new task make sure to switch back to master branch and take latest pull and then create new branch from there. 

Now just take the pull of master branch in this branch and push it

2023-04-26 07:55 UTC, GauravGusain98 commented on Modules/Operations/Http/Controllers/OperationsController.php
> +    public function destroy($id, OperationService $service)
You should use Model Class in the attribute that way you can directly get the object of the that Class corresponding to that id. 

This concept is called route-model binding. You can read about it form [here](https://laravel.com/docs/8.x/routing#route-model-binding)

2023-04-26 08:28 UTC, Harshvardhan80 commented on database/migrations/2023_04_08_181613_create_office_locations_table.php
> +
@GauravGusain98    Sir my previous PR is still not merged in the master so even after taking the pull from master, my old files are still showing there

2023-05-04 07:55 UTC, GauravGusain98 requested changes
please check the comment

2023-05-04 07:55 UTC, GauravGusain98 commented on Modules/Operations/Entities/OfficeLocation.php
> +    public function centre_head()
Fix naming convention of the function

2023-05-15 11:11 UTC, merged