sort_candidates_by_name
ColoredCow/portal pull request #3024
Opened 2023-04-25 09:54 UTC by VimalUniyal

Targets #2952 

### Description
Sorting the candidates in ascending order by their name in Codetrek Page.

- [ ] I have performed a self-review of my own code.

2023-04-25 12:20 UTC, rahulpanwar16 commented
@VimalUniyal  There are a few suggestions that needs to be done when you are making the PR.

```In Assignees``` : Assign it to yourself before assigning to the reviewers.
```In Label``` : Put ready for review label before assigning it to the reviewers.
```In Reviewers``` : Assign it to team-portal-reviewers.

2023-04-25 12:32 UTC, rahulpanwar16 requested changes
Please check the comments.

2023-04-25 12:32 UTC, rahulpanwar16 commented on Modules/CodeTrek/Resources/views/index.blade.php
> +
Why there a space in between?

2023-04-25 12:32 UTC, rahulpanwar16 commented on resources/views/hr/application/index.blade.php
> +                <select class="fz-14 fz-lg-16 w-120 w-140 form-control rounded border-0 bg-white" name="sortby" id="sortby"
Why have you done changes on commented code?

2023-04-26 08:32 UTC, rahulpanwar16 approved these changes

2023-04-26 08:37 UTC, GauravGusain98 approved these changes
LGTM

2023-04-26 08:37 UTC, merged