Corrected the alignment of client project page content
ColoredCow/portal pull request #3029
Opened 2023-04-25 11:45 UTC by Priyanka-Kaintura

Targets #2983

### Description
Corrected the alignment of client project page content.

### Checklist:

- [x] I have performed a self-review of my own code.

2023-04-25 12:12 UTC, Priyanka-Kaintura commented
@GauravGusain98 
Sir, I have checked the content alignment for almost all range of screen sizes and especially for edge cases with screen size xs, sm, md, l, xl as suggested. But if there is still a problem then please let me now.

2023-04-25 13:36 UTC, Ayush8923 requested changes

2023-04-25 13:36 UTC, Ayush8923 commented on Modules/Client/Resources/views/subviews/edit-client-projects.blade.php
> +<div class="overflow-x-scroll card" style="min-width:660px;">
Please sue bootstrap classes instead of inline-css.

2023-04-25 14:21 UTC, Priyanka-Kaintura commented on Modules/Client/Resources/views/subviews/edit-client-projects.blade.php
> +<div class="overflow-x-scroll card" style="min-width:660px;">
@Ayush8923 Sir I didn't find any specific bootstrap class to set min-width and so used inline style. I even went through the documentation but didn't find any class of this sort.

2023-04-26 15:48 UTC, Ayush8923 requested changes
One comment else looks good to me.

2023-04-26 15:48 UTC, Ayush8923 commented on resources/sass/_variables.scss
> +);
I don't think, we need this. Please remove this. Then test it locally. And let me know, it's working fine or not.

2023-04-27 06:58 UTC, Ayush8923 approved these changes
Looks good to me.

2023-04-28 11:57 UTC, merged