Feature/3020/creating seeder
ColoredCow/portal pull request #3036
Opened 2023-04-26 10:02 UTC by MayankBisht8630

Targets #3020

### Description
Creating Seeder For CodeTrek

### Checklist:

- [ ] I have performed a self-review of my own code.

2023-04-27 09:43 UTC, GauravGusain98 requested changes
Please check the comments

2023-04-27 09:43 UTC, GauravGusain98 commented on database/Seeders/CodetrekSeeder.php
> +            'updated_at'=>'',
These 2 columns will be automatically updated. No need to pass then in insert statement.

2023-04-27 09:43 UTC, GauravGusain98 commented on database/Seeders/CodetrekSeeder.php
> +            'graduation_year'=>'',
Fill the vlaue in these fields as well using faker

2023-04-27 09:43 UTC, GauravGusain98 commented on database/Seeders/CodetrekSeeder.php
> +            'deleted_at'=>'',
remove this as well

2023-04-27 09:43 UTC, GauravGusain98 commented on database/Seeders/CodetrekSeeder.php
> +            'round_name'=>'level 1'
take value from config file. Don't hardcode the value

2023-04-27 09:43 UTC, GauravGusain98 commented on database/Seeders/CodetrekSeeder.php
> +        for ($i = 1; $i <= 5; $i++) {
For this you need to create new seeder file. The `CodetrekSeeder` file is only used to call those seeder files. 

Look at how projectSeeder is working.

2023-04-27 09:43 UTC, GauravGusain98 commented on database/Seeders/CodetrekSeeder.php
> +            DB::table('code_trek_applicants')->insert([
When we create a new applicant we also create entry in the `codetrek_applicant_round` table. So for every applicant you also need to create entry in the `codetrek_applicant_round` table

2023-04-27 09:43 UTC, GauravGusain98 commented on config/database.php
> +            'collation' => 'utf8_general_ci',
These changes are not needed. Please revert them. Also please do a self review of your code changes before assigning PR.

2023-04-27 09:43 UTC, GauravGusain98 commented on database/Seeders/DatabaseSeeder.php
> +        $this->call(CodetrekSeeder::class);
This is not needed.

2023-05-03 11:38 UTC, GauravGusain98 commented on Modules/CodeTrek/Database/factories/CodetrekApplicantRoundFactory.php
> +class CodeTrekApplicantFactory extends Factory
The name of this Class is not correct.

2023-05-18 18:32 UTC, Ayush8923 commented
@MayankBisht8630 Please resolve the merge conflicts.

2023-05-18 18:32 UTC, MayankBisht8630 commented
Ok sir

2023-05-19 11:09 UTC, Ayush8923 requested changes

2023-05-19 16:30 UTC, Ayush8923 requested changes
Left some comments. 
And Have you tested it locally?

2023-05-19 16:48 UTC, MayankBisht8630 commented
> Left some comments. And Have you tested it locally?

Yes Sir made required Changes , And I have tested it locally working fine

2023-05-19 16:55 UTC, MayankBisht8630 commented on Modules/CodeTrek/Database/Factories/CodeTrekApplicantFactory.php
> +    }
> 
Sir If I am Adding a line after 33 so it is showing error in checks

2023-05-20 05:55 UTC, Ayush8923 approved these changes

2023-05-20 05:56 UTC, Ayush8923 commented
@GauravGusain98  Please take a look. You have also placed a change request in this PR.

2023-05-20 06:06 UTC, merged