updated
ColoredCow/portal pull request #3037
Opened 2023-04-26 10:26 UTC by Rishita-Gusain

Targets #2980

### Description
removed the padding of the recommend classs

### Checklist:p! -->
- [ ] I have performed a self-review of my own code.

2023-04-26 10:32 UTC, Ayush8923 commented
@Rishita-Gusain Please assign yourself and also assign the reviewers for review. And put the label `ready-for-review`.

2023-04-27 09:39 UTC, Ayush8923 requested changes
When I change the screen size then these 3 filters are not aligned. Please fix this.
Please refer Screenshot below
<img width="442" alt="image" src="https://user-images.githubusercontent.com/80516839/234823829-edc718ed-fc87-465b-8708-96a1e047a4d1.png">

2023-04-27 09:39 UTC, Ayush8923 commented on resources/views/knowledgecafe/library/books/show_nudge_modal.blade.php
> +                    <span>You have read </span>
```suggestion
                    <span>You have read</span>    
```

2023-05-01 17:00 UTC, Ayush8923 commented on resources/js/components/Dashboard/UserDashboardLibrary.vue
>          <li class="nav-item">
We need to just add the `d-flex` class. Please test locally once. And also please add the screenshot that's how it looks.

2023-05-04 05:52 UTC, Hemrajbharti123 commented
**Local Testing Feedback**
Still, the 3 filters are not aligned. Please fix this.



![image](https://user-images.githubusercontent.com/121417679/236121932-5f716342-f534-4ddc-bf6f-32e223008107.png)

2023-05-04 07:07 UTC, Hemrajbharti123 approved these changes

2023-06-20 06:06 UTC, Ayush8923 commented
Suggested changes have not been implemented and @Rishita-Gusain is not working in the PR. Closing it.

2023-06-20 06:06 UTC, closed without merging