created a dynamic form for bank details and stored the data in bank details table
ColoredCow/portal pull request #3039
Opened 2023-04-26 15:13 UTC by AJAYSINGHBISHT12

Targets #{2972}
[2972]

### Description
created a dynamic form and saved its data in database in bank-details table

### Checklist:

- [ ] I have performed a self-review of my own code.

2023-04-27 11:42 UTC, rahulpanwar16 commented
@AJAYSINGHBISHT12  There are a few suggestions that needs to be done when you are making the PR.

```In Assignees``` : Assign it to yourself before assigning to the reviewers.
```In Label``` : Put ready for review label before assigning it to the reviewers.
```In Reviewers``` : Assign it to team-portal-reviewers.

2023-04-27 12:37 UTC, AJAYSINGHBISHT12 commented
![tableindatabasein](https://user-images.githubusercontent.com/123948333/234863586-0a736e6c-79ef-46f5-bb64-d4d830415100.png)
![forminactual](https://user-images.githubusercontent.com/123948333/234863641-783c78fc-05d2-4043-8acc-eedccd4a7b0d.png)
![dataisgettingsaved](https://user-images.githubusercontent.com/123948333/234863754-90a24ea2-7494-44ba-ae62-799558989f5a.png)
this is how first dynamic form is created 
then the data is getting saved in database 
and then this saved icon is showing

2023-04-27 13:03 UTC, rahulpanwar16 commented
> ![tableindatabasein](https://user-images.githubusercontent.com/123948333/234863586-0a736e6c-79ef-46f5-bb64-d4d830415100.png) ![forminactual](https://user-images.githubusercontent.com/123948333/234863641-783c78fc-05d2-4043-8acc-eedccd4a7b0d.png) ![dataisgettingsaved](https://user-images.githubusercontent.com/123948333/234863754-90a24ea2-7494-44ba-ae62-799558989f5a.png) this is how first dynamic form is created then the data is getting saved in database and then this saved icon is showing

@AJAYSINGHBISHT12 we want this UI of success toast message. Please change it 
![Screenshot (99)](https://user-images.githubusercontent.com/106467597/234869803-1414ece4-c851-495d-9d84-6590afb940a0.png)

2023-06-13 08:14 UTC, LavishRawat requested changes

2023-06-13 08:14 UTC, LavishRawat commented on resources/views/settings/bank-details.blade.php
> +    <div id="BankDetails">
@AJAYSINGHBISHT12 Please fix the indentation.

2023-06-13 08:14 UTC, LavishRawat commented on resources/views/settings/bank-details.blade.php
> +      @csrf
@AJAYSINGHBISHT12 why are we using @csrf here? can you please explain?

2023-06-25 15:46 UTC, GauravGusain98 commented
This is not needed

2023-06-25 15:46 UTC, closed without merging