fix table colour in project resource page
ColoredCow/portal pull request #3041
Opened 2023-04-26 19:16 UTC by poornimashah

Targets #3019 

### Description

### Checklist:

- [x] I have performed a self-review of my own code.
feature/3019/fix-table-colour

2023-04-27 16:44 UTC, rahulpanwar16 commented
@poornimashah There are a few suggestions when you are making the PR.

```In Assignees``` - Assign yourself before assigning to the reviewers.
```In Labels``` - Put the label ```ready for review``` before assigning it to the reviewers.
```In Reviewers``` - Assign ```Gaurav Gusain``` in the PR Reviewers and please remove other all names from reviewers. 
```In Targets``` - Write issue-id  i.e #3019 in your case.
```In PR Name``` - Write down the meaningful PR name i.e fix table colour on project resource page.

2023-04-28 05:07 UTC, Ayush8923 commented
@poornimashah Please fix the CI checks. Then assign reviewers to review the PR.

2023-04-28 06:03 UTC, Ayush8923 requested changes
Please revert the `package-lock.json` file from this PR.

2023-04-29 07:51 UTC, Ayush8923 requested changes
One suggested change. Please remove the extra spaces.

2023-04-29 07:51 UTC, Ayush8923 commented on Modules/Project/Resources/views/resource-requirement.blade.php
> +            <table class="table table-bordered table-striped" >
```suggestion
            <table class="table table-bordered table-striped">
```

2023-04-29 07:52 UTC, Ayush8923 reviewed
Approved with one comment. We don't need to this extra small space.

2023-04-29 07:52 UTC, Ayush8923 commented on Modules/Project/Resources/views/resource-requirement.blade.php
> +            <table class="table table-bordered table-striped" >
```suggestion
            <table class="table table-bordered table-striped">
```

2023-04-29 07:52 UTC, Ayush8923 approved these changes

2023-04-29 13:54 UTC, Ayush8923 approved these changes

2023-04-29 13:55 UTC, merged

2023-04-29 13:55 UTC, poornimashah commented on Modules/Project/Resources/views/resource-requirement.blade.php
> +            <table class="table table-bordered table-striped" >
done sir