3039 make dynamic form store in database
ColoredCow/portal pull request #3047
Opened 2023-04-27 11:33 UTC by AJAYSINGHBISHT12

Targets #{3039}

### Description
make dynamic form store in database

### Checklist:

- [ ] I have performed a self-review of my own code.

2023-04-27 12:26 UTC, AJAYSINGHBISHT12 commented
UNIT TESTING
![forminactual](https://user-images.githubusercontent.com/123948333/234861414-18d4f5a7-d34a-43cf-9479-77b3b6745e82.png)
this is the dynamic form

2023-04-27 12:27 UTC, AJAYSINGHBISHT12 commented
![tableindatabasein](https://user-images.githubusercontent.com/123948333/234861582-80fe852c-84ed-4bfa-b204-eadee37627cc.png)
this is the table where data is getting stored

2023-05-02 09:29 UTC, Ayush8923 requested changes
Added some more comments. Please check.

2023-05-02 09:29 UTC, Ayush8923 commented on resources/views/settings/bank-details.blade.php
> +  </div>
Please fix the indentation.

2023-05-04 07:16 UTC, GauravGusain98 requested changes
Please check the comment

2023-05-04 07:16 UTC, GauravGusain98 commented on app/Http/Controllers/Settings/bankController.php
> +class bankController extends Controller
Class name should be in Titlecase

2023-05-04 07:16 UTC, GauravGusain98 commented on app/Http/Controllers/Settings/bankController.php
Controller file name should be in Titlecase

2023-05-04 07:16 UTC, GauravGusain98 commented on app/Http/Controllers/Settings/bankController.php
> +            $bankDetail = BankDetails::create(['key' => $key, 'value' => $value ? ContentHelper::editorFormat($value) : null]);
Why we have used `ContentHelper::editorFormat()` function? What is its use?

2023-05-04 07:16 UTC, GauravGusain98 commented on app/Http/Controllers/Settings/bankController.php
> +            $bankDetail = BankDetails::create(['key' => $key, 'value' => $value ? ContentHelper::editorFormat($value) : null]);
Also, here we should use createOrUpdate function instead of create.

2023-05-04 07:16 UTC, GauravGusain98 commented on app/Models/BankDetails.php
> +class BankDetails extends Model
Model name should not be in Plural. It should be singular. Change the name to `BankDetail`

2023-05-04 07:16 UTC, GauravGusain98 commented on resources/views/settings/bank-details.blade.php
> +          <div class="form-group col-md-5">
These fields should be generated dynamically. What is the use of creating a table if we are inserting the fields in the blade file. 

The idea to create kay value-columns in bank_details page was to have these fields displayed in the page in dynamic way. Suh that if there are 10 records in bank_details page then 10 fields should show in the page and the value should be updated based on key.

2023-06-13 08:38 UTC, LavishRawat requested changes

2023-06-13 08:38 UTC, LavishRawat commented on resources/views/settings/index.blade.php
> +                            <br>
@AJAYSINGHBISHT12 Can we use the bootstrap class instead of using  ``<br>``? 
let me know if that works.

2023-06-25 15:45 UTC, GauravGusain98 commented
Someone else is working on this task so closing it

2023-06-25 15:45 UTC, closed without merging