Add Preparatory in codetrek module
ColoredCow/portal pull request #3055
Opened 2023-05-01 11:51 UTC by Harshvardhan80

Targets #2704 

### Description
Add preparatory dropdown in codetrek module
### Checklist:

- [ ] I have performed a self-review of my own code.

2023-05-02 09:46 UTC, Harshvardhan80 commented
![S](https://user-images.githubusercontent.com/112154429/235633612-09cf64ae-aafe-45cd-b180-e0f548934f4d.png)
Had to add dropdown by this type only

2023-05-02 10:52 UTC, Ayush8923 requested changes
Left some comments. Please check.

2023-05-02 10:52 UTC, Ayush8923 commented on Modules/CodeTrek/Config/config.php
> +        ],
This round is being shown at last. This round should be the first show in the round list.

```suggestion
        'preparatory' => [
            'label' => 'Preparatory',
            'slug' => 'Preparatory'
        ],
```

2023-05-03 10:14 UTC, Ayush8923 approved these changes

2023-05-03 10:24 UTC, merged