Changed the implementation of new Sales Area page to modal form in bo…
ColoredCow/portal pull request #3056
Opened 2023-05-01 13:20 UTC by Priyanka-Kaintura

Targets #2356 

### Description
Changed the implementation of new Sales Area page to bootstrap modal forms.

### Checklist:

- [x] I have performed a self-review of my own code.

2023-05-02 09:26 UTC, Ayush8923 requested changes
@Priyanka-Kaintura Left some comments. 
Also please add the toast when the user creates the new sales area.

2023-05-02 09:26 UTC, Ayush8923 commented on Modules/SalesAutomation/Resources/views/sales-area/index.blade.php
> +						</div>
Please fix the indentation.

2023-06-22 06:38 UTC, Ayush8923 commented
@Priyanka-Kaintura Please take the latest pull of the `master` branch to this branch. So that both the branches go in sync up with each other

2023-06-22 09:29 UTC, Ayush8923 requested changes
Added a few comments. Please check.

2023-06-22 09:29 UTC, Ayush8923 commented on Modules/SalesAutomation/Resources/views/sales-area/index.blade.php
> +					<div class="card my-0">
We don't need to make a form as a card. which makes it look a bit weird then.
Take the reference of the below screenshot. The shadow of the form is visible in the background of the form. we need to see the normal form. also please take a reference CodeTrek applicant form.
<img width="466" alt="image" src="https://github.com/ColoredCow/portal/assets/80516839/1a74eede-0799-43b3-b421-b57a3a6e6385">

2023-06-22 09:29 UTC, Ayush8923 commented on Modules/SalesAutomation/Resources/views/sales-area/index.blade.php
> +				<h2>New Sales Area</h2>
This text size is too large in the model form. Please take the reference other places.

2023-06-23 03:46 UTC, Priyanka-Kaintura commented on Modules/SalesAutomation/Resources/views/sales-area/index.blade.php
> +				<h2>New Sales Area</h2>
@Ayush8923 Sir, could you please check it now.

2023-06-23 05:21 UTC, LavishRawat requested changes

2023-06-23 05:21 UTC, LavishRawat commented on Modules/SalesAutomation/Resources/views/sales-area/index.blade.php
> +                    			<td colspan="2">
@Priyanka-Kaintura i can not see the closing tag for `` <td ``. Please have a look.

2023-06-23 05:25 UTC, LavishRawat commented
@Priyanka-Kaintura  in the UI can see a white box at the end of the table. Please have a look.

<img width="1044" alt="Screenshot 2023-06-23 at 10 40 09 AM" src="https://github.com/ColoredCow/portal/assets/108713935/b359908b-3dfa-4689-bbba-8b3e1a7b5731">

2023-06-23 07:21 UTC, LavishRawat approved these changes

2023-06-23 07:49 UTC, Ayush8923 requested changes
One small comment else looks good.

2023-06-23 07:49 UTC, Ayush8923 commented on Modules/SalesAutomation/Resources/views/sales-area/index.blade.php
> +							<img src="{{ URL('images/no-result.png') }}" class='img-center' alt="" width="50%">
Remove the unwanted attributes.
```suggestion
							<img src="{{ URL('images/no-result.png') }}" class='img-center' width="50%">
```

2023-06-23 11:10 UTC, Ayush8923 approved these changes

2023-06-23 11:10 UTC, merged