bugfix/3038/search-button-alignment
ColoredCow/portal pull request #3057
Opened 2023-05-02 10:45 UTC by Tarun1505

Targets #{ISSUE_ID}

### Description

### Checklist:

- [ ] I have performed a self-review of my own code.

2023-05-03 10:18 UTC, Ayush8923 requested changes
Left some comments. Please check.

2023-05-03 10:18 UTC, Ayush8923 commented on package.json
> +        "development": "cross-env NODE_ENV=development node_modules/webpack/bin/webpack.js --progress  --config=node_modules/laravel-mix/setup/webpack.config.js",
These changes are not needed. Please revert this file changes.

2023-05-03 10:18 UTC, Ayush8923 commented on package-lock.json
> +                "node-pre-gyp",
Same here. This file changes are not needed. Please revert these file changes.

2023-05-11 09:54 UTC, Ayush8923 requested changes
Left some comments. And please revert the `package-lock.json` and `package.json` file from this PR. It's not needed in this PR.

2023-05-11 09:54 UTC, Ayush8923 commented on package.json
> +}
Please revert this file. It's not needed.

2023-05-11 09:54 UTC, Ayush8923 commented on resources/views/hr/employees/index.blade.php
> +                    <input type="text" name="employeename" class="form-control" id="name" placeholder="Enter the Employee" value="{{ request()->get('employeename') }}" button class="pr-3.0">
Please let me know, how much size of the `pr-3.0`. and also the what is means of the `button` in this input field.
```suggestion
                    <input type="text" name="employeename" class="form-control pr-3.0" id="name" placeholder="Enter the Employee" value="{{ request()->get('employeename') }}" button class="">
```

2023-05-11 09:54 UTC, Ayush8923 commented on resources/views/hr/employees/index.blade.php
> +                    <button class="btn btn-info ml-1 pr-1 py-1.0 text-white">Search</button>
Please let me know, how much size of the `pr-1.0`.

2023-05-12 11:12 UTC, Tarun1505 commented on resources/views/hr/employees/index.blade.php
> +                    <button class="btn btn-info ml-1 pr-1 py-1.0 text-white">Search</button>
It has a size of 1px .

2023-05-12 11:14 UTC, Tarun1505 commented on resources/views/hr/employees/index.blade.php
> +                    <input type="text" name="employeename" class="form-control" id="name" placeholder="Enter the Employee" value="{{ request()->get('employeename') }}" button class="pr-3.0">
This **button**  is added by mistake , and I have corrected it .

2023-05-13 15:48 UTC, Ayush8923 commented
- You can see in this below screenshot, the alignment of the search bar is not correct. The alignment of the search bar should be at the end of the table. and also you need to check in all the screen sizes.

<img width="1176" alt="Screenshot 2023-05-13 at 9 12 50 PM" src="https://github.com/ColoredCow/portal/assets/80516839/3b541a6f-758d-421a-a0e4-254e27081cf6">

2023-05-13 16:13 UTC, Tarun1505 commented
> [May 2, 2023 16:18 ](#event-9144323225)

Can you please elaborate it for better understanding!

2023-06-25 15:51 UTC, GauravGusain98 commented
Due to inactivity closing this PR

2023-06-25 15:51 UTC, closed without merging