Add Applicant through Excel sheet
ColoredCow/portal pull request #3074
Opened 2023-05-12 10:21 UTC by Akshiteshnaithani

Targets #2745

### Description
created a new button on GitHub, and upon clicking it, it opens a module where you can upload an Excel sheet and import new applicants through the Excel sheet.

**screenshot**
![image](https://github.com/ColoredCow/portal/assets/121417968/102ce49f-c33a-4b50-a246-fd181cf7e0bd)

![image](https://github.com/ColoredCow/portal/assets/121417968/8cc069b4-5284-41d1-a16d-53c8a73eff07)

### Checklist:

- [ ] I have performed a self-review of my own code.

2023-05-12 19:32 UTC, Ayush8923 requested changes
Left some comments. Please check.

2023-05-12 19:32 UTC, Ayush8923 commented on Modules/CodeTrek/Http/Controllers/CodeTrekController.php
> +        $file->move(public_path('uploads'), $filename);
I don't think, we need to save the file in local path. Please remove this.

2023-05-12 19:32 UTC, Ayush8923 commented on Modules/CodeTrek/Http/Controllers/CodeTrekController.php
> +        return redirect('/codetrek')->with('success', 'Excel file uploaded and imported successfully!');
Please use the route name instead of this `/codetrek`.

2023-05-12 19:32 UTC, Ayush8923 commented on Modules/CodeTrek/Http/Controllers/CodeTrekController.php
> +        Excel::import(new ApplicantImport, public_path('uploads/' . $filename));
We don't need to save the file in the local storage. Please fetch the file from the `request`. And then we can write like this.
```
request()->file('excel_file')
```

2023-05-12 19:32 UTC, Ayush8923 commented on Modules/CodeTrek/Resources/views/modals/add-excel-file-modal.blade.php
> +                        <h5 class="modal-title" id="exampleModalLabel"><strong>Import excel file </strong></h5>
```suggestion
                        <h5 class="modal-title" id="exampleModalLabel">Import Excel File</h5>
```

2023-05-12 19:32 UTC, Ayush8923 commented on app/Models/Applicant.php
> +class Applicant extends Model
We don't need to create one more model for the this. Its model has already been created whose name is `CodeTrekApplicant`.

2023-05-12 19:32 UTC, Ayush8923 commented on config/app.php
> +        Maatwebsite\Excel\ExcelServiceProvider::class,
Why did you add this line here?

2023-05-14 08:20 UTC, Ayush8923 requested changes
Left some small changes else looks good to me.

2023-05-14 08:20 UTC, Ayush8923 commented on Modules/CodeTrek/Entities/CodeTrekApplicant.php
> +
```suggestion
```

2023-05-14 08:20 UTC, Ayush8923 commented on Modules/CodeTrek/Resources/views/modals/add-excel-file-modal.blade.php
> +        <div class="modal-dialog modal-dialog-centered modal-md" role="document">
```suggestion
        <div class="modal-dialog" role="document">
```

2023-05-14 08:33 UTC, Akshiteshnaithani commented on Modules/CodeTrek/Entities/CodeTrekApplicant.php
> +
After doing the suggestions that were given, the   CI check is getting failed.

2023-05-14 15:42 UTC, Ayush8923 approved these changes
Approved with one comment.

2023-05-14 15:42 UTC, Ayush8923 commented on app/Imports/applicantImport.php
> +class ApplicantImport implements ToCollection, WithHeadingRow
Please update the all places. And please change the file name accordingly and use TitleCase for the file name.
```suggestion
class CodeTrekApplicantImport implements ToCollection, WithHeadingRow
```

2023-05-15 06:01 UTC, Abhinegi2 approved these changes
Looks good to me.

2023-05-15 07:57 UTC, Ayush8923 approved these changes
LGTM 👍

2023-06-29 21:33 UTC, GauravGusain98 requested changes
Please check the comments

2023-06-29 21:33 UTC, GauravGusain98 commented on app/Imports/CodeTrekApplicantImport.php
> +        foreach ($rows as $row) {
Can you fetch the email array from database and whenever looping through the row just check if the email is present in the array or not. If it is present simply continue the loop. We don't want duplicate emails in codeTrek module

2023-06-29 21:33 UTC, GauravGusain98 commented on app/Imports/CodeTrekApplicantImport.php
> +        }
We also need to add the `latest_round_name` column value. It should be level-1. Take it from config

2023-06-29 21:33 UTC, GauravGusain98 commented on app/Imports/CodeTrekApplicantImport.php
> +        }
Whenever we create an applicant we also need to make his entry in the `codetrek_applicant_round_details` table so create an entry in that table as well. 

Also, create a separate function for creating applicant

2023-07-18 13:24 UTC, closed without merging