rename round name from round_name to current_round_name in code_trek_…
ColoredCow/portal pull request #3082
Opened 2023-05-17 06:35 UTC by thisajaychauhan

…applicants table

Targets #3076 

### Description

Rename round name from round_name to current_round_name in code_trek applicant table.

### Checklist:
- [x] I have performed a self-review of my own code.

2023-05-18 06:06 UTC, GauravGusain98 requested changes

2023-05-18 06:06 UTC, GauravGusain98 commented on database/migrations/2023_05_17_114304_rename_round_name_column_of_code_trek_applicants_table.php
> +            $table->renameColumn('round_name', 'current_round_name');
```suggestion
            $table->renameColumn('round_name', 'latest_round_name');
```

2023-05-18 06:06 UTC, GauravGusain98 commented on database/migrations/2023_05_17_114304_rename_round_name_column_of_code_trek_applicants_table.php
> +            $table->renameColumn('current_round_name', 'round_name');
```suggestion
            $table->renameColumn('latest_round_name', 'round_name');
```

2023-05-18 06:06 UTC, GauravGusain98 commented on database/migrations/2023_05_17_114304_rename_round_name_column_of_code_trek_applicants_table.php
> +            $table->renameColumn('round_name', 'current_round_name');
You also need to correct the logics where we were using this column

2023-05-18 07:55 UTC, Ayush8923 requested changes
@thisajaychauhan  As far as I can see, the `round_name` column is used everywhere in the CodeTrek Modules. In the CodeTrek module, we are fetching and storing the data by round_name. There is a need to change there too.

2023-05-18 10:12 UTC, Ayush8923 requested changes
Left some comments. Please check.
And please test locally before assigning the for the review.

2023-05-18 10:12 UTC, Ayush8923 commented on database/migrations/2023_05_18_132943_rename_current_round_name_column_of_code_trek_applicants_table.php
> +        });
Where did you create this second migration file? It is not needed. You can make changes in the migration `rename_round_name_column_of_code_trek_applicants_table` file that you created earlier.

2023-05-18 10:12 UTC, Ayush8923 commented on Modules/HR/Database/Seeders/SettingsTableSeeder.php
> +            'setting_value' => '<div>Hello |*applicant_name*|,</div><br></div><div>Hope you are doing well and having a great time. We are reaching out to follow up on the interview scheduling proces
THis file is not needed. Please revert this.

2023-05-18 10:12 UTC, Ayush8923 commented on Modules/HR/Config/config.php
> +        'round-name' => '|*latest_round_name*|'
Same here.

2023-05-18 10:12 UTC, Ayush8923 commented on Modules/CodeTrek/Services/CodeTrekService.php
> +        $applicationRound->current_latest_round_name = 'level-1';
```suggestion
        $applicationRound->latest_round_name = 'level-1';
```

2023-05-19 10:56 UTC, Ayush8923 requested changes
Left some comments. 
Please check.

2023-05-19 10:56 UTC, Ayush8923 commented on Modules/HR/Config/config.php
> +        'round-name' => '|*latest_round_name*|'
Can you please revert this file? This file is not needed.

2023-05-19 10:56 UTC, Ayush8923 commented on Modules/HR/Database/Seeders/SettingsTableSeeder.php
> +            'setting_value' => '<div>Hello |*applicant_name*|,</div><br></div><div>Hope you are doing well and having a great time. We are reaching out to follow up on the interview scheduling proces
Same here. Please revert this file. It's not needed.

2023-05-20 05:59 UTC, Ayush8923 reviewed
Have you tested all the areas in CodeTrek Module?

2023-05-22 08:32 UTC, rahulpanwar16 approved these changes
Looks good to me.

2023-05-22 09:22 UTC, Ayush8923 approved these changes

2023-06-15 11:37 UTC, GauravGusain98 approved these changes
lgtm

2023-06-15 11:37 UTC, merged