Send mail to applicant
ColoredCow/portal pull request #3090
Opened 2023-05-18 13:53 UTC by Akshiteshnaithani

Targets #3083

### Description
New applicant is added to the Code Trek an email triggered to notify the applicant about their successful register.

### Checklist:

- [ ] I have performed a self-review of my own code.

2023-05-18 19:42 UTC, Ayush8923 requested changes
Left some comments. 
Please check.

2023-05-18 19:42 UTC, Ayush8923 commented on Modules/CodeTrek/Services/CodeTrekService.php
> +        Mail::to($data['email_id'], $data['first_name'])->send(new CodetrekMailApplicant());
Can you use the mail queue here?
Something like this.

```suggestion
        Mail::queue(new CodetrekMailApplicant($data));
```

2023-05-18 19:42 UTC, Ayush8923 commented on Modules/CodeTrek/Emails/CodetrekMailApplicant.php
> +    }
Please update here accordingly.

2023-05-20 06:03 UTC, Ayush8923 requested changes
Left some small comments.
Please take a look once.

2023-05-20 06:03 UTC, Ayush8923 commented on Modules/CodeTrek/Emails/CodetrekMailApplicant.php
> +    public function __construct($data)
Please update all the places accordingly.
```suggestion
    public function __construct($Applicant)
```

2023-05-20 06:03 UTC, Ayush8923 commented on Modules/CodeTrek/Resources/views/mail/codetrek.blade.php
> +	<p>We're delighted to have you join Codtreak! Get ready to embark on an exciting coding journey filled with learning, challenges, and a supportive community. Feel free to explore our resources and r
We need to change this mail template. I will update you once I created the mail template for this.

2023-05-21 09:21 UTC, Ayush8923 commented
@Akshiteshnaithani Here is the Mail template.

```
Hello |*applicant_name*|,

We hope this email finds you well. On behalf of the entire team at ColoredCow, We wanted to take a moment to congratulate you on the commencement of your internship. We are thrilled to have you on board and excited to see the valuable contributions you will bring to our organization.

Once again, congratulations on starting your internship! We believe you have the potential to achieve great things, and we look forward to witnessing your growth and accomplishments over the course of your internship. 

Wishing you a successful and fulfilling internship journey!

Best regards,
ColoredCow
```

2023-05-21 09:22 UTC, Ayush8923 commented
> @Akshiteshnaithani Here is the Mail template.
> 
> ```
> Hello |*applicant_name*|,
> 
> We hope this email finds you well. On behalf of the entire team at ColoredCow, We wanted to take a moment to congratulate you on the commencement of your internship. We are thrilled to have you on board and excited to see the valuable contributions you will bring to our organization.
> 
> Once again, congratulations on starting your internship! We believe you have the potential to achieve great things, and we look forward to witnessing your growth and accomplishments over the course of your internship. 
> 
> Wishing you a successful and fulfilling internship journey!
> 
> Best regards,
> ColoredCow
> ```

@GauravGusain98  Also please take a look at this mail. And let me know if there are any changes needed in this mail template.

2023-05-21 09:27 UTC, Ayush8923 commented
> @Akshiteshnaithani Here is the Mail template.
> 
> ```
> Hello |*applicant_name*|,
> 
> We hope this email finds you well. On behalf of the entire team at ColoredCow, We wanted to take a moment to congratulate you on the commencement of your CodeTrek internship. We are thrilled to have you on board and excited to see the valuable contributions you will bring to our organization.
> 
> Once again, congratulations on starting your CodeTrek internship! You have the potential to achieve great things, and we look forward to witnessing your growth and accomplishments over the course of your internship. 
> 
> Wishing you a successful and fulfilling CodeTrek internship journey!
> 
> Best regards,
> ColoredCow
> ```

@GauravGusain98  You also please take a look at this mail. And let me know if there are any changes needed in this mail template.

2023-05-22 10:17 UTC, Akshiteshnaithani commented
**After adding the applicant to Codetrek**

![image](https://github.com/ColoredCow/portal/assets/121417968/989888fb-e9dc-4afa-a7fe-312a0a28e901)

**The mail has been send to the applicant which is added to Codetrek**

![image](https://github.com/ColoredCow/portal/assets/121417968/788c0cfa-0ca3-4a82-af15-8ff1644af2c5)

2023-06-13 17:06 UTC, Ayush8923 requested changes
@Akshiteshnaithani Added one comment. Please implement this ASAP. Then I will merge this PR.

2023-06-13 17:06 UTC, Ayush8923 commented on Modules/CodeTrek/Services/CodeTrekService.php
> +        Mail::queue(new CodetrekMailApplicant($data));
Could you please comment on this line for now?  For now, we don't need this mail functionality. This mail functionality is enabled when the use of the codeTrek module starts in the proper way.

Also could you please add this line before this line?
`This line will be uncommented in the future when the use of the codeTrek module starts in the proper way.`
```suggestion
        // Mail::queue(new CodetrekMailApplicant($data));
```

2023-06-16 05:42 UTC, Ayush8923 approved these changes
LGTM 👍

2023-06-16 05:43 UTC, merged