Add-Dropdown-on-Dashboard
ColoredCow/portal pull request #3091
Opened 2023-05-18 13:55 UTC by Harshvardhan80

Targets #3080 

### Description
Added dropdown for officelocation on dashboard page in which the centre name appears.
After selecting the name of the centre, it is store in the usermeta table.

### Checklist:

- [ ] I have performed a self-review of my own code.

2023-05-18 19:50 UTC, Ayush8923 requested changes
Left some comments. 
Please check.

2023-05-18 19:50 UTC, Ayush8923 commented on resources/views/home.blade.php
> +    new Vue({ el: '#home_page' });
Can you please remove the extra spaces? And please update all places.

2023-05-18 19:50 UTC, Ayush8923 commented on resources/views/home.blade.php
> +                @endforeach
Can we write like this?
```suggestion
                @foreach($centres as $centre)
                    <option value="{{ $centre->centre_name }}">{{ $centre->centre_name }}</option>
                @endforeach
```

2023-05-18 19:50 UTC, Ayush8923 commented on app/Http/Controllers/HomeController.php
> +        return view('home')->with(['book' => $unreadBook, 'centre' => $centre]);
Please update the all places.
```suggestion
        return view('home')->with(['book' => $unreadBook, 'centres' => $centres]);
```

2023-05-18 19:50 UTC, Ayush8923 commented on routes/web.php
> +Route::post('/store-dropdown-value', 'HomeController@storeDropdownValue')->name('storeDropdownValue');
Can you please use an understandable name instead of `store-dropdown-value`?

2023-05-19 16:12 UTC, Ayush8923 requested changes
Testing Feedback
- [ ] When I choose the current location the current location is saved in the database but it's not reflected in the UI Dropdown. So current location also reflecting in the Dropdown.
**Please take a reference below screenshot.**
<img width="468" alt="image" src="https://github.com/ColoredCow/portal/assets/80516839/e8f9e4d9-7fd0-4ce7-b6f2-b563bab027c9">

2023-05-19 16:12 UTC, Ayush8923 commented on routes/web.php
> +Route::post('/location', 'HomeController@storeDropdownValue')->name('storeDropdownValue');
```suggestion
Route::post('/current-employee-location', 'HomeController@storeDropdownValue')->name('employee.location');
```

2023-05-19 16:12 UTC, Ayush8923 requested changes
Testing Feedback
- [x] When I choose the current location the current location is saved in the database but it's not reflected in the UI Dropdown. So current location also reflecting in the Dropdown.
**Please take a reference below screenshot.**
<img width="468" alt="image" src="https://github.com/ColoredCow/portal/assets/80516839/e8f9e4d9-7fd0-4ce7-b6f2-b563bab027c9">

2023-05-21 18:56 UTC, Ayush8923 requested changes
Left one small comment.

2023-05-21 18:56 UTC, Ayush8923 commented on routes/web.php
> +Route::post('/current-employee-location', 'HomeController@storeDropdownValue')->name('employee.location');
```suggestion
Route::post('/current-employee-location', 'HomeController@storeEmployeeLocation')->name('employee.location');
```

2023-05-21 18:56 UTC, Ayush8923 commented on app/Http/Controllers/HomeController.php
> +    public function storeDropdownValue(Request $request)
```suggestion
    public function storeEmployeeLocation(Request $request)
```

2023-05-26 06:19 UTC, GauravGusain98 requested changes
LGTM

2023-05-26 06:19 UTC, GauravGusain98 commented on app/Http/Controllers/HomeController.php
> +            'Centre' => 'required',
The name should be in small case. Also read about [exist rule in Laravel](https://laravel.com/docs/10.x/validation#basic-usage-of-exists-rule)
```suggestion
            'centre_name' => 'required | exists:office_locations,centre_name',
```

2023-05-26 06:19 UTC, GauravGusain98 commented on app/Http/Controllers/HomeController.php
> +            ['meta_value' => $request->Centre]
```suggestion
            ['meta_value' => $request->centre_name]
```

2023-05-26 06:19 UTC, GauravGusain98 commented on resources/views/home.blade.php
> +            <select class="btn bg-light text-left" name="Centre" onchange="this.form.submit()">
```suggestion
            <select class="btn bg-light text-left" name="centre_name" onchange="this.form.submit()">
```

2023-05-26 06:19 UTC, GauravGusain98 commented on resources/views/home.blade.php
> +            <span>Office Location</span>
```suggestion
            <span>Your office location</span>
```

2023-05-26 09:19 UTC, GauravGusain98 requested changes

2023-05-26 09:19 UTC, GauravGusain98 commented on app/Http/Controllers/HomeController.php
> +            ->value('meta_value');
Can we make a fucntion in user Model such that we can easily fetch office_location like 

auth()->user()->office_location

2023-05-26 09:19 UTC, GauravGusain98 commented on app/Http/Controllers/HomeController.php
> +            'centre_name' => 'required | exists:office_locations,centre_name',
Can you share what this `exists:office_locations,centre_name` do?

2023-05-26 09:19 UTC, GauravGusain98 commented on routes/web.php
> +Route::post('/current-employee-location', 'HomeController@storeEmployeeLocation')->name('employee.location');
```suggestion
Route::post('/current-employee-location', 'HomeController@storeEmployeeLocation')->name('update.employee.location');
```

2023-05-27 09:21 UTC, GauravGusain98 approved these changes
LGTM

2023-05-27 18:20 UTC, Ayush8923 approved these changes

2023-05-27 18:20 UTC, merged