hide-module error fix in step 4
ColoredCow/portal pull request #3093
Opened 2023-05-19 11:01 UTC by Ranjeet-Kalsi

Targets #3088 

Some changes in installation guide  step 4 
error fixed    --hide-module

2023-05-26 06:02 UTC, GauravGusain98 commented on docs/installation.md
> +    If you are still getting the error --hide-module then revert all changes by git checkout.
```suggestion
    If you are still getting the error --hide-module then revert all changes by `git checkout .`
```

2023-05-26 06:04 UTC, GauravGusain98 requested changes

2023-05-26 06:04 UTC, GauravGusain98 commented on docs/installation.md
> +    npm run dev
```suggestion
        npm run dev
```

2023-05-26 06:04 UTC, GauravGusain98 commented on docs/installation.md
> +    so it should be at version 5 only.
```suggestion
    **Note:** If laravel-mix version in package-lock.json changes to version 6 then npm run dev will throw error, so it should be at version 5 only.
```

2023-05-26 09:13 UTC, Ranjeet-Kalsi commented on docs/installation.md
> +    If you are still getting the error --hide-module then revert all changes by git checkout.
ok sir i will change it

2023-05-26 09:34 UTC, Ranjeet-Kalsi commented on docs/installation.md
> +    so it should be at version 5 only.
Sir changes applied, please review

2023-05-26 10:29 UTC, Ranjeet-Kalsi commented on docs/installation.md
> +    so it should be at version 5 only.
![hide module](https://github.com/ColoredCow/portal/assets/121542707/59d4c0da-5c79-43c7-b74f-eee1729fd21d)
Changes applied 
guide preview attached

2023-05-27 09:26 UTC, GauravGusain98 approved these changes
LGTM

2023-05-27 09:26 UTC, merged