Feature/3075/fixed project edit page bug
ColoredCow/portal pull request #3096
Opened 2023-05-20 07:00 UTC by MayankBisht8630

Targets #3075

### Description

Resolved The Project Edit Page Bug 

### Checklist:

- [ ] I have performed a self-review of my own code.

2023-06-13 08:18 UTC, LavishRawat commented
@MayankBisht8630  Please resolve the merge conflicts.

2023-06-25 15:27 UTC, GauravGusain98 requested changes

2023-06-25 15:27 UTC, GauravGusain98 commented on Modules/Project/Database/Factories/ProjectTeamMemberFactory.php
> +            'project_id' => Project::inRandomOrder()->first()->id,
The earlier code was creating new project and passing its id  to project_id column. The current code that you have added will not work if there are no project.

Also I didn't get why this file is changed.

2023-06-25 15:27 UTC, GauravGusain98 commented on Modules/Project/Database/Seeders/ProjectDatabaseSeeder.php
> +            ClientBillingDetail::factory()->create();
These should be added in the client factory instead of here

2023-06-25 15:27 UTC, GauravGusain98 commented on Modules/Client/Database/Factories/ClientAddressesFactory.php
> +        ];
Ideally when we are creating a ClientAddress then a new client should be created instead of adding id from existing client.

2023-06-25 15:27 UTC, GauravGusain98 commented on Modules/Client/Database/Factories/ClientBillingDetailsFactory.php
> +        ];
same here

2023-06-25 15:27 UTC, GauravGusain98 commented on Modules/Client/Database/Factories/ClientAddressesFactory.php
> +        ];
And Whenever we are creating a client then a new ClientAddress should be created for that client.

2023-06-28 11:26 UTC, GauravGusain98 commented
Closing this due to iactivity of assignee

2023-06-28 11:26 UTC, closed without merging