Revert "Revert "Feature/3020/creating seeder""
ColoredCow/portal pull request #3099
Opened 2023-05-20 08:37 UTC by MayankBisht8630

Reverts ColoredCow/portal#3097

2023-05-20 09:21 UTC, Ayush8923 requested changes
Left some comments. Please check.

2023-05-20 09:21 UTC, Ayush8923 commented on Modules/CodeTrek/Database/Seeders/CodeTrekApplicantsTableSeeder.php
> +        )->create();
We do not need to run this seeder in all environments. It should not run in a production environment. For that can you please add a condition here? Please take a reference of other modules.
Something like this.

```
 if (! app()->environment('production')) {
    // seeder logic
 }
```

2023-05-22 10:04 UTC, Ayush8923 requested changes
Can you please revert this file `Modules/CodeTrek/Database/Factories/.gitkeep`? it's not needed.

2023-05-24 07:32 UTC, GauravGusain98 requested changes

2023-05-24 07:32 UTC, GauravGusain98 commented on Modules/CodeTrek/Database/Factories/CodeTrekApplicantFactory.php
> +    }
I think this function should return a random university name.

2023-05-24 07:32 UTC, GauravGusain98 commented on Modules/CodeTrek/Database/Factories/CodeTrekApplicantFactory.php
> +            'university' =>$this->getCodeTrekApplicantsCollegeNames()[array_rand($this->getCodeTrekApplicantsCollegeNames())],
Instead of writing the code of getting random value here, you can simply return a random value from the function

2023-05-24 07:32 UTC, GauravGusain98 commented on Modules/CodeTrek/Database/Factories/CodeTrekApplicantRoundDetailFactory.php
> +            'feedback'=>'No',
keep it null

2023-05-24 07:32 UTC, GauravGusain98 commented on Modules/CodeTrek/Database/Factories/CodeTrekApplicantFactory.php
> +        ];
```suggestion
            'THDC-IHET',
            'Doon University',
            'Delhi University',
            'Chandigarh University',
            'Uttaranchal University',
            'Graphic Era University',
        ];
```

2023-05-24 07:35 UTC, MayankBisht8630 commented on Modules/CodeTrek/Database/Factories/CodeTrekApplicantFactory.php
> +    }
Random means 
Randomly from this list or from random anywhere

2023-05-24 08:01 UTC, GauravGusain98 commented on Modules/CodeTrek/Database/Factories/CodeTrekApplicantFactory.php
> +    }
randomly from the list of university you have provided

2023-05-24 08:02 UTC, MayankBisht8630 commented on Modules/CodeTrek/Database/Factories/CodeTrekApplicantFactory.php
> +    }
It is doing that only

2023-05-24 08:02 UTC, MayankBisht8630 commented on Modules/CodeTrek/Database/Factories/CodeTrekApplicantFactory.php
> +            'university' =>$this->getCodeTrekApplicantsCollegeNames()[array_rand($this->getCodeTrekApplicantsCollegeNames())],
Ok sir

2023-06-28 11:26 UTC, GauravGusain98 commented
Closing this due to inactivity of assignee

2023-06-28 11:26 UTC, closed without merging