Implement email notification for applicant round changes
ColoredCow/portal pull request #3101
Opened 2023-05-20 16:24 UTC by Akshiteshnaithani

Targets #3098

### Description:
 Implementing an email notification system for applicant round changes. It introduces the necessary code changes to trigger email notifications when the round of an applicant is changed.

### Changes Made:

- Added a new function to handle the email sending functionality.
- Added a new function to handle the email sending functionality.
- Implemented necessary configuration in email blade file.

### Checklist:

- [ ] I have performed a self-review of my own code.

2023-05-22 07:27 UTC, Ayush8923 requested changes
Left some comments. Please check.

2023-05-22 07:27 UTC, Ayush8923 commented on Modules/CodeTrek/Resources/views/mail/codetrek-round.blade.php
> +    <br>
We need to change these mail templates. I will update you once I created this mail templates.

2023-05-22 07:27 UTC, Ayush8923 commented on Modules/CodeTrek/Emails/CodetrekMailApplicantRound.php
> +        ->subject('ColoredCow Portal - Round Change Notification')
```suggestion
        ->subject('ColoredCow Portal - CodeTrek Round Update Notification')
```

2023-05-22 07:27 UTC, Ayush8923 commented on Modules/CodeTrek/Emails/CodetrekMailApplicantRound.php
> +    public $codetrekApplicant;
Can we write like this?
And Please test locally once.
```suggestion
    public $applicationRound, $codetrekApplicant;
```

2023-05-22 07:38 UTC, Akshiteshnaithani commented on Modules/CodeTrek/Emails/CodetrekMailApplicantRound.php
> +    public $codetrekApplicant;
public $applicationRound, $codetrekApplicant;
CI checks will give the error for this .

2023-05-22 10:03 UTC, Akshiteshnaithani commented on Modules/CodeTrek/Emails/CodetrekMailApplicantRound.php
> +        ->subject('ColoredCow Portal - Round Change Notification')
**Select the round of applicants**
![image](https://github.com/ColoredCow/portal/assets/121417968/32e264f0-b95d-4559-8060-8290b164eb6b)

**Mail is sent to the Applicant**
![image](https://github.com/ColoredCow/portal/assets/121417968/2eb7cb33-e20e-4298-8420-1d7e20835cfc)

2023-05-22 12:04 UTC, Ayush8923 commented
@Akshiteshnaithani Here is the Applicant round update notification mail template.

@GauravGusain98 Please take a look once.

```
Hello |*applicant_name*|,

We hope this email finds you well. I am delighted to inform you that you have successfully advanced to the |*round_name*| of the internship selection process at ColoredCow. Congratulations on this outstanding achievement!

The |*round_name*| of the internship will provide you with an opportunity to delve deeper into the specific projects and tasks relevant to your field of interest.

Wishing you the best of luck in the |*round_name*| of the internship!

Best regards,
ColoredCow
```

2023-05-22 12:26 UTC, Akshiteshnaithani commented
**Mail trigger after the round change of applicant** 
![image](https://github.com/ColoredCow/portal/assets/121417968/eeb23e88-2f31-4d65-913f-4b4e7c166212)

2023-05-23 11:49 UTC, Ayush8923 requested changes
Added one comment.

2023-05-23 11:49 UTC, Ayush8923 commented on Modules/CodeTrek/Resources/views/mail/codetrek-round.blade.php
> +	<p class="line">ColoredCow</p>
Could you please fix the indentation here?

2023-05-23 12:01 UTC, Akshiteshnaithani commented on Modules/CodeTrek/Resources/views/mail/codetrek-round.blade.php
> +	<p class="line">ColoredCow</p>
I have written correctly in blade file I think It is showing wrong in the PR.

2023-05-24 06:16 UTC, Ayush8923 requested changes
Added some small changes, please check.

2023-05-24 06:16 UTC, Ayush8923 commented on Modules/CodeTrek/Emails/CodetrekMailApplicantRound.php
> +class CodetrekMailApplicantRound extends Mailable
```suggestion
class CodeTrekApplicantRoundReminder extends Mailable
```

2023-05-24 06:16 UTC, Ayush8923 commented on Modules/CodeTrek/Services/CodeTrekRoundDetailService.php
> +        Mail::send(new CodetrekMailApplicantRound($applicationRound, $codetrekApplicant));
```suggestion
        Mail::send(new CodeTrekApplicantRoundReminder($applicationRound, $codetrekApplicant));
```

2023-05-24 06:16 UTC, Ayush8923 commented on Modules/CodeTrek/Services/CodeTrekRoundDetailService.php
> +use Modules\CodeTrek\Emails\CodetrekMailApplicantRound;
```suggestion
use Modules\CodeTrek\Emails\ CodeTrekApplicantRoundReminder;
```

2023-05-24 07:43 UTC, Ayush8923 approved these changes

2023-05-24 08:04 UTC, GauravGusain98 requested changes
Please check the comments

2023-05-24 08:04 UTC, GauravGusain98 commented on Modules/CodeTrek/Emails/CodeTrekApplicantRoundMail.php
> +        ->to($this->codetrekApplicant[0]->email)
Its not a good practice to take the value of an array using index. If its only one applicant then you should pass codetrekApplicant object instead of array

2023-05-24 08:04 UTC, GauravGusain98 commented on Modules/CodeTrek/Services/CodeTrekRoundDetailService.php
> +        $codetrekApplicant = CodeTrekApplicant::where('id', $applicant->id)->get();
Instead of using where on if you can use find method. It will return applicant object if found else null.

2023-06-13 17:08 UTC, Ayush8923 requested changes
@Akshiteshnaithani Added one comment. Please check and implement this comment ASAP. Then I will merge this PR.

2023-06-13 17:08 UTC, Ayush8923 commented on Modules/CodeTrek/Services/CodeTrekRoundDetailService.php
> +        Mail::send(new CodeTrekApplicantRoundMail($applicationRound, $codetrekApplicant));
Could you please comment on this line for now? For now, we don't need this mail functionality. This mail functionality is enabled when the use of the codeTrek module starts in the proper way.

Also could you please add this line before this line?
`This line will be uncommented in the future when the use of the codeTrek module starts in the proper way.`
```suggestion
        // Mail::send(new CodeTrekApplicantRoundMail($applicationRound, $codetrekApplicant));
```

2023-06-16 05:44 UTC, Ayush8923 approved these changes

2023-06-27 19:46 UTC, GauravGusain98 approved these changes
LGTM

2023-06-27 19:46 UTC, merged