Feature/3114/create laravel console command for new subscriber
ColoredCow/portal pull request #3124
Opened 2023-06-05 07:20 UTC by rajatsajwan

Target #3114

Description:
multiple   jobIds  can be their

2023-06-05 10:03 UTC, mohitgusain commented on app/Console/Commands/sendNewSubscriber.php
> +            $jobIds = Application::where('hr_applicant_id', $applicant->id)->pluck('hr_job_id');
What is `jobIds`? is it a collection or array ?

2023-06-05 10:03 UTC, mohitgusain commented on app/Console/Commands/sendNewSubscriber.php
> +            foreach ($jobIds as $jobId) {
Can you add a check here? if $jobIds is not null then foreach loop will execute.

2023-06-05 10:03 UTC, mohitgusain commented on app/Console/Commands/sendNewSubscriber.php
> +                if ($jobId) {
This check will not be required then

2023-06-05 10:05 UTC, mohitgusain commented
@rajatsajwan make sure that you have tested this code in you locally

2023-06-05 11:01 UTC, rajatsajwan commented
I am testing this code in my local.

2023-06-06 05:02 UTC, mohitgusain approved these changes

2023-06-06 06:31 UTC, rathorevaibhav requested changes

2023-06-06 06:31 UTC, rathorevaibhav commented on app/Console/Commands/sendNewSubscriber.php
> +                }
there are multiple queries happening here. Can't we run one query which returns titles for all the job ids?

2023-06-06 06:31 UTC, rathorevaibhav commented on Modules/HR/Http/Controllers/Recruitment/ApplicantController.php
> -        // try {
why is this code removed?

2023-06-06 06:38 UTC, rajatsajwan commented
// try {

2023-06-06 09:18 UTC, rathorevaibhav approved these changes

2023-06-06 09:26 UTC, merged