#3129 Display Only Active Applicants in CodeTreak Applicant Sidebar and Resolve Overlapping with Other Modules.
ColoredCow/portal pull request #3130
Opened 2023-06-07 11:55 UTC by jaskaransingh304

Targets #3129 

### Description

Made changes so only to display active applicants in CodeTreak Applicant Sidebar.
Resolved Overlapping of CodeTreak Applicant Sidebar with other modules.
These changes were required as the user will get to see only active applicant.Opening the sidebar does not overlaps with tables in other modules, resulting in better view for user.
 This pull request , solves the issue and displays Active applicants only in CodeTreak Applicant Sidebar and the sidebar does not overlaps with other modules.

### Checklist:

- [x ] I have performed a self-review of my own code.

### Approach -
Checked the view page and tried to figure , how data is passed in view page.
Checked the css file for sidebar.

###Expected Time - 4-6  hours.
Code review and documentation: 0.5-1 hour.
then ,
Making the required changes : 1 hour.

For testing, code review, and documentation : 1 hour.

### TOTAL TIME SPEND IN A TASK =3 hours

### Changes required in code -
As there was no condition to display active applicants, so added a condition where it displays active applicants only instead of all. 
Made changes in stack order of task i.e z-index. So sidebar opens up and does not overlaps.

2023-06-07 11:58 UTC, jaskaransingh304 commented
Attaching a screenshot for reference -
![Screenshot (4)](https://github.com/ColoredCow/portal/assets/109968722/e9747620-7669-4003-9e3e-59fbabc96690)

2023-06-08 05:20 UTC, GauravGusain98 requested changes

2023-06-08 05:20 UTC, GauravGusain98 commented on Modules/CodeTrek/Resources/views/sidebar.blade.php
> +            @endif
Instead of adding a check here. I guess we can only fetch active candidates from database i.e we can update the query from which we are getting this variable `$codeTrekApplicants`. 

The approach that I am suggesting will reduce the complexity as the loop will not run for all the candidates

2023-06-08 05:20 UTC, GauravGusain98 commented on Modules/CodeTrek/Resources/views/sidebar.blade.php
> +            @endif
You can check Harshvardhan PR that he had created for implementing the sidebar and see how he is getting the applicants from database.

2023-06-08 05:25 UTC, jaskaransingh304 commented on Modules/CodeTrek/Resources/views/sidebar.blade.php
> +            @endif
Sure , @GauravGusain98 , I will do that.

2023-06-09 05:52 UTC, GauravGusain98 approved these changes
LGTM

2023-06-09 05:52 UTC, merged