added the modal form for applicant feedback
ColoredCow/portal pull request #3131
Opened 2023-06-08 07:14 UTC by thisajaychauhan

Targets #3067 

### Description
I have made a clickable link for the applicant's name which is located in the sidebar. On clicking the applicant's name a feedback modal form will pop up and the user can give feedback to that applicant it will be easy for users to give feedback.

## Expected Time

- [x] Add clickable links to the intern name on the sidebar and open a modal when a candidate name is clicked. `3-4 hours`
- [x] Show candidate details in the modal. `3-4 hours`
- [x] Create a table schema for the database table. `1-2 hours`
- [x]  store feedback and categories. `3-4 hours`
- [x] For testing, code review, and documentation. `2-3 hours`

## Actual Time 

- [ ] Add clickable links to the intern name on the sidebar and open a modal when a candidate name is clicked. `5-6 hours`
- [ ] Show candidate details in the modal. `7-8- hours`
- [ ] Create a table schema for the database table. `4-5 hours`
- [ ]  store feedback and categories. `7-8 hours`
- [ ] For testing, code review, and documentation. `2-3 hours`

---
### TOTAL TIME = HOURS
---

## Created figma file for feedback modal form
- Created figma file for feedback modal form [Figma link](https://www.figma.com/file/TlAgl2OnnoAudoGiZR4BPO/Untitled?type=design&node-id=0%3A1&t=7NTVkLABhGbRyE9M-1)

### Checklist:

- [x] I have performed a self-review of my own code.

2023-06-09 07:27 UTC, LavishRawat requested changes

2023-06-09 07:27 UTC, LavishRawat commented on Modules/CodeTrek/Entities/CodeTrekCandidateFeedback.php
> +    // public function candidate()
@thisajaychauhan can you remove the commented code if it is not required?

2023-06-09 07:59 UTC, LavishRawat requested changes

2023-06-09 07:59 UTC, LavishRawat commented on Modules/CodeTrek/Resources/views/sidebar.blade.php
> +<div id="applicant-sidebar" class="position-fixed bg-white p-1" style="z-index: 1050;">
@thisajaychauhan can we use the Z-index  in the below Style tag?

2023-06-09 08:12 UTC, thisajaychauhan commented on Modules/CodeTrek/Resources/views/sidebar.blade.php
> +<div id="applicant-sidebar" class="position-fixed bg-white p-1" style="z-index: 1050;">
yes, added to the below Style tag.

2023-06-09 08:12 UTC, thisajaychauhan commented on Modules/CodeTrek/Entities/CodeTrekCandidateFeedback.php
> +    // public function candidate()
not required, deleted them.

2023-06-09 09:02 UTC, GauravGusain98 commented on Modules/CodeTrek/Resources/views/sidebar.blade.php
> +<div id="applicant-sidebar" class="position-fixed bg-white p-1" style="z-index: 1050;">
By the way why have you used this z-index?

2023-06-09 09:25 UTC, thisajaychauhan commented on Modules/CodeTrek/Resources/views/sidebar.blade.php
> +<div id="applicant-sidebar" class="position-fixed bg-white p-1" style="z-index: 1050;">
the modal form is overlapping with the background UI, some background UI parts come in front of the modal form.

2023-06-09 13:33 UTC, LavishRawat commented
@thisajaychauhan

1. The email in the Feedback Form is going out of the Modal . Please have a look.

<img width="1440" alt="Screenshot 2023-06-09 at 6 54 59 PM" src="https://github.com/ColoredCow/portal/assets/108713935/2d857e27-6d01-497b-a9b9-a8928847dc2b">

---

2. Getting the Following error while submitting the form.
<img width="1079" alt="Screenshot 2023-06-09 at 6 56 24 PM" src="https://github.com/ColoredCow/portal/assets/108713935/d88cdb5d-3ec5-4a80-9c68-0a23dd35ceac">

2023-06-09 14:36 UTC, Ayush8923 requested changes
Added some comments.  Please check.

2023-06-09 14:36 UTC, Ayush8923 commented on Modules/CodeTrek/Resources/views/modals/add-applicant-modal.blade.php
> +                                 <input type="text" class="form-control" name="last_name" id="lastName" placeholder="Enter last name" value="" required>
let's add `old()` also in the value.

2023-06-09 14:36 UTC, Ayush8923 commented on Modules/CodeTrek/Resources/views/modals/sidebar-feedback-modal.blade.php
> + {{-- Modal start --}}
```suggestion
```

2023-06-09 14:36 UTC, Ayush8923 commented on Modules/CodeTrek/Resources/views/modals/sidebar-feedback-modal.blade.php
> +                                       onmouseout="this.style.color=''; this.style.transform='none'">
Can you please let me know, Why did we need it?

2023-06-09 14:36 UTC, Ayush8923 commented on Modules/CodeTrek/Resources/views/modals/sidebar-feedback-modal.blade.php
> +                                       class="positive"
Can you give a generic name to it?

2023-06-09 14:36 UTC, Ayush8923 commented on Modules/CodeTrek/Resources/views/modals/sidebar-feedback-modal.blade.php
> +                                       class="negative"
Same here.

2023-06-09 14:36 UTC, Ayush8923 commented on Modules/CodeTrek/Resources/views/modals/sidebar-feedback-modal.blade.php
> +                                       onmouseout="this.style.color=''; this.style.transform='none'">
Can you please let me know, Why did we need it?
Same question here.

2023-06-09 14:36 UTC, Ayush8923 commented on Modules/CodeTrek/Resources/views/sidebar.blade.php
> +    }
Could you please move this CSS to the `app.scss` file inside the CodeTrek Module?

2023-06-09 14:36 UTC, Ayush8923 commented on Modules/CodeTrek/Resources/views/sidebar.blade.php
> +    });
Same here. 
Can you please move this script in `app.js` file inside the CodeTrek Module?

2023-06-09 14:36 UTC, Ayush8923 commented on app/Http/View/Composers/CodeTrekApplicantsComposer.php
> +        $view->with('codeTrekApplicants', $codeTrekApplicants)->with('feedback_categories', $feedback_categories);
Can we write like this?
Please test locally once, and let me know, it's works or not.
```suggestion
        $view->with([
    'codeTrekApplicants' => $codeTrekApplicants,
    'feedback_categories' => $feedback_categories,
]);
```

2023-06-09 14:36 UTC, Ayush8923 commented on Modules/CodeTrek/Resources/views/modals/sidebar-feedback-modal.blade.php
> +                                </h5>
```suggestion
                                <h5>{{ $codeTrekApplicant->first_name }} {{ $codeTrekApplicant->last_name }}</h5>
```

2023-06-09 14:36 UTC, Ayush8923 commented on Modules/CodeTrek/Resources/views/modals/sidebar-feedback-modal.blade.php
> +
Remove this line.

2023-06-09 17:59 UTC, thisajaychauhan commented on Modules/CodeTrek/Resources/views/modals/sidebar-feedback-modal.blade.php
> + {{-- Modal start --}}
done.

2023-06-09 18:01 UTC, thisajaychauhan commented on Modules/CodeTrek/Resources/views/modals/sidebar-feedback-modal.blade.php
> +                                       onmouseout="this.style.color=''; this.style.transform='none'">
for the thumbs-up and down feedback. when you hover over them they will increase their size a little bit.it is just for styling.

2023-06-09 18:02 UTC, thisajaychauhan commented on Modules/CodeTrek/Resources/views/modals/sidebar-feedback-modal.blade.php
> +                                       onmouseout="this.style.color=''; this.style.transform='none'">
for the thumbs-up and down feedback. when you hover over them they will increase their size a little bit.it is just for styling.

2023-06-09 18:04 UTC, thisajaychauhan commented on Modules/CodeTrek/Resources/views/sidebar.blade.php
> +    }
done.

2023-06-09 18:05 UTC, thisajaychauhan commented on Modules/CodeTrek/Resources/views/sidebar.blade.php
> +    });
done

2023-06-09 18:10 UTC, thisajaychauhan commented on Modules/CodeTrek/Resources/views/modals/sidebar-feedback-modal.blade.php
> +                                </h5>
done

2023-06-09 18:10 UTC, thisajaychauhan commented on Modules/CodeTrek/Resources/views/modals/sidebar-feedback-modal.blade.php
> +
done.

2023-06-15 05:53 UTC, thisajaychauhan commented on Modules/CodeTrek/Resources/views/modals/sidebar-feedback-modal.blade.php
> +                                       class="positive"
done.

2023-06-15 05:53 UTC, thisajaychauhan commented on Modules/CodeTrek/Resources/views/modals/sidebar-feedback-modal.blade.php
> +                                       class="negative"
done.

2023-06-15 05:54 UTC, thisajaychauhan commented on app/Http/View/Composers/CodeTrekApplicantsComposer.php
> +        $view->with('codeTrekApplicants', $codeTrekApplicants)->with('feedback_categories', $feedback_categories);
Yes, it is working.

2023-06-15 06:00 UTC, thisajaychauhan commented
> 2. Getting the Following error while submitting the form.
> 
> <img alt="Screenshot 2023-06-09 at 6 56 24 PM" width="1079" src="https://user-images.githubusercontent.com/108713935/244706663-d88cdb5d-3ec5-4a80-9c68-0a23dd35ceac.png">



the above error is occurring because my previous PR for  [#3082](https://github.com/ColoredCow/portal/pull/3082) is not merged.

2023-06-15 08:27 UTC, LavishRawat approved these changes

2023-06-15 08:27 UTC, LavishRawat commented on resources/js/app.js
> +// feedback modal form
@thisajaychauhan Remove this line.

2023-06-15 08:28 UTC, LavishRawat requested changes

2023-06-15 08:28 UTC, LavishRawat commented on resources/js/app.js
> +// feedback modal form
@thisajaychauhan  Remove this line

2023-06-15 09:19 UTC, thisajaychauhan commented on resources/js/app.js
> +// feedback modal form
removed.

2023-06-16 08:48 UTC, Ayush8923 submitted a review, later dismissed
Added a few more comments. Please check.

2023-06-16 08:48 UTC, Ayush8923 commented on Modules/CodeTrek/Http/Controllers/CodeTrekController.php
> +        $this->service->storeFeedback($data);
I think we can directly write like this.
```suggestion
        $this->service->storeFeedback($request->all());
```

2023-06-16 08:48 UTC, Ayush8923 commented on Modules/CodeTrek/Resources/views/modals/sidebar-feedback-modal.blade.php
> +                    <div>
This `div` is needed?

2023-06-16 08:48 UTC, Ayush8923 commented on Modules/CodeTrek/Routes/web.php
> +    Route::post('/storeFeedback', 'CodeTrekController@storeFeedback')->name('codetrek.storeFeedback');
```suggestion
    Route::post('/codetrekApplicantFeedback', 'CodeTrekController@codetrekApplicantFeedback')->name('codetrek.codetrekApplicantFeedback');
```

2023-06-16 08:48 UTC, Ayush8923 commented on resources/sass/app.scss
> +    position: absolute;
Please use the Bootstrap classes instead of extra external CSS. And please update the all places.

2023-06-16 08:48 UTC, Ayush8923 commented on resources/sass/app.scss
> +    width: 50%;
Please define this height and width inside the `Variable.scss` file. 
And the use the directly like 
```
h-3 w-3
```

2023-06-16 08:48 UTC, Ayush8923 commented on resources/sass/app.scss
> +  position: absolute;
Same here.

2023-06-16 09:19 UTC, thisajaychauhan commented on resources/sass/app.scss
> +  position: absolute;
done

2023-06-16 09:34 UTC, thisajaychauhan commented on Modules/CodeTrek/Routes/web.php
> +    Route::post('/storeFeedback', 'CodeTrekController@storeFeedback')->name('codetrek.storeFeedback');
done.

2023-06-16 09:34 UTC, thisajaychauhan commented on Modules/CodeTrek/Resources/views/modals/sidebar-feedback-modal.blade.php
> +                    <div>
not needed removed.

2023-06-16 09:36 UTC, thisajaychauhan commented on Modules/CodeTrek/Resources/views/modals/sidebar-feedback-modal.blade.php
> +                    <div class="">
not needed removed

2023-06-16 09:37 UTC, thisajaychauhan commented on resources/sass/app.scss
> +    position: absolute;
this is existing code.

2023-06-16 09:38 UTC, thisajaychauhan commented on resources/sass/app.scss
> +    width: 50%;
this also existing code.

2023-06-17 08:16 UTC, LavishRawat approved these changes

2023-06-24 10:58 UTC, GauravGusain98 requested changes

2023-06-24 10:58 UTC, GauravGusain98 commented on database/migrations/2023_06_05_163616_create_code_trek_candidate_feedbacks_table.php
> +            $table->string('feedback');
`String` field has a limit of 191 character only. Lets make it a `text` field

2023-06-24 10:58 UTC, GauravGusain98 commented on resources/js/app.js
>  });
This will create issue as this app.js file gets compiled on every page. So instead of writing this code in app.js we can use the app.js which is inside the CodeTrek Module.

2023-06-24 10:58 UTC, GauravGusain98 commented on resources/sass/app.scss
> +}
This is very generic name and anyone can use this name which can cause issue at that place. Lets make it more specific to codetrek feedbacks so that we can make sure that other developer don't use the same name by mistake

2023-06-24 10:58 UTC, GauravGusain98 commented on resources/views/layouts/app.blade.php
> +    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>
Why do we need this?

2023-06-24 10:58 UTC, GauravGusain98 commented on Modules/CodeTrek/Routes/web.php
> +    Route::post('/storeCodeTrekApplicantFeedback', 'CodeTrekController@storeCodeTrekApplicantFeedback')->name('codetrek.storeCodeTrekApplicantFeedback');
The formatting of route name and URL is not correct
```suggestion
    Route::post('/store-feedback', 'CodeTrekController@storeCodeTrekApplicantFeedback')->name('codetrek.store-feedback');
```

2023-06-24 10:58 UTC, GauravGusain98 commented on Modules/CodeTrek/Resources/views/modals/sidebar-feedback-modal.blade.php
> +                    <h5 class="modal-title" id="exampleModalLabel"><strong>Feedback Form</strong></h5>
Please use meaningful name for id and if its not being used then remove it
```suggestion
                    <h5 class="modal-title" id="globalCodetrekFeedbackModal"><strong>Feedback Form</strong></h5>
```

2023-06-24 10:58 UTC, GauravGusain98 commented on Modules/CodeTrek/Resources/views/modals/sidebar-feedback-modal.blade.php
> +<div class="feedback-modal modal fade" id="candidatefeedback{{ $codeTrekApplicant->id }}" tabindex="-1" z-index="1"
Correct naming convention
```suggestion
<div class="feedback-modal modal fade" id="candidateFeedback{{ $codeTrekApplicant->id }}" tabindex="-1" z-index="1"
```

2023-06-24 10:58 UTC, GauravGusain98 commented on Modules/CodeTrek/Resources/views/modals/sidebar-feedback-modal.blade.php
> +                                @foreach ($feedback_categories as $feedback_category)
PHP varibale naming convention not correct. Use camelCase

2023-06-24 10:58 UTC, GauravGusain98 commented on Modules/CodeTrek/Resources/views/modals/sidebar-feedback-modal.blade.php
> +                                    <option value="{{ $feedback_category->id }}">{{ $feedback_category->category_name }}</option>
Correct variable naming convention

2023-06-24 10:58 UTC, GauravGusain98 commented on Modules/CodeTrek/Resources/views/modals/sidebar-feedback-modal.blade.php
> +                                <label for="feedback_type">Feedback Type</label>
Whenever adding a normal text use text sanitizing. You can read more about it in Laravel documentation
```suggestion
                                <label for="feedback_type">{{ __('Feedback Type') }}</label>
```

2023-06-24 10:58 UTC, GauravGusain98 commented on Modules/CodeTrek/Resources/views/sidebar.blade.php
> +                <a class="applicant-name" data-toggle="modal" data-target="#candidatefeedback{{ $codeTrekApplicant->id }}">
Correct Naming Convention
```suggestion
                <a class="applicant-name" data-toggle="modal" data-target="#candidateFeedback{{ $codeTrekApplicant->id }}">
```

2023-06-24 10:58 UTC, GauravGusain98 commented on Modules/CodeTrek/Entities/CodeTrekCandidateFeedback.php
> +    protected $fillable = ['candidate_id', 'posted_by', 'category_id', 'latest_round_name', 'feedback', 'feedback_type', 'posted_on'];
If we are filling all the column then we can use `guarded` attribute
```suggestion
    protected $guarded = [];
```

2023-06-24 10:58 UTC, GauravGusain98 commented on Modules/CodeTrek/Resources/views/modals/sidebar-feedback-modal.blade.php
> +        <form action="{{ route('codetrek.storeCodeTrekApplicantFeedback') }}" method="POST" id='feedback_form'>
Correct route naming convention and id naming convention

2023-06-24 10:58 UTC, GauravGusain98 commented on Modules/CodeTrek/Resources/views/modals/sidebar-feedback-modal.blade.php
> +        <form action="{{ route('codetrek.storeCodeTrekApplicantFeedback') }}" method="POST" id='feedback_form'>
Id should be in cameCase and route name should be in kabab-case

2023-06-24 10:58 UTC, GauravGusain98 commented on Modules/CodeTrek/Resources/views/modals/sidebar-feedback-modal.blade.php
> +                                <input type="hidden" name="latest_round_name" id="latest_round_name" value="{{ $codeTrekApplicant->latest_round_name }}">
id name should be in camelCase

2023-06-24 10:58 UTC, GauravGusain98 commented on Modules/CodeTrek/Resources/views/modals/sidebar-feedback-modal.blade.php
> +                                <h6 for="graduation_year">Graduation Year</h6>
use camelCase naming convention as `for` attribue uses id name as value

2023-06-24 10:58 UTC, GauravGusain98 commented on Modules/CodeTrek/Resources/views/modals/sidebar-feedback-modal.blade.php
> +                                <label for="feedback_categories">Feedback Categories</label>
correct naming convention in for attribute

2023-06-24 10:58 UTC, GauravGusain98 commented on Modules/CodeTrek/Resources/views/modals/sidebar-feedback-modal.blade.php
> +                            <select name="feedback_category" id="feedback_category" class="form-control" required>
correct id naming convention

2023-06-24 12:00 UTC, thisajaychauhan commented on database/migrations/2023_06_05_163616_create_code_trek_candidate_feedbacks_table.php
> +            $table->string('feedback');
done

2023-06-24 13:08 UTC, thisajaychauhan commented on Modules/CodeTrek/Resources/views/modals/sidebar-feedback-modal.blade.php
> +                    <h5 class="modal-title" id="exampleModalLabel"><strong>Feedback Form</strong></h5>
not needed, removed.

2023-06-30 07:16 UTC, GauravGusain98 requested changes

2023-06-30 07:16 UTC, GauravGusain98 commented on Modules/CodeTrek/Resources/assets/sass/app.scss
> +}
Do we want to run this only inside codetrek module? I guess this feedback form will be available in all the pages, so it should be inside main app.scss file only.

2023-06-30 07:16 UTC, GauravGusain98 commented on Modules/CodeTrek/Resources/views/layouts/master.blade.php
> +<link href="{{ mix('/css/codetrek.css') }}" rel="stylesheet">
I think it should be like this as js path is also provider like this, please check can confirm if this also works or not?
```suggestion
<link href="{{ mix('css/codetrek.css') }}" rel="stylesheet">
```

2023-06-30 07:16 UTC, GauravGusain98 commented on Modules/CodeTrek/Services/CodeTrekService.php
> +        $feedback->posted_on = date('y-m-d');
This carbon function will also work
```suggestion
        $feedback->posted_on = today();
```

2023-06-30 07:16 UTC, GauravGusain98 commented on database/Seeders/CodetrekSeeder.php
> +        ]);
We dont need this as the task of creating seeder is done by someone else

2023-06-30 12:29 UTC, thisajaychauhan commented on Modules/CodeTrek/Resources/views/layouts/master.blade.php
> +<link href="{{ mix('/css/codetrek.css') }}" rel="stylesheet">
yes, it is working.

2023-07-02 18:20 UTC, GauravGusain98 requested changes

2023-07-02 18:20 UTC, GauravGusain98 commented on Modules/CodeTrek/Resources/assets/js/app.js
> +	});
I think this is duplicate code as the same code based been written in the main app.js file as well. Please remove this.

2023-07-06 09:41 UTC, GauravGusain98 commented
### Testing feedbacks
1. The thumbs up and thumbs down icon is not getting selected

2023-07-06 09:54 UTC, thisajaychauhan commented
> ### Testing feedbacks
> 1. The thumbs up and thumbs down icon is not getting selected

@GauravGusain98 In my local, it is selecting the desired thumb and also stores the data in DB, after taking the latest pull.

![image](https://github.com/ColoredCow/portal/assets/120373044/ac36b404-f901-4f9b-8d69-ef7fd1f130c0)

---
![Screenshot 2023-07-06 151653](https://github.com/ColoredCow/portal/assets/120373044/89267195-c8b6-4a48-827a-94cdd8222d62)

2023-07-06 17:39 UTC, GauravGusain98 approved these changes
LGTM

2023-07-06 17:39 UTC, merged