Update the CodeTrek installation guide line
ColoredCow/portal pull request #3132
Opened 2023-06-08 13:23 UTC by Akshiteshnaithani

### Description
Updated the Code

### Checklist:

- [ ] I have performed a self-review of my own code.

2023-06-08 15:53 UTC, Ayush8923 requested changes
Added one comment. Please check.

2023-06-08 15:53 UTC, Ayush8923 commented on docs/installation.md
> +    WORDPRESS_ENABLED: Set this to `true` to enable the integration with the Colored Cow website. If it is set to "false," the integration will not work.
Can you write these points next to the same points which are already written? I think you don't need to write the same points again.
Something like this:-
```
DB_WORDPRESS_PREFIX=cc_
WORDPRESS_ENABLED=true
```

2023-06-09 06:30 UTC, GauravGusain98 requested changes

2023-06-09 06:30 UTC, GauravGusain98 commented on docs/installation.md
> +    DB_WORDPRESS_PREFIX=cc_
Can you also explain the meaning of these variables as you had done earlier.

2023-06-09 06:30 UTC, GauravGusain98 commented on docs/installation.md
> +    DB_WORDPRESS_PREFIX=cc_
Just put them before the code block

2023-06-09 09:34 UTC, Ayush8923 submitted a review, later dismissed
Added some more comments. Please check.

2023-06-09 10:03 UTC, tarunnjoshi commented on docs/installation.md
> +       - WORDPRESS_ENABLED: Set this to `true` to enable the integration with the ColoredCow website. If it is set to "false," the integration will not work.
```suggestion
       - WORDPRESS_ENABLED: Set this to `true` to enable the integration with the ColoredCow website. If it is set to "false" the integration will not work.
```

2023-06-25 14:20 UTC, GauravGusain98 approved these changes

2023-06-25 14:21 UTC, merged