#3023 Add Counts to each tabs in CodeTrek
ColoredCow/portal pull request #3134
Opened 2023-06-09 14:29 UTC by jaskaransingh304

Targets #{3023}

### Description

Several changes were implemented in Codetrek to enhance the user experience. Firstly, the service page of Codetrek underwent modifications to display the total counts alongside the tabs. This improvement allows users to quickly ascertain the number of items associated with each tab.

In addition, adjustments were made to the controller to pass the necessary requests to the view page. This ensures that the updated functionality is properly integrated and accessible to users.

Moreover, variable values were assigned adjacent to the status names in the view page. As a result, these values are displayed beside each tab, providing users with immediate information about the associated status.

Overall, these changes in Codetrek's service page, controller, and view page contribute to an improved user interface and facilitate easier navigation and understanding of the data.

### Checklist:

- [x] I have performed a self-review of my own code.

### Approach -
Checked the view page and tried to figure , how data can be passed in it.
Checked the view page of projects , and figured how function was created in service page and used in menu_header. Took its reference. 

### Expected Time - 4-6 hours.
### Code review and documentation: 1 hour.
then ,
### Making the required changes :  4 hour.

### For testing, code review, and documentation : 2 hour.

### Total time spent in task =7 hours
### Changes required in code -
As there was no function to count status, so added a function in Codetrek Service page.
Return request was made in controller as what it will return to view page, then added the counts next to the status name.

2023-06-10 11:29 UTC, GauravGusain98 requested changes

2023-06-10 11:29 UTC, GauravGusain98 commented on Modules/CodeTrek/Http/Controllers/CodeTrekController.php
> +        $completedCount = $applicantData['completedCount'];
These are unwanted variables. We can simply return the $applicantsData variable to view

2023-06-10 11:29 UTC, GauravGusain98 commented on Modules/CodeTrek/Http/Controllers/CodeTrekController.php
> +        $applicants = $applicantData['applicants'];
I think we are getting applicants data and not only applicants. So lets change the variable name to $applicantsData

2023-06-10 11:29 UTC, GauravGusain98 commented on Modules/CodeTrek/Services/CodeTrekService.php
> +        $completedCount = CodeTrekApplicant::where('status', 'completed')->count();
Can you re write this using group function such that you will get 2 columns - status_name and count of applicants in that status. 

You can read about group clause in my SQL and see if laravel provides any function for grouping.

2023-06-10 11:31 UTC, jaskaransingh304 commented on Modules/CodeTrek/Services/CodeTrekService.php
> +        $completedCount = CodeTrekApplicant::where('status', 'completed')->count();
I will do that

2023-06-10 12:17 UTC, jaskaransingh304 commented on Modules/CodeTrek/Http/Controllers/CodeTrekController.php
> +        $completedCount = $applicantData['completedCount'];
Sure

2023-06-13 08:37 UTC, jaskaransingh304 commented
![image](https://github.com/ColoredCow/portal/assets/109968722/40c8a42d-e260-4be4-ab74-cfea49141587)
![image](https://github.com/ColoredCow/portal/assets/109968722/2644bb5d-55d6-4c63-a181-f07722ee995c)
     
Attaching screenshot for reference

2023-06-15 07:46 UTC, GauravGusain98 commented on Modules/CodeTrek/Services/CodeTrekService.php
> +        }
The the slug valuesof status from config.php which is inside `Modules/CodeTrek/config`
<img width="465" alt="image" src="https://github.com/ColoredCow/portal/assets/54376313/17f1df52-f40f-48ab-b290-977b68193d92">

2023-06-15 07:56 UTC, GauravGusain98 requested changes

2023-06-15 07:56 UTC, GauravGusain98 commented on Modules/CodeTrek/Services/CodeTrekService.php
> +        }
Here take the key names from config
```suggestion
        $statusCounts = [
            'active' => 0,
            'inactive' => 0,
            'completed' => 0
        ];
        foreach ($applicantsData as $data) {
            $statusCounts[$data->status] = $data->total;
        }
```

2023-06-25 14:08 UTC, GauravGusain98 approved these changes

2023-06-25 14:08 UTC, merged