updated the installlation guide
ColoredCow/portal pull request #3161
Opened 2023-06-16 11:30 UTC by AkshitRawat1207

Targets #{ISSUE_ID}

### Description
Versions of Node and npm are updated.

### Checklist:

- [x] I have performed a self-review of my own code.

2023-06-16 19:39 UTC, Ayush8923 commented
@AkshitRawat1207 Please put the label `ready-for-review` then assign the PR for review.

2023-06-16 19:39 UTC, Ayush8923 requested changes
Added one comments.

2023-06-16 19:39 UTC, Ayush8923 commented on docs/installation.md
> -
Why did you remove these lines? 
Any reason?

2023-06-25 14:05 UTC, GauravGusain98 approved these changes

2023-06-25 14:05 UTC, GauravGusain98 commented on docs/installation.md
> -
Because we have updated the node version so this is not required

2023-06-25 14:06 UTC, merged