issue/#3027/Books counts are not shown properly
ColoredCow/portal pull request #3172
Opened 2023-06-19 13:08 UTC by Ranjeet-Kalsi

Targets #3027 

### Description
I have found the total numbers of books shown in the Wishlist's menu & Borrowed Books menu.

I have added to lines in    resources\views\knowledgecafe\library\menu.blade.php

  $wishlistCount = auth()->user()->booksInWishlist->count();
 $borrowedCount = auth()->user()->booksBorrower->count();

### Checklist:
First i checked the flow of code then apply changes to menu.blade.php
![books](https://github.com/ColoredCow/portal/assets/121542707/20550daa-2ac2-4444-a0f4-95792a6f0c20)
![wishlist](https://github.com/ColoredCow/portal/assets/121542707/2a9676ed-f171-4e64-b811-f7ae6b17e816)
![borrowed](https://github.com/ColoredCow/portal/assets/121542707/6be8fea8-32fd-427b-a43f-e652c5bb5085)

2023-06-20 05:12 UTC, Ayush8923 requested changes
Added one comment. Please check.

2023-06-20 05:12 UTC, Ayush8923 commented on resources/views/knowledgecafe/library/menu.blade.php
> +         $wishlistCount = auth()->user()->booksInWishlist->count();
Please write this logic in service then return the `$wishlistCount` variable from there and directly use it here.

2023-06-20 06:12 UTC, Ranjeet-Kalsi commented on resources/views/knowledgecafe/library/menu.blade.php
> +         $wishlistCount = auth()->user()->booksInWishlist->count();
ok I will check it

2023-06-21 05:13 UTC, LavishRawat commented
@Ranjeet-Kalsi The ``Books Category``  and  ``A Book A Month``  pages are currently displaying the following error.
Please have a look and let me know if it's the same for you.

<img width="1196" alt="Screenshot 2023-06-21 at 10 37 52 AM" src="https://github.com/ColoredCow/portal/assets/108713935/594d2afc-7a5b-4146-9472-6f31283156c2">

2023-06-21 06:22 UTC, Ayush8923 requested changes
Added one small comment.

2023-06-21 06:22 UTC, Ayush8923 commented on resources/views/knowledgecafe/library/menu.blade.php
> +     $booksBorrowerCount = auth()->user()->booksBorrower->count();
Now, these 2 lines of code are not needed here. Please remove this. And then please test locally once.

2023-06-21 11:03 UTC, Ayush8923 commented
@Ranjeet-Kalsi Suggested changes are not implemented. Could you please check this [comment](https://github.com/ColoredCow/portal/pull/3172#pullrequestreview-1489846697)?
And please test locally once and also please do self-review before assigning the PR to reviewers.

2023-06-21 11:06 UTC, Ranjeet-Kalsi commented
> @Ranjeet-Kalsi Suggested changes are not implemented. Could you please check this [comment](https://github.com/ColoredCow/portal/pull/3172#pullrequestreview-1489846697)? And please test locally once and also please do a self-review before assigning the PR to reviewers.

yes i not implemented the suggested changes I used only in locally.
ok i will implemented it

2023-06-21 11:35 UTC, Ranjeet-Kalsi commented
> @Ranjeet-Kalsi Suggested changes are not implemented. Could you please check this [comment](https://github.com/ColoredCow/portal/pull/3172#pullrequestreview-1489846697)? And please test locally once and also please do a self-review before assigning the PR to reviewers.

Now suggested changes applied and also i follow the these steps 
1. remove count logic from controller file due to another function affects 
2. i implemented code & logic only in blade file

2023-06-21 15:26 UTC, Ayush8923 requested changes
Added one comment.

2023-06-21 15:26 UTC, Ayush8923 commented on resources/views/knowledgecafe/library/menu.blade.php
> +     $booksBorrowedCount = auth()->user()->booksBorrower->count();
@Ranjeet-Kalsi, you don't need to add these books count logic inside the blade file. let's define these 2 books count logic inside the  `index` function of the `BookController` and `index` function of the `BookCategoryController` and then return these 2 variable corresponding to their `index.blade` file. and after that, we can directly use this variable in the blade file. 

Please let me know, if there are any confusion and question.

2023-06-22 06:26 UTC, Ayush8923 requested changes
Added some comments. Please check.

2023-06-22 06:26 UTC, Ayush8923 commented on app/Http/Controllers/KnowledgeCafe/Library/BookCategoryController.php
> +        ->with('booksBorrowedCount', $booksBorrowedCount);
I think we can optimize this code. Something like this.
```
return view('knowledgecafe.library.categories.index', [
    'books' => $books,
    'categories' => $this->formatCategoryData($categories),
    'wishlistedBooksCount' => $wishlistedBooksCount,
    'booksBorrowedCount' => $booksBorrowedCount,
]);
```

2023-06-22 06:26 UTC, Ayush8923 commented on app/Http/Controllers/KnowledgeCafe/Library/BookController.php
> +        ->with('booksBorrowedCount', $booksBorrowedCount);
Same here. Could you please optimize this code?
 Please don't repeat the `with` function again and again. Please take the reference of the previous comment.

2023-06-23 07:51 UTC, Ayush8923 requested changes
Few minor comments. Please check.

2023-06-23 07:51 UTC, Ayush8923 commented on app/Http/Controllers/KnowledgeCafe/Library/BookCategoryController.php
> +        'booksBorrowedCount'=> $booksBorrowedCount]);
Please fix the indentation here.

2023-06-23 07:51 UTC, Ayush8923 commented on app/Http/Controllers/KnowledgeCafe/Library/BookController.php
> +        'booksBorrowedCount'=> $booksBorrowedCount]);
Same here. Please fix the indentation here..

2023-06-23 11:09 UTC, Ayush8923 approved these changes

2023-06-23 11:09 UTC, merged