Automated of review system
ColoredCow/portal pull request #3174
Opened 2023-06-20 10:07 UTC by Akshiteshnaithani

Targets #3167 

### Description
This task aims to automate the review system by implementing scheduled tasks using cron jobs. The current manual process of generating assessment cards for employees will be replaced with an automated system that generates assessment cards at regular intervals(Quarterly).

### Checklist:

- [ ] I have performed a self-review of my own code.

2023-06-20 15:20 UTC, Ayush8923 requested changes
Added some comments. Please check. Also I think, we don't need the `EmployeeController`, so please revert this file.

2023-06-20 15:20 UTC, Ayush8923 commented on app/Console/Kernel.php
> +        SystemReviewQuaterly::class
Please update all places accordingly
```suggestion
        QuarterlyReviewSystemForEmployee::class
```

2023-06-20 15:20 UTC, Ayush8923 commented on Modules/HR/Console/SystemReviewQuaterly.php
> +    protected $name = 'hr:quarterly-review-system';
```suggestion
    protected $name = 'employee:quarterly-review-system-for-employee';
```

2023-06-21 07:08 UTC, Akshiteshnaithani commented
> Added some comments. Please check. Also I think, we don't need the `EmployeeController`, so please revert this file.

CI checks were getting fail due to `EmployeeController`  file.

2023-06-21 07:51 UTC, Ayush8923 commented
As per the offline discussion, please use SRP(Single responsibility principal) principal.

2023-06-23 06:02 UTC, Akshiteshnaithani commented
> As per the offline discussion, please use SRP(Single responsibility principal) principal.

Implemented the SRP principal.

2023-06-23 06:28 UTC, Akshiteshnaithani commented
### New Requirement :
currently we have added a `Review Status` filter in our Working staff page so that we could filter out all the employees whose review is pending or in-progress or completed. Now we need to remove that filter and whenever I will land onto the working staff page, all the employee should show up whose review is pending or in-progress or completed

2023-06-28 05:42 UTC, Bahugunajii approved these changes

2023-06-28 05:42 UTC, merged