Bug/3164/remove the inactive team members and inactive or halted projects from email notification
ColoredCow/portal pull request #3175
Opened 2023-06-20 10:44 UTC by thisajaychauhan

## Targets #3164
 
### Description
The cron job will only send email notifications to the key account manager for active projects and team members. The filtering mechanism will exclude inactive team members and inactive or halted projects from receiving email notifications.

## Expected Time
- [x] Set up the mail trap for email. `1-2 hours`
- [x] Understand the e-mail flow in Laravel. `2-3 hours`
- [x] Understand the bug. `3-4 hours`
- [x] For testing, code review, and documentation. `1-2 hours`

## Actual Time 
- [x] Set up the mail trap for email. `1-2 hours`
- [x] Understand the e-mail flow in Laravel. `3-4 hours`
- [x] Understand the bug. `4-5 hours`
- [x] For testing, code review, and documentation. `1-2 hours`
---
### TOTAL TIME = 13 HOURS
---

## Unit testing
- Understand the email flow and cron job schedule in Laravel [link](https://www.itsolutionstuff.com/post/laravel-send-scheduled-emails-tutorialexample.html)

### Checklist:

- [x] I have performed a self-review of my own code.

2023-06-20 10:52 UTC, GauravGusain98 requested changes

2023-06-20 10:52 UTC, GauravGusain98 commented on Modules/Project/Services/ProjectService.php
>          $zeroEffortProject = ProjectTeamMember::where('daily_expected_effort', 0)->get('project_id');
This will give the all the team members i.e active or inactive both. We only want team members that are active

2023-06-21 06:36 UTC, thisajaychauhan commented on Modules/Project/Services/ProjectService.php
>          $zeroEffortProject = ProjectTeamMember::where('daily_expected_effort', 0)->get('project_id');
but there is no status column in the project_team_member table like in the project table.

2023-06-21 06:40 UTC, thisajaychauhan commented on Modules/Project/Services/ProjectService.php
>          $zeroEffortProject = ProjectTeamMember::where('daily_expected_effort', 0)->get('project_id');
I think the project_team_member who has ended_on column is null they are active,
 and those who have ended_on column with dates are inactive.

2023-06-21 09:46 UTC, GauravGusain98 approved these changes
LGTM

2023-06-21 09:47 UTC, merged