Contract Management Module
ColoredCow/portal pull request #3176
Opened 2023-06-20 11:11 UTC by am-Anmol

Targets #3151

### Description

Expected Bheaviour:
- User:
  - User can add contract and save it as draft.
  - User can edit contract with comments.
  - User can view contract and can send it for review to client and finance team.
  - User can view comments in view contract.

- Client:
  - Client receive mail from user with signed link to view contract.
  - Client can edit contracts fields and can finalize it.
 
- Finance team:
  - After user sent contract for finance review, finance should able to see it in his dashboard.
  - Finance team can review contract and can edit contracts fields and finalize it.

### Checklist:

- [x] I have performed a self-review of my own code.

2023-06-22 10:14 UTC, GauravGusain98 commented
### Testing Feedbacks
1. On clicking edit button we are getting this error
    <img width="1437" alt="image" src="https://github.com/ColoredCow/portal/assets/54376313/a51486a1-592c-4af8-9760-7d68fc61c5e1">
2. When sending contract for finance review,  I am getting this error
     <img width="1440" alt="image" src="https://github.com/ColoredCow/portal/assets/54376313/ad69587a-411d-4837-9328-174997d0e764">
3. When I updated then contract data as a client, then the email (abhishek@coloredcow.in) to which the client updated mail went was different than the email (gaurav.gusain@coloredcow.in) I am logged in as 
    <img width="894" alt="image" src="https://github.com/ColoredCow/portal/assets/54376313/501b1739-0da9-4c8d-a840-c12a3d217053">
4. When I am clicking on contract link its redirecting me to same link. Is this an expected behaviour?
    <img width="692" alt="image" src="https://github.com/ColoredCow/portal/assets/54376313/04f81aee-1476-4018-a31a-f69cc851a182">

2023-06-22 10:50 UTC, am-Anmol commented
> ### Testing Feedbacks
> 1. On clicking edit button we are getting this error
>    <img alt="image" width="1437" src="https://user-images.githubusercontent.com/54376313/247898019-a51486a1-592c-4af8-9760-7d68fc61c5e1.png">
> 2. When sending contract for finance review,  I am getting this error
>    <img alt="image" width="1440" src="https://user-images.githubusercontent.com/54376313/247898630-ad69587a-411d-4837-9328-174997d0e764.png">
> 3. When I updated then contract data as a client, then the email ([abhishek@coloredcow.in](mailto:abhishek@coloredcow.in)) to which the client updated mail went was different than the email ([gaurav.gusain@coloredcow.in](mailto:gaurav.gusain@coloredcow.in)) I am logged in as
>    <img alt="image" width="894" src="https://user-images.githubusercontent.com/54376313/247899274-501b1739-0da9-4c8d-a840-c12a3d217053.png">
> 4. When I am clicking on contract link its redirecting me to same link. Is this an expected behaviour?
>    <img alt="image" width="692" src="https://user-images.githubusercontent.com/54376313/247899542-04f81aee-1476-4018-a31a-f69cc851a182.png">
> 5. The UI of this page is a bit messy. I think we could have used tabs instead of showing pending review and all reviews on one page. We can make this change in later phases.
>    <img alt="image" width="1438" src="https://user-images.githubusercontent.com/54376313/247899932-2b0fe14d-da13-4299-bbe1-22b98dc93224.png">

- I'm doing some fixes and ui changes to another branch that I have created I'll be merging with this branch.

- 1. This change is covered in the new branch. 
  - (On clicking edit button we are getting this error)

- 2. I have added list from user table to avoid this error. 
  - (When sending contract for finance review, I am getting this error)

- 3. I have updated this bug also , now if client update then mail will be triggered to user who created contract and same for finalize case. Since client is updating changes through signed link mail will be triggered through `portal@coloredcow.in` to user who create contract. 
  - (When I updated then contract data as a client, then the email ([abhishek@coloredcow.in](mailto:abhishek@coloredcow.in)) to which the client updated mail went was different than the email ([gaurav.gusain@coloredcow.in](mailto:gaurav.gusain@coloredcow.in)) I am logged in as)

- 4. This contract link is dummy for now it doesn't have any use for now. 
  - (When I am clicking on contract link its redirecting me to same link. Is this an expected behaviour?)

- 5. I have updated that double table for showing review issue in updated branch. 
  - (The UI of this page is a bit messy. I think we could have used tabs instead of showing pending review and all reviews on one page. We can make this change in later phases.)

2023-06-22 12:04 UTC, am-Anmol commented
Hi @GauravGusain98 , Now you can again review this PR as I have made required changes.

Note:
Run these commands before running as I have made some changes:
-  php artisan migrate::rollback --step=6
- php artisan migrate
- php artisan optimize

2023-06-25 13:58 UTC, GauravGusain98 commented
### Testing Feedbacks
1. When creating a new contract I get this error when all the fields are filled
    <img width="1410" alt="image" src="https://github.com/ColoredCow/portal/assets/54376313/55845b57-98fe-41a4-8127-a186689545d1">
2. When I am not filling GST number which is not a required field then I am getting this error. The same is happening when the contract is being updated after sending for review
    <img width="1320" alt="image" src="https://github.com/ColoredCow/portal/assets/54376313/8c239046-79b3-49dd-94e5-f002e52d214d">
3. In database the user_type and status should be in kebab-case instead of a normal text
    <img width="829" alt="image" src="https://github.com/ColoredCow/portal/assets/54376313/4c44c704-e558-4cd4-ae1d-20cc153a9b8a">
4. If a client has made some updates to the contract then should we still show the label as approved? I think we should remove the approved label in such case
<img width="1219" alt="image" src="https://github.com/ColoredCow/portal/assets/54376313/516091f3-415c-4917-a64b-4ad4af2a4a93">

2023-06-25 14:04 UTC, GauravGusain98 commented
@am-Anmol Can you create a new branch and PR for the new changes. Lets try to fix the issue in this PR and merge it. The PR is getting bigger day by day

2023-06-28 13:22 UTC, am-Anmol commented
@GauravGusain98 , I'm considering addressing your testing feedback within this pull request, while creating a new branch for the ongoing module.

1 & 2. I will fix the error related to the GST number.

3. I will use kebab-case for the user_type and status instead of the regular text format.

4. If the client makes updates, it should remain in a pending state until approved. Once approved, it will be labeled as approved.

5. Currently, the workflow allows the user to send the item for client review, and the client can either update or approve it. When the item is shared with the client, a new entry is added to the Reviewer table. However, if you send it for client review again, it will create another entry in the Reviewer table, resulting in two client tags being displayed.
To prevent users from sending an item for review multiple times, a feature needs to be implemented to block the "send for review" button if the user has already sent it for review. I will address this in the next issue. Please disregard it for now, as it is only relevant for the proof of concept (POC).

2023-07-06 06:10 UTC, GauravGusain98 requested changes
Please check the comments

2023-07-06 07:34 UTC, am-Anmol commented on Modules/ProjectContract/Emails/ClientApproveReview.php
> +        return $this->from('portal@coloredcow.com')
I'll update and add email to contract config.

2023-07-06 07:34 UTC, am-Anmol commented on Modules/ProjectContract/Emails/ClientReview.php
> +        return $this->from('portal@coloredcow.com')
I'll update and add email to contract config.

2023-07-06 07:34 UTC, am-Anmol commented on Modules/ProjectContract/Emails/ClientUpdateReview.php
> +        return $this->from('portal@coloredcow.com')
I'll update and add email to contract config.

2023-07-06 07:35 UTC, am-Anmol commented on Modules/ProjectContract/Emails/FinanceReview.php
> +        return $this->from('portal@coloredcow.com')
I'll update and add email to contract config.

2023-07-06 07:35 UTC, am-Anmol commented on Modules/ProjectContract/Entities/ContractMeta.php
> +    ];
I'll update fillable to guarded.

2023-07-06 07:35 UTC, am-Anmol commented on Modules/ProjectContract/Entities/ContractInternalReview.php
> +    ];
I'll update fillable to guarded.

2023-07-06 07:36 UTC, am-Anmol commented on Modules/ProjectContract/Entities/Contract.php
> +    ];
I'll update fillable to guarded.

2023-07-06 07:36 UTC, am-Anmol commented on Modules/ProjectContract/Entities/ContractReview.php
> +    protected $fillable = [
I'll update fillable to guarded.

2023-07-06 07:36 UTC, am-Anmol commented on Modules/ProjectContract/Entities/Reviewer.php
> +    protected $fillable = [
I'll update fillable to guarded.

2023-07-06 07:36 UTC, am-Anmol commented on Modules/ProjectContract/Entities/ContractMetaHistory.php
> +    protected $fillable = [
I'll update fillable to guarded.

2023-07-06 07:38 UTC, am-Anmol commented on Modules/ProjectContract/Entities/ContractMeta.php
> +    ];
I'll update fillable to guarded.

2023-07-06 07:45 UTC, am-Anmol commented on Modules/ProjectContract/Database/Migrations/2023_06_14_124709_create-new-contract-table.php
> +            $table->string('contract_link');
I'll update to text.

2023-07-06 07:45 UTC, am-Anmol commented on Modules/ProjectContract/Database/Migrations/2023_06_14_140438_create-new-contract-meta-table.php
> +            $table->string('value');
I'll update to text

2023-07-06 07:45 UTC, am-Anmol commented on Modules/ProjectContract/Database/Migrations/2023_06_19_182942_create-contract-meta-history-table.php
> +            $table->string('value');
I'll update to text

2023-07-06 07:46 UTC, am-Anmol commented on Modules/ProjectContract/Database/Migrations/2023_06_14_140438_create-new-contract-meta-table.php
> +            $table->string('value', 65535);
I'll update to text

2023-07-06 07:47 UTC, am-Anmol commented on Modules/ProjectContract/Entities/ContractInternalReview.php
> +    ];
I'll update fillable to guarded.

2023-07-06 08:12 UTC, am-Anmol commented on Modules/ProjectContract/Entities/ContractReview.php
> +        if ($this->comment_by === 'Internal') {
In `contract_review` table this `comment_by` is in `Polymorphic relation` with `ContractInternalReview` and `Reviewer` so in database it is not stored in Titlecase it storing like this `Modules\ProjectContract\Entities\ContractInternalReview` for `Internal` and `Modules\ProjectContract\Entities\Reviewer` for `client`, so there is no need to update.

2023-07-06 08:12 UTC, am-Anmol commented on Modules/ProjectContract/Entities/ContractReview.php
> +        } elseif ($this->comment_by === 'Client') {
In contract_review table this comment_by is in Polymorphic relation with ContractInternalReview and Reviewer so in database it is not stored in Titlecase it storing like this Modules\ProjectContract\Entities\ContractInternalReview for Internal and Modules\ProjectContract\Entities\Reviewer for client, so there is no need to update.

2023-07-06 09:34 UTC, am-Anmol commented on Modules/ProjectContract/Http/Controllers/ProjectContractController.php
> +        $this->service->update_internal($ProjectContractMeta);
Changed to camelCase

2023-07-06 09:35 UTC, am-Anmol commented on Modules/ProjectContract/Http/Controllers/ProjectContractController.php
> +        $users = $this->service->get_users();
Changed all function name to camelCase

2023-07-06 09:35 UTC, am-Anmol commented on Modules/ProjectContract/Http/Controllers/ProjectContractController.php
> +        $this->service->store_reveiwer($data);
Changed to camelCase

2023-07-06 09:36 UTC, am-Anmol commented on Modules/ProjectContract/Http/Controllers/ProjectContractController.php
> +        Mail::to($this->service->get_user_email($id))->send(new ClientApproveReview());
Changed to camelCase

2023-07-06 09:36 UTC, am-Anmol commented on Modules/ProjectContract/Http/Controllers/ProjectContractController.php
> +        Mail::to($this->service->get_user_email($request['id']))->send(new ClientUpdateReview());
Changed to camelCase

2023-07-06 09:36 UTC, am-Anmol commented on Modules/ProjectContract/Http/Controllers/ProjectContractController.php
> +    public function sendfinancereview(Request $request)
Changed to camelCase

2023-07-06 09:36 UTC, am-Anmol commented on Modules/ProjectContract/Http/Controllers/ProjectContractController.php
> +        $this->service->store_internal_reveiwer($data);
Changed to camelCase

2023-07-06 09:37 UTC, am-Anmol commented on Modules/ProjectContract/Http/Controllers/ProjectContractController.php
> +    public function clientresponse($id)
Changed to camelCase

2023-07-06 09:37 UTC, am-Anmol commented on Modules/ProjectContract/Http/Controllers/ProjectContractController.php
> +    public function sendreview(Request $request)
Changed to camelCase

2023-07-06 10:42 UTC, am-Anmol commented on Modules/ProjectContract/Resources/views/edit-project-contract.blade.php
> +                            rows="5" required>{{$contractsmeta[9]['value']}}</textarea>
As I'm using `(key, value)` pair to store fields of contract meta in `contract_meta` table that's why I'm iterating through array index.

2023-07-06 10:44 UTC, am-Anmol commented on Modules/ProjectContract/Resources/views/edit-project-contract.blade.php
> +                            rows="5" required>{{$contractsmeta[9]['value']}}</textarea>
![image](https://github.com/ColoredCow/portal/assets/48876126/9c31f6cb-405d-4743-9bf4-7cad16cc65a6)

2023-07-06 12:15 UTC, am-Anmol commented on Modules/ProjectContract/Http/Controllers/ProjectContractController.php
> +        return 'Thank you for finalise';
I have moved all mail part to `ProjectContractMailService`.

2023-07-09 18:22 UTC, GauravGusain98 requested changes

2023-07-09 18:22 UTC, GauravGusain98 commented on Modules/ProjectContract/Services/ProjectContractService.php
> +            ['key' => 'GST Number', 'value' => $gst, 'group' => 'Payment Methodology'],
The keys should be in kebab-case or snake_case.

2023-07-09 18:22 UTC, GauravGusain98 commented on Modules/ProjectContract/Services/ProjectContractService.php
> +            ['key' => 'GST Number', 'value' => $gst],
key name should be in kebab-case or snake_case

2023-07-09 18:22 UTC, GauravGusain98 commented on Modules/ProjectContract/Services/ProjectContractService.php
> +            ['key' => 'GST Number', 'value' => $gst],
same here

2023-07-09 18:22 UTC, GauravGusain98 commented on Modules/ProjectContract/Services/ProjectContractService.php
> +        $Reviewer = new ContractInternalReview;
```suggestion
        $reviewer = new ContractInternalReview;
```

2023-07-09 18:22 UTC, GauravGusain98 commented on app/Http/Kernel.php
> +        'signed' => \Illuminate\Routing\Middleware\ValidateSignature::class,
what is the use of this?

2023-07-09 18:22 UTC, GauravGusain98 commented on Modules/ProjectContract/Services/ProjectContractService.php
> +            $contractData['status'] = 'Updated by CC team';
ideally we don't store normal text format data in database. The status column should have value in kebab-case or snake_case. In order to fetch the label for this status we can use either config or we should create status_label column in DB. Using config is preferred approach

2023-07-09 18:22 UTC, GauravGusain98 commented on Modules/ProjectContract/Services/ProjectContractService.php
> +        $Reviewer = new Reviewer;
```suggestion
        $reviewer = new Reviewer;
```

2023-07-09 18:22 UTC, GauravGusain98 commented on Modules/ProjectContract/Services/ProjectContractService.php
> +        $Contract = Contract::find($id);
```suggestion
        $contract = Contract::find($id);
```

2023-07-09 18:22 UTC, GauravGusain98 commented on Modules/ProjectContract/Services/ProjectContractService.php
> +            $Contract->status = 'Finalise by User';
it should be in kebab-case or snake_case. Use config to get the label using the status

2023-07-09 18:22 UTC, GauravGusain98 commented on Modules/ProjectContract/Services/ProjectContractService.php
> +        $Reviewer = Reviewer::where(['contract_id' => $id])->first();
```suggestion
        $reviewer = Reviewer::where(['contract_id' => $id])->first();
```

2023-07-09 18:22 UTC, GauravGusain98 commented on Modules/ProjectContract/Services/ProjectContractService.php
> +        $Contract = Contract::find($id);
```suggestion
        $contract = Contract::find($id);
```

2023-07-09 18:22 UTC, GauravGusain98 commented on Modules/ProjectContract/Services/ProjectContractMailService.php
> +    }
Instead of using send() function use queue() function. The queue() function will send the mail asynchronously

2023-07-09 18:22 UTC, GauravGusain98 commented on Modules/ProjectContract/Routes/web.php
> +    Route::get('commenthistory/{id}', 'ProjectContractController@commentHistory')->name('projectcontract.commenthistory');
separate the route name and route url words using hypen (-)

2023-07-10 06:11 UTC, am-Anmol commented on Modules/ProjectContract/Services/ProjectContractService.php
> +        $Reviewer = new ContractInternalReview;
Ok

2023-07-10 06:17 UTC, am-Anmol commented on Modules/ProjectContract/Services/ProjectContractService.php
> +            $contractData['status'] = 'Updated by CC team';
Ok I'll use kebab-case and config approach.

2023-07-10 06:18 UTC, am-Anmol commented on Modules/ProjectContract/Services/ProjectContractService.php
> +        $Reviewer = new Reviewer;
ok

2023-07-10 06:21 UTC, am-Anmol commented on Modules/ProjectContract/Services/ProjectContractService.php
> +            $Contract->status = 'Finalise by User';
Ok I'll use kebab-case and config approach.

2023-07-10 06:22 UTC, am-Anmol commented on Modules/ProjectContract/Services/ProjectContractService.php
> +        $Contract = Contract::find($id);
ok

2023-07-10 06:32 UTC, am-Anmol commented on Modules/ProjectContract/Services/ProjectContractService.php
> +        $Reviewer = Reviewer::where(['contract_id' => $id])->first();
ok

2023-07-10 06:32 UTC, am-Anmol commented on Modules/ProjectContract/Services/ProjectContractService.php
> +        $Contract = Contract::find($id);
ok

2023-07-10 06:33 UTC, am-Anmol commented on Modules/ProjectContract/Services/ProjectContractMailService.php
> +    }
Ok, I'll update with queue()

2023-07-10 06:46 UTC, am-Anmol commented on app/Http/Kernel.php
> +        'signed' => \Illuminate\Routing\Middleware\ValidateSignature::class,
`ValidateSignature` middleware is used to verify that an incoming request has a valid signature.
This is required for `validate signature link` that we send to `client` for `contract review`.

2023-07-21 11:33 UTC, am-Anmol commented on Modules/ProjectContract/Services/ProjectContractService.php
> +            ['key' => 'GST Number', 'value' => $gst, 'group' => 'Payment Methodology'],
Ok, I'll use kebab-case for keys

2023-07-21 11:34 UTC, am-Anmol commented on Modules/ProjectContract/Services/ProjectContractService.php
> +            ['key' => 'GST Number', 'value' => $gst],
Ok, I'll use kebab-case for keys

2023-07-21 11:34 UTC, am-Anmol commented on Modules/ProjectContract/Services/ProjectContractService.php
> +            ['key' => 'GST Number', 'value' => $gst],
Ok, I'll use kebab-case for keys

2023-07-21 11:45 UTC, am-Anmol commented on Modules/ProjectContract/Routes/web.php
> +    Route::get('commenthistory/{id}', 'ProjectContractController@commentHistory')->name('projectcontract.commenthistory');
ok

2023-07-21 13:01 UTC, LavishRawat commented
@am-Anmol 
**Testing Feedback**
1) The FTE on the home page is Showing undefined.
<img width="500" alt="image" src="https://github.com/ColoredCow/portal/assets/108713935/90103aaf-1db7-4dc1-b169-fde2f4c95a17">

2023-08-01 07:51 UTC, Abhinegi2 approved these changes

2023-08-03 11:02 UTC, merged