Slow loading of HR recruitment page on the Portal
ColoredCow/portal pull request #3180
Opened 2023-06-21 10:41 UTC by Harshvardhan80

Targets #3113 

### Description
When I used to open the HR recruitment page, it would take more than 10 seconds to load. I would like to improve its performance.

### Checklist:

- [ ] I have performed a self-review of my own code.

2023-06-21 14:33 UTC, LavishRawat requested changes

2023-06-21 14:33 UTC, LavishRawat commented on Modules/HR/Http/Controllers/Recruitment/ApplicationController.php
> +        $hr_job_id = request()->has('hr_job_id') ? '&hr_job_id=' . request('hr_job_id') : '';
@Harshvardhan80 can we fix the naming convention here? Use camelCase.

2023-06-21 14:33 UTC, LavishRawat commented on Modules/HR/Http/Controllers/Recruitment/ApplicationController.php
> +        $graduation_year = request()->has('end-year') ? '&end-year=' . request('end-year') : '';
@Harshvardhan80 same here. Fix the naming convention in all places.

2023-06-22 07:05 UTC, Harshvardhan80 commented on Modules/HR/Http/Controllers/Recruitment/ApplicationController.php
> +        $graduation_year = request()->has('end-year') ? '&end-year=' . request('end-year') : '';
yes, sure

2023-06-22 07:05 UTC, Harshvardhan80 commented on Modules/HR/Http/Controllers/Recruitment/ApplicationController.php
> +        $hr_job_id = request()->has('hr_job_id') ? '&hr_job_id=' . request('hr_job_id') : '';
> yes, sure

2023-06-23 11:16 UTC, Ayush8923 approved these changes
Looks good..

2023-06-23 11:16 UTC, LavishRawat approved these changes

2023-06-23 11:16 UTC, merged