code trek applicant seeder created
ColoredCow/portal pull request #3207
Opened 2023-06-26 10:17 UTC by AJAYSINGHBISHT12

Targets #{3016}
made the code trek seeder and used the faker 

### Description
I made the code trek applicant seeder and uses faker for dummy data

### Checklist:

- [ ] I have performed a self-review of my own code.

2023-06-26 10:50 UTC, AJAYSINGHBISHT12 commented
![Screenshot 2023-06-26 161900](https://github.com/ColoredCow/portal/assets/123948333/d227e1ef-51cc-4558-a6ce-1fd059c8fe15)

2023-06-26 11:29 UTC, GauravGusain98 requested changes

2023-06-26 11:29 UTC, GauravGusain98 commented on database/Seeders/CodeTrekApplicantsTableSeeder.php
> +    }
When we create an entry for an applicant in codetrek then 2 tables gets populated `codetrek_applicants` and `codetrek_applicants_round_details`

Also instead of doing it like this you need to use factory in laravel. Read about how seeders work in laravel

2023-06-26 11:29 UTC, GauravGusain98 commented on database/Seeders/DatabaseSeeder.php
> +        $this->call([CodeTrekApplicantsTableSeeder::class]);
You don't need to include it here. The Codetrek seeder should be inside Codetrek module seeder folder

2023-06-26 11:32 UTC, GauravGusain98 commented
@AJAYSINGHBISHT12 Please correct the name of the PR in this format
`<#IssueId> <Title>`

2023-07-06 07:02 UTC, AJAYSINGHBISHT12 commented
![codetrekapplocantrounddetails](https://github.com/ColoredCow/portal/assets/123948333/05ce5234-f094-401a-83ce-d6af5c93bf32)
![codetrekapplicant](https://github.com/ColoredCow/portal/assets/123948333/5431468c-957e-4226-afd3-b56712f84ee4)

2023-07-08 08:31 UTC, Ayush8923 commented
@AJAYSINGHBISHT12 As far as I can see, there are only 2 file changes which are not needed. Can you please take a look once?

2023-07-10 05:26 UTC, GauravGusain98 requested changes
Please fix the merge conflicts and also make the suggested changes

2023-07-10 05:26 UTC, GauravGusain98 commented on composer.lock
We don't need any changes in this file

2023-07-10 05:26 UTC, GauravGusain98 commented on Modules/CodeTrek/Database/Seeders/CodeTrekApplicantRoundDetailsTableSeeder.php
> +// use Modules\CodeTrek\Database\Factories\CodeTrekApplicantRoundDetailsFactory;
remove the commented lines. Its not a good practice to leave commented code.

2023-07-10 05:26 UTC, GauravGusain98 commented on Modules/CodeTrek/Database/Seeders/CodeTrekApplicantsTableSeeder.php
> +// use Modules\CodeTrek\Database\Factories\CodeTrekApplicantFactory;
remove the commented lines

2023-07-10 05:26 UTC, GauravGusain98 commented on Modules/CodeTrek/Database/Seeders/CodeTrekDatabaseSeeder.php
> +        $this->call(CodeTrekApplicantsTableSeeder::class);
We dont need to call this seeder as the applicant will automatically create when we call the round details seeder

2023-07-10 07:12 UTC, GauravGusain98 commented
@AJAYSINGHBISHT12 I see that you have create a new PR for this issue. Please close this PR if it is not needed

2023-07-10 18:18 UTC, closed without merging