Change Feedback to Mentor Assign
ColoredCow/portal pull request #3224
Opened 2023-06-29 07:22 UTC by ImRishabhRawat

Targets #3222 

### Description

### Checklist:

- [ ] I have performed a self-review of my own code.

2023-06-30 13:35 UTC, LavishRawat requested changes

2023-06-30 13:35 UTC, LavishRawat commented on Modules/CodeTrek/Http/Controllers/CodeTrekController.php
> +        $users = User::all();
@ImRishabhRawat Instead of using  `$users`, let's use a more meaningful variable name.

2023-06-30 13:35 UTC, LavishRawat commented on Modules/CodeTrek/Http/Controllers/CodeTrekController.php
> +            'users' => $users,
@ImRishabhRawat Change here also.

2023-06-30 13:35 UTC, LavishRawat commented on Modules/CodeTrek/Resources/views/edit.blade.php
> +                                @foreach($users as $user)
@ImRishabhRawat Change at all the places.

2023-06-30 13:35 UTC, LavishRawat commented on Modules/CodeTrek/Resources/views/modals/add-applicant-modal.blade.php
> +                                            <option value="{{ $user->id }}">{{$user->name}}</option>
```suggestion
                                            <option value="{{ $user->id }}">{{ $user->name }}</option>
```

2023-07-02 05:58 UTC, GauravGusain98 requested changes
Minor fix, please check the comment

2023-07-02 05:58 UTC, GauravGusain98 commented on Modules/CodeTrek/Entities/CodeTrekApplicant.php
> +    public function user()
Lets name this function `mentor()` as it make more sense

2023-07-03 07:49 UTC, LavishRawat commented
@ImRishabhRawat there are some Changes requested in your PR. Please have a look.

2023-07-04 05:12 UTC, LavishRawat approved these changes

2023-07-04 06:37 UTC, GauravGusain98 approved these changes
LGTM

2023-07-04 06:37 UTC, merged