Scheduler for Need Follow Up candidates #1954
ColoredCow/portal pull request #3225
Opened 2023-06-29 08:30 UTC by Ranjeet-Kalsi

Targets #1954 
Create a scheduler, that will send an email to the address defined in config
This scheduler should run at 7:00 pm every day.

### Description
1. Create a command in hr console .
2. create email file in hr module 
3. configure config file in hr module
4. create a blade file 
5. configuration in kernel.php
6. run scheduler command.

- [x] I have self-review on that task with the help of Mailtrap .

2023-06-29 10:40 UTC, Ranjeet-Kalsi commented
I faced problem in 
Coding Standards / Larastan 
Integration testing

suggestion is composer install but doesn't work.

2023-06-29 19:25 UTC, Ayush8923 requested changes
Left some minor comments, yet to review this PR.

2023-06-29 19:25 UTC, Ayush8923 commented on Modules/HR/Config/config.php
> +        'primary' => env('HR_NEED_FOLLOW_UP_REMINDER_EMAIL', 'ayush.uniyal@coloredcow.in'),
Here we need to change this email, I will let you know, once confirmed.
```suggestion
        'primary' => env('HR_NEED_FOLLOW_UP_REMINDER_EMAIL', 'ayush.uniyal@coloredcow.in'),
```

2023-06-29 19:25 UTC, Ayush8923 commented on Modules/HR/Console/Recruitment/SendFollowUpEmail.php
> +    protected $description = 'After more than 2 followup mail send.';
```suggestion
    protected $description = 'Sending a Follow-Up Email to HR';
```

2023-06-29 19:25 UTC, Ayush8923 commented on Modules/HR/Console/Recruitment/SendFollowUpEmail.php
> +        $this->info('Follow-up email sent successfully!');
I don't think, we need this. Please remove this.

2023-06-30 04:00 UTC, Ranjeet-Kalsi commented
> @Ranjeet-Kalsi Can you please fix the CI checks and then assign the PR for reviewers?

@Ayush8923 I know,  but I faced more difficulty to remove checks.

2023-06-30 04:02 UTC, Ranjeet-Kalsi commented on Modules/HR/Config/config.php
> +        'primary' => env('HR_NEED_FOLLOW_UP_REMINDER_EMAIL', 'ayush.uniyal@coloredcow.in'),
> Here we need to change this email, I will let you know, once confirmed.

@Ayush8923 ok

2023-06-30 04:03 UTC, Ranjeet-Kalsi commented on Modules/HR/Console/Recruitment/SendFollowUpEmail.php
> +        $this->info('Follow-up email sent successfully!');
> I don't think, we need this. Please remove this.

ok i will remove it now

2023-07-04 06:38 UTC, Ayush8923 requested changes
Added some comments. Please check.

2023-07-04 06:38 UTC, Ayush8923 commented on app/Console/Kernel.php
> +use Modules\HR\Console\Recruitment\SendFollowUpEmailsDaily;
```suggestion
use Modules\HR\Console\Recruitment\SendFollowUpEmailToHr;
```

2023-07-04 06:38 UTC, Ayush8923 commented on Modules/HR/Console/Recruitment/SendFollowUpEmailsDaily.php
> +class SendFollowUpEmailsDaily extends Command
Change the class name accordingly.

2023-07-04 06:38 UTC, Ayush8923 commented on Modules/HR/Console/Recruitment/SendFollowUpEmailsDaily.php
> +            Mail::to(config('hr.hr-followup-email-daily'))->queue(new FollowUpEmail($applications, $user));
```suggestion
            Mail::to(config('hr.hr-followup-email-daily'))->queue(new FollowUpEMailToHr($applications, $user));
```

2023-07-04 06:39 UTC, Ayush8923 requested changes

2023-07-04 06:39 UTC, Ayush8923 commented on Modules/HR/Resources/views/application/follow_up.blade.php
> +    <p>Hello Pankaj Kandpal,</p>
We need to pick the user name dynamic. Something like this.
```suggestion
    <p>Hello {{$user->name}},</p>
```

2023-07-04 10:01 UTC, Ayush8923 requested changes
Added some comments.

2023-07-04 10:01 UTC, Ayush8923 commented on Modules/HR/Emails/FollowUpEMailToHr.php
> +            ->view('hr::application.follow_up');
Please use the `Kebab` case for the blade file name.

2023-07-04 17:54 UTC, Ayush8923 requested changes
Added some more comments. Please check.

2023-07-04 17:54 UTC, Ayush8923 commented on app/Console/Kernel.php
> +        $schedule->command('hr:send-follow-up-mail-daily')->dailyAt('19:00');
```suggestion
        $schedule->command('hr:send-follow-up-mail-to-hr')->dailyAt('19:00');
```

2023-07-04 17:54 UTC, Ayush8923 commented on Modules/HR/Console/Recruitment/SendFollowUpEmailToHr.php
> +        return 0;
I don't think, we need this return startment. Please remove. 

And why you have removed this below the previous code?
```
Mail::to(config('hr.hr-followup-email-daily'))->queue(new FollowUpEMailToHr($applications, $user));
```
Can you please let me know, how to pass the data from this file to the `FollowUpEMailToHr` file? Because as far as I can see there is no such code written here so that data can be passed from this file to the `FollowUpEMailToHr` file.

2023-07-05 09:35 UTC, Ayush8923 commented
@Ranjeet-Kalsi Please resolve the merge conflicts.

2023-07-05 09:38 UTC, Ranjeet-Kalsi commented
> @Ranjeet-Kalsi Please resolve the merge conflicts.

ok @Ayush8923 I will check it

2023-07-05 11:23 UTC, Ayush8923 requested changes
@Ranjeet-Kalsi Please let me know, did you test it locally. And also please check this comment https://github.com/ColoredCow/portal/pull/3225#discussion_r1251798441.

2023-07-05 14:05 UTC, Ranjeet-Kalsi commented
> @Ranjeet-Kalsi Please let me know, did you test it locally. And also please check this comment [#3225 (comment)](https://github.com/ColoredCow/portal/pull/3225#discussion_r1251798441).

@Ayush8923 I used "return 0" because Larastan threw an error which screenshot i have attached earlier. 
I'm currently testing the mail locally, but no errors are being found during command 
php artisan hr:send-follow-up-mail-to-hr
although the mail is not being sent. 
I also tried using a dummy mail in another Laravel project, and it worked fine.

Can you suggest what type of settings I need?

2023-07-05 16:00 UTC, Ayush8923 requested changes
Added one comment.

2023-12-08 07:39 UTC, closed without merging