#3197 Add a dropdown menu for the status in the CodeTrek page
ColoredCow/portal pull request #3230
Opened 2023-06-30 09:56 UTC by jaskaransingh304

## Targets #2823 
 
### Description
A dropdown menu has been added to the status column, allowing users to select an option from a list of available choices. When a user selects a particular option, the list of applicants is automatically filtered based on that selection.

## Approach
I reviewed the HR recruitment page and noticed that it had a dropdown menu for filtering. Then, I examined the controller, view page, and route to understand how the filter functionality was implemented. I replicated the same approach on the Codetrek applicant page's index. I created a route that would be requested, and I defined the corresponding functionality on the service page , which was returned to index by controller.

## Expected Time
- [x] Code review and documentation: 0.5-1 hour.
- [x] Understanding the functionality: 1-2 hours.
- [x] Making the required changes: 2-3 hours.
- [x] Testing, code, review, and documentation: 1 hour.

### TOTAL TIME = 6-8 Hours.

## Actual Time 
- [x] Code review and documentation: 0.5-1 hour.
- [x] Understanding the functionality: 5 hours.
Reading about routes and controllers: 5 hours.
Making the required changes: 2-3 hours.
Testing, code, review, and documentation: 1 hour.

### Total Time = 15 Hours.
---

### Checklist:

- [x] I have performed a self-review of my own code.

2023-06-30 10:06 UTC, jaskaransingh304 commented
Attaching screenshot for reference, Before- ![image](https://github.com/ColoredCow/portal/assets/109968722/aaaa7481-9f31-4819-a223-c817cc80695b)
After applying filter-![image](https://github.com/ColoredCow/portal/assets/109968722/fce9f569-9aac-49d5-b44a-bed32ce6e2da)

2023-07-01 14:23 UTC, GauravGusain98 requested changes

2023-07-01 14:23 UTC, GauravGusain98 commented on Modules/CodeTrek/Resources/views/index.blade.php
> +                                            {{ config('codetrek.rounds.' . $applicant->round_name . '.label') }}
I think you have not taken latest pull from master branch or didn't run the migration, as the column name in database is `latest_round_name`  and not `round_name `

2023-07-01 14:23 UTC, GauravGusain98 commented on Modules/CodeTrek/Services/CodeTrekService.php
> +            $query->where('round_name', $roundSlug);
correct here as well

2023-07-01 15:34 UTC, jaskaransingh304 commented on Modules/CodeTrek/Resources/views/index.blade.php
> +                                            {{ config('codetrek.rounds.' . $applicant->round_name . '.label') }}
Sure i will do that.

2023-07-04 05:24 UTC, GauravGusain98 requested changes

2023-07-04 05:24 UTC, GauravGusain98 commented on Modules/CodeTrek/Routes/web.php
> +    Route::get('/filter-by-round/{roundSlug}', 'CodeTrekController@index')->name('codetrek.filterByRound');
Why we have a new URL for filter? 

Opening same page using 2 different URL is not a good practice. Also, this way the current filters and search will not work along with filters. 

Please use the codetrek.index route only

2023-07-04 06:53 UTC, jaskaransingh304 commented on Modules/CodeTrek/Routes/web.php
> +    Route::get('/filter-by-round/{roundSlug}', 'CodeTrekController@index')->name('codetrek.filterByRound');
@GauravGusain98 , I have implemented the changes. Please check.

2023-07-04 07:39 UTC, LavishRawat commented
@jaskaransingh304  
**Testing Feedback**

1)The filters are not working when we apply them.

2023-07-04 07:48 UTC, jaskaransingh304 commented
@LavishRawat , which filter is not working? Can you let me know?

2023-07-04 07:53 UTC, LavishRawat commented
> @LavishRawat , which filter is not working? Can you let me know?

The dropDown Filter to filter applicant according to round is not working.


<img width="353" alt="Screenshot 2023-07-04 at 1 21 35 PM" src="https://github.com/ColoredCow/portal/assets/108713935/3e99d37b-1352-4430-9f99-dd2af0416d0a">

2023-07-04 07:53 UTC, jaskaransingh304 commented
I have tested , it is working .

2023-07-04 08:06 UTC, LavishRawat commented
> I have tested , it is working . Please run migration as a column name has been changed from round_name to latest_round_name

@jaskaransingh304 I ran the migrations still the dropdown filter is not working.

2023-07-04 08:08 UTC, jaskaransingh304 commented
@LavishRawat , I'll check again

2023-07-04 08:42 UTC, jaskaransingh304 commented
@LavishRawat , I have checked in another system, and it is working fine.

2023-07-04 09:49 UTC, LavishRawat commented
> @LavishRawat , I have checked in another system, and it is working fine.

Yes, the filters are working fine for Active Tab but when attempting to apply the filter for the "Inactive" tab, it automatically switches back to the "Active" tab. The same issue occurs when trying to apply the filter for the "Completed" tab.

2023-07-05 12:10 UTC, GauravGusain98 commented
@jaskaransingh304 Please fix the merge conflicts and check if all the feedbacks are implemented or not

2023-07-06 05:23 UTC, jaskaransingh304 commented
@GauravGusain98 , merge conflicts have been fixed , currently it is filtering for active status only as the index page is requested with active status..so I'm trying to fix it

2023-07-06 17:51 UTC, GauravGusain98 commented
> @GauravGusain98 , merge conflicts have been fixed , currently it is filtering for active status only as the index page is requested with active status..so I'm trying to fix it

@jaskaransingh304 
1. I am still seeing the merge conflict 
2. Also the filter by level filter is getting removed if I am using other filters
3. The approach of creating a new route is not correct you should use the approach that is used for center filter

2023-07-12 08:42 UTC, jaskaransingh304 commented
> > @GauravGusain98 , merge conflicts have been fixed , currently it is filtering for active status only as the index page is requested with active status..so I'm trying to fix it
> 
> @jaskaransingh304
> 
> 1. I am still seeing the merge conflict
> 2. Also the filter by level filter is getting removed if I am using other filters
> 3. The approach of creating a new route is not correct you should use the approach that is used for center filter

1. Merge conflicts fixed.

2023-07-12 09:47 UTC, GauravGusain98 requested changes

2023-07-12 09:47 UTC, GauravGusain98 commented on Modules/CodeTrek/Services/CodeTrekService.php
> +        }
This should also be added below for calculating count query for each status

2023-07-12 10:28 UTC, jaskaransingh304 commented on Modules/CodeTrek/Services/CodeTrekService.php
> +        }
> This should also be added below for calculating the count query for each status

@GauravGusain98 I have added done, the only issue is the filter works when it is selected after selecting other filters. If I select round as level 1 and status inactive, then the roundSlug is not getting passed to the status parameter, I have tried doing that but as we don't have a fixed value for $roundSlug, it keeps changing. So can you please help with the other procedure? In case of any question, we can connect and discuss.

2023-07-13 08:10 UTC, GauravGusain98 commented on Modules/CodeTrek/Services/CodeTrekService.php
> +        }
The filter is getting removed when I am using other filters

2023-07-13 08:10 UTC, GauravGusain98 commented on Modules/CodeTrek/Services/CodeTrekService.php
> +        }
maybe you are not passing the value of level filter when the other filters form is getting submitted

2023-07-13 08:16 UTC, jaskaransingh304 commented on Modules/CodeTrek/Services/CodeTrekService.php
> +        }
@GauravGusain98 , it is not working only when selected before other filter.. If round filter is selected after it..It is working...So in case to make it work for other filter , for example status - I would have to pass the value in status filter for $roundSlug...but the value of $roundSlug may change when it is selected...so that's what i was asking about...in this case i need to pass value in every filter for roundSlug

2023-07-13 08:20 UTC, GauravGusain98 commented on Modules/CodeTrek/Services/CodeTrekService.php
> +        }
yes you need to pass the value of roundSlug in every filter

2023-07-14 07:58 UTC, jaskaransingh304 commented on Modules/CodeTrek/Services/CodeTrekService.php
> +        }
> yes you need to pass the value of roundSlug in every filter

@GauravGusain98 , It is passed to every filter.

2023-07-18 10:25 UTC, GauravGusain98 approved these changes
LGTM

2023-07-18 10:25 UTC, merged