Added a bar chart on codetrek page
ColoredCow/portal pull request #3231
Opened 2023-07-02 09:58 UTC by Himanshunegi0332

Targets #{ISSUE_ID}

### Description

### Checklist:

- [ ] I have performed a self-review of my own code.

2023-07-04 05:18 UTC, GauravGusain98 requested changes

2023-07-04 05:18 UTC, GauravGusain98 commented on Modules/CodeTrek/Http/Controllers/CodeTrekController.php
> +        ->whereDate('created_at', '<=', $application_end_date)
This should be compared based in `start_date` column instead of `created_on` column

2023-07-04 05:18 UTC, GauravGusain98 commented on Modules/CodeTrek/Resources/views/index.blade.php
> +                @endif
Can you also show total count of application between that time period here
<img width="684" alt="image" src="https://github.com/ColoredCow/portal/assets/54376313/2d2f124e-856a-4a3d-832a-35727a1f7867">

2023-07-04 05:18 UTC, GauravGusain98 commented on Modules/CodeTrek/Http/Controllers/CodeTrekController.php
> +        $counts = $applicantChartData->pluck('count')->toArray();
using this array also calculate total count

2023-07-04 05:18 UTC, GauravGusain98 commented on Modules/CodeTrek/Resources/views/index.blade.php
> +            @elseif (request()->tab == 'reports')
When I am changing tabs, the tabs are being removed from UI
<img width="1410" alt="image" src="https://github.com/ColoredCow/portal/assets/54376313/cb4d04a8-caa0-414a-91cd-22042efa20f2">
<img width="1384" alt="image" src="https://github.com/ColoredCow/portal/assets/54376313/8ec2e0eb-9364-4e6e-89c7-37a1268c1e92">

2023-07-04 05:18 UTC, GauravGusain98 commented on resources/js/app.js
> +function CodeTrekApplicationsReport() {
Don't you think this should be inside Codetrek module?

2023-07-09 18:04 UTC, GauravGusain98 commented on Modules/CodeTrek/Http/Controllers/CodeTrekController.php
> +        ->count();
```suggestion
            ->whereDate('start_date', '>=', $start_date)
            ->whereDate('start_date', '<=', $end_date)
            ->count();
```

2023-07-09 18:04 UTC, GauravGusain98 commented on Modules/CodeTrek/Http/Controllers/CodeTrekController.php
> +        $start_date = Carbon::parse($request->application_start_date) ?? today()->subYears(4);
```suggestion
        $start_date = Carbon::parse($request->application_start_date) ?? today()->subYears(2);
```

2023-07-09 18:05 UTC, GauravGusain98 commented on Modules/CodeTrek/Resources/assets/js/app.js
> +				// borderWidth: 10,
```suggestion
```

2023-07-09 18:08 UTC, GauravGusain98 requested changes

2023-07-09 18:08 UTC, GauravGusain98 commented on Modules/CodeTrek/Http/Controllers/CodeTrekController.php
> +    public function applicantBarGraphData(Request $request)
The controller and service related to reports should be inside the Report Module. We should use report module for all the processing of data related to any type of reports.

2023-07-11 07:39 UTC, LavishRawat commented on Modules/CodeTrek/Services/CodeTrekService.php
> -        $feedback->posted_on = today();
@Himanshunegi0332 why have you removed this line?

2023-07-11 08:04 UTC, Himanshunegi0332 commented on Modules/CodeTrek/Services/CodeTrekService.php
> -        $feedback->posted_on = today();
Sorry, on resolving merge conflicts I have removed it by mistake.

2023-07-11 08:51 UTC, GauravGusain98 requested changes

2023-07-11 12:21 UTC, GauravGusain98 requested changes

2023-07-11 12:21 UTC, GauravGusain98 commented on Modules/Report/Http/Controllers/ReportController.php
> +    }
For this function a new controller maybe CodeTrekController should be created inside report Module as it is related to codetrek.  The report controller is used for the report page that we have in finance module, so lets not use this controller.

2023-07-11 14:13 UTC, LavishRawat requested changes

2023-07-11 14:13 UTC, LavishRawat commented on Modules/CodeTrek/Services/CodeTrekService.php
> +            ->get();
@Himanshunegi0332 are these your changes? I think these changes are related to `center Filter ` functionality.

2023-07-11 14:30 UTC, LavishRawat submitted a review, later dismissed

2023-07-11 14:30 UTC, LavishRawat commented on Modules/CodeTrek/Services/CodeTrekService.php
> +            ->get();
@Himanshunegi0332 are these your changes? if not please remove them as I think these changes are related to the `Centre Filter` functionality.

2023-07-11 14:30 UTC, LavishRawat commented on Modules/CodeTrek/Resources/views/index.blade.php
> +                <a class="nav-link active" >Total Applications</a>
```suggestion
                <a class="nav-link active">Total Applications</a>
```

2023-07-11 14:30 UTC, LavishRawat commented on Modules/CodeTrek/Resources/views/index.blade.php
> +                        <form align="right" action="{{ route('codetrek.index', ['tab' => 'reports']) }}" method="get">
```suggestion
                        <form align="right" action="{{ route('codetrek.index', ['tab' => 'reports']) }}" method="GET">
```

2023-07-11 14:30 UTC, LavishRawat commented on Modules/CodeTrek/Resources/views/index.blade.php
> +        <div>
@Himanshunegi0332 Please fix the indentation.

2023-07-11 14:33 UTC, LavishRawat commented on Modules/CodeTrek/Http/Controllers/CodeTrekController.php
> +        $start_date = Carbon::parse($request->application_start_date) ?? today()->subYears();
```suggestion
        $start_date = Carbon::parse($request->application_start_date) ?? today()->subYear();
```

2023-07-11 14:36 UTC, LavishRawat commented on Modules/Report/Http/Controllers/ReportController.php
> +    }
Remove these

2023-07-11 14:36 UTC, Himanshunegi0332 commented on Modules/CodeTrek/Services/CodeTrekService.php
> +            ->get();
no these are not my changes. Removed

2023-07-11 14:48 UTC, Himanshunegi0332 commented on Modules/CodeTrek/Resources/views/index.blade.php
> +        <div>
ok

2023-07-11 14:50 UTC, Himanshunegi0332 commented on Modules/Report/Http/Controllers/ReportController.php
> +    }
ok

2023-07-14 06:10 UTC, GauravGusain98 requested changes

2023-07-14 06:10 UTC, GauravGusain98 commented on Modules/Report/Routes/web.php
> +    Route::get('get-report-data', 'CodeTrekController@getApplicantData')->name('reports.codetrek.get-report-data');
please provide a meaningful name

2023-07-14 06:10 UTC, GauravGusain98 commented on Modules/Report/Services/Finance/ReportDataService.php
> +    public function getDataForCodeTrekApplications($type, $filters, $request)
please provide specific naming for functions

2023-07-18 10:13 UTC, GauravGusain98 approved these changes

2023-07-18 10:13 UTC, GauravGusain98 commented on Modules/CodeTrek/Http/Controllers/CodeTrekController.php
> +        $counts = CodeTrekApplicant::select(\DB::Raw('DATE(start_date) as date, COUNT(*) as count'))
```suggestion
        $reportApplicationCounts = CodeTrekApplicant::select(\DB::Raw('DATE(start_date) as date, COUNT(*) as count'))
```

2023-07-18 10:13 UTC, GauravGusain98 commented on Modules/CodeTrek/Http/Controllers/CodeTrekController.php
> +            'counts' => $counts,
```suggestion
            'reportApplicationCounts' => $reportApplicationCounts,
```

2023-07-18 10:13 UTC, GauravGusain98 commented on Modules/CodeTrek/Resources/views/index.blade.php
> +                    <span class="chart-heading">Applications Received: {{$counts}}</span>
```suggestion
                    <span class="chart-heading">Applications Received: {{$reportApplicationCounts}}</span>
```

2023-07-18 10:19 UTC, GauravGusain98 approved these changes
Left some suggestioon

2023-07-18 10:19 UTC, GauravGusain98 commented on Modules/CodeTrek/Http/Controllers/CodeTrekController.php
> +            ->count();
Feedbacks
1. naming convention of variable is incorrect
2. When no date filter is applied then the count is coming as 0. 

```suggestion
        $startDate = Carbon::parse($request->input('application_start_date', today()->subYear()));
        $endDate = Carbon::parse($request->input('application_end_date', today()));
        $reportApplicationCounts = CodeTrekApplicant::whereDate('start_date', '>=', $startDate)
            ->whereDate('start_date', '<=', $endDate)
            ->count();
```

2023-07-18 10:21 UTC, merged