Correct the day count in expected hours column in effort details in projects#3212
ColoredCow/portal pull request #3244
Opened 2023-07-05 10:13 UTC by MohitGururani

Targets #{3212}

### Description
-In this task, I successfully resolved an issue related to the calculation of the day's count in the "Expected Hour" column heading. Previously, the calculation was inaccurate as it added a whole day until 10 PM. To fix this, I made the necessary changes to accurately reflect the time period from the start date to the end of the day at 10 PM for each day.
Furthermore, I ensured that the current day is not included in the day's count calculation. Additionally, I extended this calculation to the "Expected Hours Till Today" column heading, providing consistent and accurate information throughout the application.
-In the second task i change the color of 'red arrow icon'.

### Checklist:
 [ ] I have performed a self-review of my own code.

2023-07-06 08:26 UTC, MohitGururani commented
**Expected Time**
1.Correcting the expected hour column heading.**2-4 hours**
2.Changing the color of 'red arrow icon'.**2-4 hours**
**Total Expected Time: 8 hours**

**Total Time Taken : 9 hours**

2023-07-06 18:09 UTC, GauravGusain98 requested changes

2023-07-06 18:09 UTC, GauravGusain98 commented on resources/js/components/Dashboard/UserDashboardProjects.vue
> +			</div>
Please correct the identation. The previous indentation was correct, in you current changes it got increased

2023-07-06 18:09 UTC, GauravGusain98 commented on Modules/EffortTracking/Services/EffortTrackingService.php
> -        $totalWorkingDays = count($this->getworkingDays($startDate, $endDate));
Why you removed it? It's being used below in the return statement. Please test your code properly

2023-07-06 18:09 UTC, GauravGusain98 commented on Modules/EffortTracking/Services/EffortTrackingService.php
>          $daysTillToday = count($project->getWorkingDaysList($project->client->month_start_date, $currentDate));
Lets use the same function that we used above `$this->getWorkingDays`

2023-07-07 08:15 UTC, GauravGusain98 commented on Modules/EffortTracking/Services/EffortTrackingService.php
> -        $totalWorkingDays = count($this->getworkingDays($startDate, $endDate));
OK got it was duplicate.

2023-07-10 04:50 UTC, GauravGusain98 approved these changes
LGTM

2023-07-10 04:50 UTC, merged