Days count of applicants with status completed are calculate between …
ColoredCow/portal pull request #3246
Opened 2023-07-05 11:36 UTC by AkshitRawat1207

**Targets #3211** _____________________________________________________________________________________________________________________________________
**Description**

The count of days in CodeTrek for applicants who have already completed their CodeTrek is calculated by adding new column (internship_start_date) to code_trek_applicants table which will help us to calculate the count of days in codetrek for applicants who have completed their CodeTrek by finding difference between start_date and internship_start_date column of code_trek_applicants table. _______________________________________________________________________________________________________________________________________
**Expected Time**

- [x] Create a new column internship_start_date in code_trek_applicants Table. `1-2 hours`
- [x] Finding the existing code for Codetrek Days in Codetrek Column. `1-2 hours`
- [x] Understanding the bug. ` 1-2 hours`
- [x] For testing , code review and documentation. ` 2-3 hours`
_______________________________________________________________________________________________________________________________________
**Actual Time**

- [x] Create a new column internship_start_date in code_trek_applicants Table. `2-3 hours`
- [x] Finding the existing code for Codetrek Days in Codetrek Column. `1-2 hours`
- [x] Understanding the bug. ` 1-2 hours`
- [x] For testing , code review and documentation. ` 3-4 hours`

_______________________________________________________________________________________________________________________________________

TOTAL TIME = 10 HOURS

_______________________________________________________________________________________________________________________________________
Checklist:

- [x]  I have performed a self-review of my own code.

2023-07-05 12:04 UTC, GauravGusain98 commented
@AkshitRawat1207 The PR name doesnot looks correct to me. Can you please check and do the required changes

2023-07-05 12:05 UTC, GauravGusain98 commented on Modules/CodeTrek/Resources/views/index.blade.php
> +                                        $intern_date = Carbon\Carbon::parse($applicant->internship_start_date);
In Portal we use camelCase for variable naming in PHP. So please update the name like suggested below
```suggestion
                                        $internshipStartDate = Carbon\Carbon::parse($applicant->internship_start_date);
```

2023-07-05 12:06 UTC, GauravGusain98 commented on Modules/CodeTrek/Resources/views/index.blade.php
> +                                            $daysInCodetrek = $intern_date->diffInDays($applicant->start_date);
In case of olde data this column will be initially null. So there should be a logic to handle null case. Ideally in such situation the logic of else block should run

2023-07-05 12:09 UTC, GauravGusain98 commented on Modules/CodeTrek/Resources/views/index.blade.php
> +                                            $daysInCodetrek = $intern_date->diffInDays($applicant->start_date);
Also we should avoid writing code related to any logic in blade file. You can create a laravel model accessor to calculate the value related to daysInCodetrek.

Read this [topic](https://laravel.com/docs/8.x/eloquent-mutators#defining-an-accessor) and see how we can create an accessor and read data from it.

2023-07-05 12:28 UTC, AkshitRawat1207 commented on Modules/CodeTrek/Resources/views/index.blade.php
> +                                        $intern_date = Carbon\Carbon::parse($applicant->internship_start_date);
okay sir

2023-07-06 17:58 UTC, GauravGusain98 requested changes

2023-07-06 17:58 UTC, GauravGusain98 commented on Modules/CodeTrek/Resources/views/index.blade.php
> +                                        $daysInCodetrek = $applicant->getDaysInCodetrekAttribute($applicant);
When you create accessor it can be easily be called like this
```suggestion
                                        $daysInCodetrek = $applicant->days_in_codetrek;
```

2023-07-06 17:58 UTC, GauravGusain98 commented on Modules/CodeTrek/Entities/CodeTrekApplicant.php
> +    public function getDaysInCodetrekAttribute(self $applicant)
No need to pass applicant, you can simply use `$this` attribute to get the value of applicant class object
```suggestion
    public function getDaysInCodetrekAttribute()
```

2023-07-06 17:58 UTC, GauravGusain98 commented on Modules/CodeTrek/Entities/CodeTrekApplicant.php
> +        $internDate = Carbon::parse($applicant->internship_start_date);
This name sounds more meaningful
```suggestion
        $internshipStartDate = Carbon::parse($applicant->internship_start_date);
```

2023-07-09 17:53 UTC, GauravGusain98 approved these changes
LGTM

2023-07-09 17:53 UTC, merged