tab count correction in codetrek module  using centre filter
ColoredCow/portal pull request #3247
Opened 2023-07-06 06:46 UTC by AnirudhAP2k

### Description
I applied a count() at codetrek module to count the number of applicants after applying the center filter at codetrek controller and put the integer value in statusCount[] array for $status index i.e. the status filter which we are applying at codetrek module .
### Checklist:
- [x] I have performed a self-review of my own code.

2023-07-06 08:08 UTC, LavishRawat commented
@AnirudhAP2k 
**Testing Feedbacks**

1) The filter only applies to the selected tab, while the other tab shows the total count, but as soon as we switch to the other Tab it gives the correct count for the applied filter while the previous tab shows the total count.

   <img width="1182" alt="image" src="https://github.com/ColoredCow/portal/assets/108713935/66c54b99-1cbc-4b31-80f6-f22e032a1d0e">
   
after switching to the `Inactive Tab`, the count changes to 2 and the active tab then shows the total count of applicants.

<img width="1273" alt="image" src="https://github.com/ColoredCow/portal/assets/108713935/ab044c33-ed59-4c98-bf52-2a89148664bd">

2023-07-06 18:01 UTC, GauravGusain98 requested changes

2023-07-07 07:49 UTC, GauravGusain98 requested changes

2023-07-07 07:49 UTC, GauravGusain98 commented on Modules/CodeTrek/Services/CodeTrekService.php
> +        }
For count we already have written the logic in line 34 where the count data is being stored in $applicantsData variable. You don't need to again write query to get the count. 

In line 34 logic currently, its only filtering based on search and not on center so please update the logic such that it also filter based on center

2023-07-07 12:32 UTC, Ayush8923 submitted a review, later dismissed
Added some comments. Please check.

2023-07-07 12:32 UTC, Ayush8923 commented on Modules/CodeTrek/Services/CodeTrekService.php
> +            $applicantsData = $query->get();
can you please let me know, what's the use of this line?

2023-07-08 07:14 UTC, AnirudhAP2k commented on Modules/CodeTrek/Services/CodeTrekService.php
> +        $query = CodeTrekApplicant::whereIn('status', ['active', 'inactive', 'completed'])
Sir, this query variable was already defined in master branch before this task was given. I only altered the data passing to query variable in line 34.
And also query is performing same function as a database query of storing all the data of applicants.

2023-07-08 07:20 UTC, AnirudhAP2k commented on Modules/CodeTrek/Services/CodeTrekService.php
> +            $applicantsData = $query->get();
In this statement, it is inside an 'IF' conditional statement such that if we put "ALL CENTRE" filter, the value assigned to $centre variable will be of 'null', so this condition will pass and it will assign all the codeTrek Applicant's data to to $appliantData variable from $query, which acts as a database query for Applicants having all data.

2023-07-09 17:52 UTC, GauravGusain98 commented on Modules/CodeTrek/Services/CodeTrekService.php
> +        $query = CodeTrekApplicant::whereIn('status', ['active', 'inactive', 'completed'])
No problem @AnirudhAP2k. It's always good to correct the old code as well. Just give the variable a good meaningful name

2023-07-10 07:28 UTC, GauravGusain98 requested changes

2023-07-10 07:28 UTC, GauravGusain98 commented on Modules/CodeTrek/Services/CodeTrekService.php
> +            $applicantsData = $applicantCountData->get();
Why you changed the variable name here. It should be same `applicantCountData`

2023-07-10 07:42 UTC, AnirudhAP2k commented on Modules/CodeTrek/Services/CodeTrekService.php
> +            $applicantsData = $applicantCountData->get();
Sir, applicantData is a different variable performing different function of storing filtered data on the basis of centre and status coming from $applicantCountData. 
Here applicantData and applicantCountData are two different variables performing different functions.

2023-07-10 11:26 UTC, GauravGusain98 commented on Modules/CodeTrek/Services/CodeTrekService.php
> +            'applicantsData' => $applicantCountData,
can you check if we are using this `applicantsData` in frontend or not. Because I think we might be only using `statusCounts` variable there as it is derived from the `applicantsData` only

2023-07-10 11:26 UTC, GauravGusain98 commented on Modules/CodeTrek/Services/CodeTrekService.php
> +            'applicantsData' => $applicantCountData,
In case the `applicantsData` is not being used in frontend, please remove it from the return statement else its fine

2023-07-10 11:40 UTC, AnirudhAP2k commented on Modules/CodeTrek/Services/CodeTrekService.php
> +            'applicantsData' => $applicantCountData,
Okay done sir.

2023-07-10 17:50 UTC, Ayush8923 reviewed
Added one question, else looks good to me 👍.

2023-07-10 17:50 UTC, Ayush8923 commented on Modules/CodeTrek/Services/CodeTrekService.php
> -use  Modules\CodeTrek\Emails\CodetrekMailApplicant;
I don't think, we need to remove these 2 lines. Commented out the mail functionality for now. But we need this codetrek mail functionality feature in the future. So let me know, is there any specific reason you removed these lines.

2023-07-10 17:54 UTC, AnirudhAP2k commented on Modules/CodeTrek/Services/CodeTrekService.php
> -use  Modules\CodeTrek\Emails\CodetrekMailApplicant;
I removed those because it was showing error during CI checks, as classes  were unused during execution.

2023-07-10 18:30 UTC, GauravGusain98 approved these changes
LGTM

2023-07-10 18:31 UTC, merged