Implemented button logics in codtrek applicant evaluate page
ColoredCow/portal pull request #3248
Opened 2023-07-06 07:23 UTC by Priyanka-Kaintura

Targets #3234

### Description

Implemented button logic for codeTrek applicant evaluate page.

### Checklist:

- [ ] I have performed a self-review of my own code.

2023-07-06 09:53 UTC, LavishRawat commented
@Priyanka-Kaintura 
**Testing Feedbacks**
1) The Buttons are not aligned properly.Please have a look.

    
<img width="933" alt="image" src="https://github.com/ColoredCow/portal/assets/108713935/48621fb2-4215-40f0-ac58-9a9b4c7db990">

2) The `Start Internship` will only appear if the applicant is in `onboarded` round while for other cases it should not appear for `Active` tab.

<img width="975" alt="image" src="https://github.com/ColoredCow/portal/assets/108713935/e5b01fb2-76b9-4bdd-8a0b-ed8de6dce1ff">

2023-07-06 10:23 UTC, Priyanka-Kaintura commented
Sir, I don't understand any use of accordion class here as tI cannot find anything to show in the item. Do we really need to keep this? If the divisions in the file are corrected the output looks something like this. 
![image](https://github.com/ColoredCow/portal/assets/112419110/0df4e08c-b0bc-45ef-b151-eba00c027456)
![image](https://github.com/ColoredCow/portal/assets/112419110/c567f597-19f7-437b-8965-0a4c2574b76d)

2023-07-07 03:09 UTC, Priyanka-Kaintura commented
@LavishRawat @Ayush8923 Sir, Is there any relevance of accordion in this page as all the items target the same data of the applicant. 
![image](https://github.com/ColoredCow/portal/assets/112419110/527ef17d-bf6f-4da1-8ccc-4627f4d2900b)

2023-07-07 11:14 UTC, Priyanka-Kaintura commented
I think showing the applicant information only once at the top will be enough other than that only feedbacks can be made collapsable items. if it is suitable please let me know & I will try implementing it then.

2023-07-07 15:44 UTC, LavishRawat commented
@Priyanka-Kaintura 
**Testing Feedbacks**
1) There is no space between the cards except for the gap between the first and second card.
<img width="1070" alt="image" src="https://github.com/ColoredCow/portal/assets/108713935/b4b527de-7993-478c-bdbf-79effdf2b73f">

2) The card footer is still visible even if the card is not expanded. Same happening in case of `InActive` applicant.
**Active**
    <img width="878" alt="image" src="https://github.com/ColoredCow/portal/assets/108713935/f295f67a-fb60-4c26-8cf5-d4d4a626989c">
**Inactive**
    <img width="858" alt="image" src="https://github.com/ColoredCow/portal/assets/108713935/3accf918-d334-42f2-9e05-e234cd12097d">

3) In the case of `Completed` applicant card footer should not be visible as there are no buttons to display.
    <img width="919" alt="image" src="https://github.com/ColoredCow/portal/assets/108713935/2c352a7e-d871-4eca-ad46-ff8be5412c6d">

2023-07-08 08:10 UTC, LavishRawat commented
@Priyanka-Kaintura 
**Testing Ui Feedback** 
1) Please align the `move to round`  field with the `Update Feedback ` field.

   <img width="1002" alt="image" src="https://github.com/ColoredCow/portal/assets/108713935/80b1382c-aa76-467b-b237-50522b0de18a">
   
2) Please along the ` Mark Active ` button with the `Update Feedback` field.
    <img width="878" alt="image" src="https://github.com/ColoredCow/portal/assets/108713935/61c91700-c8d0-477c-9ad0-a5648b3d5692">
    
    
 else the flow and functionality is fine.

2023-07-08 08:25 UTC, Priyanka-Kaintura commented
Sir, do you mean to shift all the elements of footer to the right or just the margins in the footer.

2023-07-08 09:04 UTC, LavishRawat commented
> Sir, do you mean to shift all the elements of footer to the right or just the margins in the footer.

Hey @Priyanka-Kaintura The feedback was to align the `move to round ` field with the fields above it.
    <img width="874" alt="image" src="https://github.com/ColoredCow/portal/assets/108713935/e3431726-fd3b-46dd-b64b-448bf5af39d6">

in your case , the following were not aligned.

<img width="1002" alt="image" src="https://github.com/ColoredCow/portal/assets/108713935/80b1382c-aa76-467b-b237-50522b0de18a">

2023-07-08 10:02 UTC, Priyanka-Kaintura commented
@LavishRawat Sir, please check it now

2023-07-09 17:56 UTC, GauravGusain98 commented on Modules/CodeTrek/Resources/views/evaluate.blade.php
> +                                    </div>
```suggestion
                                @csrf
                                <div class="d-flex align-items-center">
                                    <select name="round" id="rounds" class="w-22p">
                                        @foreach (config('codetrek.rounds') as $round)
                                            <option value="{{ $round['slug'] }}">Move to {{ $round['label'] }}
                                            </option>
                                        @endforeach
                                    </select>
                                    <button type="submit" class="btn btn-success ml-2">Take Action</button>
                                </div>
```

2023-07-09 18:02 UTC, GauravGusain98 requested changes

2023-07-09 18:02 UTC, GauravGusain98 commented on Modules/CodeTrek/Resources/views/evaluate.blade.php
> +                        <div class="card-footer row {{($applicant->status == 'completed') ? 'd-none': '' }} ml-1">
There is a white gap coming on left side of footer. Please fix it
<img width="956" alt="image" src="https://github.com/ColoredCow/portal/assets/54376313/186341ba-3d3f-4acb-97f9-b5851475d3c3">

2023-07-10 07:24 UTC, LavishRawat approved these changes

2023-07-10 08:02 UTC, GauravGusain98 approved these changes
LGTM

2023-07-10 08:02 UTC, merged