#3253 Missing Domain Dropdown in "Add New Participant" Form
ColoredCow/portal pull request #3257
Opened 2023-07-07 08:41 UTC by MohitGururani

Targets #3253 

### Description
Currently, the "Add New Participant" form in CodeTrak lacks a crucial element: a dropdown menu to select the domain of the participant. This dropdown menu is essential as CodeTrak provides training to candidates from various domains. Without this dropdown, it becomes challenging to accurately categorize and manage participants based on their domains.

### Solution:
This pull request enhances the "Add New Participant" form by adding a dropdown menu that allows users to select the domain of the new participant. The dropdown menu is labeled as "Domain" and is a required field for form submission. The dropdown options are pre-populated with the values "Engineering" and "Design" based on the configuration array config('codetrek.type'). The dropdown is also designed to accommodate future domain options as the organization grows.

### Expected Changes:
- Integrate a dropdown menu into the "Add New Participant" form. 
- Label the dropdown menu as "Domain" or "Select Domain Name."
- Pre-populate the dropdown menu with the options "Engineering" and "Design."
- Ensure the dropdown menu is expandable to include future domain options.
- Validate the domain selection to prevent submission with an empty or invalid selection.
- Add the selected domain to the backend.

### Expected Time
- [ ] Integrate a dropdown menu into the "Add New Participant" form: 0.5-1 hours
- [ ] Label the dropdown menu as "Domain" or "Select Domain Name": 30 minutes
- [ ] Pre-populate the dropdown menu with the options "Engineering" and "Design": 1 hour
- [ ] Make the dropdown menu expandable to include future domain options: 1 hour
- [ ] Implement domain selection validation: 1-2 hours
- [ ] Add the selected domain to the backend: 1-2 hours

**Total Expected Time: 5 - 7.5 hours**
### Checklist:

- [ ] I have performed a self-review of my own code.

2023-07-07 08:42 UTC, MohitGururani commented
**Total Expected Time: 5 - 7.5 hours**
**Total Time Taken : 8 hours**

2023-07-07 09:19 UTC, LavishRawat commented
@MohitGururani 
**Testing Feedback**

1) When attempting to edit an applicant's information, I noticed that all the fields are pre-filled except for the `Select Domain Name` field. Please let me know if its the same for you.
<img width="1121" alt="image" src="https://github.com/ColoredCow/portal/assets/108713935/5428da78-cf7e-4729-84f1-ff37be568c88">

2023-07-07 10:56 UTC, Ayush8923 requested changes
Added one small comment.

2023-07-07 10:56 UTC, Ayush8923 commented on Modules/CodeTrek/Resources/views/edit.blade.php
> +                            </div>
Please fix the indentation here.

2023-07-07 11:02 UTC, MohitGururani commented on Modules/CodeTrek/Resources/views/edit.blade.php
> +                            </div>
@Ayush8923  I have fixed the indentation.Please have a look.

2023-07-07 11:13 UTC, Ayush8923 requested changes
Added more comments. Please check.

2023-07-07 11:13 UTC, Ayush8923 commented on database/migrations/2023_07_07_123151_add_domain_name_to_code_trek_applicant_table.php
Please create all the `codeTrek` migrations inside the `CodeTrek` module.

2023-07-07 11:13 UTC, Ayush8923 commented on database/migrations/2023_07_07_123151_add_domain_name_to_code_trek_applicant_table.php
> +class AddDomainNameToCodeTrekApplicantTable extends Migration
```suggestion
class AddDomainNameToCodetrekApplicantTable extends Migration
```

2023-07-07 13:40 UTC, LavishRawat approved these changes

2023-07-07 15:52 UTC, Ayush8923 requested changes

2023-07-07 15:52 UTC, Ayush8923 commented on Modules/CodeTrek/Resources/views/edit.blade.php
> +                            <label for="domain" class="field-required">{{ __('Domain Name') }}</label>
```suggestion
                            <label for="domain" class="field-required">Domain Name</label>
```

2023-07-07 15:52 UTC, Ayush8923 commented on Modules/CodeTrek/Resources/views/modals/add-applicant-modal.blade.php
> +                                <label for="domain" class="field-required">{{ __('Domain Name') }}</label>
Same here. Please update here also according to the previous comment.

2023-07-07 16:00 UTC, MohitGururani commented on Modules/CodeTrek/Resources/views/edit.blade.php
> +                                <label for="domain" class="field-required">{{ __('Select Domain Name') }}</label>
@LavishRawat inside the dropdown, if we put "select domain name" it will be more appropriate,like in the other fields.Please let me know what you think otherwise i will change accordingly.

2023-07-07 16:11 UTC, LavishRawat commented on Modules/CodeTrek/Resources/views/edit.blade.php
> +                                <label for="domain" class="field-required">{{ __('Select Domain Name') }}</label>
@MohitGururani Yes, the placeholder of the dropdown will be `select domain name`. Here the Feedback is to change the Label of the field but the placeholder will remain the same.

2023-07-09 17:41 UTC, GauravGusain98 commented on Modules/CodeTrek/Services/CodeTrekService.php
> +        $applicant->latest_round_name = 'level-1';
```suggestion
        $applicant->latest_round_name = config('codetrek.rounds.level-1.slug');
```

2023-07-09 17:45 UTC, GauravGusain98 approved these changes
LGTM

2023-07-09 17:46 UTC, merged