Added a new round introductory call in codetrek rounds and made relat…
ColoredCow/portal pull request #3279
Opened 2023-07-13 09:06 UTC by Priyanka-Kaintura

…ed changes

Targets #3266

## Description of the changes

Added a new round introductory call to the codetrek rounds.

## Breakdown & Estimates 

**Expected Time Range:** 4 hrs

**Actual Time:** 4 hrs

## Feedback Cycle

**Cycle Count: 0**

## Checklist:

- [ ] The PR title follows this syntax: <#IssueID> \<PR Title>
- [ ] I have linked the issue id in the PR description.
- [ ] I have performed a self-review of my own code.
- [ ] I have added comments on my code changes where required.

2023-07-13 10:38 UTC, LavishRawat requested changes

2023-07-13 10:38 UTC, LavishRawat commented on Modules/CodeTrek/Services/CodeTrekService.php
> +        $applicationRound->latest_round_name = 'introductory-call';
@Priyanka-Kaintura let’s pick this from config.

2023-07-13 10:38 UTC, LavishRawat commented on Modules/CodeTrek/Database/factories/CodeTrekApplicantRoundDetailsFactory.php
> +            'latest_round_name' => 'introductory-call',
@Priyanka-Kaintura lets pick this from config.

2023-07-14 10:32 UTC, GauravGusain98 commented
@Priyanka-Kaintura This checklist is not yet completed
<img width="771" alt="image" src="https://github.com/ColoredCow/portal/assets/54376313/2a66a75c-5463-4318-b8c5-6c3569b15b4c">

This checklist means that in your GitHub code changes you need to leave comments on line explaining the changes you have done

2023-07-14 10:43 UTC, Priyanka-Kaintura commented
@GauravGusain98 Sir, I didn't find any piece of code requiring specific comment. So I haven't added any

2023-07-17 07:22 UTC, Ayush8923 requested changes
Added one comment. Please check.

2023-07-17 07:22 UTC, Ayush8923 commented on Modules/CodeTrek/Config/config.php
> +            'class' => 'badge badge-info'
This color is already used in the `preparatory` round. Please use different color here.

2023-07-17 08:01 UTC, Ayush8923 requested changes
Added one more suggestion.

2023-07-17 08:01 UTC, Ayush8923 commented on Modules/CodeTrek/Config/config.php
> +            'class' => 'badge badge-warning'
I think the `badge-warning` color does not make sense in the `introductory-call` round. I suggest make the custom class. and then used directly here.
Something like this.
```
.badge-theme-teal {
background-color: #63b2b7;
}
```
```suggestion
            'class' => 'badge badge-theme-teal'
```

2023-07-17 12:34 UTC, Priyanka-Kaintura commented
@Ayush8923 Please check the badge color now, if it is okay!

2023-07-18 05:39 UTC, Ayush8923 approved these changes
LGTM 👍🏻

2023-07-18 06:32 UTC, LavishRawat approved these changes

2023-07-18 09:45 UTC, GauravGusain98 commented
### Testing feedbacks
1. Instead of showing round slug here can you show label
<img width="1046" alt="image" src="https://github.com/ColoredCow/portal/assets/54376313/8f878208-7565-4610-aa2c-f6aa6e10092e">

2023-07-18 13:18 UTC, merged