HOTFIX - Fix finance report
ColoredCow/portal pull request #3308
Opened 2023-07-25 08:48 UTC by GauravGusain98

### Changes
1. Added service class in revenue

2023-07-25 08:51 UTC, GauravGusain98 commented on Modules/Report/Services/Finance/ReportDataService.php
> -        $reportData = $this->service->getRevenueReportDataForClient($filters, $client);
Earlier we had a constructer created for protected variable service. It got removed later. Instead of creating a constructed I've directly created an object of that class as it is possible that we might use multiple services in future
<img width="469" alt="image" src="https://github.com/ColoredCow/portal/assets/54376313/e2a95fbc-d63e-4c3e-8fe4-77cec87644c4">

2023-07-25 08:52 UTC, GauravGusain98 commented on Modules/Report/Services/Finance/ReportDataService.php
> -    public function getDataForDailyCodeTrekApplications($type, $filters, $request)
move this function to separate file

2023-07-25 08:52 UTC, GauravGusain98 commented on Modules/Report/Http/Controllers/CodeTrekController.php
> -        return $this->service->getDataForDailyCodeTrekApplications($type, json_decode($filters, true), $request);
removed unused variable

2023-07-25 10:54 UTC, pankaj-ag requested changes

2023-07-27 06:15 UTC, GauravGusain98 commented on Modules/Report/Services/CodeTrek/ReportDataService.php
> +            $applicants = CodeTrekApplicant::find('start_date');
done

2023-07-27 06:18 UTC, GauravGusain98 commented on Modules/Report/Services/Finance/ReportDataService.php
> -        $reportData = $this->service->getRevenueReportDataForClient($filters, $client);
Here is the PR link 
https://github.com/ColoredCow/portal/pull/3231

2023-07-27 06:24 UTC, pankaj-ag approved these changes

2023-07-27 06:24 UTC, merged