[Fix]:- HR module recruitment page performance
ColoredCow/portal pull request #3355
Opened 2023-09-06 13:58 UTC by Ayush8923

**Description**
- Optimize the HR recruitment index function code and remove the unnecessary code.
- In this, we need to test this in the UAT env. I checked this in the latest database dump of uat in local it was working fine.  Initially, it was taking time 14 seconds to load the page.

**What do we need to do next**
- We need to clean up more code in this. Because there is some same code in the application service and controller, but we are not using this service right now, all the code is added in the controller.

2023-09-06 15:58 UTC, Ayush8923 commented on Modules/HR/Http/Controllers/Recruitment/ApplicationController.php
> +        });
Before, When this function is rendered then every time it's fetched the data from the database. Now, here we are using the Laravel Caching mechanism, If this data is in the cache memory then it will fetch the data from the cache. Every data has its own unique identity and its cache expiration time is 60 minutes. So here we do not need to hit the query in the database all the time.

2023-09-06 16:02 UTC, Ayush8923 commented on Modules/HR/Http/Controllers/Recruitment/ApplicationController.php
> +            ->toArray();
Before, every time the loop ran, we would hit the database with a query, which could cause some performance issues. But now we are hitting the query in the database only once and fetching the data we need.

2023-09-06 16:11 UTC, Ayush8923 commented on Modules/HR/Http/Controllers/Recruitment/ApplicationController.php
> +        $applicantData = ApplicantMeta::whereIn('hr_applicant_id', $applications)->get();
Earlier we used to hit query in databse corresponding to each applicant id in each loop. Due to which there could be some problem in performance and time complexity also increased. But now we are passing collection of applicant id directly and hitting query in the database only once.

2023-09-07 03:53 UTC, GauravGusain98 approved these changes
LGTM

2023-09-07 05:37 UTC, pankaj-ag requested changes

2023-09-07 05:37 UTC, pankaj-ag commented on Modules/HR/Http/Controllers/Recruitment/ApplicationController.php
> +        $attr['jobs'] = Cache::remember('jobs', now()->addMinutes(60), function () {
@Ayush8923 This will restrict the system updates for one hour. So let's say you add a tag now and it will show up after 1 hour which does not make sense to me. 

Also this implementation is good but I feel that there are lot of scope to fix the existing code and then apply caching for these things. If we apply caching right now it will just suppress the error and time. 

So for now remove this implementation and try to fix all the queries we are making to DB and just fix them. 








This seems like a fine approach but we will use it as a last thing.

2023-09-07 05:37 UTC, pankaj-ag commented on Modules/HR/Http/Controllers/Recruitment/ApplicationController.php
> +            ->toArray();
This is good. 👍🏼

2023-09-07 05:41 UTC, Ayush8923 commented on Modules/HR/Http/Controllers/Recruitment/ApplicationController.php
> +        $attr['jobs'] = Cache::remember('jobs', now()->addMinutes(60), function () {
Make sense 👍

2023-09-07 06:03 UTC, Ayush8923 commented on Modules/HR/Http/Controllers/Recruitment/ApplicationController.php
> +        ->appends(request()->except('page'));
Before, we hit the different queries in the database, which could cause some performance issues and the time complexity increase. now, here we combined both queries and hit the query only once time in the database.

2023-09-07 06:12 UTC, Ayush8923 commented
@pankaj-ag I'm still working on some more cleanup and will make those changes in another PR.

2023-09-07 06:30 UTC, pankaj-ag commented on Modules/HR/Http/Controllers/Recruitment/ApplicationController.php
> +        ->appends(request()->except('page'));
It's bit tough to check how it's going to impact. So please test it carefully

2023-09-07 06:31 UTC, pankaj-ag approved these changes

2023-09-07 06:32 UTC, merged