Add employee profitability list
ColoredCow/portal pull request #3525
Opened 2024-04-07 16:33 UTC by shubtiwari

Targets #ISSUE_ID

## Description of the changes

## Breakdown & Estimates 

**Expected Time Range:**

**Actual Time:** 

## Feedback Cycle

**Cycle Count: 0**

## Checklist:

- [ ] The PR title follows this syntax: <#IssueID> \<PR Title>
- [ ] I have linked the issue id in the PR description.
- [ ] I have performed a self-review of my own code.
- [ ] I have added comments on my code changes where required.

2024-04-09 05:27 UTC, P4NK4J requested changes
Left some comments, @shubtiwari Please take a look

2024-04-09 05:27 UTC, P4NK4J commented on app/Http/Controllers/Settings/ProfitabilityController.php
> +        return redirect()->back()->with('status', 'Saved Successfully!');
These values should go in settings table rather than user_meta, since it's a system variable

2024-04-09 05:27 UTC, P4NK4J commented on resources/views/hr/employees/index.blade.php
> +    $route_name = Route::getCurrentRoute()->getName();
We use camelCasing for variables here, let's replace it with  `$routeName` all across

2024-04-09 05:27 UTC, P4NK4J commented on resources/views/hr/employees/index.blade.php
> +                @if($route_name==="employee")
```suggestion
                @if($routeName === "employee")
```

2024-04-09 05:27 UTC, P4NK4J commented on resources/views/hr/employees/index.blade.php
> +                            <i class="fa fa-info-circle" aria-hidden="true"></i>
Rather than tooltip we need to use alert symbol here

2024-04-09 05:27 UTC, P4NK4J commented on resources/views/settings/profitability-threshold-value/index.blade.php
> +                    <input type="number" class="col-xs text-center outline-none h-40 w-100 rounded-12 quantity" id="quantity" name="profitability_threshold_value" min="1" max="1000000" value="{{ old
Let's not put a limit here, it can increase and decrease as per the organizations steam

2024-04-09 05:27 UTC, P4NK4J commented on routes/web.php
> +        Route::post('/profitability-threshold-value', 'profitabilityController@update')->name('settings.update-profitability-threshold-value');
It's minimum earning threshold to make an employee profitable, instead of a profitability threshold. Let's update the name, as profitability is not what is defined by this route variable. It can be `employee-earning-threshold`

2024-04-16 07:30 UTC, GauravGusain98 commented on Modules/User/Database/Seeders/UserPermissionsTableSeeder.php
> +
This should not be in this seeder file. Please check if there are any seeder for employee. Add it there.

2024-04-16 11:20 UTC, GauravGusain98 approved these changes

2024-04-16 11:21 UTC, P4NK4J approved these changes

2024-04-16 11:21 UTC, merged