Project contract end date alert config
ColoredCow/portal pull request #3614
Opened 2024-05-01 06:17 UTC by sameer-bot1

Targets #3613

## Problem statement

2024-05-01 08:53 UTC, sameer-bot1 commented on app/Http/Controllers/Settings/ConfigurationController.php
This file used to be named ProfitabilityController.php. I renamed it to ConfigurationController because now it handles configuring multiple values instead.

2024-05-01 08:59 UTC, sameer-bot1 commented on app/Services/ConfigurationService.php
I created ConfigurationService  here created a method retrieves settings from the database related to employee earning thresholds and contract end date thresholds and updates an existing record

2024-05-01 09:03 UTC, sameer-bot1 commented on resources/views/settings/configuration-threshold/index.blade.php
Previously, the location of index.blade.php was "resources/views/settings/employee-earning-threshold/index.blade.php". I've now changed it to "resources/views/settings/configuration-threshold/index.blade.php"

2024-05-01 09:16 UTC, pokhiii requested changes

2024-05-01 09:16 UTC, pokhiii commented on Modules/Report/Http/Controllers/ContractReportController.php
> +        $alertDiff = Setting::where('setting_key', 'contract_endDate_threshold')->value('setting_value');
What's the idea behind choosing the name `$alertDiff`? Why not simply use: `$contractEndDateThreshold`

2024-05-01 09:16 UTC, pokhiii commented on app/Services/ConfigurationService.php
> +        $ConfigsValue = Setting::query()
naming convention

2024-05-01 09:16 UTC, pokhiii commented on app/Services/ConfigurationService.php
Any particular reason for calling it ConfigurationService and not SettingService?

2024-05-01 09:16 UTC, pokhiii commented on app/Services/ConfigurationService.php
> +    public function index()
The method `index` make more sense in the context of a controller. For a setting it can be more specific like `getList`, etc. depending on what you're trying to do.

2024-05-01 09:16 UTC, pokhiii commented on app/Services/ConfigurationService.php
> +            ->orWhere('setting_key', 'contract_endDate_threshold')
What special about these two settings: `employee_earning_threshold` and `contract_endDate_threshold` that you have to hardcode it here?

Ideally, the service should be generic enough to be re-used and provide common operations that can be done on a particular component/resource of the system.


It is not clear to me why the `index` method is return employee earning and contract end date threshold

2024-05-01 09:16 UTC, pokhiii commented on routes/web.php
> +        Route::post('/configuration-threshold', 'ConfigurationController@update')->name('settings.update-configuration-threshold');
If we go by this pattern, we will have to introduce a new route everytime a new setting is introduced. So routes will start growing as the rows in the settings table increase. That's not very scalable approach.

You should think of how setting routes can be used to get retrieve those values.

2024-05-01 09:50 UTC, sameer-bot1 commented on Modules/Report/Http/Controllers/ContractReportController.php
> +        $alertDiff = Setting::where('setting_key', 'contract_endDate_threshold')->value('setting_value');
> Also, what's the convention behind choosing the setting key `contract_endDate_threshold` it's a combination of snake case and cameCase.
> 
> `contract_end_date_threshold` is what i think we should have

Ok, Sure

2024-05-01 10:32 UTC, sameer-bot1 commented on Modules/Report/Http/Controllers/ContractReportController.php
> +        $alertDiff = Setting::where('setting_key', 'contract_endDate_threshold')->value('setting_value');
> What's the idea behind choosing the name `$alertDiff`? Why not simply use: `$contractEndDateThreshold`

there is no idea behind it, I am changing it to $contractEndDateThreshold

2024-05-01 10:48 UTC, sameer-bot1 commented on app/Services/ConfigurationService.php
> Any particular reason for calling it ConfigurationService and not SettingService?

in Setting we have different options like bank Detail, Salary, Country Detail, Config Variable. we are using Service for Config Variable.

2024-05-02 05:02 UTC, sameer-bot1 commented on app/Services/ConfigurationService.php
> +    public function index()
ok, sure

> The method `index` make more sense in the context of a controller. For a service it can be more specific like `getList`, etc. depending on what you're trying to do.

ok, sure

2024-05-02 05:19 UTC, sameer-bot1 commented on app/Services/ConfigurationService.php
> +        $ConfigsValue = Setting::query()
yes, i renamed as **ThresholdValues**

2024-05-02 05:43 UTC, sameer-bot1 commented on routes/web.php
> +        Route::post('/configuration-threshold', 'ConfigurationController@update')->name('settings.update-configuration-threshold');
no, We just need two routes. One to display the variable and the other to update all the variables.

2024-05-02 06:03 UTC, sameer-bot1 commented on app/Services/ConfigurationService.php
> +            ->orWhere('setting_key', 'contract_endDate_threshold')
Setting contains various data from different modules, but not all of it is needed for the configurationService. We only need specific data from the Setting, like `employee_earning_threshold` and `contract_endDate_threshold`..
And I renamed index method as getThresholdValue.

2024-05-02 06:17 UTC, sameer-bot1 commented on Modules/Report/Http/Controllers/ContractReportController.php
> +        $alertDiff = Setting::where('setting_key', 'contract_endDate_threshold')->value('setting_value');
> Don't we have a `SettingService`? Something like would be really nice:

Right now, we don't have SettingService.

2024-05-02 07:09 UTC, pokhiii commented on app/Services/ConfigurationService.php
> +    public function getThresholdValue()
```php
$setting_keys = [
    'employee_earning_threshold',
    'contract_end_date_threshold',
]
```

```suggestion
    public function getSettings($settingKeys: array)
```

2024-05-02 07:09 UTC, pokhiii commented on app/Services/ConfigurationService.php
> +            ->orWhere('setting_key', 'contract_end_date_threshold')
We can use [`whereIn`](https://laravel.com/docs/11.x/queries#additional-where-clauses) here
```suggestion
            ->whereIn('setting_key', $settingKeys)
```

2024-05-02 07:09 UTC, pokhiii commented on app/Services/ConfigurationService.php
> +        return $ThresholdValues;
```suggestion
        return $settings;
```

2024-05-02 07:09 UTC, pokhiii commented on app/Http/Controllers/Settings/ConfigurationController.php
> +        $ThresholdValues = $this->service->getThresholdValue();
1. Replace `getThresholdValue` with a more generic `getSettings` method
2. We need to provide the list of settings the controller wants to fetch from the service. For that, the controller will read the configuration values. The configurations for settings can be defined module-wise in `config/constants.php`


```php
[
    // ...
    'module-settings' => [
        'config-variable' => [
            'employee_earning_threshold',
            'contract_end_date_threshold',
        ]
    ],
]
```

3. The values can be read using the `config` helper: https://laravel.com/docs/11.x/configuration#accessing-configuration-values

2024-05-02 08:25 UTC, sameer-bot1 commented on app/Services/ConfigurationService.php
> +        return $ThresholdValues;
> 

ok, I changed it to `$setting`

2024-05-02 08:28 UTC, sameer-bot1 commented on app/Services/ConfigurationService.php
> +    public function getThresholdValue()
> ```
> $setting_keys = [
>     'employee_earning_threshold',
>     'contract_end_date_threshold',
> ]
> ```

Yes I changed it

2024-05-02 08:29 UTC, sameer-bot1 commented on app/Services/ConfigurationService.php
> +            ->orWhere('setting_key', 'contract_end_date_threshold')
> We can use [`whereIn`](https://laravel.com/docs/11.x/queries#additional-where-clauses) here

Ok, Sure

2024-05-02 09:39 UTC, sameer-bot1 commented on app/Http/Controllers/Settings/ConfigurationController.php
> +    protected $service;
> leave a line above

Ok

2024-05-02 09:41 UTC, sameer-bot1 commented on app/Http/Controllers/Settings/ConfigurationController.php
> +        return view('settings.configuration-threshold.index', [
> Can we keep the name consistent everywhere:

Ok, sure

2024-05-02 09:43 UTC, sameer-bot1 commented on app/Http/Controllers/Settings/ConfigurationController.php
> +        $this->service->updateSetting([
> Since we can save/update multiple settings

Ok, sure

2024-05-02 09:46 UTC, sameer-bot1 commented on app/Services/SettingService.php
> +    public function updateSetting($settings)
sure

2024-05-02 09:49 UTC, sameer-bot1 commented on config/constants.php
> +            'employee_earning_threshold', 'contract_end_date_threshold',
ok, sure

2024-05-02 10:17 UTC, sameer-bot1 commented on app/Http/Controllers/Settings/ConfigurationController.php
> +    public function update(Request $request)
sure

2024-05-02 14:33 UTC, pokhiii approved these changes

2024-05-02 14:33 UTC, pokhiii commented on routes/web.php
> +        Route::post('/config-variables', 'ConfigurationController@update')->name('settings.update-config-variables');
```suggestion
        Route::resource('config-variables', 'ConfigurationController')->only(['index', 'update']);
```

// config-variables.index
// config-variables.update

2024-05-03 08:28 UTC, merged