Added Universities-Module in HR Module
ColoredCow/portal pull request #759
Opened 2020-08-22 13:39 UTC by maniSHarma7575

@rathorevaibhav Please review the same and provide further feedback.

**What I did yet:**

- Added Universities Listing table.

- CRUD operation for universities and universities contacts.

- Worked on the design feedbacks.

2020-08-25 13:04 UTC, rathorevaibhav requested changes

2020-08-25 13:04 UTC, rathorevaibhav commented on resources/views/hr/universities/edit.blade.php
> +function addNewContactForm(opened){
external js. use app.js

2020-08-25 13:04 UTC, rathorevaibhav commented on resources/views/hr/universities/index.blade.php
> +            <h5 style="font-weight:bold">{{$university->name}}</h5>
```suggestion
            <h5 class='font-weight-bold'>{{$university->name}}</h5>
```

2020-08-25 13:04 UTC, rathorevaibhav commented on resources/views/hr/universities/index.blade.php
> +                    {{$contact->designation}}
```suggestion
                    {{$contact->designation ?? '-'}}
```

2020-08-25 13:04 UTC, rathorevaibhav commented on routes/web.php
> +        Route::resource('universities.contacts', 'Universities\UniversityContactController')
```suggestion
        Route::resource('universities/contacts', 'Universities\UniversityContactController')
```

2020-08-25 13:04 UTC, rathorevaibhav commented on routes/web.php
> +        Route::get('universities-reports', 'Universities\ReportController@index')->name('universities.reports');
```suggestion
        Route::get('universities/reports', 'Universities\ReportController@index')->name('universities.reports');
```

2020-08-26 09:03 UTC, maniSHarma7575 commented
Requested changes are done. @rathorevaibhav  sir, please review the same.

2021-07-19 14:40 UTC, closed without merging