(#794) New job opportunity should reflect on website also
ColoredCow/portal pull request #798
Opened 2021-07-21 17:17 UTC by atul5238

Target #794 
## Summary

1. New feature integrated using Corcel .
2. Job opportunities will update/delete/create on ColoredCow website also if updated from Portal.

2021-07-24 12:22 UTC, rathorevaibhav requested changes

2021-07-24 12:22 UTC, rathorevaibhav commented on Modules/HR/Http/Controllers/Recruitment/RecruitmentOpportunityController.php
> +        Corcel::where(['post_type' => 'career', 'post_title' => $opportunity['title']], 0)->delete();
What does `0` do here?

2021-07-24 12:22 UTC, rathorevaibhav commented on Modules/HR/Http/Controllers/Recruitment/RecruitmentOpportunityController.php
> +    public function store(JobRequest $request)
what happens when you update the job from the portal? Does the website counterpart also gets updated?

2021-07-26 16:16 UTC, atul5238 commented on Modules/HR/Http/Controllers/Recruitment/RecruitmentOpportunityController.php
> +        );
This feature includes both update and create, `updateOrcreate` is for just code optimization purpose.

2021-07-26 16:19 UTC, atul5238 commented on Modules/HR/Http/Controllers/Recruitment/RecruitmentOpportunityController.php
> +            'description' => $validated['description'] ?? null, // null needed for backward compatibility
Yeah I just checkout on UAT, removing description from nullable

2021-07-26 16:33 UTC, atul5238 commented on Modules/HR/Http/Controllers/Recruitment/RecruitmentOpportunityController.php
> +        Corcel::where(['post_type' => 'career', 'post_title' => $opportunity['title']], 0)->delete();
sorry forgot to remove, removing this.

2021-07-26 16:35 UTC, atul5238 commented on Modules/HR/Http/Controllers/Recruitment/RecruitmentOpportunityController.php
> +    public function store(JobRequest $request)
Yes

2021-07-26 16:36 UTC, atul5238 commented on Modules/HR/Http/Controllers/Recruitment/RecruitmentOpportunityController.php
> +            'link' => $validated['link'] ?? null,
permalink is still generated on Website.

2021-08-13 15:46 UTC, rathorevaibhav commented
@am-Anmol just wanted to check if you're working on this branch or on a separate one? If it's a separate one, can we close this Pull Request?

2021-08-13 15:49 UTC, am-Anmol commented
@rathorevaibhav Yes, I'm working on a new branch, so closing this pull request.

2021-08-13 15:49 UTC, closed without merging

2021-08-13 15:50 UTC, rathorevaibhav commented
Awesome thanks!