Added University auto create and mapping with applicant functionality
ColoredCow/portal pull request #846
Opened 2021-07-23 05:13 UTC by am-Anmol

## Summary
1.First checking if `college` is entered or not.
2.Then checking `university` is present or not in the database, if
    i.)Present then updating `hr_university_id`.
    ii.)Not Present then creating a new entry in the `university` table and updating `hr_university_id`.

2021-07-24 12:26 UTC, rathorevaibhav requested changes

2021-07-24 12:26 UTC, rathorevaibhav commented on Modules/HR/Entities/Applicant.php
> +        if (isset($attr['college']))
let's move this code to the model observer class.
https://laravel.com/docs/8.x/eloquent#observers

2021-07-24 12:26 UTC, rathorevaibhav commented on Modules/HR/Entities/Applicant.php
> +        {   $university = University::select('id')->where('name', $attr['college'])->first();
please properly format

2021-07-24 12:26 UTC, rathorevaibhav commented on Modules/HR/Entities/Applicant.php
> +        {   $university = University::select('id')->where('name', $attr['college'])->first();
The issue also says to check in university aliases. I don't see code for that. Am I missing anything?

2021-07-24 12:26 UTC, rathorevaibhav commented on Modules/HR/Entities/Applicant.php
> +            Applicant::where('email', $attr['email'])->update(['hr_university_id' => $university->id]);
```suggestion
            $applicant->update(['hr_university_id' => $university->id]);
```

2021-07-25 08:49 UTC, am-Anmol commented on Modules/HR/Entities/Applicant.php
> +        if (isset($attr['college']))
->@rathorevaibhav Can I create a custom static method that checks university and fires events in the same file `Modules/HR/Entities/Applicant.php`? like `public static function checkUniversity(parameters){ }`
->Or should I create a model observer class only?

2021-07-25 08:56 UTC, am-Anmol commented on Modules/HR/Entities/Applicant.php
> +        {   $university = University::select('id')->where('name', $attr['college'])->first();
I think there is no need to check in the `university aliases` table because we can add the `University Aliases` name only if the university exists in `hr_universities`.

2021-07-25 12:05 UTC, rathorevaibhav commented on Modules/HR/Entities/Applicant.php
> +        if (isset($attr['college']))
I'd prefer observer as it'll help to declutter the code in the model file and only relating to handling applicant create/update/store functionality.

2021-07-25 12:07 UTC, rathorevaibhav commented on Modules/HR/Entities/Applicant.php
> +        {   $university = University::select('id')->where('name', $attr['college'])->first();
So consider this scenario:
> Universities table has entry for name="Graphic Era Dehradun"
> Someone may enter "Graphic Era (Deemed to be University)" in their college name
> Now based on your code, it will create a new university and now system will have two universities but in reality they are one.
> If you had Graphic Era (Deemed to be University) as an alias set for existing university, then it will map it to the right one.

2021-07-27 19:05 UTC, am-Anmol commented
## Summary
1. Moved code to Model Observer class named `ApplicantObserver`.
2. Approach followed for checking university and mapping explained through flowchart below :

![image](https://user-images.githubusercontent.com/48876126/127212918-4b231699-c7f1-4d94-9258-69846c4e76f4.png)

2021-07-30 20:39 UTC, rathorevaibhav requested changes

2021-07-30 20:39 UTC, rathorevaibhav commented on Modules/HR/Observers/Recruitment/ApplicantObserver.php
> +    {   $data = request()->all();
formatting.

2021-07-30 20:39 UTC, rathorevaibhav commented on Modules/HR/Observers/Recruitment/ApplicantObserver.php
> +    {   $data = request()->all();
Did this file get automatically formatted with phpcs? Can you check manually?

2021-07-30 20:39 UTC, rathorevaibhav commented on Modules/HR/Observers/Recruitment/ApplicantObserver.php
> +                    $university = University::select('id')->where('name', $data['college'])->first();
Don't need second query
```suggestion
                    $university = University::create(['name'=>$data['college']]);
```

2021-07-30 20:39 UTC, rathorevaibhav commented on Modules/HR/Observers/Recruitment/ApplicantObserver.php
> +                $universityAlias = UniversityAlias::select('hr_university_id')->where('name', $data['college'])->first();
you don't need to make another query to get aliases. While querying university, you can get the alias relationship also. Something like:
```php
// with aliases or whatever the relationship name is defined in University model
$university = University::with(['aliases'])->where('name', $data['college'])->first();

// then access it via
$university->aliases()
```

2021-07-30 20:39 UTC, rathorevaibhav commented on Modules/HR/Observers/Recruitment/ApplicantObserver.php
> +                    $university = UniversityAlias::select('hr_university_id')->where('name', $data['college'])->first();
if you already have the $aliases as PHP variable, you can search within the array. No need to make another DB query.

2021-07-30 20:39 UTC, rathorevaibhav commented on Modules/HR/Observers/Recruitment/ApplicantObserver.php
> +                    $applicant->update(['hr_university_id' => $university->hr_university_id]);
this `else` will run when `$universityAlias==null` is false, which basically means there are aliases present for the university.

However, what happens if, within the aliases array, you're unable to find the university name match? In that case, it should create a new university, right? But it doesn't seem to be happening now.

2021-08-01 15:13 UTC, am-Anmol commented on Modules/HR/Observers/Recruitment/ApplicantObserver.php
> +                    $applicant->update(['hr_university_id' => $university->hr_university_id]);
If within the aliases array if unable to find the university name match then this `if` condition works and creates a new university
```
   if($universityAlias==null)
    {
        $university = University::create(['name'=>$data['college']]);
        $applicant->update(['hr_university_id' => $university->id]);
    }
```

2021-08-07 18:25 UTC, am-Anmol commented on Modules/HR/Observers/Recruitment/ApplicantObserver.php
> +                $universityAlias = UniversityAlias::select('hr_university_id')->where('name', $data['college'])->first();
Actually this code is `$university = University::with(['aliases'])->where('name', $data['college'])->first();` is not returning desired result as expected rather than returning `NULL` ,so that's why using another query for it.

2021-08-08 04:31 UTC, kuldeep3 reviewed
Please fix the indentation issue and then reassign it for review.

2021-08-08 04:31 UTC, kuldeep3 commented on Modules/HR/Entities/Applicant.php
> +
Remove extra indentation

2021-08-08 04:31 UTC, kuldeep3 commented on Modules/HR/Observers/Recruitment/ApplicantObserver.php
> +        }
```suggestion
        if (isset($data['college'])) {
            $university = University::select('id')->where('name', $data['college'])->first();
            if ($university == null) {
                $universityAlias = UniversityAlias::select('hr_university_id')->where('name', $data['college'])->first();
                if ($universityAlias == null) {
                    $university = University::create(['name' => $data['college']]);
                    $applicant->update(['hr_university_id' => $university->id]);
                } else {
                    $applicant->update(['hr_university_id' => $universityAlias->hr_university_id]);
                }
            } else {
                $applicant->update(['hr_university_id' => $university->id]);
            }
        }
```

2021-08-08 08:07 UTC, am-Anmol commented on Modules/HR/Entities/Applicant.php
> +
Ok

2021-08-09 09:55 UTC, P4NK4J reviewed
Minor comments, else looking good.

2021-08-09 09:55 UTC, P4NK4J commented on Modules/HR/Observers/Recruitment/ApplicantObserver.php
> +                if ($universityAlias==null) {
```suggestion
                if ($universityAlias == null) {
```

2021-08-09 09:55 UTC, P4NK4J commented on Modules/HR/Observers/Recruitment/ApplicantObserver.php
> +            if ($university==null) {
```suggestion
            if ($university == null) {
```

2021-08-09 11:04 UTC, am-Anmol commented on Modules/HR/Observers/Recruitment/ApplicantObserver.php
> +                if ($universityAlias==null) {
Ok, I'll do that.

2021-08-09 11:08 UTC, P4NK4J approved these changes
Looks good.

2021-08-09 11:27 UTC, P4NK4J commented
@rathorevaibhav , Since this PR involves your suggestions, hence it would be better if you could also have a look and approve the PR.

2021-08-10 04:06 UTC, GauravGusain98 commented on Modules/HR/Observers/Recruitment/ApplicantObserver.php
> +            if ($university == null) {
You need to make your code short. You can write it like this:

```suggestion
            if (!$university) {
```

2021-08-10 04:13 UTC, GauravGusain98 requested changes
Please have look at the comments and make the suggested changes.

2021-08-10 04:13 UTC, GauravGusain98 commented on Modules/HR/Observers/Recruitment/ApplicantObserver.php
> +            if ($university == null) {
You need to make your code short. You can write it like this:

```suggestion
            if (!$university) {
```

2021-08-10 04:13 UTC, GauravGusain98 commented on Modules/HR/Observers/Recruitment/ApplicantObserver.php
> +                if ($universityAlias == null) {
same here

2021-08-10 04:13 UTC, GauravGusain98 commented on Modules/HR/Observers/Recruitment/ApplicantObserver.php
> +}
Try avoiding, so many nested if-else conditions. You can use the `return` inside the `if` condition if you think the code will not run after it if the condition is true.

Give it a try.

2021-08-10 17:24 UTC, am-Anmol commented on Modules/HR/Observers/Recruitment/ApplicantObserver.php
> +            if ($university == null) {
Ok, I made these changes.

2021-08-10 17:24 UTC, am-Anmol commented on Modules/HR/Observers/Recruitment/ApplicantObserver.php
> +                if ($universityAlias == null) {
Ok, I made these changes.

2021-08-10 17:27 UTC, am-Anmol commented on Modules/HR/Observers/Recruitment/ApplicantObserver.php
> +}
I have tried but not working as expected so going with the previous one.

2021-08-11 03:40 UTC, GauravGusain98 requested changes
Looks good to me. Just some minor fixes. Please make these changes

2021-08-11 03:40 UTC, GauravGusain98 commented on Modules/HR/Observers/Recruitment/ApplicantObserver.php
> +        }
```suggestion
        if (isset($data['college'])) {
            $university = University::select('id')->where('name', $data['college'])->first();
            if (!$university) {
                $universityAlias = UniversityAlias::select('hr_university_id')->where('name', $data['college'])->first();
                if (!$universityAlias) {
                    $university = University::create(['name'=>$data['college']]);
                    $applicant->update(['hr_university_id' => $university->id]);
                } else {
                    $applicant->update(['hr_university_id' => $universityAlias->hr_university_id]);
                }
                return;
            } 
            $applicant->update(['hr_university_id' => $university->id]);
        }
```


This is what I meant by reducing the conditions, as using too many conditions is not a good way of writing code. Can you test it using this approach?

2021-08-11 10:52 UTC, am-Anmol commented on Modules/HR/Observers/Recruitment/ApplicantObserver.php
> +        }
Yes, this approach is working perfectly.

2021-08-11 10:53 UTC, am-Anmol commented on Modules/HR/Observers/Recruitment/ApplicantObserver.php
> +    {   $data = request()->all();
yes, this file gets automatically format with phpcs.

2021-08-11 17:13 UTC, P4NK4J approved these changes
Looks good to me

2021-08-11 17:15 UTC, merged