Added conversion rate column in Invoice table and conversion rate fie…
ColoredCow/portal pull request #856
Opened 2021-07-26 14:37 UTC by abhinav80066

## Summary
Added conversion_rate column in Invoice table and conversion rate field in view of invoice module.

2021-07-27 03:58 UTC, pankaj-ag requested changes

2021-07-27 03:58 UTC, pankaj-ag commented on Modules/Invoice/Resources/views/subviews/edit/invoice-details.blade.php
> +                        <label for="client_id" class="mr-4 pt-1 field-required">Conversion Rate:</label>
```suggestion
                        <label for="conversion_rate" class="mr-4 pt-1 field-required">Conversion Rate:</label>
```

2021-07-31 13:30 UTC, pankaj-ag commented on Modules/Invoice/Resources/views/subviews/edit/invoice-details.blade.php
> +                        <label for="client_id" class="mr-4 pt-1 field-required">Conversion Rate:</label>
We also need to add this column in fillables.

2021-08-03 06:07 UTC, rathorevaibhav commented
@pankaj-ag @abhinav80066 any updates on this?

2021-08-03 12:09 UTC, abhinav80066 commented
> @pankaj-ag @abhinav80066 any updates on this?

We are working on that and give an update soon.

2021-08-06 12:40 UTC, P4NK4J commented
@abhinav80066 , Please respond to the comments to make sure if you made the suggested changes, or if you have any different thoughts. This would bring clarity to the people reviewing the PR as well.

2021-08-06 12:49 UTC, abhinav80066 commented
> @abhinav80066 , Please respond to the comments to make sure if you made the suggested changes, or if you have any different thoughts. This would bring clarity to the people reviewing the PR as well.

Okay, I will keep that in mind from now on.

2021-08-06 16:16 UTC, kuldeep3 requested changes

2021-08-06 16:16 UTC, kuldeep3 commented on Modules/Invoice/Resources/views/subviews/edit/invoice-details.blade.php
> +                    </div>
Is d-flex required? What will happen if I only do this?
```suggestion

                    <label for="conversion_rate" class="mr-4 pt-1 field-required">Conversion Rate:</label>
                    <input type="text" class="form-control w-272 ml-auto" name="conversion_rate" v-model="conversion_rate" required="required">

```

2021-08-06 16:16 UTC, kuldeep3 commented on Modules/Invoice/Resources/views/subviews/edit/invoice-details.blade.php
> +                    </div>
I see `<label for="conversion_rate"` but couldn't find `<input id="conversion_rate"` in the `input` tag. What is the purpose of `for` attribute in `label` tag?

2021-08-06 16:16 UTC, kuldeep3 commented on database/migrations/2021_07_26_141927_adding_conversion_rate_column.php
> +class AddingConversionRateColumn extends Migration
```suggestion
class AddConversionRateColumn extends Migration
```

2021-08-06 16:23 UTC, GauravGusain98 commented on database/migrations/2021_07_26_141927_adding_conversion_rate_column.php
> +            $table->string('conversion_rate');
Why is this column of type string? If it's some numeric value then you should assign the type accordingly. Check [here](https://laravel.com/docs/8.x/migrations#available-column-types) for all available column types in Laravel. 

Also confirm if this column can be nullable or not. If it can then make this column as nullable.

2021-08-06 16:29 UTC, GauravGusain98 requested changes
Left some feedbacks. Please take a look and fix them accordingly.

2021-08-06 16:29 UTC, GauravGusain98 commented on database/migrations/2021_07_26_141927_adding_conversion_rate_column.php
> +        });
Why is this column of type string? If it's some numeric value then you should assign the type accordingly. Check here for all available column types in Laravel.

Also, confirm if this column can be nullable or not. If it can then make this column nullable.

2021-08-06 16:29 UTC, GauravGusain98 commented on database/migrations/2021_07_26_141927_adding_conversion_rate_column.php
> +class AddingConversionRateColumn extends Migration
Please check if the naming convention is correct. I think we don't use present continuous tense while naming a file or class. You can take help from other migrations names. Like `2020_09_08_073651_add_hr_university_id_to_hr_applicants_table.php`

2021-08-06 17:30 UTC, abhinav80066 commented on Modules/Invoice/Resources/views/subviews/edit/invoice-details.blade.php
> +                    </div>
I used d-flex and ``` for ``` attribute in ```label``` tag because they are used in all the other fields in the form and I tried to follow the same structure.

2021-08-06 17:38 UTC, abhinav80066 commented on database/migrations/2021_07_26_141927_adding_conversion_rate_column.php
> +        });
This column is of type string because I saw that there is a similar column conversion_rate_diff of type string. I will confirm if this column can be nullable or not and make the changes accordingly.

2021-08-06 17:40 UTC, abhinav80066 commented on database/migrations/2021_07_26_141927_adding_conversion_rate_column.php
> +class AddingConversionRateColumn extends Migration
Okay, I will rename the class according to the naming convention.

2021-08-13 15:47 UTC, rathorevaibhav commented
@abhinav80066 any update on this? Is it ready for review or are there any changes remaining? If it's ready, please add label.

2021-08-14 06:48 UTC, abhinav80066 commented
> @abhinav80066 any update on this? Is it ready for review or are there any changes remaining? If it's ready, please add label.

Yes, It is ready to review. I will add the label.

2021-08-16 04:31 UTC, GauravGusain98 requested changes
Please check the comments and make the required changes.

2021-08-16 04:31 UTC, GauravGusain98 commented on Modules/Invoice/Resources/views/subviews/edit/invoice-details.blade.php
> +                    </div>
Your answer is not relevant to the question @kuldeep3 asked. You can google search the purpose of `for` attribute and its use and then you can understand better what Kuldeep is asking.

2021-08-16 04:31 UTC, GauravGusain98 commented on database/migrations/2021_07_26_141927_adding_conversion_rate_column.php
> +            $table->decimal('conversion_rate' 10, 2)->nullable();
In the issue, I see that conversion rate is a required field. So why it is nullable database here. You can once confirm the requirement. If the conversion rate is required field then fix this.

2021-08-30 05:44 UTC, gaurish-saini commented on Modules/Invoice/Resources/views/subviews/edit/invoice-details.blade.php
> +                        <label for="client_id" class="mr-4 pt-1 field-required">Conversion Rate:</label>
@pankaj-ag Resolved in the latest commit.

2021-08-30 05:46 UTC, gaurish-saini commented on Modules/Invoice/Resources/views/subviews/edit/invoice-details.blade.php
> +                    </div>
> Is d-flex required? What will happen if I only do this?

@kuldeep3 Removing `d-flex` disturbs the UI as it the input field comes below the label.

2021-08-30 05:47 UTC, gaurish-saini commented on Modules/Invoice/Resources/views/subviews/edit/invoice-details.blade.php
> +                    </div>
> I see `<label for="conversion_rate"` but couldn't find `<input id="conversion_rate"` in the `input` tag. What is the purpose of `for` attribute in `label` tag?

Resolved in this commit https://github.com/ColoredCow/portal/pull/856/commits/57553d9d9084cb90827045c707c18cde5ab17815

2021-08-30 05:49 UTC, gaurish-saini commented on database/migrations/2021_07_26_141927_adding_conversion_rate_column.php
> +            $table->decimal('conversion_rate' 10, 2)->nullable();
@GauravGusain98 Agreed conversion rate is a required field for international clients, resolved in this commit https://github.com/ColoredCow/portal/pull/856/commits/57553d9d9084cb90827045c707c18cde5ab17815

2021-08-30 15:54 UTC, GauravGusain98 requested changes
Please check the comments

2021-08-30 15:54 UTC, GauravGusain98 commented on Modules/Invoice/Resources/views/subviews/edit/invoice-details.blade.php
> +
You have added an input field. But how is this data being saved in the database, as I don't see any backend changes.

2021-08-30 19:52 UTC, gaurish-saini commented on Modules/Invoice/Resources/views/subviews/edit/invoice-details.blade.php
> +
`conversion_rate` has already been added to the fillables.

2021-08-31 04:48 UTC, GauravGusain98 commented on Modules/Invoice/Resources/views/subviews/edit/invoice-details.blade.php
> +
I mean, there might be a backend code in the controller, where this data is going. There as well you need to do some changes for adding this `conversion_rate` field to the database.  It's not like I am sending the data from front end and it will directly be saved in the database.

2021-08-31 06:56 UTC, gaurish-saini commented on Modules/Invoice/Resources/views/subviews/edit/invoice-details.blade.php
> +
According to the current flow, as it has been already added to the fillable it is saving the conversion rate in the database.

2021-08-31 06:59 UTC, gaurish-saini commented on database/migrations/2021_07_26_141927_adding_conversion_rate_column.php
> +            $table->decimal('conversion_rate' 10, 2)->nullable();
I have updated the issue description here https://github.com/ColoredCow/portal/issues/814. Let me know your thoughts.

2021-08-31 16:28 UTC, GauravGusain98 commented
@gaurish-saini 
Please resolve the merge conflicts. Also, test the functionality once more as the merge conflicts may affect the workflow.

2021-08-31 17:42 UTC, gaurish-saini commented
> @gaurish-saini
> Please resolve the merge conflicts. Also, test the functionality once more as the merge conflicts may affect the workflow.

@GauravGusain98 Resolved in the latest commit.

2021-09-14 07:03 UTC, rathorevaibhav commented
Stale PR. Closing.

2021-09-14 07:03 UTC, closed without merging