Opportunity delete when update any opportunity
ColoredCow/portal pull request #857
Opened 2021-07-28 18:31 UTC by am-Anmol

Target #845 
## Summary
1. This bug is coming because there have been nesting of two forms one is for `update` and another one is for `delete`, so once we are clicking on the update button it's considering submitting for the delete button.
2. So changed nested to multiple forms.
3. And make that div to flexbox with some left margin to it.

2021-07-30 20:42 UTC, rathorevaibhav requested changes

2021-07-30 20:42 UTC, rathorevaibhav commented on resources/views/hr/job/edit.blade.php
> +            </form>
This isn't the right place to close this form. All child tags within this must be closed. However, you see the `<div>` tag isn't closing.

```html
<div class="d-flex"> <!-- this must close before form as it is a child element -->
    <button type="submit" class="btn btn-primary ml-2">Update</button>
    </form>
```

2021-07-31 07:37 UTC, am-Anmol commented
## Summary
1. Added `form` attribute in submit button and assigned respective `id` to forms tag.
For more details on how to nest form in HTML5, please refer to this https://www.vivait.com.au/nested-forms-using-html5.

2021-07-31 12:01 UTC, rathorevaibhav approved these changes

2021-07-31 12:04 UTC, merged