Update prerequisites.md
ColoredCow/portal pull request #859
Opened 2021-07-30 11:09 UTC by RohitDhingra27

## Summary
Updated  Installation guide in case the user prefers working on WAMP server.

2021-07-30 20:57 UTC, rathorevaibhav requested changes
@RohitDhingra27 please check the feedbacks.

2021-07-30 20:57 UTC, rathorevaibhav commented on docs/prerequisites.md
> +    - If you prefer using WAMP, you can download from [this link](https://www.wampserver.com/en/download-wampserver-64bits)
you faced issues while setting up WAMP. Please add what commands you ran and what errors you saw.

This doesn't ensure a new person installing the project will be able to comfortably resolve the issues you faced. Documentation is always for new people, so please make sure someone else shouldn't struggle as same as you did in WAMP.

2021-07-31 11:33 UTC, rathorevaibhav requested changes

2021-07-31 11:33 UTC, rathorevaibhav commented on docs/prerequisites.md
> +    - Command to run, composer update.
```suggestion
    A possible error that may arise with openSSL extension. It should be enabled from your `php.ini` file. To enable it, use the following steps:
    - Edit the system environment variables and set the path of your selected PHP version.
    - In `php.ini`, uncomment the ";extension=openssl" by removing ";" before it and then restart the apache services.
    - Run this command:
       ```sh
       composer update
       ```
```

2021-07-31 11:33 UTC, rathorevaibhav commented on docs/prerequisites.md
Some questions @RohitDhingra27 : 
1. Which directory should composer update need to run?
2. You said there was issue with VSCode also. Do you think that should also be mentioned?
3. Don't you need to restart WAMP after updating `php.ini` file? If yes, please mention that as well.

2021-07-31 11:33 UTC, rathorevaibhav commented on docs/prerequisites.md
> +    -Edit the system environment variables and set the path of your selected php version.
please add the steps for this also. Or a link to an article that you followed in your case.

2021-07-31 11:33 UTC, rathorevaibhav commented
@RohitDhingra27 please ensure the markdown file is properly formatted. You can check here:
https://dillinger.io/

2021-08-02 11:26 UTC, P4NK4J commented on docs/prerequisites.md
> +   - The WAMP users have to right click on the server icon in the toolbar, and choose ‘Restart all services’ after making changes to the 'php.ini' file.
@RohitDhingra27, Do you think we should also mention restarting Apache for XAMPP users, in case if they face any issues?

2021-08-03 05:09 UTC, RohitDhingra27 commented on docs/prerequisites.md
> +   - The WAMP users have to right click on the server icon in the toolbar, and choose ‘Restart all services’ after making changes to the 'php.ini' file.
Yes, so we should mention about it inside the XAMPP section. But I was not sure since I am working on WAMP.

2021-08-04 10:35 UTC, P4NK4J reviewed
Left some comments, please have a look.

2021-08-04 10:35 UTC, P4NK4J commented on docs/prerequisites.md
> +   - Run this command in the top-most directory of your project:
```suggestion
   - Run this command in the root directory of your project:
```

2021-08-04 10:35 UTC, P4NK4J commented on docs/prerequisites.md
@RohitDhingra27 , Could you answer these questions ? currently, it's not clear whether you worked on these feedbacks or not.

2021-08-04 10:47 UTC, RohitDhingra27 commented on docs/prerequisites.md
> +    - Command to run, composer update.
I have made the requested changes. Thank you.

2021-08-04 10:53 UTC, RohitDhingra27 commented on docs/prerequisites.md
I added these things while updating the pre-requisites and mentioned about this within the additional comment box.

2021-08-06 12:39 UTC, P4NK4J commented
@RohitDhingra27 I can see ready for review label is attached to the PR, but I see there is no assignee in the reviewer. If the PR is ready to review, please assign this to team-portal reviewers for taking it forward.

2021-08-13 15:49 UTC, rathorevaibhav commented
@P4NK4J can you finish the remaining changes on this when you have time and merge?

Also, I see this will get outdated by #801 but when that issue will be worked upon is not clear.

2021-08-16 07:52 UTC, P4NK4J commented
Currently, looks good with the installation steps. In case there is any error while installation for a specific case, it can be updated then again. Hence, merging the PR here.

2021-08-16 07:53 UTC, merged