Correction in Readme
ColoredCow/portal pull request #861
Opened 2021-07-31 06:53 UTC by kickb71

Correction's in the installation file is completed.

2021-07-31 11:59 UTC, rathorevaibhav requested changes

2021-07-31 11:59 UTC, rathorevaibhav commented on app/Http/Controllers/DashboardController.php
> +<?php
I don't think this file is needed in this Pull Request. This PR should only include changes related to readme.

2021-07-31 11:59 UTC, rathorevaibhav commented on docs/installation.md
> +Go to your php.ini file(C:\xampp\php)
```suggestion
3. Enable the OpenSSL extension. Go to your php.ini file (C:\xampp\php)
```

2021-07-31 11:59 UTC, rathorevaibhav commented on docs/installation.md
> +Search for openssl,
```suggestion
Search for openssl
```

2021-07-31 11:59 UTC, rathorevaibhav commented on docs/installation.md
> +3. Change's in the php.ini file,
I think this shouldn't be part of installation, but rather pre-requisites file. When setting up XAMPP.

2021-07-31 11:59 UTC, rathorevaibhav commented on resources/views/graph.blade.php
> +@extends('layouts.app')
this file shouldn't be in this Pull Request.

2021-08-01 18:03 UTC, kickb71 commented on resources/views/graph.blade.php
> +@extends('layouts.app')
Okay sir

2021-08-01 18:03 UTC, kickb71 commented on app/Http/Controllers/DashboardController.php
> +<?php
Okay sir

2021-08-02 06:10 UTC, kickb71 commented
The files have been changed sir

2021-08-03 05:10 UTC, kuldeep3 requested changes
The PR says correction in Readme, although I can see other files too that are not required in this PR. Moreover, there is a conflicting file. Please resolve the conflicts and remove the files that are not required in this PR before assigning it for review.

2021-08-06 06:33 UTC, closed without merging