Dashboard
ColoredCow/portal pull request #866
Opened 2021-08-05 10:06 UTC by kickb71

2021-08-05 12:31 UTC, kickb71 commented
The date icon has not be been moved

2021-08-05 12:47 UTC, kuldeep3 requested changes
@kickb71 Please describe the PR and add a link to the issue so that reviewer can be aware of what the PR is all about. Right now, it's quite hard to understand what changes are proposed in the PR. Moreover, please resolve the conflicts first and then assign it for review.

2021-08-05 12:50 UTC, kickb71 commented
I did not know any thing about these conflict and the PR link to this issue is
https://github.com/ColoredCow/portal/issues/811

2021-08-05 12:57 UTC, P4NK4J commented
@kickb71 , There are some merge conflicts in this PR, maybe you need to take a pull from the master branch and resolve them. In your previous comment, I think you wanted to share the issue linked with the PR. 

Also, the issue description is for what we want to achieve, and in the PR description, you need to mention what changes you did to achieve the desired functionality (described in the issue).

Let me know if that makes sense, or if you have any questions.

2021-08-05 12:59 UTC, kickb71 commented
These issues are not from my file which is ready for pull request.

2021-08-05 13:01 UTC, P4NK4J commented
Probably you should get an understanding of what merge conflicts are, how they appear and how you can resolve them. Here is a [link](https://docs.github.com/en/github/collaborating-with-pull-requests/addressing-merge-conflicts/about-merge-conflicts) for reference.

2021-08-05 13:07 UTC, GauravGusain98 commented
@kickb71 
Remember, whenever you make a PR please write a description about the changes you have made and issue you resolved. For reference you can take help from this image 

![image](https://user-images.githubusercontent.com/54376313/128354973-d373b707-7d2a-4bfe-9ab8-4e67efe8eb83.png)

2021-08-06 13:23 UTC, GauravGusain98 requested changes

2021-08-06 13:23 UTC, GauravGusain98 commented on app/Sql.php
> +}
This file is not needed as there is already a model for this table. You have to use that model. Here is the path of that model `Modules\HR\Entities\Applicant.php`

2021-08-06 13:23 UTC, GauravGusain98 commented on app/Http/Controllers/DashboardController.php
> +    $today_count = Sql::whereDate('created_at', '=',now())
Please use meaningful variable names. Also, we don't use `snake_case` naming convention in Laravel. Please use `camelCase` for naming variables and functions.

2021-08-06 15:57 UTC, kickb71 commented on app/Http/Controllers/DashboardController.php
> +    $today_count = Sql::whereDate('created_at', '=',now())
Okay Sir i will change

2021-08-06 16:01 UTC, kickb71 commented on app/Sql.php
> +}
I need this to leave out time stamp of all the data from database

2021-08-06 16:08 UTC, GauravGusain98 commented on app/Sql.php
> +}
I didn't get what you mean by `leave out timestamp of all the data from database`. But whatever the case is, you don't need this file as it is not a good practice to have multiple files/functions for the same purpose. 

If you want to make some changes then you can do that in the `Applicant.php`. Also if you have used this model at other places, then please correct them as well.

2021-08-07 06:58 UTC, kickb71 commented on app/Sql.php
> +}
All the entry in the database is  like this for July 2nd (02-07-2021 10:34:54)  I want to remove last and display as (02-07-2021) in the chart that's why.

2021-08-09 06:46 UTC, kickb71 commented
@ColoredCow/team-portal-reviewers  This PR is ready for review

2021-08-09 07:07 UTC, GauravGusain98 commented on app/Sql.php
> +}
I am not sure what you are trying to do, please describe that thing in the description clearly. 

Also, the approach you are taking is incorrect. Whatever the issue is but a table should not have more than one model.

2021-08-09 09:04 UTC, kickb71 commented on app/Sql.php
> +}
I have changed it as per you suggested and will update the final out put now!

2021-08-09 09:07 UTC, closed without merging

2021-08-09 10:00 UTC, P4NK4J commented
@kickb71 , Not sure why this PR closed after adding the ready-to-review comment. Please explain the purpose of status inconsistencies and closure of this PR.

2021-08-09 10:14 UTC, kickb71 commented
All my files in tge local is deleted that's why i have created a new one