Updated the PR template
ColoredCow/portal pull request #869
Opened 2021-08-06 13:38 UTC by GauravGusain98

## Summary
The current PR template is not being followed properly, many PRs don't have descriptions in them. Therefore, updated the PR template for improving the quality of PRs.

2021-08-06 15:22 UTC, rathorevaibhav requested changes

2021-08-06 15:22 UTC, rathorevaibhav commented on .github/PULL_REQUEST_TEMPLATE.md
> +- [ ] The code follows the style guidelines of this project.
this might not be needed as we have CI checks to detect if coding standards were followed or not.

2021-08-06 15:22 UTC, rathorevaibhav commented on .github/PULL_REQUEST_TEMPLATE.md
> +### Please complete the following steps and check these boxes before filing your PR:
This heading shouldn't show up in the description

2021-08-06 15:22 UTC, rathorevaibhav commented on .github/PULL_REQUEST_TEMPLATE.md
> +#[ISSUE_ID]
This just puts focus on the issue id with an H1 tag. Probably lets have it without the H1 tag
```suggestion
Targets #{ISSUE_ID}
```

2021-08-06 15:22 UTC, rathorevaibhav commented on .github/PULL_REQUEST_TEMPLATE.md
>  Explain the **motivation** for making this change. What existing problem does the pull request solve?
Somehow this was incorrectly set before. This whole like needs to be a comment I believe.

2021-08-06 15:58 UTC, kuldeep3 approved these changes
LGTM 👍🏽 Please make the update as per suggestion before merging.

2021-08-06 15:58 UTC, kuldeep3 commented on .github/PULL_REQUEST_TEMPLATE.md
> +<!--- Why these change are required? What existing problem does the pull request solve? -->
```suggestion
<!--- Why these changes are required? What existing problem does the pull request solve? -->
```

2021-08-09 10:30 UTC, P4NK4J approved these changes
Looks good to me.

2021-08-09 10:30 UTC, merged