Resolved PHP-CS Errors
ColoredCow/portal pull request #870
Opened 2021-08-06 18:37 UTC by am-Anmol

Target #851 
## Summary
Resolved all errors occurring according to PHP- Coding Standards.

**References**
https://github.com/FriendsOfPHP/PHP-CS-Fixer

2021-08-07 08:02 UTC, am-Anmol commented
## Summary
1. All Php-cs errors resolved according to PHP- Coding Standards.
2. Exclude `node_modules` directories  `.php-cs-fixer.php`.

**For more reference to the Configuration file in PHP-CS fixer:**
https://github.com/FriendsOfPHP/PHP-CS-Fixer/blob/3.0/doc/config.rst

2021-08-08 05:07 UTC, GauravGusain98 requested changes
Some minor changes are requested. Please have them fix.

2021-08-08 05:07 UTC, GauravGusain98 commented on public/lib/fullcalendar/examples/php/utils.php
> +    public $allDay; // a boolean
This indentation is not matching with the indentation of other variables. Please fix it the indentation in other variables as well

2021-08-08 07:22 UTC, am-Anmol commented on Modules/HR/Database/Seeders/HRRoundsTableSeeder.php
> -            array (
These changes are requested in the `PHP-CS fixer`, that's why replaced `array` function with `[ ]`.`

2021-08-08 07:28 UTC, am-Anmol commented on app/Http/Controllers/HomeController.php
> +        if (count($groups)) {
These changes are requested in the `PHP-CS fixer` because as per PHP official documentation, there is no difference between `count` and `sizeof` function. The `sizeof` function is just the alias of the `count` function. That means the `sizeof` uses the same as the `count` function underneath.

2021-08-08 07:50 UTC, am-Anmol commented on public/lib/fullcalendar/examples/php/utils.php
> +    public $allDay; // a boolean
Ok I make these changes.

2021-08-09 11:08 UTC, am-Anmol commented on Modules/HR/Database/Seeders/HRRoundsTableSeeder.php
> -            array (
These changes are required because the only difference in using `[ ]` or `array()` is with the version of PHP you are using. In PHP version more than 5.4, you can also use the short array syntax, which replaces `array()` with `[ ]`.

2021-08-09 11:30 UTC, P4NK4J approved these changes
Looks good to me.

2021-08-10 04:40 UTC, GauravGusain98 approved these changes
Looks good to me.

2021-08-11 03:50 UTC, merged