PHP artisan error
ColoredCow/portal pull request #876
Opened 2021-08-08 07:43 UTC by kickb71

If I run this command ("php artisan route:cache") it shows error message in the terminal

I have corrected and rectified all the files have been corrected which is causing the error's not to run this command.

Issue no:#848 (https://github.com/ColoredCow/portal/issues/848)

2021-08-09 10:29 UTC, P4NK4J reviewed
Minor questions, let me know what you think.

2021-08-09 10:29 UTC, P4NK4J commented on routes/web.php
> +            Route::put('roles/{id}', 'PermissionController@updateRolePermissions')->name('permissions.module.role');
@kickb71 , I think the route name should specify what it's intending to. Can we rename this route to `role-update`, The name `role` seems quite generic. Let me know your thoughts.

2021-08-09 12:04 UTC, kickb71 commented on routes/web.php
> +            Route::put('roles/{id}', 'PermissionController@updateRolePermissions')->name('permissions.module.role');
That is what causing the error sir 
I have changed in the permisson controller to

2021-08-10 04:01 UTC, GauravGusain98 requested changes
Please check the comments and make the necessary changes.

2021-08-11 03:55 UTC, kickb71 commented on routes/web.php
> +            Route::put('roles/{id}', 'PermissionController@updateRolePermissions')->name('permissions.module.role');
I will change the name to "permission.module.update.role" is that fine sir?

2021-08-11 13:28 UTC, GauravGusain98 commented on routes/web.php
> +            Route::put('roles/{id}', 'PermissionController@updateRolePermissions')->name('permissions.module.role');
You can use `permission.module.update-role`

2021-08-11 13:30 UTC, GauravGusain98 commented on routes/web.php
> +            Route::put('roles/{id}', 'PermissionController@updateRolePermissions')->name('permissions.module.role');
Also, does this route being used anywhere in the codebase? I can't see any changes related to the route name in the files from where this route is being called.

2021-08-11 17:49 UTC, GauravGusain98 requested changes
Some minor changes required. Please make the changes and confirm if the routes are in use anywhere or not.

2021-08-11 17:49 UTC, GauravGusain98 commented on app/Http/Controllers/Settings/PermissionController.php
>          $validatedData = $request->validated();
Revert these changes. They are not required. The old code is correct. 

Also, the name inside the authorize function is not the name of the route. It is the name of the function that is defined in the policy file. But for now, just revert these changes.

2021-08-11 17:49 UTC, GauravGusain98 commented on routes/web.php
> +            Route::put('roles/{id}', 'PermissionController@updateRolePermissions')->name('permissions.module.update.role');
I see that these 2 routes are not used anywhere in the codebase. Not sure why they were added. Do you know where these routes are used? 

Also, you can use the name `permissions.module.update-role` for the route

2021-08-12 02:47 UTC, kickb71 commented on app/Http/Controllers/Settings/PermissionController.php
>          $validatedData = $request->validated();
If we revert these changes we get error when we run the 'php artisan route:cache' command.

2021-08-12 02:47 UTC, kickb71 commented on routes/web.php
> +            Route::put('roles/{id}', 'PermissionController@updateRolePermissions')->name('permissions.module.update.role');
yes I can change the name to "permissions.module.update-role"

2021-08-12 02:49 UTC, kickb71 commented on routes/web.php
> +            Route::put('roles/{id}', 'PermissionController@updateRolePermissions')->name('permissions.module.role');
yes it is used in the "settings->permission->role.blade.php"

2021-08-12 04:14 UTC, GauravGusain98 commented on routes/web.php
> +            Route::put('roles/{id}', 'PermissionController@updateRolePermissions')->name('permissions.module.role');
Got it. I see that the URL is being used here. So for now, you can just change the name or route to `permission.module.update-role`.

2021-08-12 04:15 UTC, GauravGusain98 commented on app/Http/Controllers/Settings/PermissionController.php
>          $validatedData = $request->validated();
No, it will not throw an error. Just try it.

2021-08-12 04:15 UTC, GauravGusain98 commented on routes/web.php
> +            Route::put('roles/{id}', 'PermissionController@updateRolePermissions')->name('permissions.module.update.role');
yeah

2021-08-12 09:35 UTC, kickb71 commented on app/Http/Controllers/Settings/PermissionController.php
>          $validatedData = $request->validated();
I have tried it
<img width="720" alt="error" src="https://user-images.githubusercontent.com/73119570/129174629-fa20812e-6a46-4a7b-80b0-7ff8643e5cd8.PNG">

2021-08-12 14:03 UTC, GauravGusain98 commented on app/Http/Controllers/Settings/PermissionController.php
>          $validatedData = $request->validated();
I told you to just revert the changes of the PermissionController file. The route names were correct.

2021-08-13 15:31 UTC, GauravGusain98 approved these changes
Looks good to me.

2021-08-13 15:56 UTC, rathorevaibhav commented
@GauravGusain98 do we need another review on this or it's good to merge? If good to merge, then please merge it after approval. For other PRs, also.

2021-08-13 17:26 UTC, GauravGusain98 commented
> @GauravGusain98 do we need another review on this or it's good to merge? If good to merge, then please merge it after approval. For other PRs, also.

Sure, I'll do this from now onwards.

2021-08-13 17:26 UTC, merged