Dashboard
ColoredCow/portal pull request #877
Opened 2021-08-09 09:30 UTC by kickb71

Expected Behavior
To create the dashboard page with charts as per the design.
The calendar icon should be on left.

Current Behavior:
I have assigned to create a bar chart where it displays total number of Application received for the past 7 days.

Changes:
I have created the bar chart as expected and also added date picker function. 
The calendar icon is on the left because it cant be done.
Also used the design as a reference to create a bar chart.

Issue no #811

2021-08-12 02:20 UTC, kickb71 commented on app/Http/Controllers/DashboardController.php
> +        $data['chart_data'] = json_encode($data);
This JSON encode is used to pass the data into the chart's value.

2021-08-12 02:21 UTC, kickb71 commented on docs/installation.md
> +-## Installation Guidelines :rocket:
I am changing it sir

2021-08-12 02:23 UTC, kickb71 commented on config/database.php
> +            'strict' => false,
I think Yes, it is not required I changed it because of a error I have rectified it.

2021-08-12 04:39 UTC, GauravGusain98 requested changes
Please do the changes requested.

2021-08-12 04:39 UTC, GauravGusain98 commented on composer.json
> +        }
Are the changes in this file related to charts?

2021-08-12 04:39 UTC, GauravGusain98 commented on docs/installation.md
> +   composer install
Are the changes in this file related to this feature Or you have just corrected this thing while making the feature?

2021-08-12 04:39 UTC, GauravGusain98 commented on resources/views/graph.blade.php
> +   <link href="{{ asset('css/app.css') }}" rel="stylesheet">
Correct the indentation

2021-08-12 04:39 UTC, GauravGusain98 commented on resources/views/graph.blade.php
> +<br>
Give one line space after `<br>` tag. You should use a formatter plugin to format the document

2021-08-12 04:39 UTC, GauravGusain98 commented on resources/views/graph.blade.php
> +                //bodyFontColor:"#E0DEDE",
Remove these comments if they are not used.

2021-08-12 04:39 UTC, GauravGusain98 commented on resources/views/graph.blade.php
> +            }
Why this javascript code is written inside the blade file? We have `app.js` for this purpose. Please correct this.

2021-08-12 04:39 UTC, GauravGusain98 commented on resources/views/welcome.blade.php
> -@extends('layouts.app')
Why you removed this?

2021-08-12 04:39 UTC, GauravGusain98 commented on app/Http/Controllers/DashboardController.php
> +    ->get();
Correct the formatting
```suggestion
        $todayCount = Applicant::whereDate('created_at', '=', now())
            ->count();
        
        $record = Applicant::select(\DB::raw("COUNT(*) as count"), \DB::raw("MONTHNAME(created_at) as month"), \DB::raw("DATE(created_at) as date"))
            ->where('created_at', '>', Carbon::today()->subDay(7))
            ->groupBY('date')
            ->orderBy('date', 'ASC')
            ->get();
```

2021-08-12 04:39 UTC, GauravGusain98 commented on app/Http/Controllers/DashboardController.php
> +
Correct the formatting

2021-08-12 06:52 UTC, kickb71 commented on composer.json
> +        }
Yes sir.

2021-08-12 06:54 UTC, kickb71 commented on resources/views/graph.blade.php
> +   <link href="{{ asset('css/app.css') }}" rel="stylesheet">
These indentation are as per GitHub styles

2021-08-12 06:55 UTC, kickb71 commented on resources/views/graph.blade.php
> +                //bodyFontColor:"#E0DEDE",
These are commented because of the design let me change it

2021-08-12 06:55 UTC, kickb71 commented on resources/views/graph.blade.php
> +            }
sure sir

2021-08-12 06:55 UTC, kickb71 commented on resources/views/welcome.blade.php
> -@extends('layouts.app')
I did not remove it

2021-08-13 15:40 UTC, GauravGusain98 commented on resources/views/welcome.blade.php
> -@extends('layouts.app')
So why this change is showing

2021-08-13 15:50 UTC, GauravGusain98 requested changes
Please check the comments

2021-08-13 15:50 UTC, GauravGusain98 commented on resources/views/graph.blade.php
> +<br>
This is not a way we use <head> in laravel. The head is included using the @extends() function which is used in line 1. Please check the `app.blade` file and add the content of the head section there.

2021-08-13 15:50 UTC, GauravGusain98 commented on resources/views/graph.blade.php
> +      </script>
You have to add these lines in `app.js` file. All the JS scripts that are used in a project are written inside the app.js file. 

It is just like you add a js file in HTML instead of writing the JS script inside the HTML.

2021-08-16 10:27 UTC, kickb71 commented on resources/views/graph.blade.php
> +      </script>
I am unable to change this file because of it is not passing the data from controller.

2021-08-16 15:45 UTC, GauravGusain98 commented
Please correct the formatting. Take reference from `continuous-integration/styleci/pr` check results.

2021-08-17 04:15 UTC, GauravGusain98 requested changes
Please check the comments.

2021-08-17 04:15 UTC, GauravGusain98 commented on resources/views/graph.blade.php
> +</head>
If you have already included these lines in the `app.blade` file. Then you don't need them here again.

2021-08-17 04:15 UTC, GauravGusain98 commented on resources/views/welcome.blade.php
> -@extends('layouts.app')
What about this?

2021-08-17 04:15 UTC, GauravGusain98 commented on resources/js/app.js
> +	  }
The indentation is not looking correct to me. It should be a tab or 4 spaces instead of 2 spaces

2021-08-17 04:15 UTC, GauravGusain98 commented on resources/views/graph.blade.php
> +<body>
Please correct indentation in this file as well

2021-08-17 04:15 UTC, GauravGusain98 commented on resources/views/graph.blade.php
> +      </script>
You need to find a way to pass a PHP variable to JS.

2021-08-17 04:41 UTC, kickb71 commented on resources/views/welcome.blade.php
> -@extends('layouts.app')
I don't know and I have changed it

2021-08-17 04:43 UTC, kickb71 commented on resources/views/graph.blade.php
> +<br>
yes I will change it

2021-08-17 06:28 UTC, kickb71 commented on resources/views/graph.blade.php
> +      </script>
I found it but the format is changing

2021-08-17 06:38 UTC, kickb71 commented on resources/views/graph.blade.php
> +      </script>
it is changing the format of values

2021-08-17 07:11 UTC, kickb71 commented on resources/js/app.js
> +	  }
done I will change it

2021-08-17 07:12 UTC, kickb71 commented on resources/views/graph.blade.php
> +<body>
sure

2021-08-17 07:12 UTC, kickb71 commented on resources/views/graph.blade.php
> +</head>
okay

2021-08-18 01:22 UTC, kickb71 commented
@GauravGusain98 This issue(https://github.com/ColoredCow/portal/pull/877#discussion_r690020793) cant be changed into JavaScript because passing variable from PHP to JavaScript is changing the format of the value stored.

2021-08-18 02:21 UTC, GauravGusain98 requested changes
Please check the comments

2021-08-18 02:21 UTC, GauravGusain98 commented on resources/views/graph.blade.php
> +<body>
This is not done. Please correct the indentation in this whole file.

2021-08-18 02:21 UTC, GauravGusain98 commented on resources/views/welcome.blade.php
> -@extends('layouts.app')
This file is deleted. You need to make a new file and then add line 1 to it.

2021-08-18 02:21 UTC, GauravGusain98 commented on app/Http/Controllers/HR/DashboardController.php
> +<?php
@rathorevaibhav Could you please review this file? It is looking OK to me.

2021-08-18 02:23 UTC, GauravGusain98 commented on resources/views/graph.blade.php
> +<body>
Also, check how to fetch PHP variable data from js and write the script section in app.js.

2021-08-18 09:57 UTC, kickb71 commented
@GauravGusain98  should where should I add the JavaScript in public or resources app file?

2021-08-18 13:09 UTC, GauravGusain98 commented
> @GauravGusain98 should where should I add the JavaScript in public or resources app file?

For every module you have to use the app.js inside of resource one.

2021-08-18 19:00 UTC, GauravGusain98 requested changes
Please check the comments

2021-08-19 02:01 UTC, kickb71 commented on resources/views/graph.blade.php
> +      </script>
okay I will take care of it.

2021-08-19 14:26 UTC, kickb71 commented on resources/views/graph.blade.php
> +      </script>
@GauravGusain98  
 I have looked into it we must definitely use one script tag to pass the data to java script 
 I have tried so many ways 
By URL method it is not possible to pass the chart data.
even verbatim method 
The sample format of the data is : {"data":[1],"label":["2021-08-12"]}
I Don't know how to convert to this format in JavaScript .

2021-08-19 14:39 UTC, kickb71 commented on resources/js/app.js
> +$(function(){
Okay

2021-08-19 14:39 UTC, kickb71 commented on resources/js/app.js
> +$(function(){
okay

2021-08-19 14:48 UTC, GauravGusain98 requested changes
Please check these comments as well.

2021-08-19 14:48 UTC, GauravGusain98 commented on resources/welcome.blade.php
> +@extends('layouts.app')
This file was supposed to be inside views folder.

2021-08-19 14:48 UTC, GauravGusain98 commented on resources/views/graph.blade.php
> +          <span style="font-size: 35px;">Application Recived</span> &emsp;&emsp; <span style="font-size: 20px;">Today's Count:<?php echo $todayCount; ?></span>
Please remove styling from this line as well.

```suggestion
          <span style="font-size: 35px;">Application Received</span> &emsp;&emsp; <span style="font-size: 20px;">Today's Count:<? php echo $todayCount; ?></span>
```

2021-08-19 14:48 UTC, GauravGusain98 commented on resources/views/graph.blade.php
> +   <div class="line-chart-container" style="width : 1000px">
It's bad practice to use style tag in blade. There are class defined for font sizes (eg. fz-10) and also for width (eg. w-100). You can find the size list in `variables.scss` file. You can take reference from other blade files.

Please correct this everywhere.

2021-08-20 02:14 UTC, kickb71 commented on resources/views/graph.blade.php
> +          <span style="font-size: 35px;">Application Recived</span> &emsp;&emsp; <span style="font-size: 20px;">Today's Count:<?php echo $todayCount; ?></span>
If we add the gap in front of PHP it throws a error

2021-08-20 02:15 UTC, kickb71 commented on resources/views/graph.blade.php
> +   <div class="line-chart-container" style="width : 1000px">
Sure I will correct it

2021-08-21 17:29 UTC, GauravGusain98 requested changes
@kickb71 Please check the suggestions. Also, I was not able to find the page where I can see the chart. Also when I tried to search for `/dashboard` URL then it throws this error. Plesea check this as well
![image](https://user-images.githubusercontent.com/54376313/130330171-6da2b5eb-5d70-4cbf-a4fe-9643dd4c0275.png)

2021-08-22 07:22 UTC, kickb71 commented
> @kickb71 Please check the suggestions. Also, I was not able to find the page where I can see the chart. Also when I tried to search for `/dashboard` URL then it throws this error. Please check this as well
> ![image](https://user-images.githubusercontent.com/54376313/130330171-6da2b5eb-5d70-4cbf-a4fe-9643dd4c0275.png)

@GauravGusain98  It runs perfectly in my local. I don't know what's causing the error.

2021-08-22 07:24 UTC, kickb71 commented
> @kickb71 Please check the suggestions. Also, I was not able to find the page where I can see the chart. Also when I tried to search for `/dashboard` URL then it throws this error. Please check this as well
> ![image](https://user-images.githubusercontent.com/54376313/130330171-6da2b5eb-5d70-4cbf-a4fe-9643dd4c0275.png)

@GauravGusain98  It runs perfectly in my local. I don't know what's causing the error.

2021-08-30 07:34 UTC, kickb71 commented
There are a lot of changes in file deletion of files replaced in the old file its confused so I am closing this pull request opening a new one

2021-08-30 07:34 UTC, closed without merging