Feature/hr jobs/add start and end date
ColoredCow/portal pull request #879
Opened 2021-08-12 03:44 UTC by srivastava-jyoti

Added start_date and end_date fields in hr_jobs module.

2021-08-12 14:15 UTC, GauravGusain98 requested changes
Please check the comment and make the requested changes.

2021-08-12 14:15 UTC, GauravGusain98 commented on Modules/HR/Entities/Job.php
> +    protected $fillable = ['title', 'type', 'domain', 'start_date','description', 'posted_by', 'link','end_date', 'status', 'facebook_post', 'instagram_post', 'twitter_post', 'linkedin_post'];
Fix the formatting.

2021-08-12 14:15 UTC, GauravGusain98 commented on Modules/HR/Http/Controllers/Recruitment/JobController.php
> +            'end_date' =>$validated['end_date'],
Please fix the formatting. You should use `phpfmt` plugin for formatting.

2021-08-12 14:15 UTC, GauravGusain98 commented on Modules/HR/Http/Requests/Recruitment/JobRequest.php
> +                'end_date' =>'required|date',
Same formatting mistake.

2021-08-12 14:15 UTC, GauravGusain98 commented on Modules/HR/Http/Controllers/Recruitment/JobController.php
> +            'end_date' =>$validated['end_date'],
Also if the start_date and end_date is nullable then you should assign null value to it as done in line 75 and 76.

2021-08-12 14:15 UTC, GauravGusain98 commented on database/migrations/2021_08_11_151111_add_start_date_and_end_date_to_hr_jobs.php
> +
Please confirm if these columns should be nullable or not. Also, remove the extra line at line 19.

2021-08-12 14:15 UTC, GauravGusain98 commented on resources/views/hr/job/create.blade.php
> +                    </div>
Please correct the formatting. Also why the `<strongclass="text-danger"></strong>` tag is used if it do not contain any text
```suggestion
                    <div class="col-md-3 form-group">
                        <label for="start_date" class="fz-14 leading-none text-secondary mb-1">Start Date<strong class="text-danger"></strong></label>
                        <input type="date" id="start_date" name="start_date" class="form-control">
                    </div>

                    <div class="col-md-3 form-group">
                        <label for="end_date" class="fz-14 leading-none text-secondary mb-1">End Date<strong class="text-danger"></strong></label>
                        <input type="date" id="end_date" name="end_date" class="form-control">
                    </div>
```

2021-08-12 14:15 UTC, GauravGusain98 commented on resources/views/hr/job/edit.blade.php
> +                    <input type="date" id="end_date" name="end_date" class="form-control">
Same as above

2021-08-12 17:29 UTC, GauravGusain98 commented on resources/views/layouts/app.blade.php
> -</html>
Why this file is removed?

2021-08-12 17:35 UTC, srivastava-jyoti commented on resources/views/layouts/app.blade.php
> -</html>
This was done by mistake. This was the file of second task and I made some changes to it without changing the branch name  and by mistake this was added to current commit. I am reverting the changes.

2021-08-12 17:35 UTC, GauravGusain98 commented on resources/views/hr/job/create.blade.php
> +                        <input type="date" id="start_date" name="start_date" class="form-control">
Can we leave the `start_date` and `end_date empty`? OR is any of these fields should be required? Please confirm.

2021-08-12 17:38 UTC, GauravGusain98 commented on resources/views/hr/job/create.blade.php
> +                        <input type="date" id="start_date" name="start_date" class="form-control">
Also you need to add `old` attribute to input tags so that if any error occurs, the user input should not be lost. Take reference from line 28

2021-08-12 17:40 UTC, GauravGusain98 commented on resources/views/hr/job/edit.blade.php
> +                        <input type="date" id="start_date" name="start_date" class="form-control">
Same feedback. Here the `old` attribute is used in a bit different way. Take reference from line 35.

2021-08-12 17:43 UTC, GauravGusain98 commented on database/migrations/2021_08_11_151111_add_start_date_and_end_date_to_hr_jobs.php
> +            $table->text('end_date')->after('link')->nullable();
Why end_date is of type text instead of date. Please correct it. Also, can you please let me know if these columns should be nullable or not? You can think of the use case and decide if there is any case where these fields can be null.

2021-08-16 11:05 UTC, GauravGusain98 requested changes
Some minor feedbacks. Please check.

2021-08-16 11:05 UTC, GauravGusain98 commented on Modules/HR/Http/Requests/Recruitment/JobRequest.php
> +                'end_date' =>'required|date',
Please fix formatting

2021-08-16 11:05 UTC, GauravGusain98 commented on resources/views/hr/job/edit.blade.php
> +                        <input type="date" class="form-control" id="start_date" name="start_date" value="{{ old('start_date' , $job->start_date)}}">
Please fix formatting
```suggestion
                        <input type="date" class="form-control" id="start_date" name="start_date" value="{{ old('start_date' , $job->start_date) }}">     
```

2021-08-16 11:05 UTC, GauravGusain98 commented on resources/views/hr/job/edit.blade.php
> +                        <input type="date" class="form-control" id="end_date" name="end_date" value="{{ old('start_date' , $job->end_date)}}">
Here as well

2021-08-16 11:08 UTC, GauravGusain98 commented
@srivastava-jyoti,  while giving PR please check if the `continuous-integration/styleci/pr` check if pass or not

2021-08-16 17:02 UTC, srivastava-jyoti commented
I have made the required changes but still continous-integration/styledci/pr is showing wrong tick. And I have tried the solution suggested in details and made changes . Will @GauravGusain98 suggest me where am I lacking??

2021-08-17 04:55 UTC, srivastava-jyoti commented
@GauravGusain98 the formatting problem is sorted now. There was some extra space after the semicolon.

2021-08-18 02:07 UTC, GauravGusain98 requested changes
Please correct the formatting

2021-08-18 02:07 UTC, GauravGusain98 commented on database/migrations/2021_08_11_151111_add_start_date_and_end_date_to_hr_jobs.php
> +            $table->dropColumn(['start_date','end_date']);
```suggestion
            $table->dropColumn(['start_date', 'end_date']);
```

2021-08-18 02:07 UTC, GauravGusain98 commented on resources/views/hr/job/edit.blade.php
>                      </div>
```suggestion
                    <div class="col-md-3 form-group">
                        <label for="start_date" class="fz-14 leading-none text-secondary mb-1">Start Date></label>
                        <input type="date" class="form-control" id="start_date" name="start_date" value="{{ old('start_date', $job->start_date) }}">     
                    </div>
                    <div class="col-md-3 form-group">
                        <label for="end_date" class="fz-14 leading-none text-secondary mb-1">End Date</label>
                        <input type="date" class="form-control" id="end_date" name="end_date" value="{{ old('end_date', $job->end_date) }}">
                    </div>
```

2021-08-18 05:32 UTC, srivastava-jyoti commented on resources/views/hr/job/edit.blade.php
>                      </div>
I have corrected formaating.

2021-08-18 19:09 UTC, GauravGusain98 approved these changes
Looks good to me

2021-08-18 19:09 UTC, merged