#881 Project module schema
ColoredCow/portal pull request #888
Opened 2021-08-13 17:31 UTC by gaurish-saini

Target #881 
### Description

This is an enhancement.
This PR contains the code for 
1. migration to update the `table_name`.
2. addition of foreign key's to `users` & `projects` table
### Checklist:
- [ ] I have performed a self-review of my own code.

2021-08-13 17:34 UTC, GauravGusain98 commented
Remove this line. As it is also a requirement.
https://github.com/ColoredCow/portal/blob/fbc7429b63efb9622a4de44657280808bdfae1d1/Modules/Project/Entities/ProjectResource.php#L10

2021-08-13 17:40 UTC, GauravGusain98 commented
Also, did you check if these changes are affecting any areas? You can once test the sections where the `project_resouce` table is being used for any operation. 

Many relationship functions inside the models we use the table name. So, the old table name might be used in those places, you need to update them as well.

2021-08-13 17:53 UTC, gaurish-saini commented
> Remove this line. As it is also in the requirement.
> https://github.com/ColoredCow/portal/blob/fbc7429b63efb9622a4de44657280808bdfae1d1/Modules/Project/Entities/ProjectResource.php#L10

Resolved in the latest commit.

2021-08-13 17:54 UTC, gaurish-saini commented
> project_resouce

Changes made in the latest commit.

2021-08-13 18:23 UTC, GauravGusain98 requested changes
Please check the comments.

2021-08-13 18:23 UTC, GauravGusain98 commented on Modules/Project/Entities/ProjectResources.php
> +class ProjectResources extends Model
The class name wa correct. In Laravel, the model name is not plural. Based on the model name the framework decide the name of the table by converting it into plural form.

2021-08-13 18:43 UTC, gaurish-saini commented on Modules/Project/Entities/ProjectResources.php
> +class ProjectResources extends Model
Okay noted, made the required changes in the latest commit.

2021-08-14 04:27 UTC, GauravGusain98 requested changes
Please fix the issue mentioned in the comments.

2021-08-14 04:27 UTC, GauravGusain98 commented on database/migrations/2021_08_13_115947_update_project_resource_table.php
> +}
The migration is not working. Please fix it.

![image](https://user-images.githubusercontent.com/54376313/129433908-3fde2e2e-f975-4ad1-be6f-8f099a61da0f.png)

2021-08-16 05:19 UTC, GauravGusain98 commented on database/migrations/2021_08_13_115947_update_project_resource_table.php
> +}
The foreign key column type and the reference table id column type are not matching. In one place its is `bigint unsigned` and in the other place, it is `int unsigned` due to this it is throwing an error on mac. This could be a system-dependent issue. That's why it is not occurring in your system. Please have it fix. Just change the column type according to the reference column.

2021-08-16 06:53 UTC, gaurish-saini commented on database/migrations/2021_08_13_115947_update_project_resource_table.php
> +}
@GauravGusain98 I added a step for this in the latest commit. Let me know if this system-dependent issue still persists.

2021-08-16 06:58 UTC, GauravGusain98 requested changes
Please check the comments

2021-08-16 06:58 UTC, GauravGusain98 commented on database/migrations/2021_08_16_063114_update_project_resource_table.php
> +        });
No, you should not change the type of this column as it can be defined as the foreign key in other tables. By changing this the same error which is occurring here, will then occur in those migrations as well.

2021-08-16 06:58 UTC, GauravGusain98 commented on database/migrations/2021_08_16_063114_update_project_resource_table.php
> +        });
Also, you need to do the same change for `project_id` column.

2021-08-16 07:22 UTC, gaurish-saini commented on database/migrations/2021_08_16_063114_update_project_resource_table.php
> +        });
Resolved in the latest commit.

2021-08-16 10:26 UTC, GauravGusain98 requested changes
Please make the changes

2021-08-16 10:26 UTC, GauravGusain98 commented on database/migrations/2021_08_16_063114_update_project_resource_table.php
> +            $table->bigInteger('resource_id')->change();
Please make these updates after removing foreign keys as it is throwing error while rollback

2021-08-16 13:56 UTC, gaurish-saini commented on database/migrations/2021_08_16_063114_update_project_resource_table.php
> +            $table->bigInteger('resource_id')->change();
Okay got it, seems again a system-dependent issue. It should be resolved in the latest commit.

2021-08-16 15:30 UTC, GauravGusain98 commented on database/migrations/2021_08_16_063114_update_project_resource_table.php
> +            $table->bigInteger('resource_id')->change();
Just remove these two lines as the column type are not getting rollbacked. There is some issue with this. Other things are fine.

2021-08-16 15:34 UTC, GauravGusain98 requested changes
Please make the following changes

2021-08-16 15:34 UTC, GauravGusain98 commented on database/migrations/2021_08_16_063114_update_project_resource_table.php
> +        });
Please update it like this. 

```suggestion
       Schema::table('project_resources', function (Blueprint $table) {
            $table->dropForeign('project_resources_resource_id_foreign');
            $table->dropIndex('project_resources_resource_id_foreign');
            $table->dropForeign('project_resources_project_id_foreign');
            $table->dropIndex('project_resources_project_id_foreign');
        });
        Schema::table('project_resources', function (Blueprint $table) {
            $table->bigInteger('project_id')->change();
            $table->bigInteger('resource_id')->change();
        });
```

2021-08-16 15:36 UTC, GauravGusain98 commented
The old migrations are not getting rollback. There might be some issue with them. Will create a new issue for that.
![image](https://user-images.githubusercontent.com/54376313/129590016-f29ffb09-87f3-4927-8c76-74d06dddd9c0.png)

2021-08-16 15:42 UTC, gaurish-saini commented on database/migrations/2021_08_16_063114_update_project_resource_table.php
> +        });
updated in the latest commit.

2021-08-16 15:43 UTC, GauravGusain98 requested changes
Minor change.

2021-08-16 15:43 UTC, GauravGusain98 commented on database/migrations/2021_08_16_063114_update_project_resource_table.php
> +        Schema::rename( 'project_resources', 'project_resource' );
```suggestion
        Schema::rename('project_resources', 'project_resource');
```

2021-08-16 15:45 UTC, gaurish-saini commented
> The old migrations are not getting rollback. There might be some issue with them. Will create a new issue for that.
> ![image](https://user-images.githubusercontent.com/54376313/129590016-f29ffb09-87f3-4927-8c76-74d06dddd9c0.png)

`php artisan migrate:refresh` works on my end.

2021-08-16 15:46 UTC, GauravGusain98 commented
Please correct the formatting issue shown in `continuous-integration/styleci/pr` check.

2021-08-16 15:47 UTC, GauravGusain98 commented
> Please correct the formatting issue shown in `continuous-integration/styleci/pr` check.

Ignore if done.

2021-08-16 15:48 UTC, GauravGusain98 approved these changes
Looks Good to me.

2021-08-16 15:52 UTC, GauravGusain98 commented
@rathorevaibhav Could you please have a look at this PR. It looks good to me but I am not sure if merging this will run the migration command automatically or not.

2021-08-17 04:40 UTC, rathorevaibhav approved these changes

2021-08-17 04:40 UTC, rathorevaibhav commented
Looking good. Merging.

2021-08-17 04:40 UTC, merged