New Job Opportunity also reflect on ColoredCow Website
ColoredCow/portal pull request #889
Opened 2021-08-13 19:20 UTC by am-Anmol

Targets #794 

### Description
**Job opportunities will `create/update/delete` on the `ColoredCow website` also if updated from `Employee Portal`.**
- Changes made in `Modules/HR/Observers/Recruitment/JobObserver.php` :
     - **`Created` function (working):**
          - Check if `status` is `published` or not, if it is `not` then do nothing.
          - If it is `published` then creating a new entry of data in `wp_post` table with `post_title,post_content,post_type` and a new entry in `wp_postmeta` table with `hr_id` and value of `hr_id` from employee portal `hr_jobs` table.
     - **`Updated` function (working):**
          - Check if `status` is `published` or not, if it is `not` then do nothing.
          - If it is `published` then creating a new entry of data in `wp_post` table with `post_title,post_content,post_type` and a new entry in `wp_postmeta` table with `hr_id` and value of `hr_id` from employee portal `hr_jobs` table.
          - Then finding `post id` by matching `hr_id` in `wp_postmeta` table (Website) with `hr_id` in `hr_jobs` table (employee portal).
          - After that finding an old post with `post id` and deleting the old post.
     - **`Deleted` function (working):**
          - Matching `post_title` and `post_type` with records and deleting the post.
      
- **Prerequisites Required:**
     - Update `config/database.php` with the correct database configurations.
     - ![image](https://user-images.githubusercontent.com/48876126/129408078-df379005-bfcb-48cc-87af-37fb25d625f6.png)

**References:**
Check out the Corcel package to easily create entries in the WordPress database from Laravel
https://github.com/corcel/corcel
### Checklist:

- [ ] I have performed a self-review of my own code.

2021-08-14 04:39 UTC, GauravGusain98 commented on Modules/HR/Observers/Recruitment/JobObserver.php
> +            $Corcel->post_type = 'career';
Please use the value from config files instead of hardcoding. This way if we want to change the value of post_type, we have to only change that in one place instead of changing at every place.

2021-08-14 04:47 UTC, GauravGusain98 requested changes
Please make the suggested changes.

2021-08-14 04:47 UTC, GauravGusain98 commented on Modules/HR/Observers/Recruitment/JobObserver.php
> +            $Corcel->post_type = 'career';
Please use the value from config files instead of hardcoding. This way if we want to change the value of post_type, we have to only change that in one place instead of changing at every place.

2021-08-14 04:47 UTC, GauravGusain98 commented on Modules/HR/Observers/Recruitment/JobObserver.php
> +            $corcel->delete();
This is not looking correct to me as we need to update the record here. But in this case, we are creating a new entry and deleting the old one. Please use the update approach for this.

2021-08-14 07:05 UTC, am-Anmol commented on Modules/HR/Observers/Recruitment/JobObserver.php
> +            $corcel->delete();
OK, I'll update this approach.

2021-08-14 07:35 UTC, am-Anmol commented on Modules/HR/Observers/Recruitment/JobObserver.php
> +            $Corcel->post_type = 'career';
Ok, I make these changes.

2021-08-14 07:47 UTC, am-Anmol commented
**Update function approach:**
- Check if `status` is `published` or not, if it is `not` then do nothing.
- If it is `published` then find `post ID` in `wp_post` table using `job_id`.
- Then finding `post` with `post ID` and updating respective columns.

2021-08-16 04:40 UTC, GauravGusain98 reviewed
Please check the comment

2021-08-16 04:40 UTC, GauravGusain98 commented on Modules/HR/Observers/Recruitment/JobObserver.php
> +        if ($data['status'] == 'published') {
Just a doubt, can there be a case when the status is not published and we can update the job? If yes, then we need to update the job details for both the case.

2021-08-16 15:39 UTC, GauravGusain98 commented
Please check the above comment

2021-08-17 06:37 UTC, am-Anmol commented on Modules/HR/Observers/Recruitment/JobObserver.php
> +        if ($data['status'] == 'published') {
Yes, this can be a possible scenario then we have to update both of them.
If we update the job from the portal and mark status to published it also gets updated on a website post.

2021-08-18 01:59 UTC, GauravGusain98 requested changes
Please check the comments and if required do the requested changes.

2021-08-18 01:59 UTC, GauravGusain98 commented on Modules/HR/Observers/Recruitment/JobObserver.php
> +        if ($data['status'] == 'published') {
Let me rephrase my question, 
I was saying that suppose a job is not published but you updated the job details in the portal. In this case as well, the job details should get updated in the website post. But as per the code, it looks like that the job will only get updated when the status is published.

Also what about the case when we update the job from `published` to `draft`. I don't think in that case it will mark the job as a draft on the website. 

Let me know if there is any doubt in understanding.

2021-08-18 02:00 UTC, GauravGusain98 requested changes
Please do the following changes.

2021-08-18 02:00 UTC, GauravGusain98 commented on Modules/HR/Observers/Recruitment/JobObserver.php
> +    }
Let me rephrase my question, 
I was saying that suppose a job is not published but you updated the job details in the portal. In this case as well, the job details should get updated in the website post. But as per the code, it looks like that the job will only get updated when the status is published.

Also what about the case when we update the job from `published` to `draft`. I don't think in that case it will mark the job as a draft on the website. 

Let me know if there is any doubt in understanding.

2021-08-18 18:16 UTC, am-Anmol commented
**Changes in created and updated function:**
- Created:
    - Checking if the status is `not published` then saving the post as a draft.
- Updated:
   - Checking if the status is `published` then updating the post as a `publish`, otherwise updating as `draft` only.

2021-08-18 18:18 UTC, am-Anmol commented on Modules/HR/Observers/Recruitment/JobObserver.php
> +    }
Yeah, I have understood your scenario and updated the code as per all scenarios possible while creating and updating any post through an employee portal.

2021-08-18 19:13 UTC, GauravGusain98 requested changes
Please check the suggestion

2021-08-18 19:13 UTC, GauravGusain98 commented on Modules/HR/Observers/Recruitment/JobObserver.php
> +        }
```suggestion
      $Corcel->post_status = $data['status'] == 'published' ? 'published' : 'draft';
```

2021-08-19 03:48 UTC, am-Anmol commented on Modules/HR/Observers/Recruitment/JobObserver.php
> +        }
Ok I make changes

2021-08-19 03:57 UTC, GauravGusain98 approved these changes
Looks good to me

2021-08-19 03:57 UTC, merged