Readme
ColoredCow/portal pull request #894
Opened 2021-08-16 12:07 UTC by kickb71

While Installing the portal we are facing some issues in the PHP version and the SSL errors. 

I have added the PHP version required for composer 7.3 and 7.4.
I have added the method to enable the SSL in php.ini file

2021-08-17 04:39 UTC, GauravGusain98 requested changes
Please check the comments

2021-08-17 04:39 UTC, GauravGusain98 commented on docs/installation.md
> +
Why this is written in the Install dependencies point?

2021-08-17 04:39 UTC, GauravGusain98 commented on docs/installation.md
> +link for php7.4(https://www.php.net/downloads.php#v7.4.21)
This will be more clear
```suggestion
Note: Required PHP versions - [7.3](https://www.php.net/downloads.php#v7.3.29) or [7.4](https://www.php.net/downloads.php#v7.4.21)
```

2021-08-17 11:46 UTC, kickb71 commented on docs/installation.md
> +link for php7.4(https://www.php.net/downloads.php#v7.4.21)
I will change it

2021-08-17 11:47 UTC, kickb71 commented on docs/installation.md
> +
It must be done mandatory because its causing some errors while installing.

2021-08-18 01:53 UTC, kickb71 commented on docs/installation.md
> +
While installing we are facing errors because of this command. This should be enables before before or while installing.

2021-08-19 04:10 UTC, GauravGusain98 requested changes
Please check the comments.

2021-08-19 04:10 UTC, GauravGusain98 commented on docs/installation.md
> +Note: Required PHP versions - [7.3](https://www.php.net/downloads.php#v7.3.29) or [7.4](https://www.php.net/downloads.php#v7.4.21)
Add an indentation to this line as it is inside point 1.

2021-08-19 04:10 UTC, GauravGusain98 commented on docs/installation.md
> +Note: Required PHP versions - [7.3](https://www.php.net/downloads.php#v7.3.29) or [7.4](https://www.php.net/downloads.php#v7.4.21)
Also, add a tab indentation to every line inside of the pointers.

2021-08-19 04:10 UTC, GauravGusain98 commented on docs/installation.md
> +
I mean, are the errors coming while installing dependencies? If yes, then please mention that `If you face any error while installing composer, then make sure you have OpenSSL enabled in your php.ini file`

2021-08-20 02:05 UTC, kickb71 commented on docs/installation.md
> +
okay fine

2021-08-20 10:13 UTC, kuldeep3 approved these changes

2021-08-20 10:13 UTC, kuldeep3 commented
@kickb71 Please resolve conflicts before merging the PR

2021-08-20 10:15 UTC, kuldeep3 commented
@GauravGusain98 Could you once review this PR and mark the conversation as resolved if the feedback has been implemented.

2021-08-20 10:17 UTC, GauravGusain98 commented on docs/installation.md
> +Note: Required PHP versions - [7.3](https://www.php.net/downloads.php#v7.3.29) or [7.4](https://www.php.net/downloads.php#v7.4.21)
Gautam, can you please check the above comment and make changes accordingly.

2021-08-20 13:12 UTC, kickb71 commented
@kuldeep3  Conflicts have been resolved

2021-08-21 16:38 UTC, GauravGusain98 approved these changes
Looks Good to me

2021-08-21 16:39 UTC, merged