Resolved Larastan Errors
ColoredCow/portal pull request #897
Opened 2021-08-18 09:45 UTC by am-Anmol

Targets #849 

### Description

**Resolve Larastan errors by:**
- Removing unused functions and unnecessary definitions of the return statement.
- Added correct definition of return statement where required.
- Added Errors that are `false-positive` as mentioned in documentation also `'Some parts of Laravel are currently too magical for Larastan/PHPStan to understand. We listed common errors to ignore, add them as needed'`.
- Added some `excluded files` where errors cannot be able to add in `ignore-errors` but code is correct according to `laravel documentation` but as its `larastan` showing as `false-positive`.

**After running this command `./vendor/bin/phpstan analyse`**

![image](https://user-images.githubusercontent.com/48876126/129876597-cff35cc4-ce85-4d25-8fe5-83074c16d84e.png)

**References**
https://github.com/nunomaduro/larastan
### Checklist:

- [ ] I have performed a self-review of my own code.

2021-08-18 19:23 UTC, GauravGusain98 commented on Modules/AppointmentSlots/Services/AppointmentSlotsService.php
> -     * @return bool
This function is returning collection. Please [check](https://laravel.com/docs/8.x/collections#method-replace) what is the type of Collection and use that in place of bool.  

Try this, if the check failed after making the changes then just revert them to the `bool`

2021-08-19 04:22 UTC, GauravGusain98 requested changes
Please check the comments

2021-08-19 04:22 UTC, GauravGusain98 commented on phpstan.neon
> +
Could you please tell me what these lines are for?

2021-08-19 04:22 UTC, GauravGusain98 commented on Modules/HR/Entities/Applicant.php
> -     * @return this
Don't remove line these multiline comments as they are made using the standard format. If you have any doubt about the return type, you can look for that on Google. In some places, you have corrected the @return  and @param, which is the right way.

2021-08-19 18:02 UTC, am-Anmol commented on Modules/AppointmentSlots/Services/AppointmentSlotsService.php
> -     * @return bool
Yes, I have tried with the `collection` but it's showing errors and suggestions to use `bool` only.

2021-08-19 18:07 UTC, am-Anmol commented on Modules/HR/Entities/Applicant.php
> -     * @return this
Actually, this Larstan is giving `false-positive` errors where I removed and corrected `return type` so that's why I have to remove these return type statements, I have seen some pull requests there in Larstan repo as mentioned there **`'Some parts of Laravel are currently too magical for Larastan/PHPStan to understand. We listed common errors to ignore, add them as needed'`** , so as suggested there remove the definition of the return statement.

Wherever possible and not showing error I have fixed them.

2021-08-19 18:19 UTC, am-Anmol commented on Modules/HR/Entities/Applicant.php
> -     * @return this
So the best solution for this is to remove for now for some time because Larastan is under build and improving their 
`false-positive errors`.

2021-08-19 18:27 UTC, am-Anmol commented on phpstan.neon
> +
These are the errors that are added to ignore errors with a combination of regular expressions which are Coded in the right way but Larstan showing them in error and those errors which can't be added to ignore errors like all internal errors which are not showing in local larastan check but showing in Coding Standards / Larastan (pull_request)  on GitHub so that files need to add in excluded paths.
These changes are required for passing larastan checks.

2021-08-20 12:41 UTC, GauravGusain98 approved these changes
Looks Good to me. @am-Anmol can you once take a pull of master branch to  this branch, just to make sure that there are no other fixes required.

2021-08-20 16:16 UTC, am-Anmol commented
@GauravGusain98 I have already taken the latest master pull and made larastan checks fixed because there were some conflict files so resolving them I have taken the latest master pull.
You can go forward with merging this pull.

2021-08-20 16:21 UTC, GauravGusain98 commented
> @GauravGusain98 I have already taken the latest master pull and made larastan checks fixed because there were some conflict files so resolving them I have taken the latest master pull.
> You can go forward with merging this pull.

Cool

2021-08-20 16:21 UTC, merged