Option to add, edit, update, delete remove tags
ColoredCow/portal pull request #915
Opened 2021-08-27 07:40 UTC by am-Anmol

Targets #834 

### Description

- Created the Manage Tags option in the navbar.
- Created TagController, index, edit, create-modal for managing tags.
- Created required routes in hr/web.php.
- Updated Tag table by changing column named `name` with `tname` because the `name` and `slug` columns are causing conflicting for CRUD operation that's why by changing the `name` to `tname` solved.

### Output:
![image](https://user-images.githubusercontent.com/48876126/131090061-5ce1873e-febb-46fe-bd33-1bd559a65a89.png)

### Checklist:

- [x] I have performed a self-review of my own code.

2021-08-28 05:55 UTC, am-Anmol commented
There are some UI feedbacks given by @rathorevaibhav & @pankaj-ag : 
1. Table content should not be bold.
2. Edit form should be centered align and input box size should be small.

Given feedbacks is resolved and now ready for review.

2021-08-28 16:35 UTC, GauravGusain98 requested changes
Please check the comments

2021-08-28 16:35 UTC, GauravGusain98 commented on Modules/HR/Http/Controllers/TagsController.php
> +    public function edit(int $id)
No you should use `Tag $tag`, then you don't require to find the tag in the next line.

2021-08-28 16:35 UTC, GauravGusain98 commented on Modules/HR/Http/Controllers/TagsController.php
> +    public function destroy($id)
Same here

2021-08-28 16:35 UTC, GauravGusain98 commented on Modules/HR/Resources/views/tags/create-tag-modal.blade.php
> +  <div class="modal-dialog">
indentation is still incorrect. I can see only 2 space indentation whereas it should be 4 spaces or a tab indentation, Please fix it.

2021-08-29 06:36 UTC, GauravGusain98 commented
@am-Anmol Please check the comments.

2021-08-29 06:57 UTC, am-Anmol commented on Modules/HR/Http/Controllers/TagsController.php
> +    public function destroy($id)
Ok, I'll change the suggested issues by today.

2021-08-29 06:57 UTC, am-Anmol commented on Modules/HR/Resources/views/tags/create-tag-modal.blade.php
> +  <div class="modal-dialog">
Ok, I'll fix them

2021-08-30 17:30 UTC, P4NK4J reviewed
Left some comments, please check.

2021-08-30 17:30 UTC, P4NK4J commented on Modules/HR/Resources/views/tags/create-tag-modal.blade.php
> +        </div>
@am-Anmol The indentation in this file seems different than the ones in the other files, could you please check and share your thoughts.

2021-08-30 17:45 UTC, am-Anmol commented on Modules/HR/Resources/views/tags/create-tag-modal.blade.php
> +        </div>
Yeah, it's feedback given by Gaurav https://github.com/ColoredCow/portal/pull/915#discussion_r697888564, that's why I have made it.

2021-08-31 14:56 UTC, am-Anmol commented
@ColoredCow/team-portal-reviewers You can take it forward for review.

2021-09-01 06:51 UTC, GauravGusain98 requested changes
Please make the following changes

2021-09-01 06:51 UTC, GauravGusain98 commented on Modules/HR/Resources/views/tags/index.blade.php
> +                        <a title="Edit" class="pr-1 btn btn-link" href="{{ route('hr.tags.edit',$tag) }}"><i class="text-success fa fa-edit fa-lg"></i></a>
```suggestion
                        <a title="Edit" class="pr-1 btn btn-link" href="{{ route('hr.tags.edit', $tag) }}"><i class="text-success fa fa-edit fa-lg"></i></a>
```

2021-09-01 06:51 UTC, GauravGusain98 commented on Modules/HR/Resources/views/tags/index.blade.php
> +                <td><div class="rounded w-13 h-13 d-inline-block mr-1" style="background-color: {{$tag->background_color}};color: {{$tag->text_color}};"></div>{{ $tag->tag_name }}</td>
```suggestion
                <td><div class="rounded w-13 h-13 d-inline-block mr-1" style="background-color: {{ $tag->background_color }};color: {{ $tag->text_color }};"></div>{{ $tag->tag_name }}</td>
```

2021-09-01 06:51 UTC, GauravGusain98 commented on Modules/HR/Http/Controllers/TagsController.php
> +    public function store(Request $request)
Add backend validation as well. For this you need to create a file with name `TagRequest` inside Request folder. You can take reference form other Request files. Then you can use that validation file here like. Also use TagRequest while updating. So try to make that file generic, so that it can be used in both the operation.
```suggestion
    public function store(TagRequest $request)
```

2021-09-01 06:51 UTC, GauravGusain98 commented on Modules/HR/Resources/views/tags/edit.blade.php
> +    <form action="{{route('hr.tags.update', $tag->id)}}" method="POST" id="update-form">
After adding backend validation you need to show errors in this blade file as well. Take reference from other blade files for showing the errors that are coming from the backend.

2021-09-01 06:51 UTC, GauravGusain98 commented on Modules/HR/Resources/views/tags/edit.blade.php
> +    <form action="{{route('hr.tags.update', $tag->id)}}" method="POST" id="update-form">
You should also show errors while creating the tags but as you are using a model while creating, so the approach will change there. We can leave that for now. Just show the errors while editing for now.

2021-09-01 13:41 UTC, am-Anmol commented on Modules/HR/Resources/views/tags/index.blade.php
> +                <td><div class="rounded w-13 h-13 d-inline-block mr-1" style="background-color: {{$tag->background_color}};color: {{$tag->text_color}};"></div>{{ $tag->tag_name }}</td>
Ok

2021-09-01 13:42 UTC, am-Anmol commented on Modules/HR/Http/Controllers/TagsController.php
> +    public function store(Request $request)
Ok, I'll make the requested changes.

2021-09-01 13:43 UTC, am-Anmol commented on Modules/HR/Resources/views/tags/edit.blade.php
> +    <form action="{{route('hr.tags.update', $tag->id)}}" method="POST" id="update-form">
Ok I add these changes

2021-09-05 08:01 UTC, GauravGusain98 approved these changes
Looks good to me

2021-09-05 08:03 UTC, GauravGusain98 commented
@kuldeep3 @P4NK4J Can you please review this once?

2021-09-06 04:38 UTC, P4NK4J approved these changes
Looks good to me

2021-09-06 09:49 UTC, am-Anmol commented
@GauravGusain98 @P4NK4J Can we merge this PR now?

2021-09-06 09:53 UTC, P4NK4J commented
Sure, I am merging it now.

2021-09-06 09:53 UTC, merged