Added functionality to add effort sheet url in project
ColoredCow/portal pull request #919
Opened 2021-08-28 16:00 UTC by GauravGusain98

Targets #909 

### Description

- Added input field from effort sheet URL while creating and updating the project
- Added backend validation for effortsheet URL and display them on the frontend
- Added a button to open the sheet on the new tab

![image](https://user-images.githubusercontent.com/54376313/131223720-31ff4861-ef52-43ee-bf75-08444677ae8a.png)

### Checklist:

- [x] I have performed a self-review of my own code.

2021-08-28 16:00 UTC, GauravGusain98 commented on Modules/Project/Http/Controllers/ProjectController.php
> +    public function update(ProjectRequest $request, Project $project)
Add validation rules while editing the project

2021-08-28 16:00 UTC, GauravGusain98 commented on Modules/Project/Http/Requests/ProjectRequest.php
> +            'effort_sheet_url' => 'nullable|active_url|max:255',
added rule for effortseet

2021-08-28 16:01 UTC, GauravGusain98 commented on Modules/Project/Http/Requests/ProjectRequest.php
> +            'effort_sheet_url.active_url' => 'Input url is not valid'
custom messages for effortsheet validations

2021-08-28 16:03 UTC, GauravGusain98 commented on Modules/Project/Resources/views/edit.blade.php
> +    </div>
show error messages on UI. 
Note: This error message display is sown only wile editing as wile editing, the axios call is used due to we have to sow the error messages using js

2021-08-28 16:06 UTC, GauravGusain98 commented on Modules/Project/Resources/views/edit.blade.php
> +            await axios.post('{{ route('project.update', $project) }}', formData)
Making post request to submit form

2021-08-28 16:07 UTC, GauravGusain98 commented on Modules/Project/Resources/views/edit.blade.php
> +            })
show and hide error messages

2021-08-28 16:07 UTC, GauravGusain98 commented on Modules/Project/Resources/views/subviews/create-project-details.blade.php
> +        </div>
added input field for effortsheet url

2021-08-28 16:08 UTC, GauravGusain98 commented on Modules/Project/Services/ProjectService.php
> +            'effort_sheet_url' => $data['effort_sheet_url'] ?? null
store effort sheet url while creating the project

2021-08-28 16:08 UTC, GauravGusain98 commented on Modules/Project/Services/ProjectService.php
> +            'effort_sheet_url' => $data['effort_sheet_url'] ?? null
store effort sheet url while editing the project

2021-08-28 16:08 UTC, GauravGusain98 commented on database/migrations/2021_08_28_043719_add_effort_sheet_url_column_in_projects_table.php
> +            $table->string('effort_sheet_url')->nullable()->after('status');
add `effort_sheet_url` column in `projects` table

2021-08-30 16:18 UTC, kuldeep3 requested changes
Please make changes as per our offline conversation

2021-08-30 16:18 UTC, kuldeep3 commented on Modules/Project/Http/Requests/ProjectRequest.php
> +            'effort_sheet_url.max' => 'Url must be less than 191 character',
```suggestion
            'effort_sheet_url.max' => 'Url must be less than 191 characters',
```

2021-08-30 16:18 UTC, kuldeep3 commented on database/migrations/2021_08_28_043719_add_effort_sheet_url_column_in_projects_table.php
> +     * Reverse the migrations.
```suggestion
     * Reverse the migration.
```

2021-08-30 16:18 UTC, kuldeep3 commented on database/migrations/2021_08_28_043719_add_effort_sheet_url_column_in_projects_table.php
> +     * Run the migrations.
```suggestion
     * Run the migration.
```

2021-08-30 17:03 UTC, GauravGusain98 commented on Modules/Project/Resources/views/edit.blade.php
> +                    $('#edit-project-error-list').append("<li class='text-danger ml-2'>" + errors[error] + "</li>");
This will return the key of the error array.

2021-08-30 17:13 UTC, kuldeep3 approved these changes

2021-08-30 17:21 UTC, merged