Creation of reports file
ColoredCow/portal pull request #920
Opened 2021-08-30 08:14 UTC by kickb71

2021-08-30 17:20 UTC, GauravGusain98 commented
@kickb71 Please fix the checks

2021-08-31 10:56 UTC, kickb71 commented
> @kickb71 Please fix the checks

Okay

2021-08-31 16:36 UTC, GauravGusain98 requested changes
Please check the comments. Also if possible can you please add a screenshot of the chart.

2021-08-31 16:36 UTC, GauravGusain98 commented on resources/views/hr/recruitment/reports.blade.php
> -        <div class="col-md-12">
Pleaese correct the indentation. It should be 4 spaces or a tab. Currently, it is only 2 spaces indentation.

2021-08-31 16:36 UTC, GauravGusain98 commented
@kuldeep3  If possible can you also check this PR once.

2021-09-01 06:21 UTC, kickb71 commented on resources/views/hr/recruitment/reports.blade.php
> -        <div class="col-md-12">
OK

2021-09-01 17:58 UTC, GauravGusain98 approved these changes
Looks fine. Approving.

2021-09-01 17:58 UTC, merged