Added javascript code for hiding previous dates
ColoredCow/portal pull request #924
Opened 2021-08-31 06:17 UTC by srivastava-jyoti

Issue:[#316](https://github.com/ColoredCow/portal/issues/316)

Tasks:

- [ ] To remove > from start date in edit file
- [ ] To hide previous dates

2021-08-31 06:51 UTC, srivastava-jyoti commented
@GauravGusain98 I have made a new PR for this issue. As in the previous one somehow other files got merged and I tried reverting but I was unable to revert.

For the issue which You pointed out that the changes are not visible on your local so for this we need to run `npm run watch`
in command prompt. I was facing same issue got checked on stackoverflow. Here's the link:[link](https://stackoverflow.com/questions/53425186/laravel-reactjs-changes-are-not-reflecting-after-change-in-my-jsreactjs-file)

Here's the screenshot from my local
![Screenshot (57)](https://user-images.githubusercontent.com/79009032/131455996-b18f35f7-99c4-44fc-b1f5-820dff9f8496.png)

2021-08-31 10:11 UTC, GauravGusain98 requested changes
Please do the suggested changes

2021-08-31 10:11 UTC, GauravGusain98 commented on resources/js/app.js
> +document.getElementById("end_date").setAttribute("min", minDate);
Can you add a check here for the page where you need to load this script. You just need to add an id on the page and check the length of the id like this:

```suggestion
if ($('#page_id').length) {
    var date = new Date();
    var tdate = date.getDate();
    if (tdate < 10) {
                tdate = "0" + date;
    }
    var month = date.getMonth() + 1;
    if (month < 10) {
        	month = "0" + month;
    }
    var year = date.getUTCFullYear();
    var minDate = year + "-" + month + "-" + date;
    document.getElementById("start_date").setAttribute("min", minDate);
    document.getElementById("end_date").setAttribute("min", minDate);
}
```

2021-09-01 09:06 UTC, srivastava-jyoti commented on resources/js/app.js
> +document.getElementById("end_date").setAttribute("min", minDate);
@GauravGusain98 I have made the required changes. And for the id part, I have used a unique id for start and end dates.These are not generic for the entire hr module. The previous dates are not visible for job description pages only.

2021-09-01 17:51 UTC, GauravGusain98 approved these changes
Looks good to me

2021-09-01 17:52 UTC, merged