912 new UI application status
ColoredCow/portal pull request #925
Opened 2021-08-31 08:26 UTC by tarun9142

Targets #{912}

### Description
*updated the UI for application status tabs 

These changes updates the job application status bar UI  on recruitment page.
![app status](https://user-images.githubusercontent.com/79507487/131466733-12f619cd-d294-4ebd-a044-a3155bbc5bfd.png)
### Checklist:

- [x] I have performed a self-review of my own code.

2021-08-31 16:21 UTC, GauravGusain98 requested changes
Please do the requested changes

2021-08-31 16:21 UTC, GauravGusain98 commented on .env.example
> -APP_NAME=Laravel
You don't have to remove this file. Just make a copy of it and rename that as `.env`

2021-08-31 16:21 UTC, GauravGusain98 commented on Modules/HR/Resources/views/application/index.blade.php
> +            <h1>Applications dsgrggfdsg</h1>
What's this? Please fix it.

2021-08-31 16:21 UTC, GauravGusain98 commented on package.json
> +        "axios": "^0.21.1",
Why you updated this package. If the update is not required for the feature, then, please don't add package files to git

2021-08-31 16:21 UTC, GauravGusain98 commented on resources/views/hr/application/index.blade.php
> +
remove unwanted line spaces

2021-08-31 16:21 UTC, GauravGusain98 commented on resources/views/hr/application/index.blade.php
> +                            {{$newApplicationsCount + $inProgressApplicationsCount - $trialProgramCount}}
Fromat accordingly at all the other places. Add spaces wherever `{{ }}` are used
```suggestion
                            {{ $newApplicationsCount + $inProgressApplicationsCount - $trialProgramCount }}
```

2021-09-01 03:03 UTC, tarun9142 commented on package.json
> +        "axios": "^0.21.1",
ok

2021-09-01 03:05 UTC, tarun9142 commented on Modules/HR/Resources/views/application/index.blade.php
> +            <h1>Applications dsgrggfdsg</h1>
fixed it

2021-09-01 03:05 UTC, tarun9142 commented on .env.example
> -APP_NAME=Laravel
ok

2021-09-01 03:15 UTC, tarun9142 commented on resources/views/hr/application/index.blade.php
> +
should I merge line 52 and 53 in single line or something else.

2021-09-01 03:33 UTC, tarun9142 commented on resources/views/hr/application/index.blade.php
> +
ok got it

2021-09-12 14:55 UTC, closed without merging