UI for Appointment Slots
ColoredCow/portal pull request #941
Opened 2021-09-06 07:27 UTC by srivastava-jyoti

Targets:[#911](https://github.com/ColoredCow/portal/issues/911)

Describe the task:
Build User Interface for controlling a maximum number of slots in a day for a user.

Prerequisite: Issue [#836](URL) to be completed.

Checklist:

- [ ] UI part done
- [ ] Save value passed by user in the database.

2021-09-10 19:47 UTC, srivastava-jyoti commented
@GauravGusain98 Please review this. I have integrated both parts together. I am getting PHP CS for importing the module which is not used. But I have used UserMeta module for establishing relationships.

2021-09-11 05:04 UTC, srivastava-jyoti commented
@GauravGusain98  as suggested by @rathorevaibhav there was no need for a reset button in UI.

2021-09-11 11:06 UTC, GauravGusain98 requested changes
Please work on the feedbacks.

2021-09-11 11:06 UTC, GauravGusain98 commented on Modules/User/Entities/UserMeta.php
> +    protected $fillable = ['max_interviews_per_day'];
Also, add `user_id` in the fillable.

2021-09-11 11:06 UTC, GauravGusain98 commented on Modules/User/Http/Controllers/UserSettingsController.php
> +            ['max_interviews_per_day'=>$request->max_interviews_per_day]
```suggestion
            ['max_interviews_per_day' => $request->max_interviews_per_day]
```

2021-09-11 11:06 UTC, GauravGusain98 commented on Modules/AppointmentSlots/Services/AppointmentSlotsService.php
> +            }
```suggestion
           
                $maxInterviewsPerDay = $userMeta ? $userMeta->max_interviews_per_day : config('hr.daily-appointment-slots.max-reserved-allowed', 3);
```

2021-09-11 11:18 UTC, kuldeep3 requested changes
Please fix the indentation on the stylesheet.

2021-09-11 11:18 UTC, kuldeep3 commented on resources/sass/app.scss
> +}
Rename the class name to something that makes sense..like currently I can't get what `d33` represent here. Moreover there are indentation issues. Please fix them also.

2021-09-11 11:18 UTC, kuldeep3 commented on resources/sass/app.scss
> +}
I can see you have added `left: 828px`. What will happen if I view this on a tablet or mobile?

Please check if the UI elements are mobile-responsive or not.

2021-09-11 11:18 UTC, kuldeep3 commented on resources/sass/app.scss
> +}
The class name should make sense. Please rename it to something that will have user understand what this class is used for.

2021-09-11 11:18 UTC, kuldeep3 commented on resources/sass/app.scss
> +}
Indentation

2021-09-11 11:18 UTC, kuldeep3 commented on resources/sass/app.scss
> +}
indentation

2021-09-11 11:18 UTC, kuldeep3 commented on resources/sass/app.scss
> +.search{
Please don't use a generic term for classes unless it is used globally. You can rename it to `user-setttings-search-box` or `user-settings-search-icon` depending upon the use case.

2021-09-11 11:18 UTC, kuldeep3 commented on Modules/User/Http/Controllers/UserSettingsController.php
> +}
Any reason to use a separate controller for user settings?

Why not creating these methods on UserController itself?

2021-09-11 11:18 UTC, kuldeep3 commented on Modules/AppointmentSlots/Services/AppointmentSlotsService.php
> +            $userMeta = User::find($userId)->meta;
```suggestion
            $userMeta = UserMeta::where('user_id', $user_id)->first();
```

Will there be any difference in end result if I do this?

2021-09-11 12:21 UTC, rathorevaibhav requested changes

2021-09-11 12:21 UTC, rathorevaibhav commented on Modules/User/Http/Controllers/UserSettingsController.php
> +        DB::table('user_meta')->updateOrInsert(
let's use models here instead of hardcoded table names. It will be difficult if you update the table name and then you'll have to update at all places.
```php
UserMeta::updateOrCreate([], []);
```

Read more here:
https://laravel.com/docs/8.x/eloquent#upserts

2021-09-11 12:21 UTC, rathorevaibhav commented on Modules/User/Http/Controllers/UserSettingsController.php
> +        return redirect('/user/user-settings')->with('status', 'Saved Successfully!');
Please use route names instead of hardcoded URLs.
```suggestion
        return redirect(route("your-route.name"))->with('status', 'Saved Successfully!');
```

Also, in case you just need to go back, you can use this:
```php
return redirect()->back()->with('data', 'data');
```

2021-09-11 12:21 UTC, rathorevaibhav commented on Modules/User/Resources/views/user-settings/index.blade.php
> +                <a class="nav-link active" aria-current="true" href="#">Finance</a>
since there are no settings for finance right now, can we name it as:
```suggestion
                <a class="nav-link active" aria-current="true" href="#">Finance (coming soon)</a>     
```

2021-09-11 12:21 UTC, rathorevaibhav commented on Modules/User/Resources/views/user-settings/index.blade.php
> +                <a class="nav-link" href="/user/user-settings">HR</a>
HR tab should be active not the finance tab

2021-09-11 12:21 UTC, rathorevaibhav commented on Modules/User/Resources/views/user-settings/index.blade.php
> +                <a class="nav-link" href="/user/user-settings">HR</a>
Also, please use named routes instead of hardcoded URLs:
```suggestion
                <a class="nav-link" href="{{ route('your-route.name') }}">HR</a>  
```

2021-09-11 12:21 UTC, rathorevaibhav commented on Modules/User/Routes/web.php
> +    Route::post('/user-settings', 'UserSettingsController@update')->name('user.settings-hr');
This is incorrect name. Please use what the route does:
```suggestion
    Route::post('/user-settings', 'UserSettingsController@update')->name('user.settings.update');
```

2021-09-11 12:21 UTC, rathorevaibhav commented on database/migrations/2021_09_05_120744_create_user_meta_table.php
> +            $table->integer('max_interviews_per_day')->unsigned();
This field should be nullable.

2021-09-11 12:21 UTC, rathorevaibhav commented on resources/sass/app.scss
> +.user-settings{
@kuldeep3 @GauravGusain98 we should enforce using bootstrap classes instead of CSS. Write only that thing in CSS which is not covered by bootstrap utilities.

2021-09-11 12:21 UTC, rathorevaibhav commented on resources/sass/app.scss
> +    font-family: Mulish;
let's keep it same font as the rest of the app. Let's remove this.

2021-09-11 12:21 UTC, rathorevaibhav commented on resources/sass/app.scss
> +	position: absolute;
any reason for using `position: absolute` in all the elements? @srivastava-jyoti

2021-09-11 16:52 UTC, srivastava-jyoti commented
@ColoredCow/team-portal-reviewers  I have made the suggested changes. Only the bootstrap part is left. I will cover it in different PR.

2021-09-11 16:55 UTC, srivastava-jyoti commented on Modules/AppointmentSlots/Services/AppointmentSlotsService.php
> +            $userMeta = User::find($userId)->meta;
I have tried using where clause comparing user_id with $userId but no slots were visible for that particular user although I had fixed it as 1.

2021-09-11 17:22 UTC, kuldeep3 requested changes
Left some comments. Please have a look once.

2021-09-11 17:22 UTC, kuldeep3 commented on Modules/User/Routes/web.php
> +    Route::post('/user-settings', 'UserSettingsController@update')->name('user.settings.update');
Correct the controller name. I think it should be UserController.

2021-09-11 17:22 UTC, kuldeep3 commented on app/Http/Controllers/UserController.php
> +    }
These should not be here. I think it should be in the UserController of the User module. Also after making changes please test it once to check if everything is working as expected.

2021-09-11 17:22 UTC, kuldeep3 commented on Modules/User/Routes/web.php
> +    Route::post('/user-settings', 'UserSettingsController@update')->name('user.settings.update');
I don't see this is getting called anywhere. Please confirm once.

2021-09-11 18:03 UTC, srivastava-jyoti commented
@kuldeep3 using user controller it is directing to this page.
![Screenshot (85)](https://user-images.githubusercontent.com/79009032/132957055-470d5ec2-d3f1-4f30-9510-a8cdfdbe6822.png)

2021-09-11 18:09 UTC, GauravGusain98 commented
@srivastava-jyoti is this feature is working in your local?

2021-09-11 18:18 UTC, srivastava-jyoti commented
@GauravGusain98 Yes,it is working

2021-09-11 18:20 UTC, GauravGusain98 commented
> @GauravGusain98 Yes,it is working

cool

2021-09-11 18:20 UTC, GauravGusain98 approved these changes

2021-09-11 18:27 UTC, kuldeep3 approved these changes

2021-09-12 14:57 UTC, rathorevaibhav reviewed
@srivastava-jyoti one last feedback. Everything else looking great 👏

2021-09-12 14:57 UTC, rathorevaibhav commented on Modules/User/Resources/views/user-settings/index.blade.php
> +                <a class="nav-link" href="{{ route ('user.settings') }}">HR</a>
please make this active link

2021-09-12 15:06 UTC, srivastava-jyoti commented on Modules/User/Resources/views/user-settings/index.blade.php
> +                <a class="nav-link" href="{{ route ('user.settings') }}">HR</a>
@rathorevaibhav I have made another pull request for UI part corrected everything in that PR.

2021-09-12 15:17 UTC, rathorevaibhav commented on Modules/User/Resources/views/user-settings/index.blade.php
> +                <a class="nav-link" href="{{ route ('user.settings') }}">HR</a>
Sounds good then.

2021-09-12 15:17 UTC, rathorevaibhav approved these changes

2021-09-12 15:17 UTC, merged