Reject
ColoredCow/portal pull request #942
Opened 2021-09-06 08:44 UTC by kickb71

2021-09-07 08:14 UTC, GauravGusain98 requested changes
Please check the comments.

2021-09-07 08:14 UTC, GauravGusain98 commented on database/migrations/2021_09_06_081550_hr_application_rejection_reasons.php
> +            $table->text('reason_comment');
I think this should be nullable. Just check if we can leave the comment field empty or not.

2021-09-07 08:14 UTC, GauravGusain98 commented on resources/js/app.js
>  import "jquery-ui/ui/widgets/datepicker.js";
It is very difficult to find the changes you have made with these many formatting changes. So only format the code that you have added.

2021-09-07 08:14 UTC, GauravGusain98 commented on resources/views/hr/application/rejection-modal.blade.php
> +                        <input type="checkbox" id="rejectReason1"> No responce <br>
Whenever you are using a text inside a blade tag, always sanitize it using `{{ __('') }}`

```suggestion
                        <input type="checkbox" id="rejectReason1"> {{ __('No response') }} <br>
```

2021-09-07 08:14 UTC, GauravGusain98 commented on resources/views/hr/application/rejection-modal.blade.php
> +                        <input type="checkbox" id="rejectReason4"> Salary  expectation mismatch <br>
```suggestion
                        <input type="checkbox" id="rejectReason4"> {{ __('Salary expectation mismatch') }} <br>
```

2021-09-07 08:14 UTC, GauravGusain98 commented on resources/views/hr/application/rejection-modal.blade.php
> +                        <div id="txtReasonRejected2" style="display: none">
```suggestion
                        <div id="txtReasonRejected2" class="d-none">
```

2021-09-07 08:14 UTC, GauravGusain98 commented on resources/views/layouts/app.blade.php
> +    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
Why you have added this?

2021-09-07 08:16 UTC, kickb71 commented on database/migrations/2021_09_06_081550_hr_application_rejection_reasons.php
> +            $table->text('reason_comment');
It will automatically add text when you click check box that's why its not nullable

2021-09-07 08:17 UTC, kickb71 commented on resources/js/app.js
>  import "jquery-ui/ui/widgets/datepicker.js";
I did only use the formater app it made changes every where

2021-09-07 08:18 UTC, kickb71 commented on resources/views/hr/application/rejection-modal.blade.php
> +                        <input type="checkbox" id="rejectReason1"> No responce <br>
Sure let me change it  for all

2021-09-07 08:19 UTC, kickb71 commented on resources/views/layouts/app.blade.php
> +    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
> Why you have added this?

I have added this Jquery for when a check box is clicked a textbox should appear that's why I need jquery

2021-09-07 08:19 UTC, GauravGusain98 commented on resources/js/app.js
>  import "jquery-ui/ui/widgets/datepicker.js";
So when you format a document. There is option to format only changes. So just use that option. You can find it in settings.

2021-09-07 09:12 UTC, GauravGusain98 commented on resources/views/layouts/app.blade.php
> +    <script type="text/javascript" src="http://ajax.googleapis.com/ajax/libs/jquery/1.8.3/jquery.min.js"></script>
But we are using jquery earlier in app.js and it was working. Did you tried testing the code without importing this line. I would suggest testing it once without this line.

2021-09-08 05:31 UTC, kickb71 commented on resources/js/app.js
>  import "jquery-ui/ui/widgets/datepicker.js";
I will change it.  It won't happen again!

2021-09-10 16:18 UTC, P4NK4J commented on Modules/HR/Config/config.php
> +        'Not enough knowledge/inclination for ColoredCow'
@kickb71 I think we should keep key=>value pair in the config, and store the slug in the database, since the labels may change in the future. Let me know your thoughts on it.

2021-09-10 16:22 UTC, P4NK4J commented on Modules/HR/Http/Requests/Recruitment/ApplicationRoundRequest.php
> +            $rules['reject_reason'] = 'nullable|array';
@kickb71 Any reason why nullable rule is being used here ?

2021-09-10 16:22 UTC, P4NK4J commented on Modules/HR/Routes/web.php
> +            // Route::post('/applicationround/{applicationRound}/store', 'ApplicationRoundController@storeReason')->name('reasons.post');
@kickb71 Any specific reason, why the commented code is left in this file ?

2021-09-10 16:23 UTC, P4NK4J commented on database/migrations/2021_09_06_081550_hr_application_rejection_reasons.php
> +class HrApplicationRejectionReasons extends Migration
Why `Hr` naming convention is used here while at all other places `HR` is mentioned ? Let's use similar conventions everywhere.

2021-09-10 16:25 UTC, P4NK4J commented on resources/views/hr/application/rejection-modal.blade.php
> +                            <input type="checkbox" class="reject-reason mr-1" id="reasonTitle{{ $index }}" name='reject_reason[{{ $index }}][title]' value='{{ $reasonForRejection }}'>{{ $reasonForRej
I think we should use slug and value pair here, since the vocabulary for reasons may change in the future, we could have constant slug saved in the database then. Let me know your thoughts,

2021-09-10 16:26 UTC, P4NK4J requested changes
@kickb71 Left some comments, please take a look.

2021-09-10 16:26 UTC, kickb71 commented on Modules/HR/Config/config.php
> +        'Not enough knowledge/inclination for ColoredCow'
If we change the key value means it will be hard. In for loop in the blade file and javascript file I have to change in both places. If we use a new value means we should just add here the new value but if we use the key-value means we have to change all the files for future use. 
@P4NK4J  I think it should be the same. If it should be changed means I happy to change it

2021-09-10 16:31 UTC, kickb71 commented on Modules/HR/Routes/web.php
> +            // Route::post('/applicationround/{applicationRound}/store', 'ApplicationRoundController@storeReason')->name('reasons.post');
I forgot to remove it. Let me remove it

2021-09-10 16:34 UTC, kickb71 commented on Modules/HR/Http/Requests/Recruitment/ApplicationRoundRequest.php
> +            $rules['reject_reason'] = 'nullable|array';
Yes. If you reject a person for only 2 reasons but all the others must not save that is why I gave nullable.

2021-09-10 16:35 UTC, kickb71 commented on database/migrations/2021_09_06_081550_hr_application_rejection_reasons.php
> +class HrApplicationRejectionReasons extends Migration
I can't understand what are trying to say?

2021-09-10 16:36 UTC, kickb71 commented on resources/views/hr/application/rejection-modal.blade.php
> +                            <input type="checkbox" class="reject-reason mr-1" id="reasonTitle{{ $index }}" name='reject_reason[{{ $index }}][title]' value='{{ $reasonForRejection }}'>{{ $reasonForRej
I think it will hard to pass in this foreach

2021-09-11 04:51 UTC, P4NK4J commented on Modules/HR/Config/config.php
> +        'Not enough knowledge/inclination for ColoredCow'
@kickb71 , I am saying the `key` will be saved in the database, which would never get changed. If there is any change to the reason let's say `No response` is changed to `No response given`, that would be easy to make only in the config, without changing it from the database, hence recommending to use the following
```suggestion
        'no-response' => 'No response',
        ...
```

2021-09-11 04:52 UTC, P4NK4J commented on Modules/HR/Http/Requests/Recruitment/ApplicationRoundRequest.php
> +            $rules['reject_reason'] = 'nullable|array';
If the others are not selected from the form field, they won't be saved then.

2021-09-11 04:53 UTC, P4NK4J commented on Modules/HR/Routes/web.php
> +            // Route::post('/applicationround/{applicationRound}/store', 'ApplicationRoundController@storeReason')->name('reasons.post');
I can see it hasn't been removed. Let me know if there is something which I am missing.

2021-09-11 04:53 UTC, P4NK4J commented on database/migrations/2021_09_06_081550_hr_application_rejection_reasons.php
> +class HrApplicationRejectionReasons extends Migration
Let me know if it's clear after today's discussion

2021-09-11 04:55 UTC, P4NK4J commented on resources/views/hr/application/rejection-modal.blade.php
> +                            <input type="checkbox" class="reject-reason mr-1" id="reasonTitle{{ $index }}" name='reject_reason[{{ $index }}][title]' value='{{ $reasonForRejection }}'>{{ $reasonForRej
Instead of $index, you use a slug in the value, and reason name in the label, while for the integer value you can initialize a different variable. Let me know if that makes sense.

2021-09-11 04:55 UTC, P4NK4J requested changes
@kickb71  Left some comments, please check.

2021-09-11 12:11 UTC, kickb71 commented on Modules/HR/Config/config.php
> +        'Not enough knowledge/inclination for ColoredCow'
The same thing happens without the key. I don't know the difference

2021-09-11 12:11 UTC, kickb71 commented on Modules/HR/Http/Requests/Recruitment/ApplicationRoundRequest.php
> +            $rules['reject_reason'] = 'nullable|array';
There are two things the title and comment box we can leave the comment box empty that's why its nullable

2021-09-11 13:11 UTC, P4NK4J commented
@kickb71 , Removing the status ready for review, I think there are some changes need to be made in this PR, as per our discussion.

2021-09-11 14:22 UTC, P4NK4J commented on database/migrations/2021_09_06_081550_hr_application_rejection_reasons.php
> +class HrApplicationRejectionReasons extends Migration
@kickb71 Please resolve feedback before you assign for review

2021-09-11 14:23 UTC, P4NK4J reviewed
Left one comment, please check @kickb71

2021-09-11 14:25 UTC, P4NK4J commented on resources/views/hr/application/rejection-modal.blade.php
> +                            <input type="checkbox" class="reject-reason mr-1" id="reasonTitle{{ $index }}" name='reject_reason[{{ $index }}][title]' value='{{ $reasonForRejection }}'>{{ $reasonForRej
@kickb71 Also, you are not saving slugs in the value here, please make changes.

2021-09-11 14:33 UTC, kickb71 commented on database/migrations/2021_09_06_081550_hr_application_rejection_reasons.php
> +class HrApplicationRejectionReasons extends Migration
Changed!

2021-09-11 14:39 UTC, P4NK4J commented on resources/views/layouts/app.blade.php
> +    {{-- <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"> --}}
Why this CDN is commented @kickb71 ? Is it unused everywhere ?

2021-09-11 14:39 UTC, P4NK4J reviewed
Left a comment, let me know your thoughts

2021-09-11 14:41 UTC, kickb71 commented on resources/views/layouts/app.blade.php
> +    {{-- <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"> --}}
No i vas working on another issue that is why commented

2021-09-11 14:49 UTC, GauravGusain98 approved these changes
Looks good

2021-09-11 14:50 UTC, P4NK4J approved these changes

2021-09-11 14:51 UTC, merged