Project hours
ColoredCow/portal pull request #951
Opened 2021-09-09 08:31 UTC by AkhileshNegi

2021-09-16 05:38 UTC, kuldeep3 requested changes
Can we make active selected by default in project type?

Let me know your thoughts on this.

2021-09-16 05:38 UTC, kuldeep3 commented on Modules/Project/Http/Requests/ProjectRequest.php
> +                    'monthly_estimated_hours' => 'numeric|between:0,9999.99'
Can we lower down the max limit?

2021-09-18 13:09 UTC, AkhileshNegi commented on Modules/Project/Http/Requests/ProjectRequest.php
> +                    'monthly_estimated_hours' => 'numeric|between:0,9999.99'
@kuldeep3 let it be as it is for the time being.

2021-09-18 13:10 UTC, AkhileshNegi commented on Modules/Project/Resources/views/subviews/create-project-details.blade.php
> +                placeholder="Enter monthly estimated hours" value="{{ old('monthly_estimated_hours') }}">
@kuldeep3 I have updated the issue with the new field name in the schema. Let me know in case its good to go

2021-09-18 13:11 UTC, AkhileshNegi commented on Modules/Project/Resources/views/subviews/edit-project-details.blade.php
> +                        <label for="name" class="field-required">Select project type</label>
@kuldeep3 made requested changes

2021-09-20 17:08 UTC, GauravGusain98 reviewed
Looks good just some minor changes requested.

2021-09-20 17:08 UTC, GauravGusain98 commented on config/constants.php
> -
Please remove this change if no file changes are made in this file.

2021-09-21 06:37 UTC, AkhileshNegi commented on config/constants.php
> -
@GauravGusain98 reverted the file changes

2021-09-21 06:42 UTC, kuldeep3 approved these changes
LGTM ⚡

2021-09-21 07:07 UTC, merged