910 Update Migrations for Effort Tracking
ColoredCow/portal pull request #962
Opened 2021-09-11 11:31 UTC by GauravGusain98

Targets #910

### Description

- Replace `resource` with `team-member` at all the places in codebase
- Add a migration to make the changes as per the [DB Schema](https://docs.google.com/presentation/d/1jaByFL_NodzD1onxb7JGie3MFsNxfrMbdsEg9WFHVDk/edit#slide=id.geb9fea0699_1_47)

### Checklist:

- [x] I have performed a self-review of my own code.

2021-09-11 12:05 UTC, rathorevaibhav reviewed
Some minor comments. @GauravGusain98 have a look.

2021-09-11 12:05 UTC, rathorevaibhav commented on Modules/Prospect/Resources/views/index.blade.php
> +                    <th>Requirements</th
👍

2021-09-11 12:05 UTC, rathorevaibhav commented on database/migrations/2021_09_09_082632_update_tables_for_effort_tracking.php
> +            $table->enum('type', array_keys(config('project.type')))->after('id')->default(config('project.type.monthly'));
let's not use enums. They make it difficult later to rename columns in that table. This should be just `string` or `varchar`.

2021-09-11 12:05 UTC, rathorevaibhav commented on Modules/Project/Resources/views/subviews/edit-project-team-members.blade.php
> +                        <button v-on:click="removeProjectTeamMember(index)" type="button" class="btn btn-danger btn-sm mt-1 ml-2"> - </button>
can we do this? May look a bit nicer on UI
```suggestion
                        <button v-on:click="removeProjectTeamMember(index)" type="button" class="btn btn-danger btn-sm mt-1 ml-2 text-white fz-14">Remove</button>
```

2021-09-11 12:05 UTC, rathorevaibhav commented on Modules/Project/Config/config.php
> +        'monthly' => 'Monthly',
```suggestion
        'monthly-billing' => 'Monthly Billing',
```

2021-09-11 12:16 UTC, GauravGusain98 commented on Modules/Project/Config/config.php
> +        'monthly' => 'Monthly',
Cool, let's update the `type` column value to `monthly-billing` in the database schema as well.

2021-09-11 12:22 UTC, rathorevaibhav commented on Modules/Project/Config/config.php
> +        'monthly' => 'Monthly',
Done.

2021-09-11 13:10 UTC, kuldeep3 commented
@rathorevaibhav Will it be `team-members` or just `members` in place of `resources` as from team-members it seems we have multiple teams in the project and `project-team-members` reflects that for a project there are teams and members is confine within the team.

2021-09-11 13:15 UTC, rathorevaibhav commented
@kuldeep3 not sure if `project members` would be straightforward to understand. Let's keep it `project team members` for now only. I can understand where you're coming from with the doubt with teams inside project, but let's keep it this way right now.

2021-09-13 18:01 UTC, kuldeep3 requested changes

2021-09-14 05:49 UTC, kuldeep3 approved these changes
Looks good on code ⚡

2021-09-14 05:50 UTC, merged