Feature/UI/job applications dashboard
ColoredCow/portal pull request #973
Opened 2021-09-12 14:04 UTC by srivastava-jyoti

Targets #{912}

 Description: To change the UI  of Job application dashboard.

2021-09-15 04:19 UTC, GauravGusain98 requested changes
Please check the comments. @P4NK4J @kuldeep3 Can you please review this PR once.

2021-09-15 04:19 UTC, GauravGusain98 commented on resources/js/app.js
> +	const menuItem  = document.querySelectorAll("#job-application-listings");
```suggestion
	const menuItem = document.querySelectorAll("#job-application-listings");
```

2021-09-15 04:19 UTC, GauravGusain98 commented on resources/js/app.js
> +		}
```suggestion
		if (menuItem[i].href === currentLocation) {
			menuItem[i].className = "job-application-status";
		}
```

2021-09-15 04:19 UTC, GauravGusain98 commented on resources/js/app.js
> +	for(let i=0; i<menuLength; i++){
```suggestion
	for (let i = 0; i < menuLength; i++) {
```

2021-09-15 04:19 UTC, GauravGusain98 commented on resources/views/hr/application/index.blade.php
> +                    <sup class ="head1">
Use a meaningful name at all places required.
```suggestion
                    <sup class ="application-menu-options-title">
```

2021-09-15 04:19 UTC, GauravGusain98 commented on resources/views/hr/application/index.blade.php
> +                                ]]);
It is good pratice to use `array()` instead of `[ ]`
```suggestion
                                $target = request()->fullUrlWithQuery(array(
                                    'tags' => array($tag->id)
                                 ));
                
```

2021-09-15 05:44 UTC, GauravGusain98 commented on resources/js/app.js
> +if ( document.getElementById("list-styling") ){
You should handle this logic at the PHP level. I don't think you need to update the className using Javascript. Laravel provides the functionality to get the current url and using that you can update the class Name in blade file.

2021-09-15 05:49 UTC, GauravGusain98 commented on resources/views/hr/application/index.blade.php
> +                    <h5 class="toapprove">To Approve</h5>
You should not add svg like this in the blade file. All the icons should be stored inside `\public\icons` folder.
If icons folder is not present you can create one.

The you can access this svg file using 
```php
{!! file_get_contents(public_path('icons/file-name.svg')) !!}
```

2021-09-15 05:49 UTC, GauravGusain98 commented on resources/views/hr/application/index.blade.php
> +                    <h5 class="toapprove">To Approve</h5>
Please correct this at all the places

2021-09-15 05:57 UTC, srivastava-jyoti commented on resources/views/hr/application/index.blade.php
> +                                ]]);
@GauravGusain98 I have not changed these lines. It was pre written.

2021-09-15 06:01 UTC, srivastava-jyoti commented on resources/js/app.js
> +if ( document.getElementById("list-styling") ){
I had tried that way also but after clicking on icons the color changed but on reloading the color remains the same as initial. That's why I used javascript to handle my logic.

2021-09-16 05:38 UTC, srivastava-jyoti commented
@ColoredCow/team-portal-reviewers I have a question why the color of icon was not changing when I was using <img> tag to access icons defined in public/icons folder in the blade file?? Although I have defined a css class for this.

2021-09-17 04:23 UTC, GauravGusain98 requested changes
Please check the comments

2021-09-17 04:23 UTC, GauravGusain98 commented on public/icons/pause-circle.svg
> +<svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" fill="currentColor" class="bi bi-pause-circle" viewBox="0 0 16 16">
The width and height of the SVG should be 100%. This is because if we want to use the SVG at other places then we can use it by defining the width and height of the element in which SVG is loaded.

So just update the width and height to 100% at all svgs.

2021-09-17 04:23 UTC, GauravGusain98 commented on resources/views/hr/application/index.blade.php
> +                    {!! file_get_contents(public_path('icons/code.svg')) !!}
When using SVG with a width and height of 100%, you have to put this SVG inside an element and give that element width and height as per the requirement.

2021-09-17 04:23 UTC, GauravGusain98 commented on resources/js/app.js
> +if ( document.getElementById("list-styling") ){
I still think this can be handle with PHP. Could you please think and try again? If you still couldn't find a way then you can ask for help.

2021-09-18 07:05 UTC, srivastava-jyoti commented on resources/js/app.js
> +if ( document.getElementById("list-styling") ){
I still couldn't find a way to handle it at PHP level. Can @ColoredCow/team-portal-reviewers please help me out how to do this??

2021-09-18 09:34 UTC, GauravGusain98 commented on resources/js/app.js
> +if ( document.getElementById("list-styling") ){
I think we can connect on a call for this part.

2021-09-18 10:20 UTC, GauravGusain98 requested changes
Left some comments.

2021-09-18 10:20 UTC, GauravGusain98 commented on public/icons/pause-circle.svg
> +<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" class="bi bi-pause-circle" viewBox="0 0 16 16">
Correct this at all places
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" width="100%" height="100%" class="bi bi-pause-circle" viewBox="0 0 16 16">
```

2021-09-18 10:20 UTC, GauravGusain98 commented on resources/views/hr/application/index.blade.php
> +                    <svg class="job-application-icons">{!! file_get_contents(public_path('icons/pause-circle.svg')) !!}</svg>
```suggestion
                    <span class="job-application-icons">{!! file_get_contents(public_path('icons/pause-circle.svg')) !!}</span>
```

2021-09-18 10:20 UTC, GauravGusain98 commented on resources/views/hr/application/index.blade.php
> +                    <svg class="job-application-icons">{!! file_get_contents(public_path('icons/pause-circle.svg')) !!}</svg>
Correct this at all places

2021-09-20 04:07 UTC, GauravGusain98 requested changes
Please check the comments

2021-09-20 04:07 UTC, GauravGusain98 commented on resources/views/hr/application/index.blade.php
> +                <a class="{{ $status === config('constants.hr.status.on-hold.label') ? 'job-application-status' : '' }} btn" id="job-application-listings"
If you are adding the class using `$status === config('constants.hr.status.on-hold.label') ? 'job-application-status' : ''` logic then you should also use the same logic for the Trial program  i.e on line 61.

2021-09-20 04:07 UTC, GauravGusain98 commented on resources/views/hr/application/index.blade.php
> +                <a class="{{ $status === config('constants.hr.status.on-hold.label') ? 'job-application-status' : '' }} btn" id="job-application-listings"
Also please test this once after making the changes.

2021-09-20 04:07 UTC, GauravGusain98 commented on resources/sass/app.scss
> +	font-size: 20px;
we have a custom bootstrap class `fz-<size>` for this. You can also use that.

2021-09-20 17:44 UTC, GauravGusain98 requested changes
Please check the comments and make the following changes.

2021-09-20 17:44 UTC, GauravGusain98 commented on public/icons/people.svg
> +</svg>
please minify this file as well

2021-09-20 17:44 UTC, GauravGusain98 commented on resources/sass/app.scss
> +	color: rgb(77, 75, 75);
Please use Hex code instead of rgba.

2021-09-20 17:44 UTC, GauravGusain98 commented on resources/sass/app.scss
> +	color: #C4C4C4;
Same here

2021-09-20 17:44 UTC, GauravGusain98 commented on resources/views/hr/application/index.blade.php
> +                    <svg class="job-application-icons">{!! file_get_contents(public_path('icons/people.svg')) !!}</svg>
You cannot use svg tag outside an svg. Use span tag like this and make the design changes as the UI is getting changed by this.
```suggestion
                    <span class="d-block h-24 w-24 job-application-icons">{!! file_get_contents(public_path('icons/people.svg')) !!}</span>
```

2021-09-20 17:44 UTC, GauravGusain98 commented on public/icons/clipboard-check.svg
> +<svg xmlns="http://www.w3.org/2000/svg" fill="currentColor" class="bi bi-clipboard-check" viewBox="0 0 16 16"><path fill-rule="evenodd" d="M10.854 7.146a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708 0l-1.5-
Add width and height in all SVGs
```suggestion
<svg xmlns="http://www.w3.org/2000/svg" width="100%" height="100%" fill="currentColor" class="bi bi-clipboard-check" viewBox="0 0 16 16"><path fill-rule="evenodd" d="M10.854 7.146a.5.5 0 0 1 0 .708l-3 3a.5.5 0 0 1-.708 0l-1.5-1.5a.5.5 0 1 1 .708-.708L7.5 9.793l2.646-2.647a.5.5 0 0 1 .708 0z"/><path d="M4 1.5H3a2 2 0 0 0-2 2V14a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V3.5a2 2 0 0 0-2-2h-1v1h1a1 1 0 0 1 1 1V14a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1V3.5a1 1 0 0 1 1-1h1v-1z"/><path d="M9.5 1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-3a.5.5 0 0 1-.5-.5v-1a.5.5 0 0 1 .5-.5h3zm-3-1A1.5 1.5 0 0 0 5 1.5v1A1.5 1.5 0 0 0 6.5 4h3A1.5 1.5 0 0 0 11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3z"/></svg>
```

2021-09-21 02:03 UTC, srivastava-jyoti commented on resources/views/hr/application/index.blade.php
> +                    <svg class="job-application-icons">{!! file_get_contents(public_path('icons/people.svg')) !!}</svg>
@GauravGusain98 this is happening after using span class.
![Screenshot (108)](https://user-images.githubusercontent.com/79009032/134100916-a24f17d5-6e14-471b-bbb9-638f1ceb794e.png)

2021-09-21 05:25 UTC, srivastava-jyoti commented on resources/views/hr/application/index.blade.php
> +                    <svg class="job-application-icons">{!! file_get_contents(public_path('icons/people.svg')) !!}</svg>
This is sorted but, how to align the icons to the center. I tried using `align-items: center;` using span class but changes are not visible.
![Screenshot (109)](https://user-images.githubusercontent.com/79009032/134115999-637edb62-44b8-4c4e-b81e-83416e632d14.png)

2021-09-22 07:06 UTC, GauravGusain98 requested changes
Looks good. Minor changes

2021-09-22 07:06 UTC, GauravGusain98 commented on resources/views/hr/application/index.blade.php
> +                    <h5 class="toapprove">To Approve</h5>
Please correct the naming convention of class
```suggestion
                    <h5 class="to-approve">To Approve</h5>
```

2021-09-22 07:06 UTC, GauravGusain98 commented on resources/views/hr/application/index.blade.php
> +                    <h5 class="toapprove">To Approve</h5>
Also if it is not used anywhere, then you can remove it

2021-09-22 08:09 UTC, GauravGusain98 approved these changes
Looks good on code.

2021-09-22 09:28 UTC, merged