Feature/bootstrap/part/appointment slots
ColoredCow/portal pull request #974
Opened 2021-09-12 14:53 UTC by srivastava-jyoti

Target:#(911)

Description: To create UI for regulating maximum interviews to be taken by users on a particular day.

2021-09-13 17:43 UTC, kuldeep3 commented
@srivastava-jyoti Please resolve the conflicts and then assign it for review.

2021-09-15 04:02 UTC, GauravGusain98 requested changes
Please check the comments

2021-09-15 04:02 UTC, GauravGusain98 commented on resources/sass/app.scss
> +        font-size: 26px;
Indentation is not correct.

2021-09-15 04:03 UTC, GauravGusain98 commented
@kuldeep3 @P4NK4J  Could you please review this PR once?

2021-09-15 05:09 UTC, kuldeep3 requested changes
Please check can we directly use the bootstrap classes in the HTML instead of writing our own class. Moreover, please check if it is mobile responsive or not.

2021-09-15 05:09 UTC, kuldeep3 commented on Modules/user/Resources/views/user-settings/index.blade.php
> +<form action ="{{ route('user.settings') }}" method = "POST">
Leave a line above and check indentation.

2021-09-15 05:09 UTC, kuldeep3 commented on Modules/user/Resources/views/user-settings/index.blade.php
> +                        <a class="nav-link" href = "{{ route ('user.settings') }}">HR</a>
```suggestion
                        <a class="nav-link" href="{{ route ('user.settings') }}">HR</a>
```

2021-09-15 05:09 UTC, kuldeep3 commented on Modules/user/Resources/views/user-settings/index.blade.php
> +                <input type="number" class="quantity" id="quantity" name="max_interviews_per_day" min="0" max="4" value="{{ old ('max_interviews_per_day', optional(Auth::user()->meta)->max_interviews
Indentation.

2021-09-15 05:09 UTC, kuldeep3 commented on Modules/user/Resources/views/user-settings/index.blade.php
> +</div>
Indentation

2021-09-19 13:04 UTC, srivastava-jyoti commented
This is how the page is looking in a phone.
![Screenshot (105)](https://user-images.githubusercontent.com/79009032/133928559-7e54fda8-2a53-4a91-913f-109802ab0e49.png)

2021-09-20 17:23 UTC, GauravGusain98 requested changes
Please make the requested changes.

2021-09-20 17:23 UTC, GauravGusain98 commented on Modules/user/Resources/views/user-settings/index.blade.php
> +        <div class=".col-6 .offset-md-3">
`.` is not used inside class attribute. Please make these changes and also check if the UI is affected due to this change or not.
```suggestion
        <div class="col-6 offset-md-3">
```

2021-09-20 17:23 UTC, GauravGusain98 commented on Modules/user/Resources/views/user-settings/index.blade.php
> +            <label class="user-settings" style="font-size:24px;">User Settings</label>
Don't use style inside blade file. We have a class `fz-<size>` for font size. You can use that. Please remove style attribute from other places as well

2021-09-20 17:23 UTC, GauravGusain98 commented on resources/sass/app.scss
> + 	font-family: Mulish;
we have bootstrap classes for these. You can use them at the place where you are using `.quantity` class

2021-09-20 17:23 UTC, GauravGusain98 commented on resources/sass/app.scss
> +        outline: none;
you can use bootstrap class for this.

2021-09-20 17:23 UTC, GauravGusain98 commented on resources/sass/app.scss
> +	color: #969281;
Can you change the name of this class to a meaningful name.

2021-09-21 06:13 UTC, srivastava-jyoti commented on Modules/user/Resources/views/user-settings/index.blade.php
> +        <div class=".col-6 .offset-md-3">
Removing dots from div are affecting UI

2021-09-21 13:07 UTC, GauravGusain98 commented on Modules/user/Resources/views/user-settings/index.blade.php
> +        <div class=".col-6 .offset-md-3">
Then remove both classes as they are not being used

2021-09-21 13:09 UTC, GauravGusain98 requested changes
Looks good. Just some minor changes are required. Please make those changes.

2021-09-21 16:12 UTC, GauravGusain98 approved these changes
Looks good

2021-09-21 16:12 UTC, GauravGusain98 commented
@srivastava-jyoti  Please fix the merge conflict

2021-09-22 07:07 UTC, GauravGusain98 commented
@kuldeep3 can you review this PR.

2021-09-22 10:07 UTC, GauravGusain98 commented
@srivastava-jyoti Can you please re-request the review to Kuldeep?

2021-09-22 10:36 UTC, srivastava-jyoti commented
@GauravGusain98  Okay.

2021-09-22 17:17 UTC, kuldeep3 requested changes

2021-09-22 17:17 UTC, kuldeep3 commented on Modules/user/Resources/views/user-settings/index.blade.php
> +</div>
Check indentation.

2021-09-22 17:17 UTC, kuldeep3 commented on resources/sass/app.scss
>  	margin: auto;
Check Indentation.

2021-09-22 17:17 UTC, kuldeep3 commented on resources/sass/app.scss
> +
Can we define these as variables, and then use that variable here?

2021-09-22 17:17 UTC, kuldeep3 commented on resources/sass/app.scss
>  	background-color:#F3F2EC;
Same here...define that in variables and use them here.

2021-09-23 08:05 UTC, srivastava-jyoti commented on resources/sass/app.scss
>  	background-color:#F3F2EC;
I am not able to access sizes from variables.scss

2021-09-24 06:27 UTC, srivastava-jyoti commented on resources/sass/app.scss
>  	background-color:#F3F2EC;
There is no class defined for top in variable.scss. So, I am using this one.

2021-09-28 15:34 UTC, kuldeep3 requested changes

2021-09-28 15:34 UTC, kuldeep3 commented on resources/sass/app.scss
>  	margin: auto;
I still see some formatting issues. Please fix these. rest all looks good to me.

2021-09-29 03:21 UTC, srivastava-jyoti commented on resources/sass/app.scss
>  	margin: auto;
There should 8 spaces indentation and it's there. I am not able to find formatting mistakes
![Screenshot (123)](https://user-images.githubusercontent.com/79009032/135197612-45dcb08e-b90d-4bb9-8299-f366495939c0.png)
.

2021-09-29 04:33 UTC, kuldeep3 commented on resources/sass/app.scss
>  	margin: auto;
I see this which is not appropriate. You need to reduce the extra indentation in `width: 20px`

<img width="322" alt="Screenshot 2021-09-29 at 9 56 47 AM" src="https://user-images.githubusercontent.com/37093310/135203478-f5a589e4-ced1-490e-9650-298f308710bf.png">

2021-09-29 04:33 UTC, kuldeep3 commented on resources/sass/app.scss
> +        box-shadow: 0 2px 6px rgba(44, 42, 44, 0.04);
Reduce extra indentation.

2021-09-29 06:37 UTC, srivastava-jyoti commented on resources/sass/app.scss
>  	margin: auto;
Sorry, but still these formatting issues are not visible to be me neither on the app.scss file uploaded on github by me nor on my local. There is 4 spaces indentation on my local and 8 spaces on gihub.
![Screenshot (129)](https://user-images.githubusercontent.com/79009032/135215739-3c225e52-ac26-471b-8920-693e6fc65891.png)
![Screenshot (131)](https://user-images.githubusercontent.com/79009032/135215755-1aac35a6-6d01-4879-8878-f3f72a6d9d09.png)

2021-09-29 06:38 UTC, srivastava-jyoti commented on resources/sass/app.scss
> +        box-shadow: 0 2px 6px rgba(44, 42, 44, 0.04);
Same here.
![Screenshot (132)](https://user-images.githubusercontent.com/79009032/135215974-73e265bf-04a8-409a-b073-132d3bc38bd6.png)

2021-09-30 04:17 UTC, GauravGusain98 commented on resources/sass/app.scss
>  	margin: auto;
I am also able to see the extra indentation @srivastava-jyoti. You can use 4 spaces instead of giving a tab and then try.
![image](https://user-images.githubusercontent.com/54376313/135386152-98c4da57-6803-47f1-b672-5b028619cc63.png)

2021-09-30 16:59 UTC, P4NK4J commented on Modules/user/Resources/views/user-settings/index.blade.php
> +<form action ="{{ route('user.settings') }}" method = "POST">
```suggestion
<form action="{{ route('user.settings') }}" method="POST">
```

2021-09-30 16:59 UTC, P4NK4J approved these changes
Minor suggestion else looks good.

2021-09-30 17:01 UTC, kuldeep3 approved these changes

2021-09-30 17:12 UTC, merged