Fixed issues related to environment variables
ColoredCow/portal pull request #978
Opened 2021-09-14 08:02 UTC by GauravGusain98

Targets #917 

### Description

- Fetching the environment variables from config instead of env file
- Corrected some coding conventions

### Checklist:

- [x] I have performed a self-review of my own code.

2021-09-15 05:04 UTC, kuldeep3 requested changes

2021-09-15 05:04 UTC, kuldeep3 commented on app/Listeners/RemoveUserFromWebsite.php
> +            return;
Why this check is called two times?

```
if (! $wpUser) {
    return;
}
```

2021-09-15 05:33 UTC, GauravGusain98 commented on app/Listeners/RemoveUserFromWebsite.php
> +            return;
I think the second check should be for admin. Let me correct it.

2021-09-16 04:31 UTC, kuldeep3 approved these changes
Looks good on code ⚡

2021-09-16 05:11 UTC, merged