The symbol is removed while downloading
ColoredCow/portal pull request #980
Opened 2021-09-14 10:58 UTC by kickb71

This PR contains the solution for the removal of currency signs from excel downloaded from monthly tax reports.
Issue #954

2021-09-15 18:08 UTC, GauravGusain98 approved these changes
Looks good

2021-09-16 10:43 UTC, kuldeep3 requested changes

2021-09-16 10:43 UTC, kuldeep3 commented on Modules/Invoice/Services/InvoiceService.php
>                  'Received amount' => $invoice->amount_paid,
Can we access `$invoice->amount`, instead of firstly fetching `$invoice->display_amount` (that comes with currency symbol) and then removing the currency symbol.

2021-09-16 11:34 UTC, kickb71 commented on Modules/Invoice/Services/InvoiceService.php
>                  'Received amount' => $invoice->amount_paid,
```InvoiceAmount()``` comes with the GST added so the value will change if add the ```$invoice->display_amount```

2021-09-16 12:20 UTC, GauravGusain98 requested changes

2021-09-16 12:20 UTC, GauravGusain98 commented on Modules/Invoice/Services/InvoiceService.php
>                  'Received amount' => $invoice->amount_paid,
@kickb71 Can you check the logic of how `diplay_name` is calculated and how it is different from the `$invoice->amount`. If the value are same then you can use `$invoice->amount`. 
You can find the logic in this file `Modules/Invoice/Entities/Invoice.php`

2021-09-17 07:41 UTC, GauravGusain98 commented on Modules/Invoice/Services/CurrencyService.php
> +        return round($data, 2);
What are these changes for?

2021-09-17 08:11 UTC, kickb71 commented on Modules/Invoice/Services/CurrencyService.php
> +        return round($data, 2);
If I go into in finance module I get the error that's why I removed a temp fix.I have created a issue for this

2021-09-18 10:44 UTC, GauravGusain98 requested changes
Some Minor fixes. @kuldeep3 Could you please check this PR once?

2021-09-18 10:44 UTC, GauravGusain98 commented on Modules/Invoice/Services/InvoiceService.php
> +                'Amount' =>  $invoice->amount,
```suggestion
                'Amount' => $invoice->amount,
```

2021-09-20 04:12 UTC, GauravGusain98 approved these changes
Looks good. Just remove the space on line 208.

2021-09-20 05:31 UTC, gautam071 commented
> Looks good. Just remove the space on line 208.

@GauravGusain98 Can U merge this PR after the monthly tax PR.

2021-09-21 04:07 UTC, GauravGusain98 commented
> > Looks good. Just remove the space on line 208.
> 
> @GauravGusain98 Can U merge this PR after the monthly tax PR.

Sure. Just remember to make the change I requested in this [comment](https://github.com/ColoredCow/portal/pull/980#pullrequestreview-758242193)

2021-09-21 05:54 UTC, gautam071 commented
> > > Looks good. Just remove the space on line 208.
> > 
> > 
> > @GauravGusain98 Can U merge this PR after the monthly tax PR.
> 
> Sure. Just remember to make the change I requested in this [comment](https://github.com/ColoredCow/portal/pull/980#pullrequestreview-758242193)

Changed the indentation error

2021-09-21 13:11 UTC, GauravGusain98 commented
@kuldeep3 Can you review this PR?

2021-09-21 16:32 UTC, kuldeep3 requested changes

2021-09-21 16:32 UTC, kuldeep3 commented on Modules/Invoice/Services/InvoiceService.php
> +                'Amount (+GST)' => (float) str_replace(['$', '₹'], '', $invoice->invoiceAmount()),
```suggestion
                'Amount (+GST)' => $invoice->amount + $invoice->gst,
```

Can you once try this suggestion and compare the result.

2021-09-21 16:37 UTC, gautam071 commented on Modules/Invoice/Services/InvoiceService.php
> +                'Amount (+GST)' => (float) str_replace(['$', '₹'], '', $invoice->invoiceAmount()),
Sure

2021-09-21 16:43 UTC, gautam071 commented on Modules/Invoice/Services/InvoiceService.php
> +                'Amount (+GST)' => (float) str_replace(['$', '₹'], '', $invoice->invoiceAmount()),
It works but it is used in multiple places should I changed it everywhere. But the code will be repeated

2021-09-21 16:44 UTC, GauravGusain98 commented on Modules/Invoice/Services/InvoiceService.php
> +                'Amount (+GST)' => (float) str_replace(['$', '₹'], '', $invoice->invoiceAmount()),
Just use it here only for now.

2021-09-21 18:14 UTC, GauravGusain98 commented on Modules/Invoice/Services/InvoiceService.php
> +                'Amount' =>  $invoice->amount,
Why this change showing again?

2021-09-21 18:16 UTC, GauravGusain98 commented on Modules/Invoice/Services/InvoiceService.php
> +                'Amount (+GST)' => (float) str_replace(['$', '₹'], '', $invoice->amount + $invoice->gst),
I don't think Kuldeep told you to change it like this. Why you are using str_replace now? There will be no symbol now as you are just adding two numbers.

2021-09-21 18:18 UTC, gautam071 commented on Modules/Invoice/Services/InvoiceService.php
> +                'Amount (+GST)' => (float) str_replace(['$', '₹'], '', $invoice->amount + $invoice->gst),
because the method @kuldeep3 mentioned is coming with the rupee or roller symbols

2021-09-21 18:21 UTC, GauravGusain98 commented on Modules/Invoice/Services/InvoiceService.php
> +                'Amount (+GST)' => (float) str_replace(['$', '₹'], '', $invoice->amount + $invoice->gst),
I don't think ` $invoice->amount + $invoice->gst` will return symbol. As they both are numbers. Can you please check again

2021-09-21 18:21 UTC, GauravGusain98 commented on Modules/Invoice/Services/InvoiceService.php
> +                'Amount (+GST)' => (float) str_replace(['$', '₹'], '', $invoice->amount + $invoice->gst),
The whole point of using `$invoice->amount + $invoice->gst` was to remove the extra function i.e `str_replace` which is being used.

2021-09-21 18:22 UTC, gautam071 commented on Modules/Invoice/Services/InvoiceService.php
> +                'Amount (+GST)' => (float) str_replace(['$', '₹'], '', $invoice->amount + $invoice->gst),
because GST has a symbol i have tried that too then only I added the str replace

2021-09-22 04:30 UTC, GauravGusain98 commented on Modules/Invoice/Services/InvoiceService.php
> +                'Amount (+GST)' => (float) str_replace(['$', '₹'], '', $invoice->amount + $invoice->gst),
@kuldeep3 do you have any questions about it?

2021-09-22 05:42 UTC, kuldeep3 commented on Modules/Invoice/Services/InvoiceService.php
> +                'Amount (+GST)' => (float) str_replace(['$', '₹'], '', $invoice->amount + $invoice->gst),
@gautam071 So, are you saying that we are saving GST with a symbol on our database? If this is the case, I think we need to fix that too.

2021-09-22 05:53 UTC, gautam071 commented on Modules/Invoice/Services/InvoiceService.php
> +                'Amount (+GST)' => (float) str_replace(['$', '₹'], '', $invoice->amount + $invoice->gst),
Yeah, But the symbol need to be displayed in the webpage

2021-09-22 16:24 UTC, kuldeep3 commented on Modules/Invoice/Services/InvoiceService.php
> +                'Amount (+GST)' => (float) str_replace(['$', '₹'], '', $invoice->amount + $invoice->gst),
Ok, please revert it to the original one, i.e. ` (float) str_replace(['$', '₹'], '', $invoice->invoiceAmount()),`

2021-09-22 17:13 UTC, GauravGusain98 commented on Modules/Invoice/Services/InvoiceService.php
> +                'Amount (+GST)' => (float) str_replace(['$', '₹'], '', $invoice->amount + $invoice->gst),
@gautam071 Please make the changes Kuldeep has suggested.

2021-09-22 17:57 UTC, kuldeep3 approved these changes

2021-09-22 17:57 UTC, merged