All the TDS are rounded to 2 decimal poimts
ColoredCow/portal pull request #987
Opened 2021-09-15 08:57 UTC by kickb71

The TDS values are rounded to 2 decimal points in the monthly tax report

2021-09-18 10:04 UTC, GauravGusain98 requested changes
Please check the comments and also please link the issue id in the description. I am not able to find the issue for which this PR is made.

2021-09-18 10:04 UTC, GauravGusain98 commented on Modules/Invoice/Resources/views/tax-report.blade.php
> +                        @endif
same as above

2021-09-18 10:04 UTC, GauravGusain98 commented on Modules/Invoice/Resources/views/tax-report.blade.php
> +                        @endif
same here

2021-09-18 10:04 UTC, GauravGusain98 commented on Modules/Invoice/Services/InvoiceService.php
> +                'TDS' => number_format((float) ($invoice->tds), 2),
Why these changes are here?

2021-09-21 04:18 UTC, GauravGusain98 commented
@gautam071 Please check the comments and resolve the merge conflicts.

2021-09-21 07:28 UTC, gautam071 commented on Modules/Invoice/Resources/views/index.blade.php
> +                    @endif
This is not in this file i will change in that file

2021-09-21 16:18 UTC, GauravGusain98 commented
The merge conflicts are not yet resolved.

2021-09-21 16:20 UTC, gautam071 commented
> The merge conflicts are not yet resolved.

the conflicts are resolved

2021-09-22 18:15 UTC, GauravGusain98 approved these changes
Looks good

2021-09-22 18:20 UTC, merged