Solved the error showing in the console
ColoredCow/portal pull request #991
Opened 2021-09-15 17:10 UTC by kickb71

Targets #990 

### Description
This PR solved the value error that is showing in the console.

### Checklist:

- [ ] I have performed a self-review of my own code.

2021-09-15 18:16 UTC, GauravGusain98 requested changes
Please check the comments

2021-09-15 18:16 UTC, GauravGusain98 commented on resources/views/hr/recruitment/reports.blade.php
> +                <div class="card-body chartdata" data-target="{{ $chartData }}" >
```suggestion
                <div class="card-body chart-data" data-target="{{ $chartData }}" >
```

2021-09-15 18:16 UTC, GauravGusain98 commented on resources/js/app.js
> +	  if (value != null) {
If you are taking value inside the lineChart() function, then why are you passing it from the blade file? You can use an id or a class to make sure that this code will run only on a particular page.

2021-09-16 04:27 UTC, kickb71 commented on resources/js/app.js
> +	  if (value != null) {
Can you go through the issue because that's what causing the error on all other pages?

2021-09-16 05:04 UTC, GauravGusain98 commented on resources/js/app.js
> +	var value = $(".chartdata").data("target");
correct the indentation here

2021-09-16 05:06 UTC, GauravGusain98 commented on resources/js/app.js
> +	  if (value != null) {
Yes you're correct, if the value variable is not present in any screen then it will throw an error. 

I was saying to not pass the value variable from the blade file as it is not being used anywhere except in the `if` condition. If you need to use the if condition you can do it using any className or id Name instead of a variable i.e `value`.

2021-09-16 05:07 UTC, GauravGusain98 commented on resources/js/app.js
> +	  if (value != null) {
Let me know if there is any doubt.

2021-09-16 05:08 UTC, GauravGusain98 commented on resources/js/app.js
> +	  if (value != null) {
You can simply use
```suggestion
	  if ($(.chart-data)) {
```

2021-09-16 05:32 UTC, kickb71 commented on resources/js/app.js
> +	  if (value != null) {
I don't know this throws an error or not but using if with chart data will work

2021-09-16 05:33 UTC, kickb71 commented on resources/js/app.js
> +	  if (value != null) {
But I think it still throws the value undefined error

2021-09-16 05:34 UTC, kickb71 commented on resources/js/app.js
> +	  if (value != null) {
I have run it it still throws the error

2021-09-16 05:35 UTC, kickb71 commented on resources/js/app.js
> +	var value = $(".chartdata").data("target");
I have corrected it

2021-09-16 06:05 UTC, GauravGusain98 commented on resources/js/app.js
> +	  if (value != null) {
Ohh I forgot use length function. Try this
```js
if ($(".chart-data").length) {

2021-09-16 06:05 UTC, GauravGusain98 commented on resources/js/app.js
> +	  if (value != null) {
Also, remove the value variable from the blade file and test the functionality once.

2021-09-16 06:08 UTC, GauravGusain98 commented
@kickb71  Can you also correct the indentation from lines 67 to 112.

2021-09-16 07:23 UTC, GauravGusain98 requested changes
Everything is fine. Just make this change.

2021-09-16 07:23 UTC, GauravGusain98 commented on resources/js/app.js
> +	}
```suggestion
	if ($(".chart-data").length) {
		datePickerChart();
		lineChart();
	}
```

2021-09-16 07:42 UTC, kickb71 commented on resources/js/app.js
> +	}
Okay let me change

2021-09-16 07:42 UTC, kickb71 commented on resources/js/app.js
> +	}
But the chart is not working

2021-09-16 07:43 UTC, kickb71 commented on resources/js/app.js
> +	}
after removing the value

2021-09-16 07:54 UTC, kickb71 commented on resources/js/app.js
> +	}
That works let me make a Commit

2021-09-16 08:02 UTC, GauravGusain98 commented
@kickb71  can you also remove the `<body>` tag from this `resources/views/hr/recruitment/reports.blade.php` file. We don't use a body tag inside the blade file as it is already included in the `app.blade.php` PHP file.

2021-09-16 08:02 UTC, kickb71 commented on resources/js/app.js
> +	  if (value != null) {
I have added it works perfectly

2021-09-16 08:03 UTC, kickb71 commented
> @kickb71 can you also remove the `<body>` tag from this `resources/views/hr/recruitment/reports.blade.php` file. We don't use a body tag inside the blade file as it is already included in the `app.blade.php` PHP file.

Sure let me remove it

2021-09-16 10:30 UTC, rathorevaibhav approved these changes

2021-09-16 10:50 UTC, GauravGusain98 requested changes
One minor feedback. Please make the changes.

2021-09-16 10:50 UTC, GauravGusain98 commented on resources/views/hr/recruitment/reports.blade.php
> +                <span class="chartHeading">Application Received</span> &emsp;&emsp; <span class="totalChartCount">Today's Count:<?php echo $todayCount ?></span>
You should use same naming convention for class. Please correct this at all places where this class is being used
```suggestion
                <span class="chart-heading">Application Received</span> &emsp;&emsp; <span class="totalChartCount">Today's Count:<?php echo $todayCount ?></span>
```

2021-09-16 10:54 UTC, kickb71 commented on resources/views/hr/recruitment/reports.blade.php
> +                <span class="chartHeading">Application Received</span> &emsp;&emsp; <span class="totalChartCount">Today's Count:<?php echo $todayCount ?></span>
Every where it is changed as per request

2021-09-16 11:00 UTC, GauravGusain98 approved these changes
Looks good to me

2021-09-16 11:12 UTC, kuldeep3 requested changes

2021-09-16 11:12 UTC, kuldeep3 commented on resources/views/hr/recruitment/reports.blade.php
> +            <input type="date" name="from" id='StartDate'> to
```suggestion
            <input type="date" name="report_start_date" id='StartDate'> to
```

2021-09-16 11:12 UTC, kuldeep3 commented on resources/views/hr/recruitment/reports.blade.php
> +            <input type="date" name="to" id="EndDate">
```suggestion
            <input type="date" name="report_end_date" id="EndDate">
```

2021-09-16 11:12 UTC, kuldeep3 commented on resources/views/hr/recruitment/reports.blade.php
> +                <span class="chart-heading">Application Received</span> &emsp;&emsp; <span class="total-chart-count">Today's Count:<?php echo $todayCount ?></span>
```suggestion
                <span class="chart-heading">Application Received</span><span class="total-chart-count">Today's Count:<?php echo $todayCount; ?></span>
```

2021-09-16 11:12 UTC, kuldeep3 commented on resources/views/hr/recruitment/reports.blade.php
> +                <span class="chart-heading">Application Received</span> &emsp;&emsp; <span class="total-chart-count">Today's Count:<?php echo $todayCount ?></span>
Can we use margin instead of `&emsp;&emsp;`?

2021-09-16 11:30 UTC, kickb71 commented on resources/views/hr/recruitment/reports.blade.php
> +                <span class="chart-heading">Application Received</span> &emsp;&emsp; <span class="total-chart-count">Today's Count:<?php echo $todayCount ?></span>
The &emsp; is used for the text in the header of the chart to move the textaway. I don't know how to use margin for movement of text

2021-09-16 12:08 UTC, GauravGusain98 requested changes

2021-09-16 12:08 UTC, GauravGusain98 commented on resources/views/hr/recruitment/reports.blade.php
> +            <input type="date" name="report_end_date" id="EndDate">
You also need to update the name in the `Modules/HR/Http/Controllers/Recruitment/ReportsController.php` file.

2021-09-16 12:09 UTC, GauravGusain98 commented on resources/views/hr/recruitment/reports.blade.php
> +                <span class="chart-heading">Application Received</span> &emsp;&emsp; <span class="total-chart-count">Today's Count:<?php echo $todayCount ?></span>
@kickb71 Kuldeep is trying to say that you can use the margin class that bootstrap provide instead of using `&emsp`

2021-09-16 12:09 UTC, kickb71 commented on resources/views/hr/recruitment/reports.blade.php
> +            <input type="date" name="to" id="EndDate">
Okay

2021-09-16 12:09 UTC, kickb71 commented on resources/views/hr/recruitment/reports.blade.php
> +            <input type="date" name="from" id='StartDate'> to
Okay

2021-09-16 12:13 UTC, kickb71 commented on resources/views/hr/recruitment/reports.blade.php
> +            <input type="date" name="report_end_date" id="EndDate">
Yes. I forgot it is changed now

2021-09-16 12:23 UTC, GauravGusain98 commented on resources/views/hr/recruitment/reports.blade.php
> +                <span class="chart-heading">Application Received</span> &emsp;&emsp; <span class="total-chart-count">Today's Count:<?php echo $todayCount ?></span>
Can you make this change as well?

2021-09-16 13:05 UTC, GauravGusain98 commented
@kickb71  I don't see the changes requested in this comment. https://github.com/ColoredCow/portal/pull/991/files#discussion_r710065206

2021-09-16 13:09 UTC, kickb71 commented
> @kickb71 I don't see the changes requested in this comment. https://github.com/ColoredCow/portal/pull/991/files#discussion_r710065206

I can see the changes the first change is that change

2021-09-16 13:18 UTC, kickb71 commented on resources/views/hr/recruitment/reports.blade.php
> +                <span class="chart-heading">Application Received</span> &emsp;&emsp; <span class="total-chart-count">Today's Count:<?php echo $todayCount ?></span>
May I know what's wrong with ```&emsp;``` and why do I need to change

2021-09-16 14:27 UTC, GauravGusain98 requested changes
Please make the requested changes

2021-09-16 14:27 UTC, GauravGusain98 commented on app/Http/Controllers/Settings/FinanceController.php
> +}
Why these changes are here?

2021-09-16 14:27 UTC, GauravGusain98 commented on resources/views/settings/finance/index.blade.php
> +</div>
Remove these changes if they don't belong to this issue.

2021-09-16 14:27 UTC, GauravGusain98 commented on resources/views/hr/recruitment/reports.blade.php
> +                <span class="chart-heading">Application Received</span><span class="total-chart-count">Today's Count:<?php echo $todayCount ?></span>
You need to add the margin class that Bootstrap provides to add a margin between the text. 
Check how to add margin in an element.

2021-09-16 14:37 UTC, GauravGusain98 approved these changes
Looks Good

2021-09-16 14:42 UTC, rathorevaibhav approved these changes

2021-09-16 14:52 UTC, kuldeep3 approved these changes

2021-09-16 14:53 UTC, merged