Update prerequisites.md
ColoredCow/portal pull request #994
Opened 2021-09-16 05:53 UTC by rathorevaibhav

Targets #{ISSUE_ID}

### Description

### Checklist:

- [ ] I have performed a self-review of my own code.

2021-09-17 13:19 UTC, P4NK4J commented on docs/installation.md
> +
@kickb71 I think the statement seems missing, I was able to interpret that we need to add something in the hosts file, but exactly what to add, I could not figure out. Let me know your thoughts.

2021-09-17 13:21 UTC, P4NK4J reviewed
Left a comment, please check

2021-09-17 16:00 UTC, kickb71 commented on docs/installation.md
> +
I like to add  some comments there to 
May be the description of the host why is it there or may be what's the use of it 
May be the another way to access these files without the terminal file location

2021-09-21 13:16 UTC, GauravGusain98 requested changes
Looks good, need some minor changes.

2021-09-21 13:16 UTC, GauravGusain98 commented on docs/installation.md
> +            ```
Please correct the indentation

2021-09-21 13:16 UTC, GauravGusain98 commented on docs/installation.md
> +            ```
Can you also correct the indentation on line 76 to 78

2021-09-21 13:44 UTC, gautam071 commented on docs/installation.md
> +            ```
Yea Sure

2021-09-22 08:12 UTC, GauravGusain98 requested changes
Please remove extra changes from this PR

2021-09-22 08:12 UTC, GauravGusain98 commented on Modules/HR/Http/Controllers/Recruitment/ReportsController.php
> +            ->where('created_at', '<=', $req->report_end_date)
remove these changes from this PR.

2021-09-22 08:41 UTC, gautam071 commented on Modules/HR/Http/Controllers/Recruitment/ReportsController.php
> +            ->where('created_at', '<=', $req->report_end_date)
Removed

2021-09-22 08:43 UTC, GauravGusain98 approved these changes
Looks good

2021-09-22 08:43 UTC, merged